### ISSUE TITLE
Experimental Design [Building Icon for, for-profit colleges]

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/vets-design-system-documentation#1018]
## What
> A building icon to represent for-profit institution ownership.

## Purpose
> This will provide the veteran an icon to identify the option to view the ownership of a for-profit school?

## Usage
> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.

## Behavior
> Used to identify for-profit ownership.

## Examples
![image](https://user-images.githubusercontent.com/104099521/176916627-c06c7c87-6e52-47a3-9d89-207db2373bbb.png)

## Accessibility
> Include any accessibility considerations.

## Guidance
> A building design similar to the provided sample acceptable as well.

## Research (optional)
> N/A

## Code (optional)
> N/A.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
@MitchLivingstone - The Design System and VA.gov use the FontAwesome iconography set. There are a number of buildings to choose from: https://fontawesome.com/search?q=building&s=solid  Note however that we have an older version of the library and thus only have access to the freely available solid icons. Our current set of documented icons are here: https://design.va.gov/foundation/icons We don't have a building called out there yet so if you want to suggest one from the FontAwesome set that would be fine.

**Comment by MitchLivingstone** [comment]
Thank you for the quick reply. I will touch base with my stakeholders for them to pick a building from FontAwesome to move forward with. I will keep you posted, thank you very much.

**Comment by MitchLivingstone** [comment]
Good Afternoon, 
 
Can we please move forward with approval for the selected icon? It's listed as "School Flag" If any further information is needed please let me know. 

![image](https://user-images.githubusercontent.com/104099521/179053494-06fece93-fb85-4b70-97a5-48775e7948ca.png)

**Comment by caw310** [comment]
@humancompanion-usds @GnatalieH , tagging you both to give feedback.

**Comment by humancompanion-usds** [comment]
@MitchLivingstone - Sorry, I left out an important detail and steered you wrong. My apologies. We only have version 5.15.4 thus you have to filter when you search the icons by that version. Unfortunately, school-flag was added in v6 and we have not upgraded yet. 

There is a building in v5 that is very close to the example you originally provided. Would that work?
https://fontawesome.com/v5/icons/building?s=solid

**Comment by MitchLivingstone** [comment]
Not a problem. I will update that to my Stakeholders and we will take it from there. I appreciate you getting back to me so quickly.

**Comment by MitchLivingstone** [comment]
@humancompanion-usds ,

Thanks again for the follow-up. Our stakeholders are okay with moving forward with the suggested building you have recommended. Please let me know if anything further is needed. 

https://fontawesome.com/v5/icons/building?s=solid

**Comment by caw310** [comment]
Closing since this has been resolved.

**Comment by MitchLivingstone** [comment]
Can the Icon be used without going through any other processes?

**Comment by caw310** [comment]
@MitchLivingstone yes it can be used without going through any other processes. Thanks.

**Comment by MitchLivingstone** [comment]
Thank you.
