### ISSUE TITLE
Rework IA of Patterns

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1038]
The current information architecture of the Patterns section isn't clear and is actually making it difficult to determine both how to craft the pattern to be most helpful to users of the system and for the DST to decide what is, and what is not, a pattern. There are not many great examples of a model or structure for Patterns out there. But the ones that are not a grab bag are aligned around user needs. That includes even going into the way back machine and looking at the IA of the old Yahoo Pattern Library:

#### User needs to...
* Search
* Navigation
* Browsing
* Selection
* Rich interaction
* Social

Those labels are not a consistent end to a sentence but, it is an organizing principle. The gov.uk and NHS systems also take this pattern. They use "Ask users for..." and "Help users to...". This is a useful construct that moves us away from authoring and organizing our patterns around the UI or as instructions to a designer and/or developer that are more general and moves us toward a specific user goal. I think it would also reorganize our patterns in a way that allows us to grow the system more readily in a logical way.

Here is how our patterns would be reorganized:

## Ask users for…

- Addresses (Patterns > Forms > Contact information#addresses)
- Email addresses (Patterns > Forms > Contact information#email-addresses)
- Dates (Patterns > Forms > Dates)
- Direct Deposit (Patterns > Forms > Direct Deposit) - should this be Bank Details?
- Feedback (Patterns > Feedback)
- Gender (Patterns > Forms > Applicant information#gender)
- Method of contact (Patterns > Forms > Contact information#method-of-contact)
- Name (Patterns > Form s> Applicant information#name)
- Phone numbers (Patterns > Forms > Contact information#phone-numbers)
- Race, ethnicity, or origin (Patterns > Forms > Applicant information#race) - should this be Equality information?
- Service history (Patterns > Forms > Service history)
- Signature (Patterns > Forms > Signature)
- Social Security number (Patterns > Forms > Applicant information#important-numbers-social-security-number--va-file-number)
- VA file number (Patterns > Forms > Applicant information#important-numbers-social-security-number--va-file-number)

## Help users to…

- **Change language**
- **Check a service is suitable** (currently Patterns > Wizard but will build on the Eligibility section of Patterns > Benefit applications and use various benefit application examples and point to “One Thing per Page” which I need to name)
- **Check answers** (Patterns > Forms > Review) - Not new but woefully out of date
- Check personal information (Patterns > Authenticated info list)
- Confirm an application (Patterns > Forms > Confirmation)
- **Confirm an email address** - This came up in CollabCycle recently and is a pattern in other systems
- Navigate a long list (Patterns > Show more options)
- Navigate benefit applications (Patterns > Benefit applications)
- **Prepare for site maintenance** (Draft pattern in Patterns > Sitewide banners that Ryan started) - Could also be named “Prepare for a service to be unavailable”
- **Prepare to visit a VA facility** - Perhaps this could cover check-in and COVID alerts? This might be a bit of a stretch, but we need to relate information on different Alert and Banner levels.
- Provide a mutually exclusive answer (Patterns > Forms > All of none of the above)
- Provide multiple responses (Patterns > Forms > List and Loop)
- Recover from an error (Patterns > Error messages style guide) - Working on reformatting this one now
- **Sign in with less friction** - LoROTA (low auth, low risk) pattern from Stephen Barrs & co.
- Upload files (Patterns > Forms > File upload)

**Bold patterns** are recommended patterns to add. 

## Remove from Patterns

- Content presentation - This is advice on how to choose a component and it’s fairly brief. Thus we can share/repeat this guidance in the 3 components (featured content, accordion, additional info) that need it.

## Verbs

Here are the verbs that the gov.UK and their NHS system use:

* UK: change, check, confirm, contact, create, navigate, start, recover
* NHS: access, change, correct, download, extend, find, save, send

Here are the verbs we would use:
* VA: change, check, confirm, navigate, prepare, provide, recover, sign in, upload

Would love feedback on this from any or all of: @DanielleThierryUSDSVA, @bethpotts, @mnorthuis, @jimuhh, @GnatalieH, @seanasewell, @KevinMHoffmanUSDS

**Comment by humancompanion-usds** [comment]
If we agree this is a good model and where we want to go I've got a few immediate tasks to get us there:

* [ ] Replace the sidenav component in the Pattern layout so that we can have those sub-headers (and not use accordions)
* [ ] Rename the Patterns (we could initially just rename their titles, keep the URLs the same, and have the sidenav use the titles)

**Comment by humancompanion-usds** [comment]
This update does not solve for “One Thing per Page”. The UK puts that under Design Principles which are in their Service Manual documentation, a distinct site from their design system. I do have a place for Design Principles in our Component template but stupidly did not put it in the Pattern template. Thus I'll fix that when I write "Check a service is suitable". 

The other use case I was struggling to fit in is a pattern to cover all of the less than critical informational alerts we throw at users, especially hurricane warnings. Most of the alerts would fall under the "Help users to prepare to visit a VA facility" pattern (COVID warnings about visitation, masking policy, and other safety precautions; construction, temporary closure or changes to hours; active threat training). Hurricane warnings sometimes include links to how it changes the visitation policy for that facility, but not always. At any rate, I think I'm going to group it under that pattern and write up an example that includes that visitation policy change as the reason.

**Comment by jimuhh** [comment]
@humancompanion-usds 
Wondering about the user testing that went into this schema? I know that UK.gov is generally very good about that but curious how this performed with technically savvy web people? I'd be particularly interested in how time on task compared to the standard layout. 
I'm asking because of a Nielsen/Norman article called, **[Use Specialized Language for Specialized Audiences](https://www.nngroup.com/articles/specialized-words-specialized-audience/)** that says putting specialized professional vocabulary into plain laypeople's language can actually impair understanding for skilled and trained users for whom technical terms work as a kind of shorthand or trigger switch for a set of well-worn neural connections that the rest of us lack.

**Comment by humancompanion-usds** [comment]
@jimuhh - Thanks for the feedback. I suspect the same amount of user research when into the UK IA of patterns as went into our own IA of patterns: Very little. But, I don't have any real insight into what the GDS or NHS folks have done. It isn't mentioned in any of their [blog posts and videos](https://design-system.service.gov.uk/community/blogs-talks-podcasts/) (though I admit I read most of these in the past and only just scanned them now). I was less suggesting their model because they did it and more because it seems to be at least intentional. 

I've looked at 15 other systems recently, specifically at patterns, and the models are on the whole a hodgepodge of principles, components, page layouts/templates, and few actual patterns. The organization of those are usually based on UI placement or more rarely where in the experience they appear. I have a [bit of an audit going here](https://airtable.com/invite/l?inviteId=invZd6ulAXnrQ5jK1&inviteToken=1e84f9ebb326279f84a055dbc781aa08db2ab48f8a8e03e4db3fb8c1ad081de1&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts). There are [many, many more to look at](https://github.com/alexpate/awesome-design-systems).

I'm not opposed to the use of specialized language. My questions would be: 

#### What should the organizing principle be? 
It could be Design Principles followed by UX Patterns at a high-level but within those UX Patterns is it by:
* UI element (which feels awfully close to components)
* Interaction type (i.e. login or authentication, forms, search, etc.)
* Something else?

I feel like a lot of design systems are using one of these and not doing so well at sticking to a clear organizing principle.

#### Whose specialized language or whose lexicon?
The Design System serves designers, developers, and content writers. They each kinda have their own lexicons with some overlap. Do we need to define an ontology? I feel like the patterns are mostly aimed at designers. Different designers have different level of experience and understanding of principles and patterns. We could get into principles, cognitive biases, and things of that nature (ala https://lawsofux.com/) but I've been mainly just pointing to those things from a component or pattern rather than organizing around them.

**Comment by jimuhh** [comment]
@humancompanion-usds 
### Interesting!
Thanks for clarifying the varied user audience on this site. (I should have asked that to begin with.) I agree. Your question, "Whose specialized language or whose lexicon?" gets at the key issue. 


#### Some thinking...

**The three main user types:**

- Designers
- Content writers
- and developers


...are going to be coming here with different types and degrees of existing knowledge about 
- What design patterns are
- What kind of things they can do
- Which ones are available to do what, including:
  - Contexts of use
  - Best practices
  - and caveats for each
- Which one(s) they need for the thing they're planning to do

So ideally, we'd want to let the savvy users jump right to find what they know they want while letting less-domain-experienced users fill their rparticular knowledge gaps by discovering what they didn't know they needed. 
(Aha. Now I understand your user verb-based schema better)

The site also needs to formalize a controlled and shared vocabulary for the various patterns so that the inexperienced user can not only find the pattern they need, but learn the approved term for communicating with colleagues. 

(Yes, it's a lot, but you know that already.) 
But here's some good really good guidance on this very problem from Jared Spool:
#### [Riding the Magic Escalator of Acquired Knowledge](https://articles.uie.com/magic_escalator/)

**Comment by jimuhh** [comment]
@GnatalieH 
Among web designers, there more consensus on what different design patterns are called. So one job of the taxonomy would be teaching the industry terms to people who don't know them, while still making it easy for these people to locate the thing they want but can't name.

> "Oh, so those thing is called "radio buttons?" who knew?"

It would also give experienced people like you shortcuts (such as a typeahead that would suggest "featured content" when you typed in "fea..."). Designers who used to work in shops that used different terms for less-common components and patterns would also benefit.

**Comment by jimuhh** [comment]
@humancompanion-usds @GnatalieH 
IMO, the concept and vocabulary onboarding function referenced previously fits nicely with your idea of leading with plain language, verb-based summaries of the user outcomes the UI elements are meant to produce, followed by an introduction of the unfamiliar term.
We're all familiar with this pairing  from the chapter headings of our elementary school textbooks and continuing education texts

- **Supplying the Body with Blood:** The Circulatory System
- **Atoms:** Building Blocks of our World
- **Creating lists** with UL, OL and DL tags

**Comment by humancompanion-usds** [comment]
@GnatalieH - Yes, "Ask users for" and "Help users to" would be surfaced as top-level categories as they are [in the GDS system](https://design-system.service.gov.uk/patterns/) 

> Among web designers, there more consensus on what different design patterns are called.

Having just audited those few design systems looking at patterns I feel a consensus is lacking. But I suspect that is because designers don't all agree or have the same perspective on what's a pattern vs. a component vs. a page or template vs. a design principle, which then leads to odd naming of "patterns". Regardless, we lack a clear structure at the moment and need to find one as it's slowing down the authoring of new patterns.

Agree about the introduction of unfamiliar terms. We have limited space in the sidenav but can do a lot more context setting and education in the page of the pattern itself. Let me mock that up and then I'll circle back around here for feedback.

**Comment by GnatalieH** [comment]
@humancompanion-usds and @jimuhh I like the idea of leading with verb-based summaries based upon user outcomes. Then we have "Pages". Hmm. But I think it's valuable to have things like form confirmation page patterns documented.

**Comment by humancompanion-usds** [comment]
I presented this work to DSC on Fri Aug 5th. We added new patterns and voted on them. Here is the outcome of the vote:

* Help a user to Sign in with less friction (6)
* Help a user to Receive actual notifications, i.e. "Your claim has been approved" (6)
* Help a user to Deal with multiple errors (3)
* Help a user to Check that a service is suitable (3)
* Date last updated? Thinking of Veterans who obsessively check on their claim. Can we show the last update date? (3)

3 of those are new contributions that need to be reworded. Some possibilities:
* Help a user to stay informed of their application status (notifications, claim status)
* Help a user to stay informed (notifications, claim status)
* Help a user recover from errors (errors)
* Help a user check their eligibility (service is suitable)
* Help a user know the status of their claim (claim status)

The rest of the patterns that received 2 votes:
* Help a user find the right thing (search)
* Help a user get help (doing a thing so that we can pass them along to content or people to help)
* Help a user prepare to visit a VA facility
* Help a user identify whether or not changes they make in one place will impact changes in other places. Perhaps: know the ramifications of their changes, know how their information is updated?
* Help a user to change language
* Help a user to change their contact info in form (address/phone/email) - I think we have this covered by Ask a user for address, phone, email. But perhaps this is related to the ramifications of changes pattern?
* Help a user to download a copy of the form they just filled out (we do this some places but not other places) - Perhaps Help a user get a record of their application?

A few more suggestions that earned 1 vote:
* Resolve an error (system or within a form)
* Check on how much longer they have to wait (some kind of progress pattern)
* Pattern of table to card? Often designers display data in a table on desktop and then a stack of cards on mobile
* Tasks list - added from within a form, e.g. fill out a 4142, or 4138
* Pattern of table to card? Often designers display data in a table on desktop and then a stack of cards on mobile

**Comment by humancompanion-usds** [comment]
We held a workshop with VFS Teams today (8/8/22) and had them generate new patterns as well as vote on existing ones.

### New patterns

#### Help a user stay informed of their application status - 12 votes (split among 4 titles)
* Design a template to show application status and where to get help or follow up
* Check general progress of a submitted application
* Find out how long something will take
* This is similar to the DSC request of "Check on how much longer they have to wait"
* In my mind, this would be handled by "Help a user check the status of their claim" and "Help a user to stay informed of their application status"

#### Ask a user about their housing - 6 votes
A pattern for asking about homelessness 

#### Help a user review their changes - 6 votes (split among 2 titles)
* Expanding "one thing at a time" solution that replace a list loop to include a review pattern in the middle of a workflow (not just on the review page) 
* Similar to know the ramifications of their changes and may include a Profile component that updates the Profile as well.
* Also related, "Check, then update/edit personal info (phone, email, address, NOK, emergency contact)"

#### Help a user sign-in with less friction - 7 votes (split among 4 titles)
* There is LoROTA for a lighter weight identify verification method. Maybe we should document LoROTA in the DS.
* Is there a way 2FA doesn't have to be required for every sign in? Veterans are hating how time-consuming that is. [Remember this device]
* Sign in pages clear out all stored data, it would be nice to keep the sign in process within the site, or within iframes

#### Help a user find the right thing - 5 votes (split among 3 titles)
* Improve fuzzy search pattern
* Compare options side by side (e.g. multiple locations that provide a service)

Those 5 were clear stand-outs. A few other patterns received 2 votes:
* Way to designate Veteran preferred phone/contact method.
* Make an appointment/add an ICS file to their calendar
* Know the benefits they might be eligible for within a category
* Easy to spot error messages. Using color, weight, and iconography to ensure veterans can see it

**Comment by humancompanion-usds** [comment]
New patterns and templates structure is live!

https://design.va.gov/patterns/
https://design.va.gov/templates/

The rest of this information is captured in an airtable:
https://airtable.com/invite/l?inviteId=invrjoqpGSqjdYf4s&inviteToken=1082a3b62e3d39fe955ce43eaa5d6c484789e7e7f96c8df1cd7f548efab060fd&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts
