### ISSUE TITLE
va-text-input error state looses red bar at mobile sizes

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/vets-design-system-documentation#1055]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
When using `vads-l-grid-container` as a wrapper there is not enough padding to show the red error bar for `va-text-input` at mobile sizes. This is because the red bar renders in negative space relative to the components container. The padding at mobile sizes with `vads-l-grid-container` is 1.5rem which computes to 15px for us. There needs to be at least 20px of padding for the red bar to show at the edge of the screen.

### Screenshot gif of current state:
<kbd>
  <img src="https://user-images.githubusercontent.com/13967174/179254509-ba0b6e17-9db1-42b3-b303-7a9e44accd14.gif" />
</kbd>

## What I expected to happen
I would expect for the component to not utilize negative space, because this could cause issues in other layout scenarios as well. At the very least it should work within mobile containers.
### Screenshot of minimum expected behavior:
<kbd>
  <img src="https://user-images.githubusercontent.com/13967174/179256692-8423de72-541d-489b-ace7-38fc347e4465.gif" />
</kbd>

### Screenshot of ideal behavior (in my opinion):
<kbd>
  <img src="https://user-images.githubusercontent.com/13967174/179255320-79791b12-a75b-443d-86ba-a66a2549bd73.gif" />
</kbd>

In USWDS the error bar indents in for mobile screen sizes:
![Screen Shot 2022-07-15 at 8 26 53 AM](https://user-images.githubusercontent.com/13967174/179255500-9824275e-9f15-467e-9815-6770891f4533.png)

## Reproducing
- Formation version: ?
- Device: Macbook
- Browser: chrome, firefox

Steps to reproduce:

1. Create a div with this class `vads-l-grid-container`
2. Add a form with the `va-text-input` component
3. Set screen size to small mobile device ~320px 
4. Put the text input in an error state

**Comment by jamigibbs** [comment]
I tested this in staging and it appears that the issue was resolved as part of https://github.com/department-of-veterans-affairs/component-library/pull/501

https://staging.va.gov/profile/contact-information

![Screen Shot 2022-11-10 at 9 52 22 AM](https://user-images.githubusercontent.com/872479/201142537-5b141ee1-68fe-427b-88a5-040c294777b8.png)
