### ISSUE TITLE
Discovery: integrating VA Pattern Library with USWDS Sketch library

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1066]
## Description
How might we prepare to inherit USWDS Sketch symbols and better integrate our libraries? 

## Details
The VA Pattern library in Sketch is organized much differently than the USWDS Sketch library. If our goal is to integrate with USWDS in the future so we can inherit their updates, we should examine how to reorganize our library so that the two libraries are in better sync.

## Tasks

1. Review the organization of USWDS Sketch libraries, including how USWDS uses a master "sticker sheet" library in combination with smaller libraries.  
2. Compare naming conventions and atomic design of symbols between VA Pattern Library and USWDS libraries. USWDS uses basic shapes as building blocks for larger symbols. USWDS also gets very granular in the way colors are managed. 
3. Take guidance from USWDS regarding naming conventions for text and layer styles, as well as color variables.
4. Learn how USWDS library updates are pushed out to Designers and compare that with how VA Pattern Library updates are pushed out to our Designers.
5. Account for the "diffs" between library assets. What does the VA Pattern Library need that may not exist in USWDS libraries?
6. Present findings to team, along with recommendations for how to best organize the VA Pattern Library to integrate with USWDS libraries.

**Comment by GnatalieH** [comment]
@humancompanion-usds, how do Designers using the USWDS Sketch library know when it's been updated to a new version? I reviewed the "[Getting started for designers](https://designsystem.digital.gov/documentation/getting-started-for-designers/)" documentation on the website, but it doesn't mention how to stay up to date. I know there's not a Sketch for Teams space for USWDS. 

BTW I like their caveat about using the Figma library. We could do something like that, too, using the Figma assets that other teams have created. Could be a slippery slope, though.

![Screen Shot 2022-09-07 at 3.51.58 PM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/8a872e97-1198-4b1b-9e28-25f789af12e1)

**Comment by GnatalieH** [comment]
Steps we'll need to take to align with USWDS in terms of Sketch assets (WIP):

- Prioritize the 19 components Matt indicated "Yes" for, for inheriting from UWDS ([Airtable link](https://airtable.com/appF4FJKBeNVNGrlm/tblRMaKxvyPn6F0qe/viwNb9nb3qUoZt6Vm?blocks=hide)) 
- Add column in Airtable and note visual diffs between VA Pattern library and USWDS Sketch assets (for "Yes" components) 
- Note any major discrepancies in naming conventions between VA Pattern library assets
- Decide which USWDS colors we're using and create those variables in VA Sketch library
- Work with Allison to do an icon audit, note diffs of what we have vs. what USWDS has, and how to bridge any gaps
- Make sure VA DS form components and their error states are in alignment with each other and using USWDS styles
- Place USWDS aligned components in the new Components Sketch file that Sean started, which pulls in symbols and styles from the VA Pattern library
- Indicate in Sketch Components file which VA components are now aligned with UWDS components
- Communicate this change to VFS teams per the Service Design playbook

**Comment by humancompanion-usds** [comment]
> Add column in Airtable and note visual diffs between VA Pattern library and USWDS Sketch assets (for "Yes" components)

That is a useful step for the developers working on components. However, once we decide to adopt a component from USWDS we're going to try to take all of their styling. Thus in the Sketch library I would expect step 1 to be to copy that component out of the uswds-project.sketch file and drop it onto our corresponding page for that component. Then make sure the symbols are correctly connected to the libraries/uswds.sketch file. Do you agree? Perhaps we should test that out?

Where it gets a little complicated is when we want some of the USWDS elements but not all. For example: Buttons. We'd just want the Primary button and Outline - Primary button (our secondary). Then we'd probably want to rename the secondary one (at least for a little while when teams are transitioning). 

> Note any major discrepancies in naming conventions between VA Pattern library assets and USWDS assets. Decide how to reconcile if major diffs are present.

Does this mean symbol names? I feel like to keep it simple we'd adopt their symbol names given that we're adopting their styles. Component names already line up but with some conflicts (Banner, for example).

**Comment by GnatalieH** [comment]
> Thus in the Sketch library I would expect step 1 to be to copy that component out of the uswds-project.sketch file and drop it onto our corresponding page for that component. Then make sure the symbols are correctly connected to the libraries/uswds.sketch file. Do you agree? Perhaps we should test that out?

@humancompanion-usds yes, I agree with you. We should copy + paste the USWDS component onto the corresponding page in our new Components file in Sketch for Teams, the one that Sean started. And, I think we're going to need to manage our own version of libraries/uswds.sketch in Sketch for Teams and keep it manually synced up with the USWDS latest version. 

I've been trying to think about this from a workflow-centric POV, how we library Admins will work and how Designers will work. I'm going to do some simple flow diagrams as a next step since this ticket is carrying over into the next sprint, anyway.

> Note any major discrepancies in naming conventions between VA Pattern library assets and USWDS assets. Decide how to reconcile if major diffs are present.
> 
> Does this mean symbol names? I feel like to keep it simple we'd adopt their symbol names given that we're adopting their styles. Component names already line up but with some conflicts (Banner, for example).

Yes, I meant symbol names. I'm more concerned with areas like viewport size where I think our VA symbols are more intuitively named than what I've seen in USWDS. Are there going to be more places where the hierarchies just don't mesh, where the drill-down would be different? We've trained VFS Designers to have a certain mental model regarding how our symbols are organized, so I just want to stay mindful of that as we transition. 

I'll make some changes and throw this back into review when I'm done. Thanks!
