### ISSUE TITLE
Background Only Icon icon has positioning issues in Safari

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/vets-design-system-documentation#1080]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
The Background Only Icon icon has positioning issues in Safari. See screenshot:
<img width="1077" alt="Screen Shot 2022-08-02 at 11 49 00 AM" src="https://user-images.githubusercontent.com/13967174/182467703-dfd679dc-67ef-4637-96ec-7ff2bb53987f.png">

## What I expected to happen
I expect DS components to have consistent style across browsers. See screenshot in chrome:
![Screen Shot 2022-08-02 at 11 49 21 AM](https://user-images.githubusercontent.com/13967174/182467807-8d74a5a1-1e5d-4a7e-b3d0-e19b5cb1d035.png)

## Reproducing
- Device: (Macbook)
- Browser: (Safari)

Steps to reproduce:

View this page in Safari: https://design.va.gov/components/alert

**Comment by bkjohnson** [comment]
Possibly related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39181
