### ISSUE TITLE
2-line version of the closed accordion

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/vets-design-system-documentation#1097]
It would be great to have a 2-line version of the `accordion/mobile/default/closed` component, so that the title can wrap to a second line. 

**Original**
![closed Copy 6](https://user-images.githubusercontent.com/95102058/184183599-d131dc16-eda9-4de0-8ec3-72d2c8caaa97.png)

**Proposed**
![2 lines](https://user-images.githubusercontent.com/95102058/184183561-66e86e6b-3a42-4093-9f69-b38d3f59f219.png)

**Comment by KevinMHoffmanUSDS** [comment]
Hello, @skylerschain!

Based on a quick look in Storybook, it already behaves this way. Attached is a screenshot. Can you tell me a little more about what you're thinking? 

<img width="173" alt="image" src="https://user-images.githubusercontent.com/50150810/185156471-3c53e1e7-87b3-4fa5-89c7-8a5101af9915.png">

**Comment by skylerschain** [comment]
Hey Kevin. That does look correct! Maybe this is more of an issue with the Sketch library than the component itself. 

In Sketch, I didn't see a version of the `accordion/mobile/default/closed` component that wraps to two lines. And when you add two lines of text, the component is not responsive to that. I've attached a short screen recording so you can see what I mean. 

The solution would be to adjust the component so that it can accommodate two lines of text (I'm not sure Sketch can do this), or create a new variant `accordion/mobile/default/closed/2lines`. 

https://user-images.githubusercontent.com/95102058/185217644-70ae3bb3-2251-48b3-a4c9-d0fd3117a12b.mov

**Comment by caw310** [comment]
This is on the agenda for the 8/19 DSC meeting.

**Comment by GnatalieH** [comment]
I know we're talking about this at the DSC tomorrow, but @skylerschain I think this will make a good addition to the Sketch library. The wrapping accordion header is a likely scenario in small mobile viewports. We can add it to the library by putting this work in our backlog, or if you create and share the assets it will get added to the library even sooner. :) Thanks for bringing this up!

**Comment by caw310** [comment]
On the agenda for 8/26 DSC meeting.

**Comment by caw310** [comment]
From DSC meeting: 
DST will add this ticket to our backlog to update Sketch library with the 2-line version of closed accordion.

**Comment by GnatalieH** [comment]
@humancompanion-usds this work is ready to review on the [Accordion page](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/Gmg1e75) (at the bottom of the Mobile artboard). Thanks.

**Comment by humancompanion-usds** [comment]
Approved! Just be sure to update the release notes.

**Comment by GnatalieH** [comment]
I've added this item to the [November release notes](https://vfs.atlassian.net/wiki/spaces/DST/pages/2356215938/November+2022+Updates), and closing out the ticket.
