### ISSUE TITLE
Experimental Design [On this page with translations]

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/vets-design-system-documentation#1100]
On pages with translated content where we're using the On this page component, the header appears in English, which would create bad user experience. Is there any plan to create logic for translating this header? Let me know if this beyond the scope of the Design System team.

Examples:
- https://www.va.gov/health-care/covid-19-vaccine-esp/
- https://www.va.gov/health-care/covid-19-vaccine-tag/

**Comment by bkjohnson** [comment]
There is a plan for tackling this work within the Design System team. We are [waiting to receive translations](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/834#issuecomment-1189706338) so that we can make the appropriate changes.

**Comment by allisonlu** [comment]
- Spanish = **En esta página**
- Tagalog = **Sa pahinang ito**

**Comment by caw310** [comment]
From DSC meeting on 8/19

- Allison to add translations to the ticket. 
- DST will work on this request either in this sprint or the next.

**Comment by bkjohnson** [comment]
I think part of this will be out of scope for the Design System team. Internationalized static pages currently don't have anything on the page indicating what the language is. The way our components have automatic translation is looking for the `lang` attribute of specific tags, and right now there's nothing to indicate that this is a Spanish page:

![Screenshot of the Covid 19 Spanish page with the inspector open. The HTML tag has the lang attribute set to "en", and the "main" tag doesn't have a lang attribute at all. The content of the page is in Spanish.](https://user-images.githubusercontent.com/2008881/187738304-d4c27e2c-fa17-4a3c-8849-ec8401eb6650.png)

An appropriate `lang` attribute will need to be added to the `<main>` tag in order for the component to know which language to use. This would come from the CMS and be used in the content build.
