### ISSUE TITLE
[Checkbox, Checkbox group, Radio button] - Error state styles do not match other form controls

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1115]
## Description
Error state styles in Checkbox, Checkbox group, and Radio do not match other form controls' error states. I expect the label (black) and error message (red) to be bold. Margins and padding should be updated to match [va-text-input error](https://design.va.gov/storybook/?path=/docs/components-va-text-input--error) or [va-text-area error](https://design.va.gov/storybook/?path=/docs/components-va-textarea--error), for example. 

## Details
Checkbox error:
![Screen Shot 2022-08-16 at 2.47.16 PM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/2595f868-43b5-4065-bf5e-b23c91d4286e)

Checkbox group error:
![Screen Shot 2022-08-16 at 2.48.09 PM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/6e327a60-1107-44d4-a038-68f6708779a4)

Radio button error:
![Screen Shot 2022-08-16 at 2.48.39 PM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/b23503a6-1d72-450c-b6c0-a250cfb79ff6)

Error styles should be updated to use this same bold text treatment and margins/padding:
![Screen Shot 2022-08-16 at 2.50.00 PM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/b86e55b5-a011-4c52-b1b2-3b30541de452)

## Tasks
- [ ] Create designs for checkbox, checkbox group, radio button error states
- [ ] Update developed components to match

**Comment by k80bowman** [comment]
During standup on 9/14/22, the team decided that only the error message should be bold for all of these components. Neither the description nor the label should be bold in an error state. @GnatalieH @caw310
