### ISSUE TITLE
Incomplete focus halo on prototype

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1132]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The focus halo on our [prototype](https://dev.va.gov/health-care/covid-19-vaccine/) is missing the bottom border in the open state on expandable parent elements, and missing the left and right sides for child elements in the sidenav. 

Examples:

### Sidenav
![Screen Shot 2022-08-24 at 11.53.15 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/7cf5b9b0-e891-4a56-b8fc-e9f59c1bd525)

![Screen Shot 2022-08-24 at 11.55.40 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/f0ccb917-24c7-4d7e-89ed-18ea37e488bc)

### Accordion
![Screen Shot 2022-08-24 at 11.56.00 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/a2bf1629-d861-4ac6-8517-c2db58089dc8)

## What I expected to happen
The focus halo in the prototype should work in a similar fashion to our current focus halo and be complete on all four sides on all interactive page elements.

## Reproducing
- Go to [the prototype](https://dev.va.gov/health-care/covid-19-vaccine/)
- Use the keyboard to move focus to any expandable content element, open and close it

**Comment by caw310** [comment]
@bkjohnson , is this a simple fix?

**Comment by bkjohnson** [comment]
The accordions in the first and third images will be simple, but I don't think the second will be where the shadow is removed on the left and right sides. That may require more extensive sidenav work.

**Comment by GnatalieH** [comment]
FWIW, I think the bottom border issue is more significant than the left and right sides border issue. But, users may expect the new focus style to work in a similar fashion to the existing one, where all four sides of the halo are visible on all interactive elements. @bkjohnson, can the sidenav child elements get this treatment?

<img width="307" alt="Screen Shot 2022-08-24 at 12 33 30 PM" src="https://user-images.githubusercontent.com/88347129/186485765-504d6a25-315e-4857-933d-ecf786feb2fb.png">

**Comment by bkjohnson** [comment]
Actually, I think the second issue may be simpler than I thought. @GnatalieH yes, I think all sidenav links could have that focus styling.

**Comment by bkjohnson** [comment]
Changes are ready for review in https://github.com/department-of-veterans-affairs/content-build/pull/1277
