### ISSUE TITLE
Link Design System Form patterns to Forms Library codified patterns

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1134]
## Description
Given that the Forms System Team has done a great job of updating the Forms System documentation out on the Platform Developer Docs site, it would be great if we could link the Design System form components to that documentation.

## Details
I **think** this may be appropriate but perhaps not so I am looking for feedback here. One reason it might not be appropriate is that the components, to my understanding, are not the same. Thus perhaps linking from Storybook would make more sense? Also, sometimes our documentation disagrees with how the current Forms System implements something. For example, our Social Security number documentation (in patterns) specially says not to abbreviate to SSN yet in the Forms System the example definitely does that. Perhaps those little details are worth fixing, perhaps not. 

## Updated patterns

* [x] Address
* [x] Names
* [x] Relationship to Veteran
* [x] Email
* [x] Phone numbers
* [x] SSN
* [x] Dates

**Comment by k80bowman** [comment]
In the current forms system, there are some places where design system components are used, while in other places there are custom components being used instead. We could tease that out and add links in the documentation where appropriate, but it would take a little work. 

I think the decision about whether to do this work (and fix little details like the SSN thing) comes down to whether or not we see the new forms library being made available any time soon. If we anticipate releasing it in the next six months, say, it might be better to leave the current forms documentation as is and focus our efforts on getting the new forms library out the door. If we think it will take longer than six months, however, it might be worth making the updates to maintain consistency while we continue to work on the new library.

**Comment by humancompanion-usds** [comment]
The Veteran-facing forms team is close to making this a reality. Thus I'll be working on this in an upcoming sprint.

**Comment by humancompanion-usds** [comment]
Starting on this in the current sprint for the SSN pattern.

**Comment by humancompanion-usds** [comment]
@taylojill and @caw310 - This is the issue I've been using for linking the patterns in the Design System to the new coded patterns in the Forms library.

**Comment by humancompanion-usds** [comment]
@taylojill - Can you add an updated screenshot to Relationship to Veteran? Thanks.

**Comment by taylojill** [comment]
Will do @humancompanion-usds

**Comment by humancompanion-usds** [comment]
@taylojill - Please remove the examples that are there and add a screenshot of the current pattern from the mock-form-patterns. Thanks.
