### ISSUE TITLE
Remove header and level props from accordion storybook examples

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1137]
## Description

Our accordion component still has the `level` and `header` prop for compatibility with older code, but we want teams to be using the `headline` slot instead. We should remove `header` and `level` prop examples from Storybook.

## Tasks
- [ ] Update accordion stories to not use any `header` or `level` props

## Acceptance Criteria
- [ ] Accordion stories on storybook don't use `header` or `level` props

**Comment by humancompanion-usds** [comment]
This was a v1 issue. Closing as it is not in v3.
