### ISSUE TITLE
Style va-alert so it doesn't rely on formation.css

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/vets-design-system-documentation#1144]
## Issue Description
Currently, the styles implicitly rely on formation.css to show up properly, but that shouldn't be a peer dependency.

Specifically, the font-awesome icon for the close button doesn't show up without the formation stylesheet.

**Comment by humancompanion-usds** [comment]
@Andrew565 - Is this even still true? If not, can we close this? If so, how many other components have this dependency? We may need to double-check components to be sure that we've decoupled from Formation (though I suppose we'll find out as we drop v3 components into the v3 system Playground).
