### ISSUE TITLE
Configure a devcontainer for the design.va.gov repo

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/vets-design-system-documentation#1145]
## Issue Description
Now that [Codespaces](https://docs.github.com/en/codespaces) are available to everybody, we can use that as the editing experience for design.va.gov. Engineers and designers alike can open up a Codespace, make the changes to the markdown that they would normally, but now also be able to _see_ those changes in the Codespace before committing them.

## Acceptance Criteria
When a Codespace is created:
- [ ] The dependencies are installed
- [ ] The Jekyll dev server is started
- [ ] The port the site runs on is made public (to simplify sharing if desired)
- [ ] A new browser pane (within the Codespace) is opened to the dev server URL

**Comment by caw310** [comment]
@Andrew565 @jamigibbs - can we close this?

**Comment by jamigibbs** [comment]
@caw310 I do think that we need to improve the editing experience for design.va.gov. I'm not sure if codespaces is the direction we'd like to go with it but it might be worth investigating if we haven't already. 

@Andrew565 Was this something you explored earlier in the year when you were looking into a staging environment for the documentation site?

**Comment by Andrew565** [comment]
I did not explore this option at the time, no. I think a bigger question might be if there are enough advantages to using a codespace to make it worth continuing to set this up. At the time this ticket was created, codespaces were free. They are no longer free, so we would need to justify paying for each one that was setup. I think right now, for our team and how we currently work, setting up codespaces might be more trouble and cost than any potential gains we'd receive in using it.

**Comment by caw310** [comment]
Closing as this is old and the VADS components have been updated so this should no longer be an issue. IF you are still seeing the issue with the new components, file a new bug.
