### ISSUE TITLE
Identify pilot or test fo integrate emoji's into experimental design tickets

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1148]
This request originated from the DSC meeting on 8/6. Shawna had raised the question "Ddo we want to add a feature to allow Up Voting?"

The DSC has asked the DST to identify how we might integrate emojis into responses or comments for experimental designs. 

This idea should be tested or a pilot to see if it is successful. If it is, then we should add to issues. 

Reassign to Natalie Hill once she is onboard.

**Comment by bkjohnson** [comment]
@humancompanion-usds do we want to do this anymore now that we have the Maturity Scale instead of a separate "Experimental Design System"?

**Comment by humancompanion-usds** [comment]
Shawna and I decided to gather feedback by holding quarterly (or so) workshops with VFS Teams to get them to chime in on patterns and component they need. We held the first one on 8/8/22 and it was a success! We now have a board of priorities from those who participated (turn out was ~20 people IIRC):  
https://github.com/orgs/department-of-veterans-affairs/projects/779/views/2

Thus I think we'll continue to hold sessions and tackle it that way.
