### ISSUE TITLE
Discovery: what would it take to export components as individual node packages 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1149]
This is discovery issue to look into what it would take to  export components as individual node packages. 

Notes from initiative where this originated
Exporting components as node packages individually 
- instead of entire DS being one package, the components individually could be exported/imported when a team uses it
- when a change to DS, update is applied across the board to even teams who don't use it. 
- if export components individually, updating is controlled by teams using the component. 
- Problem solving: risk inherent in updating the DS versions in application repos without application teams having knowledge and making sure apps are working properly before going to prod

- [ ] Research quantifiable way of the impact of this initiative
- [ ] Define the impact and possible measurement / metric this change would have

**Comment by caw310** [comment]
@Andrew565 @jamigibbs - can we close this or do we want to do this still for the upgrade?

**Comment by jamigibbs** [comment]
This is still relevant. It's also kind of related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1954

**Comment by micahchiang** [comment]
Gonna close this one in favor of #1954 since they are pretty similar and this one is kind of old =\
