### ISSUE TITLE
Update Internal BigQuery Documentation

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/vets-design-system-documentation#1157]
## Related Discovery Ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32882

## Description
Using Google Cloud CLI and the `bq` tools that I provides we can upload our BigQuery data directly from a terminal. Therefore we can update the Updating Component Usage Report documentation [here](https://vfs.atlassian.net/wiki/spaces/DST/pages/1962213425/Updating+component+usage+data) to reflect that approach.

Topics to add: (Related Discovery Ticket can inform this portion)
- How to install the gcloud cli: https://cloud.google.com/sdk/docs/install and https://www.codingforentrepreneurs.com/blog/google-cloud-cli-and-sdk-setup
- Example command to run
- Break down of what each part of the command is doing to achieve the correct upload

## Acceptance Criteria
- [ ] Update Updating Component Usage Report documentation
- [ ] Inform internal DST team of changes

**Comment by caw310** [comment]
Closing as this is old
