### ISSUE TITLE
Resolve Package Dependency Issues in Component Library

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/vets-design-system-documentation#1160]
## Original Ticket department-of-veterans-affairs/va.gov-team#36826
Dependabot Alert led to: https://github.com/department-of-veterans-affairs/component-library/pull/292

Most of the remaining resolutions will be able to be removed upon upgrading Storybook from Webpack 4 to 5 however these three dependencies will require the following updates:
* `diff` and `minimist` steps to fix upgrade mocha@9.2.1 - React Components
* `node-fetch` steps to fix upgrade to puppeteer@13.5.0 - Web Components

Outstanding
* `trim` and `glob parent` will need to remain in resolutions until we upgrade to Storybook 7

See report in comment below that has the most recent vulnerabilities and how to fix

## Acceptance Criteria
- [ ] Upgrade packages listed above and double check that the version needed to fix the vulnerability in the dependency has been met
- [ ] Verify that no regressions occur
- [ ] Remove resolutions except for `trim` and `glob parent`

**Comment by caw310** [comment]
Closing as this is old
