### ISSUE TITLE
Add a script to automatically bump the core package version

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1161]
## Description
Add a script to the `component-library` repo for bumping versions in the react-components and web-components packages that also automatically bumps the core package version.

## Details
This ticket is dependent on completion of department-of-veterans-affairs/va.gov-team#35708 and department-of-veterans-affairs/va.gov-team#35709

## Acceptance criteria
- [ ] A script has been added that allows an engineer to bump the version in either react-components or web-components and the core package.

**Comment by caw310** [comment]
@Andrew565 is this still needed?

**Comment by Andrew565** [comment]
I think this ticket will be no longer needed once the work on https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1954 is completed.
