### ISSUE TITLE
Alert components containing buttons in mobile view

### ISSUE THREAD

**Issue by oleksii-morgun-va** [department-of-veterans-affairs/vets-design-system-documentation#1167]
It appears that <va-alert> component containing a button, doesn't apply proper styling on mobile views, causing the button width to expand outside of the Alert component width. 

https://design.va.gov/storybook/?path=/docs/components-va-alert--default

![image](https://user-images.githubusercontent.com/87077843/187458958-f3a6322b-671e-4f9e-a2f7-352be904374e.png)

**Comment by andaleliz** [comment]
Here's another example of this from Storybook:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/55992116/204335468-f10ac1f6-6872-4790-a0d2-ae41e2f780f0.png">


and on the health application page (va.gov/health-care/apply/application/introduction):
<img width="376" alt="Screen Shot 2022-11-28 at 11 51 26 AM" src="https://user-images.githubusercontent.com/55992116/204335543-4b17c40e-7465-43e9-a062-74bc50df8cec.png">

**Comment by jamigibbs** [comment]
Closing this one because we have a duplicate ticket that has some more details and a possible solution: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1798
