### ISSUE TITLE
Design system pages: feedback & questions

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#117]
Jared - I'm 'forwarding' this feedback about design system pages. These came in via the content style guide email inbox but they are regarding sections beyond.  See pasted copy from email; also attached - as GH doesn't render the highlighted texts in the original message. /jen

[Design-system-pages-issues-DR.pdf](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/3311529/Design-system-pages-issues-DR.pdf)

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [x] Other

## What is the name

 Various - see below or attached doc.

## What is the nature of this update?

- [ ] When to use
- [ ] When to use something else
- [ ] Code snippet
- [ ] Accessibility
- [ ] Research insight
- [ ] General documentation

## Additional Context

From: Rodriguez, Donna Adorian 
Sent: Tuesday, June 18, 2019 7:05 AM
To: VA Web Design <VAWebDesign@va.gov>
Subject: Content style guide

It does not appear the code is undated to USDWS 2.0. What version is this site based on? How often will it be updated?
_Formation is built with USWDS 1.6.x. We will not be migrating to version to 2 for a number of reasons. Primarily is that it breaks much of the existing design of VA.gov and the LOE is too high for something that brings no significant changes to design or functionality. The main difference is USWDS 2.0 introduces utilities, which we have already built into Formation. If USWDS introduces a new component that would be useful on VA.gov, the process will be to implement that component individually, in a way that works with VA.gov's design system._ 

Here  are a few things I found while going through site:

At top, here’s how you know link on home page does not drop down. 
_This was resolved earlier this week. In creating non-react versions of the accordions, a polyfill needed to be added Formation to fix a bug in IE. VA.gov had the polyfill already. It was added to design.va.gov on Monday or Tuesday. There is a ticket to include it Formation._

https://design.va.gov/documentation
provide hyperlink to analytics.usa.gov to go to site.
_Done._

How do you get license for Sketch? 
www.sketch.com
_I do not know how VA gets liceneses. I imagine the process may differ by department?_

Spacing Units paragraph (1st paragraph) 
https://design.va.gov/design/spacing-units
Add “to” to when applied “to” margins …
_Done._

Link to Formation’s base files produces 404 error.
_Fixed._

https://design.va.gov/documentation/designers
Capitalize Veterans 
_Fixed._

https://design.va.gov/patterns
VA.gov
_Fixed_

https://design.va.gov/layout
needs a . U.S. 
_Fixed_

https://design.va.gov/documentation/developers
Should help you get started

Depends greatly on your project structure

Implementing design works
Implications that designs design
In general-duplicative
some, some
You will notice that not everything in Formation follows the naming the convention …
Components may be refactored
_Fixed_

https://design.va.gov/documentation/whats-new
fixed bug where 
_Fixed_

**Comment by jaredcunha-usds** [comment]
Added comments in _italics_ directly in your comment. Typos are fixed here:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/119
