### ISSUE TITLE
Experimental Design [Notification]

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/vets-design-system-documentation#1181]
## What
- New component design for authenticated experience notifications
- Dismissible and not dismissible options
- Two icon options: Exclamation mark (!) for items that require action by the user; info icon (i) for important updates that don't necessarily require user action

## Purpose
> What problem does this component or pattern solve for the user?
- Surfaces important updates and action items that may be buried within the existing page hierarchy or do not exist on the page and would need to be shown as an alert
- Visually stands out from other cards and content on the page so the user knows it is the most important thing to pay attention to
- The subtle drop shadow helps to draw the user's eye to it before other items on the page so they know it should be interacted with. It looks visually more important than the cards in gray boxes
- Provides minimal, clear content that is quick to digest and act upon

## Usage
> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.
- My VA, since this is a user "dashboard" of sorts
- Can be used on any page where timely action is needed and we might have previously utilized a link within a warning alert
- May be useful in the mobile app to surface important information upon login

## Behavior
> Describe the key interactions for this component, calling out any specific considerations for mobile.
- The user can click/tap a link within this notification or dismiss it by clicking/tapping the X icon. The interaction is the same on mobile.
- In the non-dismissible version of this notification, there is a link that the user can click/tap. In this case the notification will only disappear when the user takes a specific action or completes a task.

## Examples
> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.

**Screenshots:**
![Screen Shot 2022-09-01 at 5 13 08 PM](https://user-images.githubusercontent.com/97965610/188021100-0749e5bd-921e-448b-b57c-9fbb8a6c1bca.png)
![Screen Shot 2022-09-01 at 5 56 15 PM](https://user-images.githubusercontent.com/97965610/188021102-ba9a4290-34fe-45b0-ba99-1eeeac38c739.png)

Non-dismissible option:
![Screen Shot 2022-09-01 at 8 40 20 PM](https://user-images.githubusercontent.com/97965610/188035369-a251f4c6-3fae-44b0-980e-4a2cc29e0ec2.png)
![Screen Shot 2022-09-01 at 8 41 49 PM](https://user-images.githubusercontent.com/97965610/188035383-f794abc6-1c1e-4524-b655-64d461200f5a.png)

**Sketch Links:**
[Desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/0AD97AC5-6E6F-4203-ADCF-EC8C4485BD67)
[Mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/9770D6A2-25CB-4E9A-B8AB-5B0538768471)

## Accessibility
> Include any accessibility considerations.
- This design has been run by a11y specialists which affected the order of info (headline first, then date, then link) to make more sense for screen reader users. It would be ideal to include alt text for the icons that reads "Important" and "Update".
- This design has been tested with users who have low vision and the only adjustment was to make the date a little darker (which we did).

## Guidance
> What would you want to tell other teams about this component or pattern?
- These are not related to system performance or general site updates and should have content that is personal to the logged in user. Utilizing the alert component for messaging that is not specific to the user/doesn't require action will help to differentiate these notifications as action items.
- Notifications should not be used as a band-aid for poor hierarchy within a page. Example: It's not necessary to add a notification at the top of the page if the main purpose of the page is to provide that specific update to the user. It's repetitive.

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.
- The authenticated experience team tested this component in usability testing in August 2022. All 8 Veterans noticed it right away, could see it clearly (with the exception of the color of the date text which has been updated), understood the content, and knew how to act on it. 
- The authenticated experience team attempted to use the background-only warning alert for notifications and it did not test well. Veterans said the yellow color seemed soothing and some with low vision had trouble seeing a blue link on top of the yellow background. The only other option was the warning alert with yellow bar on the left, which we also use for system errors.

## Code (optional)
> Include any existing code.
- N/A

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
Decision from DSC meeting.  This will be put in the DST's backlog to add to the DS as an experimental design. We will reach out to you if we need more information. Thanks!

**Comment by caw310** [comment]
Things to consider from discussion: 
- Need guidance on how many can stack. How will we handle multiple? Once past 3, it’s a burden. One notification and have an addition formula. 
- Have higher level description for this. People are using different words for different things.

**Comment by aagosto90** [comment]
Hi @humancompanion-usds ! I'm revisiting this notification component as our team is currently exploring what our next notification will be to add to My VA through VA Notify. Has there been any further progress on the design or code for it? Another team sent me a link to this [Sketch file](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/p/8E62D47D-F38C-4727-8E27-B5DF3424F12F/canvas) and I noticed that the close icon has changed somewhat so wanted to make sure I have the latest iteration. Thank you!

CC @ajakabcin @BerniXiongA6 @Samara-Strauss

**Comment by humancompanion-usds** [comment]
@aagosto90 - Hey Angela - Yes, there have been some changes. The symbols for the Card itself in that Sketch file are correct and up-to-date. There are two variations - 1 with a drop-shadow and 1 without. Both have a border. The drop-shadow and border have been reviewed by a11y. Those will go into the system as the base of all Cards (along with a gray variation to match what we have elsewhere today). Cards using that base card style are starting to get tested by teams and find their way out the door. 

As for the close icon, we noticed while working on link styles for modals that it is one of the few icons we have that has no corresponding label. I brought this "icon button" style to DSC week before last. We didn't get consensus on it but it's something a11y and I would like to explore. Thus if you wanted to test an iteration with it and one using what you had that would be quite helpful. I did some variations of the notifications card (on the bottom of the Modal page) in that Sketch file to show how the new icon button would potentially cause some problems unless the Card grows to meet the need and keep it in proportion:

<img width="816" alt="Screen Shot 2023-02-27 at 3 40 19 PM" src="https://user-images.githubusercontent.com/52176351/221680589-2c81f930-b2d0-44c9-b742-1ba4250a6eec.png">

**Comment by aagosto90** [comment]
Thanks for the update @humancompanion-usds! We were planning to have our developers code this experimental component this sprint so we can switch out the warning component we're using sooner than later. Just wanted to make sure we're okay to move forward with that and that no other teams have moved on to coding this new card yet before I give them the go-ahead to work on it.

As for testing, I could have our developers code a version with the text next to the icon and one without so that when we test in production with Veterans, I can get some feedback on that to relay to you all.

**Comment by humancompanion-usds** [comment]
@aagosto90 - If you are not going to incorporate the text with the icon then, no, it doesn't need to change. If you do choose to add the text then I found that the "icon button" of Close and icon was a bit too close to the title. I think there are a few options:

1. The title text could wrap and thus keep the title and close text & icon on the same line.
2. The Close text & icon could be on their own line pushing the title down.
3. A combo: Start with 1 and when there is room have the Card grow wider when it can to allow for 2.

**Comment by aagosto90** [comment]
@humancompanion-usds Got it! Thanks for the response. Good to know it's not necessarily required at this point and there's still room for exploration.

**Comment by ajakabcin** [comment]
Latest sketch files including incorporation of "close" text in addition to x icon for dismissal

- **Desktop:** [single](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/ZOkzKM7), [multiple](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/zxDMl7W)
- **Mobile:** [single](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/YG34bgd), [multiple](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/JnjwPe5)

**Comment by babsdenney** [comment]
The sketch assets look great! We have a couple of items to consider in future updates but we can proceed with the current design. 

- Consider moving the location of the close button to [above the title](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1181#issuecomment-1447073790) 
- Improve button states for the [close button text variation](https://sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347)

**Comment by humancompanion-usds** [comment]
Moving this up in priority since this is coming to CollabCycle Staging review next week.

**Comment by humancompanion-usds** [comment]
The guidance isn't really complete in that it doesn't go into details like how many notifications can be shown in different contexts and which variation is preferred. However, it's flexible enough to allow teams to use it and figure that out. We can file an issue to add more guidance later as this functionality develops.
