### ISSUE TITLE
Create ESLint rule for Process list migration

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1195]
## Description

We have a [`<va-process-list>` Web Component](https://design.va.gov/components/process-list) that is meant to replace the `process` and `process-step` family of [CSS classes from `formation`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/f0e1d666503ecf4aafcb421bbc47fc7f76abec4a/packages/formation/sass/modules/_m-process-list.scss). Many VFS teams are still using this older style of component and [coming up with workarounds](https://github.com/department-of-veterans-affairs/vets-website/pull/22141#discussion_r965392349) rather than switching to the newer component.

We should add a new ESLint rule which can autofix this older code to use the new Web Component, similar to [what we did for `tel` links](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/864).

## Details

There are currently about 3 dozen instances of the `process` class being used in `vets-website` application code:

![Screenshot of a terminal with ripgrep output. The regular expression that is being searched on is `process-step` and we are searching inside the `src/` directory for all `.jsx` files. There are 37 files total, with one being a spec file.](https://user-images.githubusercontent.com/2008881/190021883-004a66af-6871-418a-8a49-324a8aa05ccb.png)

## Tasks
- [ ] Write new ESLint rule that it is capable of migrating a `<ol className="process">` to the `<va-process-list` web component

## Acceptance Criteria
- [ ] Older `process` classes can be migrated to use the Process List web component

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
