### ISSUE TITLE
VACheckbox with a screen reader causes screen to scroll to top

### ISSUE THREAD

**Issue by EClancyVA** [department-of-veterans-affairs/vets-design-system-documentation#1196]
# Bug Report

- [✔️] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using VACheckboxes with JAWS, I noticed that the page was scrolling to the top. When I went to the VA Design site for guidance, the same behavior occurred. Videos and link to page below:

![checkbox scroll to top of page 2](https://user-images.githubusercontent.com/113545409/190219991-d039d2d2-0821-4815-beb6-63482bf5d4f6.gif)
![checkbox scroll to top of page](https://user-images.githubusercontent.com/113545409/190219992-fa3aea01-7585-4070-9d3d-b924e43f7167.gif)

https://design.va.gov/components/form/checkbox

## What I expected to happen

No scrolling while navigating across checkboxes with a screen reader. 

## Reproducing
- Formation version: 7.0.2
- Device: Windows Laptop
- Browser: Chrome, Edge

Steps to reproduce:

1. Open a page with checkboxes
2. Scroll down
3. Click on a checkbox/element containing a checkbox (can be laggy/finicky)

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [✔️] This bug is not blocking any work
- [ ] Other

**Comment by EClancyVA** [comment]
As an update, we have since refactored our UI, and have no way to test this any more.

**Comment by humancompanion-usds** [comment]
I'm marking this as invalid. It seems highly unlikely this anomaly was related to va-checkbox.
