### ISSUE TITLE
VaAccordionItem re-renders the icon when panel is collapsed

### ISSUE THREAD

**Issue by imelda-guzman** [department-of-veterans-affairs/vets-design-system-documentation#1199]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
The accordion panel icon does not hold the state of panel when trying to programmatically pass a boolean variable to the `open` prop for accordion item.

**The accordion panel when initialized - starts out correct**:

<img width="862" alt="initial-open-state" src="https://user-images.githubusercontent.com/748095/190469805-c69f8107-4425-41b6-9695-4f48e1c6ef81.png">

**Opening second panel - first panel closes and value is set to false, still correct:**
Before modifying a form element within an accordion item.

<img width="862" alt="mandatory-panel-closed" src="https://user-images.githubusercontent.com/748095/190470444-e8ce828a-37e6-46d4-a467-087106d7406d.png">

**Modifying a radio option or dropdown selection or triggering a validation error on a text input is causing icon in first panel to re-render and change**

<img width="862" alt="modified-input-changes-closed-panel-icon" src="https://user-images.githubusercontent.com/748095/190471483-96c2925c-1d20-486e-807e-96f76b54df3d.png">

## What I expected to happen
I would expect to modify a form element within the accordion item and not have the panel icon change.

## Reproducing
- Component Library version: 11.5.0
- Web Components version: 4.12.0 
- Formation version: 7.0.2
- Device: HP Elitebook
- Browser: Microsoft Edge

Steps to reproduce:

1. Create a VaAccordion with 2 or 3 panels and give it the `open-single` prop and set the first panel to open when initialized.
2. Create a function that can be passed to "onAccordionItemToggled" to dynamically set the boolean value for the open prop
3. Modify a form element in either second or third panel and change its value.  The VaRadio or VaSelect will work.
4. Notice the icon will change on the first panel when its collapsed.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

**Comment by bkjohnson** [comment]
In your steps to reproduce, what does this function look like?

> Create a function that can be passed to "onAccordionItemToggled" to dynamically set the boolean value for the open prop

**Comment by imelda-guzman** [comment]
The application is built in React. Create two states for each panel. This will be initial state when accordion loads.
```
const [isPanelOneOpen, setPanelOneOpen] = useState(true);
const [isPanelTwoOpen, setPanelTwoOpen] = useState(false);
```
Pass the two new variables and functions to accordion item.  Note we are using Typescript
```
<VaAccordionItem
      header="Panel One"
      id="panelOne"
      open={isPanelOneOpen}
      onAccordionItemToggled={(event: { target: { open: boolean } }) => setPanelOneOpen(event.target.open)}
>

<VaAccordionItem
      header="PanelTwo"
      id="panelTwo"
      open={isPaneTwoOpen}
      onAccordionItemToggled={(event: { target: { open: boolean } }) => setPanelTwoOpen(event.target.open)}
>

We also tried creating a function and then passing it to "onAccordionItemToggled" like this

const togglePanelTwo = (event: boolean | ((prevState: boolean) => boolean)) => {
      setPanelTwoOpen(event);
};

and then on accordion item
onAccordionItemToggled={(event: { target: { open: boolean } }) => togglePanelTwo(event.target.open)}
```

**Comment by imelda-guzman** [comment]
Hello,

I'm following up on old reported GitHub issues.  Does anyone have information on this ticket and whether issue reported here with the va-accordion icon has been resolved?

**Comment by caw310** [comment]
Closing as this is old and the VADS components have been updated so this should no longer be an issue. IF you are still seeing the issue with the new components, file a new bug.
