### ISSUE TITLE
Text edit on 'getting started on design.va.gov' pg

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#122]
## This update is for: 
https://dev-design.va.gov/documentation/#us-web-design-system-already-included

- [ ] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [x] Other

-->

## What is the nature of this update?

- [x] General documentation

## Additional Context

**Current:**
We will not be update to version to USWDS v2, primarily because:

    Many of the naming conventions have changed between the two versions
    The design of some of the base components has changed based on specific needs for VA.gov
    Formation includes its own set of utility classes and design tokens

**SUGGESTED CHANGE:**
Lead-in text; periods at end of bullet points (if they're complete sentences, they all get punctuation); we use numerals (except for weird cases of 1 vs "one"). 

We're not currently updating to USWDS v2 because:

    Many of the naming conventions have changed between the 2 versions.
    The design of some of the base components has changed based on specific needs for VA.gov.
    Formation includes its own set of utility classes and design tokens.

@rtwell FYSA

**Comment by jaredcunha-usds** [comment]
Updated and merged.
