### ISSUE TITLE
Explore versioning solutions for component-library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1223]
## Description
Explore ways to ease the versioning process for the packages in the component-library repo. One option could be using [Yarn deferred versioning](https://yarnpkg.com/features/release-workflow#deferred-versioning) as part of the CI process to manage versioning for the react-components, web-components, and core packages. As part of this, we should create and document an ideal workflow for versioning.

## Details
We are not sure if this will work yet, it needs to be explored. But I imagine that a lot of the exploration will involve just doing the work, so I don't think we need separate discovery and work tickets.

## Acceptance Criteria
- [ ] Create ideal workflow for versioning in component-library
- [ ] Explore ways to ease versioning in component-library
- [ ] Document results of exploration in this ticket
- [ ] Review results with engineering team

**Comment by caw310** [comment]
Closing since this is old.
