### ISSUE TITLE
Discovery:  CTA web component (based on experimental design request) 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1232]
This discovery work is follow up from this experimental design request to build a Call To Action Web Design System Element. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/644 

DST engineers to do discovery work and identify benefit of a CTA web component widget. 

- [ ] Identify what this CTA web component element would do
- [ ] Identify the problem(s) this solves
- [ ] Identify what the benefit is
- [ ] What would it take to build this? 
- [ ] What are the next steps?

**Comment by humancompanion-usds** [comment]
This work has already happened and continues in this issue: https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1459
