### ISSUE TITLE
[Pagination] Design: Pagination navigation

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1233]
## Description
We have received comments about how the pagination component makes it difficult to get back to page 1 when users are on higher number pages. We have an option to show the highest number page, so the pagination component would have an ellipsis and then the highest number page would be shown, like this:
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/637f1d9f-f898-433c-b1f7-fd03174f8fff)

But we don't have a similar option for showing the first page. As shown in the screenshot above, the user has to press the `prev` button repeatedly in order to get back to the first page.

We need to create a design for this component that includes an option for easily returning to the first page.

## Acceptance Criteria
- [ ] Complete design for easy navigation to first page as part of Pagination component

**Comment by humancompanion-usds** [comment]
We should be following the US System here: https://designsystem.digital.gov/components/pagination/
What they've got handles the issues I mentioned back in April. This is a prime example of where we should inherit from them rather than redefining, poorly, what they have provided.

**Comment by caw310** [comment]
Closing since we are upgrading to USWDS v3 pagination component.
