### ISSUE TITLE
[Alert] Capture design and behavior details for closeable background alerts

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1236]
Recently a designer came to the DSC with a proposed experiment for dismissable notifications/background alerts. Since we already have non-dismissable background alerts in the design system, the DSC suggested we simply move forward with this request as a component update. In order to make this official, we need to capture the following:

- Design specs for dismissable background alerts including X (close) icon and its placement
- Details around behaviors of dismissable background alerts, such as: What happens to the page content when an alert is closed? Is there animation when a background alert is dismissed? Should all background alerts be dismissable, or just certain ones? 

When these details are captured we can confirm the changes with the DSC.

**Comment by humancompanion-usds** [comment]
We've done this: https://design.va.gov/components/alert#dismissible-background-only-icon
