### ISSUE TITLE
Guidance for "Need Help?" Content Block

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/vets-design-system-documentation#1239]
To learn more about contributing to the Design System or requesting new components, requesting changes to existing components, and reporting bugs, go here.
https://design.va.gov/about/contributing-to-the-design-system/

---
# Bug Report or Design System update

- This is following up on a Slack thread related to the "Need help?" content block. The request is to provide some usage guidance in the Design System around when and where to use this content. 

## Additional Context
https://dsva.slack.com/archives/C01DBGX4P45/p1664214428679009

<img width="1257" alt="Screen Shot 2022-09-26 at 1 42 19 PM" src="https://user-images.githubusercontent.com/95102058/192357417-96f3e987-3667-4e4a-9137-bdbb1b23e6e1.png">

**Comment by humancompanion-usds** [comment]
Need help? is now a component in the System: https://design.va.gov/components/form/need-help We're prefer that it be consistently placed just above the footer and not in the right-rail.
