### ISSUE TITLE
[FileInput] React Testing Library does not trigger an upload event on va-file-input

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#1241]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

With plans to update the [lgy/coe document uploader component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/lgy/coe/status/components/DocumentUploader/DocumentUploader.jsx#L112) to use `va-file-input`, we were not able to write unit tests to activate an upload using testing-library. Targeting the button or input isn't possible due to lack of shadow DOM support. I ended up continuing to use the `FileInput` React component

## What I expected to happen

Be able to use testing library to trigger an upload userEvent on `va-file-input`

```js
userEvent.upload(input, file);
```

## Reproducing
- Formation version: All
- Device: (e.g. iPhone 8, Macbook): All
- Browser: (e.g. Firefox, IE 11): All

Steps to reproduce:

Attempt to trigger a `userEvent.upload` on `va-file-input` does nothing

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
No rush on this, we'll continue to use React `FileInput` until an update is available

**Comment by bkjohnson** [comment]
Do you have a code sample or a branch/commit where we can see what was causing the test to fail?

**Comment by bkjohnson** [comment]
The linked PR above unblocks you on the failing unit tests but some Cypress tests are failing as a result of the migration. Feel free to take over the PR and make the updates to the Cypress tests.
