### ISSUE TITLE
Add SMS option to <va-telephone>

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/vets-design-system-documentation#1246]
## What
The Veteran Crisis Line (VCL) offers a SMS option in a few different places on VAgov, notably the modal available from the header of all pages. It's a 6-digit number. And because it's an SMS number, the appropriate markup would be `href="sms:######"`. 

The Public Websites team encountered challenges in using this markup within the DS:
- eslint notified us to use `<va-telephone>` instead of a link, but that component doesn't offer an SMS option
- eslint notified us that phone numbers need to be 3 or 10 digits
- our implementation currently requires disabling eslint for this line of code

## Purpose
Enable teams to publish SMS links within the DS.

## Usage
(Above.)

## Behavior
This is primarily a mobile use case. Tapping an SMS number should request the user's permission to open their SMS app.

## Examples
VCL modal:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/4054752/193159602-7c333464-d0dd-4636-82f0-a6978f0233a5.png">

## Accessibility
> Include any accessibility considerations.

## Guidance
> What would you want to tell other teams about this component or pattern?

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.

## Code (optional)
> Include any existing code.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. **Asynchronous should be fine. Matt Dingee suggested I file this request and he has context.**

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by jamigibbs** [comment]
Adding @GnatalieH to this ticket so that she can confirm how we'd like the SMS number to appear. In the screenshot it's showing up as "Text: 838255" but she will need to confirm with the Content team if that's how it should look.

**Comment by GnatalieH** [comment]
Here is the way we should format SMS:

Text: [838255](url)

**Comment by humancompanion-usds** [comment]
We had a bit of back and forth on this. We resolve to leave TTY alone and keep the "TTY:" label as part of the link. Thus TTY stays the same:

`<a href="tel:+711" aria-label="TTY. 7 1 1.">TTY: 711</a>`

For text we decided to handle it as we do telephone numbers and not include any label or text. That's left up to the caller to decide on (though our guidance will instruct them NOT to put "text" in the URL). Thus:

text `<a href="sms:838255" aria-label="8 3 8 3 5 5.">838255</a>`

There are some current instances of "text" being within the URL but adding SMS to this component, and guidance, should help us resolve those.

**Comment by wesrowe** [comment]
@humancompanion-usds, need clarification on the comment above. Your examples are `<a>` tags, but this ticket is about adding SMS to the `va-telephone` component. DS docs for the telephone component don't appear to have changed. I think what would help me is direct guidance on how we should handle text links now. Here's the [Public Websites ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10868) that was blocked on DS updates.
cc @jilladams @jtmst

**Comment by jamigibbs** [comment]
@wesrowe I might be able to add some more details. @humancompanion-usds's comment was specifically to clarify a development question I had although he might want to add more details here if he'd like.

We have added an `sms` attribute to the `va-telephone` component which you can see in an example on Storybook here: https://design.va.gov/storybook/?path=/docs/components-va-telephone--default#sms

**Comment by humancompanion-usds** [comment]
I have [an issue to document](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1298) the new option in the [component](https://design.va.gov/components/telephone) page as well. I will get to that now that the option has been added.

**Comment by wesrowe** [comment]
Thank you both.
