### ISSUE TITLE
text link bug on health hub page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#125]
![image](https://user-images.githubusercontent.com/43381063/60196972-6d29db80-980c-11e9-83de-d67b8875a0d0.png)

On this page: https://www.va.gov/health-care/family-caregiver-benefits/comprehensive-assistance/

See screenshot attached. The text link is one link, but renders on hover as 2 separate links. 

EX: when you hover over "Use our online caregiver support" part of the text, it shows as an active link; and when you hover over the latter part of the text "coordinator search tool" that shows as another separate link.

But they both point to https://www.caregiver.va.gov/help_landing.asp and I believe should be rendering as one unified link.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I fixed this is CMS so that it's just one link.

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva The design system site repo is probably not the best place for these kinds of kinds of tickets. Perhaps `vets-website`, but I'm not sure for CMS-related content.

**Comment by jenniferlee-dsva** [comment]
Aak, noted. Sorry @jaredcunha-usds . I just hit 'new issue' on whatever page I happened to be on. Didn't realize it was generating it specifically in the design system repo.
