### ISSUE TITLE
Conversion to USWDS v3 - Memorable date - Development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1267]
## Description
Adapt the va-radio component to match the [USWDS Memorable date](https://designsystem.digital.gov/components/memorable-date/) component and import and use the USWDS CSS for this component. This component is already based on the USWDS component, so this shouldn't require any structural changes.

## Details
- Design documents: [add links to any design documents]
- See the [Textarea discovery](https://github.com/department-of-veterans-affairs/component-library/pull/493) for an example
- According to the [plan](https://vfs.atlassian.net/wiki/spaces/DST/pages/2366275704/Plan+-+Aligning+VA+Design+System+components+with+their+USWDS+v3+equivalents), we will be using a prop if necessary to differentiate between our version of this component and the USWDS version. It may not be necessary for this component, this can be decided on a case-by-case basis

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ] Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ] Check with Natalie to make sure the component and the design match
- [ ] Add a USWDS story to Storybook
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json

## Acceptance Criteria
- [ ] USWDS version has been created and added to Storybook
- [ ] Design.va.gov has the latest version of component-library

**Comment by caw310** [comment]
We had a meeting with USWDS 1/17. Asked about their using a select box for month instead of input field. Here is a summary of the response from Dan: 

> Change based on what we found with our own usability testing around patterns. We were finding that it wasn’t always as clear as it could have been around month, day and year. Select allowed us to be more clear around month. and to spell out month instead of a number. More a11y focused testing - performed better than a number input. Select wasn’t any harder and resulted in it always being clear that that was the month

Convert Memorable date to the USWDS v3 version with month as a select box.

**Comment by caw310** [comment]
For reference. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1301#issuecomment-1387544580

**Comment by caw310** [comment]
Will carry over into the next sprint.

**Comment by jhonnyoddball** [comment]
The following tickets will need to be addressed with relationship to the `memorable date `component:

- [Memorable date doesn't translate select values on language change](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1605)
- [Memorable date field doesn't translate error message on language change](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1488)
- [USDWS v3 minor changes](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1606)
