### ISSUE TITLE
Experimental Design [va-number-input]

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/vets-design-system-documentation#1280]
## What
Updating `va-number-input` with currency styling. This can probably be asynchronous review, but I'm available if there's any questions/concerns!

## Purpose
Allow for consistent numeric input with currency symbols across VA. 

## Usage
When creating custom components in VA forms system this flag will allow for consistent styling throughout the form regardless of page implementation.  

## Behavior
Add a bool prop to va-number-input with an option that will add currency styling like the example below. 

## Examples
`<va-number-input required name="example" currency />`

A number input example with a currency symbol: 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/25368370/195107307-93179166-b828-49d2-8b36-b39591a94835.png">

With error message:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/25368370/195107593-b918ac2d-64b0-47c9-8fc1-52c3eaba9264.png">

## Accessibility
Only major concern is if the current forms system has a specific aria label for currency input boxes that we might want to add if this option is selected. 

## Guidance
With this new prop styling currency number inputs is easy and intuitive! 

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.

## Code (optional)
> Include any existing code.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
We discussed this component in DSC today:

* DK mentioned the aria-label and SaraK commented that VoiceOver announces currency but other screen readers may not. Sarah can guide our implementation should we get to it.
* Robin mentioned we might want to consider a prefix and suffix for text-input. Currency could be a prefix and suffix might be a %. We can decide when we take this one.

We'll add this to our backlog as a new variation to add.

**Comment by Dr-Pongo** [comment]
Hey @humancompanion-usds! I wanted to follow up on this to see if it is something that will be in motion soon?

**Comment by humancompanion-usds** [comment]
@Dr-Pongo - Unlikely. We're behind on delivering the MPV of the upgrade to USWDS v3. That's our priority. Once that MVP is ready then we'll re-introduce sprints focused on the backlog. That's currently looking like May. There is a chance that my other team working on Veteran-Facing Forms will need this functionality as they work on Forms. In that case, this may happen in the next few weeks as the Design System team converts the Forms library to use our current web-components.
