### ISSUE TITLE
Update Telephone to include SMS - Documentation

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1298]
## Description
Once [the SMS option has been added](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1246) to the va-telephone component, we should update the guidance for Telephone on design.va.gov to include details for SMS.

## Details
- https://design.va.gov/components/telephone
- https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/WKjQYn0

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
Confirmed that all docs are now up-to-date with the SMS option.
