### ISSUE TITLE
Determine how a USWDS3-based web component will get its color

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#1322]
## Description

The DST is making an effort to base our Web Components around USWDS3 - this means relying on their CSS & SVG assets and modeling our markup after theirs. Certain aspects of typography, such as font family and size, can be inherited globally, but color doesn't work the same way. Additionally, we may have some components and/or colors that deviate from what USWDS3 defines and uses, so how will a web component that is built using USWDS as a dependency get its color values for those scenarios where we may deviate?

## Details

One possible solution is instead of making `uswds` a direct dependency of our `web-components` package, we add our `css-library` package as a dependency to `web-components`. This is the package where we consume `uswds` and choose what we provide to VFS teams under the VADS namespace, and we have [done discovery on how to override color tokens](https://github.com/department-of-veterans-affairs/component-library/pull/493#discussion_r935762486)

---

Another option that we could use as a fallback is to import the USWDS sass modules as they are, and then add our custom color override after the import, similar to [this pattern](https://github.com/department-of-veterans-affairs/component-library/pull/514/files#diff-b9371b1eb88c2ce2201bd06c9bbe9342c0079778e82e3a0db59ebeee78d4b535), and it might look like:

```css

@import 'usa-accordion/src/styles';
@import '../../mixins/focusable.css';

.usa-accordion__button {
   color: var(--color-gray-dark);
}
```
This CSS variable pattern is already in place:

- [Component CSS](https://github.com/department-of-veterans-affairs/component-library/blob/bb1bcb44d2eb724fbbe70da96f8e3bb06f7eb551/packages/web-components/src/components/va-additional-info/va-additional-info.css#L31)
- [CSS variable definitions](https://github.com/department-of-veterans-affairs/component-library/blob/bb1bcb44d2eb724fbbe70da96f8e3bb06f7eb551/packages/web-components/src/global/variables.css#L5-L37)

And if we were to go this route, we would probably remove color definitions as something that happens in our web component library and instead rely on a [StyleDictionary export](https://github.com/department-of-veterans-affairs/component-library/blob/bb1bcb44d2eb724fbbe70da96f8e3bb06f7eb551/packages/css-library/config.json#L4-L13) based on the tokens that we define.

## Acceptance Criteria
- [ ] We have a clear approach for how our USWDS3-based web components can:
    - [ ] Use a USWDS color token that is already part of the overall pallette, but not selected as a default
    - [ ] Override a color value to be something that is part of the VA Design System but not USWDS

**Comment by jhonnyoddball** [comment]
## Recommended solution

A testing [PR](https://github.com/department-of-veterans-affairs/component-library/pull/581) was created to simulate this behavior.

The recommended solution will be making `uswds` and `css-library` as direct dependencies of our `web-components` package. Therefore, we will be able to include the full paths into `stencil`.

```
      includePaths: [
        '../../node_modules/@uswds/uswds/packages/',
        '../../node_modules/@department-of-veterans-affairs/css-library/src/tokens/',
      ],
```

We will be importing from `variables` tokens from `css-library` to access our custom colors, followed by using the path from `uswds` to import the sass modules directly into each component.

Once that is done, we could override the custom colors like this:

```
@import 'variables';

@import 'usa-label/src/styles';
@import 'usa-input/src/styles';

// ***** OVERRIDES ***** //

.usa-focus {
  outline: $color-orange solid 4px;
}

.usa-input--error {
  border-width: 4px;
  border-color: $color-primary;
  border-style: solid;
  padding-top: 4px;
  padding-bottom: 4px;
}
```

### NOTE
since we will be overriding some colors while we do the full transition, we will need to do some cleaning afterwards.

We should use the following comment:

```
// ***** OVERRIDES ***** //
```

So, we can search for it and go back to do the clean up

**Comment by jhonnyoddball** [comment]
Color tokens will be added in [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1409)
