### ISSUE TITLE
[Alert] - Update guidance

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1327]
## Description
We need to update our guidance on the Alert page to address the following:

- When to use a background vs. full width alert
- Where to place background alerts on the page
- Show the different levels of "Info" in ascending order, including mentioning Featured content

Ticket #1317 will handle the reorganization of the content under the Alert umbrella.

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by GnatalieH** [comment]
@humancompanion-usds and @allison0034 here's the ticket I created to address updating Alert guidance. If something is missing please let me know and I'll update the ticket.

**Comment by humancompanion-usds** [comment]
We already filed #1317 for reorganizing. Let's just use this ticket for updating the guidance.

**Comment by GnatalieH** [comment]
Before I create a PR to update the Alert guidance on design.va.gov, I am making an outline of the existing Alert content next to some examples of different alert placements. I am gathering this work in a Mural. [Here is that link](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1666809961448/e4033eda8bed1f392088a2fe02d25a0499bbd5a1?sender=u851998f98038e0f1e2da4592). The Mural is editable to visitors, so anyone can comment or contribute. The placement guidance isn't ready for review, yet, but I wanted to share this WIP. There is a lot of Alert content, so I'm trying to understand how placement should fit in within the existing content (which we're going to reorganize, soon).

CC @allison0034 and @humancompanion-usds. I'll send a meeting invite to Allison and Sara Sterkenburg so we can start discussing the content organization.

**Comment by GnatalieH** [comment]
And [here's a link to the PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1340) I created to update the Alert Placement guidance.

**Comment by GnatalieH** [comment]
@caw310 this ticket will carry over to Sprint 15. Per Matt's latest Slack comment on 11/18:

"I'd like to keep going through the examples you collected so we can further refine why background-only Alerts exist and when, and when not, to use them. It's still pretty nebulous at the moment. We're getting there but not quite well defined yet."

Thanks.

**Comment by GnatalieH** [comment]
@humancompanion-usds updated [the PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1340) and tagged you. Ready for review. Thanks.

**Comment by GnatalieH** [comment]
Closing as PR has been reviewed by Matt and merged.
