### ISSUE TITLE
Process list component - Add Figma example of dynamic variation to Storybook

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1328]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

va-process-list

### What is the nature of this update?

- [ ] How to build this component/pattern
- [X] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [X] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Somehow we missed updating this one in Q2 and it's lacking in details:

* We show only one example of the process list leading some to believe that is the only instance.
* We don't connect the component guidance to the Templates > Form guidance > Introduction page (which links out to github and should be brought into the Design System) thus users don't know when to use this component.
* No link to Sketch from design.va.gov
* Storybook does not show states that Sketch has.

### Additional Context

This came up in a Slack thread today. I can see how teams would be confused given the lack of clear guidance and examples.

**Comment by humancompanion-usds** [comment]
I added one example and filled out the guidance. The other items remain to be done though:

* [ ] Connect the component guidance to the Templates > Form guidance > Introduction page so folks know which page this component should appear on
* [ ] Link to Sketch from design.va.gov
* [ ] Update Storybook to show the states that Sketch has

**Comment by allison0034** [comment]
Brian DeConick mentioned some accessibility issues with the current process map and has suggested updating the guideline text:

**When to use a process list**
Displaying high-level sequential steps. Use process lists to create a clear hierarchy and help users easily differentiate between individual high-level steps or stages in a process.
_Just adding another "high-level" in there for emphasis!_

**When to consider something else**
When you are instructing users to take specific actions that don't require explanation, not describing high-level steps. This component isn't a good fit for steps like "Click the login button" or "Right-click and select Save As" that don't require any additional description.
_There's probably a better way to say that?_

**Accessibility considerations**
Don't use headings alone. Each step should have both a heading and content that helps describe the step in more detail.

**Comment by humancompanion-usds** [comment]
Deployed the Sketch link and Brian's guidance updates. Will now alter the title to reflect the remaining work in Storybook.

**Comment by humancompanion-usds** [comment]
Storybook and Figma are now in sync.
