### ISSUE TITLE
Experimental Design [List Item]

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/vets-design-system-documentation#1330]
## What
> The ListItem component would define the style to use for any item in a list. It would consist of a header, subheader, and CTA with variations as needed to accommodate different use cases.

## Purpose
> This gives us a standard appearance and styling for any simple unordered list.

## Usage
> Any time we are showing a list to the user.

## Behavior
> The list item component would have three parts to it: 
- Header
- Subheader (optional)
- CTA (optional)

## Examples
> In the new Claim Letters page as part of the Decision Letter Download feature, we created a style for the list items that could be standardized for similar types of simple lists across VA.gov.
<img width="517" alt="Screen Shot 2022-11-10 at 11 20 00 AM" src="https://user-images.githubusercontent.com/95102058/201149915-568974e4-5c97-4fa3-bac2-e9775b3aa974.png">

## Accessibility
> See [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46508#issuecomment-1297661689) for a11y considerations that led to this ultimate design.

## Guidance
> Lists are used for repeated, continuous grouping of information. They consist of lines of text and, optionally, icons, links, or buttons. [Reference](https://m2.material.io/components/lists#anatomy)

## Research (optional)
> Our list items tested well in the [Decision Letter Download Usability Studies](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-08-Decision-Letter-Download/research-findings.md) conducted in September 2022.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by skylerschain** [comment]
Great, looking forward to it!

**Comment by caw310** [comment]
Follow up from DSC meeting on 12.2
- Go forward and use it. 
- DST will add documentation to our backlog

**Comment by humancompanion-usds** [comment]
@allison0034 - I'd like to get Lists added as a component (moving what we have out of Typography). Would you be able to find some time soonish to do an audit?

**Comment by skylerschain** [comment]
@humancompanion-usds I've got a[ local Figma component here](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=330-3078&mode=design&t=wvtZTrFtou4gigoz-4) if you want to take a look at it. I set it up to scale between desktop/mobile.

**Comment by allison0034** [comment]
@humancompanion-usds I have created a [Mural and started grabbing screen shots](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1706296373778/a5ce1a2456f811ec88d1de3eee19d6050345f330?sender=u045df875f30f7e9f34339908). Are there any specific screens you want?

**Comment by humancompanion-usds** [comment]
@allison0034 - I don't have any particular screens in mind and the Mural is helpful. A couple of things:

1. Mural degrades the quality of the image when you import it so I can't use the screenshots in there. So if you can be sure to keep the originals in a folder and upload them here or I can point you to where they'll go in this repo and you can drop them there.
2. I'm hoping to show ordered, unordered, and any definition lists. The Appointments example is a good one because it gets close to search results (which is also in my queue) and thus will help me define the borders of both.

**Comment by humancompanion-usds** [comment]
Updated example from Skylar:

https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=80-1335&mode=design&t=johV8B4Ax0nesGFj-4

"Recent Activity" section of the Status tab, and the "Documents filed" section of the Files tab. The idea is that those are the same component.

Also here: https://www.figma.com/file/FmPqyjeCs4shI0oXQiuWLD/CST---Decision-Letter-Download?type=design&node-id=0-12067&mode=design&t=vqoNRSHtri3A6PrA-4

**Comment by humancompanion-usds** [comment]
Created a new issue to track adding List to Figma:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2510
