### ISSUE TITLE
Experimental Design Progress Bar - Segmented

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/vets-design-system-documentation#1333]
## What

- Introduce a current step or chapter segment color
- Remove the form title and subtitle out of the component and relocate them to a simplified VA.gov header navigation 

## Purpose

- Indicate where a user is in a multi-step process that spans several different pages that can be organized into three or more high-level steps or chapters. This helps users understand the progression of long forms and reduces the uncertainty as they complete each screen. Reference: https://designsystem.digital.gov/components/step-indicator/
- Reduce the cognitive load required to complete a multi-step process by quickly navigating users to the first heading/question and start interacting with the form. Reference: https://design.va.gov/patterns/help-users-to/complete-a-sub-task  
- Reduce the chances of users leaving a form or process (that doesn't support finishing the form later) before completing all the required steps.
- Reduce the cognitive load required to complete a form or process that doesn't support finishing it later, are time-sensitive and/or does not have a home within the VA.gov sitewide IA or include a related navigation pattern on the page.

### When to use this component 

- Multiple steps and screens for a single interaction that spans several different pages that can be organized into three or more high-level steps or chapters. This helps users understand the progression of long forms and reduces the uncertainty as they complete each screen. 
- Long forms with conditional logic. Use progress bar - segmented when the number of chapters is constant, but the number of steps within a chapter might change due to user input. 
- Forms or processes that don't support finishing it later, are time-sensitive and/or does not have a home within the VA.gov sitewide IA or include a related navigation pattern on the page.

### When to consider something else 

- Very short forms. Don’t use a progress bar - segmented for short forms without chapters. If a form or process has fewer than three chapters, don’t use a progress bar - segmented.

## Behavior

- The segments in the progress bar should equal the total number of chapters in the form or process. 
- Use the current step or chapter segment color to indicate what step or chapter a user is in the process. 
- Forms or processes using a subtitle can be included immediately after the form title in normal case.
- Hide the VA seal on desktop screens to anchor all pages with the form title as a replacement for a traditional h1 that's persistent across all form pages.

## Examples

[Patient Check-In prototype with simplified header/footer and progress bar - segmented
](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/prototype/a/E50121F2-F405-46C7-9FE6-8505525F7010)

<img src="https://user-images.githubusercontent.com/101129355/201193527-db6bac46-aafe-4c6d-86ee-549aadb8d39a.png" width=200>

<img src="https://user-images.githubusercontent.com/101129355/201193687-dbd88fdf-9a58-4820-b7a9-54bf21cfb82a.png" width=200>

## Accessibility

- The form title should take on the banner landmark for assistive technologies. A banner landmark role overwrites the implicit ARIA role for the container element upon which it is applied. It should be reserved for globally repeating sitewide content that is generally located at the top of every page.

## Guidance

N/a

### Research that has already been conducted

- 0.4% of users (131,136) within a 30-day period interacted with any of the VA.gov footer navigation superlinks while using VA's Pre-Check-In product. In addition, 6.6% of those same users interacted with the VA.gov header menu and 5% with the VA.gov Sign In, respectively, which in most scenarios resulted in an incomplete Pre-Check-In process. Reference: [Header and footer events for patient check in.xlsx](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/9983720/Header.and.footer.events.for.patient.check.in.xlsx)
- Veterans often think they’re checked in, when they’re not according to an analysis of multiple research studies that included 117 Veterans and caregivers, 81 staff members and an additional 626 comments from VSignals reports. (Reference: [Eliminating Veteran Confusion at Check In.pdf](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/10007270/Eliminating.Veteran.Confusion.at.Check.In.pdf)). Whether it’s from confusing Pre-Check-In with Check-In or using the kiosks in the clinics, adding a progress bar to Check-In will help those Veterans that initiate the eCheck-In process to understand the progression of the process and reduce uncertainty as they complete each step. For example, there were 5,134 exits (or 3.55%) from 144,597 pageviews within a 30-day period of key pages of the Check-In process according to [Google Analytics](https://analytics.google.com/analytics/web/#/report/content-exit-pages/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22appointment-check-in%22,0%5D,%5B0,%22analytics.pagePath%22,%22RE%22,%22details%7Ccontact-%7Cnext-of%7Cemergency-%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25/).  
- A Veteran in a [recent research study for Patient Check-In](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/Spanish/Spanish%20Check-in%20%26%20Toggle%20Design%20Research%20Report.pdf) said, "The top where it says sign in and menu could be confusing to those that are just trying to sign in to an appointment." 

### Research we plan to conduct

TBD

## Code (optional)

N/a

**Comment by caw310** [comment]
This request was discussed in 11.18 DSC meeting. 
Action items: 
Go ahead and research this 
DST needs to figure out where we are currently so will add a backlog item to do an audit.

**Comment by benbrasso-agile6** [comment]
@caw310 for now, the PCI Team is not prioritizing the implementation and testing of this experimental component. The team feels that we would need to make more changes before releasing. E.g., changes around accessibility support and making it "fit" for an app where the questions change based on how Veterans respond and that has a short amount of questions. We may pick this back up at a later date.

**Comment by humancompanion-usds** [comment]
We have not discussed this recently but, our plan at the moment is to adopt the USWDS Step Indicator. In fact, we have that component in our [MVP for the USWDS v3-based VA Design System](https://design.va.gov/storybook/?path=/docs/uswds-va-segmented-progress-bar--default) and the Veteran-facing Forms team will be testing it out this quarter.

**Comment by humancompanion-usds** [comment]
@benbrasso-agile6 - Do we still need this given that we have the v3 Step indicator now with these options?

**Comment by benbrasso-agile6** [comment]
No sir
