### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Pezequiel1976** [department-of-veterans-affairs/vets-design-system-documentation#1336]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1.
2.
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

**Comment by bkjohnson** [comment]
Closing empty issue.
