### ISSUE TITLE
Experimental Design Simplified VA Header and Footer

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/vets-design-system-documentation#1339]
## What

- Simplified VA.gov header navigation that removes Sign In and the menu
- Simplified VA.gov footer navigation that removes link lists and superlinks
- Introduce a site section name or form title, along with subtitle, in to the VA.gov header navigation 

## Purpose

- Reduce the chances of users leaving a form or process (that doesn't support finishing the form later) before completing all the required steps.
- Reduce the cognitive load required to complete a form or process that doesn't support finishing it later, are time-sensitive and/or does not have a home within the VA.gov sitewide IA or include a related navigation pattern on the page.
- Reduce the cognitive load required to complete a multi-step process by quickly navigating users to the first heading/question and start interacting with the form. Reference: https://design.va.gov/patterns/help-users-to/complete-a-sub-task

### When to use this component 

- Forms or processes that don't support finishing it later, are time-sensitive and/or does not have a home within the VA.gov sitewide IA or include a related navigation pattern on the page. 

## Behavior

- Forms or processes using a subtitle can be included immediately after the form title in normal case. 
- Hide the VA seal on desktop screens to anchor all pages with the form title as a replacement for a traditional h1 that's persistent across all form pages.   

## Examples

[Patient Check-In prototype with simplified header/footer and progress bar - segmented
](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/prototype/a/E50121F2-F405-46C7-9FE6-8505525F7010)

[Desktop version](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/a/L0LVoDQ)

<img src="https://user-images.githubusercontent.com/101129355/201193527-db6bac46-aafe-4c6d-86ee-549aadb8d39a.png" width=200>

## Accessibility

- The form title should take on the banner landmark for assistive technologies. A banner landmark role overwrites the implicit ARIA role for the container element upon which it is applied. It should be reserved for globally repeating sitewide content that is generally located at the top of every page. 

## Guidance

N/a

### Research that has already been conducted

- 0.4% of users within a 30-day period interacted with any of the VA.gov footer navigation superlinks while using VA's Pre-Check-In product. In addition, 6.6% of those same users interacted with the VA.gov header menu and 5% (6,555 of 131,136 sessions) with the VA.gov Sign In, respectively, which in most scenarios resulted in an unsuccessful Pre-Check-In. The Patient Check In (PCI) product does not support full authentication, and therefore the presence of VA.gov Sign In increases the chances of Veterans leaving the Pre-Check-In process (as well as Check-In) before completing all the required steps. Reference: [Header and footer events for patient check in.xlsx](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/9983720/Header.and.footer.events.for.patient.check.in.xlsx)
- Average page load time for Check-In pages (11.19 seconds) is almost triple than the VA.gov average (4.08 seconds) according to [Google Analytics](https://analytics.google.com/analytics/web/#/report/content-site-speed/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22appointment-check-in%22,0%5D%5D&explorer-table.plotKeys=%5B%5D/). In a time-sensitive interaction like checking in for an appointment, page load time is of utmost importance to success. Therefore, the Modernized Check-In Experience Team hypothesizes that the number of check-ins will increase if the VA.gov header and footer files are not loaded within the PCI product, which would decrease the average page load time.  
- A Veteran in a [recent research study for Patient Check-In](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/Spanish/Spanish%20Check-in%20%26%20Toggle%20Design%20Research%20Report.pdf) said, "The top where it says sign in and menu could be confusing to those that are just trying to sign in to an appointment." 

### Research we plan to conduct

TBD

## Code (optional)

N/a

**Comment by caw310** [comment]
This request was discussed in the 11.18 DSC meeting. Decision is for check-in team to proceed with testing and talk to Patrick about having a conversation to find out the legal requirements for what needs to be in the footer.

**Comment by humancompanion-usds** [comment]
Header - Minimal is out: https://design.va.gov/components/header/header-minimal

If your team is interested in using it reach out in #platform-design-system.

Footer - Minimal is up next.

**Comment by humancompanion-usds** [comment]
Footer - Minimal is in Storybook: https://design.va.gov/storybook/?path=/docs/components-va-minimal-footer--default

I need to write the documentation next sprint.

**Comment by benbrasso-agile6** [comment]
Cool. Let you know if Check In dives in.
