### ISSUE TITLE
[Alert] - Add mobile size Default alert variations to the Sketch library

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1341]
## Description
Currently the only symbol options under Alert / mobile are Background only and Background only with icon. This gives the impression to Designers that only the Background style of alert can be used in mobile viewports. 

## Details
We should include mobile-size Default alerts in all variations (Info, Warning, Success, Error, Sign-in/prompt) in our Sketch library.

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by humancompanion-usds** [comment]
@GnatalieH - I went ahead and grabbed this. Add mobile for the default Alerts:

https://sketch.com/s/610156b6-f281-4497-81f3-64454fc72156

Let me know if that link doesn't work. I just saved it into the Pattern library but I have not starred the release yet. 

I also updated the desktop Alerts to match the icon size and spacing which it looks like we missed last time we updated these. Anyway, give it a once over and if it looks good I'll star the release to get it out there.

**Comment by GnatalieH** [comment]
> I also updated the desktop Alerts to match the icon size and spacing which it looks like we missed last time we updated these. 

@humancompanion-usds updated the desktop icon size and spacing to match the coded components?

I think everything looks consistent and fine. I do wish the icon size was smaller on the mobile Default alerts so there wasn't so much negative lefthand space. I hear complaints from Designers and from Allison about this issue, often. I know some alert content can get quite long, and the icon effectively takes up 25% of the horizontal screen real estate which results in lots of scrolling and just kind of looks wonky. But that's beyond the scope of this ticket, I reckon. Thanks!

**Comment by humancompanion-usds** [comment]
Starred a release in Sketch. Done.
