### ISSUE TITLE
[Header] - Align Sketch assets with Production

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1342]
## Description
The authenticated and unauthenticated header symbols in Sketch do not match what's in Production and they also do not align with the VA DS spacing units. We should fix this so Designers can use header symbols with the proper specs, which means building the header navigation items as buttons in Sketch. 

The header and page template symbols should be examined. The mobile header was updated recently, so this work mostly applies to the desktop and tablet sizes.

## Details

**Sketch asset:**
![sketch-header](https://user-images.githubusercontent.com/88347129/201973590-08165f92-efc7-42f9-97af-881ba6b9f0ff.png)

**Production:**
<img width="384" alt="Screen Shot 2022-11-14 at 5 39 05 PM" src="https://user-images.githubusercontent.com/88347129/201973733-95441a89-b7ce-4ec7-a7fc-b5639a4826f7.png">

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
@LillyBoot @babsdenney , do we still need this ticket? Or can we close?

**Comment by babsdenney** [comment]
@caw310 @LillyBoot This hasn't been fixed yet. We can keep this ticket open.

**Comment by caw310** [comment]
@danbrady has this been fixed in Figma?

**Comment by danbrady** [comment]
Yep, when we brought it into Figma, we aligned it to the production header and not Sketch. Closing.
