### ISSUE TITLE
Text input error text doesn't change languages when toggling

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/vets-design-system-documentation#1350]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When toggling the language while an error state is active, the error text doesn't update with new language. It does update if the error gets triggered again.
### Initial toggle after error present
![step1](https://user-images.githubusercontent.com/13967174/203449295-d8aaba47-930d-4a61-a18f-8282e35469e6.gif)

### Error triggered again
![step2](https://user-images.githubusercontent.com/13967174/203449312-35731e2f-322a-4bcc-a990-bb6766b2d56c.gif)

## What I expected to happen
I expect the error message to change to the selected language when toggled.

## Reproducing
- Formation version:
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1. Visit https://www.va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287
2. Don't fill out the name form field and click continue
3. After the error message renders, click either Spanish or Tagalog
4. Observe that the error message stays in English

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jhonnyoddball** [comment]
@brianseek the `<VaTextInput>` does not handle the error messages automatically. You have to handle that on your page

```
        <VaTextInput
          autoCorrect="false"
          error={lastNameErrorMessage}
          label={t('your-last-name')}
          name="last-name"
          onInput={updateField}
          required
          spellCheck="false"
          value={lastName}
          data-testid="last-name-input"
          onKeyDown={handleEnter}
        />
```

You need to handle the `lastNameErrorMessage` same as any other translation variable, ex: `t('your-last-name')`. Make sure you have an entry in the `translation.json` file for every language.

**Comment by brianseek** [comment]
> @brianseek the `<VaTextInput>` does not handle the error messages automatically. You have to handle that on your page
> 
> ```
>         <VaTextInput
>           autoCorrect="false"
>           error={lastNameErrorMessage}
>           label={t('your-last-name')}
>           name="last-name"
>           onInput={updateField}
>           required
>           spellCheck="false"
>           value={lastName}
>           data-testid="last-name-input"
>           onKeyDown={handleEnter}
>         />
> ```
> 
> You need to handle the `lastNameErrorMessage` same as any other translation variable, ex: `t('your-last-name')`. Make sure you have an entry in the `translation.json` file for every language.

@jhonnyoddball right, we do have the message translated in all of our translation.json files. It's key is `please-enter-your-last-name`

**Comment by jhonnyoddball** [comment]
I believe this issue has nothing to do with the `<VaTextInput>`, however, I think it's more in how the translation has been setup.

[Based on](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/check-in/utils/validateVeteran/index.js#L32-L39):

```
setLastNameErrorMessage();

  let valid = true;

  if (!lastName) {
    setLastNameErrorMessage(i18next.t('please-enter-your-last-name'));
    valid = false;
  }
```

This is only going to work when there is validation.

The way I understand the code, it only translates when you click on the button `Continue`. If you open [check-in](https://www.va.gov/health-care/appointment-check-in/verify)  and just click `Continue`, you will see the error in English. Now, if you click on `Español`, the error will stay on English because the link it not validating the error, but if you click on `Continuar`, it will translate because the validation is happening there, and therefore it will `setLastNameErrorMessage(i18next.t('please-enter-your-last-name'));`

**Comment by brianseek** [comment]
@jhonnyoddball ah okay I think that makes sense to me. I have an idea on how we could refactor this. Thanks for looking into it! Feel free to close on your end and I will open a new issue if we have any other feedback after refactoring this.

**Comment by jhonnyoddball** [comment]
Sounds good
