### ISSUE TITLE
(SCREENREADER) VaModal reads close button incorrectly

### ISSUE THREAD

**Issue by EClancyVA** [department-of-veterans-affairs/vets-design-system-documentation#1351]
When displaying a VaModal with a status of warning, the screen reader will immediately read "Close [Modal Title], to activate press enter". It will then read the Modal Title again, then "Hollow square bullet" (which is, I think, trying to read the warning symbol next to the title), and then it will finally read the Modal Title a third time. 

If you open the modal again though, it will skip reading the close button and the first two titles being read, meaning you don't hear the "to activate press enter" prompt. 

Ideally I would imagine when warning modal is opened, it should read the title of the modal once, and then the close modal prompt every time the modal is opened. 

We're also noticing difficulty including grammar symbols. In our case, the title is "The following error(s) were found:". Hearing "paren S paren" and "colon" 3 times makes it very difficult to follow. If it was possible to instead pass in an aria label that reads differently than the modal title itself, that would solve the issue.

**Comment by jamigibbs** [comment]
Closing as duplicate because I believe this issue was flagged as part of the a11y review here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2100
