### ISSUE TITLE
Icon web component - Accessibility review

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1365]
## Issue Description
We need to conduct a full accessibility review of the Icon web component. The component can be viewed in Storybook here: [insert Chromatic link here]

## Tasks
- [ ] Full accessibility review of the component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] If necessary, discuss any accessibility issues found with the engineer who developed the component
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by humancompanion-usds** [comment]
@caw310 - Didn't va-icon already go through staging review? Do we need an additional a11y review or is this just an orphaned ticket?

**Comment by caw310** [comment]
@humancompanion-usds I thought I had submitted va-icon for staging review but it seems I did not. I've looked through tickets and my notes and cannot find the request, only a link to Sketch. I have a vague recollection that we decided to hold off but cannot remember why. I can submit it now.

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1365?planning-poker) with Zenhub @rsmithadhoc

**Comment by rsmithadhoc** [comment]
@caw310  This component looked good in my testing, no follow-up issues needed. I'll close this one out.
