### ISSUE TITLE
Update Link component with calendar variation - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1368]
## Description
Add or update documentation and guidance for Link component to include guidance on the calendar variation the VAOS team added on design.va.gov. When adding a new component, use the [component documentation template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_components/template.md).

## Details
https://github.com/department-of-veterans-affairs/component-library/pull/583
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13011
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/603

Be sure to use the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option. If this is a new component that has not yet gone through Staging Review, use the "Use with Caution: Candidate" label.

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by GnatalieH** [comment]
I've added a Calendar variation of link to the Sketch library [here](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/OmKlgMm). @humancompanion-usds the Calendar variation exists on Storybook, would you like me to add it to the design.va.gov/components/link examples?

**Comment by humancompanion-usds** [comment]
Looks good. Yes, please add it to the Link component page on design.va.gov as well.

**Comment by GnatalieH** [comment]
Thanks @humancompanion-usds. I created a [PR for the Calendar variation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1418) I just added.
