### ISSUE TITLE
Audit for new pattern to Help users to check the status of their claim

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1370]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Pattern

### What is the name?

Help users to check the status of their claim

### What is the nature of this update?

- [X] How to build this component/pattern
- [X] When to use this component/pattern
- [X] When to use something else
- [X] Usability guidance
- [X] Accessibility
- [X] Implementation
- [X] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

This new pattern was prioritized 5th by DSC and VFS teams. We'll need to start with an audit. I'm honestly not sure how this is done today and the votes for this seemed to be more about us all wanting VA.gov to do this better, rather than a need to document how we do this in order to spread the information. Thus I'm not sure we can proceed until a VFS Team really takes up the mantle. But my understanding may be wrong. Let's figure out how Veterans can check their claim status today and document those to start with.

Next step would be to talk to Martha, Kristen, and Kevin to understand better how we do this today and what they are hoping the pattern could provide.

**Comment by GnatalieH** [comment]
[Mural link](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1675203106522/be466941b5e520699bce18534edc57a329b6fd5a?sender=u851998f98038e0f1e2da4592) (WIP).

**Comment by GnatalieH** [comment]
Here are the types of **claims or appeals** that can be made:

**Compensation**

- Disability compensation (including claims based on special needs like an automobile or clothing allowance)
- Veterans or Survivors Pension benefits
- Special monthly compensation (such as Aid and Attendance)
- Dependency and Indemnity Compensation (DIC)
- Burial allowance to help pay for a Veteran’s burial and funeral expenses

**Other benefits**

- VA health care
- GI Bill or other education benefits
- Veteran Readiness and Employment (VR&E)
- A home loan Certificate of Eligibility (COE)
- A Specially Adapted Housing (SAH) or Special Housing Adaptation (SHA) grant
- Life insurance
- A pre-need determination of eligibility to be buried in a VA national cemetery

**Comment by GnatalieH** [comment]
Comment from @artsymartha68 about frustrations Veterans face when trying to check the status of a claim:

> You’ll see on the Reddit Veteran boards that folks say they maximize their logins and get locked out, or have to uninstall the mobile app bc it makes OCD-like checking way too easy at all hours of the night. Evidently VA.gov doesn’t give as many details as eBenefits? So then they’ll log into eBen and try to see if they can find out more. Then they complain eBen doesn’t have the same info as VA.gov or the app.

**Comment by GnatalieH** [comment]
Here are the ways a user can check the status of a claim/appeal (this is also noted in the [Mural board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1675203106522/be466941b5e520699bce18534edc57a329b6fd5a?sender=u851998f98038e0f1e2da4592)):

- Claims Status Tool on VA.gov
- eBenefits.va.gov 
- VA mobile app

Disability claims can take over 100 days to process, whereas healthcare claims are usually around 10 days. @humancompanion-usds suggested we follow up with documenting the Help users to stay informed of their application status pattern, since claims/appeals status is usually handled through the Claims Status Tool.
