### ISSUE TITLE
va-textarea issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#1372]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

While using the `va-textarea` web component, several issues popped up:

- Internal text size is calculated to be 13.33 px (way too small). The label font size is 16px, so it should at least match this.
- Error message includes "Error" which should be hidden by the `sr-only` class (undefined?) 

<img width="700" alt="textarea with error showing 'Error' prefixed to message, and internal to the text area is a repeated 'lorem ipsum' in a much smaller font size" src="https://user-images.githubusercontent.com/136959/205084395-6c3ab357-60f0-4cda-ad20-6f86ae7b3cd8.png">

## What I expected to happen

- "Error" prefix on error message should not be visible, but still read out by screenreaders
- Font inside the textarea should be larger

## Reproducing
- Formation version: All
- Device: (e.g. iPhone 8, Macbook) Any
- Browser: (e.g. Firefox, IE 11) Any

Steps to reproduce:

1. Go to [textarea storybook page](https://design.va.gov/storybook/?path=/docs/components-va-textarea--default)
2. Type anything into the text area to note the smaller text size
3. Set the "error" string parameter to see the "Error" message prefix

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment]
Thanks for bringing this to our attention @Mottie. I'm seeing that this component does not have the a11y import for that css class and a font size isn't set on the input. I'm not entirely sure when or why that was removed (or how long it's been this way) but I'll expedite a PR for it.

**Comment by Mottie** [comment]
You're the best! Thanks!
