### ISSUE TITLE
VaModal component is obscured by the navbar in the VA.gov header

### ISSUE THREAD

**Issue by mmoyer-va** [department-of-veterans-affairs/vets-design-system-documentation#1374]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

There is a chance this may be related to [#49518](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49518), pertaining to Medallia modals interacting w/ VA.gov modals.

## What happened

When opening a VaModal component on a small screen, the modal appears underneath the header navbar -- it has a lower z-index, and so is partially covered. In addition, the text in the far upper-right ("Search", "Contact us", etc.) is also at this higher z-index.

Here are two examples of this in action. Note the navbar obscuring the modal, but also the bright white text, indicating that it has a higher z-index than the gray overlay.
![image (1)](https://user-images.githubusercontent.com/87040148/205146884-b1bdab07-ace5-44ef-b8f0-8501b6aae85a.png)
![image (2)](https://user-images.githubusercontent.com/87040148/205146900-523cd9b5-d415-4bb4-8473-73a84a95fcbf.png)

## What I expected to happen

I would expect modals to have a higher z-index than all other page content, so that it is not obscured.

## Reproducing
- Formation version: ^7.0.3
- Device: I tested this on my Windows GFE, but others have confirmed it on other platforms
- Browser: Reproduced in Edge and Chrome

This appears to be happening for every VaModal component in the application, but it is easily reproducible in the new Secure Messaging application. To reproduce:
1. Go to staging.
1. Login using the ID.me user "vets.gov.user+263@gmail.com" (password [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/sm/test-accounts.md))
1. Browse to https://staging.va.gov/my-health/secure-messages/folders
1. Click "Create New Folder" to pop up a VaModal
1. Resize the browser window to push the modal towards the top

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jtmst** [comment]
I ran into this issue as well while implementing the homepage redesign soft-launch modal.  Opted to use the old Modal component as a work around.

**Comment by wesrowe** [comment]
@bkjohnson @jamigibbs, I went and dug up this bug report because Public Websites is seeing the same issue with our new modal. (Per Josh's comment, which just appeared above as I was typing.) FYSA we're on a tight timeline.

@mmoyer-va, did your team find a work-around?

**Comment by wesrowe** [comment]
I guess since Public Websites cares for the header, we could be a part of the solution. I don't feel confident we have any idea why that header element has such a high z-index, though, and that would make us very hesitant to change it. So I guess moving the modal higher would be my vote.

**Comment by caw310** [comment]
Adding @jhonnyoddball to this.
