### ISSUE TITLE
Translation buttons on Storybook require a page refresh before they work

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1387]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When navigating to a component page in [Storybook](https://design.va.gov/storybook/?path=/story/about-introduction--page), the translation buttons do not work until you do a full page refresh (ie. Command + R). This appears to be an issue for all components that have an internationalization story.

![Screen Shot 2022-12-07 at 11 34 31 AM](https://user-images.githubusercontent.com/872479/206251140-3c8cdaf4-df84-4047-8531-c56980107cdd.png)

## What I expected to happen

I expect the translation buttons to work when they're clicked without needing to do any additional steps.

## Reproducing
- Formation version: NA
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1. Navigate to a component's internationalization story on Storybook. For example: https://design.va.gov/storybook/?path=/docs/uswds-va-radio--internationalization
2. Click the "Spanish" button.
3. The "Required" text should display "Requerio" but it still displays in English.
4. Do a full refresh of the page and click the "Spanish" button again and the text now toggles.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Will be discussed in engineering meeting on 1.18. Carrying over into sprint 19
