### ISSUE TITLE
VA logo in footer points to wrong place

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#140]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
In the design system footer, when you hover over the official VA logo, the hover text says it's going to go to VA.gov. But it actually takes you to the top of the design system homepage. 

![image](https://user-images.githubusercontent.com/43381063/64450368-03ea0280-d0b0-11e9-8b2e-3d6029c8e374.png)

-->

## What I expected to happen

To be taken to VA.gov homepage

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook) PC
- Browser: (e.g. Firefox, IE 11) CHROME

Steps to reproduce:

1.
2.
3.
4.

**Comment by jaredcunha-usds** [comment]
Wow! Good catch! This has been fixed. You can see it on https://dev-design.va.gov/
