### ISSUE TITLE
Experimental Design Textarea (va-textarea) web component

### ISSUE THREAD

**Issue by mattwrightva** [department-of-veterans-affairs/vets-design-system-documentation#1410]
## What
I am proposing a "part" attribute be added to the textarea element within the VA.gov Textarea web component. 

## Purpose
This enables targetted styling of the textarea element, such as making it wider than the default max-width of 48rem. 

## Usage
I would like to be able to use this component in a form where the contents are styled to span the width of a container that is wider than 48rem in desktop view. 

## Behavior
I would like to use this component for a message field that is able to contain multiple paragraphs and line breaks that are easy for a user to see and interact with. I am trying to build in accordance with UCD designs and specifications. 

## Examples
This is what the textarea element within the Textarea web component would look like:
`<textarea part="textarea"></textarea>`

Currently the textarea has a max-width of 48rem:
(notice the _message_ field does not match the width of the other fields)
<img width="719" alt="Screenshot 2022-12-21 at 12 59 34 PM" src="https://user-images.githubusercontent.com/107576133/208993268-54993210-cbab-4d83-851a-d4908c3900a0.png">

After the change, I could style the textarea to be wider so that it fills the width of a wider container:
(notice the _message_ field matches the width of the other fields)
<img width="719" alt="Screenshot 2022-12-21 at 12 59 49 PM" src="https://user-images.githubusercontent.com/107576133/208993432-c8f3ed72-951b-4254-98c3-882b1611ac03.png">

## Accessibility
I don't see this affecting accessibility in any way. 

## Guidance
After this change, the Textarea web component can be styled similarly to the Text input web component (va-text-input) because the _Text input_ web component has a "part" attribute on its `<input />` element. 

## Code (optional)
```
<va-textarea>
   <textarea part="textarea"></textarea>
</va-textarea>
```

## Next steps
I am requesting asynchronous approval on this.

**Comment by caw310** [comment]
Request was discussed in the Jan 13, 2023 DSC meeting. Change approved. 
If you have PR for this it would speed it along so we can review and approve. If not, we will add to our backlog.
