### ISSUE TITLE
Upgrade React to v18 in `component-library`

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/vets-design-system-documentation#1415]
## Description
Based on [support request](https://dsva.slack.com/archives/CBU0KDSB1/p1672262982771759)

```
Hello, our project currently has the package "@department-of-veterans-affairs/component-library" installed 
and wondering when it will have support for React v18
The peer dependency listed for this package only supports React v17.
Our project doesn't use any of the React components, only the Web components.
```

## Tasks
- [ ] Upgrade react from v17 to v18

## Acceptance Criteria
- [ ] React dependency is at v18

**Comment by jamigibbs** [comment]
@jhonnyoddball Can you double check that Slack link to the support request to upgrade to v18? I think that the link in the description of this ticket isn't correct.

**Comment by jhonnyoddball** [comment]
Slack link updated
