### ISSUE TITLE
Error messages aren't getting translated in memorable date field

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/vets-design-system-documentation#1416]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When there is an error ex: date is entered as month: 10, day: 10, year: 22. There is an error message that appears but it is not translated to whatever language is selected.

![Screen Shot 2023-01-04 at 2 35 38 PM](https://user-images.githubusercontent.com/2982977/210638465-58e06a2f-50d1-4aca-aa7b-efb0a1993c1d.png)

## What I expected to happen

Since the labels for month, day and year are getting translated I expected the errors would as well since we are not giving the component a custom error message to render.

## Reproducing
- Formation version:
- Device: Macbook Air
- Browser: Firefox

Steps to reproduce:

1. Visit https://www.va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287
2. Don't fill out the name field
3. Fill out the DOB field with 10 10 10
4. Change language to Spanish

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jhonnyoddball** [comment]
@wullaski We have published a [new release](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v13.8.0) in the `component-library` with the fix for this issue. Please install it  and try it.

**Comment by wullaski** [comment]
@jhonnyoddball It works on initial render with whatever language you have set but doesn't change when i toggle the language to something else. I can get it to re-translate the message if I blur on the input again.

**Comment by jhonnyoddball** [comment]
The error message is only generated when validation is triggered, so it's the translation. The translation will only work when the validation triggers. You could add the trigger in the translation button.

**Comment by wullaski** [comment]
@jhonnyoddball how would I do that? The only way I know of to trigger the validation is to focus then blur on one of its inputs. Why is the error string behaving differently from all of the other strings of the web component?

https://user-images.githubusercontent.com/2982977/215107426-ea18447b-4c66-4ba3-91f9-58e4ad62b6a9.mov

**Comment by jhonnyoddball** [comment]
@wullaski Does the `Continue` button have a validation trigger?

**Comment by wullaski** [comment]
It validates the form before submitting it by checking for any errors in the application state.

**Comment by wullaski** [comment]
@jhonnyoddball I noticed the same behavior in storybook so I created another [issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1488) for this. Thanks for your help!
