### ISSUE TITLE
Experimental Design: Card Component Variation

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/vets-design-system-documentation#1419]
## What
This proposal is an alternative variation to the current card component. The differences within the new design include an icon, white background color, and gray-medium border.

## Purpose
The optional icon at the top of the card enables another level of visual communication across cards. For instance, the icon can be used to denote categories; however, they aren't limited to this use.

This light-weight background color variation also allows more focus to be on the card’s content, while still maintaining the natural grouping ability that card components provide.

## Usage
No different from the current card component.

## Behavior
No different from the current card component.

## Examples
- [V1 on this Sketch page](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/a/bgmjKmz).
  - Allison Christman and Matt Dingee shared this Sketch file with the check-in team. The team met to discuss V1 vs. V2 (since Matt didn't have a strong preference either way). We realized most other design system components currently follow a flat design aesthetic (not a lot of shadows or dimension). As a result, we narrowed down our proposal to follow V1.
- Pre-check-in 
  - <img width="319" alt="Screen Shot 2023-01-05 at 4 06 24 PM" src="https://user-images.githubusercontent.com/66287082/210880177-3fd7ecb2-a145-49ee-8c6e-34e33e681071.png">
  - <img width="322" alt="Screen Shot 2023-01-05 at 4 07 25 PM" src="https://user-images.githubusercontent.com/66287082/210880193-d1441075-8c66-4a2f-9527-647fdd9606a2.png">
- Check-in
  - <img width="322" alt="Screen Shot 2023-01-05 at 4 08 45 PM" src="https://user-images.githubusercontent.com/66287082/210880392-941b42ea-48a5-4782-87e6-beee7d57a016.png">

## Accessibility

- The color contrast will increase with this design, so accessibility will slightly improve.
- The heading should be descriptive of the icon. If not, then you need aria information on the icon.

## Guidance
No different from the current card component.

## Research (optional)
- [VAOS tested a variation of this lightweight card.
](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/research/2022-09-appts-list-usability)
- The check-in team plans to further test this design by doing a limited release to a percentage of users in production. The rollout will be evaluated based upon the following metrics:
  - Pre-check-in:
    - % change (compared to current appts design) of /intro pageviews vs. clicks on "get started" link
    - Secondary metrics to monitor: detail page pageviews, clicks on directions and phone number on detail pages
  - Check in
    - % change (compared to current appts design) of Your Appointments page vs. successful check ins
    - Secondary metrics to monitor: detail page pageviews, clicks on "check in now" button and phone number from detail pages
  - And then, do daily readouts to monitor the % change and increase rollout from there.

## Code (optional)
N/A

**Comment by caw310** [comment]
Request discussed in Jan 13 DSC meeting. DST will add guidance to cards for this variation.

**Comment by humancompanion-usds** [comment]
@kristenmcconnell or @zach-park - Can you share a link to a Sketch file that shows this new Card style at mobile AND desktop widths? I'd like to get it documented and I'm considering reusing it elsewhere so I'd like to know what your thoughts are. If that's a pointer to VAOS that is fine also.

**Comment by kristenmcconnell** [comment]
Here are VAOS's [designs](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=2%3A4&t=UuOMU236mkTXAYVQ-1) (Figma), which show desktop, tablet, and mobile variations.

**Comment by humancompanion-usds** [comment]
I've added this variation to our Sketch library. 
@babsdenney - Can you copy the 4 card additions into the appropriate future libraries?

I've also added this variation to our examples (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1814).

I'm keeping this issue open until we can extend va-card to support an icon.

**Comment by humancompanion-usds** [comment]
I'll open a new issue for the va-card extension.
