### ISSUE TITLE
Conversion to USWDS v3 Pagination - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1437]
## Description
Adapt the va-pagination component to match the [USWDS Pagination](https://designsystem.digital.gov/components/pagination/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See the [Textarea discovery](https://github.com/department-of-veterans-affairs/component-library/pull/493) for an example
According to the [plan](https://vfs.atlassian.net/wiki/spaces/DST/pages/2366275704/Plan+-+Aligning+VA+Design+System+components+with+their+USWDS+v3+equivalents), we will be using a prop if necessary to differentiate between our version of this component and the USWDS version. It may not be necessary for this component, this can be decided on a case-by-case basis

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Natalie to make sure the component and the design match
- [ ]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library

**Comment by caw310** [comment]
This may take two sprints to complete to incorporate testing and a11y testing.

**Comment by babsdenney** [comment]
Sketch pagination designs
- [Desktop](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/vREjYzd)
- [Mobile](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/4om7yJ3)

[Trussworks Storybook pagination example](https://trussworks.github.io/react-uswds/?path=/story/components-pagination--sandbox)

**Comment by it-harrison** [comment]
PR is here: https://github.com/department-of-veterans-affairs/component-library/pull/794
