### ISSUE TITLE
Memorable date picker date hint doesn't mention day

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/vets-design-system-documentation#1455]
# Bug Report

The date hint for the field reads "Please enter two digits for the month and four digits for the year.
Error." There is no mention of the day field which also requires two digits although they do get auto filled with zeros if they are only one digit. 

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Reproducing
- Device: Macbook
- Browser: Firefox

Steps to reproduce:

1. Visit https://design.va.gov/components/form/memorable-date#examples

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Closing as this is fixed.
