### ISSUE TITLE
Loading Indicator repeats the word loading with screen reader

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/vets-design-system-documentation#1457]
# Bug Report

The loading indicator component repeats the word loading if the message starts with the word loading. Maybe we could leave the aria-label out if a message is supplied.

Update: It also repeats the whole statement twice so in our case it reads "Loading, Loading your appointments for today... Loading, Loading your appointments for today..."

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When checking in to the check in experience app Voice Over states "Loading Loading your appointments for today. Loading Loading your appointments for today."

## What I expected to happen

I would expect it to just say the message "Loading your appointments for today."

## Reproducing
- Device:  Macbook
- Browser: Safari with Voice Over activated

Steps to reproduce:

1. Have Voice Over activated
2. Go to https://design.va.gov/storybook/?path=/docs/components-va-loading-indicator--default
3. Right click on the loading component and reload the frame
![Screen Shot 2023-02-27 at 3 24 57 PM](https://user-images.githubusercontent.com/2982977/221677943-3eae3044-38b3-4bf9-9050-b82f5bb65bcd.png)

4. Notice that it states both the aria-label and the aria-valuetext and that it keeps repeating for a while.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by wullaski** [comment]
@caw310 I updated the description with some additional issues with the repeating voice over. I thought it might be on our end and the way it was implemented but found that it was happening in sketch as well.

**Comment by rsmithadhoc** [comment]
This has an additional prop `aria-label` that says the "Loading" portion. This may have been added after this issue was created, but omitting that will solve that issue. I didn't have it repeat the loading message on my end on Mac, which it appears the original issue is using as well. I will close this one out.
