### ISSUE TITLE
Is there any plan to add Blazor support for the VA Design System Components?

### ISSUE THREAD

**Issue by va-timorris** [department-of-veterans-affairs/vets-design-system-documentation#1465]
## What
> It would be great to be able to use components for the VA Design System natively in an Blazor web application.

## Purpose
> Developers responsible for Blazor web application cannot easily use these components.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by Andrew565** [comment]
Yes, Web Components are compatible with Blazor: https://www.htmlelements.com/blazor-and-web-components/

**Comment by va-timorris** [comment]
I don't think this really answers my question.  The link provided seems to be for a third-party framework that provides its own components that can be used in Blazor.  My question is specifically for VA Design System components.  Right now they are react components, but I was wondering if there were any plans to have VA Design System native Blazor components as well.

**Comment by caw310** [comment]
Actually the DST was migrating to web components. There are still some React components but we are transitioning those over to web components with the plan to deprecate the React components.
