### ISSUE TITLE
Add content for Right Rail and Promo Spot on Pages > Hub Pages

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#147]
This update is for Patterns > Pages > Hub Pages

## What is the name

**Right Rail** and **Promo Spots**

## What is the nature of this update?
General documentation.  These sections currently have placeholder content and would benefit from similar content we have for the rest of the sections on this page.  

<img width="1095" alt="Screen Shot from Hub Pages" src="https://user-images.githubusercontent.com/55992116/66606350-d8ab7500-eb7f-11e9-95c1-179f98ee0817.png">

**Comment by andaleliz** [comment]
The Right Rail heading is also an `h3` instead of at `h4` like the rest; I've found a few other things like that I'll address in a PR.

**Comment by jaredcunha-usds** [comment]
I think the heading levels are correct. The right rail section is the same level as the hierarchy section, and the accordion and promo section fall under the right rail. 

But yeah, there is clearly placeholder content in there.

**Comment by andaleliz** [comment]
Gotcha. That wasn't clear to me, but content will help! Thanks for clarifying.

**Comment by KevinMHoffmanUSDS** [comment]
Noting this as it's connected to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/160#issuecomment-679126217 (@rtwell and @sshein)

**Comment by humancompanion-usds** [comment]
This is still a problem. Bumping it up in the queue.

**Comment by humancompanion-usds** [comment]
The Promo spot actually is, just now as of today, in the Design System: https://design.va.gov/components/card#media So at least we can link to that now.

**Comment by humancompanion-usds** [comment]
@taylojill - This page, and the content in question, is now here: https://design.va.gov/templates/hub#right-rail This would be great to get updated.
