### ISSUE TITLE
Set up a new app within vets-website for the DS Playground

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1477]

**Comment by caw310** [comment]
@jamigibbs , can you check Branch: ds-playground. If all is good please close the ticket.

**Comment by Andrew565** [comment]
Interesting. I'll have to look into that.

**Comment by Andrew565** [comment]
Accessible by running yarn watch and then visiting http://localhost:3001/ds-playground/

**Comment by jamigibbs** [comment]
Thanks for merging those updates from main. Verified:

![Screenshot 2023-02-03 at 9 06 19 AM](https://user-images.githubusercontent.com/872479/216637080-084139c7-ac94-4b17-a3f7-710fd47c5d22.png)


![Screenshot 2023-02-03 at 9 04 44 AM](https://user-images.githubusercontent.com/872479/216636732-a49f2b94-f4e5-46d5-a547-cfbdb329fd28.png)
