### ISSUE TITLE
Fix the build of a fresh install of vets-design-system-documentation to succeed

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1479]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The build of a fresh install (i.e. installing using npm install and bundle install for the first time as outline in our docs: https://github.com/department-of-veterans-affairs/vets-design-system-documentation#readme) currently fails with an error:

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-dom@18.2.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17" from @department-of-veterans-affairs/component-library@13.6.0
npm ERR!   node_modules/@department-of-veterans-affairs/component-library
npm ERR!     dev @department-of-veterans-affairs/component-library@"^13.6.0" from the root project
npm ERR!   peer react@"^17" from @department-of-veterans-affairs/react-components@8.0.0
npm ERR!   node_modules/@department-of-veterans-affairs/react-components
npm ERR!     @department-of-veterans-affairs/react-components@"8.0.0" from @department-of-veterans-affairs/component-library@13.6.0
npm ERR!     node_modules/@department-of-veterans-affairs/component-library
npm ERR!       dev @department-of-veterans-affairs/component-library@"^13.6.0" from the root project
npm ERR!   9 more (aria-hidden, react-clientside-effect, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"*" from @department-of-veterans-affairs/component-library@13.6.0
npm ERR!   node_modules/@department-of-veterans-affairs/component-library
npm ERR!     dev @department-of-veterans-affairs/component-library@"^13.6.0" from the root project
npm ERR!   peer react-dom@"*" from @department-of-veterans-affairs/react-components@8.0.0
npm ERR!   node_modules/@department-of-veterans-affairs/react-components
npm ERR!     @department-of-veterans-affairs/react-components@"8.0.0" from @department-of-veterans-affairs/component-library@13.6.0
npm ERR!     node_modules/@department-of-veterans-affairs/component-library
npm ERR!       dev @department-of-veterans-affairs/component-library@"^13.6.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"*" from @department-of-veterans-affairs/component-library@13.6.0
npm ERR!     node_modules/@department-of-veterans-affairs/component-library
npm ERR!       dev @department-of-veterans-affairs/component-library@"^13.6.0" from the root project
npm ERR!     peer react-dom@"*" from @department-of-veterans-affairs/react-components@8.0.0
npm ERR!     node_modules/@department-of-veterans-affairs/react-components
npm ERR!       @department-of-veterans-affairs/react-components@"8.0.0" from @department-of-veterans-affairs/component-library@13.6.0
npm ERR!       node_modules/@department-of-veterans-affairs/component-library
npm ERR!         dev @department-of-veterans-affairs/component-library@"^13.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

## What I expected to happen

I expect npm install and bundle install to succeed.

## Reproducing

Steps to reproduce:

1. git clone this repo.
2. Run npm install 
3. See error.

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

This may in fact block new team members from contributing to this repo.

**Comment by humancompanion-usds** [comment]
@jhonnyoddball mentioned in the Slack thread of the support issue for this that we may need to resolve https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1415 first or in conjunction with this issue. Let's do that soon.

**Comment by jhonnyoddball** [comment]
@humancompanion-usds I didn't encounter any errors `npm install` nor with `bundle install`. This is the first time I clone this repo

```
oddball@Oddballs-MBP vets-design-system-documentation % ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
oddball@Oddballs-MBP vets-design-system-documentation % bundle install
Bundler 2.3.7 is running, but your lockfile was generated with 2.2.22. Installing Bundler 2.2.22 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.2.22
Installing bundler 2.2.22
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/...........
Using rake 13.0.6
Fetching public_suffix 4.0.7
Using bundler 2.2.22
Fetching concurrent-ruby 1.1.10
Fetching http_parser.rb 0.8.0
Fetching ffi 1.15.5
Fetching liquid 4.0.3
Fetching forwardable-extended 2.6.0
Using rexml 3.2.5
Fetching colorator 1.1.0
Fetching eventmachine 1.2.7
Fetching mercenary 0.4.0
Fetching google-protobuf 3.19.6
Fetching rb-fsevent 0.11.1
Fetching rouge 3.29.0
Installing colorator 1.1.0
Installing forwardable-extended 2.6.0
Installing mercenary 0.4.0
Installing rb-fsevent 0.11.1
Installing liquid 4.0.3
Fetching safe_yaml 1.0.5
Fetching unicode-display_width 1.8.0
Installing public_suffix 4.0.7
Installing eventmachine 1.2.7 with native extensions
Installing google-protobuf 3.19.6 with native extensions
Installing http_parser.rb 0.8.0 with native extensions
Installing safe_yaml 1.0.5
Installing unicode-display_width 1.8.0
Fetching posix-spawn 0.3.15
Fetching webrick 1.7.0
Installing concurrent-ruby 1.1.10
Fetching kramdown 2.4.0
Installing posix-spawn 0.3.15 with native extensions
Installing webrick 1.7.0
Installing rouge 3.29.0
Installing kramdown 2.4.0
Fetching pathutil 0.16.2
Fetching terminal-table 2.0.0
Installing pathutil 0.16.2
Installing ffi 1.15.5 with native extensions
Installing terminal-table 2.0.0
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching i18n 1.12.0
Installing i18n 1.12.0
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching sass-embedded 1.0.21
Installing sass-embedded 1.0.21 with native extensions
Fetching sassc 2.4.0
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching listen 3.7.1
Installing sassc 2.4.0 with native extensions
Installing listen 3.7.1
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1
Fetching em-websocket 0.5.3
Installing em-websocket 0.5.3
Fetching jekyll-sass-converter 2.2.0
Installing jekyll-sass-converter 2.2.0
Fetching jekyll 4.2.2
Installing jekyll 4.2.2
Fetching jekyll-last-modified-at 1.3.0
Fetching jekyll-seo-tag 2.8.0
Fetching jekyll-feed 0.16.0
Fetching jekyll-redirect-from 0.16.0
Installing jekyll-feed 0.16.0
Installing jekyll-redirect-from 0.16.0
Installing jekyll-seo-tag 2.8.0
Fetching minima 2.5.1
Installing jekyll-last-modified-at 1.3.0
Installing minima 2.5.1
Bundle complete! 8 Gemfile dependencies, 38 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
oddball@Oddballs-MBP vets-design-system-documentation % 
```
