### ISSUE TITLE
Update examples on Content Style Guide> Content Principles page

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#148]
### What is the name
Content Principles

### What is the nature of this update?
The examples (`Like This`, `Not Like This`) appear to have some stray placeholder content. The phrase "service member" is repeated a few times. Screenshot attached

![content-service-member](https://user-images.githubusercontent.com/55992116/66930705-fd31a200-f002-11e9-9032-d8594ae9eff4.png)

**Comment by jenniferlee-dsva** [comment]
This isn't placeholder copy. The ellipses was to show that these are all connected variations of one word. That said, if some people are reporting that this looks like an error, it's good feedback. 

Maybe changing out the ellipses with commas might be clearer.  Will take another look. Thanks for the feedback!

**Comment by andaleliz** [comment]
Thanks for explaining that - at this point, "some people" is limited to me. I read it as an error but did not capture this as feedback from others.

**Comment by jaredcunha-usds** [comment]
Can try using quotes or some type of prepend: 

Do:
Use lower case and spaces: service member

Don't:
Use upper or mixed case, single word: Service member, servicemember, etc. 

But @jenniferlee-dsva, am I seeing the lower case, separate word "service member" under both do and don't or do I need new glasses?

**Comment by jenniferlee-dsva** [comment]
LOL - clearly this example needs more clarity. That was my apparently not great attempt at saying, 'like this - "service member"  and not like this, with numerous variations. ' I'll update for that as well!

**Comment by humancompanion-usds** [comment]
This example was removed from that page. I've also checked all other references to 'service member' and have found those to be correct. Closing.
