### ISSUE TITLE
USWDS Checkbox - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1484]
## Description
We need to incorporate the designs for the [USWDS Checkbox component](https://designsystem.digital.gov/components/checkbox/) into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
USWDS: https://designsystem.digital.gov/components/checkbox/
VA DS: https://design.va.gov/components/form/checkbox

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by GnatalieH** [comment]
@humancompanion-usds the USWDS v3 Checkbox and all its variations [are here](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/Zlak33/a/KvVOjxr) and ready for your review. I'm going to rename some symbols to better organize the variations between default, tile, and group.

**Comment by caw310** [comment]
Work is done by needs review and sign off so will carry over into next sprint.

**Comment by humancompanion-usds** [comment]
Focus state seems malformed:

![Screen Shot 2023-03-01 at 12.55.50 PM.png](https://images.zenhubusercontent.com/623c98bb27734da1243c0bb5/4b1afd05-5e8f-4900-9ebe-de9cea0407a6)

Otherwise looks good. One question: I believe we said we were not supporting disabling form fields for a11y reasons. Do we currently support disabled checkboxes? If so, keep it in Sketch. If not, we probably don't want to start supporting it. 

@caw310 - I see that our checkboxes today are still indented but are Radio buttons are not. Can you file an issue to correct that in checkbox web-component and Sketch assets if we don't have an issue already? Given that Nick is about to put checkbox (or is already) into the Forms library I'd like to get that corrected. Checkboxes should not be indented and are not in USWDS. Thanks!

**Comment by GnatalieH** [comment]
@humancompanion-usds thanks I'll fix that focus state. I've been including the disabled states because they are included in the USWDS system. I'll check with our a11y folks to confirm if we're supporting the disabled states.

**Comment by GnatalieH** [comment]
@humancompanion-usds do you mind review [the Checkbox artboard](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/KvVOjxr) again to see if the focus halo looks OK? I fixed some of the setting in the symbols. Thanks!

**Comment by GnatalieH** [comment]
Focus state is fixed. Closing this ticket. If the DST decides not to offer disabled states for form elements, the disabled symbols can easily be removed once the USWDS components are released for use by VFS Designers.

![Screenshot 2023-03-03 at 12.15.19 PM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/b0d6f36f-f941-4666-b430-9199666a27b7)
