### ISSUE TITLE
Conversion to USWDS v3 Checkbox - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1485]
Adapt the va-checkbox component to match the [USWDS Checkbox](https://designsystem.digital.gov/components/checkbox/) component and import and use the USWDS CSS for this component.

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Design documents: [add links to any design documents]
See the [Textarea discovery](https://github.com/department-of-veterans-affairs/component-library/pull/493) for an example
According to the [plan](https://vfs.atlassian.net/wiki/spaces/DST/pages/2366275704/Plan+-+Aligning+VA+Design+System+components+with+their+USWDS+v3+equivalents), we will be using a prop if necessary to differentiate between our version of this component and the USWDS version. It may not be necessary for this component, this can be decided on a case-by-case basis

USWDS: https://designsystem.digital.gov/components/checkbox/
VA DS: https://design.va.gov/components/form/checkbox

## Tasks
- [ ] Create a version of this component that imports and uses the USWDS CSS
- [ ]  Make any structural changes necessary and add a prop that determines which version of the component will be used
- [ ]  Check with Natalie to make sure the component and the design match
- [ ]  Add a USWDS story to Storybook
- [ ]  Merge component
- [ ]  Create a new release of component-library
- [ ]  Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json

## Acceptance Criteria
- [ ]  USWDS version has been created and added to Storybook
- [ ]  Design.va.gov has the latest version of component-library

**Comment by jamigibbs** [comment]
The work for this ticket will involve two components `va-checkbox` and `va-checkbox-group`:

![Screenshot 2023-02-21 at 11 12 08 AM](https://user-images.githubusercontent.com/872479/220413744-5d0ffd37-fbe6-4432-b061-f287b6d5299e.png)

**Comment by GnatalieH** [comment]
@jamigibbs I've completed all the variations of Checkbox and added them [here in Sketch](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/v/Zlak33/a/KvVOjxr).
