### ISSUE TITLE
Icons: Change "Scheduling" to "Appointments"

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#1493]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Other

### What is the name?

Foundation > Icons > Scheduling

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [X] Update to existing Forms Library documentation

### What problem does this solve?

Changing the heading from "Scheduling" to "Appointments" would clarify that [this section](https://design.va.gov/foundation/icons#scheduling) covers a broader range of features than just scheduling, including check-in and other activities that occur after scheduling.

**Comment by aagosto90** [comment]
Hi @humancompanion-usds - I touched based with @outerpress and we agreed that we'll stick with the fa-calendar icon that's being used in the appointments tool, so we will add a ticket in our backlog for My VA to change it to that from the current fa-calendar-check icon. Thanks for bringing this to my attention!

**Comment by outerpress** [comment]
@humancompanion-usds and @aagosto90  thank you! 

As for the phone icon, we've been using the alt-version icon because it has a stronger visual connection to the text next to it. We've tried a few treatments for the regular phone icon and it always looks like it's separate from the text. I think because the arc of it drags the eye away from the text, where the other one almost points to the text.

 Example:
<img width="255" alt="Screenshot 2023-02-07 at 8 19 34 AM" src="https://user-images.githubusercontent.com/2536801/217302071-08e22fcb-9bea-4259-8cb3-24303478f4a9.png">

**Comment by outerpress** [comment]
FYI @Cieramaddox

**Comment by humancompanion-usds** [comment]
@outerpress - Yeah, I don't disagree but the other icon is more widely used throughout the site. Thus if you want to lobby to change the icon everywhere then please do file an issue for us to do that across the site. Otherwise, change your usage.

**Comment by outerpress** [comment]
Sounds good @humancompanion-usds, @Cieramaddox is going to take another look at the phone icon, and we'll drop a comment here with what we decide do to.

Can you share some other spots the non-reversed phone icon is being used?

**Comment by humancompanion-usds** [comment]
The main usage is in the VCL modal. It's also in various Cards that I've seen come through, though some of those may be under your domain.

**Comment by Cieramaddox** [comment]
[Here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1595) is a minor change request ticket that was submitted on this issue
