### ISSUE TITLE
2 primary blue colors in Sketch library

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1495]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

From user Dylan Glenn: 
> I’m doing an audit of the colors [VA.gov](http://va.gov/) has in the there Color Variables and was wondering why there are two Primary colors? I believe the VA-primary is the color we had been using. Is this being sunset? or was it replaced for 508 issues?

<img width="209" alt="Screenshot 2023-02-02 at 10 29 41 AM" src="https://user-images.githubusercontent.com/52176351/216421184-0aa61af0-de4f-4e52-8301-f057a707c1d7.png">

## What I expected to happen

I expect our colors to match what we have documented in Formation: 
https://design.va.gov/foundation/color-palette

## Reproducing
Use our Sketch library to select a color:

![Screen Shot 2023-02-02 at 1 53 21 PM](https://user-images.githubusercontent.com/52176351/216422265-00dac376-d7cd-417a-a7b0-603dfbc0e107.png)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

I had noticed this but failed to raise the issue. I'm confused by it and I'm sure others are as well. We need to fix this a.s.a.p.

**Comment by humancompanion-usds** [comment]
To be clear, there are multiple problems here:

1. There are 3 "Primary"s listed in the initial menu.
2. There are 2 "primary", "primary-dark", and "primary-darker" values.
3. I can't find primary-light, lighter, or vivid in our system.
4. The colors should match the names and values in our system: https://design.va.gov/foundation/color-palette
5. That whole initial menu could use a clean-up, which should happen if we do #4.

**Comment by GnatalieH** [comment]
@humancompanion-usds I made the color variables in the Sketch file match the ones in our VA color palette. However, I kept `primary` and `secondary` colors organized in their own groups, just like `tertiary` is its own group. It seemed non-intuitive to have the primary and secondary colors all listed under the base heading, as it currently is in our [color palette](https://design.va.gov/foundation/color-palette). But I'll change it if you want me to. Thx.

**Comment by humancompanion-usds** [comment]
This is much improved. Thanks! There are still a few oddities I'd like to repair:

* Let's remove "VCL bg color" which is oddly called out but is just va-secondary-darkest. Not sure why it was ever explicitly called out. Also, it's not defined in Formation.
* I'm not sure why there are 9 colors that are not categorized. Can we clean that up? White, black, gray dark, and link-default are already elsewhere. Success looks incorrect to me. The rest could move into "Base".

**Comment by GnatalieH** [comment]
@humancompanion-usds I just cleaned up those 9 uncategorized colors. Every color variable is now under a group heading.

**Comment by humancompanion-usds** [comment]
On the Canvas tab for colors I noticed we seem to have "Base" and "base":
![base-and-Base](https://user-images.githubusercontent.com/52176351/219473970-4335a832-8613-4d9c-b600-937aa2bab77b.png)

Seems like there is a Base gray that needs to be in "base" instead.

**Comment by GnatalieH** [comment]
@humancompanion-usds I think that color popped up because I copied the Text area component from the USWDS project file today. I'll see if it is a VA color or USWDS color (and clean up accordingly).

**Comment by GnatalieH** [comment]
Closing ticket because work has been completed.
