### ISSUE TITLE
Update example of "When to use something else" for Select Boxes

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#150]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Form Controls > Select Box

## What is the nature of this update?

- [ ] When to use
- [x] When to consider something else
- [ ] Code snippet
- [ ] Accessibility
- [ ] Research insight
- [ ] General documentation

## Additional Context

Currently, the last example under for the `Select Box` component reads:
"For site navigation (use the navigation components instead)."

As a new user to the site, when I initially read that, I thought, "Cool! There are navigation components?"  but then didn't see anything called `Navigation` in the menu... and wasn't sure if it was referring to the Side Nav component.

I _think_ the main point of the guidance is to discourage use of a select box as navigation.  To be more clear, I propose changing the language to:
"To navigate users to another page in the site, use a text link or the Sidenav component"

<img width="1116" alt="Screen Shot 2019-10-30 at 4 37 44 PM" src="https://user-images.githubusercontent.com/55992116/67896912-afa15300-fb33-11e9-8b11-7d48ec3917f4.png">

**Comment by KevinMHoffmanUSDS** [comment]
Thanks, @andaleliz! A slight modification to this has been pushed into production and should go live today. The final copy:

If you are intending to provide navigation. To help users navigate to a section on the same page or another page in the site, use a text link or the Sidenav component.
