### ISSUE TITLE
Conversion to USWDS v3 - Step indicator (Progress bar - segmented) - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1505]
## Description
Update documentation and guidance for the Progress bar - segmented component on design.va.gov based on guidance from USWDS v3.

## Details
[USWDS Step Indicator component](https://designsystem.digital.gov/components/step-indicator/)
[VA DS Progress bar - segmented component](https://design.va.gov/components/form/progress-bar-segmented)

## Tasks
- [ ] Update component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
We did this back in May 2024.
