### ISSUE TITLE
Maintenance Banner web component: development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#1508]
## Description
Build a web-component version of our [Maintenance Banner React component](https://design.va.gov/storybook/?path=/docs/components-banners-maintenancebanner--during-maintenance).

## Details
Styles: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-maintenance-banner.scss

Reference existing Maintenance banner: https://design.va.gov/components/banner/maintenance

Use the va-banner and va-promo-banner components as examples

## Acceptance Criteria
- [ ] `va-maintenance-banner` is written and added to Storybook
- [ ] E2E tests are written
- [ ] Add Chromatic link to department-of-veterans-affairs/vets-design-system-documentation#1511, assign ticket to Courtney, and move ticket to Current Sprint column
- [ ] Once accessibility review is complete, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

**Comment by babsdenney** [comment]
Here is the design for the Maintenance banner. 
[Sketch maintenance banner](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7/p/D413251A-9268-4E48-9E4C-8E8A3A6B31F9/canvas)

The color and styles are VA but the padding and spacing are using the USWDS alert. 
[USWDS Alert](https://designsystem.digital.gov/components/alert/)

**Comment by caw310** [comment]
Will carry over into the next sprint due to complexity.

**Comment by powellkerry** [comment]
Waiting for component library release to verify GA4 mappings

**Comment by caw310** [comment]
Staging review is scheduled for 6/27 so this will carry over into the next sprint.
