### ISSUE TITLE
USWDS v3 - Button component- Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1514]
## Description
We need to incorporate the designs for the USWDS Button component into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Button component](https://designsystem.digital.gov/components/button/)
[VA DS Button component](https://design.va.gov/components/button/)

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by humancompanion-usds** [comment]
@GnatalieH - Changes that are there look fine. 

* Do we want to include at least the additional Big Button style from USWDS? I could see that being useful.
* Do we want to include the other accent button styles? Not for the MVP but for the eventual final version that does seem like it might be good.
* Agree about keeping our primary and secondary.
* Let's keep button where it is in the hierarchy. It is used outside of forms (in Alerts and Modals most often, just to name a few).

Thanks!

**Comment by GnatalieH** [comment]
@humancompanion-usds here are my responses:

> * Do we want to include at least the additional Big Button style from USWDS? I could see that being useful.
Yes, I'll add these in.

> * Do we want to include the other accent button styles? Not for the MVP but for the eventual final version that does seem like it might be good.
When we talked about this previously we had decided to carry over the Primary and Outline variations only for the coded component. I'm not sure if it makes sense to have design assets in the library if we don't plan on offering the coded variations. We also should decide if Disabled states are getting carried over (or not). I'm happy to add these Button variations, but I think it would be confusing to include them in the library if they are not actually available. That's my $.02.

> * Let's keep button where it is in the hierarchy. It is used outside of forms (in Alerts and Modals most often, just to name a few).
Will do!

**Comment by humancompanion-usds** [comment]
> I'm not sure if it makes sense to have design assets in the library if we don't plan on offering the coded variations.

Of course not. What am I asking is: Do you think the additional button variations have utility? Would they be useful? To reiterate though, I'm not asking for those for this ticket. I was asking for the future.

**Comment by GnatalieH** [comment]
@humancompanion-usds OK gotcha. I have an MVP Sketch assets ticket in progress so I got confused about the MVP mention. But to answer, I believe the Accent Cool Color and Accent Warm Color could be useful down the line. Secondary Color (red) doesn't seem useful to me unless it's for a destructive action, and Base Color looks too much like a disabled button IMO. Thanks.

**Comment by GnatalieH** [comment]
@humancompanion-usds [here is an updated link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/P1Dzynv) to the artboard with the standard and big size buttons. I updated the link on the development ticket, too. I went ahead and created a Secondary big button because that's something we currently offer in the VA component.
