### ISSUE TITLE
Conversion to USWDS - Button component - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1516]
## Description
Update documentation and guidance for the Button component on design.va.gov based on guidance from USWDS v3.

## Details
[USWDS Button component](https://designsystem.digital.gov/components/button/)
[VA DS Button component](https://design.va.gov/components/button/)

## Tasks
- [ ] Update component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
This has been done.
