### ISSUE TITLE
Conversion to USWDS - Button pair - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1520]
## Description
Update documentation and guidance for the Button pair component on design.va.gov based on guidance from USWDS v3 Button Group.

## Details
[USWDS Button Group component](https://designsystem.digital.gov/components/button-group/)
[VA DS Button pair component](https://design.va.gov/components/button/button-pair)

## Tasks
- [ ] Update component documentation for design.va.gov
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
I merged this guidance back in August.
