### ISSUE TITLE
Epic - Forms Library - Replace React Components with Web Component versions

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1530]
## Description
Several Design System React components are still in use by the Forms Library, despite there being web component versions of these components available. This epic is to track the efforts required to replace the appropriate React components with their web component counterparts.

At this time, the focus will be on replacing the React components with their USWDS v1-compatible web component counterparts, not with any USWDS v3-compatible web components, even though they may be available. Switching from v1 to v3 web components 'variants' will be done at a later time.

Also, this epic is only considered with component upgrades needed in the Forms Library, and not the Forms System Core, a separate library.

## Source
The research compiled in this epic was carried out by Nick Gaydosh as part of [#1375](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1375).

## Details
The components identified as needing replacement are as follows (with number of files where that component was found in parentheses):

- Checkbox (2)
- LoadingIndicator (2)
- ProgressButton (3)
- Modal (3)
- AlertBox (1)
- Select (1)

Please see the individual component upgrade tickets for more details.

**Comment by annekerr49** [comment]
Is there any update on the progress of this effort
