### ISSUE TITLE
Forms Lib - Replace LoadingIndicator Component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1532]
## Description

As part of [this epic](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1530), we will replace all instances of the React LoadingIndicator component in the Forms Library with the Web Component version.

## Details

The LoadingIndicator component is currently being used in the following files:

- /vets-website/src/platform/forms/save-in-progress/ApplicationStatus.jsx
- /vets-website/src/platform/forms/save-in-progress/RoutedSavableApp.jsx

## Tasks

- [ ] Replace the React component with its Web Component component, updating any necessary props and/or logic related to the smooth operation of the component
- [ ] Ensure the web component works correctly - likely, by either finding an existing app that makes use of it or by creating a new, temporary form
- [ ] Update any accompanying tests
- [ ] Get design sign-off to ensure that the new Web Component looks and feels 'correct'

**Comment by caw310** [comment]
This work will carry over into the next sprint
