### ISSUE TITLE
Forms Lib - Replace TextInput Component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1543]
## Description

As part of [this epic](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1530), we will replace all instances of the React TextInput component in the Forms Library with the Web Component version.

## Details

The TextInput component is currently being used in the following file:

- /vets-website/src/platform/forms-system/components/FormSignature.jsx

## Tasks

- [ ] Replace the React component with its Web Component component, updating any necessary props and/or logic related to the smooth operation of the component
- [ ] Ensure the web component works correctly - likely, by either finding an existing app that makes use of it or by creating a new, temporary form
- [ ] Update any accompanying tests
- [ ] Get design sign-off to ensure that the new Web Component looks and feels 'correct'

**Comment by humancompanion-usds** [comment]
Would it be faster to create a va-form-signature component? Seems like FormSignature contains a number of React components that are to be deprecated. At the very least I'd like us to file an issue to create a signature component in future. Thanks.

**Comment by caw310** [comment]
Will carry over into the next sprint as work on this only started on the 2nd to last day of the sprint.

**Comment by caw310** [comment]
@jamigibbs I don't think we have a ticket for that yet.
