### ISSUE TITLE
<va-back-to-top /> visibility obstructed by <va-promo-banner />

### ISSUE THREAD

**Issue by oleksii-morgun** [department-of-veterans-affairs/vets-design-system-documentation#1546]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

`<va-back-to-top />` button `reveal` class is not popping the button up half way through page scroll, forcing users to scroll all the way down to the bottom to see "Back to Top" button.

## What I expected to happen

It is expected to have Back to Top button to appear on a continuous scroll (beyond specific height as I understand) before reaching the bottom of the page

## Reproducing
- Formation version: 
- Device: MacBook
- Browser: Chrome

Steps to reproduce:

1. Authenticate on va.gov
2. Navigate to `/education/about-gi-bill-benefits/` (although it was tested on `/my-health/secure-messages` as well)
3. Confirm <va-promo-baner> is fixed to the bottom of the page
4. Start scrolling until Back to Top button appears. It should appear about half way through scrolling, but appears when scrolling all the way to the bottom
5. Close promo banner and repeat the steps. Back to Top button will appear mid page scrolling as expected

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details
![image](https://user-images.githubusercontent.com/87077843/218149381-321aa3ed-ebd2-4a5f-8368-a0b90dd10a29.png)
![image](https://user-images.githubusercontent.com/87077843/218149406-2157054a-488a-4517-8dbe-fa0610264a1a.png)

**Comment by caw310** [comment]
@oleksii-morgun Is this still an issue?

**Comment by oleksii-morgun** [comment]
@caw310 I am not sure to be honest, it's been reported awhile ago

**Comment by caw310** [comment]
Closing as this is old and VA DS components have been updated. If this issue still persists, please open a new ticket.
