### ISSUE TITLE
[Modal] Improve modal example on Modal Component page

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#155]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Modal component

## What is the nature of this update?

- [ ] When to use
- [ ] When to use something else
- [ ] Code snippet
- [ ] Accessibility
- [ ] Research insight
- [x] General documentation

## Additional Context

The example shown when you click on `Open Modal` on https://design.va.gov/components/modal feels misaligned with the rest of the examples throughout the documentation.  It feels as though it may not be intentional to have the alert component inside the modal component w/ a content block underneath, and the language in the example could be improved.

Perhaps this is exactly as intended, but felt another set of eyes on to confirm would be worthwhile.

<img width="855" alt="is this correct?" src="https://user-images.githubusercontent.com/55992116/67963599-3fe3a480-fbd5-11e9-8591-b4769665ab8f.png">

**Comment by jaredcunha-usds** [comment]
The modal documentation came from the old Fractal site. This can definitely stand to be updated. Also note that the crisis line is out of sync with what is currently on VA.gov… but I remember much of the CSS for that not being in Formation but in `verts-website`, so I think those styles should placed into Formation as well.

**Comment by humancompanion-usds** [comment]
This has been updated and the example is now more appropriate.
