### ISSUE TITLE
Experimental Design - Button - Icon

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1559]
## What
I'd like to add a Button variant named Icon thus Button - Icon. It's a tertiary button style that is lightweight visually and can be used alongside Link variations.

## Purpose
Our Button - Primary and Secondary variations are visually dominant and large. When we have a number of secondary buttons clustered together we lose visual hierarchy and we hypothesize that users take longer to find the action they'd like to take. This Button style looks to repair those issues.

## Usage
* Button - Icon could be used inside of a Card, Modal, or other container where there may be multiple actions in close proximity. 
* Button - Icon could be used in Secure Messaging and other MHV applications were multiple actions of equal prominence are in close proximity and requite buttons.

## Behavior
These buttons start with an icon and then uppercase text. Upon hover state they have a background and the icon & text are a darker color.

## Examples
![New Button - Icon instances@2x](https://user-images.githubusercontent.com/52176351/219215531-c4a07163-6100-4b29-a806-62345f6ad121.png)

![Solution E 2 - Close is a Button - Icon@2x](https://user-images.githubusercontent.com/52176351/219215567-37e72025-47a0-4da1-8b95-285117b75488.png)

## Accessibility
These mocks were reviewed by Brian, Josh, and Martha. This gives teams flexibility when we want to have material honesty in using links and buttons correctly.

## Guidance
These Button - Icon will only be available initially to be used inside of a container. Today containers are Card, Modal, and application specific boxes with a darker background for grouping similar actions. They are not to be used in place of primary or secondary buttons outside of these containers. 

## Research (optional)
No research has been conducted as of yet. The notion is to make these available to teams who have been asking for solutions in this space.

## Next steps
Plan is to present this component on 2/17.

**Comment by Cieramaddox** [comment]
@humancompanion-usds Using what you've done here as a guide, we designed a tertiary button that used the same colors as the secondary button [here](https://www.figma.com/file/qm63ZVrjq6eohFpWnVqj7F/Add-Print-Button-to-Appt-List?type=design&node-id=1292%3A27387&t=Tazdz8ijHCSin8V0-1)

 <img width="136" alt="Screenshot 2023-06-05 at 3 36 17 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/92750161/0981b069-b3dc-4967-955f-8b539bcf97b4">

**Comment by humancompanion-usds** [comment]
1. @danbrady is adding this as part of the Card. 
2. Matt decided that we're going to add this but the guidance will be to use it only in Card or Modal for now (other instances, like in Check-in can be grandfathered in but we won't expand upon those use cases).
3. @humancompanion-usds to define what "destructive" really means.
4. Upgrade storybook, add mobile's destructive button, then add this button style with new guidance, then add the Close button.
5. @rsmithadhoc to weigh in on whether we really need text next to the close button or not.

**Comment by rsmithadhoc** [comment]
> 5. @rsmithadhoc to weigh in on whether we really need text next to the close button or not.

I think it is okay to not have text on the icon button for close. That is assuming the icon is enough to convey meaning (an X for close is fine), the button is appropriately sized for touch, and it is given an accessible name (typically through `aria-label`).

Generally speaking, having text on an icon button is going to be better for accessibility, but not required. It makes the functionality clear and it's easier to interact with the button. If the text is omitted, the icon should convey the right meaning. Standard operations such as close and print are generally safe with just an icon and accessible label, but anything atypical should have button text to avoid confusion.

**Comment by caw310** [comment]
Here is the ticket for Button - icon guidance. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2745
