### ISSUE TITLE
Content explaining Bitter font is copied from google.com/fonts and doesn't credit author (written in first person)

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#156]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On the typography page, the content for the font Bitter, appears to have been copy-pasted directly from Google and doesn't credit the author (it's written in first person)

## What I expected to happen

The copy would speak to why Bitter was chosen for the VA design system and/or credit the original designer who wrote the text in first person.

## Reproducing
- Formation version: current
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1. Visit https://design.va.gov/design/typography
2. Read copy about Bitter

**Comment by KevinMHoffmanUSDS** [comment]
@andaleliz @peggygannon Credited the author by name, as well as the studio. Cheers!

**Comment by andaleliz** [comment]
@KevinMHoffmanUSDS Thanks for the quick response to this!
