### ISSUE TITLE
Experimental Design [Multiple Responses - Multi-page] - Updates

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/vets-design-system-documentation#1565]
[Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/xxxPoJ/a/DP7pRp2)

## What
This is requesting an update to the existing pattern for [multiple responses](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page) for multi-page page responses. It utilizes the one-thing-per-page methodology and moving away from the wizard pattern while also introducing changes to the item cards, edit and remove buttons and confirmation modals when making changes or removing items from the list. 

## Purpose
> What problem does this component or pattern solve for the user?

This will make it easier to review and edit when a question has multiple responses with each response having it's own set of complex questions and answers in a multi-page flow. 

## Usage
> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.

On the 10-10EZ, the scenario where this component will be used involves reporting dependents and adding their information. 

## Behavior
> Describe the key interactions for this component, calling out any specific considerations for mobile.

- Confirmation modals when a user wants to cancel out of an adding flow, remove from list, or cancel edits being made.
- The flow introduces a page displaying all items entered into the multiple responses answer so far with an edit link and delete button where the edit link takes the user back to the first page of that dependent flow and the delete button presents the confirmation modal before removing the item from the list. 

## Examples
> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.

- [Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/xxxPoJ/a/DP7pRp2)

## Accessibility
> Include any accessibility considerations.

- Plan to test more in staging on future study
- The first iteration of this was tested via prototype as part of current Collaboration Cycle for [10-10 Health Apps, 10-10EZ, Household Information Optimization] #47766

## Guidance
> What would you want to tell other teams about this component or pattern?

- To use when there is a complex multiple response question where each item has it's own set of multi-page responses and editing at that point in the form flow makes senses instead of waiting for the final review page. 

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.

- [2022-12 Health care application (10-10EZ) household information section research](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/192)

## Code (optional)
> Include any existing code.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
@jessicastump , this will be discussed at the DSC meeting on 3/24/23. I'll add you to the meeting invite.

**Comment by jessicastump** [comment]
@allison0034 Here is the link to the [Sketch artboard](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/DP7pRp2) that was shared during the meeting. 

Working on a couple of minor changes based on feedback received during that meeting: calling out the new button and card components used as well as adjusting the action buttons to be on the bottom of the card and not the far right.

**Comment by humancompanion-usds** [comment]
@jessicastump - Can we get an update on this work? Were you able to conduct the research?

**Comment by longmd** [comment]
@sterkenburgsara , per our discussion around the multi-page list/loop implementation, here are some of the rationale pieces behind where things stand at the moment: 
- This single page per question pattern was explored as an alternative to the limited functionality that currently is provided by the Forms Library. At the moment, we only have the options to either show the Dependent form as a dropdown/wizard conditional of the "Do you want to add..." question (which creates known and understood accessibility issues) or move the entire form to a second page and have one page per item in the list. Option B is better than Option A, but is still overwhelming, as we have approx. 15 total responses to potentially gather, so all 15 would be on a single page. 
- With the single question per page, we can actually reduce the number of potential responses we have to gather based on the responses to previous questions, however, because we are inside of the loop at that point, we needed a single react component to manage the form data and the ability to show/hide those questions and subsequent views all together. We also need to be able to control where the user goes when clicking next and previous based on the responses they have provided.

**Comment by sterkenburgsara** [comment]
@longmd thanks for writing this up!

**Comment by humancompanion-usds** [comment]
@longmd and @jessicastump - We've released a new codified List and loop and [updated the multiple responses pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page). If you could take a look at the updates and then either close this issue out if what we added meets your needs or update this issue to identify what additional functionality you would need out of a multi-page multiple response pattern that would be greatly appreciated!

**Comment by longmd** [comment]
Thanks @humancompanion-usds , we have an initiative in our next sprint where we will try out the newly-created pattern. We will provide any feedback at that time regarding any additional functionality. 🙃

**Comment by caw310** [comment]
@longmd is there any update on this? Can we close this issue ?

**Comment by longmd** [comment]
@caw310 , I think we can close this. We have tested out the pattern and reported some feedback to @rhasselle-oddball and @jeana-adhoc . There are some additional tickets that have created to address that feedback.
