### ISSUE TITLE
Experimental Design [Message Folder - Card Variation - Secure Messaging | MHV to VA.gov]

### ISSUE THREAD

**Issue by underpaid1ntern** [department-of-veterans-affairs/vets-design-system-documentation#1577]
## What
**For use in MHV to VA secure messaging**: The proposed component is a card variation that houses the functionality traditionally associated with folders in an email program - a labeled, partitioned space that can hold messages a user moves into it. Most likely, the user will choose to do this because they see these messages as having a common theme/thread/association and organizing them into a folder would make them easier to find.
![image](https://user-images.githubusercontent.com/126206606/221584957-98e388d7-c621-4511-8e5e-b355f57fda01.png)

The proposed component is based off [recommendations](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347) the team received from Matt Dingee from the midpoint review.
## Purpose
The card component gives the user an actionable encapsulation of a custom folder and its accompanying "self-actions" -which means the "Edit folder name" and "Delete" actions on a card/folder will directly and only affect the card/folder they're "on" / "nested in".

Previously, folders were represented by links and in order to rename or delete a folder, a user would have to navigate into that folder.
![image](https://user-images.githubusercontent.com/126206606/221464507-0972c756-4b70-45f6-95ba-d829586da833.png)

Using cards allows folder-level functions to exists on the "My folders" level instead of at the message-list-view level. This can help the user assess how their custom folders relate to each other since they're all visible and actionable at the same level.
![image](https://user-images.githubusercontent.com/126206606/221464601-97b860dc-083e-4819-8a7e-b445aa79f235.png)

## Usage
This component is used whenever a user creates a custom folder. The custom folder is represented on the UI layer as a card which helps convey it as a "unit" with its own self actions like "Edit folder name" and "Delete."
## Behavior
- **Auto alphabetical order** - Behavior: Folders/cards will appear from A to Z, top to bottom automatically. Users can't designate an order of the folders/cards.
- **Enter folder** - Link: by clicking on the folder's name which appears as the largest text with underlined link styling, a user can enter the folder and see what messages they've moved inside it.
- **Edit folder name** - Button: brings up a modal that allows a user to enter in text that will become the folder's new name.
- **Delete folder** - Button: brings up a modal that confirms if the user wants to delete the folder which will release the messages back to the inbox system folder.
- No differences in behavior between the desktop and mobile experiences.

## Examples
Sketch mock of "My folders" showing folders cards: [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/358EC320-67D7-4EFC-BBF3-3D037F2D605E) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/F30C671B-45D3-4AE0-B84F-4F53E9B92393)
Sketch mock showing "Cardiologist" folder after clicking into it: [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/2F5D83E3-5A04-4527-BA2B-CEDDDEB06F0E) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/B629CF74-759C-42C8-960D-BAF83DBBCACD)
## Accessibility
On a screenreader: the rename and delete buttons will readout the folder name as well.

- "Rename 'cardiologist' folder"
- "Delete 'cardiologist' folder"

## Guidance
This component should be used whenever a "traditional" folder structure is desirable or in other cases where a series of "containers" with self-contained functionality is needed.
## Research (optional)
In R2 usability testing, users said they wanted folder functionality. We plan to validate the implementation of them in phase 0 testing.
## Code (optional)
N/A
## Next steps
Asynchronous review requested.

**Comment by caw310** [comment]
This is on the agenda for the 03.03.23 DSC meeting.

**Comment by rtwell** [comment]
@underpaid1ntern 
The headers in the cards should be at a _maximum_ an H2. Please ensure they follow mobile/desktop size variants.

**Comment by laurwill** [comment]
Hi! Thanks for the tag — I don't think this has been resolved, so I'll just share 2 reasons we avoid all caps in our Veteran-facing content:
- It's harder to read
- It can sound like we're yelling at the Veteran

But I'm not familiar with the design decisions that went into this all caps styling, so happy to chat more about this if that would be helpful! 

cc @DanielleThierryUSDSVA for awareness

**Comment by rtwell** [comment]
my preference is 2-fold:
1. we simplify the number of actions per-card. right now there are technically 3, but i would love to get it to 2. perhaps Delete could live in the folder page (maybe folks need to see what is in each folder before deleting?). fwiw the screen grab you included of the old layout isn't too terrible imo--its super straightforward and lets the actions live inside the folder pages (do we know if that is a problem?.  I think @humancompanion-usds is in the process of updating our card documentation. 
2. the H2 comment is referring to the screen grab at the top of the ticket--it looks like the h1 and headers in the cards are the same type size. personally i think the H2s look too large, but meh it's clear at least. make sure youre using our mobile styles for the mobile comps--our h1s and h2s scale down a bit for smaller screens.

**Comment by underpaid1ntern** [comment]
Hi @humancompanion-usds , we haven't progressed on this further and are going to drop this submission for now.

Why:
Given the priorities to get secure messaging into phase 0, I got agreement from the product owner and Coulton to keep what we currently have built since it tested well in R2 usability testing. We will revisit this later, but it's not currently planned when. When it's revisited and if we do a card style, we'll see see if we can start by using one of the card styles already in the system.

Follow-up question:
Should I close this ticket out?
