### ISSUE TITLE
Experimental Design [Message Attachment - Card Variation - Secure Messaging | MHV to VA.gov]

### ISSUE THREAD

**Issue by underpaid1ntern** [department-of-veterans-affairs/vets-design-system-documentation#1578]
## What
**For use in MHV to VA secure messaging**: proposed card component variation for attachments to secure message in-progress messages.
_Current_ execution of attachments to in-progress messages:
![image](https://user-images.githubusercontent.com/126206606/221588698-2d667703-b4bf-4405-bf0e-9ca329406274.png)
_Proposed_ component of attachments as cards to in-progress messages:
![image](https://user-images.githubusercontent.com/126206606/221589335-b71ec301-647e-416e-b2e5-006cd6635277.png)

The proposed component is based off [recommendations](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347) the team received from Matt Dingee from the midpoint review.
## Purpose
This component will help reduce "button-clutter" in the UI that increases as users add attachments. In the current design, the "Attach" and "Remove" buttons look very similar. Changing the attachment to a card also helps communicate the "presence" of an attachment to the message (since it more closely resembles an added object). Using a card also allows the experimental buttons-on-card styling which will differentiate it from the existing primary, secondary, and tertiary buttons already on the page.
![image](https://user-images.githubusercontent.com/126206606/221596140-d3cfb34b-4aeb-4076-8b44-1baa78aa70d8.png)
## Usage
This component is used when a user is in-progress of writing a new message or reply to a message -and that user attaches a file to the message. This could be used in other contexts/potential VA tools where a user is adding a file attachment to something that has to be submitted, sent, or uploaded.
## Behavior
- **Remove attachment** - Button: brings up a modal to confirm if the user wants to remove the attachment and that if they change their mind, they'll have to reattach it.
- No differences in behavior between the desktop and mobile experiences.
- Please note tech limitations to attaching files. These should not affect the component - only how many of them would appear on the screen.
![image](https://user-images.githubusercontent.com/126206606/221606605-3545b35a-df8b-4d7e-b451-05d2e0a2087a.png)

## Examples
[Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D5242E4C-4D8F-47F0-8726-D4AD997E0C13) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/09CCB3DD-379D-463F-ACD6-D7364007053F)

## Accessibility
On a screenreader: the remove button will readout the file name as well.
"Remove 'xray-results.jpg' attachment"

## Guidance
This component can be used whenever a user can "attach" a file to something that will be submitted such as a message or an upload - representing an attachment as a card on the UI layer can help a user understand that they've successfully "added" a file to a form or whatever is being submitted.

Using a card also helps connect any functionality on a card, to the card that it's found on -meaning: a remove button on a card most likely removes that card versus affecting something else.
## Research (optional)
We plan to validate the implementation of them in phase 0 testing.
## Code (optional)
N/A
## Next steps
Asynchronous review requested.

**Comment by caw310** [comment]
This is on the agenda for the 03.03.23 DSC meeting.

**Comment by rtwell** [comment]
@underpaid1ntern 
I would limit the width of these entries—I know we're allowing for lengthy file names, but the further away the Remove button is, the harder it is to track which button belongs to which file. Secondly, what does this look like on mobile?

**Comment by caw310** [comment]
@underpaid1ntern @rtwell , is there an update on this?

**Comment by rtwell** [comment]
@underpaid1ntern are we stuck with the narrow column the file name is jammed into?

**Comment by underpaid1ntern** [comment]
Hi @rtwell , this is what the focus boxes look like for that -showing the cards containers. This is at 320px wide mobile view.

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/126206606/c403a0a2-f7eb-43ac-beae-74e616197c5b)

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/126206606/a555efca-0dd4-4f56-a7a2-c2d18ebbdc8c)

I reached out to development and we could possibly do something like this which may also be better for users using 300-400% zoom. It should still meet Accessibility expectations regarding tabbing order.
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/126206606/fc2deadf-653b-4e56-8ec6-a8f18e407f49)

**Comment by humancompanion-usds** [comment]
@rtwell - Is there someone who can bring the current state of these Cards to Design System Council?

**Comment by danbrady** [comment]
Attaching screenshot of an example from the forthcoming File Input for reference:

**Initial State:**
<img alt="" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/c5ba56e9-becc-453e-a124-6e3af6fd695f" width=320 />

**Attached State:**
<img alt="" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/a5d9f399-0315-4683-a446-8ccf0db30477" width=320 />

**Comment by pmclaren19** [comment]
Hey you tested this with .jpg at all or .txt? When we try to upload a file like this using the va-file-input v3 component we get the error `'This is not a valid file type.'` 
![Screenshot 2024-03-25 at 11 34 47 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/141954992/ec0229cd-3bf4-4eb3-aa24-97ff77df84bf)
 Wondering if you guys also get this and this is a bug or if we have this implemented incorrectly now that we are using the v3 version.

**Comment by humancompanion-usds** [comment]
@pmclaren19 - We have variations of va-file-input that appear to work correctly in Storybook. There is a [variation that limits the file types accepted](https://design.va.gov/storybook/?path=/docs/uswds-va-file-input--accepts-only-specific-file-types). If you think that va-file-input is not behaving correctly you should file a new issue. This issue is about bringing in the experimental design of attaching files from MyHealtheVet.

**Comment by pmclaren19** [comment]
Okay thanks @humancompanion-usds will do! After further investigation looks like the v1 component accepted spaces between file types for the accept prop while the v3 version does not. I'll let the platform team know in slack!

**Comment by humancompanion-usds** [comment]
This is superceded by the new file-input. Here is the Staging review ticket to follow along with: https://github.com/department-of-veterans-affairs/va.gov-team/issues/77552
