### ISSUE TITLE
Add a single-column page template to the design system

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/vets-design-system-documentation#158]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/2691 I have designed an updated template for downloading VA forms. That template is comprised of a single wide column. 

@jaredcunha-usds suggested that we should add this as a standard template here: https://design.va.gov/layout/page-templates

Being new to the design system, I'm not sure how this should be specified programatically. I did see the 732 pixel wide standard in the Sketch file but I'm not sure this correlates to anything in actual code or column widths.

- Component/utility name:

## Do you have a suggestion for a new component or utility?

Yes this should be a responsive layout.

**Comment by caw310** [comment]
@artsymartha68 , is this still a valid request?

**Comment by humancompanion-usds** [comment]
@GnatalieH - Can you look in the CMS and see if there is a template for this or a single-col template? I suspect it doesn't make sense for us to document templates that are in the CMS (unless sitewide designers want Sketch assets for this).

**Comment by GnatalieH** [comment]
@humancompanion-usds I'm on it. I don't have access to the CMS, but I've recruited Randi to help out. I'll update this comment with the answer.

**Comment by GnatalieH** [comment]
@humancompanion-usds I noticed the sidenav. However, this was a question Randi had asked me, so I wanted to confirm. I'll share the template Martha added in the Site-wide Content team's Slack channel, but so far no one I've talked to has seen a single column template in Drupal.

**Comment by humancompanion-usds** [comment]
Sorry, yes, I wanted us to check to see if it was a CMS template or not. If it is not, please create it as a template in our Sketch library and then we'll document it in our Templates section on design.va.gov.

**Comment by GnatalieH** [comment]
Thanks @humancompanion-usds. I did some digging. Martha's examples are for form pages, which are not built in Drupal. We do, however, use a single-page template for [R&S pages](https://www.va.gov/resources/choosing-a-decision-review-option/) that are built in Drupal. Shall I go ahead and create a template in Sketch for a page like the one I linked to?

**Comment by artsymartha68** [comment]
This is a very old request, closing it out since we've gone 5 years without it.
