### ISSUE TITLE
Add "download" icon as a standard to the design system, update icon page

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/vets-design-system-documentation#159]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

1. This request comes out of the work in #152 

Let's add the download icon to the official VA design system list of icons:
https://design.va.gov/design/icons

2. Does it also have to get added to the Sketch file...? If I need to open a separate issue for that work, let me know. 

3. @jaredcunha-usds also requested the following. I'm happy to help but not sure what it entails:

> I'd love for someone to take a look at that icon page at some point. That was brought over from the old Fractal site (which no longer exists). The icons page is a limited set, but technically, the entirety of the Font Awesome free solid set is available. Same with brands.

**Comment by andaleliz** [comment]
@artsymartha68  FYI: I've been working w/ Emily Waggoner + a couple of others on an initiative to create better alignment w/ the design system documentation + the Sketch file; one action item I picked up was to add a download icon to the Sketch file. It's completed locally and was waiting to review w/ that small team before committing it back to the repo.

**Comment by andaleliz** [comment]
I have also noticed a disconnect between the icons on the documentation site and the sketch library (e.g. one has `fa-calendar` and the other has `fa-calendar-o` and have captured this on our list of items to investigate

**Comment by artsymartha68** [comment]
@andaleliz YOU ROCK and THANK YOU!!!!!

**Comment by andaleliz** [comment]
@artsymartha68 I added the icon to the sketch library file here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/downloads/

**Comment by artsymartha68** [comment]
So great - thanks @andaleliz !!!

**Comment by jenstrickland** [comment]
When this is added to the design system documentation, would it be possible to update the underlying HTML structure from #152 ? This  addresses accessibility issues with the way the icons are currently presented throughout VA.gov and the design system.

**Comment by KevinMHoffmanUSDS** [comment]
This has been absorbed by https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/281
