### ISSUE TITLE
Go back to VA.gov should be an action link

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#1591]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

![image](https://user-images.githubusercontent.com/14154792/222572217-64e6e830-a2fb-4ef5-a827-0f12afba1b87.png)

If a user is unable to submit a form, they're prompted to return to the VA.gov homepage. Two issues exist:
- This seems to be a link, but is styled as a button
- If it is a button, it's unnecessarily taking up two lines when it can simply extend to the full width

## Reproducing
- Formation version:
- Device: iPhone 12
- Browser: Safari

Steps to reproduce:
Uncertain, but it should appear upon form submission failure on staging.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details
This is a relatively minor bug, flagging just so it doesn't get lost

**Comment by caw310** [comment]
@joshkimux , This isn't a DS bug. Implementation of button or action link would be the decision of the VFS team.

**Comment by Mottie** [comment]
@caw310 The code is in the [form system generic error message](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/review/submit-states/GenericError.jsx#L52) code.

**Comment by caw310** [comment]
@Mottie Okay, we will look into this. We all thought otherwise. Thanks for the clarification.

**Comment by humancompanion-usds** [comment]
@ndsprinkle - This looks to be just a className change. Can we pick this change up?

**Comment by caw310** [comment]
@ndsprinkle Did this work get done?

**Comment by humancompanion-usds** [comment]
@jeana-adhoc fixed it!!! https://github.com/department-of-veterans-affairs/vets-website/pull/27431
