### ISSUE TITLE
Memorable date, old date bug, NVDA bug, and validation bug

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#1593]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Bug with older dates

1. Enter a date with the year 1990 in the field
2. Tab out of the field
3. Shift tab back into the field and change it to 1900
4. Tab out of the field and confirm an error emerges
5. Shift tab back into the field and change it back to 1990, then delete the 90 and replace with 00
6. Tab out and confirm no error is drawn
7. Tab to continue and confirm you are unable to continue

https://user-images.githubusercontent.com/14154792/223220573-0c67ca38-0f73-417c-b528-fc20db914ce4.mov

### Acceptance criteria
- [ ] I expect an error to be provided when a date is too old to be accepted

## NVDA bug

1) Open up NVDA
2) Tab to the month field
3) Type in "January"
4) Confirm the screen reader announces as though it is being accepted, but it is not being written into the textbox
5) Tab and confirm an error message is provided "You must enter a decision date" which is unspecific to the error that just occurred (the user attempted to enter a character date, not a numerical one)
6) Tab to "Add issue" and use "space"
7) Confirm focus isn't sent to the input with the issue (empty month)

### Acceptance criteria
- [ ] I expect the month field to accept character inputs so that a descriptive error message can be provided OR
- [ ] I expect the month field to simply accept "Jan, JAN, January" and any other possible formats
- [ ] I expect error messaging to be unique to each empty field. For example, if only month is missing, the error should read, "You must enter a month for the decision date."

## Error onblur between fields for iOS users

iOS users will trigger an error after inputting information field by field. This is unlike the desktop/keyboard experience where using tab does not trigger the error.

For VoiceOver users, this is particularly challenging, as they'll hear the error announce despite submitting correct information each time.

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/14154792/ec0ca763-af46-40e7-8548-42df542b5650

### Acceptance criteria
- [ ] Error messaging should not trigger if the user inputs correct information

### Recommendations
This is tricky. I'm uncertain what the best method of fixing this will be. I think this reminds me of previous conversations on fully switching to validation on submit, instead of live validation-- particularly with our recent shift to embracing one thing per page as a principle.

## Error messaging does not address February 
February can have years without the 29th, which should be accounted for in our error messaging

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/14154792/2946c71b-8591-4a72-a501-ef5c76545a16

## Reproducing
- Device: NVDA
- Browser: Chrome

1. [Open the supplemental claims flow
](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/add-issue?index=1)
2. Log in as Cara, User 223, [vetsgov+test233@id.me](mailto:vetsgov+test233@id.me)
3. Add a new issue (memorable date field will be here)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

[This is blocking the upcoming staging review (not yet scheduled) for Supplemental Claims](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52046)

**Comment by jamigibbs** [comment]
Hi @joshkimux I'll take a look at this as soon as I can but can you clarify what work this issue is blocking?

**Comment by Mottie** [comment]
Related to this is the old date error message... when we add a custom error message, it changes to the default "Please enter a year between 1900 and 2123" on blur - [here's a demo of the problem](https://codesandbox.io/s/icy-water-vnrvys?file=/src/App.js)

![memorable-date inputs showing June 6, 1800 with an error of "Enter a more current year". When the year input is focus, then blurred, the error changes to "Please enter a year between 1900 and 2123"](https://user-images.githubusercontent.com/136959/225686507-db878ae9-0448-498e-b657-3c1348939bb0.gif)

**Comment by joshkimux** [comment]
I've added a validation bug for iOS, which is a major accessibility issue

**Comment by Mottie** [comment]
Fixes submitted for:
- [Bug with older dates](https://github.com/department-of-veterans-affairs/component-library/pull/749)
- [Error messaging does not address February](https://github.com/department-of-veterans-affairs/component-library/pull/750)

Bugs not yet fixed (I probably won't tackle these):
- NVDA bug (Entering Jan, JAN or January) - enhancement is out of scope of the work I'm doing
- Error onblur between fields - the web component loses focus completely when "done" is used. Not sure how to fix this.

**Comment by joshkimux** [comment]
@Mottie [it looks like efforts are starting to address the error onblur between fields!](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1130)

**Comment by powellkerry** [comment]
@joshkimux @Mottie Im trying to get caught up on this issue. When I go to the form (20-0995) I cannot replicate the original issue. Is there still an issue around validation not showing when it should? Are there other issues that need to be addressed?

**Comment by Mottie** [comment]
The error message not clearing on blur has been fixed, but there are still 2 issues that need to be addressed:

> - [ ] NVDA bug (Entering Jan, JAN or January) - enhancement is out of scope of the work I'm doing
> - [ ] Error onblur between fields - the web component loses focus completely when "done" is used. Not sure how to fix this.

It might be better to split them out into separate tickets and close this ticket to make tracking easier

**Comment by caw310** [comment]
DST met with the VFFT to discuss this issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1130

We are pausing on this for now so for this ticket, DST will focus on NVDA bug.
