### ISSUE TITLE
Reverse phone icon 

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/vets-design-system-documentation#1595]
## What
Requesting an asynchronous review for a minor change to an existing pattern. The request is to flip the current font awesome phone icon to the right, facing corresponding text. It currently faces left and away from corresponding text. There have been conversations surrounding this change [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1493#issuecomment-1421052617)

Current Icon:
<img width="150" alt="Screenshot 2023-03-07 at 11 42 05 AM" src="https://user-images.githubusercontent.com/92750161/223534883-001efefc-a163-4fd0-981c-88e777b03756.png">

Proposed icon:
<img width="150" alt="Screenshot 2023-03-07 at 11 41 57 AM" src="https://user-images.githubusercontent.com/92750161/223534994-88bead2d-10b4-4ea1-b973-81fd22ab68e1.png">

## Purpose
The current icon does not appear to correspond with the information it is referencing and pulls the users eye away from the text. The updated version points directly to the text, therefore making it easier to identify and select. 

## Usage
In VAOS the phone icon is used in a few different scenarios.

It is used to indicate that an appointment will be conducted by phone. 

<img width="300" alt="Screenshot 2023-03-07 at 12 03 26 PM" src="https://user-images.githubusercontent.com/92750161/223539559-4b809b7e-a931-408c-baf2-549cdcd704ff.png">

It is also used in the appointment details pages to provide a facility or clinic's phone number.

<img width="291" alt="Screenshot 2023-03-07 at 12 10 04 PM" src="https://user-images.githubusercontent.com/92750161/223540932-27111763-5435-4075-96c7-7587a4de257d.png">

## Behavior
There are no special behaviors to consider for this icon. It will continue to behave the way it currently does. 

## Accessibility
There are no changes to accessibility considerations for this icon. 

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
Closing as ticket 1800 encompassed work in this issue. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1800
