### ISSUE TITLE
Experimental Design Search Filters

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/vets-design-system-documentation#1607]
## What
> Give a brief description of the component or pattern you want to propose.

Expand search filter capabilities by introducing filter buttons, dropdowns, and other ways to filter search results. 

## Purpose
> What problem does this component or pattern solve for the user?

This would allow users to easily search and find accurate information.

## Usage
> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.

Work is starting on [the facility locator](https://www.va.gov/find-locations/) to include filters that would allow users to filter by distance, type of care, and different VA health service types. This filter pattern could be used on other searches across the site, such as Find a VA Form, Outreach Events, Resources and Support, Outreach Materials, and Find a Yellow Ribbon School.

## Behavior
> Describe the key interactions for this component, calling out any specific considerations for mobile.

Users will be able to interact with filter buttons in different ways depending on what the filter is for. Some filters will include radio buttons, check boxes, or limited search capabilities. The mobile version of this would need to have the capability to toggle between showing a limited view of the filters and showing all filters. 

## Examples
> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.

Here is a low-fi wireframe that better shows the filtering capabilities that could be implemented to the Facility Locator. Note: This project is still in the early stages and is subject to change. 

![Facility Locator](https://user-images.githubusercontent.com/104526584/225070733-e988f87c-5463-4604-b693-39a22d7caf16.jpg)

## Accessibility
> Include any accessibility considerations.

The solution will need to be reviewed thoroughly with accessibility to ensure users can use the search filters. 

## Guidance
> What would you want to tell other teams about this component or pattern?

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.

## Code (optional)
> Include any existing code.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by thejordanwood** [comment]
I'm unsure if I'm too early in the process to present at a Design System Council meeting. Should I wait until I have high fidelity mockups to share?

**Comment by caw310** [comment]
@thejordanwood , it does seem early to present at DSC. Have you gone through design intent? IF not then, you should get feedback during the collab cycle. Thanks.

**Comment by thejordanwood** [comment]
Thanks for confirming @caw310! I'm fairly new to the ecosystem and am still trying to figure out the timing for all of the processes. I haven't went through design intent yet, but will get that set up. 

Feel free to close this ticket if needed! I can create a new one when I have high fidelity mockups to share.

**Comment by caw310** [comment]
Closing this ticket. @thejordanwood will create a new experimental design request if needed after going through collaboration cycle.
