### ISSUE TITLE
Make sure all web components that should have Google Analytics have been updated

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1612]
## Description
We need to do an audit of the following components from Michelle's [analytics tracking spreadsheet](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=2089299676) which she identified as not having `action` or `event` values for yet in order for her to connect GA:

- [x] va-back-to-top
- [x] va-official-gov-banner
- [x] va-featured-content
- [x] va-file-input
- [x] va-omb-info
- [x] va-privacy-agreement
- [x] va-process-list
- [x] va-search-input
- [x] va-table
- [x] va-telephone
- [x] va-textarea

## Details

Workflow for each component:

- [ ] If the component needs an analytics event
     - [ ] Add the event to the web component
     - [ ] Update the [vets-website analytics setup](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/component-library-analytics-setup.js) script to include it
     - [ ] Let Michelle know what the `action` and `event` value is for the component
- [ ] If the component does not need an analytics event (ie. there are no events in the component)
     - [ ] Let Michelle know that the component can be removed from her spreadsheet
     
## Acceptance Criteria
- [ ] All of the web components have been audited and updated as necessary (as well as the vets-website script).

**Comment by michelle-dooley** [comment]
@jamigibbs - great, thank you for the update!!  I updated the [tracking sheet](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=2089299676) accordingly.  I will get those configured for GA4 data layer code.
