### ISSUE TITLE
[Typography] - Add Mobile H1 and H2 styles to documentation

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1619]
## Description
In the desktop viewport, the H1 and H2 are sizes 64px and 48px, respectively. In viewports 481px and under, the H1 and H2 sizes become responsive and render as 30px and 24px, respectively. The Sketch library contains the mobile H1 and H2 text styles (as well as the desktop styles), but there is no mention of the mobile header sizes on our [Typography page](https://design.va.gov/foundation/typography). We should update the Typography page to mention the mobile H1 and H2 sizes and provide guidance on when to use them.

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by caw310** [comment]
closing as this is an old ticket and it looks like has been addressed,
