### ISSUE TITLE
Add right-caret animated component to the Sketch file, include rules about usage

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/vets-design-system-documentation#162]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: I am not sure of its official name but it's the animated right-caret links (Eligibility, How to file a claim, etc.) that appear on this page: https://www.va.gov/disability/ 

<img width="692" alt="Screen Shot 2019-12-06 at 2 09 48 PM" src="https://user-images.githubusercontent.com/47792423/70349102-1819d900-1832-11ea-9160-5d045d998ee9.png">

## Do you have a suggestion for a new component or utility?

The component is fine but it's not in the Sketch file for me to use in mockups. 

Are there rules around its usage? It seems no one can be sure. I propose that we reserve this component as "tool launcher" links. Also it seems that these links will appear in the main navigation on the next page. Perhaps that could be another rule around usage? I don't think we want this used on regular content navigation links. 

<img width="271" alt="Screen Shot 2019-12-06 at 2 10 45 PM" src="https://user-images.githubusercontent.com/47792423/70349191-41d30000-1832-11ea-9360-8cadb8ed3407.png">

I will take ownership of updating the Sketch file.

**Comment by KevinMHoffmanUSDS** [comment]
@artsymartha68 Thanks! Is this only an issue on hub landing pages, e.g.https://design.va.gov/patterns/pages#hub-pages
including https://www.va.gov/health-care/ https://www.va.gov/education/ etc.

My sense is that we've made this call. 

If it's in the "Link and teaser" sections of the page, we add a caret. If it's not, we don't.

@andrewlewandowski or @lalexanderson-dsva or @JeffBarnesUSDS - any insight or memory on that one?

**Comment by andrewlewandowski** [comment]
The link+teaser design is one component. It should be added to our design system. In 2018, the angle-right icon was added as an affordance to indicate that users will be taken out of/away from the hub page; and the angle-right icon animation and underline on hover was added to indicate interactivity for 508/accessibility.

I believe @rtwell 's general rule for this component, and buttons and links (see "Manage your health online" links on this page: https://www.va.gov/pittsburgh-health-care/), is: they get an angle-right icon if the user is being taken away from the product, and going to a different product.

**Comment by andrewlewandowski** [comment]
This is Formation's original link+teaser text component (I believe the devs recycled the code). It is inside an actual component in our design system--the Related Info box. These links are styles differently -- Bitter and no underline or angle-right icon. We should either update it to make the link underlined always, or change the link to Source Sans and use the same affordances and interactions as we do on the hub pages.
<img width="720" alt="Screen Shot 2019-12-06 at 3 08 14 PM" src="https://user-images.githubusercontent.com/36239278/70352961-50251a00-183a-11ea-9f02-32b0c429b1e4.png">

**Comment by KevinMHoffmanUSDS** [comment]
Thanks, @andrewlewandowski!

**Comment by GnatalieH** [comment]
@humancompanion-usds I created [this PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1420) where I added documentation about the Active link animation behavior.
