### ISSUE TITLE
Discovery: Translation support for web components outside of vets-website

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1620]
# Bug Report

Web components that have text loaded from i18next does not seem to work outside of vets-website.

## What happened

When I tried to replace the design.va.gov government banner with the `va-official-gov-banner` web component, I received an error because the translations values were not being provided to the component from i18next.

**Example of HTML to replace in design.va.gov**
<img width="649" alt="Screenshot 2023-03-21 at 5 27 52 PM" src="https://user-images.githubusercontent.com/872479/226756100-78e90e0f-6ec1-4970-a208-68bc417147bc.png">

**Error received when trying to use va-official-gov-banner (where translation text is trying to load)**
<img width="893" alt="Screenshot 2023-03-21 at 5 28 09 PM" src="https://user-images.githubusercontent.com/872479/226756097-a0f0e769-051f-4b56-8cba-4c9659a80e31.png">

I believe this is similar to the [issue reported in this Slack convo](https://dsva.slack.com/archives/C01DBGX4P45/p1678970588740699) where developers were trying to use the component library in [codepen](https://codepen.io/wullaski/pen/eYLMXLJ). The `va-memorable-date` component's translated text does not display:

<img width="906" alt="Screenshot 2023-03-21 at 5 30 28 PM" src="https://user-images.githubusercontent.com/872479/226756490-afe376cc-f0c3-40af-a978-993f4a60d28f.png">

I was able to reproduce this in the following codesandbox example:

https://codesandbox.io/s/web-components-vanilla-js-forked-6psh7t?file=/index.html:196-241

There is another [Slack convo here](https://dsva.slack.com/archives/C01DBGX4P45/p1704926943917649) that mentions that they are getting `undefined` for the `va-accordion` expand all toggle.

## What I expected to happen

I expect that translated text loads the initial English text as well as provides translations if they are available.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Visit to [codesandbox example](https://codesandbox.io/s/web-components-vanilla-js-forked-6psh7t?file=/index.html:196-241).
2. Note that the va-memorable-date compnent is not displaying the English text "Please enter two digits for the month and four digits for the year" or "Required".
3. Toggle the language buttons and noticed that translated text does not toggle.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other

I don't think this is blocking any work but I think that it's important that we resolve this otherwise there are components that are not loading in their entirety.

**Comment by jamigibbs** [comment]
This is the PR for setting up the component library in design.va.gov for reference:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/815

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1620?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Possibly related Slack thread about issues with translated strings: https://dsva.slack.com/archives/C01DBGX4P45/p1704926943917649

**Comment by caw310** [comment]
This is a discovery issue as a few teams have raised this as a problem.

**Comment by caw310** [comment]
Started in Sprint 46

**Comment by harshil1793** [comment]
Created a followup discovery: https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/77588
