### ISSUE TITLE
Add an option to allow accordion and additional info components to be open on page load

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#1621]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Accordions and additional info components are always closed on page load

## What I expected to happen

I expected an option to be available that would allow the components to be open (or closed) on page load. The option does not exist currently in the design system.

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other: fixing this bug will allow for accessibility improvements of other components

**Comment by jeana-adhoc** [comment]
For more context, [here is an example of where it could be used](https://codepen.io/jeana/full/oNPyRaR). I would like to present an option where legal text could be added to the component and the component be open on page load. This would allow the leagelese to be still visible and skimmed by sighted users, and also AT users would be notified of it's existence and be given the choice whether or not to have all of the text read to them.

**Comment by Mottie** [comment]
The [Higher-Level Review wizard](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start) (we will convert this to a sub-task soon), if you choose "A claim other than disability compensation", a link [Send the completed form to the benefit office](https://staging.va.gov/decision-reviews/higher-level-review/#find-addresses-for-other-benef-8622) is shown that will auto-open the accordion on that static page - this is built-into the web component; but there isn't a property to have the accordion open by default.

**Comment by Mottie** [comment]
I've been working on fixing the review & submit page accordions, and I can confirm that adding an `open` property to the web component will make the accordion show as expanded initially on page load; Adding an `open` property to the additional info doesn't work.

**Comment by Mottie** [comment]
@caw310 You can already programmatically open accordions, but not additional info blocks. @jeana-adhoc told me her team no longer has this need, so I think we can close this issue? Unless y'all have a plan to add a method to start with an additional info component expanded?
