### ISSUE TITLE
USWDS v3 - Number input - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1624]
We need to incorporate the designs for the USWDS Input Mask & Text input  (VA DS Number input) into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Text input component](https://designsystem.digital.gov/components/text-input/)
[USWDS Input mask component](https://designsystem.digital.gov/components/input-mask/)
https://designsystem.digital.gov/components/input-prefix-suffix/
[VA DS Number component](https://design.va.gov/components/form/number-input)

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Design will be completed today but this will need review so will carry over into the next sprint.

**Comment by LillyBoot** [comment]
I couldn't create an MVP version for the credit card inputs because font awesome does not have credit card icon
