### ISSUE TITLE
Update component usage data script to output instance locations

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1647]
## Description
Currently, the component usage data script outputs only a 'blind' count of how many instances of a component exist. This ticket seeks to see that the script is updated to also output "where" the instances of a component exist.

## Details
Component usage data is currently generated by following these instructions, culminating in the `yarn report` command being run from within component-library/packages/design-system-dashboard-cli.

## Tasks
- [ ] Update the script which is run to output a CSV file that can be imported into Excel or Google Sheets or something similar.

## Acceptance Criteria
- [ ] Accurate files are generated

**Comment by humancompanion-usds** [comment]
I think we're good to close this so long as Carol and Andrew have worked out when and how it will be updated.

**Comment by Andrew565** [comment]
This will update as part of the component usage data update that is already being performed on Fridays. It will generate a CSV file which will then need to be imported into the Google Sheet. There is a chance that this will also necessitate re-making the pivot tables, haven't tested this yet but will when I run the update shortly.
