### ISSUE TITLE
DS Playground: Add va-textarea

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/vets-design-system-documentation#1652]
## Description
In order to demonstrate compatibility between v1 and v3 components when loaded on the same page, the `va-textarea` components should be added to the DS Playground's "V1 and V3 Side-by-Side Demo" page.

**va-textarea story**: https://design.va.gov/storybook/?path=/docs/uswds-va-textarea--default

## Additional Info
- The design system playground is on the `ds-playground` branch in vets-website.
- Create a feature from the `ds-playground` branch for this work.
  - **Important**: Merge `main` into `ds-playground` before creating a feature branch
- Create a PR that merges your feature branch into the `ds-playground` branch.

https://github.com/department-of-veterans-affairs/vets-website/tree/ds-playground/src/applications/ds-playground

## Acceptance Criteria
- [ ] The V1-compatible and V3-compatible versions of this component render correctly and function correctly when loaded simultaneously within the DS Playground app.

**Comment by caw310** [comment]
Closing as this is a duplicate but this ticket has more details so they're cross linked.
