### ISSUE TITLE
Update DS Documentation to use Sketch Naming Conventions best practices for all Sketch files 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#1666]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Update documentation

### What is the name?

[About/Naming](https://design.va.gov/about/naming) and [About/Designers/Sketch for Teams](https://design.va.gov/about/designers/sketch-for-teams-at-va)

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Add a section to the [Naming Convention documentation](https://design.va.gov/about/naming) and the [Sketch for Teams](https://design.va.gov/about/designers/sketch-for-teams-at-va) page in the About Section for working inside of Sketch specifically. Also, update the [Getting Started artboard](https://www.sketch.com/s/2f665c26-160d-474e-b5cc-bb94e73bb91a#Version) in the Sketch for Teams Template.

Allows for standardized naming conventions for designers to follow when creating Sketch files specifically for Page, Artboard, and Group names since these are not already defined in the Design System. It will help designers working on the same files to keep things consistent and more readable. 

Use these rules defined by the [Sketch Assistant](https://www.sketch.com/extensions/assistants/@sketch-hq/sketch-naming-conventions-assistant/):

- [Page names](https://github.com/sketch-hq/sketch-assistants/tree/main/assistants/core/src/rules/name-pattern-pages) should start with an emoji, e.g. 🚧 Work in Progress.
- [Artboard names](https://github.com/sketch-hq/sketch-assistants/tree/main/assistants/core/src/rules/name-pattern-artboards) should start with numbers followed by a space, e.g. 1.1 Splash Screen.
- [Group names](https://github.com/sketch-hq/sketch-assistants/tree/main/assistants/core/src/rules/name-pattern-groups), default names such as Group are forbidden.
- [Symbol names](https://github.com/sketch-hq/sketch-assistants/tree/main/assistants/core/src/rules/name-pattern-symbols) should be using forward-slash grouping, e.g. Icon/Frog.

**Comment by caw310** [comment]
@josephrlee , Would you be able to attend the Design System Council meeting on Friday, April 7 at 1pm to talk about this request? It would be helpful if you could speak to this with the group.

**Comment by humancompanion-usds** [comment]
@josephrlee - Having some consistency with page names and artboard names makes sense to me. Symbol names are already standardized via the Design System component library. How folks names their groups and symbols seems a bit pedantic. What are the goals here or the problems this would solve?

**Comment by caw310** [comment]
Closing as we have migrated to Figma so this should have been addressed.
