### ISSUE TITLE
va-accordion is not displaying styling or icons 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/vets-design-system-documentation#1679]
# Bug Report

- In using the `va-accordion-item` component, There is no way to style or use icons in the header. This looks like a by product of using a custom render method instead of relying on `slots` to do their work and is related to [this TODO](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-accordion/va-accordion-item.tsx#L106)

## What happened

- Instead of render any HTML/JSX that is passed to the header as HTML, its render as a string. 

## What I expected to happen

- The component to render the HTML passed as HTML

## Reproducing

offending code sample 

```
 <va-accordion >
      <va-accordion-item>
        <div slot='headline'>
          <h3 style={{fontWeight:700}}><i class="fas fa-paperclip"></i>Did the thing!</h3>
        </div>
        shall make no law respecting an establishment of religion, or
        prohibiting the free exercise thereof; or abridging the freedom of
        speech, or of the press; or the right of the people peaceably to
        assemble, and to petition the Government for a redress of grievances.
      </va-accordion-item>
<va-accordion >
  
```

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

- I have started to work through this but progress is slow

**Comment by humancompanion-usds** [comment]
This is the design from Secure messaging: https://www.sketch.com/s/32bdb345-fb1f-409b-985f-ff627cb60032

**Comment by caw310** [comment]
@mdewey it seems this is more of an enhancement. Can your team handle this work? Would be great if you could. Let me know if you cannot and your time frame for when you would need this.
