### ISSUE TITLE
Elements in Sketch symbols are overlapping across versions

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#168]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When you try to apply the `required` label to a form input in Sketch 61.2, the `required` overlaps the form input label.  

The same thing occurs when you try to use a button with an icon on the right, and update the label.

When you look at these elements in older versions of Sketch (I also have 51 installed), this isn't an issue.  Suspect this is due to changes in how Sketch handles resizing content across newer versions.

## What I expected to happen

The elements should be pinned to the right side of the element and preserve spacing between the label and the `required` / icon.

I'm not sure what the breakpoint is...e.g Sketch 59 may be okay.
![image (6)](https://user-images.githubusercontent.com/55992116/72812724-06e52a00-3c30-11ea-921f-fc75da3e8ecc.png)

## Reproducing
- Formation version: latest
- Device: MacBook
- Sketch: Compare across version 51 and 61

Steps to reproduce:

1.  Open a file in the latest version of Sketch. 
2. Go to Insert > VA Pattern Library and select either a button with an icon, or a text input form field
3. Insert the symbol, and then update the label via the overrides

**Comment by CrystabelReiter** [comment]
Fixed overlapping symbols with updating to sketch 67 and using smart layout
