### ISSUE TITLE
Add minimized header/footer to the Sketch file (potentially real code too?)

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/vets-design-system-documentation#169]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Minimized header/footer

## Do you have a suggestion for a new component or utility?

There was work done to suggest a minimized header/footer for certain use cases and partner sites here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/secondary-header-footer/design/VA-subdomain-header-footer.pdf

Should we add it as an official thing available in the Sketch file? And potentially as code available elsewhere (TBD)?

## Additional context

I found out about this because I was asked to consult on a EULA/terms of service microsite for the transition from MHV to My VA Heath. It seems there could be additional partner-ish projects that could benefit from this component.

EULA/terms of service design work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5242

**Comment by caw310** [comment]
Closing as we're making a lot of updates to sketch.
