### ISSUE TITLE
Update list of components that have a migration script and clarify ESLint rules

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1703]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We have a list of components that have a migration script and which throw a warning via ESLint:
https://design.va.gov/about/developers/using-web-components#web-component-migrations

That list is now out of date in that all deprecated components throw an error. Thus we just want to list the components that remain to be deprecated and a list of web-components that have a migration script.

## What I expected to happen

Expected this list to be updated.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details
It would clarify the current state to get this updated.

**Comment by jamigibbs** [comment]
I think we should do this at the same time this PR is merged: https://github.com/department-of-veterans-affairs/vets-website/pull/23737

**Comment by caw310** [comment]
Adding to sprint 26 as unplanned since it goes with 1707
