### ISSUE TITLE
Action link icon displaying an underline on mobile devices

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1706]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On mobile devices, the [action link](https://design.va.gov/storybook/?path=/docs/components-action-link--primary) is showing an underline below the icon. I was unable to reproduce this in the browser but I was able to see it using Browserstack iPhone 13 Chrome.

![Screenshot 2023-04-24 at 10 11 41 AM](https://user-images.githubusercontent.com/872479/234040695-8b48a76e-438a-4904-9158-fde3601bab73.png)

## What I expected to happen

I only expect to see an underline below the link text and not under the icon.

## Reproducing
- Formation version: 7.0.5
- Device: iPhone
- Browser: Chrome

Steps to reproduce:

1. On a mobile device, navigate to [https://www.va.gov/resources/the-pact-act-and-your-va-benefits/](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by josephrlee** [comment]
I was gonna post this same issue as well but just saw it here already. FYI, I was able to reproduce the issue on my personal iPhone 12 mini. Attached is a screenshot for reference from staging:
![IMG_49D4483909C7-1](https://user-images.githubusercontent.com/1631062/234699307-28dd9768-74f6-43d4-b5f7-3ce72eed16ab.jpeg)

**Comment by powellkerry** [comment]
It looks like this may be an issue with the latest publish. `display: inline-block` is present in 7.0.4 of formation.min.css `(a.vads-c-action-link--blue:before, a.vads-c-action-link--green:before, a.vads-c-action-link--white:before)` but does not appear in the 7.0.5 version. Safari will underline the icon unless that is present. The latest commit states that updates were made to make text wrap properly.
