### ISSUE TITLE
Experimental Design va-accordion-item sub header icon

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/vets-design-system-documentation#1709]
## What
The Secure Messaging Team on the MHV on va.gov initiative is looking to expand the capability of the `va-accordion item` to have a more  expressive sub header. 

## Purpose
To support this UX : https://www.sketch.com/s/32bdb345-fb1f-409b-985f-ff627cb60032

## Usage
This will be able to support a more detailed view of messaging; see the above screen shot

## Behavior
Update the sub header to be styleable via the `::part` selector. and add a sub header 

## Examples
The sample code usage would look lke 

```
<va-accordion-item subheader="My subheader text that I can style with part"> 
   <i slot='icon' class='...'>
   <h2 slot='header'>
     blah
   </h2>
   <i slot='subheader-icon' class='blah'>
</va-accordion-item>
```
## Accessibility
Aligns with current icon guidelines

## Guidance
> What would you want to tell other teams about this component or pattern?

## Code (optional)
This would be based on the [recent header work ](https://github.com/department-of-veterans-affairs/component-library/pull/679)

## Next steps
I have already chatted with @jamigibbs about this and I am going to start coding up this solution.

**Comment by caw310** [comment]
@mdewey , did you already do this?
