### ISSUE TITLE
Save in progress intro content issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#1710]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using the `SaveInProgressIntro` on a form's introduction page, it can be set up to:
- Sign in prior to starting the app (Sign in button; [Request a Board Appeal example](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182))
- Start the app without signing in (start app link; [mock form example](https://staging.va.gov/mock-form))

|| Sign in optional | Sign in required |
|-|------------------|------------------|
| Main (above process list) | <img width="698" alt="sign in optional. Has a start your application without signing in link" src="https://user-images.githubusercontent.com/136959/234391777-57230585-3c86-4ec0-a1ae-f38a5071445b.png"> | <img width="695" alt="sign in required. Has sign in button" src="https://user-images.githubusercontent.com/136959/234391784-94febf3f-f357-4e86-be8e-d56f78a6b593.png"> |
| Button only (below process list) | <img width="331" alt="Screenshot 2023-04-25 at 3 23 48 PM" src="https://user-images.githubusercontent.com/136959/234395201-9f4c2ca9-007f-44da-821a-29b1290f68a1.png"> | <img width="293" alt="Screenshot 2023-04-25 at 3 22 59 PM" src="https://user-images.githubusercontent.com/136959/234395204-1c87480b-0043-4900-b8d0-142e529068ac.png"> |

But, in the sign in required view, the note stating you can sign in _after you start your application/request_ still exists.

<img width="701" alt="sign in required showing Note: You can sign in after you start your request. But you’ll lose any information you already filled in." src="https://user-images.githubusercontent.com/136959/234391782-b1b7cf7f-d0f6-485a-beff-c8b192888485.png">

## What I expected to happen

The note about signing in after you start the application should not be visible for sign in required app.

## Reproducing
- Formation version: All
- Device: (e.g. iPhone 8, Macbook) All
- Browser: (e.g. Firefox, IE 11) All

Steps to reproduce:

1. Go to [Mock form app](https://staging.va.gov/mock-form) to see optional sign in alert
2. Go to [Request a Board Appeal](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182) to see the required sign in alert

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

Other things to consider:

- Content review of save in progress alert
- Replace `usa-alert` elements with `va-alert`
- Replace `button` with `va-button`
- Consider changing "Start your application without signing in" to a secondary action link?
- Update design for button-only view

**Comment by jstrothman** [comment]
As info, while this isn't a current blocker, it is currently live on VA.gov

**Comment by eileen-coforma** [comment]
Checked on staging. Looks good 👍

**Comment by Mottie** [comment]
Closing, work complete
