### ISSUE TITLE
Experimental Design [va-date]

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/vets-design-system-documentation#1711]
## What
Updating va-date to allow conditionally disabling the input. This can probably be asynchronous review, but I'm available if there's any questions/concerns!

## Purpose
Per our design team's request we have a ticket necessitating the use of disabled on a few dates in our form, with a likely future need as well.

## Usage
Va-date will be disabled based on conditional logic supplied to the component.

## Behavior
Inputs will disable when condition supplied is met.

## Examples
N/A

## Accessibility
From what we know this is the lesser of two evils that our design team has chosen. Per the reasoning on buttons (https://design.va.gov/components/button/#do-not-disable-buttons) we know that we shouldn't disable and opt to remove; however, we believe that removing/re-adding the date field in the middle of the page will be jarring to screenreader users.

## Guidance
We can now dynamically disable va-dates!

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.

## Code (optional)
> Include any existing code.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by HeatherRienks** [comment]
Following

**Comment by caw310** [comment]
@OptionSelect , We don't have an a11y specialist on the DST so I've submitted a request for help to verify this. https://github.com/department-of-veterans-affairs/va.gov-team/issues/57845

Will follow up once we have more information.

**Comment by caw310** [comment]
@OptionSelect here is the feedback from a11y specialist regarding your request. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/57845

**Comment by humancompanion-usds** [comment]
A solution was provided by CAIA and it sounds like the team implemented that solution: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57845

**Comment by HeatherRienks** [comment]
FYI - @mgleo, @charlottecesana, @josephrlee, @Tom-Davis
