### ISSUE TITLE
Cannot set width of VaTextInput

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#1712]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Some form input fields we would like smaller width. Here is an example:
This text field is applying `'usa-input-medium'`
![image](https://user-images.githubusercontent.com/123402053/234920022-1004a638-a18e-435c-8f54-81e4bd218bd0.png)

Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1682110833661429?thread_ts=1681943660.853739&cid=C01DBGX4P45

Related ticket:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1704

Workarounds:
We can target `va-text-input::part(input)`, but sounds like we want a more built-in solution to this based on the slack thread above.

## What I expected to happen

Text input should allow for variations or customization in width in a straight forward manner

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook), windows 11 
- Browser: (e.g. Firefox, IE 11) chrome

Steps to reproduce:

1. create a va-text-input or VaTextInput
2. try to change width to a small size in the code

## Classification
- visual issue

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment]
We should also look at making the width dynamic for `va-number-input` as well: https://dsva.slack.com/archives/C01DBGX4P45/p1684335127702679

**Comment by caw310** [comment]
Reference text input variants in USWDS.
https://designsystem.digital.gov/components/text-input/

**Comment by jamigibbs** [comment]
https://designsystem.digital.gov/components/text-input/#component-variants-text-input

`usa-input--[width]`

> Displays an input at a specific width. Accepts 2xs (4ex), xs (7ex), sm or small (10ex), md or medium (20ex), lg (30ex), xl (40ex), and 2xl (50ex).

**Comment by josephrlee** [comment]
@jamigibbs, I know this is a closed issue, but can this width prop be added to the `va-select` component? It'd be helpful to have on the FSR.
