### ISSUE TITLE
Documentation error for Full Width Alerts Warning

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/vets-design-system-documentation#172]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [x] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the nature of this update?

- [ ] When to use
- [ ] When to use something else
- [ ] Code snippet
- [ ] Accessibility
- [ ] Research insight
- [x] General documentation

## Additional Context

From a dev on my team: " https://design.va.gov/components/alertboxes#full-width-alerts
In their Full Width Alerts Warning section they have
"usa-alert-full-width-info" instead of "usa-alert-full-width-warning"
under the Show HTML section and I for one can tell you it'll confuse
the heck out of any developer that tries to use it the first time
around."

**Comment by emilywaggoner** [comment]
Documenting my understanding of the errors here. It appears that the class names are wrong on both HTML snippets of the `usa-alert-full-width-info` and the `usa-alert-full-width-alert` on [this page of the design system](https://design.va.gov/components/alertboxes#full-width-alerts).

Here are screenshots of the errors:
<img width="750" alt="Screen Shot 2020-02-12 at 3 39 59 PM" src="https://user-images.githubusercontent.com/1379629/74375698-cac86380-4dae-11ea-8d16-3f4774adcd61.png">
<img width="759" alt="Screen Shot 2020-02-12 at 3 40 31 PM" src="https://user-images.githubusercontent.com/1379629/74375699-cb60fa00-4dae-11ea-83ab-ccf13d2df503.png">

I am going to validate with the dev and circle back here!

**Comment by bastosmichael** [comment]
ya though I had to use *-warning to get the visual look that I needed, had no idea *-alert was even an option. https://github.com/department-of-veterans-affairs/developer-portal/pull/311

**Comment by emilywaggoner** [comment]
Welp I think that's because it's not an option! And I put the wrong label in the screenshot. `-warning` is the right one. Thanks @bastosmichael.
<img width="750" alt="Screen Shot 2020-02-12 at 3 39 59 PM" src="https://user-images.githubusercontent.com/1379629/74376921-f9dfd480-4db0-11ea-89b7-0e0ce8f77ba3.png">
