### ISSUE TITLE
Presubmit form required fields and triggers

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/vets-design-system-documentation#1729]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

*Background information on form 22-5490 - if the applicant is a minor there is a trigger that shows a hidden page for the guardian to then fill out. There are also questions about if the minor has or will complete high school that trigger as well.

When working through form 22-5490, once in the presubmit page it allows the applicant to edit the form. If the applicant tries and edit the 'Your date of birth' field under the 'Applicant Information' section and the date currently entered makes the applicant 18 or over, then with the updated date the applicant is now under 18 years of age, the trigger that is seen in the actual form does not show up.

When working through the form the applicant is asked for their date of birth. Based on their birthday, if the applicant is a minor there is a message that pops up explaining that the minor will need a guardian to fill out the guardian section of the form that conditionally renders solely based on if the applicant is a minor. This also triggers a new question that asks if the applicant has graduated high school. This question appears under the 'Your date of birth' field as seen in the below screenshot.
![image](https://user-images.githubusercontent.com/88905347/235967065-51929f11-e572-4b8a-8c4c-c4ff4c3f5377.png)

This new question chain is required and depending on if the applicant has graduated or has received a GED there are follow up questions. 

With the applicant being a minor, once I reach the end of the form and expand the Applicant Information in the presumbit section, the first issue is found. The questions about the minor's high school or GED status does not show under the 'Your date of birth' field. I believe the issue is part of the presubmit page since I can see in Redux that the relativeDateOfBirth contains the correct information and this is the data that triggers the expansion of the follow up questions about high school and GED completion. 

(Screenshot showing date of birth as Nov 16 2020 and on the right hand side showing the same date of birth in redux)
![image](https://user-images.githubusercontent.com/88905347/235969468-2eb18c0d-61bd-4f39-8f0d-53addce7f4e1.png)

(Screenshot showing the form data that is currently loaded for the presumbit page and we can see the relativeDateOfBirth is 2020-11-16)
![image](https://user-images.githubusercontent.com/88905347/235969833-83cb8f00-f6f1-4d35-a379-96df7d3640c0.png)

If I make a change and now the applicant is 18 or older, I am able to click Update page and it works as expected. 
If I then go back and update the 'Your date of birth' field once more making the applicant a minor, I am now unable to click 'Update page'. 

Now if i try to update certain fields in the other sections I will receive an error in the console of 'Cannot read properties of undefined (reading minorHighSchoolQuestion)', this error is due to the fact that when the applicant edits the 'Your date of birth' field and are now a minor the questions below are not expanded as they should.

(Screenshot of error)
![image](https://user-images.githubusercontent.com/88905347/235972306-ebe4c2ab-4214-4ee9-81a4-b3c313d6b383.png)

With the question not expanding, I have gone through the code a few times and from what I can tell it is correct in the way it triggers the minor questions. I checked the VA platform documentation to see if there is another way to trigger questions conditionally and from what I can see the 'hideIf' is the correct way to do so. I do not believe there is an issue in the form code but rather in the presubmit section.

The second issue that was discovered is required fields can be bypassed in the presubmit section. In form 22-5490, under the  'Applicant Information' section in the presumbit page, if I change my relationship from adopted to Spouse or surviving spouse, there are a few new questions that trigger in the 'Sponsor Information' section that are required.

(Screenshot of new questions related to spouse that are required)
![image](https://user-images.githubusercontent.com/88905347/235974576-a04c1acd-6200-4b5c-9d4a-aa7f8e9ec9de.png)

I do not have to actually enter any information into these questions and the form will allow me to submit as is.

## What I expected to happen

When switching from an adult to minor based on birth date in the Applicant Information section inside the presubmit page, I expect the minor questions to trigger under the 'Your date of birth' field as they do in the form itself.

When making edits to the form in the presubmit page, I expect that any new required fields that may have been triggered to not allow the form to be submitted before being filled out.

## Reproducing
- Formation version: Not sure what this is
- Device: Any device
- Browser: All browsers

Steps to reproduce:

Issue #1
In the presubmit page and when the user is already 18 years or older according to the 'Your date of birth'
1. Click on 'Applicant Information' -> edit
2. Edit 'Your date of birth' so that the applicant is a minor
3. Minor questions should trigger under the 'our date of birth' field, but they do not

Issue #2
In the presubmit page and the applicant is not a spouse
1. Click on 'Applicant Information' -> edit
2. Click on 'Spouse or surviving spouse' under the 'What’s your relationship to the service member whose benefit is being transferred to you?' question.
3. Click 'Update page'
4. Click on 'Sponsor Information'
5. You will see there are new fields that are not filled out and are required.
6. Do not do anything to this section, now submit the form
7. The form will submit without forcing the required fields to be filled out

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other

### Details
This code is currently in production.

**Comment by Andrew565** [comment]
Please try asking someone on your team or in the Frontend COP for help with double-checking your configuration. If still unable to resolve we can look into what the underlying issue might be.

**Comment by micahchiang** [comment]
This is old so I'm not sure if these are still issues or not. These are not inherently design system challenges, but I do have a couple of thoughts:

Regarding the first issue:
- The review page doesn't update the redux store the same way the regular form flow does. Prior to reaching the review page, I believe `SET_DATA` is called on _every_ onBlur, and maybe even more frequently, which continuously updates formData in the store. The result here is that the conditional question chain if someone is a minor is triggered pretty much immediately. The review page only invokes `SET_DATA` once the update button has been clicked because that's what users would expect to happen in this instance. 
- The above also suggests why the update button may not work when attempting to edit dob a second time: form validation is failing silently on fields that are required but aren't rendering. You likely need to rework how that form page is rendering fields. I'd start by taking a look at the [keepInPageOnReview](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-about-schema-and-uischema) property. 

Regarding the second issue:
- Submission is based off formData in the current redux store. Even though a section is open for editing, if update is never clicked, then formData is never updated. With this, submission may work because what was already in the redux store is technically valid data. This is likely a bug worth looking into. I recommend partnering with the vfs forms library team on this.

**Comment by jsimonVA** [comment]
Forgot about this ticket to tell the truth. We find the issue and were able to fix it. I vaguely remember the fix I found, but it had to do with the way the date filed was opening under another field. Once I changed this in the code it worked as intended. I am going to close this out.
