### ISSUE TITLE
Forms Lib - Replace Select component

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1735]
## Description

As part of [this epic](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1530), we will replace all instances of the React Select component in the Forms Library with the Web Component version.

## Details

The Select component is currently being used in the following files:

- vets-website/src/platform/forms/save-in-progress/SaveInProgressDevModal.jsx

## Tasks

- [ ] Replace the React component with its Web Component component, updating any necessary props and/or logic related to the smooth operation of the component
- [ ] Ensure the web component works correctly - likely, by either finding an existing app that makes use of it or by creating a new, temporary form
- [ ] Update any accompanying tests
- [ ] Get design sign-off to ensure that the new Web Component looks and feels 'correct'

**Comment by caw310** [comment]
Will carry over into the next sprint.

**Comment by ataker** [comment]
Removing the react component is causing a large number of test failures. Blocked until [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1839) is resolved.

**Comment by caw310** [comment]
Moving out of the sprint. Once other issue is fixed we will continue work on this.
