### ISSUE TITLE
clean up duplicative text styles

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/vets-design-system-documentation#177]
# Bug Report
There are a bunch of duplicative text styles in the Library (some of which are seemingly duplicates, while others are very different, but named the same title. 

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Looks like some duplicates snuck in

## What I expected to happen

one single text style per text variant

![image](https://user-images.githubusercontent.com/12564977/76450730-a7d8a180-63a4-11ea-9bdb-87d05bc19770.png)

**Comment by CrystabelReiter** [comment]
Deleted duplicative text styles
