### ISSUE TITLE
Add mobile text styles 

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/vets-design-system-documentation#178]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Text styles for mobile

## Do you have a suggestion for a new component or utility?

I do! I made a quick pass at a handful of pages on va.gov, and I believe the only styles that scale  for mobile are `h1`, `h2`, and `Lead`. I documented those numbers below!

**`h1`**
desktop = 40/52 
mobile = 32/39

**`h2`**
desktop = 30/39
mobile = 24/31

**`Lead`**
desktop = 20/34
mobile = 16/27

## Additional context
I didn't find any other text styles that scaled on smaller screens…but that doesn't mean they aren't out there. I'm not sure if there is a way to search for site-wide media queries or w/e in order to root them out.

**Comment by artsymartha68** [comment]
Also need to consider the base font size optimization on mobile per this issue:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/12942

**Comment by humancompanion-usds** [comment]
Mobile typography is documented here: https://sketch.com/s/610156b6-f281-4497-81f3-64454fc72156
