### ISSUE TITLE
Inconsistent margin tops among web components

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#1780]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.
- related: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1704

## What happened

When using `usdws: true` web components, the margin-top of various web components is inconsistent (e.g. va-text-input with a label has margin top, but  va-radio, va-checkbox does not), causing some fields to be too close to each other. 

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/ac6f08e0-1e10-4202-bab4-7aac1d16f2d3)
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/678e44b4-d797-4bee-b4dd-c7b055d85bae)
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/5c16e35d-fb26-4ef2-8481-f7c2a2f939a1)

## What I expected to happen

Expect a common behavior for all web components used as fields in a form. 
Expect DST to either standardize these margins across all web components, or provide a guideline for teams so that a reliable CSS strategy can be used for v3 web components in a form so we don't have some fields with 0 margin, and others with + margin.

## Reproducing
- Device: Windows
- Browser: Chrome

Steps to reproduce:

1. place a text input, radio, and checkbox, (and probably a good idea to test others) next to each other. Notice some have a margin top and others do not.

## Related conversation
-  https://dsva.slack.com/archives/C01DBGX4P45/p1683909704104809

## Classification
- Visual issue (CSS)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by it-harrison** [comment]
Hi @LillyBoot here is a summary of the top margins of the `uswds` form components:

| **component**     | **margin top** |
|-------------------|----------------|
| va-checkbox-group | 0px            |
| va-checkbox       | 12px (1.2rem)  |
| va-memorable-date | 30px (3rem)    |
| va-number-input   | 24px           |
| va-radio          | 0px            |
| va-select         | 24px           |
| va-text-input     | 24px           |
| va-textarea       | 30px (3rem)    |

here is a visual aid:

<img width="587" alt="Screenshot 2023-06-16 at 12 28 04 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/8867779/57fb8368-8de3-4cbe-877b-9ca75856caec">

**Comment by babsdenney** [comment]
Here is an audit of the USWDS component spacing comparing the spacing to Ian's audit of VA's web components. 
Generally, the top margins for form elements are:

- 1.5rem for label
- .75rem for labels within checkboxes and radios
- .5rem for labels within checkbox and radio tiles
- .5rem for text inputs and selects 

@humancompanion-usds @LillyBoot How would you want to proceed?

| Component | USWDS | VADS |
| ---- | ---- | ----------- |
| va-checkbox-group | 0px  | 1.5rem |
| va-checkbox | 12px (1.2rem)  | .75rem |
| checkbox tile | | 1.5rem (legend) .5rem (label) |
| va-memorable-date | 30px (3rem) | 1.5rem |
| va-number-input | 24px | 1.5rem |
| va-radio | 0px | 1.5rem (legend) .75rem (label) |
| va-select | 24px | 1.5rem (legend) .5rem (select) |
| va-text-input | 24px | 1.5rem (label) .5rem (input) |
| va-textarea | 30px (3rem) | 1.5rem (label) .5rem (input) |

Here is a more extensive [audit of component margins](https://docs.google.com/spreadsheets/d/1snfle1uJBFkr6MpXmTbU4hxsfC7-5camsm1rf_X48jc/edit?usp=sharing) in the USWDS.

**Comment by caw310** [comment]
@babsdenney thanks for that audit and the breakdown! 
@it-harrison , do you have the information you need now?

**Comment by humancompanion-usds** [comment]
We must align with the USWDS spacing that Barb outlined.

**Comment by caw310** [comment]
This may carry over due to unexpected pto.

**Comment by it-harrison** [comment]
PRs:
* https://github.com/department-of-veterans-affairs/component-library/pull/735
* https://github.com/department-of-veterans-affairs/component-library/pull/736
* https://github.com/department-of-veterans-affairs/component-library/pull/737
