### ISSUE TITLE
Can we remove this?

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/vets-design-system-documentation#1807]
## Description
In the console, the `console.log('DOM fully loaded and parsed')` displays on all sites that use web components (see: https://github.com/department-of-veterans-affairs/component-library/blob/27cd47817dc45a5d56761fe12511403c5d215032/packages/core/src/i18n/i18n-setup.js#L26)

## Potential Options
- Option 1
  - [ ] Remove the console.log
- Option 2
  - [ ] Remove it during the build process

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
