### ISSUE TITLE
Discovery: Determine best way to submit the textarea component to USWDS

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1810]
## Description

As a team that wants to contribute code back to USWDS, we need to determine "what" and "how" we will prepare our code for their inclusion.

## Questions to Answer
- [X] Do we need to strip out our Formation-specific component code? - Yes
- [X] Do we need to strip out our Formation-specific styles? - Yes
- [X] If yes to either or both of the above, what strategy will be easiest and most successful to implement:
  - [X] Should we split our component code into V1 and V3 files? - No, messes up our codebase
  - [X] Should we create a fork of our web-components repo and manually strip out Formation-specific code? - Yes, easiest and cleanest
  - [X] Should we create a system for programmatically stripping-out Formation-specific code as part of a build step? - No, very time-consuming, complex, and likely would need a lot of manual interventions
  - [X] Is there another strategy - No other options explored at this time
- [X] Do we need to setup Stencil for USWDS as part of the PR? - Yes, included in fork

## Acceptance Criteria
- [ ] Solution identified and agreed upon

**Comment by Andrew565** [comment]
Another thing to consider here is the fact that our components are all named va-component-name, whereas uswds would probably prefer a usa-component-name naming scheme? We may need to check with them how they want their components to be named.

**Comment by humancompanion-usds** [comment]
Yes, agreed that we should scrub the code in some way before submitting a PR. Could we automate that in a build step?

**Comment by Andrew565** [comment]
Automating in a build step is one option, though not necessarily a very straightforward one because it will require navigating the code and likely several regexes. Would basically involve creating a custom parser/tokenizer in order to identify which blocks to keep and which to ditch. I'm keeping it as an option for now, but I think the other two named options above - forking or splitting - would yield quicker results.

**Comment by caw310** [comment]
This work is done so closing.
