### ISSUE TITLE
add simple error alert as a symbol

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/vets-design-system-documentation#182]
# Feature Request

Add simple version of error alert

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Sketch Library — Error alert - large

## Do you have a suggestion for a new component or utility?

Currently, the only version of an error alert (labeled "Alerts: Error - Large") in the Sketch library has a header, body text, a subhead and more body text:

![image](https://user-images.githubusercontent.com/12564977/79223194-df64be80-7e26-11ea-8095-1c0efa7d2051.png)

Sometimes an error alert can be simple, mirroring our Warning and Information alert symbols. Because we don't have a simple version in the Sketch Library, designers have to break the symbol which isn't ideal. We could add a Simple version into the Library, that looks like this:

![image](https://user-images.githubusercontent.com/12564977/79223838-17203600-7e28-11ea-8701-54aa61f4bada.png)

I'm not sure what the best naming conventions are here, but something to allow designers to not break symbols would be great!

**Comment by CrystabelReiter** [comment]
Thanks! @rtwell I'll add this item to the next update
