### ISSUE TITLE
Continue/Back mobile button pair not stacked in Sketch library

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/vets-design-system-documentation#1820]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
Continue/Back mobile button pair should be stacked in the [Sketch pattern library](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156) and is currently showing as inline. Design documentation should also be updated to reflect that the expected mobile behavior is that these are stacked. Here is what the current [documentation](https://design.va.gov/components/button/button-pair#mobile-behavior) says:

>At and after the [small-screen breakpoint](https://design.va.gov/foundation/breakpoints#names-and-values) the buttons left align and revert to a natural width (i.e. as wide as they need to be to accommodate their label) with the secondary button continuing to appear before the primary button.

![screenshot_2023-06-01_at_12 13 05_pm_720](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/104526584/bfdb4363-3297-4afa-89fa-f9dcb564dbb4)
Screenshot of current Sketch library

## What I expected to happen
Continue/Back button are stacked and design documentation is updated to reflect how this should behave. 

## Reproducing
- Formation version:
- Device: Macbook
- Browser: Chrome and Desktop

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jeana-adhoc** [comment]
In researching #1829 I found this ticket, and realized it's closely related. But looking further, I discovered additional inconsistencies in the DS guidance and the examples provided in storybook.  

[The DS says:
](https://design.va.gov/components/button/button-pair#mobile-behavior)   
> Primary and secondary buttons should appear full-width up until the [small-screen breakpoint](https://design.va.gov/foundation/breakpoints#names-and-values) with the secondary button being on top of the primary button with [2 spacing unit](https://design.va.gov/foundation/spacing-units#spacing-unit-tokens) of separation between them.

But the story book examples, when resizing for mobile, shows 
<img width="295" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/6f949a6b-48df-4db8-b3ed-55683e982b99">

In the example, the secondary button is below the primary button. This will become problematic for screen reader users who will likely not know there is a secondary option available. 

Also, if the desired behavior is for buttons to always be stacked in mobile views, this guidance should be updated as well:
> It is also acceptable for the buttons to be half-width and centered at smaller viewport sizes, as they are in the [Back/Continue](https://design.va.gov/components/button/button-pair#backcontinue) button pair variation.

**Comment by laflannery** [comment]
Related to the comment from @jeana-adhoc above about the stacked positioning for small screens, when these are stacked on mobile, the visual presentation is mismatched from what is in the DOM. In the DOM "Back" is first, followed by "Continue" but visually this is swapped. This confusion is going to present issues for visual keyboard users or low vision users that might be supplementing with a screen reader on mobile.
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106678594/60e6d1f9-8e72-40ae-bc7e-b609bfb13696)

**Comment by LillyBoot** [comment]
@laflannery @jeana-adhoc Just wanted to make a quick note here since the stacking ordering was brought up when the buttons were first designed. The reasoning behind having the continue button on top for the mobile view was because we always have the primary button on top

**Comment by babsdenney** [comment]
@LillyBoot @humancompanion-usds This button pair has been added. 

[Continue back button pair in Pattern Library](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/mPKm717#Inspect)
