### ISSUE TITLE
Extend button pair in v3 sketch library to include back/Submit application

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#1829]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.
- However - there is a related issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1820

## What happened

I am unable to extend the button pair for back and continue so that a back / submit application button follows the DS system rules. I could rebuild the symbol, but this would need to be done for every form, and it would be useful if this were available in the sketch library.

## What I expected to happen

I expected a button pair to be available to that would allow me to have a `<< back / submit application` button pair that followed the [DS rules](https://design.va.gov/components/button/button-pair).

Desired outcome:
<img width="314" alt="back button next to a submit application button" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/bc5971cf-b777-4c37-b513-f208f3403543">

## Reproducing
- sketch
- macbook

Steps to reproduce:

1. The DS rules state:
> Arrows are reserved. Arrow icons should only appear for the [Back/Continue](https://design.va.gov/components/button/button-pair#backcontinue) button pair.

Could a back/submit application pair also have icons? If so, then that can be extended/changed in the symbol itself by just changing the text. But as it is, you cannot turn off the icon in the symbol currently, so the only way to build this symbol in sketch is to break existing symbols apart.

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by babsdenney** [comment]
@humancompanion-usds @LillyBoot This is ready for review.

- [Pattern library](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/F2B3C09A-004C-4A71-BD77-E0A2C1EF2BAA/canvas)
- [MVP library](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/F2B3C09A-004C-4A71-BD77-E0A2C1EF2BAA/canvas)
- [V3 library](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/p/F2B3C09A-004C-4A71-BD77-E0A2C1EF2BAA/canvas)

**Comment by LillyBoot** [comment]
@babsdenney looks good to me!

**Comment by humancompanion-usds** [comment]
Approved!
