### ISSUE TITLE
Experimental Design Descriptive Back Link

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#1847]
## What

A link back to the previous page when navigating a task, or series of tasks. 

## Purpose

When a user is completing tasks:
- Provides a clear way to return to the previous step in a task.
- Reduces cognitive load: less reading is required to get back to the origination point, compared to a breadcrumb

## Usage

- This should be used in task flows, such as when a user wants to act on information presented.
    - This includes navigating between a summary view of information and details view. 
- This should not be used on content pages. 

## Behavior

When a user starts down a task flow, a `< Back to [H1 of previous page]` link shows at the top of the page in place of a breadcrumb.

## Examples

- [Wireframes showing basic functionality](https://www.figma.com/proto/CBX8AtctbeVHwh5iRrsXli/Define-IA-for-Appts---MHV-on-VA.gov?page-id=1201%3A171&type=design&node-id=1201-172&viewport=857%2C144%2C0.37&scaling=min-zoom&starting-point-node-id=1201%3A172)
- [Descriptive back link in context of a details page](https://www.figma.com/file/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?node-id=808%3A9504&t=Qc2PMIDHfhrs6MAC-1)

## Accessibility

- Breadcrumbs are in a component coded with the role "navigation" 
- Question for Accessibility SMEs: Would descriptive back links need a navigation role assigned, or any other semantic support? Or is it okay to leave them as a single link? 
- They include the previous page h1 to provide context, so no additional aria-labelling should be needed 

## Guidance

Check-in and Mobile app use a similar pattern for completing tasks, in a mobile context. Some guidance from those teams follows.

Notes from Check-in:
- Noting the H1 from a previous page is technically challenging where pages are dynamic based on how a Veteran has answered questions in the form flow, and we can't always easily identify the previous h1. 
- To maintain consistency they use a  use a default value, e.g., "back to last screen" or "back to last page"

From the Mobile documentation:
> Consistent sense of place: The app uses multiple wayfinding approaches to
> communicate where users are now in the app and where they can go from
> there. Examples of this are displaying global navigation on every screen
> in the hierarchy, screen names that are unique and descriptive, using
> common screen transitions to communicate a screen's position in the
> hierarchy, and including descriptive back labels on each screen

https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/Foundations/Information-Architecture

## Research (optional)

We tested a version of this: [Finding 6: The back link was easy to find](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-09-appts-list-usability/research-findings.md#6-the-back-link-was-easy-to-find-and-use)

## Code (optional)

N/A

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
This was discussed in the 6/16 DSC meeting. Go ahead with this. Probably call it a breadcrumb.   Come back to share results of A/B testing with DSC. Thanks!

**Comment by outerpress** [comment]
Notes from Design 6/16 Council meeting:
- Do include name of previous page if technically possible
   - If not possible, it's not a known accessibility issue to just use `< Back`
- Semantically it should be in a `<nav>` element with the role "Breadcrumb"
- @outerpress to share results with DSC when we run the study

**Comment by outerpress** [comment]
FYI @kristenmcconnell @mnorthuis @kristinoletmuskat ^^

**Comment by caw310** [comment]
Closing since breadcrumb was used. But would be good to get update on the results from study.

**Comment by outerpress** [comment]
Sorry for the slow reply @caw310 , we did end up implementing the descriptive back link on our appointment list/detail pages. We haven't done UAT yet, but I can get you basic usage numbers from Google Analytics. Let me know if that would be helpful.
