### ISSUE TITLE
Screen readers are reading modal content out twice

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#1849]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I visited two forms that both have modals in them. When navigating to them via the keyboard and screen reader, the contents of the modal are read by the screen reader aloud multiple times. 

I was also able to duplicate this in [storybook](https://design.va.gov/storybook/?path=/docs/components-va-modal--default).

## What I expected to happen

I expected the contents of the modal to only be read aloud once via a screen reader. 

## Reproducing
- Formation version: Current
- Device: Macbook
- Browser: Chrome, Safari
- Screen reader: Mac voiceover

Steps to reproduce:

1. Turn on a screen reader
2. Navigate to [storybook](https://design.va.gov/storybook/?path=/docs/components-va-modal--default#stories)
3. Open a modal window
4. Listen to the modal content be read twice

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/4d906d0c-c40f-435e-a07d-0869afc17bbc

```
<va-modal   
    clicktoclose="false"   
    disableanalytics="false"  
 
    modaltitle="Modal title goes here"   
    primarybuttontext="Primary button"   
    secondarybuttontext="Secondary button"   

    status="warning"   
    visible=""   

    modal-title="Modal title goes here"   
    primary-button-text="Primary button"   
    secondary-button-text="Secondary button"   

    class="hydrated"   
    aria-label="Modal title goes here modal"   
    aria-modal="true" role="alertdialog">

        <p>A modal may pass any React nodes as children to be displayed within it.</p>
        <p>By default, a modal may have up to one primary button, and up to one secondary button. Check the console log when clicking the buttons to see the events fired.</p><p>If more buttons are required, pass them in as children.</p>
</va-modal>
```
What I noticed is that `modaltitle` and `modal-title`, as well as `primarybuttontext`, `secondarybuttontext`, and `primary-button-text`, `secondary-button-text` are both rendered in the browser code.

But visually, nothing is repeated
<img width="450" alt="modal" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/9cb86eb9-5772-4935-940f-5b07a6b5cfd6">

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [X] Other - We are set to launch as is, but I have a feeling this is going to come back with 508 defects when we have them audit our 21-4142 form.

### Details
I was also able to duplicate this in the "remove" button in the list and loop [21-4142 form](https://staging.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/introduction) and on the "remove" button on the "Issues for review" page in the [21-0955 form](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/start)

**Comment by humancompanion-usds** [comment]
This is a high priority and blocking work. It's currently happening in production and the 508 office is likely to block us from deploying. Please fix in the next sprint. Thanks!

**Comment by ataker** [comment]
This isn't completely fixed, but it does seem isolated to Mac Voiceover and never happens on the first open, so hopefully this will be a rare incident.
