### ISSUE TITLE
Remove cursor pointer for current page in pagination component

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/vets-design-system-documentation#1851]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When hovering over the paging link for page 1 on a page within the VAMC (e.g., Boston news releases), the cursor changes to a hand, indicating a clickable element. However, clicking on the element does nothing.

## What I expected to happen

I expected that the cursor should not change to a hand when hovering over the paging link for the current page. Clicking on the element should also have no effect since it is the current page.

## Reproducing
Steps to reproduce:

1. Go to a page on within the VAMC that has paging, like Boston news releases
2. Hover over the paging link for page 1
3. Confirm that the cursor changes to a hand
4. Click on the element
5. Confirm that nothing happens when you click the element

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

Test: https://www.va.gov/boston-health-care/news-releases/

**Comment by rsmithadhoc** [comment]
This issue in particular originates in content-build, not the design system component.

However, there has been some discussion around whether the current page in the pagination should be clickable and focusable. This also applies to the breadcrumbs component, and there has been discussion there. I'll talk with the relevant parties to try and get a consensus on how it should work, then provide that guidance for the content-build update and ensure our components also follow that.

Links for reference:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1458
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/53331
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12061

**Comment by caw310** [comment]
@rsmithadhoc can we close this since you're saying that the issues is with the content-build?

**Comment by rsmithadhoc** [comment]
@caw310 Yeah, I think we are good to close this one. I'll go ahead and do that.

**Comment by laflannery** [comment]
@rsmithadhoc I was following up on this issue as it applies to something we are using on our products. There was [guidance given by CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53331#issuecomment-1804670431) for how this (breadcrumbs and pagers) should work. Currently the pager is not following this (the current page is not actionable nor focusable). Is this something I should open another ticket for or should mentioned this might be within content-build and there might be an existing ticket already for this where these updates should perhaps be directed? Let me know what the best next steps might be, thanks!
