### ISSUE TITLE
USWDS Summary Box / VA Featured Content - Design 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1857]
## Description
We need to incorporate the designs for the USWDS Summary box component into the VA Featured Content component in  the Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Summary box component](https://designsystem.digital.gov/components/summary-box/)
[VA DS Featured content component](https://design.va.gov/components/featured-content)

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by babsdenney** [comment]
@humancompanion-usds @LillyBoot This is ready for review.

I changed the name to the Summary box to align with the USWDS. We call this a feature box in the VADS and the USWDS calls it a Summary box. 

- [Desktop](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/r9GjLvd)
- [Mobile](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/nQJAYdp)

**Comment by LillyBoot** [comment]
Looks great to me!

**Comment by humancompanion-usds** [comment]
Agree with the name change & alignment with the USWDS component.
