### ISSUE TITLE
USWDS v3 - Search - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#1861]
## Design
We need to incorporate the designs for the USWDS Search component into the VA Sketch library. The version of this component with the different features from USWDS may need to live side-by-side with our component in the Sketch library for a time.

There may be some differences between the USWDS version and ours, so you'll want to do a small audit first to determine what those are. It would be helpful to present that audit to the team so everyone is aware. There may need to be some discussion about features we want to keep from USWDS and features we do not.

## Details
[USWDS Search component](https://designsystem.digital.gov/components/search/)
[VA DS Search input component](https://design.va.gov/components/search-input)

## Tasks
- [ ] Conduct small audit if necessary
- [ ]  Create designs for component
- [ ]  Review designs with PO and/or DSC
- [ ]  Review designs with an accessibility specialist (if there is a11y support available)
- [ ]  Review designs with DST members (during a weds standup)
- [ ]  Address any comments from reviews, if necessary
- [ ]  Comment on this ticket with any accessibility considerations engineers may need to know
- [ ]  Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ]  Comment on this ticket with a link to the designs

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Stretch item for sprint 35

**Comment by babsdenney** [comment]
This is ready for review. @humancompanion-usds @LillyBoot 
- [Desktop](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/nQgo2kl)
- [Mobile](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/QDjQYlb)

**Comment by LillyBoot** [comment]
@babsdenney these looks great to me! The only thing I noticed is that Search, Summary Box and Pagination are all in the "Example Library - USWDS v3 Components". These should be in the [Example Library](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c). I can move over Summary Box and Pagination. Would mind moving this one over?

**Comment by babsdenney** [comment]
@lillyboot Thanks for moving over the summary box and pagination! My apologies, I thought that the MVP was just the form components and everything was for the future version. The search symbol has been moved over. Should be good to go now.
