### ISSUE TITLE
[UXPin] Cannot tab into prototype

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1866]
## Description
Jeana on the Veteran-facing Forms team has been testing the UXPin prototype that uses our component library with a screenreader and other assistive technologies. Step 1 is being able to tab into the prototype. That isn't working. 

## Details
We'd like to find a way to put focus either on the h1 of the page or the first form field element (ideally the later). Jack Behar suggested on Slack that we could this in UXPinWrapper. "If on preview, on load, set focus to the canvas?"

## Acceptance Criteria
- [ ] Focus is placed on the first form field or the h1 within a UXPin prototype page

**Comment by Andrew565** [comment]
Matt was able to find a solution to this problem.
