### ISSUE TITLE
[Alerts] Formation alert styles causing too much padding

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#1874]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The alert box has too much padding for mobile on small screens and makes the content too hard to read.

## What I expected to happen

It should have less padding, and the `display: table;` should only be applied on larger screens to save more space. 

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. View alert sign https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction
2. Open devtools and resize viewport to 320px

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

<img width="484" alt="Screenshot 2023-06-26 at 3 46 53 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/6927364e-b929-4136-87f0-4229cda7138a">

**Comment by josephrlee** [comment]
Here's the minor PR I created for this issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1874

**Comment by humancompanion-usds** [comment]
@josephrlee - Can this Alert instance not be replaced by an Alert web component?

**Comment by jamigibbs** [comment]
> @josephrlee - Can this Alert instance not be replaced by an Alert web component?

Here is the link to the web component for reference: https://design.va.gov/storybook/?path=/docs/components-va-alert--default

Does this also have the same issue?

**Comment by josephrlee** [comment]
@humancompanion-usds, and @jamigibbs , yes, I think it can, but there's a decent amount of functionality attached to it that the FE folks on my team would have to tackle.

**Comment by humancompanion-usds** [comment]
The right answer here is to have the FE folks replace the code with the web-component. We rely on teams to use the System.
