### ISSUE TITLE
Accordion contents has `tab-index="0"`

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#1875]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

[Recently we caught an issue where accordion contents were unexpectedly taking a tab stop](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60176). Upon exploring further, [we were able to track the change](https://github.com/department-of-veterans-affairs/component-library/commit/6a3a1ad3233d09596333e5618713c3f084962e80#diff-1ec0d38aede412478c91b6de922244434a58053f0991356a4f5b6cd06d5a6cdf) which was recently made within the design system.

We hypothesize this may have been done in good intention, [as it's a commonly experienced mistake.](https://www.a11yproject.com/posts/how-to-use-the-tabindex-attribute/)

> There is a myth that applying tabindex="0" to non-interactive elements (paragraphs, headings, lists, etc.) helps “improve” accessibility by providing a way for a person who uses a screen reader to focus on all the content present in a webpage or web app. Unfortunately, this well-intentioned idea actually does not create a good assistive technology experience.

## What I expected to happen

Non-interactive contents should _not_ take a tab stop.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. On storybooks, open the accordion
2. Use the tab key
3. Confirm that the contents take focus

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

This is a major accessibility issue that effects all of VA.gov. We strongly recommend prioritizing this fix ASAP.

### Details
In the future, it may be helpful to hire an explicit DST accessibility specialist to assist in future reviews and audit existing components.

Tagging @jamigibbs for awareness! 🙇

**Comment by joshkimux** [comment]
@Andrew565 thank you for linking this! Was any other information provided on the details behind this? It is well documented accessibility best practice to not add a tab stop for non-interactive elements as:
- screen reader and keyboard users will still be able to access those contents by either
  - navigating line by line (low vision/non-sighted screen reader users)
  - looking at the contents (sighted keyboard users)
- adding a tab stop implies that a user can interact with it
  - as the contents of the accordion are not interactive, it creates a false affordance 

[Webaim's documentation on this](https://webaim.org/techniques/keyboard/tabindex)
> A value of 0 indicates that the element should be placed in the default navigation order. This allows elements that are not natively focusable (such as <div>, <span>, <p>, and <a> with no href) to receive keyboard focus. Links and form controls are best for almost all interactive elements, but tabindex="0" allows other elements to be focusable and thus potentially able to trigger interaction.

As this is not an interactive element (it's content), it should not be receiving a tab-index="0"

**Comment by Andrew565** [comment]
@humancompanion-usds I'm inclined to agree with Josh's assessment here, does it make sense to you as well?

**Comment by joshkimux** [comment]
Hi @humancompanion-usds , I've reached out to Mark and the a11y specialists on secure messaging ❤️ 
I'll follow up in a bit.

**Comment by Andrew565** [comment]
PR up.
