### ISSUE TITLE
Add no wrap definition

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#188]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Telephone

Having a telephone number wrap to the next line makes it harder to read. Making it not wrap would improve readability.

## Do you have a suggestion for a new component or utility?

I am suggesting a new utility definition is added that allows a block of content to not be wrapped

```css
.no-wrap {
  white-space: nowrap;
}
```

Within the foundation style, there are multiple instances of the [`nowrap` value being used](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/search?q=white-space%3A+nowrap&unscoped_q=white-space%3A+nowrap).

- Pagination links
- Icon links
- Modal buttons
- Exit icon (mixin)
- Login container

Within the `vets-website` repo, this property has been added to at least a dozen custom stylesheets. Not all are related to telephone numbers.

**Comment by caw310** [comment]
@Mottie Is this still an issue?

**Comment by Mottie** [comment]
Yes, but it's a minor one. In the apps we own, if we need this definition, we add it to our app css. I think it would be a good addition to the core though.

**Comment by k80bowman** [comment]
Since we are in the process of building out a new CSS library, I don't want to add this to our current library right now. But I have made a note in a ticket about what all we want to include in the new library about including this. We also have a new telephone component which does not have this CSS in it currently, so I can apply it there as well.
