### ISSUE TITLE
Continue/Back mobile button pair incorrectly ordered in DOM

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/vets-design-system-documentation#1884]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

[Link to original comment in a separate ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1820#issuecomment-1584686482)

When Continue/Back buttons are stacked for small screens (i.e. mobile) the visual presentation is mismatched from what is in the DOM. In the DOM "Back" is first, followed by "Continue" but visually this is swapped. This can cause confusion for visual users who are enhancing their experience with assistive technologies (magnifiers, screen readers, etc.) because what the visual tab order order is not matching the reading order.

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106678594/60e6d1f9-8e72-40ae-bc7e-b609bfb13696)

## What I expected to happen

The order in the DOM should match the visual order of elements on the page

## Reproducing
- Formation version: small screen format, button pair stacking positioning
- Device: Smaller screens
- Browser: Any browser

Steps to reproduce:

1. View the button pair on small screen so that it stacks
2. Using the keyboard, tab through the pair
3. Notice that the tab order goes to the Back button first then back up tot he Continue button

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
> This can cause confusion for visual users who are enhancing their experience with assistive technologies (magnifiers, screen readers, etc.) because what the visual tab order order is not matching the reading order.

@laflannery, @briandeconinck, @joshkimux, @davidakennedy - USWDS has the Back button over the Continue button at mobile.   

![Screenshot 2023-06-30 at 3 18 24 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/d7d7419f-ea70-47ad-9b2c-918ff2809ac2)

I don't love making the secondary action first AND I'm still working towards making back not a button and not in this location. However, it seems like you all are essentially telling us Back must be first in a mobile viewport. Is that accurate? 

If that's the case we'll follow what USWDS does. Thus do you also have any sentiments on the button widths beyond the 480px breakpoint? USWDS does not follow the wider widths we use in our form flows.

**Comment by laflannery** [comment]
I think we should follow the USWDS - I think the larger set widths tend to not be as flexible

**Comment by caw310** [comment]
This will carry over into sprint 36.
