### ISSUE TITLE
Button pair - Additional features needed [On HOLD]

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/vets-design-system-documentation#1885]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

While attempting to implement the button pair web component in the forms library, I encountered a couple of issues that require additional features to function properly. The main two issues are the following:

1. Support for `onMouseDown`

We use `onMouseDown` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/ProgressButton.jsx#L44) to stop certain blur/validation events from firing _before_ the actual click action if fired. For our progress buttons, the click action changes routes. This primarily applies to our "Back" button. More information can be found in this pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/20048

2. No alternative text, such as "Submit application"

On the review page of any given form, we switch the "Continue" button text and functionality. The text becomes "Submit application". We will need the button pair web component to either support a new option that makes the text "Back" and "Submit application" or the ability to pass in any custom text.

![image](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/e8e5e7dd-6af8-4a66-a8aa-252443ba2956)

We also pass a `type` of "submit" to the current button class we are using, although I have no idea exactly what this does or if its support is needed in the button pair web component. See [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/ProgressButton.jsx#L37) for the specific line of code that passes this property.

One more related behavior that wasn't as expected was discovered while experimenting with the button web component. In `FormNavButtons.jsx` where we implement our buttons for form navigation, I attempted to drop in the individual button web components, but encountered unexpected behavior with the buttons not expanding to fill the columns. 

![image](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/9b4c151f-5e27-484b-9175-3f1d223f9707)

That is what the button web component rendered when using this code:

```
<div className="small-6 medium-5 columns">
  <VaButton />
</div>
```

I am paraphrasing the code a bit, but essentially the code remained the same as [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/FormNavButtons.jsx#L15-L35) except instead of `ProgressButton` being used `VaButton` was used in its place. Because this is not related to our issues with button pair, I don't expect this part of the ticket to be as high of a priority.

## What I expected to happen

Most of this is explained above in "What happened" and below in "Reproducing".

## Reproducing
To observe the intended behaviors above, you can use the [mock form](https://staging.va.gov/mock-form/) on VA.gov. 

Steps to reproduce proper `onMouseDown` behavior:

1. Navigate to "Step 2 of 8: Chapter Title: Applicant Information (Basic Form elements)" using the "Continue" nav button
2. Trigger a validation error by remove one of the required fields on the page
3. Click the "Back" button
4. You should have successfully returned to the previous page

Steps to see the "Submit application" button:

1. Navigate to "Step 8 of 8: Review application" using the "Continue" nav button
2. Observe the "Submit application" button paired with the "Back" button at the bottom of the form window

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
@ndsprinkle - I'm fine with all this but want to push back a bit on onMouseDown because, the [a11y specialists would like us to move away from triggering errors onBlur](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1130). If we were to do that, would we then no longer need the onMouseDown support? Can you explain to me why we do validation onBlur instead of after the user submits the form? Don't we have to do the same error validation on the back-end anyway?

**Comment by ndsprinkle** [comment]
@humancompanion-usds I'll try to answer your questions the best I can, but honestly some of this stuff is still confusing to me. There were major decisions made years ago at the creation of the forms library (before my time) about when/where to fire validation and a bunch of code has been piled on top of that architecture over the years.

The forms library tracks if a field has been "touched". A field is marked as "touched" _after_ it's onBlur function is fired. Following the trail of tickets in the issue you linked, it seems like one of the concerns is that we fire the validation even when nothing is typed in the field. This is definitely true because all that needs to happen to be marked as "touched" is for the onBlur function to fire, which fires in any situation where the field goes from having focus to losing focus. It doesn't matter what is typed in the field.

Anyway, after a field is "touched", it will fire its validation function every time a character is typed into its field. onBlur is no longer relevant to its validation.

There is one other way to mark a field as "touched". When a user hits one of the progress buttons (continue or submit), it will actually mark all the fields as "touched" by firing their onBlur functions. It's a necessary side effect of how all this is implemented because we need to fire validation before the user continues to the next page. The easiest (or hackiest) way was to just make all the fields fire their onBlur functions. 

As for my assumptions about why we do all this onBlur stuff, I assume this was done like this so that a user could get feedback on validation without needing to hit the continue button every time. I also assume that this strange combination of onBlur and "touched" was done so that you wouldn't get annoying, immediate validation until you try to move away from the field. Now, as for why onBlur is used to trigger "touched" instead of just always waiting until the user hits the continue button, I have no idea. Maybe it was meant to be a middle ground between validating all the time and not validating until all fields are filled out? Because to me it would make sense, like you say, to wait until a user hits continue/submit, then alert them to validation issues on fields, then those fields can provide immediate validation on character press. 

With all that being said, the way onMouseDown is being used is another side effect solution thing. If a form page detects validation errors on that page, obviously hitting the continue/submit button won't continue/submit. It will just scroll to the topmost error. But when a user hits the back button, we don't want to stop them from going back (I have no idea if this is still a relevant practice, [it was changed from the original behavior of blocking the user from going back about 1.5 years ago](https://github.com/department-of-veterans-affairs/vets-website/pull/20048)). Because all the onBlur and validation stuff happens onClick, B.J. added a function for onMouseDown so that he could do something _before_ onClick happens. In this case, he's essentially blocking (and resetting, maybe on accident) onBlur for all the fields on the page when you hit the back button.

So, that's where the request for onMouseDown comes from. My request for that mainly came from a place of just wanting to be able to "drop in" the button pair component.

To answer the original question, if we did an overhaul of how onBlur is used and how validation errors are triggered, then yes we could probably get away from needing onMouseDown support.

**Comment by humancompanion-usds** [comment]
@ndsprinkle - That's a very helpful summary. Much appreciated. [Let's move our discussion to the issue on changing onBlur](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1130). I have questions.

**Comment by humancompanion-usds** [comment]
We're going to hold on this request until we've tested moving back button a link in a form. We're going to also going to determine if we can solve #1130. If we can do both of those things then we may not need to make the changes requested here.

**Comment by ndsprinkle** [comment]
@humancompanion-usds Yeah, can definitely close this.
