### ISSUE TITLE
Sketch component - v3 Memorable Date does not resize to fit smaller artboards

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#1896]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When placing the v3 memorable date component (from the current DO NOT USE MVP library) into a sketch file and resizing it to fit mobile artboard sizes, not all of the fields resize properly onto the artboard

## What I expected to happen

I expected to be able to resize the component to fit the artboard

## Reproducing
Sketch, desktop
DO NOT USE - USDS v3 Component library in Sketch

Steps to reproduce:

1. Place the memorable date component
2. Resize the component

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints (however - whenever you update the component, my templates should just slurp up the changes.
- [ ] This bug is not blocking any work
- [ ] Other

### Details

Here is a video of the issue:

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/c569f7bf-5caa-4dbb-a3f6-437a4cc4f820

**Comment by babsdenney** [comment]
@humancompanion-usds @LillyBoot This is complete and ready for review. I added a new symbol that has the mobile size for the memorable date. 
- [V3 Memorable date](https://www.sketch.com/s/15dbd73b-3afd-48ee-a91b-8dad928e02f3/a/r9rp4OK)
- [MVP Memorable date](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/a/nQDorjW)

**Comment by humancompanion-usds** [comment]
Looks good. My only complaint is that "Default v2" is not a great title. Perhaps "Month input text" or something that describes the difference. I suppose "Previous default" would also be accurate. 

Also, just a reminder to assign issues to me when you want my review on them (and please don't close them before I get a chance to look at them unless Lilly has already reviewed and that is captured in the issue).
