### ISSUE TITLE
Button group - Design

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1906]
## Description
Update design for button group Sketch artifacts for the MVP and v3 libraries. See the example below for details.

## Details
[Button group Sketch example](https://www.sketch.com/s/8631d09a-7b11-461a-ad01-40153741106e/a/Ryawb4j)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by LillyBoot** [comment]
@babsdenney this is ready for review 

[Button Group](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/F2B3C09A-004C-4A71-BD77-E0A2C1EF2BAA/canvas)

**Comment by babsdenney** [comment]
@LillyBoot  So much better! This is great, thank you!
