### ISSUE TITLE
Select - Design update

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1908]
## Description
Update design for select Sketch artifacts for MVP and v3 libraries. See the example link below for details.

## Details
[Select Sketch example](https://www.sketch.com/s/8631d09a-7b11-461a-ad01-40153741106e/a/pYQ0opk)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by babsdenney** [comment]
@LillyBoot This is ready for review. 

[MVP Select](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/a/y9Qkdmq)

**Comment by LillyBoot** [comment]
@babsdenney Looks great to me!
