### ISSUE TITLE
Checkbox and Radio - Design update

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1909]
## Description
Update design for checkbox and radio Sketch artifacts for the v3 and MVP libraries. See the example link below for details.

## Details
[Radio Sketch example](https://www.sketch.com/s/8631d09a-7b11-461a-ad01-40153741106e/a/VEkyYma)
[Checkbox Sketch example](https://www.sketch.com/s/8631d09a-7b11-461a-ad01-40153741106e/a/w5AVjpV)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by LillyBoot** [comment]
@babsdenney this is ready for review 

[Radio Button](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/AF7CD21C-2DF3-4CA4-B678-473A929B9615/canvas)
[Checkbox](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/AB01082F-B8AE-4D0A-A3FD-5B8EDEB578CD/canvas)

**Comment by babsdenney** [comment]
@LillyBoot This is so much better! Looks great! I added a "required" variation to the checkbox option. 
[Required checkbox group](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/a/r9rV8eE)
