### ISSUE TITLE
File input - Design update

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1910]
## Description
Update design for file-input Sketch artifacts for the v3 and MVP libraries. See the example below for details.

## Details
[File input Sketch example](https://www.sketch.com/s/8631d09a-7b11-461a-ad01-40153741106e/a/K0ZoLbK)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by LillyBoot** [comment]
@humancompanion-usds @babsdenney this is ready for review
[Sketch file](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols?g=Form%252Ffile%2520input)

**Comment by babsdenney** [comment]
@LillyBoot The required symbol isn't moving over when the text is changed. Everything else looks great!

**Comment by LillyBoot** [comment]
@babsdenney I fixed the issue so it should work now

**Comment by babsdenney** [comment]
@LillyBoot This looks great!
