### ISSUE TITLE
Modal - Design update

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#1911]
## Description
Update design for modal Sketch artifacts for the MVP and v3 libraries. See the example below for details.

## Details
[Modal sketch example](https://www.sketch.com/s/8631d09a-7b11-461a-ad01-40153741106e/a/qbQl0rd)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by babsdenney** [comment]
@LillyBoot This is ready for review. 

- [Desktop](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/a/aMaE5lA)
- [Mobile](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/a/mPKg1x7)

**Comment by LillyBoot** [comment]
@babsdenney the default states look great! However on my end, the text is still overlapping itself and the buttons for all the alert states except the desktop large ![Screen Shot 2023-08-08 at 5.19.51 PM.png](https://images.zenhubusercontent.com/63d7f10a208bb87a62f4e744/58a38cc0-d10c-4029-8f1f-6624fd3ad1f2)

**Comment by babsdenney** [comment]
Great catch! Thank you for finding that. @LillyBoot this is ready for review again.

**Comment by LillyBoot** [comment]
@babsdenney looks great!
