### ISSUE TITLE
Feature Request: Reusable Form Wizard

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/vets-design-system-documentation#192]
# Feature Request

As a frontend developer, I need a reusable form wizard component so I can implement multi-choice user workflows in a quick and standards-compliant way.

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Goals
_What outcome(s) do we want to see?_ 
A well defined and documented standard approach to frontend multi-choice forms with conditional logic.

## Use Case

A user on va.gov should should be able to navigate a series of questions, with the workflow of those questions and a final result page defined by developers.

### Multi-path workflow
Based on the answer to a previous question, different questions should be shown. For example, based on their answer to an initial question "Are you a VA employee?" one of the later questions should be different, while all other questions should remain the same.

### Styling Customization
Our application is only intended for mobile usage, and needs to be operable when the user is standing, walking, or holding things in another hand. Additionally the results must be visible to VA staff from 6 ft away. Therefore we need to make questions and input areas very clear and large, and need the final results to be readable at a distance.

## Is this feature request relating to an existing component or utility? Please describe.
- Component/utility name:
The closest existing component is: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/wizard/index.js

## Do you have a suggestion for a new component or utility?

Alternatively use a 3rd party library such as https://formio.github.io/formio.js/

### Background

There is a wizard pattern documented on https://design.va.gov/patterns/wizards which points to multiple code examples with various implementations. One of these examples is [How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)([source code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/wizard/wizard-entry.js)) which uses a `<Wizard>` [component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/wizard/index.js). This component was created for a particular use case, and may or may not be suitable for reuse. It is not published as a [Formation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design) component.

A frontend engineering team was tasked with creating a multi-path form for the [Coronovirus Screener](https://www.va.gov/covid19screen/) app ([source code](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/coronavirus-screener)). Because of the urgent need for deployment of the app and lack of clarity around a standard approach, code may have been written which is redundant with other solutions.

### Possible Solutions

1. Document and publish the `<Wizard>` [component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/wizard/index.js) to Formation with enhancements if needed
2. Adapt the Coronovirus Screener [code](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/coronavirus-screener) to be reusable
3. Identify and document a 3rd party library as the standard for this use case

**Comment by jason-gcio** [comment]
Here is a draft prototype of what we are thinking the wizard might look like for us: https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/130194084/simulate/sitemap

**Comment by andaleliz** [comment]
@mchelen-gov here's one issue I documented with the [discharge upgrade form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6461).  It's been a while since I've looked at this but now that I'm revisiting, I believe this is the only a11y issue I found.

**Comment by mchelen-gov** [comment]
@andaleliz oh interesting! we ran into that exact same problem with our screener, and ended up disabling the smooth scroll. great example of how helpful it would be resolve these things in one reusable place 👍

**Comment by caw310** [comment]
Closing as the wizard has been deprecated and there is a new pattern in progress for one thing per page.
