### ISSUE TITLE
Change Step Indicator Mobile font size 

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#1922]
## Description

We need to change the font size of the step indicator mobile view. It currently is 22px, but needs to be 18px 

## Tasks
- [ ] Change font size in sketch 

## Acceptance Criteria
- [ ]Reviewed by PO

**Comment by humancompanion-usds** [comment]
Ugh. This one is brutal. Every part of this component needs to be adjusted. This one will take a little bit.

**Comment by humancompanion-usds** [comment]
Done. I will file a follow-up issue to have the font-size corrected in the built web-component.
