### ISSUE TITLE
va-telephone - Not displaying 1-800 numbers as expected

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/vets-design-system-documentation#1932]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When prepending a 1 (US/Canada country-dialcode) for the contact property (e.g., `contact="18008271000"`), all dashes disappeared from the displayed number ("1800827100").

This is different from `contact="8008271000",` which displayed "800-827-1000" as expected.

## What I expected to happen

Just like when using `contact="8008271000"`, dashes should still be displayed:
"1-800-827-1000" (or "+1-800-827-1000" if required by any Sitewide-Content policy)

## Reproducing

- Formation version: 7.0.8
- Device: Macbook
- Browser: Chrome, Firefox, Safari

### Steps to reproduce:

Just add an instance of `<va-telephone contact="18008271000" />` on any existing app- or static-page in vets-website.

NOTE: Right now, I also have a [commented-out `<va-telephone/>` instance](https://github.com/department-of-veterans-affairs/vets-website/blob/85f275c824891c5f5493eb3777c750a2d3fcbc8e/src/applications/simple-forms/21-0845/containers/IntroductionPage.jsx#L62) in my feature-branch, which you can pull to replicate by uncommenting.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
According to DS guidance for telephone: 
https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers
https://design.va.gov/storybook/?path=/docs/components-va-telephone--international
> Use +1 only when the information is specifically addressing Veterans or people who are living outside the U.S.: +1-201-123-1234.

**Comment by humancompanion-usds** [comment]
@tlei123 - This seems like perhaps it is not a bug but perhaps a lack of being clear in the guidance that using 1 as a country code isn't necessary nor desired. Do you agree? If so, I can update the documentation.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1932?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
I don't think this is an issue with the component. 

@tlei123 Are you able to confirm what @humancompanion-usds asked about in his comment above? https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1932#issuecomment-1659168489 

If it's required to display the `1` in a number, you would just use the telephone component like this: 

```
  <va-telephone
    contact="8773459876"
    international
  />
```

![Screenshot 2023-11-14 at 10 59 25 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/d983ed01-1bfc-4d3f-8a42-e2999bc1a59b)


https://design.va.gov/storybook/?path=/docs/components-va-telephone--international

**Comment by tlei123** [comment]
> @tlei123 - This seems like perhaps it is not a bug but perhaps a lack of being clear in the guidance that using 1 as a country code isn't necessary nor desired. Do you agree? If so, I can update the documentation.

Sorry, for late reply, @humancompanion-usds !  **It's not a bug then**[^1].  You're absolutely right; the usage guidance just needs some clarification about avoiding the "1" in front.

[^1]: I was just trying to follow the mockup at the time, which [unlike other mockups I've seen] happened to include the "1".

**Comment by tlei123** [comment]
^ cc @jamigibbs [we just need to update the docs; no bugfix needed]
