### ISSUE TITLE
Additional info component (not working with voice command softwares)

### ISSUE THREAD

**Issue by BobbyBaileyRB** [department-of-veterans-affairs/vets-design-system-documentation#1933]
# Bug Report

- [Y] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I was testing Medical Records with voice software - I noticed the Additional info component would not open using Voice Commands and Dragon software when saying "Click (Text name of the additional info component)".

However, if I use Voice Command's Grid System, it does open. I speak "show grid". It gives a set number - I say 107 then a new list appears ranging 1-20. If the x number is on the component I will speak "Click 13" and then the drop-down does open.
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/102695954/609f63cf-dd1b-4f11-ad9b-8f3661e30ccb)

## What I expected to happen

When I say Click "components text name" it should activate the component such as opening up the drop-down to display the additional information content.

## Reproducing
- Device: Macbook and Windows
- Browser: Any browser

Steps to reproduce:

1. Turn on voice software
2. Navigate to the additional info component
3. Speak "Click Additional Info"

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [Y] Other

### Details

This bug is not blocking any work but needs to be fixed for AT users.

**Comment by BobbyBaileyRB** [comment]
@briandeconinck would you like to give more feedback or explain problems you might've saw different while using Dragon?

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1933?planning-poker) with Zenhub @rsmithadhoc

**Comment by rsmithadhoc** [comment]
@BobbyBaileyRB Hi Bobby,

I wasn't able to recreate this on my end, with the default component, "Click additional information" opens and closes the component without issue. For the example in the screenshot, it was not as consistent when reading the full name, "Click What to know about lab and test results", but Voice Control showed a message to say "Try 'Click What to know about'" and that seemed to work more consistently. I'm thinking that maybe longer text is harder for Voice Control to handle?

Can you let me know if you get similar results? Thanks!

**Comment by BobbyBaileyRB** [comment]
Hey there @rsmithadhoc - it appears to be functioning as intended now. I think the issue may have been on the MHV side with VA, but everything seems to be running smoothly now. Thank you for looking into this.
