### ISSUE TITLE
Feature enhancement for va-radio-option

### ISSUE THREAD

**Issue by imelda-guzman** [department-of-veterans-affairs/vets-design-system-documentation#1937]
Hello,

I would like to request a feature enhancement for the va-radio-option.  [By default the va-radio-option sets a width of auto and max-width of 320px to the va-radio-option](https://github.com/department-of-veterans-affairs/component-library/pull/726).

I would like to request a width property be added to the component so a user could set a desired width and override the default width set by the component.  

We are currently using the va-radio component and would like to extend the width of the options to align better with the UI.  See attached screenshot.

**Default option width**
![addModify-modal-redesign](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/748095/dbbe675d-9136-426b-b925-b8f9b2e93819)

**Desired results**
Adding the width property would allow us to align the options to the rest of the elements.

![feature-request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/748095/532a182f-1b68-42c5-9778-3ecbfdf18c32)

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
