### ISSUE TITLE
Sentry issue with va-loading-indicator null node.tagname

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1952]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

According to [this Sentry issue](http://sentry.vfs.va.gov/organizations/vsp/issues/103940/?project=4&query=is%3Aunresolved+tolowercase&statsPeriod=14d) there is a problem with va-loading-indicator when it is checking mutations to see if it has been unloaded. The theory is that when the code gets to [this line](https://github.com/department-of-veterans-affairs/component-library/blob/e2d2db654ee6ce99c44ab7596e3f9997b5d698ed/packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx#L76) `node` or `node.tagName` are either null or undefined and causing an error to pop.

## What I expected to happen

There should not be an error here.

## Reproducing
- Formation version: Current
- Device: Desktop
- Browser: Any

Steps to reproduce:

1. Unknown at this time.

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

### Details

Given the theory of a null or undefined `node` at that line of code, the suggested 'fix' for this bug is to check for the presence of a `node` before evaluating its `tagName` property.

**Comment by caw310** [comment]
removed the sprint dates as this was not planned work for sprint 32
