### ISSUE TITLE
CSS Library: Generate token file for Sketch

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1959]
## Description

Reference discovery ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1837

This ticket is to confirm that we can import CSS Library tokens into Sketch. We should try first an existing [Sketch plugin](https://www.sketch.com/extensions/plugins/) but the [CMS Design system built their own Sketch plugin](https://github.com/CMSgov/design-system/blob/main/packages/design-system-tokens/sketch/cmsds-token-importer/README.md) that we can reference in case we need to build a custom one as well.

## Tasks
- [ ] We can import tokens that are generated by the CSS Library into Sketch

## Acceptance Criteria
- [ ] CSS Library tokens have been imported into Sketch

**Comment by humancompanion-usds** [comment]
We're moving off of Sketch and will no longer use Sketch as of February 2024. Thus closing this as will not fix.
