### ISSUE TITLE
Discrepancy between CSS and Sketch for unordered list items

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#1964]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

- The unordered list item in the VA.gov Pattern Library for Sketch renders the bullets as a circle, but the [design system docs](https://design.va.gov/foundation/typography#lists) and the va.gov CSS (which I assume is part of the design system) render them as a square.   
- The distance between the list decoration and the text is also different between the two sources.

## What I expected to happen

List bullet styles in Sketch will match what is on the website and the design system documentation

## Reproducing

Steps to reproduce:

1. Apply the unordered list style to a text element in Sketch (screenshot below)
<img width="490" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/55992116/5f4fec2e-1904-4f52-88ba-44f4efbda24a">

2. Inspect the unordered list style on a page on va.gov, such as [Check Claim or Appeal status](https://www.va.gov/claim-or-appeal-status/) (screenshot below)
<img width="1268" alt="Screenshot 2023-08-01 at 11 29 26 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/55992116/fd4a9800-9564-4084-a8da-6641039176b1">

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
We handmade an unordered list in the Typography section, but there is no way to create a text style with a stylized bullet in Sketch:

![Screenshot 2023-10-11 at 5 18 49 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/811900a9-17b9-436f-8b43-a40d51cf65a7)

I'm afraid this is the best we can do.
