### ISSUE TITLE
Help users to... Keep a record of submitted information (Print styling for confirmation page)

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/vets-design-system-documentation#197]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

No.

## Do you have a suggestion for a new component or utility?
Right now, for the confirmation page on forms, we have a feature designed/coded that adds a "print this page" button and a custom css style.  You can see how it works here: https://dsva.slack.com/archives/CMJ2V70UV/p1590174244210900?thread_ts=1590157417.209200&cid=CMJ2V70UV

It was coded by Justin on the Caregiver team. (@LinnJS) 

It would be great to get this documented in our pattern library, sketch files, and then potentially think about some kind of global change so each team isn't having to do it themselves.

**Comment by amyknox** [comment]
For awareness, the Booz Allen team also added our own "print this page" element (& styling) to education forms: 22-1995 and 22-10203

**Comment by sshein** [comment]
@amyknox can we see a screencap of what you all did?

**Comment by amyknox** [comment]
22-10203: STEM Application confirmation & printer-friendly

![image](https://user-images.githubusercontent.com/41081945/101957393-54171500-3bcf-11eb-906d-33025f47dd8f.png)

![image](https://user-images.githubusercontent.com/41081945/101957384-50838e00-3bcf-11eb-8ae5-0d651fc46a9a.png)

22-1995: Change your benefits confirmation & printer-friendly
![image](https://user-images.githubusercontent.com/41081945/101957437-6f822000-3bcf-11eb-9bc3-d9a4fb1e5748.png)

![image](https://user-images.githubusercontent.com/41081945/101957449-7446d400-3bcf-11eb-89c6-ab663cb4080b.png)

**Comment by sshein** [comment]
relevant slack thread asking about patterns for notifications on print styles https://dsva.slack.com/archives/C0NGDDXME/p1607706495398400

**Comment by caw310** [comment]
Discussed during the 12/18 DC meeting. Follow up items: 

- Create ticket for: Normalize of the behaviors of confirmation page Define content guidelines for success page (Carol)
- Create ticket for: Normalize print style for for print this page (Carol

**Comment by KevinMHoffmanUSDS** [comment]
@amyknox Good afternoon, and happy holidays! We discussed in our design system council meeting today. We are going to normalize the approach to this page so that it's a little more consistent across our form applications. In the meantime, the recommendation is that you use the variation (for success page design and print styles) that's live on the caregiver page ([10-10CG](https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)), depending on where your team is in it's process.

**Comment by amyknox** [comment]
@KevinMHoffmanUSDS - @caw310 I'm not able to access success page design and print styles for [10-10CG](https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction) (on staging).  Looked around in GitHub and can't track them down their either.  Do you have a github link or visual you could share with me?

**Comment by humancompanion-usds** [comment]
@taylojill - The task here would be to gather how print styling is handled for the 10-10CG form on the confirmation page in staging (just add swap www for staging in the URLs provided in previous comments).

**Comment by taylojill** [comment]
Hi @humancompanion-usds Here are the screen grabs for the 10-10CG form (staging). What are the next steps? Thanks!
cc @GnatalieH 

![Caregiver Application For Benefits Veterans Affairs](https://user-images.githubusercontent.com/97645218/211880784-b24e3e5e-df72-4fbf-a70e-37f339e3b4d9.png)


![Print version](https://user-images.githubusercontent.com/97645218/211882887-69f7e8e3-7f72-4eb2-b6d2-c865f372c0b9.png)

**Comment by humancompanion-usds** [comment]
The next step is to write a new pattern named "Help users to... Keep a record of submitted information". The USWDS just published their version: https://designsystem.digital.gov/patterns/complete-a-complex-form/keep-a-record/ Thus we could point to their pattern and then just document what is different about ours. The goals here are to:

1. Show a definitive example of how and where to offer printing on the confirmation page.
2. Show a definitive example of what the print styling looks like.

**Comment by taylojill** [comment]
Thanks @humancompanion-usds Working on it now.
