### ISSUE TITLE
Memorable date must not reveal regex to user when using pattern prop

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#1974]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Error message for memorable date reveals regex when that prop is used.

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/2bc8fc5d-8e34-487c-827d-dbb459c1325c)

## What I expected to happen

I expect us to return a plain language error to the user. If we need one from CAIA, they should have it for us or be able to quickly generate one.

## Reproducing
Steps to reproduce:

1. Enter an invalid year in the year field
2. See error that contains regex

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
This is blocking us from shipping form 21P-0847

**Comment by jamigibbs** [comment]
A PR was submitted to address this in the Forms Library. We need to check if there is something in our validation too that should be updated as well to avoid this: https://github.com/department-of-veterans-affairs/vets-website/pull/25091

**Comment by ndsprinkle** [comment]
@nickjg231 and I synced earlier to discuss the underlying issue and confirmed that this is **not** a design system/web component issue, but rather an issue with the validation done on the particular implementation. I have addressed this issue here: https://github.com/department-of-veterans-affairs/vets-website/pull/25125

I have also reverted the email definition changes in that pull request, so that issue should also be resolved. 

I think this issue is good to close now.

**Comment by humancompanion-usds** [comment]
@ndsprinkle and I talked about this earlier as well. I understand now that a string is passed to the web-components and there is no default stored in the web-component itself. I will file new issues for us to move Forms Library to using a JSON or YAML strings file so that we can standardize and translate our error messages.

**Comment by longmd** [comment]
@ndsprinkle , just coming across this revert and had a question/concern. Would it be okay to leave the `format` key in the error message declaration and add `pattern` with the same message? Without the pattern declaration, the email fields are revealing the regex in the error message. 

cc: @hdjustice

**Comment by ndsprinkle** [comment]
@longmd Yeah that sounds like it would work. Which form is having an issue with this? It sounds like it might be an issue with the `schema` not using the default email definition I linked above, not the actual UI, because the `schema` should have that `format` property when using email

**Comment by longmd** [comment]
@ndsprinkle , it is the 10-10EZ, and yes, just looking at the `schema`, it is not the default definition. I'm unsure on the history of why this may be, but if you're okay with adding the `pattern` key to that UI definition, I will do that as a solution.
