### ISSUE TITLE
Add new design and UX guidance for sitewide downtime banner in the design system

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#198]
## Add new design and UX guidance for sitewide downtime banner in the design system

_This is related to the recent UX, design, and content changes for sitewide downtime banners._ 

## This update is for:

- [ ] Content styleguide
- [x] Component
- [x] Pattern
- [ ] Utility
- [ ] Other

## What is the nature of this update?

- [x] When to use
- [ ] When to use something else
- [x] Code snippet
- [ ] Accessibility
- [ ] Research insight
- [x] General documentation - design, ux behavior/pattern

## Additional Context

**Reference tickets:**
[#9536 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9536)
[#9223 ]( https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9223)

[ ] Add desktop design and specs in the design system ~@rtwell~ TBD
[ ] Add mobile design and specs in the design system ~@rtwell~ TBD
[ ] Add UX and governance guidance content ~@peggygannon~ TBD
[ ] Link updated downtime messages in the dictionary to the new component examples. ~@peggygannon~ TBD

**UX and governance guidance for component write-up in design system:** 

- Used when all (or most) unauth and auth apps, tools, and sign in experiences across the entire site are affected (EX: vets-api).
- Ability to publish: DEPO.
- Displays sitewide, including VAMC products.
- 2 states: In advance of downtime; and during downtime.
- Yellow for advance; red for during.
- Can be dismissed per cookie on default (configurable per cookie or per session)
- In-advance messaging displays by default 12 hours in advance, but can be configured to display earlier for extreme cases (such as a 24 hour outage). 
- During message automatically removed at end time. 
- Text is template/standardized, with custom dates and times. 300 character count limit including spaces. 
- Display hierarchy when there are multiple banners is a) Emergency banner, then b) Sitewide downtime banner,

**Comment by jenniferlee-dsva** [comment]
Updated ticket ^ with design system issue template and @KevinMHoffmanUSDS for FYSA. (I created this ticket before reading your deck w/link to new issue template.)

**Comment by KevinMHoffmanUSDS** [comment]
Thanks, @jenniferlee-dsva! Ryan and I will begin creating this documentation. @CrystabelReiter - let's discuss getting this into Sketch as well at the next Design System Council meeting.

**Comment by KevinMHoffmanUSDS** [comment]
Further discussion https://dsva.slack.com/archives/C7NJWUA8K/p1606157527023500

**Comment by peggygannon** [comment]
hello, @jenniferlee-dsva @rtwell @KevinMHoffmanUSDS do you still need to update the content portion of this request? I see it now says TBD  next to the UX and governance guidance content checkbox above.. 

Please advise. thx

**Comment by rtwell** [comment]
Because the Before and During Maintenance banners are rigid in their content, I think it would help to reflect this content structure in the components on storybook.

My suggestion (and i'm open to feedback):

## Before banner

**Upcoming site maintenance**
We’ll be doing some work on VA.gov. The maintenance will last x hour. During that time, you won’t be able to sign in or use tools.
**Date:** Day, Date, Year
**Start/End time:** 0:00 a.m. to 0:00 a.m. ET

## During banner

**Site maintenance**
We’re working on VA.gov right now. If you have trouble signing in or using tools, check back after we’re finished. Thank you for your patience.
**Date:** Day, Date, Year
**Start/End time:** 0:00 a.m. to 00:00 a.m. ET

**Comment by caw310** [comment]
@bkjohnson @cvalarida , would you be able to make the changes in SB?

**Comment by bkjohnson** [comment]
Yes, I can make these changes. However, in the component library these banners are _not_ rigid in that content.

**Comment by bkjohnson** [comment]
Even though [our content guidelines](https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones) state that `a.m.` and `p.m.` should include periods, the third-party library we are using right now (`moment`) does not support that as a formatting option. This makes it infeasible to do right now, and is another reason why we should move away from moment.

**Comment by bkjohnson** [comment]
In that PR above my previous comment, I ended up solving the `a.m.`/`p.m.` thing by switching away from `moment` in favor of `date-fns`
