### ISSUE TITLE
onblur field validation on mobile triggers when moving from field to field

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#1984]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
This is more of an issue for memorable date as it uses multiple fields, but could be an issue for forms utilizing multiple fields in general.

Field validation is triggered when moving from field to field on mobile. On desktop the validation does not fire if using the tab key. 

For VoiceOver users, this is particularly challenging, as they'll hear the error announced despite submitting correct information each time.

See: https://github-production-user-asset-6210df.s3.amazonaws.com/14154792/250154180-ec0ca763-af46-40e7-8548-42df542b5650.MP4

## What I expected to happen

Validation is read at the end of filling out a field/field segment

## Reproducing
- see referenced video

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
Split from: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1593

**Comment by joshkimux** [comment]
Kevin informed me that:
- iOS Safari users have access to the ^v (previous/next) buttons, which sends focus to the next form field without firing validation
- iOS Safari users also have access to the done button, which fires validation (should they use done to complete the field and then swipe right to access the next one)

An open question for a11y specialists and DST at large would be:
- Do iOS Safari/VoiceOver users expect validation upon tapping done within the context of a memorable date fieldset if they also have access to ^v (previous/next) buttons?
  - Creating multiple screen reader announcements in quick succession is generally an undesired experience, but would it be acceptable in this context?
- What is the status on validation at submit (vs validation at blur) at large within the DST?
  - We’ve had conversations on moving towards validation on submit, but it’s uncertain where we are in terms of progress.

**Comment by powellkerry** [comment]
@caw310 I am closing this. It appears to be working as expected, but we should re-visit some of the questions from @joshkimux with Ryan when he gets back.
