### ISSUE TITLE
VaNumberInput: prevent scrolling and changing value when input is focused

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/vets-design-system-documentation#1989]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
If you type into a `VaNumberInput` and leave it focused, then scroll within it to get to other inputs or CTAs below, the scrolling will change the number input.

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/19175324/cff53235-500f-44bf-a0a2-dfef805bd205

## What I expected to happen
Scrolling should not change any input.

## Reproducing
- Formation version: ? Not sure what this is
- Device: MBP
- Browser: Chrome 115

Steps to reproduce:
1. Go to https://staging.va.gov/health-care/income-limits
2. Select `Check current income limits`
3. Enter a zip code, then scroll with your mouse pointer inside the input

## Urgency
How urgent is this request? Please select the approriate (**typo here: appropriate**) option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other

This is an accessibility issue. @laflannery can provide more insights.

**Comment by laflannery** [comment]
From the accessibility side, the most problematic items would be:
- this type of input does not seem supported by Dragon and
- The change that happens is not announced so a users are probably not going to be aware that it happens and may accidently submit incorrect information or (realize that it's incorrect hopefully when they get to the review screen)

It was mentioned that this would most likely go into the next sprint but just let us know if that changes.

**Comment by jamigibbs** [comment]
Slack discussion for reference: https://dsva.slack.com/archives/C01DBGX4P45/p1691592189266979

**Comment by jamigibbs** [comment]
Possible solution (via Ryan Smith) - https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

> we recently moved away from `<input type="number">` to `<input type="text" inputmode="numeric" pattern="[0-9]*">` and published new [guidance on how to ask users for numbers](https://design-system.service.gov.uk/components/text-input/#numbers).
