### ISSUE TITLE
Check Readme in other repos for references to experimental design

### ISSUE THREAD

**Issue by emilywaggoner** [department-of-veterans-affairs/vets-design-system-documentation#199]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [x] Other

## What is the name

This update is for the [Contributing to Formation page](https://design.va.gov/documentation/contributing-to-formation) on design.va.gov.

## What is the nature of this update?

Let's update this page to reflect the new governance process, and also retire `Formation` from all parts of this page, including the URL.

### Potential new sections:

- Overview of the full process
- Updating an existing component
- Creating a new component
- Criteria the Design System Council uses to evaluate proposals
- What to do if you have a question
- FAQ
    - How long does this process take?
    - Who is on the design system council?

### Potential sections to retire:

- Scenarios

### To modify:
- Removing a component section

This will probably need a little bit of consensus gathering

Assigning this to myself, Kevin, and Crystabel for right now, and ultimately we should consult with Gretchen on all the edits and new content.

I volunteer myself to take a first pass at this update!

**Comment by mchelen-gov** [comment]
The READMEs in these codebases probably also need to be pointed to the the updated documentation: 
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools 
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/formation
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/formation-react

**Comment by humancompanion-usds** [comment]
The first README in Chelen's list has been updated (the other two did not mention nor link to the Design System) and points to the brand new: https://design.va.gov/about/developers/contributing
