### ISSUE TITLE
Memorable Date - Month text input too wide / select field width doesn't match design

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#2009]
# Description

- The month text field should be narrower to indicate that the field is only 2 digits and not the full month
- The date select is not wide enough on screen sizes larger than mobile

Designs: https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/a/nQDorjW

Expected:
![Screenshot 2023-08-16 at 3 09 18 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1776069/dc9798b2-cdbc-4bc4-b044-629edb3fef27)

Actual:

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1776069/64d06113-7fcb-4eb0-9343-bcfd1de74622)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by it-harrison** [comment]
Hi @babsdenney I'm not very familiar with Sketch - how do I get the size in pixels of the month select field on desktop?

**Comment by it-harrison** [comment]
@babsdenney I think I got it - 240px as specified by the `usa-form-group--month-select` class
