### ISSUE TITLE
Edit issue templates to reflect governance process

### ISSUE THREAD

**Issue by emilywaggoner** [department-of-veterans-affairs/vets-design-system-documentation#201]
Here is the [list of issue templates](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new/choose) for this repo.

We currently have 4 templates:
- Bug report
- Documentation request
- Feature request
- Support question

Make sure that the language and instructions in the templates reflect the governance model, and that each one provides clear guidance for what information and artifacts are needed on each one. 

Consider:
- Change the name of "Feature request"
- Consider removing "Support question" in favor of encouraging questions in Slack (?)

(Tagging the three of us on this with the idea that one of us can self-assign to work on as we have time)

**Comment by caw310** [comment]
Closing as this is old
