### ISSUE TITLE
Additional Info content is not fully expanded when a child of an accordion

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/vets-design-system-documentation#2010]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I'm running into an issue with the height calculation in `<va-additional-info>` when it's a child of `<va-accordion>`. When expanding, I only see the first line or so:
 
![image_720](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/101649/dd9742b7-91c1-4544-ab1f-9efd76df195c)

If I resize the window, it's immediately recalculated and fixed:

![image_720](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/101649/90d08e68-1df9-473e-9fb4-ca8bbe9c2b27)

## What I expected to happen

All content should be visible when the additional info component is first expanded.

## Reproducing
- Formation version:
- Device: Windows 10 laptop
- Browser: Edge

Steps to reproduce:

Repro sandbox here: https://codesandbox.io/s/additional-info-repro-6p44hp?file=/src/index.js

2. Add a `<va-additional-info>` component with multiple lines of content as a child of a `<va-accordion>`
3. expand the parent accordion item
4. attempt to expand the additional info component
5. content is not fully shown

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

Related slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1692226500909139

**Comment by it-harrison** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/component-library/pull/821)
