### ISSUE TITLE
Both v1 and v3 Crisis line modal do not reflect the current design

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2016]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The Crisis Line modal variation for both v1 and v3 is not what is in production:
![Screenshot 2023-08-18 at 2 25 50 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/466c0cbc-d76a-428c-adeb-66d4cd72fb18)

Also, the trigger for the modal in our examples is not current either:
![Screenshot 2023-08-18 at 2 26 20 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/07aae114-3943-4baf-9adb-89a6c48c2a8d)

## What I expected to happen

I expect our examples to match production.

## Reproducing

Steps to reproduce:

1. Visit va.gov
2. Open Veteran Crisis Line modal
3. Observe

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

We should fix this before we attempt to get this component approved in Staging review.

**Comment by caw310** [comment]
Update Storybook - https://design.va.gov/storybook/?path=/docs/components-va-modal--crisis-line-modal

**Comment by micahchiang** [comment]
Minimal header work is done minus the red trigger mentioned above in the description. We are leaving the [pull request](https://github.com/department-of-veterans-affairs/component-library/pull/846) for minimal header open until this ticket is finished, so we can properly import the trigger instead of having it as a child component.

**Comment by ataker** [comment]
I created a [`va-crisis-line-modal`](https://github.com/department-of-veterans-affairs/component-library/blob/minimal-header-dst2030/packages/web-components/src/components/va-minimal-header/va-crisis-line-modal.tsx) for the minimum header that would be a great jumping off point for working on this ticket,

**Comment by caw310** [comment]
May carry over as there is a dependency on PR approval of [Minimal Header with existing design conventions] - Development https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2030
