### ISSUE TITLE
[Sketch] Step indicator v3 for Steps 3 - 13

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2018]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Other

### What is the name?

Step indicator

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [X] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

It's unpredictable how many steps a form may need. Collab cycle has requested that the step indicator in sketch match the actual reality of the number of steps in a form, even if the code will use the correct number of steps.

To make it easier for UXers to update/change and use the proper number of steps, I've built out step indicators for forms that have as few as 3 steps and as many as 13 and all the ones in between.  You can find them in this sketch library set up as symbols:

https://www.sketch.com/s/9766bff3-3825-49af-a417-e018bf3e0e87

They are also built to be resizable - so we may only need to import the mobile version, then it can be stretched to whatever width.  There are a lot of symbols & artboards in that project, you can find all the steppers in the top right portion of the sketch file

<img width="466" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/74d44515-98fa-49b7-8f21-0f27b3deb9e9">

<img width="358" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/7f42119a-a0ef-42ac-bbe7-76252139ba4b">

If there's anything that should be done to improve these, let me know and I can spend the time to fix them.

**Comment by LillyBoot** [comment]
@jeana-adhoc these have been added to the symbols library. They are listed under Step Indicator / number of steps
