### ISSUE TITLE
Need to test value of va-text-input component for unit testing

### ISSUE THREAD

**Issue by vsaleem** [department-of-veterans-affairs/vets-design-system-documentation#2020]
# Support question

- [ ] I’ve searched for any related issues/questions on github

## How can we help?

        Hi there!  I am trying to chai write unit tests that checks the input text change of the va-text-input component while using the React Testing Library.  I am using a data-testid on the va-text-input component to pinpoint it's value, however when I use fireEvent.change from the React Testing Library, I receive this error: "Error: The given element does not have a value setter."  This indicates that the va-text-input is not a 'true' input type component. 

Can you help me find a way to test this component so that I can alter the text value?  Any method would work, I'm currently shot of ideas.

Thanks!

## What you have tried:

1) Tried using fireEvent.change and fireEvent.input with the component's data-testid attribute to change the value of the input field within a chai unit test.

## What problem does this solve?

      This problem prevents in-depth testing on the va-text-input component.. If this issue can be resolved developers will be able to just the text value presented inside the input field.

**Comment by micahchiang** [comment]
Hi @vsaleem - React Testing Library doesn't support shadow dom usage, [this is a known issue](https://github.com/testing-library/dom-testing-library/issues/413)

You can find an example of testing inputs in the shadow dom with cypress [here](https://github.com/department-of-veterans-affairs/vets-website/blob/10dda10dcba1355f9db45f3bad1396920aab6855/src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js#L137). I recommend using cypress here if you can.
