### ISSUE TITLE
USWDS Font normalization settings bug

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2025]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Background
We want to normalize the Bitter header font in the VADS to the font's already normalized in the USWDS. The USWDS has documentation on how they created the normalization settings and how you can apply tokens to get the correct normalization settings. 

[Font normalization settings ticket](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1923)

## What happened

When trying to apply those settings using what is laid out in the USWDS the settings don't work and fonts are not normalized. 

[Font normalization documentation](https://designsystem.digital.gov/design-tokens/typesetting/overview/)

I created an example using the USWDS. 

The first row show the difference in what the USWDS is documenting and what is actual showing up in code. 
1. USWDS - What they are saying the output would be using the gold table below for each font.
2. CSS - What is actually applied in the CSS
3. Computed - The computed code that can be compared to the gold table image below.

The second row shows the font css styles being applied coming directly from the USWDS without any extra styles applied.

The third row shows the font when you manually apply the normalization settings from the gold table image below.
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/4505990/4f15c5d5-b57b-4243-ab87-c36cd9d860ff)

The potential bug might be in the line-height being applied. When using the line height token of 3 a 1.35 line-height should be applied to the element but it didn't happen. There were varying line-heights applied instead, this goes against the documentation that is shown in the example. 

<img width="952" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/4505990/62540fbb-a558-45ce-a629-83dd69bead20">

We are trying to figure out if there is a bug in the Typography settings of the USWDS that is preventing the normalization of the fonts. 

## What I expected to happen

When applying the normalization settings in the USWDS that the font's all align and are of similar vertical heights. 

## Reproducing

Steps to reproduce:

1. Apply to normalization setting to a typography using the documentation and tokens on the page - https://designsystem.digital.gov/design-tokens/typesetting/overview/ 
5. See if the settings match up with the gold table image above

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

This might be easier to do a 1:1 to explain the issue and the steps to recreate it. 

Overall, the goal is to get the normalization settings to work from the USWDS and if there is a bug then we could document the issue and report it to the USWDS to fix. 

Secondary goal, if you can figure out how UWDS is creating their normalization setting so we can most accurately apply that to the Bitter font used in USWDS that would be great but no problem if this is tabled.

**Comment by nickjg231** [comment]
A bug was identified and fixed in the USWDS pull request. USWDS needs to approve the PR
