### ISSUE TITLE
[Minimal Header with existing design conventions] - Development

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2030]
## Description
We currently have a ticket (#1393) that contains work related to a new minimal header with a brand new design. That ticket should be worked on at some point down the road. For now, teams should have a minimal header with existing design conventions available for use in their applications. 

Prior discovery work was done in [ticket 1339](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1339) which includes designs for a minimal header using existing assets. 

<details><summary>Mobile Minimal Header</summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcElxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2bdd6038b5944bdd2d6cab543dfcc1cf4400b8a6/Screenshot%202023-08-22%20at%205.10.11%20PM.png)

</details>

## Details
-[Prior research and design](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1339)
- Minimal header will for now contain three parts:
  1. Crisis line
  2. [USA Gov site banner](https://designsystem.digital.gov/components/banner/)
  3. Static blue VA branding, non-dynamic for now 

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Contact designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Added to sprint 34 replacing 1393.

**Comment by caw310** [comment]
https://sketch.com/s/f5f91c9c-f5c5-41f6-8e7e-6cfe003299fa

**Comment by caw310** [comment]
Looks like this will carry over into the next sprint due to PTO and also another issue that needed to be fixed before finishing work on this.

**Comment by caw310** [comment]
This may carry over pending PR approval.
