### ISSUE TITLE
Expand all/Collapse on accordions the wrong font-family

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2033]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When [testing this form](https://staging.va.gov/supporting-forms-for-claims/alternate-signer-form-21-0972/confirmation)  that has a collection of accordions on the confirmation page, I noticed that the `Expand all +` / `Collapse all - ` button font family looked not like Source Sans. 

<img width="209" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/e4228e8c-8d2b-4abd-968f-6c0d91bc2802">

## What I expected to happen

I expected the `Expand all +` / `Collapse all - ` button font family to be Source Sans.  I confirmed that this is [also happening in Storybook](https://design.va.gov/storybook/?path=/docs/components-va-accordion--default). 

<img width="189" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/3a7ad69d-4f84-4303-a6ef-80c9bdafbbca">

## Reproducing
- Formation version:
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1. Navigate to [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-accordion--default)
2. Observe the Expand/Collapse button (One sure way of identifying the font difference is that the lower case "l" in source sans has a slight tail that curves to the right at the bottom.) Looking in inspector, I can't tell what font is being defined, but it's not Source Sans.
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work - **We will just ship with the wrong font here**
- [ ] Other

**Comment by jamigibbs** [comment]
Thank you @jeana-adhoc! You have eagle eyes. 🦅 This will go out in the next component library release.
