### ISSUE TITLE
Replace css-library 'core' color tokens with 'uswds' variables

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#2037]
## Description

As a developer, I want to take advantage of Style Dictionary's ability to use token variables, so that 'core' colors are kept in sync with their USWDS V3 counterparts. For example, in tokens/color.json, instead of `"v3-color": {"error": {"dark": {"value": "#b50909"}}}` it should be `"v3-color": {"error": {"dark": {"value": "{uswds-system-color-red-vivid-60}"}` and likewise for any and all colors which have a USWDS V3 equivalent.

## Tasks
- [ ] Replace all color token hex values with their USWDS token variables, where possible

## Acceptance Criteria
- [ ] All colors which can be replaced with variables have been replaced with variables

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2037?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
