### ISSUE TITLE
v3 Radio group fieldset has a max-width defined on the desktop viewport

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2041]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On desktop and tablet, the radio group is always limited at a `max-width:320px`. No other component tested has this width constraint.

## What I expected to happen

The radio label at least to be more than 320px wide on desktop

## Reproducing
- Formation version:
- Device: Macbook
- Browser: chrome

Steps to reproduce:

1. Navigate to https://design.va.gov/storybook/?path=/docs/uswds-va-radio--default
2. View source on the radio group
3. Observe that the fieldset around the radio group has a `usa-form` class on it with a max-width of 320 defined on it. When that class is removed, the width defaults to the class on the legend which has a width of 480px. 
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress but we have a workaround - the workaround being we will live with it for now.
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

This is most obvious in upcoming forms where we are using headings in the legends or as labels. For example, in our header test, the label becomes an `<h1>`

<img width="450" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/412c805e-bd13-47ed-a341-21e9eaed56e1">

When I remove the `usa-form` class it looks like this

<img width="450" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/5a80b4da-c12a-4129-86f9-b98a53a3fbbe">

This seems to match what is happening with the v1/2 components now where this is no max-width constraint on desktop.

**Comment by caw310** [comment]
@jeana-adhoc , this was changed per an earlier request. 
https://github.com/department-of-veterans-affairs/component-library/pull/726

Do you think that's incorrect?

**Comment by jeana-adhoc** [comment]
I think it might be. I think the breakpoints could be set up differently to handle constraining the width. If we're constraining the radio group, we should also constrain every other field type at 320 as well, and I don't think that's necessary. I'm still poking a bit to see if I can provide some better guidance.

**Comment by oleksii-morgun-va** [comment]
We are seeing this impacting `My Health - Secure Messaging` in a following way 👇🏻 

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/87077843/2437ad31-34bb-4dd5-b362-5a09dbe5304c)

**Comment by it-harrison** [comment]
[PR is here](https://github.com/department-of-veterans-affairs/component-library/pull/830)

@rsmithadhoc can you take a look from an a11y perspective?
