### ISSUE TITLE
Remove instances of deprecated color warning-message

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/vets-design-system-documentation#2047]
## Description
We have added `feedback-warning-background` to replace `warning-message`. Now we need to remove uses of `warning-message` so we can remove it form our color.json file

## Details
Current uses of `warning-message` to update: 

- Formation: https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fveteran-facing-services-tools%20path%3A%2F%5Epackages%5C%2Fformation%5C%2F%2F%20%24color-warning-message&type=code
- vets-website: https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-website%20%24color-warning-message&type=code

## Tasks
- [ ] Update any instances of `warning-message` to `feedback-warning-background`
- [ ] Remove `warning-message` from color.json file and build new tokens

## Acceptance Criteria
- [ ]

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2047?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010
