### ISSUE TITLE
CSS Library: Generate a Figma USWDS color token file

### ISSUE THREAD

**Issue by LillyBoot** [department-of-veterans-affairs/vets-design-system-documentation#2069]
## Description

We need a token file for the USWDS colors that we actively use in our components. 
Reference ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1957

## Tasks
- [ ] A token files has been created in the CSS Library that works with Figma

## Acceptance Criteria
- [ ] The token file was able to be imported properly into Figma.

**Comment by caw310** [comment]
Adding to Sprint 35 as unplanned work to unblock https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2051

**Comment by ataker** [comment]
Was able to import colors to figma with [this file](https://raw.githubusercontent.com/department-of-veterans-affairs/component-library/884b097fbc3c8da003e471a6dc8a6e23f2d056ff/packages/css-library/dist/tokens/figma/colors/uswds.json)
