### ISSUE TITLE
Design assets for USWDS font normalization

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2074]
## Description
This is a continuation of the previous ticket on finding the line-height bug used in USWDS to normalize the font sizes. 

[USWDS Font normalization settings bug#2025](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2025)

## Details
Nick was able to pinpoint the issue and now we have a solution and can implement the font normalization for the Bitter font. 
He submitted an issue and fix to the USWDS and is waiting for the merge to be complete before the final normalization settings can be updated on the VADS. 

You can track the USWDS issue in the link below.

[USWDS - uswds-core: Font normalization not matching USWDS specifications #5499](https://github.com/uswds/uswds/issues/5501)

## Design Tasks
- [ ] Send bitter font's files to Engineer
- [ ] Figure out the cap-height for the Bitter font. See notes below.

* Notes from Nick about cap-height - The cap-height value for the bitter font. I've noticed that most of the cap-height values for other fonts in the project hover between 340px - 380px. The exact origin of this value puzzles me a bit. It feels somewhat arbitrarily set, but I imagine there's reasoning behind each one. If you're unsure about this, no worries! I can seek some insights from my USWDS pull request contributors.

## Acceptance Criteria
- [ ] Have all the Bitter font file for development
- [ ] Have the cap-height needed to apply normalization settings

**Comment by babsdenney** [comment]
Follow-up dev ticket - [Apply Font Normalization settings from USWDS #2120](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2120)

**Comment by babsdenney** [comment]
[Bitter.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3J4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18897204f4b5d5dd0c5c29c98d003ff62d395a91/Bitter.zip)

Here is the Bitter font files. 

[Slack message about which font files to include.](https://dsva.slack.com/archives/G01BJ3ESXL4/p1696007446981649)

**Comment by nickjg231** [comment]
Posted a discussion post in the USWDS repository asking how they determined their cap height values:
https://github.com/uswds/uswds/discussions/5546

**Comment by caw310** [comment]
This will carry over as waiting for information from USWDS.

**Comment by babsdenney** [comment]
We got feedback from USWDS on this ticket. See this [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1697474878488129) for more information. 

- The Bitter font cap-height is **349px**.
- The Source san pro cap height doesn't match what USWDS has for a cap-height. The cap height found in Figma is **328px** vs. 340px in Github. 

@humancompanion-usds @danbrady @LWWright7 this is ready for review.

**Comment by babsdenney** [comment]
Submitted a bug to the USWDS related to the values they are using for cap-heights that could be inaccurate. 

[USWDS cap-height issue](https://github.com/uswds/uswds/issues/5568)
