### ISSUE TITLE
Implement fixes for V3 Radio Group keyboard with NVDA or JAWS

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2075]
## Details

Follow up to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2035

- What is being cycled through via the arrow keys are the `va-radio-option` elements. Because those are custom elements, the screen reader doesn't know those are inputs, so it performs its default action.

    <img width="1618" alt="bad-version" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/5595adad-b83f-4e41-b6d6-bd27b2de11d5">

    <img width="1618" alt="good-version" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/a31f1a66-35f1-45ca-8a3d-722ba6ea6d9d">

- To fix this, I believe we need to rework the following to use the `<input>`, rather than the custom element. I created a [pull request](https://github.com/department-of-veterans-affairs/component-library/pull/838) with some initial work that gets screen readers working, but there is more to do to ensure the component works as intended. I also attached a video of this with the screen reader. 

    https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/64332502-cf63-4340-baaa-b224d5608cbd

- This may change some core things about this component, so we will want to make sure other things still function as intended. This includes, but is not limited to:
    - Focus and its indicator is properly set.
    - Tabbing to the radio group starts on the first item.
    - The correct radio item gets selected.
    - Moving forward and backward through the list works as intended.
    - When moving to the next radio button, the option label is read. "Radio button 1 of 4, Sojourner Truth" and not just "Radio button 1 of 4".

**Comment by humancompanion-usds** [comment]
This issue is [launch blocking](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64659) for this component and thus needs to be fixed post-haste.

**Comment by powellkerry** [comment]
I spent some time investigating this. 
- Changing `shadow: true` to `shadow: false` on the radio option allows the options to be read and navigation to work correctly
- For some reason changing the code so that the input is inside of the label allows the label to be read properly. The current structure is based off of the USWDS and their example does not seem to have this issue. I am still investigating this.

**Comment by jeana-adhoc** [comment]
Just making a note here - [that I validated the fix in from the other ticket](https://github.com/department-of-veterans-affairs/component-library/pull/860), and it works!  Thank you.
