### ISSUE TITLE
Bug: v1 button remove background color on hover state 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2083]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
We need to remove the background color from all the different states in V1 of the secondary button.
Button should not have background color on hover.

See Storybook 
https://design.va.gov/storybook/?path=/docs/components-va-button--secondary&globals=backgrounds.value:!hex(333333)

Also see this Slack thread. https://dsva.slack.com/archives/C01DBGX4P45/p1694623499558149

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
v1 button has been replaced by the v3 va-button. Closing.
