### ISSUE TITLE
Background only alert box mobile icon padding off

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#2094]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When the `background-only` prop is applied to the [USWDS va-alert](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default), the padding/margin to the left of the icon disappears when you resize below the desktop breakpoint. Here's what it looks like:

## What I expected to happen

It should maintain the same amount of padding as the standard alert as it does on the [non-USWDS slim va-alert](https://design.va.gov/storybook/?path=/story/components-va-alert--slim)

## Reproducing
- Formation version: https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default
- Device: Macbook Pro
- Browser: Chrome

Steps to reproduce:

1. Go to: https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction
2. Resize the browser to tablet or mobile view.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/b6b37512-db1b-4d4d-816e-7f19a30a1b16)

**Comment by humancompanion-usds** [comment]
This is a v1 component bug. We won't be fixing this.
