### ISSUE TITLE
va-official-gov-banner padding issue 

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/vets-design-system-documentation#2097]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
`va-official-gov-banner` padding issue at medium size. "Here's how you know" text is wrapping to a new line incorrectly

![268127331-b21bb235-e6c7-48f7-a766-5b07de71e0a2](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1413938/957cfb6d-0512-4fec-b5f0-520f1a6dff45)

## What I expected to happen
There are three outcomes that I think would be acceptable:

1. It wraps to the new line without issue
2. It stay on the same line as "Official website..." text as it appears to be enough room at this size
3. It converts to the smaller version seen on va.gov:
![Screenshot 2023-09-15 at 15 15 54](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1413938/0c127753-3ecd-4dea-8180-ce772a1fbf03)

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
First reported on the [va-minimal-header PR](https://github.com/department-of-veterans-affairs/component-library/pull/846)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2097?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010
