### ISSUE TITLE
Email template design

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/vets-design-system-documentation#211]
# Feature Request
Email communication template

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.
No

## Do you have a suggestion for a new component or utility?
We have created an email template to be used to notify Veterans that their disability compensation claim submitted on va.gov was received (see screen below). While this is one use case, the overall template is something that should be reused for future email notifications.

## Additional context
The template draws from the design system styles. However, many email clients do not allow for non-standard fonts. The below mockup uses Arial instead.

![email-template](https://user-images.githubusercontent.com/56000470/86640754-31d5f700-bfa0-11ea-8aa3-df6062ff36c1.jpg)

**Comment by artsymartha68** [comment]
Is it possible to include any images/logos in the footer of the email body in case the Veteran is on a very slow internet connection? There's nothing more frustrating than waiting for a non-essential image to load while you're trying to read the important content. The images also take up valuable vertical screen real estate on phones.

**Comment by toddstanich** [comment]
@artsymartha68 We could add images at the bottom below the text as part of the template. The body area of the email (in this case, everything below the blue bar) is rendered using some simple formatting similar to markdown. Currently we support headings, bold, inset text (rendered as the card), bullet points, and horizontal line.

**Comment by KevinMHoffmanUSDS** [comment]
Notes from Design System Council discussion on this pattern, July 17 2020

* Recommendations for documentation
** Be sure to cross reference all other elements used in this pattern, e.g. buttons, etc.
** Develop IA and content hierarchy rules
** Guidance should include header info, to from and subject formatting
* Design recommendation: Don’t use all caps for the name, or in the text - accessibility
* UX pattern question - make sure we support email management in general - unsubscribe (or other interaction)
* Was it intentional to  include opt in or opt out - it’s just transactional for now, in the product outline, states doesn’t involve integration with VA profile to add/manage controls
* Email - make sure it says “how you will be contacted” in the actual copy, if the email is referring to an alert on a business process (e.g. "we will call you/mail you/text you when the next step has been completed in the process")

**Comment by toddstanich** [comment]
Thanks @KevinMHoffmanUSDS  Regarding documentation, what is the best way to share our documentation with you all? Add it to this ticket?

Answers to the other points below:
* Design recommendation: Don’t use all caps for the name, or in the text - accessibility - **Will address**
* UX pattern question - make sure we support email management in general - unsubscribe (or other interaction) - **in progress, will be a capability**
* Was it intentional to include opt in or opt out - it’s just transactional for now, in the product outline, states doesn’t involve integration with VA profile to add/manage controls - **We are working with the VA profile team to add/manage controls. It just doesn’t apply for this initial use case.**
* Email - make sure it says “how you will be contacted” in the actual copy, if the email is referring to an alert on a business process (e.g. "we will call you/mail you/text you when the next step has been completed in the process") **Thanks, we will include this info when referencing next steps for communication**

**Comment by artsymartha68** [comment]
Hi, team. We are exercising this template in the vaccine trial registry project, but found an issue in dark mode. Wondering if we should reconsider the blue header? That, or  "hardcode" a background color into the logos images?

![Screen Shot 2020-09-11 at 11 43 14 AM](https://user-images.githubusercontent.com/47792423/93124275-5bde2080-f697-11ea-87c3-122924ae19bc.png)

**Comment by LeakyBucket** [comment]
FYI ^ was from a very raw manual attempt to recreate this in vets-api:

```
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <style>
      header {
        background-color: #112E50;
        padding: 10px 0px 10px 25px;
      }

      body {
        background-color: #FFFFFF;
      }
    </style>
  </head>
  <body>
    <header>
      <img alt="VA Seal" src="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/header-logo.png">
    </header>

    <h1>Thank you for joining our coronavirus research volunteer list</h1>

    <p> We appreciate your commitment to helping others through this important research effort.</p>

    <h2>If we think you may be eligible for one of our research studies</h2>

    <p>We'll contact you to tell you more about it so you can decide if you want to join</p>
    <p>Please understand that some studies have specific requirements. So it may be weeks or months before there's a study that you may be eligible to join.</p>
    <p><em>Note</em>: We'll never ask for an ID number or for your financial, credit, or bank account information over the phone. For tips on how to aviod coronavirus-related scams, visit the <a href="https://www.ftc.gov/coronavirus/scams-consumer-advice">Federal Trade Comission website</a></p>

    <h2>If we don't think you may be eligible for any studies</h2>

    <p>We won't contact you. But we'll keep your information on file for future studies you may be eligible to join.</p>
  </body>
</html>
```

**Comment by toddstanich** [comment]
While we were developing the template for VANotify, we tested in several clients/browsers and we were able to get dark mode looking good on all but one version of Outlook on Windows. Based on our research, it sounds like clients are implementing dark mode differently and their support is still changing. Here is a good article explaining the differences between clients - https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers/

**Comment by toddstanich** [comment]
@KevinMHoffmanUSDS Now that we’re further along and onboarding more teams, we’d like to resume the conversations about adding the email template to the design system documentation site and Sketch library. I know there is now a design system team spun up since we started this card. What is the best way to engage and move this forward?

**Comment by caw310** [comment]
Discussed in DSC meeting 1/8. Design system team will prioritize this for an upcoming sprint.

**Comment by artsymartha68** [comment]
I have been asked to design an email template and I want to stealborrow your excellent work @toddstanich  😺 
Can I get our specs somewhere?

**Comment by toddstanich** [comment]
@artsymartha68 attaching a sketch file with some info. 
[Email-styles.zip](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/5815372/Email-styles.zip)

**Comment by caw310** [comment]
Tasks will include:
- Audit/research 
- Kickoff meeting with team 
- Sketch template created
- Handoff with developer 
- Documentation
- Development of email template (many unknowns on dev side) 

@caw310 , to create a separate development ticket for email template.
