### ISSUE TITLE
Error message on v3 Memorable date "month select" gives incorrect guidance

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2121]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When triggering an error on the memorable date v3 component, it gives me the incorrect guidance to fix the error.

<img width="466" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/c72da168-3ce1-4869-a2db-60d48ba4e73c">

The error says "Please enter a month between 1 and 12"

This is problematic because there are no numbers to enter, and the drop down has months in words, not numbers.

## What I expected to happen

I expected the error message to read "Please select a month"

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Navigate through the form 21P-0847 on staging to this page https://staging.va.gov/supporting-forms-for-claims/alternate-signer-form-21-0972/veteran-personal-information
2. Tab through the date fields, not filling out anything
3. When the error triggers,  you'll see the error message.

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/ef0684e4-2915-4c75-acd2-e9444decc4e9

You can also see the error message in [the storybook example](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--with-month-select#error-with-month-select). After you tab through the fields, the error message changes to match the screenshot above.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by rhasselle-oddball** [comment]
currently working on this

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2121?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by rhasselle-oddball** [comment]
correction: https://github.com/department-of-veterans-affairs/component-library/pull/878

**Comment by caw310** [comment]
Robert from VFF team made a fix so closing.
