### ISSUE TITLE
Figma Example Template using the Alert

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2129]
## Description
Build an example template using the Alert in Figma. 

- [Sketch Component Library](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4)
- [Sketch Example Library](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c)

## Details

- [ ] Create a new figma file
- [ ] Figure out how you would want to organize the file structure for the components
- [ ] Add the components that are ready for release from the VADS Component library
- [ ] Add link to documentation link to components
- [ ] Do a final check of the components to make sure they are well-built

## Acceptance Criteria

- [ ] Reviewed by other DS designer
- [ ]  Review by PO?

**Comment by caw310** [comment]
Adding as unplanned work in sprint 42 as this is a high priority now that VFS designers have access to FIgma.

**Comment by caw310** [comment]
This will like carry over since it was added to the sprint 42 late.
