### ISSUE TITLE
H1 white font is incorrect

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#2130]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The `H1 white` is set in `Helvetica` instead of `Bitter` in the Component Library text styles.

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/4c3f676f-aec4-4316-917b-3687a7772b84)

## What I expected to happen

The text style needs to be updated to Bitter in the Component Library text style.

## Reproducing

Steps to reproduce:

1. Try to apple the Component Libaray `H1 white` text style to a text field. 

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
"Fixed" although it's not clear to me where this text style was intended to be used. One could just change the color of the H1. I don't think that's locked down. Regardless, it's been addressed.
