### ISSUE TITLE
Add left and right chevrons to pagination component

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#2138]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We have recently added the [USWDS pagination component](https://designsystem.digital.gov/components/pagination/). The component is missing the left and right chevrons in both [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-pagination--default) and our [design system](https://design.va.gov/components/pagination#examples---v3).

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1.
2.
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2138?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by caw310** [comment]
Closing this as items are listed in this issue. https://github.com/department-of-veterans-affairs/va.gov-team/issues/66068
