### ISSUE TITLE
Change the Link - Deep Content component label to Deprecated Link 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2139]
## Description
The Link - Deep content component was added to the DS for a specific use case. It is no longer used on VA.gov so DST would like to deprecate this component. Change the Link - Deep Content component label to Deprecated Link 
https://design.va.gov/components/link/deep-content

## Tasks
- [ ] Change the label for Link-deep content component to deprecated

## Acceptance Criteria
- [ ] Link - Deep Content component has deprecated label on design.va.gov

**Comment by humancompanion-usds** [comment]
Deprecated in guidance. This never graduated to a VA component.
