### ISSUE TITLE
Update Text area sketch symbol so label can line wrap

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2147]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

the sketch symbol for text-area does not allow text to wrap in the label without breaking the symbol or forcing line breaks

## What I expected to happen

I expected to be able to resize the text-area symbols so that text would wrap for the appropriate widths.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

I have re-created the symbol with [default](https://www.sketch.com/s/9766bff3-3825-49af-a417-e018bf3e0e87/a/kKLJopg), [hint text](https://www.sketch.com/s/9766bff3-3825-49af-a417-e018bf3e0e87/a/oMLGkwY) and [error](https://www.sketch.com/s/9766bff3-3825-49af-a417-e018bf3e0e87/a/r9wDreD) states in sketch, in case it works to just copy and paste

**Comment by babsdenney** [comment]
@jeana-adhoc I updated the component library to fix the bug you are describing. Can you download the latest component library and see if that fixed the issue?

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2147?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by jeana-adhoc** [comment]
@babsdenney - It looks great! Although - I just realized there's not a version with the `(*Required)` label... but I'm thinking that's also challenging because of the way sketch works, and it doesn't have auto layout features. But yes - the goal of my bug ticket has been met!

**Comment by babsdenney** [comment]
@jeana-adhoc Thanks for reviewing! That's the truth, were having issues getting the layout to work with Sketch and Figma has a similar issue. I hope we can figure that out in the future.
