### ISSUE TITLE
508-defect-2 [COGNITION]: Telephone - 911 and 711 SHOULD NOT have extra information in their aria-labels

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#218]
@1Copenut commented on [Thu Jun 18 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10446)

# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Our [Telephone component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/telephone/) has several examples of correct formatting with `aria-labels that read out numbers individually. This is a **great** thing.

The `911` aria-label will read out "One. Nine. One. One." This is potentially confusing, because 911 does not require users to dial "1" first. The accessibility specialists are in agreement we should update this aria-label. Code snippet below.

The `711` aria-label will read out "Tee Tee Why. Seven. One. One." This could be repetitive because the string TTY: is often added in text just before the linked test "711". We should remove the string "TTY" from the aria-label. Code snippet below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] 911 link reads out as "Nine. One. One" for screen readers
- [ ] 711 link reads out as "Seven. One. One" for screen readers
- [ ] [Telephone component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/telephone/) documentation is updated to reflect the correct aria-label output.
- [ ] Create and/or modify unit tests for this component to include an aXe scan

## Environment

* https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/telephone/

## Possible Fixes (optional)

```diff
# Telephone.jsx#L32
const LABELS = {
- 711: 'TTY: 7 1 1.',
+ 711: '7 1 1.',
- 911: '1. 9 1 1.',
+ 911: '9 1 1.',
};
```

## WCAG or Vendor Guidance (optional)

* [Language of Parts: Understanding SC 3.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-other-lang-id.html)

---

@jenniferlee-dsva commented on [Thu Jun 18 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10446#issuecomment-646239587)

@1Copenut - Hello - just wanted to ask a qq:  The content team was advised before the design system launched that when phone numbers are hyperlinked, that the linkref should include the +1. I don't remember if that was due to accessibility or due to enabling mobile phones to dial the number by clicking the link. 

Does the above global aria label guidance wrt the 1- prefix mean that all hyperlinked phone numbers on content pages should now omit the 1 prefix in the linkref? 

@RLHecht @DanielleThierryUSDSVA fysa ^ 

---

@1Copenut commented on [Thu Jun 18 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10446#issuecomment-646251533)

@jenniferlee-dsva The guidance above is only for the `aria-label` that is read out to screen readers when users focus or swipe to the `911` link on the page. This should not affect or change how the `href` is structured.

---

@jenniferlee-dsva commented on [Thu Jun 18 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10446#issuecomment-646315806)

Thank you so much for the explanation @1Copenut!

**Comment by noahgelman** [comment]
@1Copenut This component doesn't exist. Please correct me if I'm wrong

**Comment by bkjohnson** [comment]
Here is the component:

- [Storybook](https://design.va.gov/storybook/?path=/docs/components-telephone--default)
- [Source](https://github.com/department-of-veterans-affairs/component-library/tree/master/src/components/Telephone)

Trevor's linked page likely got removed in [this PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/575), and the page didn't have any component documentation which is why we don't have design.va.gov/components/telephone

**Comment by noahgelman** [comment]
Closing this issue. No longer exists.
