### ISSUE TITLE
va-breadcrumbs USWDS variation compatibility with React Router <Link>

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2188]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

There's been a report that the `<Link>` component used by React Router does not work with the `uswds` variation of `va-breadcrumbs`:

https://design.va.gov/storybook/?path=/docs/uswds-va-breadcrumbs--default

See this Slack convo for more context: https://dsva.slack.com/archives/C01DBGX4P45/p1696604409093289

## What I expected to happen

Since the original va-breadcrumbs variation (non-USWDS) works with `<Link>`, I would expect that the USWDS variation would as well.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Set up the `va-breadcrumbs` component based on the [USWDS variation example](https://design.va.gov/storybook/?path=/docs/uswds-va-breadcrumbs--default).
2. Try to use the `<Link>` component to display crumbs.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by it-harrison** [comment]
[Draft PR here](https://github.com/department-of-veterans-affairs/component-library/pull/976)
