### ISSUE TITLE
Experimental Design [va-accordion] - @media print CSS

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/vets-design-system-documentation#2206]
## What
Change the `va-accordion` and `va-accordion-item` CSS ruleset for `@media print`

## Purpose
Will allow non-expanded accordions to be viewable when rendering media print

## Usage
When a user attempts to print the CSS should show all the content, not just the collapsed headlines of the sections

## Behavior
So this can be accomplished in one of two ways, either:
1. Update the `va-accordion` SCSS file OR,
2. Add the `part="accordion-content"` to the `<div id="content"><slot /></div>` and let individual teams figure out how printed pages should look.

## Examples
> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.

## Accessibility
> Include any accessibility considerations.

## Guidance
> What would you want to tell other teams about this component or pattern?

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.

## Code (optional)
> Include any existing code.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
@asg5704 , are you available to attend the DSC meeting this Friday, Oct 20 at 1pm ET?

**Comment by asg5704** [comment]
Sure @caw310 you can add me to the meeting

**Comment by caw310** [comment]
See this ticket from Robin that is related. https://github.com/department-of-veterans-affairs/va.gov-team/issues/5955

**Comment by caw310** [comment]
Follow up from DSC meeting:

- Put in backlog
- Nice to have

**Comment by Mottie** [comment]
Awaiting content library update in the vets-website repo to validate this work

**Comment by Mottie** [comment]
Component library updated to 42.1.1, which includes print media CSS to print accordion content even if it is collapsed.
