### ISSUE TITLE
v2 Progess indicator has unnecessary aria-label

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2209]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

In the 508 audit report for 21-10210, which is using the v2 version of the progress indicator, it was pointed out that JAWS is reading the "Step 2 of 6" twice. JAWS will announce the `aria-label` that's placed on the bars "Step 2 of 6", and then, it will announce the h2, `Step 2 of 6`: VA Benefits.

## What I expected to happen

I expected `Step 2 of 6` only be read once.

It appears this was solved in v3 of the stepper as `aria-hidden="true"` is placed on the graphics of the stepper and are not at all exposed to a screen reader.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Navigate to [storybook](https://design.va.gov/storybook/iframe.html?id=components-va-segmented-progress-bar--default&viewMode=story)
2. Turn on JAWS
3. Use the down arrow to nav through the items
4. Hear it announce "Step 2 of 6, Step 2 of 6 VA Benefits" 

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress but we have a workaround - use the v3 component
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2209?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
