### ISSUE TITLE
Design Discovery: Reexamine radio and checkbox colors being used

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2213]
## Description
The checkbox and radio button tiles use rgba to set the colors that have a transparency applied. Wondering if this is the best route for this. 

Note: The USWDS does have a transparency applied to their tile option for radio and checkbox. 

Concerns about using these colors:
- Introducing unnecessary colors into the Design System - We do have other colors that could work that aren't transparent (See image below).
- Accessbility issues - Does using colors with transparency introduce contrast issues. Most of the time the background color will be white but it it was a darker color there might be issues seeing the text.

Here is an example of using some colors we already have in the Design system. The top tile is using the original colors being applied. 
<img width="413" alt="Screenshot 2023-10-18 at 12 55 46 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/4505990/39453ac0-3469-44de-8ddc-9787b1cb7b55">

## Details
[VA V3 Checkbox tile](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--tile)
[VA V3 Radio tile](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--tile)
[USWDS V3 radio button component](https://designsystem.digital.gov/components/radio-buttons/)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
@babsdenney is this still needed?

**Comment by babsdenney** [comment]
@caw310 No, I think we can close this out because our background color does align with the USWDS. I can submit an issue to the USWDS and let them know the concerns.
