### ISSUE TITLE
Deprecate ResponsiveTable in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2215]
## Description 
Related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2045

[Responsive Table](https://github.com/department-of-veterans-affairs/vets-website/blob/68296c4e39ea3f166696b2bff88221f1a15713b7/src/applications/gi/components/ResponsiveTable.jsx#L6) is an class that uses regular html table elements and custom styles, and has one usage instance. This should be deprecated in favor of va-table.

## Considerations
- Uses some custom styles

## Tasks
- retire ResponsiveTable and use va-table instead
- address any tests

## Acceptance Criteria
- [ ] tasks have been completed

**Comment by nickjg231** [comment]
This ticket will carry over because of local build issues preventing debugging
