### ISSUE TITLE
Table Deprecation - Content Build

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2217]
## Description
Related: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2045

The following usages of table need to be switched to va-table:
- https://github.com/department-of-veterans-affairs/content-build/blob/2fb414c5ae31e6b2dde8f2120eafa35f08c31e1e/script/github-actions/code-coverage-format-report.js#L14 (maybe? this is in a github action, so maybe not)
- https://github.com/department-of-veterans-affairs/content-build/blob/e8816267f6de08f263078d2a7aa9319f978fb1cd/src/site/paragraphs/table.drupal.liquid#L30

## Tasks
- [ ] switch above usages to table

## Acceptance Criteria
- [ ] tasks have been completed

**Comment by caw310** [comment]
Moving sprint 40

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/content-build/pull/1817

**Comment by Andrew565** [comment]
The PR is listed as a Draft PR, is it waiting on something to promote to a 'real' PR?

**Comment by jamigibbs** [comment]
> The PR is listed as a Draft PR, is it waiting on something to promote to a 'real' PR?

@Andrew565 It looks like it still needs to be tested and the PR needs screenshots, etc.

**Comment by caw310** [comment]
Carrying over as this was handed off and tests are still needed.

**Comment by caw310** [comment]
This will carry over due to this having to be handed off. Testing has been challenging so this will carry over again due to upcoming holiday.
