### ISSUE TITLE
VA Crisis Line button colors do not align with VADS colors

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2221]
## Description

Some of the colors being used in the crisis line button in the VA header are not found in the Design System. Here are colors that are using in the current VA.gov header that don't align with colors in the Design System. 

Icon - #8b1303
Icon on hover - #b51d09

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/4505990/011c8811-fea0-4a28-be53-2d5d181446a0)

Both of these colors are not in the Design System, we will need to evaluate these colors and decide if we want to move these colors to the Design System or use current colors that are already in the DS. 

## Details
[VA.gov header in prod](https://www.va.gov/)
[Colors in VADS](https://design.va.gov/foundation/color-palette)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
@danbrady please confirm this is correct now and if so close the ticket.
