### ISSUE TITLE
va-on-this-page web component text doesn't align with other content on page

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/vets-design-system-documentation#2225]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
When using the `<va-on-this-page>` web component, the `On this page` text ends up out of alignment with the rest of the content on the page. Below is a screenshot from an app in vets-website, but this can be observed by looking at the examples in Storybook [here](https://design.va.gov/storybook/?path=/docs/components-va-on-this-page--default). The second screenshot is taken from one of the examples in Storybook.

<img width="978" alt="Screenshot 2023-10-23 at 1 36 44 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/13838621/62d4dcb9-2052-4e7d-bb88-a580ff00b3e1">

### Storybook
<img width="974" alt="Screenshot 2023-10-23 at 4 08 31 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/13838621/67469001-2990-4e67-ac4c-371cee3b728f">

## What I expected to happen
I expect that the `On this page` text would align with the rest of the content on the page and that the links under it would be indented slightly. Removing the `margin-left: -0.5em;` CSS rule applied to the `dl` achieves the desired effect.

<img width="882" alt="Screenshot 2023-10-23 at 4 02 23 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/13838621/e41f21ff-05c1-42b4-b323-2847983db5bb">

## Reproducing
- Formation version: 
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1.
2.
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment]
Original Slack convo for reference: https://dsva.slack.com/archives/C01DBGX4P45/p1698085400779229?thread_ts=1698083082.022499&cid=C01DBGX4P45
