### ISSUE TITLE
Remove banner landmark from <va-promo-banner> component

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/vets-design-system-documentation#2239]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The `<va-promo-banner>` currently has a `role="banner"` attribute, which is not correct. The banner role is intended for the global header (the `<header>` is the semantic equivalent of this role). 

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106678594/8595211c-feba-47f0-9678-1b032acd3da6)

## What I expected to happen

I would expect that the banner role is removed from the promo banner component.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1.
2.
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other

### Details

**Comment by laflannery** [comment]
@jamigibbs I'm curious about your deployment/release schedule - would you know when this would be updated?

**Comment by jamigibbs** [comment]
Hi @laflannery It looks like the [release (v32.1.0)](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v32.1.0) was merged into vets-website today and it should be in the next deployment window: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/
