### ISSUE TITLE
va-pagination (v1) pagination inner width causes next button to be pushed to the side

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#2244]
# Bug Report

- [x ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
Support request: https://dsva.slack.com/archives/CBU0KDSB1/p1698873116956839

On the Pagination component, the page number elements are list items contained in a ul with class "pagination-inner". On screen sizes below 768px and above 1201px, there is width being added to pagination-inner that pushes the "Next" button off to the side

![small](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1776069/19b055c5-4517-476e-bf20-4523f2e0c4d0)
![medium](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1776069/d8d63495-d61e-405e-9f4a-a5a503ade42a)
![large](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1776069/e2fde2b1-082d-4d84-8c52-8ff29a0f360f)

## What I expected to happen

The pagination, including the button should be centered on the page.

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2244?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by nickjg231** [comment]
This issue does not exist in the V3 USWDS version. It may still exist in V1, but we will just ask teams to use V3 so this issue does not continue
