### ISSUE TITLE
Alert - Remove v3 background-only Alert style

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2246]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

A developer recently asked us for assistance in Slack because they were noticing some problems with the "background-only v3 alert variation". The problem is that variation should not exist. It only exists in Storybook. The Slim variation of Alert was meant to replace, not be in addition to, the background-only variation.

## What I expected to happen

I expected background-only to go away in v3.

## Reproducing

Steps to reproduce:

1. Navigate to https://design.va.gov/storybook/?path=/docs/uswds-va-alert--background-only
2. Notice that this variation neither exists in [Sketch](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/5E24F540-2558-488C-BD6D-823F4A2F5607/canvas) nor in [https://design.va.gov/components/alert]guidance].

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

This clearly is causing some confusion and it's an easy fix to remove this variation so let's try to clean this up soon.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2246?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
Removing the background-only section from the USWDS va-alert stories file is trivial, but this wouldn't remove the backgroundOnly prop from the list of props. Do we want to go ahead and do that too?

There's only one instance of the backgroundOnly prop being used in vets-website, so removing the prop for V1 and replacing it with something like a 'slim' prop would need to involve editing that one instance, too.
