### ISSUE TITLE
[ZOOM]: OMB Info - Modal text MUST be readable up to 400% zoom at 1280px width

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#225]
@1Copenut commented on [Wed Jun 03 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9815)

## [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The [OMB Info component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/ombinfo/) includes a modal window that has a lot of legal text inside it. At 400%, that text runs behind the close button and is hard to read. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Create and/or modify unit tests for this component to include an aXe scan

## Environment

* https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/ombinfo/

## WCAG or Vendor Guidance (optional)

* [Understanding Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls)

## Screenshots or Trace Logs

![Screen Shot 2020-06-03 at 3 36 08 PM](https://user-images.githubusercontent.com/934879/83688688-66c2e880-a5b3-11ea-8135-db26a25a686e.png)

**Comment by pjhill** [comment]
The OMB Info component was part of the [design system audit](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/270) last year. What ever happened to resolve the synchronization of design system components?

**Comment by bkjohnson** [comment]
By synchronization are you talking about how the component looks/behaves in Sketch vs. in code?

**Comment by pjhill** [comment]
> By synchronization are you talking about how the component looks/behaves in Sketch vs. in code?

Yep, there's that. Also, has the OMB Info component been removed from the list [here](https://design.va.gov/components/).

**Comment by pjhill** [comment]
> > By synchronization are you talking about how the component looks/behaves in Sketch vs. in code?
> 
> Yep, there's that. Also, has the OMB Info component been removed from the list [here](https://design.va.gov/components/).

I found the component in Storybokk [here](https://design.va.gov/storybook/?path=/docs/components-ombinfo--default).

**Comment by bkjohnson** [comment]
I'm not sure about what it looks like in Sketch - @GnatalieH might have some info. However, I don't think we did any work on this specific component over the last year.
