### ISSUE TITLE
Checkbox Group not using correct fonts

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2251]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I noticed the label and (* Required) text in the [checkbox group](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default#required) and [checkbox tile group](https://design.va.gov/) is **not** Source Sans Pro web in [storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--tile#required)

<img width="354" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/4d6dfe0e-f194-47ba-9b95-f6c551bab3ba">

## What I expected to happen

I expected fonts to be Source Sans Pro Web.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work - We plan to launch as is since we're using the design system a perscribed.
- [ ] Other

**Comment by it-harrison** [comment]
[PR here](https://github.com/department-of-veterans-affairs/component-library/pull/969)
