### ISSUE TITLE
Buttons in button pair don't remain same width 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/vets-design-system-documentation#2261]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using the mobile default button pair, changing the text in the buttons causes different widths of the buttons. 

<img width="307" alt="Screenshot 2023-11-13 at 5 38 51 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/101129355/9726c25e-7825-421b-b676-aca85cc85e75"><br>

<img width="233" alt="Screenshot 2023-11-13 at 5 38 37 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/101129355/1d93cdfc-bb9b-4bdc-ab27-cc4fe50ff188"><br>

<img width="383" alt="Screenshot 2023-11-13 at 5 38 19 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/101129355/005343d1-b96e-4f7e-bc2e-de0f6846303b">

## What I expected to happen

The button widths to remain consistent with one another or the buttons to remain consistent widths when changing the width of the component. 

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Sketch > Symbols > Component System Library > Button Pair > Mobile > Default
2. Change text of buttons to "Submit claim" and "Cancel"
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2261?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2261?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by caw310** [comment]
This is fixed in Figma.

**Comment by humancompanion-usds** [comment]
@benbrasso-agile6 - Can you confirm that this is fixed and if so, please close? Thanks!

**Comment by benbrasso-agile6** [comment]
Validated in Figma
