### ISSUE TITLE
Update the radio group component for new forms pattern

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2269]
## Description

The new forms pattern from https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2142 will require changes to our existing components. To keep any global component changes to a minimum, we are implementing an opt-in version of these components.

Instead of the standard markup, this will use a heading as the form question and have a form description. `aria-labelledby` will be used on the field so screen readers will read out the question and description when tabbing to that field.

<img width="809" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/1663c928-6419-4139-b05b-21f84dc813d6">
<img width="817" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/c43599c9-0b93-4bf3-9f2f-4b913da83147">

EDIT: Reference how it was done for the `va-text-input` and `va-number-input` components: https://github.com/department-of-veterans-affairs/component-library/pull/985

- New advanced options
    - ~~`useFormsPattern?: boolean = false`~~  `useFormsPattern?: string`. Accepts either "single" or "multiple" to indicate if the form is a single input or will have multiple inputs. Enabling this will add a heading and description for integrating into the forms pattern.
        - Enabling this will remove headings/descriptions from `fieldset`, `legend`, these will be placed outside.
            - The HTML structure you get will be something like:
                ```html
                <h3 id="form-question">Heading</h3>

                <div class="usa-legend usa-legend" id="form-description">Select one historical figure</div>

                <!-- Form field(s) -->
                ...
                ```
            - Additional properties
                - `formHeadingLevel?: number`
                - `formHeading?: string`
                - ~~`formDescription?: string` - Could be text or some basic HTML like a list.~~
                - `<slot name="form-description"></slot>` a new slot for form description HTML.
            - Ignored properties - If using the forms pattern, some properties that apply to the default version of the component may be ignored. These should be documented.
- Update Storybook, design system docs
    - New properties

## Acceptance Criteria

- [ ] New opt-in version of the component for the form pattern has been implemented.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2269?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
@harshil1793 There have been some updates to the recommended prop additions mentioned from our [first go at integrating this pattern](https://github.com/department-of-veterans-affairs/component-library/pull/985). I'll update the description it:

- `useFormsPattern` (string)
  - Setting to "single" or "multiple" will signify we are straying from the default component and the following props will be available. The value passed in here will determine how the error state will display.
- `formHeadingLevel` (number)
- `formHeading` (string)

And a new slot for form description HTML (the `formDescription` prop has been **removed**):

`<slot name="form-description"></slot>`

**Comment by harshil1793** [comment]
Due to technical challenges, this task will be carried over.
