### ISSUE TITLE
Update the text and number input components for new forms pattern

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2271]
## Description

The new forms pattern from https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2142 will require changes to our existing components. To keep any global component changes to a minimum, we are implementing an opt-in version of these components.

Instead of the standard markup, this will use a heading as the form question and have a form description. `aria-labelledby` will be used on the field, so screen readers will read out the question and description when tabbing to that field.

<img width="809" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/ca253053-bda1-42f6-8eaa-718192c15d1b">

- New advanced options
    - `useFormsPattern?: boolean = false` or another name to describe this. Setting to true will signify "we are straying from the default component."
        - Enabling this will remove headings/descriptions from `fieldset`, `legend`, these will be placed outside.
            - The HTML structure you get will be something like:
                ```html
                <h3 id="form-question">Heading</h3>

                <div class="usa-legend usa-legend" id="form-description">Select one historical figure</div>

                <!-- Form field(s) -->
                ...
                ```
            - Additional properties
                - `formHeadingLevel?: number`
                - `formHeading?: string`
                - `formDescription?: string` - Could be text or some basic HTML like a list.
            - Ignored properties - If using the forms pattern, some properties that apply to the default version of the component may be ignored. These should be documented.
- Update Storybook, design system docs
    - New properties

## Acceptance Criteria

- [ ] New opt-in version of the component for the form pattern has been implemented.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2271?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
The description of this ticket describes what needs to happen at the form level, but not what needs to change for the inputs themselves.

**Comment by it-harrison** [comment]
@rsmithadhoc I am uncertain what needs to happen here. There are no fieldsets/legends in the text-input or number-input components. 

One thing (maybe) is this sketch design where it seems like a heading is inside a text-input label: <img width="1058" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc8e248a56191c5df9c3e7fc95a530eaf97599ef/Screenshot%202023-12-08%20at%204.17.36%20PM.png" alt="Screenshot 2023-12-08 at 4.17.36 PM.png" />

**Comment by it-harrison** [comment]
@rsmithadhoc one other question - does this pattern apply only to `uswds`?

**Comment by rsmithadhoc** [comment]
> @rsmithadhoc one other question - does this pattern apply only to `uswds`?

@it-harrison Yeah, only `uswds`, they should be using the v3 components.

**Comment by it-harrison** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/component-library/pull/985) here with notes for anyone looking to pick this ticket up
