### ISSUE TITLE
Update the textarea component for new forms pattern

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2272]
## Description

The new forms pattern from https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2142 will require changes to our existing components. To keep any global component changes to a minimum, we are implementing an opt-in version of these components.

Instead of the standard markup, this will use a heading as the form question and have a form description. `aria-labelledby` will be used on the field, so screen readers will read out the question and description when tabbing to that field.

<img width="1099" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/8637a6ee-f681-4a0c-9816-2ac58565dde8">

## Tasks

EDIT: Reference how it was done for the `va-text-input` and `va-number-input` components: https://github.com/department-of-veterans-affairs/component-library/pull/985

- New advanced options
    - ~~`useFormsPattern?: boolean = false`~~  `useFormsPattern?: string`. Accepts either "single" or "multiple" to indicate if the form is a single input or will have multiple inputs. Enabling this will add a heading and description for integrating into the forms pattern.
        - Enabling this will remove headings/descriptions from `fieldset`, `legend`, these will be placed outside.
            - The HTML structure you get will be something like:
                ```html
                <h3 id="form-question">Heading</h3>

                <div class="usa-legend usa-legend" id="form-description">Select one historical figure</div>

                <!-- Form field(s) -->
                ...
                ```
            - Additional properties
                - `formHeadingLevel?: number`
                - `formHeading?: string`
                - ~~`formDescription?: string` - Could be text or some basic HTML like a list.~~
                - `<slot name="form-description"></slot>` a new slot for form description HTML.
            - Ignored properties - If using the forms pattern, some properties that apply to the default version of the component may be ignored. These should be documented.
- Update Storybook, design system docs
    - New properties

## Acceptance Criteria

- [ ] New opt-in version of the component for the form pattern has been implemented.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2272?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
The description of this ticket describes what needs to happen at the form level, but not what needs to change for the textarea component itself.

**Comment by caw310** [comment]
This will carry over as the ticket that blocks this one will carry over due to an engineer being pulled to work on something else outside of DST.

**Comment by jamigibbs** [comment]
> This will carry over as the ticket that blocks this one will carry over due to an engineer being pulled to work on something else outside of DST.

This is in reference to this ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2271

**Comment by jamigibbs** [comment]
@ataker There have been some updates to the recommended prop additions mentioned from our [first go at integrating this pattern](https://github.com/department-of-veterans-affairs/component-library/pull/985). I'll update the description it:

- `useFormsPattern`
  - Setting to "single" or "multiple" will signify we are straying from the default component and the following props will be available. The value passed in here will determine how the error state will display.
- `formHeadingLevel`
- `formHeading`

And a new slot for form description HTML (the `formDescription` prop has been **removed**):

`<slot name="form-description"></slot>`
