### ISSUE TITLE
Update the memorable date component for new forms pattern

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2273]
## Description

The new forms pattern from https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2142 will require changes to our existing components. To keep any global component changes to a minimum, we are implementing an opt-in version of these components.

Instead of the standard markup, this will use a heading as the form question and have a form description. `aria-labelledby` will be used on the field, so screen readers will read out the question and description when tabbing to that field.

<img width="982" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/8fe5bc1d-cfe7-48ab-8364-a1150d4fa415">

## Tasks

- New advanced options
    - `useFormsPattern?: boolean = false` or another name to describe this. Setting to true will signify "we are straying from the default component."
        - Enabling this will remove headings/descriptions from `fieldset`, `legend`, these will be placed outside.
            - The HTML structure you get will be something like:
                ```html
                <h3 id="form-question">Heading</h3>

                <div class="usa-legend usa-legend" id="form-description">Select one historical figure</div>

                <!-- Form field(s) -->
                ...
                ```
            - Additional properties
                - `formHeadingLevel?: number`
                - `formHeading?: string`
                - `formDescription?: string` - Could be text or some basic HTML like a list.
            - Ignored properties - If using the forms pattern, some properties that apply to the default version of the component may be ignored. These should be documented.
- Update Storybook, design system docs
    - New properties

## Acceptance Criteria

- [ ] New opt-in version of the component for the form pattern has been implemented.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2273?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
