### ISSUE TITLE
uswds pagination with middle component not adjusting for zoom change or max page list length

### ISSUE THREAD

**Issue by robertbylight** [department-of-veterans-affairs/vets-design-system-documentation#2277]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

  Regarding the [uswds pagination with middle component](https://design.va.gov/storybook/?path=/docs/uswds-va-pagination--with-middle):

note: we are using the value of 6 for the max-page-list-length  property.
bug1: when the max-page-list-length has a value under 6 the component no longer loads the next page number after 4.
bug2: the component seems to cut off when using small screens on page 10, for some reason it doesn't on the pages before 10 but after 10 the component changes and is cut off on both ends.(see images)

## What I expected to happen

bug1: expect the next page number to appear
bug2: expect the component to adjust to the smaller screen size.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

bug 1:
1. change the max-page-list-length to 6
2. go to page 4.
3. the next page number doesn't appear
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/107279507/0593ad91-a4ee-4739-beee-93a396819388)

bug2:
1. switch to iPhone SE - 375x667
4. add 13 pages to the pagination
5. go to page 10 and notice how the first and last buttons are cut off the screen

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/107279507/9504b929-ad23-4ad2-8c70-a171ae4e8868)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by BobbyBaileyRB** [comment]
This might be worth mentioning, pagination is displaying identical numbers once you reach the end of a list. In the images, there are two instances of the number 13. I'm unsure if this is expected behavior or a bug.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2277?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
