### ISSUE TITLE
Font Awesome icon `fa-phone-alt` is not displaying

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2280]
## Description

On design.va.gov, the phone alt icon is not displaying:

https://design.va.gov/foundation/icons#feedback

![Screenshot 2023-11-28 at 3 20 47 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/6f46a5ff-5253-46c0-8d83-f0657d893827)

Based on waybackmachine, it was displaying like this:

![Screenshot 2023-11-28 at 3 07 47 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/ed90342f-3e18-4169-9137-243323870ec7)

## Tasks
- [ ] Figure out why the icon is no longer displaying and fix it.

## Acceptance Criteria
- [ ] The phone alt icon is displaying again

**Comment by jamigibbs** [comment]
From this [Slack convo](https://dsva.slack.com/archives/G01BJ3ESXL4/p1701269946156369) via Matt:

> I'm pretty sure we do use v5.15.4. The package.json just indicates the minimum version (my understanding is that is what that leading carrot means). But we could/should update it to be v5.15.4.

**Comment by caw310** [comment]
Added to sprint as unplanned work.
