### ISSUE TITLE
Formation Deprecation - Update primary blue colors in Component Library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2292]
## Description 
We currently have a [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26724) out that updates all of the primary blue colors in vets-website to re-align with USWDS3. In order to reduce the amount of color discrepancy between global changes and what is in our design system components, we will update our primary blues in component library and then update the versions of Formation and component library simultaneously in vets-website. 

## Considerations
- Related ticket - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2228
- [Comment with most up to date color diff](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2228#issuecomment-1806161655)

## Tasks
- [ ] Update all primary blue colors in component library 

## Acceptance Criteria
- [ ] Above tasks have been complete

**Comment by micahchiang** [comment]
PR here - https://github.com/department-of-veterans-affairs/component-library/pull/974

**Comment by caw310** [comment]
This was added to the sprint and will go into the next sprint to push release for the global blue color change.
