### ISSUE TITLE
Discovery: Test of release-please in component-library

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/vets-design-system-documentation#2293]
### Description
As a follow up to the results from [Publishing multiple packages from the component-library discovery ticket](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1954), we need to test `release-please` in more real world conditions to catch any possible issues that may arise its implementation in our repo. 

### Discovery findings
[Discovery: Publishing multiple packages from the component-library
](https://vfs.atlassian.net/wiki/spaces/~96033397/pages/2840100872/Discovery+Publishing+multiple+packages+from+the+component-library)

### Actions
- [x] discuss to see that these test will not interfere with the normal operation of component-library and its release cycle
- [x] Installation of `release-please` on a test branch(?)-- 
- [x] independent release of (individual) library packages (mock?)
- [x] independent release of a core package (mock?)
- [x] can we wire the action to publish  to NPMjs concurrently with merge of Release PR, for BOTH the use cases  above?, 
- [x] does it negate the use of Verdaccio?
- [x] Note any other difficulties that arise

### Results
Assuming all/most actions are successful, a PR to to incorporate `release-please` into `component-library`; 
else suggestions for an alternative course

**Comment by rmessina1010** [comment]
Concern: because the bulk f this test run is working with GHA local testing is not possible;  
extra care must be taken not to affect actual current work flow ( do not merge PR!!)

**Comment by rmessina1010** [comment]
Hit on a couple of issues:
1. **Tokens:** `release-please-action` requires a  personal or organizational  access token to run. However, despite creating both classic and fine grained tokens in my personal GH, I could not get  the action to recognize either one; `err: token not provided`, my guess being that either the action or  `department-of-veterans-affairs` does not allow for the use of our personal accounts as the source of  PATs;  I think that we `need` to  create  the token in `department-of-veterans-affairs`, but i don't have privileges to do that and test the assumption.  **As a workaround**, I copied the value of my PAT and assign it to a repo secret of `component-library`; while  this succeeded in getting the action to run it is a les than optimal solution, to say the least.
2. After getting the script to run,  targeting a separate test branch; `rm-relese-please-exp` instead of `main` I did not receive the expected results. The bot did create the chore PR, but: the instead of only bumping up  `css-library` as expected-- `css-library`, `web-components`, and `core` (component-library). were affected.  The commit messages  do not match my test commit messages either.

**Comment by rmessina1010** [comment]
I got the plug in running, with the caveats above; The version  discrepancy doesn't seem to be related to  synching with `main`; looking  into imports.


This will need to carry over till next sprint;

**Comment by rmessina1010** [comment]
### Conclusion:
#### Access tokens
` release-please-action` requires a double work around for  it to work with the `component-library` repo; first a  team member must make a personal access token in their personal account,  then the value of said access token must  be copied to the appropriate secrets field in the the `component-library` repo.  This means that only one team member is responsible  for creating and MANUALLY maintaining this secret.

#### Configuration issues/resolutions:
for the this test! I had to configure 
`on:
  push:
    branches:
      - rm-release-please-exp4`

and
`jobs:
...
          default-branch: rm-release-please-exp4`

to target the experimental `rm-release-please-exp4` branch.  But if we remove the configuration in the `jobs` field and change add  or change branches to main `release-please` should work with our main branch on push ( or we could change the trigger to 'on merge' as needed.

It's important to note that a `bootstrap` or `last-release` field ( depending if this the FIRST time running the branch)  must be added to `release-please-config.json`
example:
`    "bootstrap-sha": "8e9695af82024c13ebfa46b305d7d11a1066a32c",
    "last-release-sha": "8e9695af82024c13ebfa46b305d7d11a1066a32c",
`
The reason for this is that `release-please` searches through the ENTIRE commit history by default, looking for conventional commits, if no specific `sha` is given. As our repo has  instances of commits using conventional commits, this WILL confuse release please when selecting a version # and history.

Release please cannot work directly with Versaccio,  so work arounds will be needed for local development
Release please does not publish to NPM by default , an additional  script will be required. Tho I feel this gives us a chance to refine control ...as  releases will be based on commits/pushes to the MAIN branch ( not feature branches themselves)

**Comment by micahchiang** [comment]
Thank you @rmessina1010 and @it-harrison for looking into this. I think there are several compelling things about release-please and the granular control it gives us over our packages and their release management, though I'm also a little leery of the complexity it adds to our process. 

Given how much stuff is on our roadmap currently, I think the play here is to keep this research in our back pocket, and potentially revisit it when we have some breathing room. I still see significant value in improving our release process, but not necessarily at the cost of impacting our current velocity. 

Thanks again for the thorough investigation!
