### ISSUE TITLE
Switch Sketch links to Figma for all components

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2301]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

All components

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

All links to Sketch will now switch to Figma

**Comment by humancompanion-usds** [comment]
I need the Example library for this.

**Comment by humancompanion-usds** [comment]
@caw310 and @danbrady - Let's discuss in our chat tomorrow how we are progressing with the Example library and how I can tell which components are safe to link to. Perhaps we bring back the dots for this one?

**Comment by danbrady** [comment]
@humancompanion-usds I went through all the Sketch links in each component on the doc site to see where they are pointing to. About half link to the Example Library while the other half link to Pattern Library (and a few have no links, link to Figma already, or have an error). Both libraries have a lot of overlap with each other, however, oftentimes an example might be in one but not the other. What's the best way to sort through this so we don't repeat mistakes or cause confusion? I can think of a couple different options:

1. Follow one of the libraries. Which ever is newer or most recently maintained? (Both have recent Last Modified dates so I'm not sure which one it would be.)
2. Combine examples from both (The "union" of the two.) But I'm not sure if there's old/outdated examples in there.
3. Follow whatever library the component links to on the docs site. 
4. Other ideas...?


Below is the list of what components are currently linked to:


#### Links to Example Library
* Breadcrumbs
* Button
 * Button
 * Button Pair
* Divider
* Form
  * Checkbox
  * Memorable Date
  * Number Input
  * Privacy Agreement
  * Progress Bar - Segmented
  * Radio Button
  * Select
  * Text Input
  * Textarea
* Header
 * Header
 * Minimal
* Modal
* Pagination
* Process List



#### Links to Pattern Library
* Address Block
* Alert - Expandible
* Back to Top
* Banner 
  * Maintenance
  * Official Gov
  * Promo
* Card
* Featured Content
* Form
  * Date Input
  * File Input 
  * Need help?
  * Penalty Notice
  * Prefill
* Link 
 * Link
 * Action
 * Collection
* Loading Indicator
* Notification (deprecated)
* OMB Info 
* On this page
* Progress bar - Activity
* Search Input
* Sidenav
* Table
* Tag
* Telephone



#### Links to Figma
* Footer 
  * Footer
  * Minimal


#### No Link
* Banner 
  * Banner
* Language toggle (New)  
* Link 
 * Deep Content (deprecated)
* Tabs (New)
* Form
  * Input Message
  * Label
  * Statement of Truth


#### Links to Error
* Form
  * Autosave (Links to a non-existing page in Templates Library.)

**Comment by humancompanion-usds** [comment]
Oof. Well, they should have all been updated at some point to point to the components in Example Library. Seems like what happened is we never went back to update the links from Pattern Library to Example Library for the non-USWDS v3 components. That was an oversight.

The ones that have no link make some sense. It's a combination of either a new component (statement of truth is also new) or deprecated (Input message is also going to be deprecated). 

Example library is more recent and so I would work from there. Pattern library is very much in the rear view mirror. Don't worry about examples in there.
