### ISSUE TITLE
[COGNITION]: Sortable Table - Buttons MUST look like clickable UI elements

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#231]
@1Copenut commented on [Mon May 18 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9193)

# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️  Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Our [sortable table component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/sortabletable/) has clickable `<th>` elements that do not look like any of our styled `<button>` elements. I didn't know these were clickable. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Sortable table header buttons look clickable
- [ ] Clickable button design is stable across all media breakpoints and zooms to 400% cleanly
- [ ] Create and/or modify unit tests for this component to include an aXe scan

## Environment

* https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/sortabletable/

## WCAG or Vendor Guidance (optional)

* [Use of Color: Understanding SC 1.4.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html)

## Screenshots or Trace Logs

![Screen Shot 2020-05-18 at 10 13 43 AM](https://user-images.githubusercontent.com/934879/82230375-44617780-98f1-11ea-9e51-ccfc50e55dbe.png)

**Comment by holdenhinkle** [comment]
@1Copenut 

One last question if you're around!

Here's a screenshot of the updated Table component that supports sorting ([PR](https://github.com/department-of-veterans-affairs/component-library/pull/160)). Does the design still need updating or is it pretty clear that the row can be sorted now?

![image](https://user-images.githubusercontent.com/9326247/132919375-0c78aa07-ef49-4ce8-ba07-a5bebe76e130.png)

**Comment by holdenhinkle** [comment]
@pjhill I think the arrow that signifies ASC/DESC in the sortable column is all we need to communicate that it's a clickable element. I could make it underlined to make it 100% clear but I think the arrows suffice.

What do you think?

**Comment by GnatalieH** [comment]
@pjhill I think the caret/arrow is sufficient to communicate the column is sortable, unless you want to underline the cell label (Year in this case). I would move the sort caret to the right of the label, however, so that all of the text on the table header row is on the same baseline. CC @holdenhinkle.

**Comment by holdenhinkle** [comment]
@GnatalieH provided feedback in [this ticket](https://github.com/department-of-veterans-affairs/component-library/pull/160) which is applicable here (use USWDS arrows).

The arrows have been swapped out:
![image](https://user-images.githubusercontent.com/9326247/133521544-55f39a1d-28b7-4835-9b09-3567d7777faa.png)

This ticket is complete

**Comment by humancompanion-usds** [comment]
This still works in the web-component version of Table:
https://design.va.gov/storybook/?path=/docs/components-va-table--default
