### ISSUE TITLE
[Bug] Active action link background

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#2321]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When a primary (green) or secondary (blue) action link is active (click and hold mouse on link), the background is changed to dark blue (#0b4778) making the link temporarily unreadable.

```css
a:active {
    background: #0b4778;
}
```

<img width="1142" alt="active action link with completely blue background" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/76fdacf2-50a5-4a12-9aef-e637d768a263">

## What I expected to happen

Active action link should still be readable

## Reproducing
- Formation version: Any
- Device: (e.g. iPhone 8, Macbook) Any
- Browser: (e.g. Firefox, IE 11) Any

Steps to reproduce:

1. Go to [action link in storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--primary)
2. Click and hold on the primary or secondary action link
3. Note the background color change

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2321?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
