### ISSUE TITLE
Formation Deprecation - Audit and migrate breakpoints from Formation to CSS Library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2334]
## Description
Breakpoints need to be migrated from Formation to CSS Library. 

## Considerations
- breakpoints file in formation - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/66f36cb8920fd43cdf35093f3c9f5a09c6e1da87/packages/formation/sass/base/_b-breakpoints.scss#L17
- breakpoints.json file added to css-library - https://github.com/department-of-veterans-affairs/component-library/pull/982/files#diff-91ed3fa5fd45ae2902c23063c3de166002b1ecee6ad1e5edfef2bb281388e7b0R1
- Update the 768px breakpoint to 640px per guidance on https://vfs.atlassian.net/wiki/spaces/DST/pages/2731245815/DR001+VA+Design+System+v3+upgrade+rollout+steps
- Breakpoint variables are used extensively throughout Formation so simply removing them isn't tenable. 

## Tasks
- [ ] Add breakpoints to CSS Library in the json file mentioned above

## Acceptance Criteria
- [ ] Breakpoints have been added to CSS Library

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2334?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
