### ISSUE TITLE
Formation Deprecation - Identify all utility classes that can potentially be replaced with a web component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2340]
## Description 
A [recent pull request](https://github.com/department-of-veterans-affairs/component-library/pull/981) uncovered two instances where Formation utility classes (.feature and .card) could potentially be replaced with existing web components. In situations where this is possible we should aim to replace utility classes instead of migrating them into CSS Library. The objective of this ticket is to audit vets-website and content-build for css utility classes that can be directly replaced by existing web components. 

## Considerations 
- .feature and .card are already accounted for in #2337 and #2338

## Tasks
- [ ] audit vets-website and content build for utility classes that may directly be replaced with web components
- [ ] List all utility classes that meet this criteria as a comment on this ticket

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2340?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Confluence doc with some findings: https://vfs.atlassian.net/wiki/spaces/DST/pages/3005710374/Formation+Deprecation+Identify+ways+to+deprecate+utility+classes+and+other+styles

**Comment by jamigibbs** [comment]
I've presented the info to the engineering team and handed off those details to @micahchiang 🫡
