### ISSUE TITLE
Formation Deprecation - Add CSS rules directly to content-build

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2341]
## Description 
A [recent pull request](https://github.com/department-of-veterans-affairs/component-library/pull/981) revealed there are a couple of css classes in Formation that are only being used the content-build repository. In an effort to reduce the amount of global imports, we should attempt to load these classes directly into the content-build repository instead of migrating them over to CSS Library. 

## Considerations 
- [va-nav-breadcrumbs--playbook](https://github.com/department-of-veterans-affairs/component-library/pull/981#discussion_r1423151736) instance
- [va-quicklinks](https://github.com/department-of-veterans-affairs/component-library/pull/981#discussion_r1423119421) instance

## Tasks
- [ ] add the above two instances directly to the content-build repository
- [ ] Remove instances from Formation

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 3
@ataker - 
@harshil1793 -  3
@it-harrison - 3
@jamigibbs - 3
@micahchiang - 3
@powellkerry -
@rmessina1010 -
@rsmithadhoc - 2

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2341?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
