### ISSUE TITLE
[accessibility-defect-2] Hint text not being announced by screen readers

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2342]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

During [accessibility testing for form 20-10206](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71634), I discovered the checkbox group is placing the hint text outside of the legend, without any `aria` attributes, so it is not being announced by screen readers. 

I can also [duplicate this in storybook.](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default#with-hint-text)

The [same is true for radio group](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--default#hint).

## What I expected to happen

I expected the hint text to be located within the legend.

The [text-input component](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--with-hint-text), and [text-area component](https://design.va.gov/storybook/?path=/docs/uswds-va-textarea--with-hint-text) places the hint text within the label so it is read out by screen readers in that case. The experiences should match

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook) macbook pro with voiceover
- Browser: (e.g. Firefox, IE 11) chrome, firefox, safari

Steps to reproduce:
1. Enable voiceover or another screen reader
2. Go to the [Checkbox group in storybook](https://design.va.gov/storybook/iframe.html?id=uswds-va-checkbox-group--with-hint-text&viewMode=story)
3. Navigate into the checkbox group. 
4. You will never hear the hint text announced.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work - but it will get flagged for us in any upcoming staging reviews.
- [ ] Other

### Details
These are other related hint text related tickets I could find that are still open:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1726
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1693
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2104
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2164

### References, articles, or WCAG support

This almost falls under VA.gov Experience Standard 09.05 (Visual labels aren't included in the accessible label), which would be a launch-blocking issue. But since it's helper text and not the label itself. Logging it as other/not launch blocking. (Following other guidance from @briandeconinck )

- [WCAG SC 2.5.3_A](https://www.w3.org/WAI/WCAG21/quickref/#label-in-name)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2342?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
