### ISSUE TITLE
va-alert component - uswds (v3) defects

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/vets-design-system-documentation#2354]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.
- A related observations about the visible difference between the background color of the full with and the box containing the content is addressed in [#2339 Fix Alert Colors](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2339)

## What happened
When implementing va-alert component - uswds (v3) with the closeable attribute
- plus full-width="true" breaks the component: the close icon moves to below the component
- with full-width="true" (non-uswds), it does not expand to full width
- without full-width (non-uswds) the context expands to the whole screen but has no margins

## What I expected to happen

- If  full-width="true", the alert will be full width
- If  full-width="true", the x dismiss icon will retain intended styling
- Appropriate margins should be maintained 

## Reproducing

Steps to reproduce:

1. View https://design.va.gov/storybook/?path=/docs/uswds-va-alert
2. Set to closeable
3. Set full width=true

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work _(we realized we should be using va-banner instead even without a v3 component but wanted to report these observations)_
- [ ] Other

### Details
- Please contact @eselkin with questions

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2354?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
[PR is up](https://github.com/department-of-veterans-affairs/component-library/pull/1033)
