### ISSUE TITLE
Update the Autosave and Pre-fill to use v3 Alert component  - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2360]
## Description
Update the Autosave and Pre-fill to use v3 Alert component documentation and guidance on design.va.gov. 

## Details
Autosave - https://design.va.gov/components/form/autosave
Pre-fill - https://design.va.gov/components/form/prefill 

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by humancompanion-usds** [comment]
@danbrady - I tried to update the Autosave component in the component library. But I'm not sure I did it correctly and don't want to go farther with documentation until you confirm. Can we review it tomorrow in our design weekly chat? Thanks.

**Comment by danbrady** [comment]
This looks good to me. I am able to see the Alert component being used in these components. I can also see that it was published and available. So I think we can close this. But Matt, let me know if you have questions.
