### ISSUE TITLE
Experimental Design: Apple App Store and Google Play Store Icons

### ISSUE THREAD

**Issue by hasahmed2** [department-of-veterans-affairs/vets-design-system-documentation#2369]
## What
> Give a brief description of the component or pattern you want to propose.

Google Play and App store icons

https://fontawesome.com/v5/icons/app-store-ios?f=brands&s=solid

https://fontawesome.com/v5/icons/google-play?f=brands&s=solid

## Purpose
> What problem does this component or pattern solve for the user?

Provides visual support for link action
## Usage
> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.

The icon will be displayed when users are shown a text link or button to download the VA app from the app store.
## Behavior
> Describe the key interactions for this component, calling out any specific considerations for mobile.

N/A -- Visual only, no hover or click actions 

## Examples
> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.
<img width="690" alt="Screenshot 2024-01-08 at 11 03 16 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/148818278/6e932221-35c3-4080-822e-b561ff063b4f">

## Accessibility
> Include any accessibility considerations.

N/A

## Guidance
> What would you want to tell other teams about this component or pattern?

N/A

## Research (optional)
> Include any research you have already conducted, or plan to conduct, on this component or pattern.

N/A
## Code (optional)
> Include any existing code.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
We decided to add these icons. We'll tackle this when we get to moving to USWDS iconography in our roadmap.
