### ISSUE TITLE
[Alert] - Remove background-only prop from Alert in Storybook 

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2371]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Somewhere along the way we got confused in our Alert implementation. The Slim variation of Alert REPLACES background-only. Thus background-only should have been removed as an option in both the va-alert component and in Figma. 

## What I expected to happen

User of the Design System can either have a standard Alert or a Slim alert. They cannot have a standard alert with no border and a different colored icon. We are not aligned with USWDS v3 here.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Got to Storybook, or Figma, toggle on the background-only prop
2. Get an Alert style that is NOT in USWDS v3.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

While it isn't blocking work, it allows designers to design using an invalid Alert variation that we are trying to deprecate.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2371?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc @danbrady @LWWright7

**Comment by micahchiang** [comment]
Potentially 92 usages of the `background-only` prop in vets-website that may be impacted by removing this: 
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/15097156/87c41dd8-a37d-4449-b0b0-15d53480a805)

**Comment by danbrady** [comment]
FYI: Splitting the designer tasks out from this ticket into a [new ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2394) as it's effort is significantly lower than the engineering effort.

**Comment by Andrew565** [comment]
Double-checked and it looks like I already fixed how the slim styles are calculated, so disregard any previous comments about that issue.

**Comment by powellkerry** [comment]
Results of a global search for `background-only` and `uswds`:
- src/applications/financial-status-report/containers/IntroductionPage.jsx:121
- src/applications/personalization/profile/components/alerts/LoadFail.jsx:58

The proposed changes would not remove the prop, just ignore it, and would not cause errors. The only changes would be visual with the addition of the left border. The headline would also be visible, but neither of the instances in vets-website pass that to the component.

All other instances of `background-only` use the v1 version which will continue to support the prop.
