### ISSUE TITLE
Update Button status in Storybook

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2372]
## Description
The status for USWDS v3 Button component is out of sync with the status on design.va.gov. The correct status is  Use Deployed.  Update Button status in Storybook to "Use Deployed".

## Details
design.va.gov: https://design.va.gov/components/button/ (this has the correct status) 
Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary - needs to be updated

## Tasks
- [ ] Update status in Storybook of the USWDS v3 Button component to Use Deployed

## Acceptance Criteria
- [ ] USWDS v3 Button status in Storybook is "Use Deployed"

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2372?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by humancompanion-usds** [comment]
This has been done.
