### ISSUE TITLE
Add "Do Not Use" label to UWSDS v3 Icon component in Storybook 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2374]
## Description
Add label to UWSDS v3 Icon component in Storybook to Do Not Use

## Details
Storybook link - https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default

## Tasks
- [ ] Add "Do Not Use" label to UWSDS v3 Icon component in Storybook 

## Acceptance Criteria
- [ ] UWSDS Icon component in Storybook has "Do Not Use' Label

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2374?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by humancompanion-usds** [comment]
Let's not do this and instead get va-icon guidance out there for teams to start making the transition.
