### ISSUE TITLE
The `submit` prop does not work for `va-button`

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2379]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The `submit` prop in `va-button` does not seem to work as I would expect it:

```html
<form name="myForm" onSubmit={handleSubmit}>

  [...other form inputs...]

  <va-button
    submit
    text="Submit form"
  />
</form>
```

https://design.va.gov/storybook/?path=/docs/components-va-button--primary

## What I expected to happen

I would expect that if the `submit` prop was present, the button will natively submit the form based on this documentation:

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Wrap `va-button` around a `form` element and add an `onSubmit` callback
2. Observe that there is no submit event received by the form's callback function 
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work and there is a workaround
- [ ] Other

### Details

It would be nice if we could get this to work natively with the web component since internally it's just a `button` element. But if we can not for whatever reason, the `onClick` event can be used to programmatically submit a form. If that's the case, then we should probably just remove the `submit` prop completely.

```html

handleSubmit = (event) => {
  event.preventDefault();
  document.myForm.submit();
}

<va-button text="Submit form" onClick={(event) => handleSubmit(event)} />
```

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2379?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
For more info, see this ticket. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2734

**Comment by rmessina1010** [comment]
Closing ticket:
* Pending review
* Button will now send data on submit.
* Creating separate tickets for: unit tests/updating usage docs.
