### ISSUE TITLE
Loading indicator component audit

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#238]
### Description: 
Loading indicators are used to indicate that the user’s action is being processed

Loading indicators in the sketch library, design.va.gov, and react library are out of sync.

You can view the component in [design.va.gov](https://design.va.gov/components/loading-indicators) and in [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/loadingindicator/)

### These are the ways this component is not synced

- The sketch library has an outdated version that's a different color and says vets.gov. 
- The react component on the developer website looks buggy and doesn’t use the same language in prod/design.va.gov “Loading your application…”
-  The prod/design.va.gov loading indicator says, “Please wait while we load the application for you.”
- The react library and design.va.gov called the component a loading indicator. The sketch library calls its "Progress spinner (indeterminate)"

### Complete the following tasks to synchronize component:
**Sketch library:** 
- Update the component named "Progress spinner (indeterminate)" that's in the "8-feedback" artboard underneath the "progress indicators" section, replace it with the new VA.gov design [here](https://design.va.gov/components/loading-indicators)  
- Rename the Sketch Library component "Loading indicator" to match the react library and design.va.gov. Make it into a symbol "Global component / progress indicators / loading indicator

**React library:** 
- Fix this component to match the loading indicator's design in [design.va.gov](https://design.va.gov/components/loading-indicators) and replace the text with "Please wait while we load the application for you."

**Design.va.gov:** 
- Add documentation on how to use loading indicator, draft documentation can be found [here](https://docs.google.com/document/d/13eygQrZaVZKxA_uvnkaoT2YlDTsTHbjKBGD1UkUlJz0/edit?usp=sharing)

**Comment by kristenmcconnell** [comment]
> Fix this component to match the loading indicator's design in design.va.gov and replace the text with "Please wait while we load the application for you."

Can we make "application" variable? With all the tools we have now, not everything is an application.

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
