### ISSUE TITLE
Add missing icons for texting/mobile device and external link

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2381]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

We use a mobile device icon in the Crisis Line Modal but it is not part of our icon set. We need to add it to Figma as well as update guidance on usage.

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/eb191cc0-86b7-480e-be61-eefd9dc73928)

[Example and code](https://fontawesome.com/v5/icons/mobile-alt?f=classic&s=solid) can be found here on the FA5. 

 

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by danbrady** [comment]
We'll need to bring this one in too:
<img width="91" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/6b03e379-88c6-4366-bda7-f77fc37a6f58">

**Comment by caw310** [comment]
This ticket will include work for: 
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2573
-  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2624
-  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2369
