### ISSUE TITLE
Experimental Design - Add option to process list for a link heading

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#2383]
## What
Could there be a variation added to the heading for a process list step, where the heading is a link? 

## Purpose
Reduces content and repetition on the page while drawing attention to the call to action for a step.

## Usage and Examples
On the profile account security page, the process list steps headings are links:
<img width="283" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/55992116/d58f3f28-1010-46ce-832e-18dac2b7a722">

I wasn't the designer for this but believe this approach was taken, rather than have links within the step description, to reduce repetition on the page.

## Behavior
This would behave like a normal link.

## Accessibility
Afaik, having headings contain links don't present any accessibility concerns.

## Guidance
This approach is useful when you want to minimize content and have calls to action be scannable.

**Comment by caw310** [comment]
@andaleliz This is on the agenda for the Jan 19 DSC meeting at 1pm ET. I've added you to the meeting invite.

**Comment by andaleliz** [comment]
@briandeconinck following up with you on this - did anyone ever bring this to your attention? I see no one is assigned and I wonder if it fell off the radar.

**Comment by briandeconinck** [comment]
I don't recall anyone bringing this up with me, but it looks like @rsmithadhoc looked at it in #2411. I agree with his assessment here --- in general I think my preference would be to not have links in headings, but it's not a terrible pattern so long as the content of the heading-link is clear. The bigger concern is probably what Ryan raised in that ticket, which is whether we're okay deviating from USWDS on this.

**Comment by andaleliz** [comment]
@briandeconinck oh, I didn't know #2411 was a ticket - thank you for calling that out! In the review they said we needed to talk to you about it.  I think that it's probably best if we _don't_ deviate from USWDS and instead see if we can try to explore some content options where headings aren't exactly duplicative of links (which is what drove us to get rid of body links and instead use heading links).  Good to know the current state is not an explicit a11y violation, but I think we can improve on this.  Thanks!

**Comment by andaleliz** [comment]
PS I'll repoen this if for some reason we need to try again for this to be updated in the DS
