### ISSUE TITLE
Update the design system template screens for intro page

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#2385]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Other

### What is the name?

Form intro pages

### What is the nature of this update?

- [X] How to build this component/pattern
- [X] When to use this component/pattern
- [X] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

The [intro pages for forms for applications](https://design.va.gov/templates/forms/introduction#example---application) has recently changed [per the discussion with Danielle Theirry](https://dsva.slack.com/archives/C01K37HRUAH/p1704830073838369). We need to update the screens for both unauth and auth. [The Supplemental Claim form](https://www.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/introduction) uses the updated pattern for applications. I am attaching the unauth screen but it needs to have some things added to it.

It may also be good to add some additional guidance around when to use application vs non-app. Here is something Matt Dingee wrote:

- Application: The application template is intended for introduction pages that start an application for a benefit or service.
- Non-application: The non-application template is intended for introduction pages that start a standard form flow. In other words, an online form that is not for an application for a benefit or service. Typically these are for ancillary forms related to a benefit or service.
- 
![screencapture-va-gov-decision-reviews-supplemental-claim-file-supplemental-claim-form-20-0995-introduction-2024-01-09-15_06_05](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/72398073/9e58cd28-a90d-487a-ab8a-584f9bfb7a39)

**Comment by humancompanion-usds** [comment]
@LWWright7 and @danbrady - While you are building the Introduction template in Figma can you incorporate these changes? Essentially, the template changes to only have the "Sign in..." Alert - Info at the bottom of the page instead of the top. Allison has provided an example above. Thanks!

**Comment by humancompanion-usds** [comment]
@danbrady - I think you're handling this in the current sprint, yes? If so, can you pull this issue into the current sprint? Thanks.
