### ISSUE TITLE
Figma rebuild: Templates - Email

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2388]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/email

**Comment by LWWright7** [comment]
https://design.va.gov/templates/email

**Comment by caw310** [comment]
Added to sprint 44 as unplanned.

**Comment by LWWright7** [comment]
Ready for [review](https://www.figma.com/file/Kc1mPdc5AB02niOF0pKrOO/VADS-Templates?type=design&node-id=195%3A1860&mode=design&t=qmfKVeyvuPyjZHVi-1)!
