### ISSUE TITLE
Figma rebuild: Templates - Hub

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2389]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/hub

**Comment by LWWright7** [comment]
https://design.va.gov/templates/hub

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2389?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by danbrady** [comment]
I'm guessing we'll need a mobile template as well (even though it's not shown in guidance)?

**Comment by LWWright7** [comment]
Good call @danbrady !

**Comment by LWWright7** [comment]
This will carry over. It was pulled in and not planned for this last sprint.

**Comment by LWWright7** [comment]
@danbrady - This is ready for [review](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates---SANDBOX-USE-WITH-CAUTION?type=design&node-id=2607%3A31366&mode=design&t=xPxUdGHNw3NCxXgO-1)!

**Comment by LWWright7** [comment]
@danbrady Ready for [review](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?type=design&node-id=2607%3A31366&mode=design&t=P4dcX78QHRmIPvTZ-1)!!
