### ISSUE TITLE
[Alert] - Remove background-only prop from Alert In Figma

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2394]
## What happened

Splitting the design tasks from #2371 into this new ticket because the effort for design changes is significantly lower than the engineering changes.   

> ## What happened
> Somewhere along the way we got confused in our Alert implementation. The Slim variation of Alert REPLACES background-only. Thus background-only should have been removed as an option in both the va-alert component and in Figma.
> 
> ## What I expected to happen
> User of the Design System can either have a standard Alert or a Slim alert. They cannot have a standard alert with no border and a different colored icon. We are not aligned with USWDS v3 here.
> 
> ## Reproducing
> * Formation version:
> * Device: (e.g. iPhone 8, Macbook)
> * Browser: (e.g. Firefox, IE 11)
> 
> Steps to reproduce:
> 
> 1. Got to Storybook, or Figma, toggle on the background-only prop
> 2. Get an Alert style that is NOT in USWDS v3.
> 
> ## Urgency
> How urgent is this request? Please select the approriate option below and/or provide details
> 
> * [ ]  This bug is blocking work currently in progress
> * [ ]  This bug is affecting work currently in progress but we have a workaround
> * [ ]  This bug is blocking work planned within the next few sprints
> * [x]  This bug is not blocking any work
> * [ ]  Other
> 
> ### Details
> While it isn't blocking work, it allows designers to design using an invalid Alert variation that we are trying to deprecate.

**Comment by LWWright7** [comment]
@danbrady @babsdenney - This one is ready for review in Figma. Thanks!

**Comment by LWWright7** [comment]
@danbrady @babsdenney this one really has me stumped.  I can't, for the life of me, figure this one out.  I click on "select conflicting variants" and it selects ALL 120 variants! Any help here would be greatly appreciated! :)

**Comment by danbrady** [comment]
Aha, I figured it out. So every Alert has a variant where all properties are the same EXCEPT "Background Only" (true or false) being the only difference between them. When we delete the "Background Only" property from the main component, those variants are now exactly the same, hence the warning about conflicting variants. The fix I did is to remove all of those "Background only = true" variants. 🪄

**Comment by LWWright7** [comment]
Thanks @danbrady !!!!  You're a genius!
