### ISSUE TITLE
Document Military Addresses in Ask users for addresses pattern

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2395]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Pattern

### What is the name?

Ask users for addresses

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

PO/FPO/DPO and AA/AE/AP fields are not clearly defined in this pattern. We want teams to follow this form pattern: https://staging.va.gov/mock-form-patterns/mailing-address

### Additional Context

This came up recently in Slack: https://dsva.slack.com/archives/C0NGDDXME/p1705006679089739

**Comment by andaleliz** [comment]
We currently disable the country select input when someone checks the "I live on a military base.." checkbox. Before I open a ticket for our team, I want to confirm [this pattern](https://staging.va.gov/mock-form-patterns/mailing-address) reflects the forthcoming guidance, and instead we should display `United States` outside of a form input, and include an additional info component. Is that right?

**Comment by humancompanion-usds** [comment]
@andaleliz - Yes, that pattern reflects the forthcoming guidance. It changes the following:

* Rather than disabling the Country select, we replace it with the text United States. This was deemed to be more accessible (the guidance will detail why).
* The City field changes to a APO/FPO/DPO select menu.

The additional info component "Learn more about military base addresses" is there throughout. The contents state:
> The United States is automatically chosen as your country if you live on a military base outside of the country.

I'm not sure if we have research that backs up needing that content there. I need to track that down.

**Comment by andaleliz** [comment]
Hi @humancompanion-usds it looks like [there's an example on the address page now](https://design.va.gov/patterns/ask-users-for/addresses#military-base-address); is further guidance coming? We need to update our address form in the profile to align with that example and I want to make sure I'm not missing anything major before I mark it was ready for development. The example seems straightforward to me.

**Comment by humancompanion-usds** [comment]
@andaleliz - No, no further guidance. I'm going to close this. Just using it was a reminder to remove the first example here which is duplicative and out of date.
