### ISSUE TITLE
Formation Deprecation - Compile list of tests incompatible with v3 components in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2399]
## Description
On February 16 the design system team will default all components to v3, making it an opt out feature. This will likely cause tests to break. In an effort to prepare for this and go through a release with minimal roadblocks, we need to compile a list of tests that may fail when the change goes into effect. Once we have a list, we will go to VFS teams and ask them to address these in preparation for the release. 

## Considerations
- Compiling a list of failing tests could involve doing some sort of pre-release PR into vets-website

## Tasks
- [ ] Compile a list of unit tests and e2e tests that may fail on v3 component usage
- [ ] add the list to this ticket as a comment, organized by vets-website application

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2399?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Work on this has started in sprint 45.

**Comment by caw310** [comment]
Closing as work in this ticket will be done in 2405 https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2405
