### ISSUE TITLE
Add grey background to va-card

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2403]
## Description
In order to deprecate the `.card` class in [2337](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2337) we need to add a prop to va-card that adds support for a grey background. 

## Tasks
- [ ] Add prop to va-card for grey background

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by danbrady** [comment]
FYI: The gray background color is `vads-color-gray-lightest`.

**Comment by jamigibbs** [comment]
The decision to add a `gray` prop to va-card came from this Slack discussion here: https://dsva.slack.com/archives/G01BJ3ESXL4/p1705592968640789?thread_ts=1705592507.978689&cid=G01BJ3ESXL4
