### ISSUE TITLE
Update content style guide for Title tags

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/vets-design-system-documentation#2415]
## What
When forms use the minimum header design, the question for each page in the form (like "Are you a Veteran?") becomes the h1. Right now, our guidance suggests that we pull this in for the title tag (like "Are you a Veteran? | Veterans Affairs") A11y, IA, and content folks propose that for forms (or anywhere we use the minimum header design), we use a title tag that follows the pattern of [title] | Veterans Affairs instead of the current guidance of [h1] | Veterans Affairs.

## Purpose
If a general form question is in the title tag, it's less meaningful. I.e.: "Are You a Veteran? | Veterans Affairs" vs "File For Disability | Veterans Affairs"

## Usage
Wherever the h1 is not a descriptive name for the tool or form, we should consider using the title for the title tag instead of the h1. 

## Accessibility
If someone is filling out 2 or 3 forms and each form is in its own window, the person may be alt + tabbing between them. If a screen reader is calling the names out, it would say "[Question] | Veterans Affairs” — and the person wouldn’t be able to tell the forms apart.

## Guidance
The title tag should use the same title as the form name throughout the full form. 

## Code (optional)
> Include any existing code.

## Next steps
Asynchronous approval would be great. But we can attend if there are any questions or suggestions for how to approach this issue. @jennymayoco and @kristinoletmuskat have been involved in this discussion, so they can help answer any follow-up questions. 

-----

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
Carol and I discussed this one this morning. We think this is just a guidance clarification. I don't think anyone intended for the title to remain the question in the H1. Or at least I don't think anyone is advocating for that. The Forms team is working on templatizing One thing per Page patterns which I'll put in the design system. When I do that I'll also add this guidance. But I would appreciate a draft of the guidance, which is mostly here already, if you have the time to do that.

**Comment by megzehn** [comment]
Great! Thanks, Matt! @jennymayoco are you able to provide a draft for @humancompanion-usds?

**Comment by kristinoletmuskat** [comment]
Here's a [draft of proposed changes](https://docs.google.com/document/d/1EA9iEw1mCE8P7-JxEwX5r7yFnz1xxyG-dCviPoh_oSA/edit), but we still need to sync on this internally on the CAIA side!

**Comment by kristinoletmuskat** [comment]
Hey @humancompanion-usds, we aligned internally and that doc is up to date with our proposed changes. lmk if you want to chat through it! Happy to jump on a call.

**Comment by humancompanion-usds** [comment]
@kristinoletmuskat - Requested access to the doc.

**Comment by kristinoletmuskat** [comment]
You should have access now!

**Comment by kristinoletmuskat** [comment]
[Title Tag Design System Guidance.docx](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/14213614/Title.Tag.Design.System.Guidance.docx)
 Here's a word version

**Comment by kristinoletmuskat** [comment]
Hey @humancompanion-usds , I wanted to see if you had a chance to pull these changes to Title Tag guidance in. We're working on IA documentation and I wanted to see the status of this.

**Comment by humancompanion-usds** [comment]
@kristinoletmuskat - Sorry, I generally don't touch the Content Style Guide. I missed grabbing this when I did the Single response pattern. I'll queue it up.

**Comment by kristinoletmuskat** [comment]
That would be great! Thank you

**Comment by humancompanion-usds** [comment]
@kristinoletmuskat - Sorry, I'm finding this Word doc difficult to follow. Some questions:

* "Create a new section for Title Tags, and move content from Writing for SEO to that new section. Crosslink to the title tags section from ‘Writing for SEO’" - In one comment there is an instruction to create a new section, in another the comment mentions linking to a new page from another page. Do you want an entirely new page named Title tags in the content style guide or do you want a new section within Writing for SEO?
* What am I to remove or move from the Writing for SEO section? Title tags are mentioned in a number of places.

**Comment by kristinoletmuskat** [comment]
Hey @humancompanion-usds , sorry about that! I think I was using the words page and section interchangeably. This attached doc might be easier to read (I reworded the instructions, added screenshots, and made one change, so pls use this one as source of truth):

[Title Tags.docx](https://github.com/user-attachments/files/15540187/Title.Tags.docx)

**We want to do the following:**
1. Add a new **page** called Title tags to VADS in the 'Content' section
2. Remove title tags **section** from 'Writing for SEO' (or, remove most of it. We'll leave some info about title tags that contextualizes the guidance around it. See the doc for exactly what to remove and where to add the links)
3. Link to this new page from 3 other pages that reference title tags (Writing for SEO, Subtasks Pattern, Forms Template -- see the doc for exact spots to link)

**Comment by kristinoletmuskat** [comment]
Hey @humancompanion-usds , just seeing if you need anything else on this? I'm also happy to do a quick meeting or come to DST office hours if that would be helpful!
