### ISSUE TITLE
UL style incorrect on Process List Item inner content

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#2421]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
While working on a PR to update some old [process list formation code](https://github.com/department-of-veterans-affairs/vets-website/pull/27597) to use the new [USWDS process list component](https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--default) I noticed inside the [USWDS process list component](https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--default) `list-item-style` doesn't square bullets. It renders the default circle bullets. 
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/b006ef7e-00db-40ec-a38e-232b750cff48)

## What I expected to happen

It should render square bullets to match the design system. 

## Reproducing
- Formation version: Current
- Device: Macbook Pro
- Browser: Chrome

Steps to reproduce:

1. Use the v3 Process List component
2. Add an unordered list inside of the `process list inner item` 

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/468ca46a-f30d-4e58-90d5-87e40dc45618)
Looks like [this line](https://github.com/department-of-veterans-affairs/component-library/blob/b5ac878c3b3e778950e5aaea10a4d2b236bc6707/packages/css-library/src/stylesheets/elements.scss#L83) is being ignored.

**Comment by caw310** [comment]
Actually the round bullets for v3 process list content is correct. 
https://design.va.gov/components/process-list
https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--default

**Comment by josephrlee** [comment]
Oh, strange. Is there a reason why circle bullets are being used only in the process list for the v3 component while [other](https://design.va.gov/components/featured-content#examples---v3) [components](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default#sign-in-to-start-your-application) use the square bullet style?
