### ISSUE TITLE
Expandable alert Figma component needs number of lines property

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#2425]
# Bug Report

## What happened

The expandable alert component label text doesn't wrap onto multiple lines, which is needed for small screen sizes
## What I expected to happen

The text should wrap onto multiple lines, with the icon at the end of the last line, just like the additional info component

## Reproducing
Add the component to a frame in Figma and type a long line of text. Then resize and see the text does not wrap

## Suggestion

I think it needs the same fix applied to the additional info component

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2425?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady  This is good to go!  It may also help to write something up in the documentation about the user re-sizing the background colored box to fit the text in the user guide.
