### ISSUE TITLE
Link component (active type) update: chevron at end of line needs prop updated for 2 lines (or more)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2427]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When a link goes past 2 lines (hard return by user to force the 2nd line) the chevron stays outside the text box area instead of returning to the end of the line of text:
<img width="285" alt="Screen Shot 2024-01-26 at 11 05 44 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/146852077/67cd8bf4-82a1-49c0-98aa-d23dfde01a95">

## What I expected to happen

What should happen is that the chevron should chevron should move to the end of the line of text:

![Screen Shot 2024-01-26 at 11 06 39 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/146852077/e8ff78d4-0d05-4c86-aed7-e9ee98b9d869)

A similar issue came up for Additional Info and a prop was added to have 2 lines of text

## Reproducing
Figma component 

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2427?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady This one is ready for testing

**Comment by LWWright7** [comment]
@danbrady Can we confirm this is good to close??

**Comment by danbrady** [comment]
@LWWright7 Yep, if you published it then we can close this. Thanks!

**Comment by LWWright7** [comment]
@danbrady Thanks!!
