### ISSUE TITLE
Remove banner role from Maintenance Banner

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2429]
## Description

Per [Slack thread](https://dsva.slack.com/archives/C8E985R32/p1700687281869749), remove `role="banner"` from the maintenance banner. 

`role="banner"` is typically used for a global site header that usually includes a logo, navigation, and is located at the top of a page. This allows a screen reader user to navigate by landmark to the banner. Because this maintenance banner is not the site header, the role of banner should be removed from it. 

[MDN - ARIA banner role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role)

## Tasks
- [ ] Remove the role.

## Acceptance Criteria
- [ ] Role has been removed.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2429?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
@rsmithadhoc , would you please add more details?

**Comment by caw310** [comment]
Bringing this into sprint 47 as unplanned work as there is capacity to complete this work within the sprint.
