### ISSUE TITLE
React Component Deprecation - Remove unused components from react-components

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2439]
## Description
There are some unused components currently in the react-component package that should be removed:
- `/react-components/src/components/TextInput` should be removed and it's [entry in Storybook](https://design.va.gov/storybook/?path=/docs/deprecated-textinput-react--autocomplete) should be deleted.
- `/react-components/src/components/IconBase` should be removed, it has 0 imports in vets-website & content-build
- `/react-components/src/components/IconSearch` should be removed, it has 0 imports in vets-website & content-build

## Tasks & Acceptance Criteria
- [ ] Remove the above components from the react-components package

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2439?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
