### ISSUE TITLE
File input a11y screen reader updates

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2442]
## Description
- ~~Remove "file change event" alert, unless necessary for something.~~ **Not needed, see Jami's comment below.**
    <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51af5d7989897c9e77af37679d7ff43395b7a4e4/image.png" alt="image.png" />
- Add announcement of file selected:
    - On selection of a file. USWDS uses this:
    ```html
        <div class="usa-sr-only" aria-live="polite">You have selected the file: banner-2.png</div>
    ```
    - When tabbing away and then tabbing back to the file input button.
        - When tabbing away, then tabbing back to the file input, it currently reads "Change file: No file chosen, button", but should read "Change file: {filename}, button:" I wasn't able to find exactly where USWDS had the filename, but theirs read out the filename as expected.
            <img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d12561b411f5585c8af4a12036ac24fcda857c21/image.png" alt="image.png" />

## Tasks
- [ ] Update component for screen reader

## Acceptance Criteria
- [ ] Updates have been made

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2442?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
The "file change event" alert is just for [demonstration purposes in Storybook](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/storybook/stories/va-file-input-uswds.stories.jsx#L28-L30) to show that the custom file event was received outside of the compnent (this is how the v1 variation is set up in Storybook as well). This is not internal functionality of the component itself.

- https://design.va.gov/storybook/?path=/docs/components-va-file-input--default
