### ISSUE TITLE
Developer contribution page updates

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#2446]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Other

### What is the name?

For developers: Contributing

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [X] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

While working on defining a user flow for design component issues at staging reviews, I noticed there was no clear direction for developers to contribute code back to the design system for an existing component. Per this [Slack conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1706622472489839), we need to update a few things. I am not sure how clear it is for a VFS team to fix a global issue with an existing component and then contribute the code back to the Design System.

Some comments from that Slack thread:

- I actually think that this is a typo though and it should be 50 lines:
 PRs which make a change to the Design System should be manageable in size (less than ~500 lines of code)
- I think one thing we can add to the docs is pointing developers to the repository readme which has some additional technical information about submitting PRs and running the build locally: https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#contributing

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2446?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
