### ISSUE TITLE
Figma rebuild: Templates - Direct Deposit (Patterns)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2453]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)
- [Figma File](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates-(Patterns-%26-Forms)?type=design&node-id=2988%3A21247&mode=design&t=8oj22BwLwsXavroj-1)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/hub

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2453?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by LWWright7** [comment]
[Uploading... screencapture-staging-va-gov-profile-direct-deposit-2024-02-27-23_21_23.png]

**Comment by LWWright7** [comment]
<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21YQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6126868f28628948c5ab367eccdae4dac03fd1ef/screencapture-staging-va-gov-profile-direct-deposit-2024-02-27-23_21_23.png" alt="screencapture-staging-va-gov-profile-direct-deposit-2024-02-27-23_21_23.png" />

**Comment by caw310** [comment]
This issue will carry over as there were challenges finding examples of this pattern.

**Comment by LWWright7** [comment]
Thank you @caw310! You beat me to it!

**Comment by LWWright7** [comment]
@danbrady  This one is ready for [review](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?type=design&node-id=2988%3A21247&mode=design&t=gTmCWuP3YR0yFKuP-1)!
