### ISSUE TITLE
Figma rebuild: Templates - Files (Patterns)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2455]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)
- [Figma File](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates-(Patterns-%26-Forms)?type=design&node-id=2988%3A63596&mode=design&t=8oj22BwLwsXavroj-1)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/hub

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2455?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady & @babsdenney ....[this one](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?type=design&node-id=2988%3A63596&mode=design&t=DehyQrG9ohvNgI91-1) is ready for review! thanks :)

**Comment by LWWright7** [comment]
@micahchiang I have a few questions about the card web component after meeting with @humancompanion-usds and discussing this a specific behavior in this ticket.  

On the [guidance](https://design.va.gov/patterns/ask-users-for/files#how-to-design-and-build), it shows what a file upload would look like if a password protected PDF is uploaded for V1 (also, worth noting after the user already inputs the password)
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d06b1ca81aeca6de75f0eea5446d61e84e17d74b/Screen%20Shot%202024-04-09%20at%2010.56.26%20AM.png" alt="Screen Shot 2024-04-09 at 10.56.26 AM.png" />


BUT we need to update this to V3 and those tickets aren't til a future sprint.

This is how the behavior currently looks in staging:
<img width="663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1e4ed45dca4df01df42412876f7078a13fc79ab/Screen%20Shot%202024-04-09%20at%2012.13.13%20PM.png" alt="Screen Shot 2024-04-09 at 12.13.13 PM.png" />

Not the greatest look...so I'm submitting this as a proposed design instead:

<img width="352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ZJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10890cc3c47fc37be4da159d0e3c453f449dc4dc/Screen%20Shot%202024-04-09%20at%202.14.36%20PM.png" alt="Screen Shot 2024-04-09 at 2.14.36 PM.png" />

The question Matthew wants me to pose to you, Micah, is if this design is possible with the current web component for card? (I know this is kinda long and somewhat complicated, so please feel free to slack me with any questions). Thanks!

**Comment by micahchiang** [comment]
@LWWright7 - Thanks for the ping. A couple of thoughts I have:
- Technically yes, this is doable in the current va-card component, with the caveat that we currently don't have a blue background supported for it. The designs for multiple file input also include a blue background, so we'd probably look at just adding a blue background card variant. 
- In my mind, It's less of a question about whether or not our card component can do this, and more a question of how do we approach this for the file input component itself. Our component doesn't actually support password encryption, and the thing that is currently in production is a custom component that exists outside of our design system. We'd probably be inclined to approach this the same way we'll approach the additional information field, with a slot into which users can pass their own markup.

**Comment by danbrady** [comment]
> Technically yes, this is doable in the current va-card component, with the caveat that we currently don't have a blue background supported for it

@micahchiang @LWWright7 Chiming in here as it might be confusing. The intent was for the File Input component to have [Default - White with border](https://design.va.gov/components/card#default---white-with-border) Cards embedded within it. Visually speaking, the blue is part of the File Input, but the white background with border are cards. (Crude visual below.) I don't think we need to have a blue background variation for the card. At least, that's my thinking. Let me know if you want to discuss further.

<img width="590" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/f7916a10-7674-48d2-96c8-a424fb05ccc6">
