### ISSUE TITLE
Figma rebuild: Templates - Multiple Responses (Patterns)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2457]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)
- [Figma File](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates-(Patterns-%26-Forms)?type=design&node-id=2988%3A63598&mode=design&t=8oj22BwLwsXavroj-1)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/hub

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2457?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by caw310** [comment]
This may carry over due to sick days.

**Comment by LWWright7** [comment]
@danbrady & @babsdenney ....[this one](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?type=design&node-id=2988%3A63598&mode=design&t=yS8cnrp2IJwN4ICJ-1) is ready for review! thanks :)

**Comment by babsdenney** [comment]
@LWWright7 This looks good! I left a few notes in Figma.

**Comment by danbrady** [comment]
Same!

**Comment by LWWright7** [comment]
After discussion with @humancompanion-usds , it has been decided that once the usability testing has been done on [this ticket](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1107), if findings of the testing show that the link should be moved to the bottom, then there should be a design ticket created for a designer to go back into the templates/forms/patterns library and update those instances.

In addition, since this card pattern 
<img width="475" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTlJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a785cff8eba57ad258bcb482fdf46e1fafa205e/Screen%20Shot%202024-04-09%20at%201.37.14%20PM.png" alt="Screen Shot 2024-04-09 at 1.37.14 PM.png" />


is repeated in numerous places, it would be a good candidate for the [card audit](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2447).

With these 2 items understood, this ticket is closed.
