### ISSUE TITLE
Figma rebuild: Templates - Race, ethnicity, origin (Patterns)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2459]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)
- [Figma File](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates-(Patterns-%26-Forms)?type=design&node-id=2988%3A64512&mode=design&t=8oj22BwLwsXavroj-1)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/hub

**Comment by humancompanion-usds** [comment]
Capturing here some potential content from Nancy Clarkson, OCTO Enterprise Data Architect:

> What to know before you decide to share your [race or ethnicity, sexual orientation, gender identity]

> Sharing your [race or ethnicity, sexual orientation, gender identity] is optional. VA collects and aggregates this information to analyze and identify ways we can better serve the unique needs of different population groups. 

> You should know that this information goes into your VA-wide records and may be viewed by VA staff other than your VA health care team to validate analytical results or to identify potential benefits for which you may be eligible. If you decide you no longer want to share your [race or ethnicity, sexual orientation, gender identity], you can use your VA.gov profile [create an account or log in here] to change your selection to Prefer not to answer.

> We follow strict security and privacy practices to keep your personal health information secure. If you get your health care at VA, your health care team may be able to view this information, but any [race or ethnicity, sexual orientation, gender identity] discussions they may have with you are restricted to your health record, which is not used to update this information. If you want this information to reflect what is in your health record, you can change your selections in your VA.gov profile or ask a VA representative to assist you.

I need to run this by CAIA and see where we might house this content.

**Comment by humancompanion-usds** [comment]
@danbrady and @LWWright7 - If you could review the template I added and leave me any comments I would appreciate it. Thanks!

**Comment by LWWright7** [comment]
@humancompanion-usds I took a look and it looks good to me!
