### ISSUE TITLE
Figma rebuild: Templates - Signature (Patterns)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2461]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)
- [Figma File](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates-(Patterns-%26-Forms)?type=design&node-id=2988%3A29742&mode=design&t=8oj22BwLwsXavroj-1)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/hub

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2461?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady @babsdenney - This one is ready for [review](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=6412%3A15651&t=1ZZ42HAsJUpWhcKV-1).  Also, it may be worth mentioning that this "pattern" is really just the component "Statement of Truth".  I'm a little confused why the "pattern" is exactly the same as an already existing component and in the guidance there aren't any examples of deviation from this one layout/design that is literally the "Statement of Truth" component. 🤷‍♂️

**Comment by danbrady** [comment]
LGTM!

I see what you mean by it looks like it's just a Statement of Truth component. I'm guessing the pattern is there to offer guidance of how this pattern fits in to the form flow (or when it is or is not needed) as well as some legal language. It also looks like there's a lot of related implementation information regarding generating a PDF with a signature.

**Comment by babsdenney** [comment]
Same, this looks great!

**Comment by LWWright7** [comment]
Thanks for the review @babsdenney and @danbrady  -  Yeah, I know what you mean about that implementation with the PDF signature....I noticed that section at the top in the guidance.  Lots of very detailed government guidelines and statutes, etc to be followed for the digital replication in lieu of an actual "wet ink" signature.
