### ISSUE TITLE
Figma rebuild: Templates - Overview (Forms)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2463]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)
- [Figma file](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates-(Patterns-%26-Forms)?type=design&node-id=2988%3A66783&mode=design&t=yMHNYET2inQBmjJ0-1)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/hub

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2463?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by danbrady** [comment]
@LWWright7 @caw310 Can you link to what Overview template we need to build? It's not clear to me what this ticket is referring to?

**Comment by LWWright7** [comment]
@danbrady you're 100% correct! I created these tickets based on the menu layout of that templates page without looking at the content.  @caw310 Closing this ticket as it's not needed.
