### ISSUE TITLE
Figma rebuild: Templates - Confirmation (Forms)

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2466]
## Description
There were many templates created in Sketch that will need to be included in Figma. This has a few different things to consider that would be good to get Designer feedback on. 

- What templates to include in Figma?
- What breakpoints are needed?
- Should these templates be in the Figma library or somewhere else?

- [ ] Templates page

## Details

- [Templates in sketch](https://www.sketch.com/s/c8df169f-5b02-4999-befb-34c7b3b62ba9)
- [Figma file](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates-(Patterns-%26-Forms)?type=design&node-id=2988%3A66786&mode=design&t=yMHNYET2inQBmjJ0-1)

## Tasks
Figure out 
- [ ] What templates that we will need in Figma
- [ ]  Breakpoints for templates
- [ ]  Where will the templates live
- [ ] Create templates and add to Figma

## Acceptance Criteria
 The design is the same as what is in the Component Symbol Library in Sketch. If 

- [ ]  Reviewed by other DS designer
- [ ]  Possibly review with VFS Designers
- [ ]  Review by PO

https://design.va.gov/templates/forms/confirmation

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2466?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady @babsdenney This one is ready for review.

**Comment by danbrady** [comment]
This is looking good so far, @LWWright7! Can we move the components it uses to the same page like we did on Introduction? If there are components that are shared across templates, we can put them in the "Form Templates Shared Components" page?

**Comment by LWWright7** [comment]
@danbrady I've moved the subcomponents for this one to the same page.  And yes, we can put shared components in the new page I see you created (with the Lock) under the templates.

**Comment by danbrady** [comment]
LGTM!
