### ISSUE TITLE
va-file-input: Hide the multiple prop for now

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#2467]
## Description
In order to better align va-file-input V3's capabilities with V1's system guidance, we want to hide the `multiple` prop and upload option. This will ensure only 1 file is uploaded at a time.

## Tasks
- [ ] Hide the 'multiple' prop

## Acceptance Criteria
- [ ] Multiple file uploads are prevented

**Comment by caw310** [comment]
Added to sprint as unplanned as it is causing problems for teams.
