### ISSUE TITLE
Update forms pattern radio to show title and required label

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2475]
## Description

The forms pattern radio is missing a title and required label when those are set. It should match the checkbox version, see screenshot.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1yQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8cf446add494a493ffbd13814a6400686b6c7d9/image.png" alt="image.png" />

## Tasks
- [ ] Ensure title and required show when set.

## Acceptance Criteria
- [ ] Title and required text show when set for the forms pattern.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2475?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
