### ISSUE TITLE
Static Header - Discovery: inject react into static header

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2477]
## Description 
As part of the work to support the sitewide team while they build the federalCIO header, we need to determine a way in which we can provide the same authentication experience to users that we do now. If possible, we want to reuse the existing authentication app and its workflows instead of rebuilding it with vanilla js, html and css. With how vets-website is architected, react applications are dynamically injected into static pages. The purpose of this ticket is to confirm whether or not we can do this with the static header sitewide is building. 

## Considerations
- [Slack conversation](https://dsva.slack.com/archives/G01BJ3ESXL4/p1706653298271109) with the identity team about feasibility. 
- [Slack conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1706546388855779?thread_ts=1706311375.914819&cid=C01DBGX4P45) with sitewide about what they need
- [React injection at startup](https://github.com/department-of-veterans-affairs/vets-website/blob/d540d5d7f35a5970366d944f5f5290f94ccaacef/src/platform/startup/react.js#L48) in vets-website. This is potentially how it'd be done in the static header for teamsites. 
- [proxy-rewrite application sign in button](https://github.com/department-of-veterans-affairs/vets-website/blob/16815-dup-header-for-teamsites/src/applications/proxy-rewrite/partials/sign-in-button.js). React injection and sign in modal would likely need to happen somewhere in here. 
- [sign-in modal](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authentication/components/SignInModal.jsx) that would potentially be injected
- Possibly need to consult with Randi Mays from sitewide on how to run proxy-rewrite locally

## Tasks
- [ ] Verify if react and the sign in modal can be injected into the static header, document any limitations or gotchas on ticket as comment

## Acceptance Criteria
- [ ] Above tasks have been completed.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2477?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by randimays** [comment]
Instructions for running the proxy-rewrite application locally: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite

**Comment by Andrew565** [comment]
LGTM
