### ISSUE TITLE
Disable multiple file input dragging and dropping

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2479]
## Description

When the [file input](https://design.va.gov/storybook/?path=/docs/uswds-va-file-input--default) is set to accept a single file, it allows dragging and dropping multiple files. It only retains the first file and discards the rest. This should be updated to not allow dragging and dropping multiple files to avoid confusion. See [USWDS file input](https://designsystem.digital.gov/components/file-input/) single file and screenshots below for an example.

<img width="1792" alt="drag-drop" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/5b3a5fc5-ca65-4cff-ae34-24cc11c53271">

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/7b07794a-72bd-417a-9b3d-16b6ac60be2a)

## Tasks
- [ ] Update to not allow dragging and dropping multiple files.

## Acceptance Criteria
- [ ] When dragging and dropping multiple files, it should not allow them to be dropped (nothing should be uploaded).
    - On Mac, this will show a red indicator with the number of files, but _no_ green plus indicator.
    - On Windows, this will show a red disallowed symbol.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2479?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/component-library/pull/1050)
