### ISSUE TITLE
Add Military Address Pattern to Figma Templates

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2480]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Pattern

### What is the name?

Address

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Allows a user to drop in a variation that depicts are user selecting the "live on US base" option.

### Additional Context

Related [slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1707234354787589). (Internal)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2480?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady This one is ready for [review](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?type=design&node-id=2988%3A13554&mode=design&t=gTmCWuP3YR0yFKuP-1).   

<img width="1447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2UwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--756cf32ba51d1be2e01fc7ed6efb57170f85495d/Screen%20Shot%202024-03-05%20at%202.15.04%20PM.png" alt="Screen Shot 2024-03-05 at 2.15.04 PM.png" />

**Comment by danbrady** [comment]
@LWWright7 I believe when the "I live on a U.S. military base..." is checked the country becomes a read-only "United States" field. See the example on the [pattern page](https://design.va.gov/patterns/ask-users-for/addresses).

**Comment by LWWright7** [comment]
@danbrady Right you are!  That should be fixed now. Can you please re-check? Thanks
