### ISSUE TITLE
design system, components [KEYBOARD]: Focus outline MUST be visible around focused content, pagination

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#249]
@jenstrickland commented on [Tue Apr 21 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8254)

# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

```diff
! Team: VSA Public Websites; Project: Find Forms MVP
```

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

For each page of search results, the focus outline **must** be visible around the entire page indicator. but is currently cropped at the top at bottom.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a keyboard user, I want to tab through the content and be able to see where focus is.

## Environment

* Operating System: all
* Browser: all
* Server destination: production

## Steps to Recreate

1. Enter https://www.va.gov/find-forms?q=medical in browser
2. Tab through page content to the pagination
3. Verify that the focus outline is cut off on the top and the bottom

## Screenshots or Trace Logs

![Screen Shot 2020-04-21 at 8 23 08 PM](https://user-images.githubusercontent.com/57469/79927839-087ce480-840f-11ea-9d64-26f3b358f3f5.png)

**Comment by jenstrickland** [comment]
Once this issue is addressed, please let the VSA Public Websites team know so they may audit their work to ensure they no longer have this issue. Thanks!

**Comment by 1Copenut** [comment]
This issue was previously fixed by https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/7e9f370f4561e159c62b1aa59d3edf5bec5bc3a7 on May 11, 2020.
