### ISSUE TITLE
Modal text overflows at 702px

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#2492]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The `va-omb-info` web component contains a `va-button` and `va-modal` which can be set to use USWDS v3, but there is no `uswds` option for the outer `va-omb-info` component. Also, with some manual testing, it appears that setting the `va-modal` v3 property causes the text to overflow the modal window.

Manual update to v3 using dev console:

<img width="1194" alt="OMB info inside modal overflows when modal is set to v3" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/3ac5040d-b93d-43f9-b1db-869e9b5dfd5a">

## What I expected to happen

Adding a `uswds` property to `va-omb-info` should update both the `va-button` and `va-modal` inside the component. Also, the modal content should be contained within the modal window.

## Reproducing
- Formation version: All
- Device: (e.g. iPhone 8, Macbook) All
- Browser: (e.g. Firefox, IE 11) All

Steps to reproduce:

1. Go to https://design.va.gov/storybook/?path=/docs/components-va-omb-info--default
2. Open dev console and edit va-omb internal web components to include `uswds` property

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
I updated the title to better reflect the current state.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2492?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
