### ISSUE TITLE
On This Page component functionality bug

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#2493]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

In trying to implement the `on-this-page`. I ran into a limitation where the logic in the component doesn't work when `h2s` are included from another component. So, I had to recreate it with the code from the component for the `combined-debt-portal` and [apply utility classes to get the styles to work correctly](https://github.com/department-of-veterans-affairs/vets-website/pull/27832/files#diff-ffb8cce1e42b413c43c818958d032493dc8f73d2c1a58612a04cfe88bdcd31b2).

## What I expected to happen

I'd expect the component to be able to find every `h2` on the page even ones that get included from other components. 

## Reproducing
- Formation version: N/a
- Device: Macbook Pro
- Browser: Chrome (latest)

Steps to reproduce:

1. Add `on-this-page` component to `OverviewPage` then run locally and see only `h2s` generated from whats in the `container`

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
Here's a PR to my workaround: https://github.com/department-of-veterans-affairs/vets-website/pull/27832/files#diff-608302ca2470bea309bc7ebbeb570d23ffdf53d5261e625cf7e2127c6bad31a0

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2493?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Possibly related issue:

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2956

**Comment by caw310** [comment]
Closing this as this bug will be fixed in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3318
