### ISSUE TITLE
Icons - missing LinkedIn icon

### ISSUE THREAD

**Issue by LWWright7** [department-of-veterans-affairs/vets-design-system-documentation#2497]
Create LinkedIn Icon in Figma under Icons - USWDS tab

https://www.va.gov/housing-assistance/

![Screen Shot 2024-02-13 at 9 28 33 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/146852077/ebb96348-c765-4054-9113-7df401c27d14)

The icon can be found in Material UI here:
https://mui.com/material-ui/material-icons/?query=linkedin

- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and/or DSC
- [ ] Review designs with an accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

- [ ] Component design is complete and has been reviewed
- [ ] Accessibility considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Unplanned work in sprint 47
