### ISSUE TITLE
Link - Action Web Component - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2500]
## Description
Build a web component of Link- Action. Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

If this is a pattern or component that is already in existence, check the Design System Team backlog for outstanding issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this new version and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
- Design documents: [[Figma](https://www.figma.com/file/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?type=design&node-id=1312-10314&mode=design&t=YkmspaSpgTltfUrc-0)]
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Contact designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2500?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jilladams** [comment]
@caw310 Question for you: our team has a ticket we're holding on until this one is completed ([[V1 & 3 Components] Implement available components for Income Limits #17276](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17276)). Looks like this ticket had been planned, but is now back in considering prioritization -- do you have a sense of when this may be possible to get prioritized?   (cc @randimays @davidconlon @FranECross )

**Comment by caw310** [comment]
@jilladams this is scheduled to be worked on in mid-April. We moved it out a few sprints as we have other higher priority work.

**Comment by randimays** [comment]
Adding here that we will need to add a white action link version for dark backgrounds, please! Screenshot from the homepage hero banner.

<img width="338" alt="Screenshot 2024-03-22 at 4 08 39 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/19175324/0005e43d-f4ee-4d64-82a7-e1970244f643">

**Comment by caw310** [comment]
We are swapping this ticket and moving it to the next sprint to work on[ 2676](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2676)

**Comment by humancompanion-usds** [comment]
Just a head's up that the a11y CoP and I are designing, and plan to test, a revision to the primary Link - Action that will solve for making the primary link stand out in a sea of text. That [experimental issue is here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1459). I mention it just so you can look at it before coding so that we leave room for what the eventual implementation could be. In other words, we'll likely want to create a va-link-action rather than extending va-link as the design may potentially become slightly more complicated. But that experimental issue should not hold up the creation of the new web-component.

**Comment by FranECross** [comment]
@jamigibbs I don't think this has actually been released yet. Is there an estimate as to when it will be released to prod? Thanks!  cc @randimays @chriskim2311
