### ISSUE TITLE
Add focus outline to `tabindex` in shadow DOM

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#2521]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

Related:
- #1314
- #654

## What happened

When a header is added to a `va-radio`, it is getting focused in our app after navigating to a new page. But because the header is inside the shadow DOM, there isn't a focus outline on the header

USWDS v3 `va-radio` with `label-header-level="3"` set; the header is being focused, but no focus outline is visible

<p/>

<img width="1004" alt="Would you like us to request... header of a yes/no va-radio group is focused - shown in the dev console, but no focus ring is shown" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/1de55870-ff67-4eda-881d-2ea65741e5ae">

Default form radio widget (pending v3 update) with `h3` focused showing a typical focus ring.

<p/>

<img width="514" alt="radio widget with h3 in the fieldset/legend with a yellow outline focus" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/5c0661c0-8e12-4b79-bbed-18d098e383a6">

<p/>

Occasionally while navigating through a form, blue focus outlines sometimes appear - after checking the dev tools, it appears to be visible when the [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#focus_vs_focus-visible) state is true

<p/>

<img width="1134" alt="Screenshot 2024-02-21 at 1 55 10 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/0d7e347a-1e56-4934-ac6e-6f9374fc1673">

The browser (Brave which is Chrome based) has this user agent stylesheet definition:

```
:focus-visible {
  /* rgb(0, 95, 204) */
  outline: -webkit-focus-ring-color auto 1px;
}
```

## What I expected to happen

Focus outline should show up on the header (when `tabindex="-1"`) and match the same styling as other outlines

## Reproducing
- Formation version: Current
- Device: (e.g. iPhone 8, Macbook) All
- Browser: (e.g. Firefox, IE 11) All

Steps to reproduce:

1. Navigate to https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995
2. Log in with any of the [decision review users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md)
3. Navigate to the primary phone number page (immediately after the contact info page, third page in)
4. Note that the main focus is on the `va-radio` with the `h3` inside the shadow DOM having focus inside the web component but no focus outline is visible (in the first screenshot, click on the eye icon in the dev console to add watched variables)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

This isn't _blocking_ any work per se, but it is a hinderance for Veterans that depend on the focus outline.

**Comment by rhasselle-oddball** [comment]
additional notes:
any form using `v3SegmentedProgressBar: true` will now have the following CSS black outline on the va-segmented-progress-bar on chrome+windows after this [scroll issue PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27784) is merged. (before we didn't show any outline)
![chrome_01r2feXV3x](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/2ec5b399-60d1-4317-913e-dd95e92228f4)
affected forms:
```
src/applications/ask-va/config/form.js
src/applications/ivc-champva/10-10D/config/form.js
src/applications/pensions/config/form.js
src/applications/simple-forms/20-10206/config/form.js
src/applications/simple-forms/20-10207/config/form.js
src/applications/simple-forms/21-0966/config/form.js
src/applications/simple-forms/21-10210/config/form.js
src/applications/simple-forms/40-0247/config/form.js
```

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2521?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
DST note: The focus mixin can be imported from this mixin:

```css
@import '../../mixins/focusable.css';
```
