### ISSUE TITLE
Accordion - Expand/Collapse All control incorrect when items opened on page load

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2524]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On every Hub landing page, the accordions in the right column are expanded on page load. However, the toggle control still states "Expand All".

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/57248b50-9d8a-4295-bbce-026148b73e82)

## What I expected to happen
The toggle button should correctly match the state of the accordions.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2524?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by GovCIOLiz** [comment]
Hello, please be aware the VEBT team has the same issue for our SCO page: https://staging.va.gov/education/school-administrators/ that will go to prod in a few short weeks, replacing https://www.va.gov/school-administrators/. It's affecting 3 accordions on the page. 

<img width="331" alt="Screenshot 2024-08-14 at 11 43 37 AM" src="https://github.com/user-attachments/assets/ff360287-c550-4c43-8e2c-e4e57dbcddfb">
<img width="694" alt="Screenshot 2024-08-14 at 11 43 57 AM" src="https://github.com/user-attachments/assets/4b1ca369-8676-49dc-94f6-5164626ce259">
<img width="706" alt="Screenshot 2024-08-14 at 11 43 49 AM" src="https://github.com/user-attachments/assets/b4c6936a-eabd-4bc2-878e-8ccd04ae7240">
