### ISSUE TITLE
[Figma] Update Penalty Statement in figma components

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2528]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

However - 
We had previously made this change in [sketch in this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1960).

See also this [conversation on Octo Slack](https://dsva.slack.com/archives/C044AGZFG2W/p1690817813440449)

## What happened

When placing the penalty notice and using the review page template, I noticed the text included is not the most current version.  The text reads

> **Note:** According to federal law, there are criminal penalties, including a fine and/or imprisonment for up to 5 years, for withholding information or for providing incorrect information (See 18 U.S.C. 1001).

## What I expected to happen

I expected the penalty statement to read:

> **Note:** According to federal law, there are criminal penalties, including a fine and/or imprisonment for up to 5 years, for withholding information or for providing incorrect information (Reference: 18 U.S.C. 1001).

The only difference is the word `See` vs `Reference`

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. In figma, using the VADS component library place the penalty component
2. In figma, use the VADS review page template
3.
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work - I'm updating the text to be what we're using on production
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2528?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by danbrady** [comment]
We should update this on the [Penalty Notice](https://design.va.gov/components/form/penalty-notice) page as well. (It's simple content, not a web component.)

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2528?planning-poker) with Zenhub @babsdenney
