### ISSUE TITLE
Formation Deprecation - Add 768px Breakpoint to CSS Library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2533]
## Description 
We previously added breakpoints to CSS Library in preparation for sunsetting Formation. Part of this was completing [#2334](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2334). I incorrectly listed in the considerations of that ticket that the 768px breakpoint should be replaced with the new 640px. 

This ticket is to add the 768px breakpoint to CSS Library **alongside** the 640px breakpoint. We're doing this because we want to provide teams with a timeline to migrate to the new breakpoint instead of just turning it on. 

## Considerations
- Previous PR - https://github.com/department-of-veterans-affairs/component-library/pull/1042/files

## Tasks
- [ ] Add 768px as a breakpoint to CSS Library

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2533?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
Decision was made to change "medium" breakpoint to 768px, and change the 640px breakpoint to "medium-mobile".
