### ISSUE TITLE
Formation Deprecation - Icon Migration eslint rule

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2535]
## Description
To assist teams with migrating off of font awesome and onto `va-icon`, we should write an eslint rule that lets teams know font awesome usage is deprecated. 

## Considerations
- [vets-website eslint rules](https://github.com/department-of-veterans-affairs/vets-website/blob/26e5d68050bfa806f98a746ce8147c95f07c0eda/.eslintrc.js#L38)

## Tasks
- [ ] write an eslint rule that alerts teams to use va-icon instead of font awesome

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2535?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
We have an example of an ES Lint rule that we wrote for telephone numbers that can probably be used as an example for this too:

**veteran-facing-services-tools**
- [eslint-plugin/lib/rules/prefer-telephone-component.js](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/43f7896c33b06501d5e0fc6be5be6993189316b9/packages/eslint-plugin/lib/rules/prefer-telephone-component.js)

**vets-website import**
- https://github.com/department-of-veterans-affairs/vets-website/blob/26e5d68050bfa806f98a746ce8147c95f07c0eda/.eslintrc.changed.js#L11

**Comment by jamigibbs** [comment]
I'm going to close this as a duplicate because we can combine the eslint notice and migration together in ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2534
