### ISSUE TITLE
Formation Deprecation - Write icon migration guidance

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2536]
## Description
With the completion of [#2534](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2534) and [#2535](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2535), we should communicate out to teams how they can migrate to `va-icon` using the tools we've built. 

## Considerations
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2535
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2534

## Tasks
- [ ] Write guidance on how teams can migrate to `va-icon`. This should include how to use the above mentioned script, as well as manually replacing a font awesome instance with `va-icon`. 

## Acceptance Criteria
- [ ] Guidance has been written as a step by step process and pasted onto this ticket as a comment.

**Comment by jamigibbs** [comment]
Icon mapping in Mural: [https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/16[…]692dc255f43c852737?sender=63396f15-d0e2-4d3a-92a5-d5c8a34880c1](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1678830068825/553b0ef0eb59ba6e26ad03692dc255f43c852737?sender=63396f15-d0e2-4d3a-92a5-d5c8a34880c1)


va icons audit ticket: 
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1476

**Comment by jamigibbs** [comment]
I've started [writing a draft for this](https://docs.google.com/document/d/1UkiEgS7KxXdzNPBAYJqyfB6T2FpVlYmx2XUf8X5GvVE/edit) and I'm dragging @danbrady in to help if he has capacity 🙏
