### ISSUE TITLE
Formation Deprecation - Styles Migration - Swap content-build import

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2539]
## Description
With the completion of [#2537](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2537), we're ready to attempt a swap of the css imports in content-build from Formation to CSS Library.

## Considerations
- content-build imports formation through a script tag [here](https://github.com/department-of-veterans-affairs/content-build/blob/8f210b698a727201dd01b35d3ccaea84e0330512/src/site/includes/header.html#L124)
- Similar to how we conducted significant QA on #2494 and #2525, we'll want to manually test our imports through verdaccio
- Because content-build imports Formation through a script tag, we may not be able to take a stepwise approach to swapping imports, and instead be obligated to conduct a direct swap. 
- Content build relies heavily on Formation utility classes, so we may need to ensure similar classes are accessible from CSS Library

## Tasks
- [ ] Submit a PR into content-build that updates the CSS-Library dependency

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2539?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
@micahchiang This block below in content-build I suspect was done temporarily to test an experimental hover state in the dev enironment. It's wrapped in this condition: `{% if entityId == 11463 and buildtype == "vagovdev" %}`

https://github.com/department-of-veterans-affairs/content-build/blob/2d652e59e45ccbd3fd4f425c34b2099736faa728/src/site/includes/header.html#L122-L142

I wonder if we may not need to do anything except remove it at this point.

Here are some related PRs:
- https://github.com/department-of-veterans-affairs/content-build/pull/1277
- https://github.com/department-of-veterans-affairs/content-build/pull/1262
