### ISSUE TITLE
Table component audit

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#254]
### Description: 
Tables show tabular data in columns and rows.

Tables in the sketch library, design.va.gov, and react library are out of sync.

*Note* team is currently updating the table component with a responsive table list and new sorting feature. 

You can view the component in [design.va.gov](https://design.va.gov/components/tables) and [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/sortabletable/)

### These are the ways this component is not synced

- The borderless table style needs to be added to design.va.gov and the react library 
- The responsive table/simple content list needs to be updated in the sketch library and added to design.va.gov and react library
- There is no documentation on when to use a borderless table in design.va.gov
- Weird naming with the developer documentation site. It's called "SortableTable" here but when I click on the column headers the column does not sort

### Complete the following tasks to synchronize component:
**Sketch library:** 
- Update the responsive table/simple content list to reflect design system council feedback- Have the typography match the table (header typography match the table header typography, unbold the values, and center the  colons for better legibility

**React library:** 
- Add Borderless table and responsive table/simple content list 
- Update table to have sortable columns

**Design.va.gov:** 
- Add Borderless table and responsive table/simple content list 
- Add documentation on when to use a borderless table in design.va.gov

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
