### ISSUE TITLE
NumberUI pattern type error

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/vets-design-system-documentation#2540]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

- Using the `numberUI` web component pattern produces 'type errors' even if integers are used in the field
- Generic type error message appears
- Believed to be stemming from `vaTextInputFieldMapping.jsx`

<img src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/57480791/7fc10b58-4bdb-4186-ba2d-741d1f3c4c50)" width="500">

## What I expected to happen

- Integers pass input validation

## Reproducing
- Formation version: N/A
- Device: Any
- Browser: Chrome, FireFox

Steps to reproduce:

1. Setup an input field using `numberUI` web-component-pattern
2. Input any numbers and click continue

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

I've opened a Draft PR that addresses this issue. We do not yet have a `currencyUI` pattern in place and so the other option was to use `numberUI` as continue to make updates to v3 web components. I decided to push this up as a solution if anyone else is currently being affected by this issue.

https://github.com/department-of-veterans-affairs/vets-website/pull/28201

**Comment by caw310** [comment]
This is a forms system issue.

**Comment by rhasselle-oddball** [comment]
@Midge-dev hi, this might because you need the corresponding numberSchema with the numberUI:
GitHub example: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/simple-forms/mock-simple-forms-patterns/pages/mockNumberInput.js
Live example: https://staging.va.gov/mock-simple-forms-patterns/number-input

does that resolve this issue? or are there still concerns/still something not working as expected?

**Comment by Midge-dev** [comment]
@rhasselle-oddball Ah - well, I will eat crow because this was indeed the problem. I didn't know we _had_ to use `numberSchema` for the the validation. Disregard this bug report - closing issue :call_me_hand:
