### ISSUE TITLE
Unable to add a file after previously adding a file when using the V3 VAFileInput component

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/vets-design-system-documentation#2549]
# Bug Report
Currently the Benefit Management Tools team has code on the claim status tool that takes the VaFileInput component and allows users to use the component to upload multiple files.

When trying to update this component to the v3 version we found that we were kind of able to do the same thing but it requires a user to select 'Change file' to add an additional file which doesnt make sense. It would make more sense if this button said 'Add file'.

Slack Discussion: https://dsva.slack.com/archives/C01DBGX4P45/p1709154979517099

## What happened

Currently the Benefit Management Tools team has code on the claim status tool that takes the VaFileInput component and allows users to upload multiple files 

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/141954992/afddbaab-78b0-4acf-88b5-dd178f470f7e

When trying to update this component to the v3 version we found that we were kind of able to do the same thing but it requires a user to select 'Change file' to add an additional file which doesnt make sense.

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/141954992/d827f2ef-e5f6-42c8-8dec-97c61d02457e

## What I expected to happen

It would make more sense if after uploading a file using VaFileInput the component had a button that said 'Add file'.

## Reproducing

Steps to reproduce:

1. Go to an opened disability claim `http://localhost:3001/track-claims/your-claims/`
2. Go to the files tab
3. Try to upload two files

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
This file upload is a part of our V2 release. We need this to work in order to complete our release which is set to happen beginning of April.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2549?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
cc @danbrady

**Comment by caw310** [comment]
This will be a stretch for sprint 49.

**Comment by Andrew565** [comment]
This ticket hasn't been updated with the work that Dan did to reflect what it is that engineers are being asked to do.

**Comment by caw310** [comment]
@danbrady can you add a link to the Figma library for file input?

**Comment by danbrady** [comment]
@Andrew565 - I've added the File Input to the component library, but it would be easier to see the various different states in [this figma file](https://www.figma.com/file/UZys4hvw2Vwuo7U0pwbKbq/File-Input-v3?type=design&node-id=71%3A25203&mode=design&t=QXVZLwZlpSP3fJCI-1). The biggest change/addition is, one, we'll actually allow multiple uploads now, and two, we'll (optionally) allow additional content to show after a file has been selected. (That's in the "Additional Info" row.) For example, after a user uploads a file, we can present them with additional content or form fields about that file. Let me know if you have more questions or want a walkthrough of it.

**Comment by caw310** [comment]
DST engineers will discuss how to approach this composition of components before estimating. This work will most likely be broken into multiple tickets.

**Comment by caw310** [comment]
Moving to an upcoming sprint as this needs to be broken down further. It will not hold up deprecation of v1 components.

**Comment by caw310** [comment]
The work for this request has been broken into three tickets. 
va-icon-button - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2641 (needed for file input)
update file input - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2642 (needs to happen before multiple file input)
multiple file input - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2643

**Comment by caw310** [comment]
Closing as all the tickets related to this request have been done.
