### ISSUE TITLE
Add "Featured Story" component to the design system

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#255]
# Feature Request

- [x ] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: "Featured content list item" 

- This is an existing component in VA.gov that has not yet been added to design.va.gov or the react library. 
- We currently have it in the sketch library in the content presentation as a "Featured story" component 

## Additional context

It's on Pittsburgh medical center:

https://staging.va.gov/pittsburgh-health-care/health-services/

It's on the VA forms search page:
https://www.va.gov/find-forms/

**Comment by caw310** [comment]
Closing as this is old
