### ISSUE TITLE
Broken link to "linking to external link" info

### ISSUE THREAD

**Issue by danbivins** [department-of-veterans-affairs/vets-design-system-documentation#2552]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
In the "Behavior" section on this page: https://design.va.gov/components/link/ 

I try to use this link: 
> See [linking to external sites](https://design.va.gov/content-style-guide/links/#linking-to-external-sites) in the ...

But I get take to a 403 page.

## What I expected to happen
I expect to get taken to more info on links to external sites.

## Reproducing
Tested across a couple different browsers to make sure I didn't have extensions that were in the way. 
Mac: Chrome and Firefox

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other:

**Comment by caw310** [comment]
Here is the correct link it should go to. https://design.va.gov/content-style-guide/links#linking-to-external-sites

**Comment by caw310** [comment]
Unplanned work added to the sprint as it was a quick fix.
