### ISSUE TITLE
File Input - Update v3 design to allow additional actions [Design] 

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2554]
## Description

The v3 File Input has multiple issues regarding taking actions on files:

* No clear way to remove file once uploaded
* No way to append an additional action on uploaded file
* Does not support multiple file uploads  

## Tasks
- [x] Create design(s) that address the issues above 

## Acceptance Criteria
- [x] Design approved with PO

Related issue: #2549

**Comment by caw310** [comment]
Adding this to the current sprint 48 as this is an issue that blocks the v3 component opt in.
