### ISSUE TITLE
Accessibility Annotations

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2555]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Other

### What is the name?

Annotations for VA.gov

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [X] Accessibility
- [X] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Helping to guide teams on how to add annotations to their figma mock up files.
- benefits of annotations for designers and engineers
- collaboration cycle requirements

### Additional Context

The draft of documentation can be found in this [google doc](https://docs.google.com/document/d/1tyGtsLXdsf5cNgNbF_odnNOiRFuAec2Kc4Klm_EeA0k/edit?usp=sharing). Feel free to let me know if you have problems accessing it or need me to help in any other way.

@briandeconinck, @rachaelpenfil and myself (@jeana-adhoc) are presenting the annotation kit to the larger VA.gov design community on March 18. We'd like to have this documentation in place by then so we can share the URL to the guidance in our presentation (it can of course go live sooner).

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2555?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by caw310** [comment]
@humancompanion-usds @danbrady @LWWright7 let's discuss where this should go.
