### ISSUE TITLE
Add card component to design system

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#256]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

Component/utility name: Cards
We've added cards to the sketch library and they're plenty of cards that exist currently in va.gov 

Places where cards exist: 
- Location cards
- Form cards- expandable forms cards
- Form status cards
- Appointment status cards 
- Case status
- Content cards - disability rating
- Promo cards 
- Media cards
- claim status cards
- MyVA

## Do you have a suggestion for a new component or utility?

I suggest we add the card component to design.va.gov and the react library. They are currently in VA.gov and widely used across a variety of applications.  There is currently cards in [USWDS design system](https://designsystem.digital.gov/components/card/) that we can use for sample documentation

## Additional info

Examples of cards on VA.gov:
[GI Bill comparison tools search results- Location cards](https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=new+york)

[Facility Locator search results - Location cards ](https://staging.va.gov/find-locations/?zoomLevel=4&page=1&address=California&facilityType=health&serviceType&location=37.0743595873%2C-119.699375153073&context=California%2C%20United%20States)

From My VA (logged in):
![image](https://user-images.githubusercontent.com/55992116/98166606-b2a4f100-1eb5-11eb-832d-5bd7e3024d6b.png)

**Comment by andaleliz** [comment]
Not sure if this is part of the work, but after this is done - how do we update across the site to reflect the new pattern?

**Comment by CrystabelReiter** [comment]
Right now we're working on that process. For right now I think the design system developers will assign tickets to teams to update their cards once a card component is created.

**Comment by CrystabelReiter** [comment]
Discussed this during design system council meeting on 11/6 - decided that this shouldn't be a prioritized item at this time.

**Comment by caw310** [comment]
Decision made during 11/6/20 DSC meeting not to work on card component at this time.

**Comment by caw310** [comment]
Closing as we are working on a card pattern. I have referenced this ticket in that other one.
