### ISSUE TITLE
Migrate breadcrumbs liquid template to breadcrumbs web component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2560]
## Description 
If an application in the [content-build registry.json file](https://github.com/department-of-veterans-affairs/content-build/blob/4ff558516c6af0270ce577b42127f5cd413ddf8f/src/applications/registry.json#L1678) includes breadcrumbs, then it'll use the liquid template provided in content-build found [here](https://github.com/department-of-veterans-affairs/content-build/blob/0487c9e913ca56e0623f18400a4a95c9bb2eb3c9/src/site/includes/breadcrumbs.html#L7).

Of the 109 application entries in that registry file, there are 47 applications explicitly setting includeBreadcrumbs: true and 5 which set that property to false. So a little under 50% look to be using the aforementioned liquid template.

All instances that don't have the includeBreadcrumbs flag, or set it to false, are likely using a web component to manage their breadcrumbs. 

We need to update [this template](https://github.com/department-of-veterans-affairs/content-build/blob/0487c9e913ca56e0623f18400a4a95c9bb2eb3c9/src/site/includes/breadcrumbs.html#L11) to use the `va-breadcrumbs` web component instead of the unordered list it currently uses. 

## Considerations
- Testing this will probably mean running the static pages for vets-website. Directions for how to run those can be found [here](https://github.com/department-of-veterans-affairs/content-build/blob/0487c9e913ca56e0623f18400a4a95c9bb2eb3c9/src/site/includes/breadcrumbs.html#L11). 

## Tasks
- [ ] replace the unordered list in the liquid template above with the va-breadcrumbs component and verify it functions as expected

## Acceptance Criteria
- [ ] Tasks have been completed.

**Comment by humancompanion-usds** [comment]
Sitewide is going to handle this change here:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17410

We'll assist in whatever way they need.
