### ISSUE TITLE
Update foundation icons page with v3 icons

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2569]
## Description
Update icons in guidance on the foundational icons page to v3 icons 
https://design.va.gov/foundation/icons 

## Tasks
- [ ] Replace icons on https://design.va.gov/foundation/icons  with v3 icons 

## Acceptance Criteria
- [ ] https://design.va.gov/foundation/icons  has been updated with v3 icons

**Comment by humancompanion-usds** [comment]
This happened a short time ago:
https://design.va.gov/foundation/icons
