### ISSUE TITLE
Experimental Design [Icon library - add USWDS chat icon to our VA instance of the USWDS library]

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/vets-design-system-documentation#2573]
## What
Add additional "chat" icon from the USWDS approved icons to the USWDS icon library available in Figma. 

![Screenshot 2024-03-07 at 10 16 37 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/137226108/7b2f1e26-8947-4ba3-a897-a54138ad99bc)

## Purpose
The additional chat icon will help Veterans distinguish a difference between secure messaging and VA Health Chat when both services are presented next to each other. 

## Usage
**Context**: We are adding "VA Health Chat app" to health system facilities pages to a section where Secure messaging already exists. Both of these are messaging with health care providers. The chat app is more of a triage real time chat assistance and secure messaging is sending a message to a specific provider with a few days turnaround time.

In early [discussion with DST](https://dsva.slack.com/archives/C01DBGX4P45/p1709832068721499), the tentative plan was to update all icons in section where this appears to USWDS icons and request addition of USWDS chat icon for the new service addition of VA health chat. The chat icon is on USWDS but not available in our Figma library.

## Examples
![Screenshot 2024-03-08 at 12 54 22 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/137226108/ca51782e-0fc2-42ee-992c-e2703ac940b8)

Example [facility system level page](https://www.va.gov/eastern-colorado-health-care/) of where this section appears

## Guidance
May want to maintain naming convention and label of "chat" to maintain consistency in use across VA so that it is not used interchangeably with secure messaging. Chat is to indicate real-time response. 

## Next steps
I would like an asynchronous review/approval

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
@aklausmeier are you available to attend DSC meeting Thursday, March 14 at 11am ET?

**Comment by aklausmeier** [comment]
@caw310 I have a conflict but can prioritize DSC if async doesn't work

**Comment by caw310** [comment]
@aklausmeier we should be able to do async but I will follow up if we need you to attend. FYI: DSC meets every 2 weeks so we could have this on the agenda for 2 weeks out.

**Comment by aklausmeier** [comment]
Sounds good, thank you @caw310

**Comment by caw310** [comment]
@humancompanion-usds are you good with adding this icon ?

**Comment by humancompanion-usds** [comment]
Yes, I'm find with adding this icon.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2573?planning-poker) with Zenhub @danbrady @LWWright7
