### ISSUE TITLE
VA Accordion Icon display issue on hover

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/vets-design-system-documentation#2578]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
When hovering on the accordion dropdown button, the icon shrinks in size

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Hover over the va-accordion item button

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment]
We had some discussion about this issue on [Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1710200196112369) and we're going to just remove the Font Awesome icon override to allow the USWDS icons to load. That will resolve the problem described here.

- https://github.com/department-of-veterans-affairs/component-library/pull/1083
