### ISSUE TITLE
va-select needs describedby property

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#2587]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

While updating file upload document type selects from a React component to a USWDS v3 web component, I noticed that there isn't any way to connect the select to the file name. In the React component, an `aria-describedby` would point to the `<strong>` element containing the file name. To get around this, `va-select` would need a `message-aria-describedby` property,  similar to the one in `va-text-input`.

## What I expected to happen

While using a screenreader, and focus is moved to the document type select, the screenreader should include the file name

<img width="1015" alt="Voiceover screenreader window shown next to a document type select for a file named test.pdf. It displays the selected value of 'civilian police reports, document type (*required), required menu pop up collapsed, button, list 2 items' with no mention of the file name" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/7e361733-6abb-4125-b328-f983614716b3">

## Reproducing
- Formation version: Current
- Device: (e.g. iPhone 8, Macbook) Any
- Browser: (e.g. Firefox, IE 11) Any

Steps to reproduce:

1. Change a file upload attachment schema:
    ```js
    import VaSelectField from 'platform/forms-system/src/js/web-component-fields/VaSelectField';
    // ...
    attachmentSchema: () => ({
      'ui:title': 'Document type',
      'ui:webComponentField': VaSelectField,
    }),
    ```
2. Enable screenreader
3. Upload a document
4. Tab to select & note that the file name is not announced 
5. Tab to delete button and it will announce the file name to delete

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints - There are a few forms that need the `attachmentSchema` updated.
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2587?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
