### ISSUE TITLE
Sidenav component audit

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/vets-design-system-documentation#259]
### Description: 
Hierarchical, vertical navigation to place at the side of a page.

There might be a new side nav component design implemented (similar to the VAMC sidenav). The intended use for this component may overlap considerably with that new component.

Sidenav is **not** present in the [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design). 

Sidenav is present in [design.va.gov](https://design.va.gov/components/sidenav).

### These are the ways this component is not synced
- Sketch library focus state is not bolded, but in prod and design.va.gov it is
- Component not present in React library
### Complete the following tasks to synchronize component:
**Sketch library:** 
- In the artboard, "9-Navigation > Side navigation > Focus: Focus state needs to represent that text within the focused navigation element is bolded

**React library:** 
- Create an entry in the React library for the existing Sidenav and consider replacing it when the newly designed component is available
- Crosslinking  for creating a new template for the sidenav: department-of-veterans-affairs/vets-design-system-documentation: Issue #216

**Design.va.gov:** 
- Add additional details such as intended user cases, visual design, behavior, and accessibility considerations. Suggested details can be found [here](https://docs.google.com/document/d/1rCwo_CaRh_tSG7bdCmCahuXdPmBZiFgjV6oSN5q6MIE/edit).

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
