### ISSUE TITLE
va-process-list-item: allow the header font size to be adjusted based on the header level 

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2593]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The checkin-in app is unable to use the `header` prop on the process list items because the component, while it allows the `level` size to be adjusted, it's opinionated about the font-size. 

Initial discussion https://github.com/department-of-veterans-affairs/vets-website/pull/28550#discussion_r1525011795

## What I expected to happen

I expect the component to allow the flexibility to change the header font size based on the semantic needs of the page it's being used.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

The design system team might want to consider adding `h1, h2, h3, h4, h5, h6` font sizes to the component stylesheet or `part=header` to the header element so that it can be styled by teams.

This issue will block teams from migrating the USWDS version va-process-list if they need to change the header font-size.

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 3
@ataker - 3
@harshil1793 -  
@it-harrison - 3
@jamigibbs - 3
@micahchiang -
@powellkerry - 3
@rmessina1010 -
@rsmithadhoc - 3

**Comment by jamigibbs** [comment]
@brianseek Please feel free to add any other details that you'd like here.

**Comment by brianseek** [comment]
Thanks @jamigibbs I should point out that you can change the header level in the component with the `level` prop but you can't change the header level styling. Like in our case I needed an h2 styled like and h3.

**Comment by brianseek** [comment]
sure here is our page with the heading style as designed 
![localhost_3001_my-health_appointment-travel-claim__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (6)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/13967174/73129d9e-1a5a-4661-aa6a-d3b5ec086515)

Here is a link to our design: https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=642-3804&mode=design&t=ZbOpOlNmuM6Y2yh7-0

**Comment by brianseek** [comment]
ccing @benbrasso-agile6 in case there is any discussion needed around design

**Comment by brianseek** [comment]
here is a screenshot with the first process list item using the header and level props. With the level at h2. The second process list item left alone, it doesn't use the props and is an h2 with this class `vads-u-font-size--h3`
![localhost_3001_my-health_appointment-travel-claim_travel-pay (3)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/13967174/bc157f07-4574-4d0a-adc5-ffcae49e88d6)

**Comment by jamigibbs** [comment]
Thank you @brianseek! I've updated the description of the issue and I'll wrangle in some other DS folks to weigh in on this.
