### ISSUE TITLE
Update Figma form address pattern

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#2594]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Pattern

### What is the name?

Address

### What is the nature of this update?

- [X] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Currently the [design system](https://design.va.gov/patterns/ask-users-for/addresses) and the [mock form pattern](https://staging.va.gov/mock-form-patterns/mailing-address) for address have the city change to APO when the user checks the "I live on a United States military base outside of the U.S. ". Figma does not have this change in that design pattern. Can we please update Figma to match?

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2594?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by danbrady** [comment]
Correct me if I'm wrong, @LWWright7. Didn't you recently complete the address pattern that has this?

**Comment by LWWright7** [comment]
Yes! This was done in [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2480), @danbrady 

CC: @caw310

**Comment by caw310** [comment]
Closing since this work has been done.
