### ISSUE TITLE
va-accordion-item plus-sign changes size on hover

### ISSUE THREAD

**Issue by mmoyer-va** [department-of-veterans-affairs/vets-design-system-documentation#2598]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Mousing over the va-accordion-item changes the "+" icon to be small. The same thing does NOT happen when mousing over an open accordion. The "-" icon remains large.

This only seems to be happening in the version of the component using USWDS v3. It disappears if I set `uswds={false}`
 
### USWDS v3 screenshot ###
<img width="400" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/87040148/416d953a-3515-42a2-afb3-9ab954a058dc">

### USWDS v1 screenshot ###
<img width="400" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/87040148/0496b387-2bcd-4ade-a778-01621ff60073">

We noticed this while testing out the new component-library in MHV Medical Records, however the issue can be viewed now in staging at https://staging.va.gov/disability/ -- I'm guessing they have already upgraded to the new component.
<img width="400" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/87040148/9605fb2a-a061-4ce6-aea6-90336a298f68">

Tested on MacOS on Chrome and Safari.

## What I expected to happen

In the previous version of the component, the "+" icon remained the same size on-hover. Expected that to persist.

## Reproducing

The cleanest way to reproduce is:

1. Copied in the storybook code for `va-accordion` into the VA.gov application, outside of any app code that might change the CSS
2. I changed the accordion item to include `<va-accordion-item uswds ...>`
3. Browsed to the app and saw the issue.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment]
Hi @mmoyer-va! Thanks for reporting this. We recently made an update that fixes this issue though so I'm going to close this as a duplicate:

- https://github.com/department-of-veterans-affairs/component-library/pull/1083

The update will be in the latest component library release: https://github.com/department-of-veterans-affairs/component-library/releases/tag/v38.0.1
