### ISSUE TITLE
Document pattern for Ask users for a single response

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2611]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Pattern

### What is the name?

Ask users for a single response

### What is the nature of this update?

- [X] How to build this component/pattern
- [X] When to use this component/pattern
- [X] When to use something else
- [X] Usability guidance
- [X] Accessibility
- [X] Implementation
- [X] Research insights
- [ ] Package information
- [X] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

We need a pattern that speaks to how to implement the One Thing per Page content principle in our forms. We have examples now of nearly all of the form components and how to use them as the single element on a form page. But we need to show those in context and describe the implementation of each in greater details than just the storybook examples.

**Comment by caw310** [comment]
This was swapped in for icon web component documentation
