### ISSUE TITLE
Update component-library to USWDS 3.8.0 (if possible 3.8.1)

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2612]
## Description

[USWDS 3.8.0](https://github.com/uswds/uswds/releases/tag/v3.8.0) has been released. We will need to update the packages with the new version and also look at any new features or bug fixes that may need component updates too. [slack convo for reference](https://dsva.slack.com/archives/G01BJ3ESXL4/p1711045489565529)

For example:

**checkbox**

> This is a feature of usa-checkbox that I'd like to bring in to support some teams who have asked for it:

> Added styles for indeterminate checkboxes. Checkboxes will now display as indeterminate when you set input.indeterminate = true via JavaScript or add the data-indeterminate attribute. This is only a style addition and does not affect checkbox functionality.

**button group**

> We should also look into this bug fix and see if it helps out our issues with the same problems in button-group:

> Improved the appearance of button groups when button text wraps to multiple lines.

**checkbox indeterminante state**

Separate ticket here:

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2652

## Tasks
- [ ] update uswds package(s) to v3.8.0
- [ ] address any component updates that might need to happen

## Acceptance Criteria
- [ ]

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2612?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
https://github.com/uswds/uswds/releases
