### ISSUE TITLE
eliminate live instances of FontAwesome in the text styles

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/vets-design-system-documentation#262]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## purge FontAwesome as a font from the Sketch library, and only use the icon symbols our library already contains (or add as needed)

A few paragraph styles use fontawesome for some reason, and even tho I have that font on my machine, I constantly get a "missing font" error in Sketch. When you look at the text styles, you can see the errors:

![image](https://user-images.githubusercontent.com/12564977/87579070-5e29fb80-c6a3-11ea-8c11-58f05d2fdde1.png)

My recommendation would be to get rid of every "live" instance of FontAwesome, and replace them with outlined versions, or with their respective symbols.

**Comment by CrystabelReiter** [comment]
Looking into this...just saw this now~

**Comment by CrystabelReiter** [comment]
Fixed this in the most recent sketch update. Closing now
