### ISSUE TITLE
Icons - Update Figma Components to use USWDS icons - Design

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2624]
## Description
Update Figma components to use USWDS icons.

Also validate the coloring of certain icons (warning, error, etc.) may no longer be needed.

Tasks:

- [ ] Confirm there is a 1:1 matching of USWDS icons from FA icons
- [ ] Confirm the naming for each icon component is accurate and easy for a designer to use and search for
- [ ] Validate if icons can/should have colors applied
- [ ] Audit all components and update any to use the USWDS icons
- [ ] Have another designer review updated components
- [ ] Publish updated components with note

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2624?planning-poker) with Zenhub @danbrady @LWWright7

**Comment by danbrady** [comment]
Adding a list of impacted components:
* Accordion
* Additional Info
* Alert
* Alert - Expandable
* Back to Top
* Banner - Maintenance
* Banner Promo
* Card
* Crisis Line Button
* Link - Action
* Link - Collection
* Modal
* On this page
* Process List
* Search Input
* Forms:
    * Autosave
    * Prefill
    * Privacy Agreement
    * Statement of truth

**Comment by danbrady** [comment]
@LWWright7 @babsdenney This is ready for review!

**Comment by LWWright7** [comment]
@danbrady This looks great! g2g
