### ISSUE TITLE
va-button: hover background should be white

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#2628]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

There is a [v1 bug report](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2083), but this ticket is for the v3 style

## What happened

When a USWDS v3 secondary button has a colored background, inside an alert or modal, the background turns transparent upon hovering the button.

![button-bkgd](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/cf5096d6-3bec-4fbf-8808-d4417d78b58b)

## What I expected to happen

After [discussing this behavior in Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1711475097770429?thread_ts=1710774255.547199&cid=C01DBGX4P45), it was determined that the background color should stay white

## Reproducing
- Formation version: All
- Device: (e.g. iPhone 8, Macbook) All
- Browser: (e.g. Firefox, IE 11) All

Steps to reproduce:

1. Go to [secondary button](https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary#secondary) in storybook
2. Open dev panel
3. In CSS, set hover state
4. Inspect secondary button background color - it shows as transparent

<img width="624" alt="dev panel with button in shadow root selected. A hover state is set on the button and the css shows that the background is transparent. This is overriding the usa-button hover state which sets the background to white" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/1c6b1d40-377d-40f2-82eb-8d0a95b4348a">

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2628?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
