### ISSUE TITLE
[Bug] Hint text loses its top margin when following a (* Required) label

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2629]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

In reviewing an upcoming form, it felt like the hint text was incredibly close to a heading. When I checked story book I saw the same thing. But, when the required label is removed, the margin above the hint text is what I was expecting.

## What I expected to happen

I expected hint text to always have a top margin of 1em regardless of a (* Required) label being used or not.

**Important caveat** I have not checked the other components to see if this happens in other places where hint text is used. But I assume it will also occur anytime hint text follows a required label.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. [Go to storybook radio group](https://design.va.gov/storybook/?path=/docs/components-va-radio--with-hint-text)
2. Change the parameters so that the label is an h3, that there is hint text
3. Observe in inspector that the top margin on the hint text is 1em
<img width="796" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/e1aa640d-0e59-40c7-ad77-f46377885073">
4. Toggle the (* Required) label to be true
5. Observe that the top margin on the hint text is lost
<img width="707" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/2955cfd7-cd21-4e04-9efb-8017bf80e362">

I think the issue is that the <span> for the required label breaks the css class that's looking only for headings to cause the separation between the hint text and the header.
```
h1 + *, h2 + *, h3 + *, h4 + *, h5 + *, h6 + * {
    margin-top: 1em;
}
```

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress but we have a workaround - This is impacting current forms, but it's not a big enough issue for now to block work.
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2629?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
@jeana-adhoc The screenshots look like it's for the v1 version. Is the USWDS (v3) version of radio ok?

**Comment by jeana-adhoc** [comment]
It is the v3 version


https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/b4b12f01-c62d-4a81-8be3-2fc9c28ada25
