### ISSUE TITLE
File Input - Multiple File Input

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2643]
## Description
After [2641](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2641) and [2642](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2642) have been completed, we need a way to support the upload of multiple files. [Here are the Figma Designs for it](https://www.figma.com/file/UZys4hvw2Vwuo7U0pwbKbq/File-Input-v3?type=design&node-id=71-25203&mode=design). 

## Considerations
- Multiple file input should use existing web components for its composition
- Multiple file input shouldn't: 
  - be in charge of uploading a file, we have file input for that
  - handle state, i.e. application engineers should be passing in handlers and a data structure to handle their own state
- The blue background in the designs isn't something we have in va-card or elsewhere. Should it be added to va-card as a variation, or directly used just for file input? 

## Tasks
- [ ] Add support for multiple file uploads

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2643?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
We're pausing work on multiple file input until we've completed single file input.

**Comment by caw310** [comment]
Since work on this has paused will move to the next sprint.

**Comment by caw310** [comment]
This issue will carry over into the next sprint as multiple file input is going to take more time to complete as it was handed off.

**Comment by rmessina1010** [comment]
Component functions correctly, closing ticket.
