### ISSUE TITLE
[va-checkbox] - Add Indeterminate State - Development

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2652]
## Description
In [USWDS 3.8.0](https://github.com/uswds/uswds/releases/tag/v3.8.0), the checkbox has a new indeterminate state. We should bring this capability into VADS. See https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3365#issuecomment-2426922846 for information on the preliminary accessibility revie and implementing this.

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 3
@ataker - 
@harshil1793 -  
@it-harrison - 3
@jamigibbs - 3
@micahchiang -
@powellkerry - 3
@rmessina1010 -
@rsmithadhoc - 3

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Contact designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2652?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
I just want to mention that we need to make sure we do an accessibility audit of this feature. There appears to be a [number of different ways](https://github.com/mui/material-ui/issues/20476#issuecomment-611468844) screen readers interact with the `indeterminate` state and we might find some challenges with that.

I also couldn't find an example on the [USWDS site](https://designsystem.digital.gov/components/checkbox/) of this implemented so it's difficult to check it before we start dev.

cc @rsmithadhoc

**Comment by jamigibbs** [comment]
Linking to the related ticket for updating to USWDS v3.8.0:

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2612

**Comment by danbrady** [comment]
> I also couldn't find an example on the [USWDS site](https://designsystem.digital.gov/components/checkbox/) of this implemented so it's difficult to check it before we start dev.

If it helps a11y testing or dev, the USWDS Indeterminate checkbox is in their [storybook](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-checkbox--indeterminate).

**Comment by caw310** [comment]
Ticket for a11y review for this. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3351

**Comment by caw310** [comment]
Added this [a11y audit ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3365) which we will work on before development of this.
