### ISSUE TITLE
Migrate V1 va-select to V3 in vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2659]
## Description
We will remove all v1 component code at the end of July. To do so, we need to migrate all remaining instances of v1 components to v3. This ticket is for migrating all remaining v1 va-select components. 

## Considerations
Remaining instances:

VaSelect | src/applications/mhv | vfs-mhv-integration
-- | -- | --

## Tasks
- [ ] Migrate v1 select to v3

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2659?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
`va-checkbox` is used as a child component in `va-statement-of-truth` and `va-privacy-agreement`
