### ISSUE TITLE
Improve NPM package publication docs

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/vets-design-system-documentation#266]
**Is your feature request related to a problem? Please describe.**
The [documentation](https://design.va.gov/documentation/contributing-to-formation#modifying-a-component) for modifying a component in Formation includes updating package version number, but does not describe the process to publish the updated package at https://www.npmjs.com/package/@department-of-veterans-affairs/formation

**Describe the solution you'd like**
Please add or update documentation for modifying Formation to include the process for getting the updated package published

**Describe alternatives you've considered**
IDK if this is something developers should be doing themselves, opening a ticket to have someone else do, should be handled by CI/CD, or what.

**Additional context**
https://dsva.slack.com/archives/C0NGDDXME/p1594066098012700

**Comment by mchelen-gov** [comment]
May overlap with https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/199

**Comment by rianfowler** [comment]
Needs discussion but off the top of my head: 

## short term 
- add [link](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/updating-formation) to documentation to README 
- review / update documentation 

## long term 
- separate the tools stuff into a separate repo
- remove everyone but bots / depo / VSP admins from the npmjs org
- create a pipeline for a bot to publish updates to npm when changes are merged 
- look into using private npm or github package management 
  - e.g. publish to private npm -> private npm CI publish from private npm to public npm 
  - private npm provides more resiliency to FE build / deploy against [public npm changes](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/)

**Comment by caw310** [comment]
Documentation exists here. https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/updating-formation/
