### ISSUE TITLE
Remove V1 Text Input and Textarea from Storybook

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2667]
## Description
On May 3 all V1 components will be fully retired except for va-table and va-file-input. To manage the significant amount of work to do this, we'll split the effort into several tickets. 

This ticket is for removing  V1 Text Input and Textarea from Storybook. 

## Tasks
- [ ] Remove  V1 Text Input and Textarea from Storybook

## Acceptance Criteria
- [ ]  V1 Text Input and Textarea  have been removed from Storybook

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2667?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
`va-text-input` is used as a child component in a few different places so this might be larger than we expect:

**Comment by micahchiang** [comment]
Closing since this is no longer needed.
