### ISSUE TITLE
Address Pattern Error Message for APO/FPO/DPO

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/vets-design-system-documentation#2672]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When testing the staging instance of the new Burial 21P-530EZ form, I selected the checkbox indicating that I live overseas on a military base and then tried to proceed through the form without entering any address information. The error message that appeared for the APO/FPO/DPO was: City is required
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/134541644/ea3bbb9e-1bc9-44c8-9059-9dfb10d598d0)

## What I expected to happen
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/134541644/5bc6d0b5-e07f-4401-ba9e-495fd589f6ab)

## Reproducing
- Formation version: V3
- Device: Apple, Desktop
- Browser: Chrome

Steps to reproduce:

1. Visit: https://staging.va.gov/burials-and-memorials/application/530/
2. Within "Your Information" on the "Mailing Address" page, select checkbox indicating you live outside the U.S. on a military base.
3. Leave other fields blank.
4. Attempt to proceed to the next step.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
@rhasselle-oddball and @jeana-adhoc - I'm guessing this might be specified in the address pattern? 

@laurwill - This error message isn't in the data I have from CAIA for this pattern: https://design.va.gov/patterns/ask-users-for/addresses#content-considerations Should it be? Seems like it.

**Comment by jeana-adhoc** [comment]
@humancompanion-usds - [This is in our address pattern in the mock form](https://staging.va.gov/mock-form-patterns/mailing-address)

I don't think this is about the same thing, but we were also tagged on another [military base address PR this morning](https://github.com/department-of-veterans-affairs/vets-website/pull/28840/files#diff-de4dd8bf12bd8b364a463b10f1f4a384c8f34ea55827773e17082fa5a9059708). I can't approve it since I'm not a dev, and @rhasselle-oddball is out today, but I thought I'd connect the pieces in case they are connected.

**Comment by laurwill** [comment]
Hi @humancompanion-usds @jeana-adhoc ,
Yep, looks like we missed this field in the csv for labels & errors on address pattern. We've added these suggestions to the file: 
Label: APO, FPO, or DPO
Error type 1: No selection
Error message 1: Select a post office type: APO, FPO, or DPO

**Comment by humancompanion-usds** [comment]
I fixed the issue Laura mentioned. I've now also have a PR attached to this to update the labels, errors, and hint text for a number of patterns, including addresses. After that PR is approved, @tbaker1026 - We'll need to fix this in the codified pattern for Address. You can take this issue to track it (i.e. you can move it to your repo)

**Comment by tbaker1026** [comment]
@humancompanion-usds thank you

**Comment by humancompanion-usds** [comment]
New issue created to get this changed in the Forms library. Closing this as the guidance piece is done.
