### ISSUE TITLE
Phone number input needs to allow more than 10 character for international numbers

### ISSUE THREAD

**Issue by fiorella-io** [department-of-veterans-affairs/vets-design-system-documentation#2673]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We are using the phone number input component on the form we are about to launch, Burial 21P-530EZ. One of the new fields we are adding is an international number field. The current phone number component only allows for 10 characters. We need an international version of this component.

## What I expected to happen

To not see the following error while entering more than 10 characters into the input field. 
<img width="541" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/91498500/64b08960-d6bf-4a05-b462-87f003b0ce6a">

## Reproducing
- n/a

Steps to reproduce:

1. Go to the [Burial form on staging](https://staging.va.gov/burials-and-memorials-v2/application/530/introduction)
2. Navigate to Step 1, Contact information
3. Enter a number larger than 10 characters
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment]
Here is the StackOverflow accepted answer:

```
\+(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|
2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|
4[987654310]|3[9643210]|2[70]|7|1)\d{1,14}$
```

At any rate, if your team is not using the codified pattern in the Forms Library then you can do this with the va-text-input today. Just change the label and the pattern prop regex. If you are using the codified pattern (and you should be), then we need to make a variation that supports i18n numbers, or change the accepted pattern to also accept i18n numbers. That decision needs to come to Design System Council thus making this an experimental request. So if you can clarify, we can get you on the docket.

**Comment by fiorella-io** [comment]
yes, can we extend the va-text-input pattern to support international numbers on a new international number field?

**Comment by steele-lm** [comment]
@humancompanion-usds Yes, this would be the phone number pattern. @Midge-dev confirmed that we are using the codified pattern, but it is built in a way where it needs it's schema helper to function correctly. We would have to implement our own custom pattern that uses the suggested regex and produces a v3 styled component.

**Comment by humancompanion-usds** [comment]
@steele-lm - You can have your team contribute a variation to the [phone number pattern](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/web-component-patterns/phonePattern.jsx) that offers support for an international number. Alternatively, I can put it on the backlog for the Veteran-facing Forms team to work on but, it will be awhile before we get to it. If you want to go the former route, your engineers can talk to @rhasselle-oddball or @ndsprinkle about extending that pattern.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2673?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Work for https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2885 will be done in this ticket.

**Comment by caw310** [comment]
Work for this ticket will encompass enabling international phone number in text input to accept phone numbers and update Regex.

**Comment by mtcA6** [comment]
Not sure if this helps but VA Profile (the backend for VA.gov Profile) is looking to expand support for international numbers. The guidance they gave related to numbers the BE will accept is:

> - For phone numbers with a country code of +1, that includes the +1 country code, a 3-digit area code and a 7-digit phone number.
> - For phone numbers with a country code other than +1, there is a county code from 1-3 digits and a phone number up to 12 digits.

**Comment by caw310** [comment]
This will carry over due to illness.
