### ISSUE TITLE
[TTY]: Add Font Awesome TTY icon to our design system for use with calls to action

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#2675]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor, Crystabel, Ryan_

## User Story or Problem Statement

As a TTY user, I would like to have the universal TTY icon included as a secondary cue for the linked 711 phone number in long-form prompts.

## Details

~~There's an open-source version of the TTY phone icon ( https://www.iconfinder.com/icons/1608964/tty_icon ) that we'd like to create an SVG from, and use in our long-form prompt. Language could be something like "If you are deaf or hard of hearing, call TTY: LINK 711".~~

UPDATE:
There's a Font Awesome version of the TTY icon https://fontawesome.com/v4.7.0/icon/tty that we should use for pairing with the approved call to action and helper text for https://github.com/department-of-veterans-affairs/va.gov-team/issues/23664

## Acceptance Criteria

- [ ] Font Awesome icon is added to Sketch file
- [ ] Font Awesome icon is available for use in Design System

**Comment by humancompanion-usds** [comment]
@caw310 & @danbrady - This issue was languishing in va.gov-team with our label but not in any pipeline. So I transferred it over to our repo. I'd like to handle adding this in va-icon and to va-telephone for TTY. Thanks.

**Comment by Andrew565** [comment]
This issue has been resolved, there is now a TTY va-icon available.

**Comment by humancompanion-usds** [comment]
This is done and there is another issue to have it added to guidance and/or the va-telephone component.
