### ISSUE TITLE
Label component audit 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#268]
### Description: 
Labels draw attention to new or important content.

Labels in the sketch library, design.va.gov, and react library are out of sync.

You can view the component in [design.va.gov](https://design.va.gov/components/labels)

### These are the ways this component is not synced

- Label component is missing from the sketch library and react library

### Complete the following tasks to synchronize component:
**Sketch library:** 
- Add label component to artboard, "7- Content presentation"

**React library:**
- Add label component to react library 

**Design.va.gov:** 
-Should we consider decapitalizing the "label" of the label? Sentence case is best for accessibility reasons
- Add examples of interactive versions of these labels (I've seen more teams use these as tags)

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
