### ISSUE TITLE
account_circle VA USWDS V3 Icon Not Rendering in Staging

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/vets-design-system-documentation#2680]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We are trying to use the icons in the USWDS V3 system.  These icons are displaying correctly in our developers' local build, but they are not displaying as expected in our Staging environment.

[Staging for Find a Representative](https://staging.va.gov/get-help-from-accredited-representative/find-rep/) -- the Representative Status Widget under the "Check your current accredited representative" header does not have the icons displaying.

## What I expected to happen

This is the intended design, and what we are seeing in the local build:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/142453186/a98480a9-3642-4112-8a80-d2fed264226b)

## Reproducing
I am viewing Staging in a Chrome browser (Version 123.0.6312.59), on a Mac (OS 14.1.2).  

Steps to reproduce:

1. [View Staging](https://staging.va.gov/get-help-from-accredited-representative/find-rep/)
2. See that the icons are not present, despite the reference in the code when inspecting the element

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/142453186/792ca926-6952-474c-ba4d-5b447033e899)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details
While this is not blocking any work for the Accredited Representation Management team, icons are a significant part of our [Widget designs](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2268-79606&mode=design&t=IHfyejZouDQR6eQF-0) and we hope to include the icons with our MVP launch (currently targeted for a 5/6-5/13 staged rollout).

**Comment by caw310** [comment]
Adding as unplanned work for sprint 51 as it is blocking other iconography work.
