### ISSUE TITLE
Typography Step 1 Completion: Merge component-library and vets-website PRs

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#2681]
## Description
This task is to wrap up the work done in formation, component-library, and vets-website to set the base font-size to 16px. Once teams have a chance to review, this work will be to merge PRs and publish packages to push these changes to production.

### component-library:
- Update the package.json files for css-library, react-components, web-components, and core to remove the `beta.0` versioning
- Merge the [PR](https://github.com/department-of-veterans-affairs/component-library/pull/1096) and publish

### vagov-content
- Merge [PR](https://github.com/department-of-veterans-affairs/vagov-content/pull/934)

### content-build
- Merge [PR](https://github.com/department-of-veterans-affairs/content-build/pull/2011)

### vets-website
- Update package.json to remove `beta.0` from package dependencies
- Merge [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26606)

## Acceptance Criteria
- [ ] vets-website is released with new base font-size

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2681?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
