### ISSUE TITLE
checkboxGroupUI: No support for message-aria-describedby

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/vets-design-system-documentation#2685]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

- Using the existing pattern for checkbox v3 web-component doesn't allow passing `messageAriaDescribedby`

## What I expected to happen
- I expected to have an aria label when passing `messageAriaDesribedby` via `uiOptions` in the `checkboxGroupUI` pattern

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/57480791/8e0f2011-7e59-4f5b-a972-98cbae9c765b)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
- [21-530V2 schema (vets-json-schema)](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/21P-530v2/schema.js)
- [*BUILT* 21-530V2 schema (vets-json-schema)](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21P-530V2-schema.json)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2685?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
This is a forms library issue. Hoping the forms team can work on this.

**Comment by ndsprinkle** [comment]
@Midge-dev Hey, just wanted to get some clarification on this. Are you wanting to pass a single messageAriaDescribedBy to the checkbox group? Or do you need to pass it to a specific checkbox item in the group? I assume it's the former, but just wanted to make sure.

@caw310 From what I can tell, the design system web component for the checkbox group does **not** support passing in a messageAriaDescribedBy: https://design.va.gov/storybook/?path=%2Fdocs%2Fuswds-va-checkbox-group--docs

So if this is what @Midge-dev wants, then we would need design system work in addition to forms library work.

**Comment by ataker** [comment]
I believe this will have a similar solution to [this previous ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3059)
