### ISSUE TITLE
Component Analytics enhancement request: Provide context for <va-link>

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/vets-design-system-documentation#2693]
# Enhancement Request

- [X] I’ve chatted with Carol for any related issues and avoided creating a duplicate issue.

## Enhancement Request

For <va-link>, If at all possible, having some some context will be key in gathering meaningful analytics. 

For instance, if a user clicks a link within the header, if there was a 'header' flag, that would be helpful. We don't really need context specifics on the actual links, but knowing they are in the header would be helpful in finding analytics. 

## What I expected to happen

Randi Mays has supplied an example here:

On https://www.va.gov/service-member-benefits/, if you click "Certificate of Eligibility for a VA-backed home loan," we would expect to see the following in analytics for only using a <va-link>:

- Title of the link ("Certificate...")
- Origin page: [va.gov/service-member-benefits](http://va.gov/service-member-benefits)
- Destination URL: https://www.va.gov/housing-assistance/home-loans/eligibility

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [X] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by FranECross** [comment]
@caw310 Here is the component analytics enhancement request. I used the bug github form because all other DST tickets indicated internal only. Thanks so much! cc @johnny-jesensky-adhoc @randimays @chriskim2311

**Comment by randimays** [comment]
I had created this ticket a couple weeks ago: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2600 I'll close it as a dupe!

**Comment by randimays** [comment]
Adding that other ticket's description here:

> I checked with Jamie Stutt on the Platform Analytics team about the information that Google Analytics receives from DST web components. She said (specifically in regards to <va-link>) that the information being sent lacks the destination URL, so we cannot differentiate between web addresses and files (PDF, etc.).

Looking here: https://github.com/department-of-veterans-affairs/component-library/blob/a2ef00783db566809ad34386429cf1bb0926b1d5/packages/web-components/src/components/va-link/va-link.tsx#L87 we can add the details' href to send this information over. Further clarification with Jamie Stutt would be ideal to make sure DST is sending everything that the Platform Analytics team would prefer. This would help teams clean up their custom events.

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- tagging you here for visibility into this.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2693?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by randimays** [comment]
@jamigibbs 

> Isn't this already possible to do with the existing va-link analytics + additional Google dashboard settings?

I'm not sure about this; I have spoken to @jestutt about destination URLs on `<va-link>` a couple of times and she mentioned this is something that DST needs to add.

Re: closed ticket / dupes: Slack conversation for context: https://dsva.slack.com/archives/C01DBGX4P45/p1710536192355749?thread_ts=1709651393.696019&cid=C01DBGX4P45

I created the closed ticket (#2600) as a result of the Slack conversation above, but Fran didn't know about it when she created this current ticket (#2693), so I closed #2600 as a duplicate. This current ticket (#2693) is requesting the destination URL/href, which is the same thing #2600 was requesting.

**Comment by jamigibbs** [comment]
Thanks @randimays!

So for the DST estimating exercise, we should just be estimating for the work needed to pass the `href` prop value (which already exists) to the Google Analytics function here:

https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-link/va-link.tsx#L91-L93


Something like this:

```
      const detail = {
        componentName: 'va-link',
        action: 'click',
        details: {
          label: this.text,
          href: this.href
        },
      }
```

**Comment by FranECross** [comment]
@jamigibbs I believe  if the info isn't in the event, then we're not easily able to just query GA by event to get the info we need. I'm not a GA aficionado, though, so @jestutt , please correct me if I'm wrong. 

There are approximately 135 links in the header, and this so far is the most expeditious way to get the data. So, having context on the origin and then the destination is key.

For instance, when I'm querying GA now in order to get analytics for, say, the header... so that I don't need to query each link, I query for "Navigation - Header", and it will return all the different possible clicked links within the header e.g. 
- Navigation - Header - Health research - https://www.research.va.gov/ 
- Navigation - Header - Open Second Level - Innovation at VA
- Navigation - Header - Schedule a burial for a family member - https://www.va.gov/burials-memorials/schedule-a-burial

cc @randimays

**Comment by jestutt** [comment]
@jamigibbs @FranECross  Correct. If we're using dataLayer push events to track an interaction, all the information we want passed thru to GA needs to be in that dataLayer (exception for default info like page the event happens on). 

I expressed concern when the idea of using the `va-link` component and the attached event in the site navigation areas (header, footer, side) was first brought up to me -- see [Slack](https://dsva.slack.com/archives/CKCRMLGAC/p1712169849099989?thread_ts=1711566118.186519&cid=CKCRMLGAC). That tracking scenario needs more than the basic click text and click URL variables that _all link click tracking_ needs to have and it might be better served to leave those areas as custom tracking events or to create a new navigation component that includes nav specific variables like the location of the link and the section/grouping/level as well as the click text and click URL. It would also more easily account for the sub-nav clicks (the second in Fran's example list) that are not html links to start with.

**Comment by FranECross** [comment]
@jestutt Do you mind updating the 'What I expected to happen" section of this ticket to what the you (and analytics team) feels it should be? Then we on the PW team can then keep the custom events for header/footer, and make determinations on our other custom events depending on outcome. Thanks in advance! cc @randimays

**Comment by jamigibbs** [comment]
> Header (and footer) links are different and should be tracked differently with their own events rather than forcing the the va-link component's event to work in that scenario.

@FranECross I am reading through the convo here as well as the Slack message @jestutt  linked to (quoted above) and it sounds like the scenario being discussed about header/footer needs custom analytics. That means to me that:

1. `va-link` should have the `disable-analytics` prop set on those links, and,
2. The sitewide team should then use a callback on `onClick` to send whatever information needs to be tracked in analytics for header/footer links.

That means that the Design System Team won't be working on that specific scenario (maybe that requires a separate ticket for your team?) **but** we are happy to add the **destination and origin URL's** to the component library analytics if that's still needed (being done in [this PR](https://github.com/department-of-veterans-affairs/component-library/pull/1145) now). Those updates will be available in the next component-library release.

**Comment by jamigibbs** [comment]
@jestutt Just a head's up in case you need to make an update on your end, the `va-link` web component will have two new values in addition to the existing `link-label` once the next component-library release gets published:

1. `link-destination` (where the link is navigating to)
2. `link-origin` (where the va-link component is at)

Local testing:

<img width="595" alt="Screenshot 2024-05-14 at 2 12 33 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/376a160d-dc3c-481b-96c4-6fa29f213cbb">

**Comment by randimays** [comment]
Adding a side note to @FranECross that once the `va-link` has destination URL, we can do some discovery to figure out where we can fall back to `va-link` analytics versus custom events.

**Comment by jestutt** [comment]
@jamigibbs  No need to change but I might have suggested `link-url` and `link-location` which are the dashed version of the GA4 variable names. Next time :)

How do these two (2) work? Are they automated or does the FE have an option to define? I ask because there are some links where we want to capture something but not the actual URL. This scenario can be seen in [#72444](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72444).

**Comment by jestutt** [comment]
@jamigibbs  If everything is automatically pulling, then `link-origin` is redundant. Every event captures the page location an event happens on as part of the GA4 default tracking variables. 

> Are you finding that it's common for teams to disable the va-link design system analytics because it's getting double tracked in analytics (the component fires its analytics and the anchor link getting globally tracked fires analytics too)?

There's not a real easy way to tell if multiple events are being triggered/fired for the same interaction. They tend to be identified as those specific interaction locations or one of the events on a page are being reviewed and I flag them as I find them. It happens -- yet to work on a site where it doesn't -- but probably a lot less than you think. 

It is awesome that the design system's team has added these dataLayer push events -- it does make things easier particularly in the information available for capture. I think removing or changing the auto-enable setting for the `va-link` event would be a bigger problem than leaving it, esp now that you're fixing the biggest complaint I've heard about it by adding the click/destination URL.

**Comment by jamigibbs** [comment]
@jestutt Thanks for your thoughtful feedback!

**Comment by jamigibbs** [comment]
@FranECross The updates I mentioned previously are in the [v41.1.0 release of component-library](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v41.1.0) and that version is currently available in vets-website.

I believe this resolves the ticket for the work the design system team is able to do here so I'm going to close this issue.

**Comment by FranECross** [comment]
@randimays ☝🏼 Just an FYI in case you weren't alerted on updates to this ticket.
