### ISSUE TITLE
Formation typography base font-size change - replace all rem values in vets-website

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/vets-design-system-documentation#2695]
## Description

Replace all `rem` values in css, scss, jsx and html pages with their corresponding value based on a base font-size of 16px instead of 10px.

Changes should be made in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/26606

## Details
The base font-size is changing in formation from 10px to 16px. This will affect anything that uses `rem` values for spacing, sizing, etc. All of these values need to be updated in vets-website.

@jamigibbs has developed a tool to calculate what the new rem value should be here: https://jamigibbs.github.io/rem-to-rem/

**Comment by caw310** [comment]
Converted to an epic. We will write up smaller tickets to address this by 1-3 apps at a time.

**Comment by humancompanion-usds** [comment]
@caw310 and @micahchiang - Would one of you like the pleasure of closing this?

**Comment by micahchiang** [comment]
Get this ish outta here!
