### ISSUE TITLE
OMB Info component audit

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#270]
### Description: 
The OMB info component appears at the bottom of the form introduction page and shows:
- Respondent burden
- OMB control number
- Expiration date 
- Privacy act (link)

OMB info component in the sketch library, design.va.gov, and react library are out of sync.

You can view the component in the [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/ombinfo/)

### These are the ways this component is not synced

- OMB Info component is missing from the sketch library and design.va.gov
- There is no documentation on how to use this component in the react library

### Complete the following tasks to synchronize component:

**Sketch library:** 
- Add OMB info component to the artboard "6-Form controls"

**React library:**
- Add documentation on how this is used. Maybe place under a Forms Control section

**Design.va.gov:** 
- Add OMB info component to the Form controls section and add documentation. Sample documentation [here](https://docs.google.com/document/d/1GXIeK7Frg5UYNtcz7SBmsvnLkoknZFzUldXwZSHhvb4/edit?usp=sharing)

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
