### ISSUE TITLE
Typography - Update Application REM Values -auth and avs

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2701]
## Description
In addition to Global rem values, some applications specify rem values in their unique sass stylesheets. Those need to be updated in order for typography change to be a seamless experience. 

## Considerations
- rem values need to be scaled down for the 16px base font size

## Tasks
- [ ] update all rem values in auth and avs

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by jamigibbs** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/26606/commits/7879d27dddf9e144bc9bdf403060cb8bdb4c2d25

Did not find any `rem` values for avs.
