### ISSUE TITLE
Typography - Update Application REM Values - representative-search and search

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2719]
## Description
In addition to Global rem values, some applications specify rem values in their unique sass stylesheets. Those need to be updated in order for typography change to be a seamless experience. 

## Considerations
- rem values need to be scaled down for the 16px base font size
- inline rem values at [representative-search/components/results/SearchResult](https://github.com/department-of-veterans-affairs/vets-website/blob/dc066242866eb7cb251824297b22350df29d9ecf/src/applications/representative-search/components/results/SearchResult.jsx#L180)

## Tasks
- [ ] update all rem values in representative-search and search

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by rmessina1010** [comment]
Successfully applied commit to: https://github.com/department-of-veterans-affairs/vets-website/commits/66753-formation-global-overrides/
Closing.
