### ISSUE TITLE
Megamenu component audit

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#272]
### Description: 
The MegaMenu is the initial design for navigation between va.gov and vets.gov. The MegaMenu is dynamically generated through data. The intent is to have va.gov people be able to modify labels and links on the page without ever touching the codebase. We will be getting data from the original TeamSite system that runs va.gov.
Buttons in the sketch library, design.va.gov, and react library are out of sync.

You can view the component in the [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/megamenu/)

### These are the ways this component is not synced

- The sketch library has the "megamenu" component in the header pattern, but there is no expanded menu option
- There's no megamenu or main navigation section in the design system, only side navigation 
- In the react library, the images for the menu are broken and blurry

### Complete the following tasks to synchronize component:
**Sketch library:** 
- Add megamenu to the artboard "9-Navigation" and place them under the header sections. Create a desktop, tablet, and mobile version of the megamenu

**React library:**
- The images of the menu are broken. Can we fix these?

**Design.va.gov:** 
- Add the megamenu component to the design.va.gov
- Should we rename it main navigation? since we also have side navigation component? 
- Add documentation on how to use this component. Sample documentation is [here ](https://docs.google.com/document/d/1bfK3MaEyK3XWoKs12KY6RNcJ2CxVkTwdy-01yryXCAY/edit?usp=sharing)

**Comment by caw310** [comment]
Deprecated.
