### ISSUE TITLE
Typography - Update Application REM Values - simple-forms/mock-simple-forms-patterns-v3 and simple-forms/shared

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2723]
## Description
In addition to Global rem values, some applications specify rem values in their unique sass stylesheets. Those need to be updated in order for typography change to be a seamless experience. 

## Considerations
- rem values need to be scaled down for the 16px base font size

## Tasks
- [ ] update all rem values in simple-forms/mock-simple-forms-patterns-v3 and simple-forms/shared

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2723?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
