### ISSUE TITLE
Cannot change text of a continue va-button

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#2733]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I want to create a `va-button` with the `fa-angles-right` icon inside it with the words "Save and Continue", however va-button it doesn't support this use case. 

Desired:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/0113b4dc-7648-4922-83db-4fe9eaaf1849)

## What I expected to happen

If you pass `continue` to `va-button`, you should still be able to change the text

## Reproducing

- Formation version:
- Device: Windows 11
- Browser:  Chrome

Steps to reproduce:

1. Go to [storybook va-button](https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary)
2. Try to set both continue, and text
3. Notice you cannot change the text

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2733?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Hey @rhasselle-oddball - Is there a reason you'd need to pass `continue` to `va-button` and at the same time change the text? You should be able to change the button text by leaving `continue` off and assigning a string value to the `text` prop - https://github.com/department-of-veterans-affairs/component-library/blob/1f3b13dd020cf88cc0ddd82d3cc891684bc63c53/packages/web-components/src/components/va-button/va-button.tsx#L73-L76

**Comment by humancompanion-usds** [comment]
This is a duplicate this experimental request: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2362

At DSC we decided to allow for this. We just need to do that work. PRs welcome!
