### ISSUE TITLE
Empty va-official-gov-banner component 

### ISSUE THREAD

**Issue by nicksayre** [department-of-veterans-affairs/vets-design-system-documentation#2735]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When trying to use [va-official-gov-banner](https://design.va.gov/storybook/?path=/docs/components-va-official-gov-banner--default) in a Next.js project, it is rendered with an empty shadow root, and therefore doesn't display anything on the page.

**Screenshot showing display issue and empty shadow root:**

<img width="1468" alt="Screenshot 2024-04-15 at 10 14 27 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1807967/f5da6698-9899-40ba-b00c-7b06ed1a3eca">

**Screenshot showing importing React bindings and then exporting the Header Minimal (which contains the VA Official Gov Banner) with types for use with TypeScript:**

<img width="845" alt="import and add type info" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1807967/4c67b690-ca94-488d-b920-705da38401d5">

**Screenshot showing how the typed component is composed in TSX:**

<img width="752" alt="use component" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1807967/e80f4243-00c5-470b-9a33-6b25a52f3511">

## What I expected to happen

The VA Gov Official Banner should contain its content and display on the page.

## Reproducing

- Formation version: 10.1.2
- Device: MacBook Pro 16-inch, 2019
- Browser: Firefox 124.0.2

Steps to reproduce:

1. Clone the repo `git clone git@github.com:department-of-veterans-affairs/performance-dashboard.git`
2. `cd performance-dashboard`
3. Checkout the [branch](https://github.com/department-of-veterans-affairs/performance-dashboard/tree/va-gov-banner-bug) containing the bug `git checkout va-gov-banner-bug`
4. `npm i` to install dependencies
5. `npm run dev` -- the site will be available at http://localhost:3000/
6. Verify that the Official Gov Banner's shadow root is empty and that it doesn't display on the page

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2735?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Possibly related issue: 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77587

**Comment by jamigibbs** [comment]
Hi @nicksayre! Are you still having this issue? We made an [update to the build](https://github.com/department-of-veterans-affairs/component-library/pull/1297) that may have resolved this.

**Comment by jamigibbs** [comment]
Hi @nicksayre. I still haven't heard back from you about if [this update](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77587) fixed your issue but I'm feeling pretty confident that it has so I'm going to close this issue. But please feel free to re-open if you still need us to look into it.
