### ISSUE TITLE
Update button width for mobile modals in Figma component

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/vets-design-system-documentation#2740]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

At 375px wide, the buttons in the Figma modal component don't stack like they do in the actual web component. 

## What I expected to happen

At the 375px, the [Storybook component](https://design.va.gov/storybook/?path=/docs/uswds-va-modal--default) looks like this

<img width="428" alt="Screenshot 2024-04-18 at 12 37 09 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/95102058/18b12148-4ed8-40b4-bb94-20d4f79f0757">

## Reproducing

Steps to reproduce:

1. Insert an instance of the `Modal` component into a Figma file
2. Set width to 375px
3. Buttons don't stack

@ 375px
<img width="557" alt="Screenshot 2024-04-18 at 12 22 34 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/95102058/08c61a5a-8ada-4b6c-9a85-09dbb7221f0b">

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2740?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@danbrady / @babsdenney  This one is ready for [review](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=496-1719&t=Bg2TiLSiPePlENQv-1)!

**Comment by danbrady** [comment]
LGTM! Nice work.
