### ISSUE TITLE
Move content-build's breadcrumbs liquid logic to a liquid filter

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/vets-design-system-documentation#2741]
## User Story or Problem Statement

The breadcrumbs component in `content-build` will be converted to [the V3 component.](https://design.va.gov/storybook/?path=/docs/uswds-va-breadcrumbs--rerender-state) But first, the logic for modifying the breadcrumbs in the template must be separated into a liquid filter since the component will only accept an array of data objects. This filter must also be thoroughly tested, since the breadcrumbs component will affect most of the pages on `content-build`.

The current component update deadline is May 3.

This ticket is a blocker for department-of-veterans-affairs/vets-design-system-documentation#2742.

## Description or Additional Context 

The filter must cover the following points:

- [ ] It will receive the `crumbs` variable after it is potentially passed into the previous two filters, `deriveLastBreadcrumbsFromPath` and `deriveLcBreadcrumbs`.
- [ ] It filters out any breadcrumb objects that do not have `crumb.url.path`.
- [ ] It sets the URL for the final breadcrumb in the array to the `path` variable.
- [ ] If `crumb.url.path` equals `"/"` and `hideHomeBreadcrumb` is false, then it will use `customHomeCrumbText` for the breadcrumb's text (if available). If there's no custom text, it uses the text from the crumb object.
- [ ] All other breadcrumbs keep their URL and text data the same.
- [ ] The objects in this array are mapped to meet the specifications for [the V3 component](https://design.va.gov/storybook/?path=/docs/uswds-va-breadcrumbs--rerender-state)'s `breadcrumb-list` parameter.

Please reference `src/site/includes/breadcrumbs.drupal.liquid` for more details of what logic to carry over.

## Change management
Note: 57 products use the Liquid template for breadcrumbs, per Design System: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14724#issuecomment-1979334906

Not all of those products are Sitewide products. Design System has agreed to help code review on behalf of the other affected products: https://dsva.slack.com/archives/C01DBGX4P45/p1709666843934939?thread_ts=1709664794.685379&cid=C01DBGX4P45

We should also coordinate with DS team to get a change announcement posted for awareness, and/or report in Team of Teams, before we ship.

## Steps for Implementation

- [ ] The above filter requirements are met for the new filter
- [ ] Unit testing is added for the filter that tests all necessary variables and stress cases.

## Acceptance Criteria

- [ ] Implementation steps are met
- [ ] Prior to merge, notify PM / DM for change management outreach
    - [ ] PM/DM: Include in Team of Teams update when this is added to sprint
    - [ ] #vfs-change-announcements post prior to ship? (Collab with DS team to decide) 
- [ ] @department-of-veterans-affairs/vfs-public-websites-frontend is added as a code reviewer on related PRs.
- [ ] @micahchiang from Design System Team is added as a code reviewer on related PRs.
- [ ] @ndsprinkle from Forms Team is added as a code reviewer on related PRs.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2741?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
Will carry over due to Sitewide team needing more time to review. CC @jilladams
