### ISSUE TITLE
Replace content-build breadcrumb partial with V3 Component

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/vets-design-system-documentation#2742]
## User Story or Problem Statement

The breadcrumbs component in `content-build` will be converted to [the V3 component.](https://design.va.gov/storybook/?path=/docs/uswds-va-breadcrumbs--rerender-state) This ticket is for making the official transition to the component.

This ticket is blocked by department-of-veterans-affairs/vets-design-system-documentation#2741.

The current component updated deadline is May 3.

## Description or Additional Context 

* The "current link" at the end of breadcrumbs will appear as a visible link, while the current `content-build` breadcrumbs do not do this. This is an intentional and expected change.
* The component may need to be placed in a `div` wrapper with additional padding to ensure it keeps the same layout

## Steps for Implementation

- [ ] Use the new filter created in department-of-veterans-affairs/vets-design-system-documentation#2741 to create the `breadcrumb-list` array that will be passed into the component.
- [ ] Replace the HTML markup in the component with `<VaBreadcrumbs>` and pass in the `breadcrumb-list` along with any other needed arguments.
- [ ] If needed, add extra padding to a `div` wrapper to keep the layout and placement as consistent as possible with the previous breadcrumbs.

## Acceptance Criteria
- [ ] Implementation steps are completed
- [ ] Current tests and coverage are reviewed and if any new or updated tests are needed, that is noted
- [ ] Thorough QA testing is done on a wide variety of pages to properly assess impact and catch potential bugs
- [ ]  @department-of-veterans-affairs/vfs-public-websites-frontend is added as a code reviewer on related PRs
- [ ] @micahchiang from Design System Team is added as a code reviewer on related PRs.
- [ ] @ndsprinkle from Forms Team is added as a code reviewer on related PRs.
- [ ] Requires design review
- [ ] Requires accessibility review
- [ ] Tag PM to implement change management in collaboration with Design System Team.

**Comment by jilladams** [comment]
@caw310 thanks for moving this over! I don't have the power to change epics on it anymore -- would you mind removing the 2 Epics it was in before the move? (Same on #2741 )

**Comment by Andrew565** [comment]
This work has been completed in the above PR, just waiting on sitewide to approve.
