### ISSUE TITLE
Experimental Design Medications Icons

### ISSUE THREAD

**Issue by alexiawunder** [department-of-veterans-affairs/vets-design-system-documentation#2748]
## What

> We use three distinct icons in Medications on VA.gov that we would like added to the design system. 

## Purpose

> To differentiate the three most important statuses Veterans look for when scanning through their medications list

## Usage

> **Context or task**:  If a user is looking for which medications have been submitted, shipped, or are in process, they can easily  scan their lists for the corresponding statuses. Because the medications list is 20 cards long (due to the fact that on average, Veterans have about 15 active prescriptions at any given time) the list is easy to get lost in. 

## Behavior

> These icons are decorative.

## Examples

> <img width="286" alt="Screenshot 2024-04-19 at 2 58 17 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/102695187/fdd5a3d9-c54d-42b9-b273-81440f0e7bcb">
We are currently using: 
- Active Submitted: https://fontawesome.com/v5/icons/file-prescription?f=classic&s=solid
- In Process: https://fontawesome.com/v5/icons/file-export?f=classic&s=solid
- Shipped: https://fontawesome.com/v5/icons/truck?f=classic&s=solid

## Accessibility

> Since these are decorative, I believe we are using an aria-hidden attribute. 

## Guidance

> These icons are helpful status indicators. 

## Research (optional)

> Include any research you have already conducted, or plan to conduct, on this component or pattern.

## Code (optional)

> Include any existing code.

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
Discussed in DSC. @rtwell was able to share with us the examples of where this is used. Here are our thoughts:

1. We use the [Tag component](https://design.va.gov/components/tag) to convey status within a Card fairly consistently across the site. Or at least, it's the most common way we convey status. Thus you should explore using that component to start with.
2. We discussed whether icons could be used inside the Tag component but it raised concerns that it may start to make the Tag look interactive. It also gets close to our new [Button - Icon](https://design.va.gov/storybook/?path=/docs/components-va-button-icon--change-file) design. Thus we would recommend sticking with text.
3. If you try the Tag and feel strongly it won't work then we agree that the icons, at a slightly larger size, would work to make the status more scannable than just text. However, you'll need to use icons from the [USWDS set](https://designsystem.digital.gov/components/icon/), which we are moving to. That set pulls from Google icons so if you don't find what you need then reach out to @danbrady and he can help direct you to a set that you can choose from. That said, we'd want you to consider choosing more generic icons that work for those statuses and are not specific to RX as the statuses of submitted, in process, and complete (shipped) could be reused in other applications.

**Comment by alexiawunder** [comment]
Thank you. We will try out the tags, see how that looks, and get back to you.

**Comment by alexiawunder** [comment]
So we made a few mocks, and the tags defeat the purpose as it's entirely possible every card on the first page of their medication list could have a tag on it. I will reach out to Dan Brady for alternative icon options.

**Comment by alexiawunder** [comment]
We took our problem to a larger audience, and got feedback from other teams that these three icons would work for Medications and other tools. 

For submitted items, we chose "[Fact Check](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Afact_check%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)"

For items that are in progress, we chose "[Acute](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aacute%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)" 

For shipped items, we chose "[Local Shipping](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alocal_shipping%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)"

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/102695187/2394a503-51be-4f42-968b-c55c4b7542e1)

**Comment by humancompanion-usds** [comment]
We'll add these to the Design System. We may need to normalize in future but this is a start.

**Comment by alexiawunder** [comment]
Thank you!

**Comment by danbrady** [comment]
FYI: These three icons have been added to the Figma DS. 

Follow up issues:
* Dev ticket to [add to va-icon](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2872)
* [Add to guidance site](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2873)
