### ISSUE TITLE
System down view component audit

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/vets-design-system-documentation#275]
### Description
System down view is a means of presenting an easy to understand and user friendly system down message to Veterans. One primary message is required, and a second message with supplementary information is optional.

You can view the component in the [react library.](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/systemdownview/) 

### These are the ways this component is not synced
- In order to better align with VADS, the text within the button should be in sentence case.

### Complete the following tasks to synchronize component:
- **Sketch library**: Create an entry for the component
- **React library**: TBD
- **Design.va.gov**: TBD

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
