### ISSUE TITLE
Adjust memorable date on Figma

### ISSUE THREAD

**Issue by fiorella-io** [department-of-veterans-affairs/vets-design-system-documentation#2750]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using the memorable date on Figma, the error message does NOT hug the container it resides in making the error message overlap the fields under it. 

## What I expected to happen

The error message container should hug the text it contains 

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

This is Figma component. If you reduce the width of the memorable date to 288px or less and the words are longer than 2 lines this will happen:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/91498500/4b51cc93-12cf-450d-be25-93bf65f99475)

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2750?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
I worked with @fiorella-io directly in fixing this. This issue was determined to not be an issue in the component library. Closing this but please re-open if more issues arise. Thanks!
