### ISSUE TITLE
Buttons with icons are not formatted correctly in the Sketch file

### ISSUE THREAD

**Issue by mikang** [department-of-veterans-affairs/vets-design-system-documentation#276]
# Bug Report

- [yes] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I downloaded the Formation Sketch file, and I found that the "button with icon" components are misaligned. When I try to align them, I am unable to separate the text from the icon, and they move together. I am not able to fix the misalignment.

## What I expected to happen

I expected the Sketch file to exactly mirror the styles on the Formation website.

## Reproducing
- Formation version: last updated May 12, 2020
- Device: Macbook
- Browser: N/A

Steps to reproduce:

1. Download the Sketch file https://design.va.gov/documentation/code-and-design.html
2. Open the Sketch file
3. Look through Symbols

![image](https://user-images.githubusercontent.com/3641394/88495044-8c45f000-cf6d-11ea-93a6-a2f53b72b0b6.png)
![image](https://user-images.githubusercontent.com/3641394/88495065-9ff15680-cf6d-11ea-9944-a42752514783.png)
![image](https://user-images.githubusercontent.com/3641394/88495096-b7304400-cf6d-11ea-8f51-2adedc18499a.png)

**Comment by CrystabelReiter** [comment]
@mikang Hi! Thanks for putting in an issue for this. Can I ask what version of sketch were you using? This current version is only compatible with sketch 51.3 and symbols break when opened in newer versions

We're working currently on updating the library to Sketch 67, so *fingers crossed* this will get fixed.

**Comment by mikang** [comment]
Hi @CrystabelReiter! Thank you for your response. I am using Version 67.2. I'll use Version 51.3 for now. How will I know when this is fixed?

**Comment by mikang** [comment]
Hmm, I downloaded Version 51.3, and I'm still having the same issue. What should I do?

![image](https://user-images.githubusercontent.com/3641394/89135588-67a8c580-d4e3-11ea-8877-d9957379ea65.png)

**Comment by CrystabelReiter** [comment]
@mikang Hm that's strange. I'm checking mine and it looks fine here. Want to send me your slack name and I'll send my file over to you?

We'll update the sketch file to version 67 by Tuesday afternoon.

**Comment by mikang** [comment]
Awesome! I'll check back on Tuesday. Which Slack should I join?

**Comment by CrystabelReiter** [comment]
@mikang the DSVA slack! you can DM me at Crystabel Reiter if you want try to work it out tomorrow :) ! In the meantime, feel free to break symbols and make it work.

Sorry for the inconvenience! Hope the next update will solve these issues.

**Comment by mikang** [comment]
@CrystabelReiter What is the link to DSVA Slack? I'm sorry - I'm looking through Google but can't find it 😞 

I broke the symbols and have a modified version now that I can share, if that would be helpful. I can't attach it here, but I will DM you on Slack!

**Comment by KevinMHoffmanUSDS** [comment]
@mikang Hello! My name is Kevin, and I'm the manager of the VA.gov Design System at Veterans Affairs. This repo is public because we are a United States government agency and we work out in the open. However, we focus our bug fix efforts and our support for individuals that are actively developing applications for Veterans that work with our office directly. Are you a part of a team building an application for Veterans working directly with VA's Digital Experience and Product Office?

**Comment by mikang** [comment]
Hi @KevinMHoffmanUSDS! I am not part of a team developing for Veterans, but I was just exploring the design system. It's a nice robust example. I was trying to be helpful by reporting the bug.

**Comment by CrystabelReiter** [comment]
@mikang Thanks for reporting the bug. We will be updating the sketch library tomorrow that will be compatible with Sketch 67.

**Comment by KevinMHoffmanUSDS** [comment]
@mikang Thank you so much for reporting the bug! This should be resolved in tomorrow's update, but please feel free to let us know if you find anything else. Cheers!

**Comment by mikang** [comment]
Great! Thank you @CrystabelReiter

**Comment by CrystabelReiter** [comment]
@mikang we've updated yesterday. How do the buttons look now?
