### ISSUE TITLE
Update documentation for `aria-describedby` attribute/functionality to va-button

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#2770]
## Description

Per [this comment](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2739#issuecomment-2075371633), we should update our documentation with additional guidance for this update.

## Acceptance Criteria
- [x] Documentation has been updated.

**Comment by caw310** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2770?planning-poker) with Zenhub @rsmithadhoc
