### ISSUE TITLE
Add Sorting to Borderless Table  - Development

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2771]
## Description
Add Sorting to the v3 Borderless Table . Be sure to add analytics if necessary, see [guidance](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

USWDS Sorting example here: https://designsystem.digital.gov/components/table/#sortable-table-rows

## Details
- Design documents: https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=6089%3A652&mode=design&t=09EBu70iVXFcUZL0-1 
- Review accessibility considerations added to component design ticket (if any)
- Review [Design System Engineering Best Practices document](https://vfs.atlassian.net/wiki/spaces/DST/pages/2176516116/Design+System+Engineering+Best+Practices)

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Contact designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json
- [ ] Add analytics set-up to `vets-website` repository. See [guidance here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
- [ ] Analytics has been configured for the component in the `vets-website` repo

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2771?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
@danbrady @LWWright7 @babsdenney -- just want to check if we are diverging from [uswds sortable table](https://designsystem.digital.gov/components/table/#sortable-table-rows-2) with respect to focus states:

uswds:

![Image](https://github.com/user-attachments/assets/a3680929-ae7b-4b36-8125-42663ca5aa55)

dst:
![Image](https://github.com/user-attachments/assets/48604643-891f-4488-abe1-6e7aeb51482d)

**Comment by danbrady** [comment]
@it-harrison Thanks for pointing this out, Ian. A few thoughts:

* The current yellow focus ring in VADS in our sorted table is yellow *only* because that is the standard focus ring color throughout the majority of all other components. It's not "right", because...
* Both yellow (VADS) and blue (USWDS) focus rings in a sorted column header have inaccessible color contrast.
* This is a known (and deceptively tricky) issue and one that @davidakennedy is factoring as he works through the larger in-progress [focus ring research](https://github.com/department-of-veterans-affairs/vads-focus-styles).
* We can update our designs once accessibility weighs in on the right direction to take.

CCing @rsmithadhoc

**Comment by it-harrison** [comment]
@micahchiang given Dan's comment re focus/color-contrast above, is it ok to close the associated [PR](https://github.com/department-of-veterans-affairs/component-library/pull/1358) that follows current DST convention, with the idea that we will update the component when this issue is sorted out?
