### ISSUE TITLE
Accept terms prompt component audit 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#279]
### Description: 

The accept terms prompt is used in the healthcare section. 

The accept terms prompt component in the sketch library, design.va.gov, and react library are out of sync.

You can view the component in the [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/accepttermsprompt/)

### These are the ways this component is not synced

- The component is not in the sketch library or design.va.gov 
- Component documentation does not match component functionality. Terms prop is not well defined.

### Complete the following tasks to synchronize component:
**Sketch library:** 
- Should we add this to the sketch library? Should the privacy agreement be aligned with this?
- Maybe this can live in the templates section 

**React library:**
- The information inside the terms and conditions prompt does not match the copy on va.gov, can we update it to reflect real word content? 
- Write component documentation that matches component functionality. Define terms prop

**Design.va.gov:** 
- Do we need this on design.va.gov? Could we add this to the patterns page?

**Comment by CrystabelReiter** [comment]
![Accept terms prompt](https://user-images.githubusercontent.com/18386248/89070346-de5a8d00-d342-11ea-9223-bd1c96743fdf.png)

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
