### ISSUE TITLE
Add icon name mapping to va-icon ESLint migration script

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2791]
## Description

Now that we have the [Font Awesome names mapped](https://design.va.gov/foundation/icons) to a USWDS name, we'd like to update the ESLint migration script to automatically fill in the mapping name to the `icon` prop.

We might be able to do something similar to like what was done for [mapping new utility classes](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/eslint-plugin/lib/rules/use-new-utility-classes.js).

**References**

- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/1025
- [Name mapping chart](https://design.va.gov/foundation/icons)

## Tasks
- [ ] update the `prefer-icon-component` migration script so that the mapped USWDS icon name auto-populates

## Acceptance Criteria
- [ ] given a provided Font Awesome class name, the mapped USWDS icon name populates for the `icon` prop in the va-icon migration script

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2791?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
Previous (Font-awesome) and current (USWDS) icon names as found on the design.va.gov site are accessible in yml format here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/2797f1d4310b81227f52489036324e085dbf6744/src/_data/icons.yml

**Comment by caw310** [comment]
This will carry over due to an error which is a blocker.
