### ISSUE TITLE
Experimental Design Back Link

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#2797]
## What

> Give a brief description of the component or pattern you want to propose.

A back link with a gray arrow.

[See this thread for background](https://dsva.slack.com/archives/C01DBGX4P45/p1711643398155559)

## Purpose

> What problem does this component or pattern solve for the user?

Currently appointments use descriptive back links with the format `< Back to [Heading of previous page]` for our details pages. This link replaced the breadcrumb, but followed the design pattern that breadcrumbs use on mobile.

With the breadcrumb updates, [the mobile breadcrumb now uses a gray arrow instead of a carat](https://design.va.gov/components/breadcrumbs#default-at-mobile-viewport-width).

We'd like an option added to the link component that adds the left-pointing gray arrow so we can use this for descriptive back links. This will help keep the interaction of navigating to a previous page consistent whether the page uses a back link or the breadcrumb on mobile.

## Usage

> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.

This is a link that sends users back to a previous page.

## Behavior

> Describe the key interactions for this component, calling out any specific considerations for mobile.

The link includes a left-pointing gray arrow at the front, like the mobile breadcrumb. Otherwise it has all the same functions as a standard link.

## Examples

> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/2536801/5b283f60-a28e-44e8-a5ca-8cccdd7e518d)

See all screen sizes of [these details page designs](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011-195846&mode=design&t=1pKV5DZ7EJvdT0yK-4)

## Accessibility

> Include any accessibility considerations.

## Guidance

> What would you want to tell other teams about this component or pattern?

## Research (optional)

> Include any research you have already conducted, or plan to conduct, on this component or pattern.

## Code (optional)

> Include any existing code.

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by outerpress** [comment]
@Cieramaddox @sterkenburgsara FYI here's the ticket for updating the link component with a gray back arrow.

**Comment by sterkenburgsara** [comment]
Is the arrow a blocker to the more important back link updates?

**Comment by outerpress** [comment]
@sterkenburgsara it sounds like design council gave the go-ahead to this addition to the DS at office hours today. It'll be up to a team to build this out/contribute the code. Is that something Cartography can take on? 

(Correct me if I'm wrong on any of this @Cieramaddox @erinrwhite @allison0034 )

**Comment by erinrwhite** [comment]
Hi @outerpress our meeting yesterday was just Platform office hours, which is separate from Design System Council. Tagging @allison0034 for suggestions on next steps.

**Comment by allison0034** [comment]
Hi @outerpress , Erin is correct, you will still need to present and get approval from DSC. Let us know if we can help.

**Comment by wesrowe** [comment]
@outerpress, I want to level-set expectations on Cartographers' involvement with this backlink change. I haven't seen anything to make me think this is a high priority for us. We have a pretty long list of work that I believe will have more impact on Veterans. If it hasn't gotten done by someone else we may have bandwidth to take this on a handful of sprints from now.

**Comment by outerpress** [comment]
@erinrwhite @allison0034 apologies! I got my design meetings crossed. I'll get this on the DSC calendar.

@wesrowe I'm not speaking to priority - the value-add here is small, and mainly about keeping the navigation UI visually consistent across health apps. I'm just trying to keep it moving forward in the hopes that we have it for when we update the breadcrumbs/back links. If we don't, we'll just create separate tickets and stick with using `< Back to [Previous page]` for our back links until the work is ready. I'll note at DSC that we're not sure who can/should be doing this work.

**Comment by caw310** [comment]
@outerpress This is on the agenda for the May 23 DSC meeting at 11am. I will add you to the meeting invite.

**Comment by danbrady** [comment]
Some items that came up during DSC to investigate further when the DST takes it on:
* Accessibility requirements - Focus management needs?
* Should it be a variation of `va-link`? (This would change icon color.)
* Since this is a substitute for breadcrumb, it should follow same top/bottom margins for alignment

**Comment by humancompanion-usds** [comment]
@jeana-adhoc adds:
> if the back link is not a crumb, should it still be in a `<nav>` region like the current breadcrumbs

**Comment by humancompanion-usds** [comment]
@micahchiang - Let's discuss next week whether this should be an instance of va-link or va-breadcrumb.

**Comment by outerpress** [comment]
In case it helps, here's how we coded the back link in the appts tool. This doesn't include the gray icon arrow. We'll update this to use the component once it's ready. FYI @vbahinwillit 

```html
<div class="vaos-hide-for-print xsmall-screen:vads-u-margin-bottom--0 small-screen:vads-u-margin-bottom--1 medium-screen:vads-u-margin-bottom--2">
    <nav aria-label="backlink" class="vads-u-padding-y--2 "> 
        <va-icon icon="navigate_before" size="2" class="vads-u-padding-y--0p25 vads-color-gray-medium hydrated"></va-icon><a aria-current="page" class="active" aria-label="Back link" href="/my-health/appointments/schedule/location">Back</a> 
   </nav>
</div>
```

**Comment by micahchiang** [comment]
Decision: DST will look into adding "back link" functionality as a `va-link` variant

**Comment by LWWright7** [comment]
From a design perspective, for Figma, this is the exact same thing that already exists as a variant for the [Breadcrumb component](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=798-931&t=mkQXot8FDs860zr4-1).  Do we really need to add a variant of this to link?  Or does this suffice?


![Screen Shot 2024-08-23 at 11 13 32 AM](https://github.com/user-attachments/assets/fba7f1c8-8f10-42c6-be4e-d6a811ef9ed0)

**Comment by jeana-adhoc** [comment]
The "Back link" will be the same on both desktop and mobile in this case. So, it might be confusing if someone is using a desktop page, but has to select the mobile variant? Also, the text will say "Back" or "Back to x". If we don't provide it as a figma variant, we need to have really explicit documentation about when this is used and how to construct it in figma.
