### ISSUE TITLE
Include more <a>'s in the button code snippet examples.

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/vets-design-system-documentation#28]
@kevwalsh commented on [Mon Mar 11 2019](https://github.com/department-of-veterans-affairs/design-system/issues/260)

As a design system user looking to see if i could use `<a>`'s for buttons, it took me a long time to figure out if it was OK. I looked at code snippets first, which are almost all `<button>`'s (except for "Big buttons, Primary". I still wasn't sure if it was OK to use it for other variants, until i read the help text at the bottom.  Including more `<a>`'s in the code snippets for other variants would be helpful.

**Comment by jaredcunha-usds** [comment]
@kevwalsh - Thanks for flagging this! I've gone and updated the documentation to better address this. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/commit/18af03b2dabef1e26527315c7130828ca4659f3c

Here's the page: 
https://department-of-veterans-affairs.github.io/vets-design-system-documentation/components/buttons.html

Let me know if that clears up your issue.

**Comment by kevwalsh** [comment]
wow that was fast! looks great.
