### ISSUE TITLE
Expanding group component audit 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#280]
### Description: 
Expanding group components are used to reveal elements that become relevant based on a user's response.  

Expanding group component in the sketch library, design.va.gov, and react library is out of sync.

You can view the component in the [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/expandinggroup/)  and [design.va.gov](https://design.va.gov/patterns/supplemental-content)

 ### These are the ways this component is not synced
- Sketch library has this expanding group in the conditional fields section and the additional info section. The blue bar looks different in each section
- In the react library the expanding group is a component and in design.va.gov it's a part of several components in the patterns section: in supplemental content and wizards section 

### Complete the following tasks to synchronize component:
Sketch library: 
- Replace the turquoise bar in the additional info component with the symbol "conditional bar + padding" 

React library: 
- See all props used in the code example. The fourth prop expandedContentId has an unclear description that should be re-written to explain why an ID is needed for React CSS Transition Group.

Design.va.gov: 
- Consider adding the blue bar (expanding group) component to the component list and documentation on where to use it 
- Sample documentation is [here](https://docs.google.com/document/d/1kIV3afw89Rh3FvwcWTGWvX5D1Xb9ZQaPtI5t8B36bfo/edit?usp=sharing)

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
