### ISSUE TITLE
Remove v1 component guidance from v3 components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#2802]
## Description
Remove v1 component guidance from v3 components on design.va.gov. 

## Details
All of these components have a v3 version that VFS teams should be using so remove the v1 guidance for these components.
v1 COMPONENTS with a v3 version

- Accordion
- Additional info
- Alert
- Breadcrumbs
- Button
- Button pair
- Checkbox
- Checkbox group
- File input - KEEP? (until multiple file input is done) 
- Number input
- Pagination
- Privacy agreement
- Process list
- Progress bar - segmented
- Radio button
- Search input
- Select
- Summary box
- Table - KEEP (Until we have guidance for the v3 borderless table)
- Text input
- Textarea

## Tasks
- [ ] Remove v1 guidance for the components listed above.

## Acceptance Criteria
- [ ] v1 guidance for the components listed above have been removed..

**Comment by humancompanion-usds** [comment]
I missed a few:

* Button pair
* Modal
* Text input has mentions of v1 in the a11y considerations
* Number Input has mention of v1 in an alert
