### ISSUE TITLE
va-accordion Storybook - Icon headers should use va-icons

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#2807]
## Description
In the va-accordion Storybook there is an example showing how to make use of "Icon Headers", which currently utilizes Font Awesome icons. This should be updated to make use of va-icon components instead.

## Details
https://design.va.gov/storybook/?path=/docs/uswds-va-accordion--icon-headers

## Tasks
- [ ] Replace Font Awesome icons with va-icon components

## Acceptance Criteria
- [ ] Example code shows how to use va-icon components for Icon Headers

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2807?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
