### ISSUE TITLE
Add Table Example in Figma 

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#2809]
## Description

Add table component example to Figma on [this page](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=1879-677). 

## Details

The table component is complete in Figma and it just needs to be added to the Figma Example file above. 

See this ticket for any details - [USWDS v3 Borderless Table - Design#1859](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1859)

## Tasks

- [x] Add table component to Figma example file
- [ ] Review designs with PO and/or other DST designers

**Comment by danbrady** [comment]
@babsdenney LGTM! 🚀
