### ISSUE TITLE
New Components: Download, Video Link, and Accessibility Links

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/vets-design-system-documentation#281]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name:Download, Video Link, and Accessibility Links

Details at https://github.com/department-of-veterans-affairs/va.gov-team/issues/11852

**Comment by KevinMHoffmanUSDS** [comment]
Design System Council Feedback, 07/31/2020

Video: Add the new icon, add necessary documentation to design.va.gov for appropriate use of the "play" icon (for single videos) versus the YouTube icon (for linking to a channel.)

We recommend that these function more like "mini buttons" or in lists, as opposed to using these styles in paragraphs or text. Our recommendation is that this style does not appear in paragraphs or text. 

We'll need to add the download and play icons to formation to get this integrated. 

Related: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/159
Demo: https://plnkr.co/edit/aOhgB5ZjPx8IJb53?open=Hello.js&deferRun=1&preview

Final step: review this proposal further with a content person, such as @peggygannon, @DanielleThierryUSDSVA.

**Comment by CrystabelReiter** [comment]
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152

When adding these links include this documentation ^

**Comment by andaleliz** [comment]
Hi! Are you also considering the recommendation for the `download` link described in #11852? @KevinMHoffmanUSDS 's comment only mentions the video link so just want to clarify whether or not that's the only recommendation accepted...

Thanks!

**Comment by humancompanion-usds** [comment]
These variations are documented now and in Sketch: https://design.va.gov/components/link/#variations

We'll be adding them as web-components in an upcoming sprint.

**Comment by humancompanion-usds** [comment]
All of the Link variations are now web components: https://design.va.gov/components/link/
