### ISSUE TITLE
Experimental Design [new icon request: pill] 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/vets-design-system-documentation#2811]
## What

My HealtheVet has a special use case for icons in the case of the secondary navigation component for the health portal. We believe that the current mapping for one of the four health tool icons that will go into this component is not as clear as an alternative available in the Google material icon library.

We'd like to request the following for the **va-icon** library:
* removal of the `medication` icon (current mapped for medications/prescriptions)
* replace that with a new icon:`pill` from the Google material icon library

## Purpose

This icon will be used alongside references to the Medications health tool within My HealtheVet, including in the secondary navigation component that will soon live across the portal. 

## Usage

This icon is used in a few places across the My HealtheVet portal and broader auth experience, namely: 
* the My HealtheVet landing page (decorative only)
* the My HealtheVet secondary navigation
* MyVA

## Behavior

On very small devices (widths less than 400 px), icons within the My HealtheVet secondary navigation component are more than purely decorative. We leverage icons to serve as quick visual references, but also to help make sense of abbreviated text (i.e. Meds, Appts) that describe the four main health tools. 

## Examples

`Pill` icon in our Figma files for My HealtheVet secondary navigation:
<img width="368" alt="Screenshot 2024-05-14 at 4 38 36 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/115033532/f8f99355-c21e-4188-a82b-e09e988cc6fe">

## Accessibility

N/A

## Guidance

N/A

## Research (optional)

N/A

## Code (optional)

N/A

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by sterkenburgsara** [comment]
cc @jonathanjnelson @fmccaf1 @kfink24

**Comment by sterkenburgsara** [comment]
cc @fmccaf1 @katbrinkley

**Comment by jonathanjnelson** [comment]
@danbrady, 

The goal of launching the My HealtheVet on VA.gov secondary nav is June 5. The launch is dependent on this icon being brought into the design system. 

We are hoping to schedule a staging review next week so appreciate any eyes on this ticket.

**Comment by danbrady** [comment]
Thanks, @jonathanjnelson. That medication icon that was chosen because it is visually similar to the FA icon we had. We attempted to find the visually closest icon as we did the upgrade.  You can see all the comparisons on our [foundation icons](https://design.va.gov/foundation/icons) page:

<img width="952" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/c5d50b4a-5c1a-44db-8a58-1292b15a0fbc">

I'm a bit hesitant to replace this icon without knowing if other teams use it. That might not be the case, but we need to know for sure. I wouldn't want to change it for one team that negatively affects another in which it works for them.

It would take some time to see if that icon is out there already. Alternatively, we can add the "pill" to our set, which would be safer. (We could then deprecate the "medication" one if it's then found not to be used or "pill" would be more appropriate.)

@humancompanion-usds Thoughts on this and priority?

cc: @caw310

**Comment by fmccaf1** [comment]
Thanks for your reply @danbrady. Can we go ahead and add the "pill" to our set now? Is there any reason to wait on that?

cc: @humancompanion-usds

**Comment by danbrady** [comment]
I've added the "pill" icon to our Figma DS library and published, so that should be available in your designs now. 

@caw310 Can we add this as a dev task into the next sprint?

**Comment by caw310** [comment]
@danbrady is this urgent? If not, I'd prefer to put this in a future sprint after upgrade work is done.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2811?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by danbrady** [comment]
> @danbrady is this urgent? If not, I'd prefer to put this in a future sprint after upgrade work is done.

@caw310 I think we're trying to get these done because we don't want unavailable icons to hold up teams from switching to `va-icon`. This particular team also has a scheduled launch of June 5th. 

cc: @humancompanion-usds

**Comment by caw310** [comment]
@danbrady okay, let me try to get this into the next sprint.

**Comment by Andrew565** [comment]
To clarify, we won't be touching the existing medication icon, just adding the pill icon.

**Comment by humancompanion-usds** [comment]
I will add this to guidance.
