### ISSUE TITLE
Dropdown panel component audit 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#282]
### Description: 
The dropdown panel provides a way to hide information on a page by default until the user elects to display that information by clicking the drop down panel.

Dropdown panels in the sketch library, design.va.gov, and react library are out of sync.

You can view the component in the  [react library](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/dropdownpanel/)

### These are the ways this component is not synced

- There is no dropdown panel component in the sketch library in the symbols section. The dropdown panel exists within the global navigation header but there's no states (hover, closed, open) where the dropdown panel is by itself. 
- There is no dropdown panel component in design.va.gov 
- There doesn't seem to be enough documentation on how and where to use the dropdown panel in the react library 

### Complete the following tasks to synchronize component:
**Sketch library:** 
- Add the dropdown panel to the navigation section, with states on how it opens and closes

**React library:**
- Add more documentation on how and where to use the dropdown panel. 

**Design.va.gov:** 
- Add the dropdown panel to the components section 
- Add documentation on how to use it. Sample documentation is [here ](https://docs.google.com/document/d/18x1yUvTHVEqjcl16YUOqa8YwJpgSzO-DXZ26xJZ2_rM/edit?usp=sharing)

**Comment by caw310** [comment]
Closing as the team did an audit in Q2 2022
