### ISSUE TITLE
Update templates in VA.gov pattern library to include 508-compliant hierarchy

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/vets-design-system-documentation#284]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [x] Other - Templates in pattern library

## What is the name

@1Copenut Identified a 508 issue in heading hierarchy on the introduction and confirmation pages of some VA.gov forms, as seen in this issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12339 

This issue is also present in the Sketch VA Pattern Library file, within the Templates page. The headings are skipping from H1 to H3 in the example of an Apply page.  

## What is the nature of this update?

 The headings should skip from H1 for the page title to H2 for the subway map heading. 

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

![Screen Shot 2020-08-11 at 5.08.50 PM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/379a1ab4-0180-4405-a89a-4d44b0ae4dd2)

**Comment by CrystabelReiter** [comment]
Thanks for flagging @ccruzgra We'll definitely make this change in the sketch library template

**Comment by CrystabelReiter** [comment]
Updated sketch templates in this most recent update. Closing now
