### ISSUE TITLE
Experimental Design: 2 additional icons for va-icon component

### ISSUE THREAD

**Issue by gileswells** [department-of-veterans-affairs/vets-design-system-documentation#2841]
## What

> In migrating from `FontAwesomeIcon` to `va-icon` the team working on the VA Developer Portal has some icons that we have used in our portal that are not present in the current icon set available within the VADS and would like to request consideration for the following icons to be added.

## Purpose

> Unifying the iconography from prior to the `va-icon` migration to the post `va-icon` migration state as much as possible.

## Usage

> Used as either decorative or semantic icons in support of on page designs UX has created.

## Behavior

> People look at them (they're icons)

## Examples

> The filter bar at the top of the [Explore APIs](https://developer.va.gov/explore) page in the VA Developer Portal.

## Accessibility

> Accessibility concerns are already discussed and covered [here](https://design.va.gov/foundation/icons#accessibility-considerations).

## Guidance

> I will include the suggested table values (plus a related screenshot showing usage) that might be used within the [icons page layout](https://design.va.gov/foundation/icons#appointments) to fit the existing pattern on the page.

| Icon v3 name | FontAwesome class | Usage | Screenshot of current usage |
| --- | --- | --- | --- |
| sell | fas fa-tag | Filter icon, in a category or topic sense | ![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/304798/8bae373e-eeba-44f3-8c85-0d82dd9ee4ad) |
| key | fas fa-key | Used to show this text is related to something security related | ![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/304798/bf7021ee-3f17-454e-88b0-7683e615b791) |

## Research (optional)

> I searched for existing icons as recommended on the [figma page](https://fonts.google.com/icons?icon.set=Material+Icons&icon.style=Filled&icon.size=24&icon.color=%23e8eaed) linked from the documentation.

## Code (optional)

> As these are simply additional icons I cannot think of any code examples.

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
@gileswells icon requests will be handled async so you're not held up. 

@danbrady would you review and make sure there is no conflict and then add the icons if appropriate?

**Comment by danbrady** [comment]
Alright, the 'tag' and 'key' icons have been added to the Figma DS. We're working on adding them to web component and guidance site soon. Stay tuned...

**Comment by danbrady** [comment]
Adding link to [dev ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2872).

**Comment by danbrady** [comment]
Closing as icons are in sprite. Guidance site to be updated as part of #2914.
