### ISSUE TITLE
Va-Memorable-Date Web Component: Default Error Messages Overwrite Custom Error Messages

### ISSUE THREAD

**Issue by adam-antonioli** [department-of-veterans-affairs/vets-design-system-documentation#2856]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

For the `va-memorable-date` web component under certain conditions, the custom error messages are getting overwritten by the component's default error messages.

### Example

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/132934480/53db7bb8-8f22-4117-b2eb-6b8391c361ec

## What I expected to happen

For the `va-memorable-date` web component, the custom error messages should overwrite the component's default error messages.

## Steps to reproduce:

1. Implement a `va-memorable-date` web component in a form with custom validation following the method described [here](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--custom-validation).
2. Specifically, implement validation which conflicts with the existing default validation. For example: Check if the month is within the expected number range of 1<=n<=12 on an `onBlur` event and display an error, such as "My error".
3. Observe that the default validation is what is displayed instead of the custom validation ("My error").

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

Related ticket with additional information: https://dsva.slack.com/archives/CBU0KDSB1/p1715885793285659?thread_ts=1715787286.085509&cid=CBU0KDSB1

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2856?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by MichelleDieudonne** [comment]
@caw310 I see that you have added this to your planning, do you have an estimate for when this bug will be worked?  Right now this blocking some of our PI committed functional work.  Thank you!

**Comment by caw310** [comment]
@MichelleDieudonne No estimate on when we will get to this. Hoping in the next sprint or two. However, we have our sprints planned out working on the upgrade.

**Comment by MichelleDieudonne** [comment]
@caw310 Good Morning! Checking back in to see if all were able to decide when you will be pulling this item for work.  We are approaching the end of our PI and since this is a committed item for us we will need to determine our next steps based on your response. Thank you!

**Comment by caw310** [comment]
@MichelleDieudonne This is tentatively scheduled to be worked on in our next sprint which starts June 20.

**Comment by Mottie** [comment]
Related ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/65647

**Comment by MichelleDieudonne** [comment]
@Mottie with the related ticket linked above, will this issue be fixed during this sprint?  We are coming to the end of our PI and need to know how to communicate to our customer around our work that this is affecting.  Thank you!

**Comment by caw310** [comment]
We had to move this to the next sprint due to other higher priority work.
