### ISSUE TITLE
Add icons for the mobile app

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/vets-design-system-documentation#2865]
## What
The mobile app team would like to add 6 Material icons to the VADS sprite to replace the old FontAwesome icons. A similar icon was not found in the existing VADS or USWDS icon collections.

## Purpose
Currently, the mobile app is still using FontAwesome icons. By adding these icons, we’ll be able to fully migrate to the new VADS/USWDS/Material icons. Also, these icons could potentially be used on the web in the future.
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/82840483/de4d8be6-94d1-42d9-ac6e-4f576f45ed84)

## Usage
- **circle** - used as dot indicator for unread messages
![IMG_4437](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/82840483/45fa468a-80d0-41fd-964d-b8ab26132b12)

- **crop_square** - used for bullets
![IMG_4439](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/82840483/85f442c7-49c1-43d0-b08a-6b2a53300007)

- **inbox** - used when moving message to inbox folder
![IMG_4438](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/82840483/a1f42fe8-9ad4-4c1b-a857-c1c55c529b57)

- **local_shipping** - used for prescription tracking
![IMG_4440](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/82840483/85771762-ff84-4ae5-b7f9-3a95327bb60b)

- **refresh** - used to refresh webview template
![IMG_4441](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/82840483/1397ea8a-bbb2-4855-84ce-6bbc16836924)

- **smartphone** - used to start text message
![IMG_4442](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/82840483/3896574b-4153-4637-baad-a74e5e645e2c)

## Behavior
None

## Examples
Screenshots included above.

## Accessibility
None

## Guidance
None

## Your team
Mobile app design system team (submitted by @jessicawoodin and @narin)

## Research (optional)
N/A

## Code (optional)
No code necessary, but presumably .svgs would need to be added to the icons folder of [dst-uswds-compile](https://github.com/department-of-veterans-affairs/dst-uswds-compile), a new sprite would need to be generated, added to [component-library](https://github.com/department-of-veterans-affairs/component-library), and released to NPM

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
@danbrady - Can you pull these icons in as well during our iconpalooza swarm?

**Comment by danbrady** [comment]
Ok, I've added the `local_shipping` and `refresh` icons to Figma DS. (`phone_iphone` can be used for smartphone.) [Here is the dev issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2872) to track when these are added to `va-icon`.

Per discussion with @humancompanion-usds, we didn't add the square and circle. We will be moving away from squares for bullets in the near future. Also, the circle as a status indicator is currently going through the exploratory phase so guidance isn't quite there yet.

**Comment by danbrady** [comment]
Follow up issues:
* Dev ticket to [add to va-icon](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2872)
* [Add to guidance site](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2873)
