### ISSUE TITLE
Experimental Design [identified icons for use on MHV landing page and secondary nav]

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/vets-design-system-documentation#2874]
## What

The Cartography team, which governs and works on the MHV landing page as well as movement to and between MHV apps (secondary navigation), is seeking to move forward with newly chosen Material Design icons currently within the VADS Component Library.

## Purpose

With the secondary nav especially, we use the icons to help users of different abilities to identify health tools based on what works best for them, whether that be image (icon) or text. 

## Usage

These icons will be used alongside references to MHV health tools, both within the secondary nav and on the landing page. We plan to use the same icon for each mention of the health tool. For example, the Medications tool will be associated with the same icon both within the secondary nav and the landing page.

## Examples

Secondary nav (mobile):
<img width="550" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106624475/6ff0cde4-af74-459b-9a2d-1d042193319d">

Landing page with icons:
<img width="575" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106624475/35764d07-c230-49bd-b791-a362a09a8671">

## Your team

Cartography Team (MHV to VA.gov)

## Next steps

I'm hoping to complete this work async if possible. Let me know if it would be better for me to find a time to present instead.

**Comment by caw310** [comment]
@fmccaf1 con requests will be handled async so you're not held up.

@danbrady would you review and make sure there is no conflict and then add the icons if appropriate?

**Comment by danbrady** [comment]
@fmccaf1 - These icons are available in in your screenshots are published in Figma and the web component. Below are the icon names the web component uses:

* calendar
* forum
* pill [1]
* medical_records
* attach_money
* medical_services

[1] We've identified an issue with this icon not showing up in our storybook and is currently being looked into. However, it should be correctly published on vets website.

cc: @Andrew565
