### ISSUE TITLE
Guidance - Records thumbnail color incorrect

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#2878]
## What happened

Records and Life Insurance colors on doc site appear to be the same color even though guidance points to different USWDS color tokens.

## What I expected to happen

The thumbnail color should match the token value.

![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/0c04b986-8f70-45f5-a6b9-6041bb332f9f)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2878?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
