### ISSUE TITLE
Update docs to reflect notClickable change for Telephone component

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/vets-design-system-documentation#288]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [X] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

_Unsure what this refers to_

## What is the nature of this update?

_Unsure_

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Telephone component has been updated to add a notClickable prop: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/373

Documentation should be updated accordingly

**Comment by bkjohnson** [comment]
@k80bowman I couldn't find a dedicated page on design.va.gov for documentation on the telephone component where this could go, but we do have a description of the web component prop in storybook:

![image.png](https://images.zenhubusercontent.com/5db75d6f1484010001787ee1/1e6eb56f-5dbc-46e9-b8fa-863c374bdf17)

**Comment by k80bowman** [comment]
We should probably add documentation for the telephone component on design.va.gov. I can add a ticket for that.

**Comment by caw310** [comment]
This has been done.
