### ISSUE TITLE
Within va-link, allow for custom sizing and alignment of the va-icon

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/vets-design-system-documentation#2890]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

There are cases where the `va-link` component with an embedded icon is used in conjunction with individual `va-icon` and `va-link` components. In these cases, the icon sizes and alignment do not match and engineers do not have a way to adjust the embedded icon in order to make them match. The embedded icon is smaller than the `va-icon` size 3:

![Screenshot 2024-05-30 at 10 14 06 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106678594/319d6f83-dade-4885-9b38-6b8595b2f012)

## What I expected to happen

Allowing for the custom sizing of embedded icons within the `va-link` component would assist in ensuring that all icon sizes match when used with standalone icons. With custom sizing, alignment should also be allowed, because when the sizes change, the alignment is not always going to be exact, example, when the active link uses a size 3 icon the alignment needs to be adjusted:

![Screenshot 2024-05-30 at 10 19 09 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106678594/ba2d3ce1-9221-47be-9a42-c79478c3fc7f)

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1.
2.
3.
4.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Closing as there is an issue for DST to update va-link to address these issues. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2880
