### ISSUE TITLE
Accessibility discussion points for 8/28 meeting

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#290]
## This update is for:

- [ ] Scrolling behavior
- [ ] Focus haloes for non-interactive elements
- [ ] Error handling exploration

## What is the nature of this update?
I have three items I'd like to bring to the council for possible future research and improvement.

### Scrolling behavior
Our forms and React apps rely on a [JavaScript smooth scrolling behavior](https://github.com/fisshy/react-scroll/blob/master/README.md) in multi-step forms, and some long content pages. This behavior has been highlighted as a possible hindrance for users with vestibular issues like vertigo, nausea, dizziness, that can be triggered by parallax or smooth scroll behaviors. I'd like to discuss if we want to seek out if this is an issue for our users, or if it might be good to remove the smooth scroll in favor of the native browser "jump cut".

### Focus haloes for non-interactive elements
Headings (H2, H3, H4, etc) don’t normally take keyboard focus. It’s my opinion showing the yellow focus halo is somewhat unexpected on elements that wouldn't normally receive focus. I’ve talked with Linsey at the VA 508 office about not showing the halo on headings when we focus them using JavaScript. She took it to her peers for review, and they were in agreement.

Sometimes it makes sense to show the yellow focus halo, like when we add a `<p>` tag into the tab order with `tabIndex="0"` but not as much when we focus a heading after pressing the Continue button on a form. I'd like to get the council's take on these strong opinions, loosely held.

The USWDS website doesn't offer clear guidance on this point:
* https://designsystem.digital.gov/utilities/font-size-and-family/
* https://designsystem.digital.gov/utilities/text-styles/

### Error handling exploration
We have a few forms that have an option to contact the person filling them out, and fields toggle between optional and required based on how users answer. I'm not sure this is the best way to capture the ask, and wanted to see what the council thought:

<img width="695" alt="Screen Shot 2020-08-27 at 4 48 38 PM" src="https://user-images.githubusercontent.com/934879/91498588-a41ed580-e885-11ea-93d4-660ea2be6afd.png">

**Comment by caw310** [comment]
Closing as this is an old ticket from before DS team was established.
