### ISSUE TITLE
User flows for getting to authenticated tools

### ISSUE THREAD

**Issue by mpeterz** [department-of-veterans-affairs/vets-design-system-documentation#291]
# Feature Request

- [X ] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [X] Pattern
- [ ] Utility
- [ ] Other

## User flows for getting to authenticated tools

We need a consistent flow for taking users to tools. Now different tools have different flows. 

Resolving this issue calls for IA, content, and design expertise. We need to figure out: 
* What is the flow? (Does the user go straight to a tool after signing in?)
* What content goes on what page? (If we take signed-in users directly to a tool, are they missing important content on the static tool page?)
* Which components go where? (This is related to the right rail because many tool pages have right rail content.)

## What is the nature of this update?

It's a flow pattern that may contain page patterns within it. 

- [X] How to build this component/pattern
- [X] When to use this component/pattern 
- [X] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Below is a rough flow. This is a work in progress. We would like to form a working group to help figure this out (IA, content person, and designer). 

A related issue is that during sign-in, either the unauthenticated static tool page or the homepage flashes on the screen briefly, depending on the flow. Sign-in is happening “on top” of the page. 

![user-flows-to-auth-tools-v2](https://user-images.githubusercontent.com/20934443/91612807-2d004480-e94c-11ea-8e3c-d5b6406a913d.png)

**Comment by mnorthuis** [comment]
Updated flows: 

![image](https://user-images.githubusercontent.com/20994159/91612414-feca3700-e942-11ea-8c1f-dbb40cc75e76.png)

**Comment by caw310** [comment]
closing as this is an old ticket
