### ISSUE TITLE
Update error status of va-alert component to be consistent with other statuses

### ISSUE THREAD

**Issue by agravell047** [department-of-veterans-affairs/vets-design-system-documentation#2910]
## What

I'd like to add an optional `message-aria-describedby` property to the `<va-alert>`, so we can give more context to the user about the alert when it's shown. 

## Purpose

For alerts with a status of "error" specifically, the `<va-alert>` only announces: "main, alert, group". Whereas alerts with other statuses announce the content of the alert.

## Usage

A developer adds `<va-alert>` to their page and needs to use status="error". They now have the option to add an `message-aria-describedby` property that will allow them to give more context to the SR user about what the alert is for.

## Behavior

The `<va-alert>` component will accept an aria-labeledby and when passed into the component announces this instead of the aria-label that is there now. If it is not passed into the component, it will fallback to using the aria-label. 

## Examples

Here is PR that added the same property to the `message-aria-describedby` prop
https://github.com/department-of-veterans-affairs/component-library/pull/1139

## Accessibility

This will improve the user experience for SR's only

## Guidance

I'm not sure if this is possible with the way we are assigning `role=alert` to the web-component directly. I think this could potentially override this new prop and still cause nothing to be announced.

## Collaboration Cycle Ticket

None (not sure what this is)

## Your team

MHV Medications team 

## Research (optional)

When the success alert becomes visible, it announces everything that is contained within the alert. However, when the error alert becomes visible, it only announces "main, alert, group". This is because there is an added aria-label property only for error alerts. This adds a navigable item for SR's and stops the SR user from knowing what the alert is about unlike the success alert.

Code:
It looks like this code is creating a role only if the status is "error":
[https://github.com/department-of-veterans-affairs/component-library/blob/72af25b32[…]41/packages/web-components/src/components/va-alert/va-alert.tsx](https://github.com/department-of-veterans-affairs/component-library/blob/72af25b32[%E2%80%A6]41/packages/web-components/src/components/va-alert/va-alert.tsx)

And then it sets the aria-label based on the role here:
[https://github.com/department-of-veterans-affairs/component-library/blob/72af25b32[…]41/packages/web-components/src/components/va-alert/va-alert.tsx](https://github.com/department-of-veterans-affairs/component-library/blob/72af25b329606c3b058f52ad1bf5fcff5ad4d241/packages/web-components/src/components/va-alert/va-alert.tsx#L197)

Instead we would add the new prop to be used by the screen reader instead of aria-label.

## Code (optional)

Nonw

**Comment by agravell047** [comment]
@caw310 ok thank you!

**Comment by caw310** [comment]
I will put this on the June 20 DSC instead since you are not available on June 14. The meeting is at 11:05am ET on Thursday, June 20. I will add you to the invite.

**Comment by caw310** [comment]
Follow up from DSC
- Add to backlog to fix in upcoming sprint
- Ryan to describe what we need to do.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2910?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by rsmithadhoc** [comment]
For the other statuses, the `role` is handled outside of the component. But for `error`, there is special logic inside of it that looks outdated. I believe what we need to do is make `error` consistent with the others, since those seem to function as intended, and then test across all the main screen readers.

```
    const role = status === 'error' ? 'alert' : null;
    const ariaLive = status === 'error' ? 'assertive' : null;
```
