### ISSUE TITLE
[DESIGN] Update the heading style of multiple page forms to match code going to production

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#292]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [x] Pattern
- [ ] Utility
- [ ] Other

## What is the name

We've updated the visual styling of our multi-page form header with [PR 14024](https://github.com/department-of-veterans-affairs/vets-website/pull/14024) to fix an iOS bug. We should update the Sketch file to match.

## What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [x] Implementation
- [ ] Research insights
- [ ] Package information

**Comment by CrystabelReiter** [comment]
@1Copenut Update the sketch templates. Looks like I'll have to delete the chapter titles from our sketch file for a future update. I'm going to keep this open as a reminder

**Comment by CrystabelReiter** [comment]
This was updated in the most recent sketch update

**Comment by KevinMHoffmanUSDS** [comment]
@CrystabelReiter is going to chat with Becca on VSA regarding UXPin sync issues.
