### ISSUE TITLE
va-link doesn't support external links

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#2922]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I was updating one of our font awesome links to use `va-link`, and noticed it doesn't support `target` or `rel` so that it opens on a new tab, nor an icon for external links (if we want one).
Example (Ask VA) and also example privacy policy
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/29742c3f-2583-4c45-b9f2-d61ddf77a10a)
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/94a38d64-00b9-4fb7-a539-c60c614e1c0b)

## What I expected to happen

Support for external links, so it opens in a new tab, and possibly an icon if desired.

## Reproducing

- Formation version:
- Device: Windows
- Browser: Chrome

Steps to reproduce:

1. Go to [va-link storybook](https://design.va.gov/storybook/?path=/docs/components-va-link--default) and notice it doesn't provide support for this.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2922?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by humancompanion-usds** [comment]
Hey @rhasselle-oddball - We're not able to get to this quickly. You have 2 paths: 

1. Switch back to just using a regular old HTML link
2. Contribute a PR to add this functionality

**Comment by caw310** [comment]
@artsymartha68 we do not have a ticket for updating guidance for va-link. I will create a ticket for that.

**Comment by danbrady** [comment]
Upon an [accessibility review](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3224#issuecomment-2377462666), the recommended approach is use "(opens in a new tab)" text and not an icon. So the DS will be removing the external icon and va-link variation.
