### ISSUE TITLE
Search isn't returning results

### ISSUE THREAD

**Issue by mattschoemaker** [department-of-veterans-affairs/vets-design-system-documentation#2929]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

<img width="1765" alt="Screenshot 2024-06-11 at 7 02 09 AM (2)" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1721764/03fec4a8-2ecc-4828-bd65-4157518c59c5">

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1.
2.
3.
4.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment]
Hi @mattschoemaker 👋 Thanks for reporting this. We've made [an update](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2927) that should have this fixed now. I'm going to close this issue but if you're still having trouble, feel free to follow-up.
