### ISSUE TITLE
Update or create usage script to look for font awesome icons

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2932]
## Description
In order to better track which teams are responsible for remaining font-awesome instances, we should update our existing cli script or create a new one that outputs which vets-website applications and teams still need to migrate to va-icon. 

## Considerations
- Script should look for occurrences of `<i>` tags using font awesome classes, which are usually ordered in this pattern: `className="fas fa-<some-icon-name>"`
- For each occurrence, we may be able to cross reference file path with the vets-website [CODEOWNERS file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS) to get an idea of which team owns the application

## Tasks
- [ ] Update the existing component usage script or create a new one that generates the above information in a .csv file that can be uploaded to google sheets

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2932?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
