### ISSUE TITLE
va-link active variation wrapping behavior

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#2938]
## Description

When the `va-link` component is used with the `active` prop set, the arrow icon does not wrap appropriately with the flow of content in different viewport sizes.

https://design.va.gov/storybook/?path=/docs/components-va-link--docs#active

![before](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/5447ff56-4fa8-4ade-81f7-1d1db5a67c9c)

Example in production (check various browser sizes):

- https://www.va.gov/north-orange-county-vet-center/

Feedback from this PR: 

- https://github.com/department-of-veterans-affairs/vets-website/pull/30089#discussion_r1635552655

## Tasks
- [ ] update `va-link` so that the trailing `active` icon wraps with text instead of dangling on its own

## Acceptance Criteria
- [ ]

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2938?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
closing as a duplicate of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2595
