### ISSUE TITLE
VaFileInput component delete button

### ISSUE THREAD

**Issue by ediiotero** [department-of-veterans-affairs/vets-design-system-documentation#2940]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using the VaFileInput component as its used in the docs [here](https://design.va.gov/storybook/?path=/story/uswds-va-file-input--default) I am not able to get the vaChange function to fire when clicking the delete button. It works in the docs but does not work in my project on vets-website app ask-va. I tried it on different pages and components to make sure it wasn't a problem with the page I was working on. 

I put an alert or a console.log in the vaChange prop for the component and I can see it fires when picking a file to upload and when changing the file but does not fire when clicking delete. I am keeping track of the files within the state of the component I am building when a user clicks delete it is removed from the UI but because vaChange isn't called I can't detect the button was clicked to update the state.

Slack convo with support [here](https://dsva.slack.com/archives/CBU0KDSB1/p1718385116479119)

## What I expected to happen

I expect the function passed to the vaChange prop to fire so I can update the state of my component.

## Reproducing

- Formation version: Current version in vets-website
- Device: (e.g. iPhone 8, Macbook) Macbook pro
- Browser: (e.g. Firefox, IE 11) Chrome

import VaFileInput in React. Use component and pass a function to the vaChange prop, test with an alert or console log. Function should be called with first click to add a file, change file, and delete file.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2940?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
I could not replicate this bug - I believe the support request was the result of user error. I have reached out to the engineer with this information and am awaiting a response.
