### ISSUE TITLE
v3 File Input should have a success alert

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2947]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

In CAIA Pilot testing for the Form Upload project, we realized a screen reader user has no indication that their file has successfully uploaded.

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/fe16a44e-f2ab-447b-8dc3-235aa9f20b96

## What I expected to happen

After the file upload is complete, a success alert to appear in the file upload box that also receives focus and announces that the file has successfully uploaded.

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook) Macbook
- Browser: (e.g. Firefox, IE 11) Chrome + Mac Voiceover

Steps to reproduce:

1. Enable a screen reader - I used Mac Voiceover
2. Navigate to https://staging.va.gov/form-upload/21-0779/upload  (you'll have to be logged in)
3. Upload a file
4. listen for a notification that your file successfully uploaded
5. You won't hear a notification.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

### Details

I don't believe this would be considered launch blocking, and probably an accessibility-defect-2. Mostly annoying/confusing.

**Comment by humancompanion-usds** [comment]
@jeana-adhoc and I talked about this over Slack. We agreed that we should just announce that the file has been added rather than have a success state. We would have found this I suspect in a11y view from @rsmithadhoc but Jeana got there first. So we definitely have a fix to make here but we don't need another visual state.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2947?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by rsmithadhoc** [comment]
It did announce success in the initial version, but seems to have been lost when we made the visual updates for the multiple file input. So there may be clues in the file history for getting this to work again.

**Comment by rsmithadhoc** [comment]
I believe it should also alert on Change File or Delete File, so a screen reader user is notified that those operations were successful.
