### ISSUE TITLE
Remove Font Awesome from content-build

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2948]
## Description
On June 20th, we will be re-adding the eslint error for font awesome, meaning teams will need to migrate to va-icon as they work. Our original plan was to remove the font awesome dependency from vets-website and content-build on June 26th. On the 26th, we'll take a look at how many instances there are remaining, including in css files and test assertions, and remove the rest ourselves. 

## Considerations
- Most font awesome icons are used by their css class names, though some are referenced directly in stylesheets
- Since we're waiting to take action on this until the 26th, there's an expectation here that it could carry over into the next sprint depending on number of remaining instances. 

## Tasks
- Replace all inline font awesome classes with va-icon

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by micahchiang** [comment]
Sitewide has an [issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18326) that should address all of these, but we can keep this open for the time being to track the progress and ensure nothing slips through the cracks.

**Comment by caw310** [comment]
Closing this one as the work for this ticket is being done as part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2944
