### ISSUE TITLE
Down chevron in mobile header is getting wonky when mobile template gets taller

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#295]
# Bug Report
## What happened
When I add the mobile template to an artboard and make it taller, the down chevron in the `Here's how you know` link at the very top of the header gets misplaced and stretched. In my example, it's overlaying the `Contact Us` link.
![Screen Shot 2020-09-01 at 4 43 50 PM](https://user-images.githubusercontent.com/55992116/91904263-a5c80f00-ec72-11ea-9a92-edcf1fc6ad12.png)

## What I expected to happen
I could resize the mobile template height without anything going astray.

## Reproducing
- Formation version: latest pull from GH today
- Device: (e.g. iPhone 8, Macbook) macbook
- Sketch version 68.2

Steps to reproduce:

1. Create a 2000px tall artboard
2. Insert > Symbol > Pattern library > template > mobile
3. resize the height to 2000px tall

**Comment by CrystabelReiter** [comment]
Thanks for catching this @andaleliz 

I'll correct this in the next update

**Comment by CrystabelReiter** [comment]
This should be fixed in the most recent sketch update
