### ISSUE TITLE
Update guidance for headings in Summary box component

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/vets-design-system-documentation#2955]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

Summary box

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [X] Usability guidance
- [ ] Accessibility considerations
- [ ] Content considerations
- [ ] Implementation
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Currently in the summary box ["How to use" section](https://design.va.gov/components/summary-box#how-to-use-the-summary-box-component) there is guidance that implies only an H3 or H4 heading should be used. This should be updated to make it clear that H2 level headings are also acceptable as long as that is the correct heading level within the context of the page.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2955?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by babsdenney** [comment]
Part of this ticket work would be to understand any development requirements or properties needed to make sure a H2, H3, or H4 can be used.

**Comment by babsdenney** [comment]
@laflannery Thank you for submitting this issue! We have updated the [Summary box documentation](https://design.va.gov/components/summary-box) to included H2 heading levels. Could you verify that this is correct?

**Comment by laflannery** [comment]
@babsdenney Looks good to me, thanks!
