### ISSUE TITLE
Allow ability to exclude H2s from On the page component

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/vets-design-system-documentation#2956]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The [On this page component](https://design.va.gov/components/on-this-page) currently pulls every H2 on the page into the table of contents and there isn't a way to exclude specific H2s if needed. We have a use case where we would like to add the Summary box above the  OtP but this would cause a poor user experience because the anchor link would take the user UP the page instead of down. 

## What I expected to happen

We would like the ability to exclude specific H2s from the OtP component so that if there is an H2 above the component, there isn't a chance of a user selecting a link and moving up the page.

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1.
2.
3.
4.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other

### Details
Screenshot of what we are proposing:
The link "What type of services do Vet Centers provide?" is the link that would take the user up instead of down:
![Screenshot 2024-06-24 at 9 03 04 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/106678594/7ee0fd35-50bb-4d2c-b71c-bc365d85360a)

This bug is not entirely blocking work in progress but it does introduce undesirable behavior. We are going to go forward because this work does have stakeholder priority attached to it

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2956?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by laflannery** [comment]
@caw310 If this ticket gets worked on, is it possible to review [this related ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1998) in tandem? It's something that continuously surfaces in the VA Automated AMP scans and would be good to move forward if possible CC: @artsymartha68

**Comment by caw310** [comment]
@laflannery we will evaluate when we are going to pull this ticket into a sprint.

**Comment by laflannery** [comment]
Thanks! CC: @aklausmeier for awareness

**Comment by aklausmeier** [comment]
This is also occurring on [VBA Portland](https://www.va.gov/portland-va-regional-benefit-office/) page.

**Comment by aklausmeier** [comment]
Hi @caw310 curious if there is an anticipated ETA for this fix?

**Comment by caw310** [comment]
@aklausmeier no ETA at the moment. I will put it in a future sprint probably late Nov or Dec as we are booked until then in terms of sprint work.

**Comment by Andrew565** [comment]
@aklausmeier @laflannery The va-on-this-page component finds h2s based on two criteria:

1) They must be a descendant of an `article` element
2) They must have an ID attribute

I know it's not always desirable or feasible to change away from using an `article` element, but I think in both your use cases you should be able to remove the ID attribute from the h2 and then the on-this-page component will not include those h2s in its list.

**Comment by aklausmeier** [comment]
@Andrew565 Our team will look into this and the feasibility of removing the ID in Drupal's content build.

**Comment by laflannery** [comment]
@Andrew565 we were able to to this by adding an exception in the content-build function
