### ISSUE TITLE
SSN Masking in Forms

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/vets-design-system-documentation#296]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Social security number text fields in forms

## Do you have a suggestion for a new component or utility?

For added security measures for VA.gov users completing forms, it would be helpful to have their social security number masked by default with the user having the option to reveal it, such as by clicking an eye icon or some kind of show/hide option next to it. An example of masking can be seen when typing in a password on many sites.  

## Additional context

An example of a social security number field, usually found on Applicant Information pages of forms: 
<img width="356" alt="Screen Shot 2020-09-02 at 4 01 38 PM" src="https://user-images.githubusercontent.com/41477797/92030900-b55c5c00-ed35-11ea-9786-06b975af77a8.png">

An example of the eye icon toggle found online:
![eye-icon-toggle](https://user-images.githubusercontent.com/41477797/92031387-872b4c00-ed36-11ea-8cb1-2c0d9787d5bb.png)

**Comment by caw310** [comment]
Closing as it was addressed by 18093
