### ISSUE TITLE
va-omb-info modal overflow

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#2962]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When the screen width is between 480 and 680-ish pixels wide. The content within the `va-omb-info` modal overflows.

<img width="762" alt="va-omb-info modal text overflowing off the right of the screen" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/79578198-deab-46c6-b9a1-ab807d93c47e">

## What I expected to happen

Modal text to not overflow

## Reproducing

- Formation version: Current
- Device: (e.g. iPhone 8, Macbook) All
- Browser: (e.g. Firefox, IE 11) All

Steps to reproduce:

1. Go to [`va-omb-info` in storybook](https://design.va.gov/storybook/?path=/story/components-va-omb-info--docs)
2. Set the screen size to "medium"

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by powellkerry** [comment]
@caw310 this issue was resolved with [this](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2492) task. I double checked and the modal does not overflow now.

**Comment by caw310** [comment]
Thanks @powellkerry . Will close this ticket then.
