### ISSUE TITLE
Forms: Phone number auto-formatting for text fields

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/vets-design-system-documentation#297]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Phone number text fields found in VA.gov forms

## Do you have a suggestion for a new component or utility?

When filling out forms on VA.gov, it would be helpful for users to have auto-formatting for phone number fields to help them easily enter a phone number in the proper format. With auto-formatting, users can just start typing in a phone number without then having to think about how to format it. 

An example of auto-formatting: https://uxmovement.com/forms/bad-practices-on-phone-number-form-fields/

If auto-formatting isn't yet possible, then consider parenthetical copy next to the text field label, grayed out sample text within the field, or simply displaying the phone number symbols in the text box, such as the parentheses and dash that users can fill in with the digits.

**Comment by caw310** [comment]
Closing as this is an old ticket
