### ISSUE TITLE
va-textarea does not support label-header-level property

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#2974]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

we want to create this scenario:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123402053/7f99776b-0d2e-4dcf-a5b1-f8c4373fb833)

however [va-textarea](https://design.va.gov/storybook/?path=/docs/uswds-va-textarea--docs) does not support label-header-level in order to do this, like [va-radio](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--docs#label-header) and [va-checkbox-group](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--docs#label-header) does.  I tried using `use-forms-pattern` as a workaround, but our required field would be below the header instead of on the header, which didn't seem like the right solution for this. We want the required on the field title, which works with `label-header-level`

## What I expected to happen

`va-textarea` should support `label-header-level`
- optional: all field components support this

## Reproducing

- Formation version:
- Device: Windows 11
- Browser: Chrome

Steps to reproduce:

1. Go to textarea storybook, and notice there is no supported property for this
2. You can see examples however for radio and checkbox group

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2974?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc
