### ISSUE TITLE
Swap css import in the injected header style-consolidated stylesheet

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2979]
## Description
We recently discovered that the global stylesheet for our web components is being imported into [style-consolidated.scss](https://github.com/department-of-veterans-affairs/vets-website/blob/9ef0eaafd7a173b60785f22147c48208efff2e03/src/applications/proxy-rewrite/sass/style-consolidated.scss#L111), but the only thing that's really needed is css variables from css-library. This import should be updated to directly import our css-library variables instead.

## Tasks
- Change this import: ` @import '~@department-of-veterans-affairs/component-library/dist/main.css';` to `@import '~@department-of-veterans-affairs/css-library/dist/tokens/scss/variables.scss';`
- verify the injected header continues to work by running the proxy-rewrite application locally

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2979?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
Closing this because it's no longer needed. Randi's recent work to decouple the injected header removed the need for this import.
