### ISSUE TITLE
Back to top component

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/vets-design-system-documentation#298]
# Feature Request: Back to top component

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Do you have a suggestion for a new component or utility?

I certainly do! As we've been fleshing out the Learning center, we've noticed some of our pages get increasingly taller and taller, despite our best efforts to condense content. A back to top component would help users navigate these taller pages. 

We'd need some pretty strict governance around its implementation. Here's a start:

- The BTT component will not display until a user scrolls beyond a certain Y position in the viewport. 
   - This position needs to be a decision we make collectively, based on recommendations from design, FE, accessibility, etc
- Pages that are "too short" or of a particular height, will not utilize the BTT component. We'll need to figure out a recommendation for that height as well.
- It will have a wider display on desktop / skinnier on mobile. 
- It will be anchored to the right side of the main content area on desktop, and the right side of the viewport on smaller screens. 
- It will need to be tested and validated (I think we can do this w/ the Learning center)
- account for the Foresee/Medalia feedback component
- This is def up for discussion!
- Some excellent examples: 
   - [gov.uk](https://www.gov.uk/how-to-have-your-benefits-paid) 
   - [vic.gov.au](https://www.vic.gov.au/digital-guides)

![image](https://user-images.githubusercontent.com/12564977/92122757-dcfd0400-edc9-11ea-9a0c-dda0923c1c10.png)

![image](https://user-images.githubusercontent.com/12564977/92122825-f0a86a80-edc9-11ea-8c6d-32dfaff50681.png)

**Comment by andaleliz** [comment]
As we figure out governance for this, we may want to consider how it might work with other sticky elements like the ForeSee feedback button on the facility locator page. Might be a moot point w/ the switch to Medallia, but prob good to just give it a some thought and possibly address that in documentation.

![Screen Shot 2020-09-03 at 12 02 08 PM](https://user-images.githubusercontent.com/55992116/92139230-708c0000-eddd-11ea-9818-450379bea9ee.png)
![Screen Shot 2020-09-03 at 12 02 23 PM](https://user-images.githubusercontent.com/55992116/92139239-71bd2d00-eddd-11ea-9a10-2d35940c98ad.png)

**Comment by rtwell** [comment]
ah yes—i stumbled across that immediately after i posted. that you for noting! i will add to the list in the description!

**Comment by bkjohnson** [comment]
Implemented in https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/562
