### ISSUE TITLE
<header> landmark applied too narrowly in minimal header

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2985]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

I don't think these are duplicate issues, but they are issues that may be impacted by this bug. 
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2858
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2735

## What happened

The current [minimal header component](https://design.va.gov/storybook/?path=/story/components-va-header-minimal--default) is loading with a `<header>` tag wrapped around the "Official website of the United States government" banner. 

This causes accessibility issues in that the other elements in this minimal header are now not in a landmark, and a AT user would not be accessing all of the information that looks like it's in the `<header>` but it's not.

## What I expected to happen

I expected more than just the "Official website".. banner to be the page `<header>`

And when testing this in isolation in storybook, I do see there is a `<header>` wrapping the component, but then you have a nested header, and you [can't have a banner landmark inside another banner landmark](https://dequeuniversity.com/rules/axe/4.9/landmark-banner-is-top-level?application=AxeChrome)

This needs to be implemented in conjunction with the Forms Team, that would like to 'inject' this into the **current** `<header>` that wraps the existing header elements (legacy & mobile). This minimal header would be a third option. (side note: I have questions and concerns about all of these headers loading for every user, but that's a separate issue for another day) So, I believe `<header>` shouldn't be in the web component at all at this point. 

You can see that the [USWDS on their website](https://designsystem.digital.gov/components/banner/) and in their examples include the US Website banner, and navigation in it's [page `<header>`](https://designsystem.digital.gov/components/header/)

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook) Macbook 
- Browser: (e.g. Firefox, IE 11) Chrome

Steps to reproduce:

1. Login to staging.va.gov 
2. Navigate to https://staging.va.gov/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/
3. Start the form.
4. On the first page you'll see the minimal header load.
5. Run axe browser tools
6. You'll see this error "All page content should be contained by landmarks". And it points to the "skip to main content" link. However, across all VA.gov pages, you'll see that link is not contained in a landmark.
7. Upon further inspection, I noticed the minimal header *not* loading in a `<header>` tag. And upon further investigation, found the `<header>` tag was buried deep in the component.
8. In the browser, I changed the `<div>` wrapping the minimal header to `<header>` and that fired off additional warnings because of the nested `<header>` in a header.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

I marked that this is blocking work currently in progress, as it would be a launch blocking issue. However, I think we can move forward with our usability testing that we're doing with this bug in place.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2985?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jeana-adhoc** [comment]
Note to the DST Team... After a conversation with @humancompanion-usds this might be more an issue with the VFF's team implementation. 

However - after looking at the [USWDS page templates](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=pages-documentation-page--documentation-page&args=&viewMode=story),  the grey bar *is* indeed a header, but the navigational page elements are in a second header that is a peer to the first `<header>`. 

For the [VADS minimal header](https://design.va.gov/storybook/iframe.html?args=&id=components-va-header-minimal--default&viewMode=story). the `va-official-gov-banner` matches the USWDS system, but the crisis line and `va-header` are outside of a header or landmark area. They should be contained in a sibling `<header>` as well.
