### ISSUE TITLE
Add "list loop" pattern to the sketch library 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#299]
Add list loop pattern to the sketch library. 

In the forms of VA.gov, a common pattern is when the user needs to add another piece of information to the form. This is prompted by a secondary button "Add another..." 

Be able to standardize and share when a user needs to add 1 singular text field/form field and a set of form fields. 

- [x] Audit current forms on VA.gov and how they use the pattern

- [ ] Standardize and make the list loop pattern a template in the sketch library

- [ ] Get approval and update the sketch library

**Comment by caw310** [comment]
Waiting for final usability testing changes to the design based on VAOS team testing.
