### ISSUE TITLE
yesNoUI description property is not working

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/vets-design-system-documentation#3004]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.
  - I searched yesNo and did not find any issues that match yesNo 

## What happened

The [yesNoUI pattern](https://github.com/department-of-veterans-affairs/vets-website/blob/4a7acf5069603f5dcd85f4ecbc3c36d0efdec638/src/platform/forms-system/src/js/web-component-patterns/yesNoPattern.jsx#L36) should allow a property of `description` with a type of `string | JSX.Element | React.ReactNode`. 

This description property is working in the textareaUI:
`/vets-website/src/applications/accreditation/21a/pages/06-background-information-chapter/conditionThatAffectsExaminationDetails.js` - [link](https://github.com/department-of-veterans-affairs/vets-website/blob/deb0da22464ed9b0e8d61f0b66bdd6f55dbc51d2/src/applications/accreditation/21a/pages/06-background-information-chapter/conditionThatAffectsExaminationDetails.js#L12)
```
uiSchema: {
    conditionThatAffectsRepresentationDetails: textareaUI({
      title:
        'Describe the condition or impairment and any treatment you receive now or in the past year',
      description: ConditionThatAffectsRepresentationDetailsNote,
    }),
  },
```
![image](https://github.com/user-attachments/assets/1712b947-afc7-4417-a774-06a0d47500ed)

However, the description key is not working in yesNoUI:
`/src/applications/accreditation/21a/pages/06-background-information-chapter/index.js` - [link](https://github.com/department-of-veterans-affairs/vets-website/blob/deb0da22464ed9b0e8d61f0b66bdd6f55dbc51d2/src/applications/accreditation/21a/pages/06-background-information-chapter/index.js#L15)
```
uiSchema: {
      [key]: yesNoUI({
        title: question,
        description,
      }),
    },
```
Note: this code may look a little strange but this is because we made an abstraction to unify our many uses of the yesNo pattern. The standard yesNo use gives the same problem.
![image](https://github.com/user-attachments/assets/f9201784-248a-4b14-b06a-794acff1e7d4)

Description is not working whether it is a component or if it is a string even though both work in textareaUI.

## What I expected to happen

I expected the yesNoUI description to work like the textareaUI example above, and therefore the UI would look similar to our designs:
THIS IS A FIGMA DESIGN (THE UI CANNOT CREATE THIS)
<img width="273" alt="Screenshot 2024-07-11 at 3 04 12 PM" src="https://github.com/user-attachments/assets/54ec7398-ed85-494f-9090-0e5d935cd50c">

## Reproducing

- Formation version: All
- Device: (e.g. iPhone 8, Macbook) All
- Browser: (e.g. Firefox, IE 11) All

Steps to reproduce:

1.  Add a description property with a string or a component to a textareaUI pattern 
2. Observe the description in localhost
3. Add a description property with a string or a component to a yesNoUI pattern
4. Observe the lack of description in localhost

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
We are currently putting the description below the yesNoUI patterns but this does not link the description to the yesNoUI for screen readers. We also feel it is better for the note about how they should answer the yes/no question be before the yes/no options (but after the question) since it is necessary information for them to answer it.

**Comment by caw310** [comment]
This is a forms issue so its something for the VFFT to fix. 
@tbaker1026

**Comment by tbaker-taylor** [comment]
@caw310 Opened this[ issue ](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1466)for Nick to take a look at in our repo

**Comment by rhasselle-oddball** [comment]
Some additional context:
when we talk about `"description"` for fields from `vets-website` side, e.g. the part between the label and the field, we're talking about passing `children` into the web components and making it show up in that area. Either slotted or non-slotted. Since radio already has children for options, perhaps this needs to be a new slotted spot.

So for example, with `VaText` https://staging.va.gov/mock-simple-forms-patterns/text-input we can pass children as text or JSX, and it will display in that area. However we can't do this with `VaRadio` (compare RJSF (old patterns) vs new web component patterns https://staging.va.gov/mock-simple-forms-patterns/radio).  

`VaRadio` does support `formDescription` when used in conjunction with `useFormsPattern`, however it's not desired to use `useFormsPattern` for these generic cases, since the field label is a regular label, and not a header of the page. We don't want forms pattern, but just a generic description slot we can pass to the component.

**Comment by rhasselle-oddball** [comment]
update: I did do some testing - there are some things we can do on our side to update this. However it might not be read out by screen readers. But we can add passing the description to children in radio and yesno pattern. it looks like we might not be doing that.
