### ISSUE TITLE
Chromatic - ensure TurboSnap is configured correctly

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3005]
## Description
Recently we've run into Chromatic issues where we run out of snapshots and our builds for visual regression testing do not finish. Previously this could have been attributed to being on an old version of Storybook, though with our recent upgrade to Storybook 7, we should be able to properly configure TurboSnap and reduce the amount of outright snapshots we are consuming. 

## Considerations
- [Chromatic documentation for TurboSnap](https://www.chromatic.com/docs/setup-turbosnap/#prerequisites)
- Docs state we at least need to be on Storybook 6.5, Chromatic CLI v10+, and run our github actions on `push` instead of `pull_request`.
- Builds with TurboSnap properly running have an icon with a blue dot and the word `TurboSnap` on their details page. See [build 521](https://www.chromatic.com/build?appId=65a6e2ed2314f7b8f98609d8&number=521) as an example. 
- From a chat with one of the Chromatic reps: running the [@chromatic-com/turbosnap-helper](https://www.npmjs.com/package/@chromatic-com/turbosnap-helper) tool with npx may help confirm our `storybookBaseDir` is correct. 
- As of CLI v.11.3.2, Chromatic uses cwd relative to the repo root as the default value for storybookBaseDir; if project is in a subdirectory and `workingDir` is used to change cwd, we shouldn't need to include storybookBaseDir unless it deviates from the cwd

## Tasks
- [ ] Configure TurboSnap properly and confirm it is working as expected

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3005?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
I think this is working now after the [onlyChanged flag is turned back on](https://github.com/department-of-veterans-affairs/component-library/pull/1238) so I'm going to close this ticket. 

We will just need to be more aware of when we're updating `package.json` files because it will automatically generate new snapshots when that happens.

![Screenshot 2024-07-26 at 9 35 54 AM](https://github.com/user-attachments/assets/c857186d-a86d-4bad-982b-9623afc85b8a)
