### ISSUE TITLE
V1 Component Code Removal - va-breadcrumbs

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3013]
## Description
With migration to v3 complete there are no v1 component instances left in vets-website or content-build. We should remove v1 component code from the component library repo to prevent teams from inadvertently using them. This ticket is for the removal of v1 va-breadcrumbs

## Considerations
- V3 component code is currently housed in an `if` statement. That code needs to become the default component code, and everything else needs to be removed. 
- Some components rely on css selectors that target the `uswds` property on the host, such as `:host([uswds='false'])` These should also be removed
- Some e2e test specs for components still rely on the uswds prop. These should be cleaned up and removed if necessary. 
- [getClickLevel](https://github.com/department-of-veterans-affairs/component-library/blob/00a3569e296c5732fefa14ebbadad218a55871c8/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx#L121) may need to be updated with the removal of `uswds`
- [fireAnalyticsEvent](https://github.com/department-of-veterans-affairs/component-library/blob/00a3569e296c5732fefa14ebbadad218a55871c8/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx#L131) may need to be updated with the removal of `uswds`
- [comopnentWillLoad](https://github.com/department-of-veterans-affairs/component-library/blob/00a3569e296c5732fefa14ebbadad218a55871c8/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx#L236) may need to be updated with the removal of `uswds`
- [handleSlotChange](https://github.com/department-of-veterans-affairs/component-library/blob/00a3569e296c5732fefa14ebbadad218a55871c8/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx#L270) may need to be updated with the removal of `uswds`

## Tasks
- [x] Remove v1 component code for va-breadcrumbs
- [x] Update css and test files where v1 is no longer needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3013?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
