### ISSUE TITLE
V1 Component Code Removal - va-button, va-button-pair

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3014]
## Description
With migration to v3 complete there are no v1 component instances left in vets-website or content-build. We should remove v1 component code from the component library repo to prevent teams from inadvertently using them. This ticket is for the removal of v1 va-button and va-button-pair

## Considerations
- V3 component code is currently housed in an `if` statement. That code needs to become the default component code, and everything else needs to be removed. 
- Some components rely on css selectors that target the `uswds` property on the host, such as `:host([uswds='false'])` These should also be removed
- Some e2e test specs for components still rely on the uswds prop. These should be cleaned up and removed if necessary. 
- [va-button componentDidLoad](https://github.com/department-of-veterans-affairs/component-library/blob/54c94bb655b31850139ca813ed6ff8c355637f22/packages/web-components/src/components/va-button/va-button.tsx#L98) should be updated
- va-file-input has a [va-button instance](https://github.com/department-of-veterans-affairs/component-library/blob/c624e6e4833ce20af0b9ee5634ed79ef0891ac74/packages/web-components/src/components/va-file-input/va-file-input.tsx#L499) where uswds is set to false
- va-omb-info has a [va-button instance](https://github.com/department-of-veterans-affairs/component-library/blob/dcf7cd09c1ddca7428a1e63239b5e563c524d104/packages/web-components/src/components/va-omb-info/va-omb-info.tsx#L175) where uswds is set to false
## Tasks
- [ ] Remove v1 component code for va-button and va-button-pair
- [ ] Update css and test files where v1 is no longer needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3014?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
