### ISSUE TITLE
V1 Component Code Removal - va-file-input, va-file-input-multiple

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3017]
## Description
With migration to v3 complete there are no v1 component instances left in vets-website or content-build. We should remove v1 component code from the component library repo to prevent teams from inadvertently using them. This ticket is for va-file-input and va-file-input-multiple.

## Considerations
- va-file-input-multiple doesn't have a v1, but it does have a `va-file-input` component which uses the `uswds` prop. The `uswds` flag will need to be removed from these and we'll need to ensure it continues to function as expected.
- [These stencil lifecycle hooks](https://github.com/department-of-veterans-affairs/component-library/blob/c624e6e4833ce20af0b9ee5634ed79ef0891ac74/packages/web-components/src/components/va-file-input/va-file-input.tsx#L296-L310) will need to be updated for va-file-input
- [This instance of uswds=false](https://github.com/department-of-veterans-affairs/component-library/blob/c624e6e4833ce20af0b9ee5634ed79ef0891ac74/packages/web-components/src/components/va-file-input/va-file-input.tsx#L499) on va-button will need to be removed
- Some components rely on css selectors that target the `uswds` property on the host, such as `:host([uswds='false'])` These should also be removed
- Some e2e test specs for components still rely on the uswds prop. These should be cleaned up and removed if necessary. 

## Tasks
- [ ] Update va-file-input to remove v1 code
- [ ] Update css and test files where v1 is no longer needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3017?planning-poker) with Zenhub @jamigibbs @micahchiang @Andrew565 @rmessina1010 @harshil1793 @powellkerry @ataker @rsmithadhoc @it-harrison
