### ISSUE TITLE
Read Only Information Design on Review Page of Form

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/vets-design-system-documentation#302]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: review-lineitem(s) within the review/accordion-open on the forms review page

## Do you have a suggestion for a new component or utility?
This is a proposed variation to the review page of a form. 

Our use case: We are displaying read-only information within our healthcare form as another way to verify identity before entering health information in preparation for an upcoming appointment. As a result, this read only information will also display on the review page. 

Possible benefits to the new design:
- visually differentiating read-only information from editable information on the review page.
- clear hierarchy of read-only information.
- scan-ability of the information.
- mobile friendly.

## Additional context

![Read-only Demographi Info](https://user-images.githubusercontent.com/66287082/92765219-2b2e7c00-f363-11ea-8f1b-7f94aadd8f47.jpg)

**Comment by CrystabelReiter** [comment]
@kristenmcconnell The design system council has reviewed this proposal and gives this pattern the green light for the team to prototype. VSP will be collaborating in the future how to share this pattern globally.

**Comment by kristenmcconnell** [comment]
Wonderful. Thank you.

**Comment by caw310** [comment]
Closed as team did not pursue this design.
