### ISSUE TITLE
V1 Component Code Removal - va-segmented-progress-bar

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3024]
## Description
With migration to v3 complete there are no v1 component instances left in vets-website or content-build. We should remove v1 component code from the component library repo to prevent teams from inadvertently using them. This ticket is for va-segmented-progress-bar

## Considerations
- uswds code needs to be hoisted out of `if` statement in va-segmented-progress-bar
- Some components rely on css selectors that target the `uswds` property on the host, such as `:host([uswds='false'])` These should also be removed
- Some e2e test specs for components still rely on the uswds prop. These should be cleaned up and removed if necessary. 

## Tasks
- [ ] Update va-segmented-progress-bar to remove v1 code
- [ ] Update css and test files where v1 is no longer needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3024?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
