### ISSUE TITLE
V1 Component Code Removal - va-table, va-table-inner

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3027]
## Description
With migration to v3 complete there are no v1 component instances left in vets-website or content-build. We should remove v1 component code from the component library repo to prevent teams from inadvertently using them. This ticket is for va-table and va-table-inner

## Considerations
- uswds code needs to be hoisted out of `if` statement in va-table
- [makeVaTable](https://github.com/department-of-veterans-affairs/component-library/blob/41318bbfaaaa5cd4f4da4d722e097fea31aee3b5/packages/web-components/src/components/va-table/va-table.tsx#L142) will need to be updated
- [va-table componentDidLoad](https://github.com/department-of-veterans-affairs/component-library/blob/41318bbfaaaa5cd4f4da4d722e097fea31aee3b5/packages/web-components/src/components/va-table/va-table.tsx#L197) will need to be updated
- [va-table-inner componentDidLoad](https://github.com/department-of-veterans-affairs/component-library/blob/41318bbfaaaa5cd4f4da4d722e097fea31aee3b5/packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx#L85) will need to be updated
- [va-table-inner componentDidUpdate](https://github.com/department-of-veterans-affairs/component-library/blob/41318bbfaaaa5cd4f4da4d722e097fea31aee3b5/packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx#L189) will need to be updated
- Some components rely on css selectors that target the `uswds` property on the host, such as `:host([uswds='false'])` These should also be removed
- Some e2e test specs for components still rely on the uswds prop. These should be cleaned up and removed if necessary. 

## Tasks
- [x] Update va-table and va-table-inner to remove v1 code
- [x] Update css and test files where v1 is no longer needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3027?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
