### ISSUE TITLE
V1 Component Code Removal - va-text-input

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3029]
## Description
With migration to v3 complete there are no v1 component instances left in vets-website or content-build. We should remove v1 component code from the component library repo to prevent teams from inadvertently using them. This ticket is for va-text-input

## Considerations
- uswds code needs to be hoisted out of `if` statement in va-text-input
- [componentDidLoad](https://github.com/department-of-veterans-affairs/component-library/blob/68e22a5b37ff612342a5083d66f75efff572c9ab/packages/web-components/src/components/va-text-input/va-text-input.tsx#L337-L343) will need to be updated
- Some components rely on css selectors that target the `uswds` property on the host, such as `:host([uswds='false'])` These should also be removed
- Some e2e test specs for components still rely on the uswds prop. These should be cleaned up and removed if necessary. 

## Tasks
- [ ] Update va-text-input to remove v1 code
- [ ] Update css and test files where v1 is no longer needed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3029?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
