### ISSUE TITLE
v3 file input (single and multi) does not fire correct event on file remove

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/vets-design-system-documentation#3031]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

[V3 multi-file upload component](https://design.va.gov/storybook/?path=/docs/uswds-va-file-input-multiple--docs) events fired when removing a file are out of step with the component's view. The information in the event is stale and makes it infeasible to track the state of uploaded/removed files external to the component.

The single event fired on file add, remove, or change is `vaMultipleChange`. It includes a property `event.detail.files`, which should list the current array of files that have been uploaded so far.

On file add, this works as expected and the list shows all files uploaded so far:
![add2](https://github.com/user-attachments/assets/adc90cd6-3137-48a1-923f-4b4a908482ea)

However, when that same newly-added file is removed, the view updates but the event fired is identical to when it was added:
![remove2a](https://github.com/user-attachments/assets/b16671de-334c-4c9c-bee5-d7e2eba46981)

With no distinguishing difference between the file's add/remove events, we don't know what file was just removed external to the component (or even that this event represents a removal at all).

This has the effect that the same external upload code that is triggered on file upload is triggered on file removal. This causes same file to be re-uploaded with no way to remove.

Here's a video for extra context:
https://github.com/user-attachments/assets/673bb936-1874-4f08-a8a2-fa1f4ca2d6ee

## What I expected to happen

I expected an event to be fired upon removal (or change of file) that explicitly indicates a file removal (or change) and provides details on which file is being removed (or changed).

## Reproducing

Steps to reproduce:

1. Checkout this [vets-website branch](https://github.com/department-of-veterans-affairs/vets-website/tree/update-file-upload-component-7959a) ([PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30732))
2. Start the vets-api backend locally
3. In browser, navigate to [this page](http://localhost:3001/family-and-caregiver-benefits/health-and-disability/file-champva-claim-10-7959a/additional-eob-upload) of IVC/CHAMPVA form 10-7959a
4. Open developer console
5. Upload a file and observe the event shown by the debugger
6. Let the event finish
7. Click the newly uploaded file's "remove" button and observe the event shown by the debugger

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [X] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

Until this is resolved, we'll have to rely on the v1 file upload component. It's definitely viable, but means we're not up to the current v3 design standard on our form.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3031?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
Hi @michaelclement I am trying to reproduce this bug but have failed so far. I have checked out your branch and investigated the events that get fired. In the video below I:
* add file `one.png`: `event.detail.files` has `one.png`
* add file `two.png`: `event.detail.files` has `one.png` and `two.png`
* delete file `two.png`. after the delete `event.detail.files` has `one.png`
So it seems that the event payload is correct, but from watching your video, maybe the problem is that the payload is correct but the files that get uploaded are nevertheless _not_ correct? I don't have much experience running `vets-api`, so I'm not sure how to check what gets uploaded to the server.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2tvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7efd3086cbc37236eb424a3024a2b7854755ada9/va-file-input-multiple-bug.mov)

**Comment by michaelclement** [comment]
Hello @it-harrison! Not sure what changed, but I pulled the latest `main` branch into the demo one linked above, rebuilt, and now the event is displaying the way you described. Thank you for looking into this!
