### ISSUE TITLE
Experimental Design [Icon - Right arrow in circle]

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/vets-design-system-documentation#3035]
## What

> Give a brief description of the component or pattern you want to propose.

The mobile app team has a need for an icon showing a right arrow in a circle.

`arrow_circle_right`
![image](https://github.com/user-attachments/assets/d0cdc3dc-0f14-494e-af99-c5bdf1f6a3b3)

## Purpose

> What problem does this component or pattern solve for the user?

This icon is used when there is a link to a **different section** in the app.
For links within sections, a "chevron" icon is typically used. 
For links to webview or outside of the app, a "launch" icon is typically used.

## Usage

> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.

N/A

## Behavior

> Describe the key interactions for this component, calling out any specific considerations for mobile.

N/A

## Examples

> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.

![image](https://github.com/user-attachments/assets/05259336-0490-42ee-81ab-7bf0a263f97a)

## Accessibility

> Include any accessibility considerations.

N/A

## Guidance

> What would you want to tell other teams about this component or pattern?

N/A

## Collaboration Cycle Ticket

> Provide a link to your collaboration cycle ticket. 

N/A

## Your team

> Tell us what team you are on. 

Mobile app design system team

## Research (optional)

> Include any research you have already conducted, or plan to conduct, on this component or pattern.

N/A

## Code (optional)

> Include any existing code.

N/A

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
@jessicawoodin there's no need to bring this to DSC. @danbrady will work with you on this icon request.

**Comment by danbrady** [comment]
Ok, I've added it to the Figma DS and published. Attaching the 24x24 SVG here for engineering to update the sprite sheet with. (Note for devs: you may have to modify attributes to match the other icons.)

![arrow_circle_right](https://github.com/user-attachments/assets/99ec8f11-415b-427a-ac67-9bd41c5ce158)

@caw310 This needs to be assigned to an engineer for the next step. After the icon is added to our sprite sheet and that is deployed to our doc site, we will need to update the icons guidance page with it. Thanks!

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3035?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
