### ISSUE TITLE
Update va-memorable-date component to allow disabling of default hint text

### ISSUE THREAD

**Issue by adam-antonioli** [department-of-veterans-affairs/vets-design-system-documentation#3046]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The default hint text for a va-memorable-date component persists after using custom hint text. This is causing both texts to display when only the custom hint text is needed in some cases.

<img width="358" alt="Screenshot 2024-07-18 at 09 18 34" src="https://github.com/user-attachments/assets/9a2b8450-31ce-4207-84c4-ed2d6d5c57e1">

## What I expected to happen

Suggested fix is to allow for disabling of the default hint text with a flag prop. This will allow for only having the custom text displayed when needed.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

Proposed change: https://dsva.slack.com/archives/CBU0KDSB1/p1721243582909029?thread_ts=1721243509.618949&cid=CBU0KDSB1

**Comment by jamigibbs** [comment]
[Slack convo](https://dsva.slack.com/archives/CBU0KDSB1/p1721244361327729?thread_ts=1721243509.618949&cid=CBU0KDSB1) for reference
