### ISSUE TITLE
va-radio description is not being read by screen reader

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/vets-design-system-documentation#3059]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

This PR [yesNoUI and radioUI to accept description prop #30897](https://github.com/department-of-veterans-affairs/vets-website/pull/30897) added the ability to have a description in the yesNoUI and radioUI but noted "However this is a half-solution. This won't be read out by screen readers. We need support from DST in order to allow that."

## What I expected to happen

Whether it is a yesNoUI or a radioUI a screen reader should read the description:
![image](https://github.com/user-attachments/assets/f9724f81-deed-45f3-b941-5302c2c6193f)
Here the screen reader should read: "This is a description".

![image](https://github.com/user-attachments/assets/bc9b2f4d-1a26-402f-b9ce-184c11c73066)
Here the screen reader should read all the text including the list.

## Reproducing

- Formation version: ??
- Device: (e.g. iPhone 8, Macbook) Macbook
- Browser: (e.g. Firefox, IE 11) Chrome

Steps to reproduce:

1. Pass a description to a yesNoUI
3. Enable the screenreader

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
@rhasselle-oddball will provide the technical details of what he meant by the needed support from DST he mentioned in his PR  [yesNoUI and radioUI to accept description prop #30897](https://github.com/department-of-veterans-affairs/vets-website/pull/30897): "However this is a half-solution. This won't be read out by screen readers. We need support from DST in order to allow that."

**Comment by rhasselle-oddball** [comment]
for va-text-input, we can pass children, and it will get placed in this area and be read out by screen reader.  however for va-radio, or va-checkbox-group if we try to do the same thing, it won't get read out by a screen reader. we have form-description, but that is intended for useFormsPattern - which we don't want to use since that is more than just a field, that is also page title. we just want a generic description slot to place content that will also be read out by screen reader.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3059?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
@williamphelps13 this is tentatively scheduled to be worked on in sprint 8 which starts mid August.
