### ISSUE TITLE
Design pattern for a "list tool"

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/vets-design-system-documentation#306]
There are many similar tools on VA.gov, and we should have a standard pattern for these tools. Some examples of "list tools" can be found here 

1. View Payments https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/ (edited) 
2. View your representative https://preview.uxpin.com/00985ac7bf2e8454786086efbf1c89de82d5cb3c#/pages/127904094/simulate/no-panels
 (potentially combined with search for a representative https://xd.adobe.com/view/fe3c02e8-a803-4a02-7a76-14c7dcad4a48-880d/screen/25f19aea-7630-473e-811e-3cb995869ff1/) (edited) 
3. The debt letters designs which used a right rail and then changed to an "on this page" design. Content page + "tool page" (edited) 
4. View your rated disabilities (currently in production) https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/ <- Note I'm not sure if that is the final copy that might be a slightly older revision (edited) 

We are currently working on patterns for this tool

**Comment by sshein** [comment]
discussions happening here #temp-standardizing-tool-designs

**Comment by sshein** [comment]
Proposed design so far 

![desktop-tool](https://user-images.githubusercontent.com/3856611/92791167-4e582c00-f361-11ea-83f2-2178e33d99ba.png)
![mobile-tool](https://user-images.githubusercontent.com/3856611/92791187-53b57680-f361-11ea-84e2-851bbe5e3878.png)

**Comment by mpeterz** [comment]
A key part of this work is integrating content now in the right rail into the main area of the page. This will keep the right rail free and optimized for mobile.

**Comment by sshein** [comment]
**Recommendations for designing a "list tool" and where content appears:**
- Identify the top questions veterans would want answered while interacting with the tool itself
- Integrate these questions/answers into the list tool "in context" as much as possible, either with the "additional info" component or on the page
- If there are still questions/answers that don't make sense to be integrated into context, include these below the tool lists themselves with an "on this page" component
- Include a "Get help" prefooter component above the footer for all tool pages
- Additionally, most tools will have Drupal "landing pages" which should be treated as pages "selling" to veterans essentially, primarily for folks that are not logged in

**Comment by sshein** [comment]
[Research done with this pattern for the Debt letters tool ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/usability-readout.md)showed that this basic tested well. **"Most participants engaged highly with the 'On this page' component, and it helped them complete the usability tasks quickly"**

**Comment by humancompanion-usds** [comment]
This is documented here:
https://design.va.gov/patterns/help-users-to/check-personal-information

Unfortunately, the research didn't make it into the repo (it was done back in 2020) but it is linked from the pattern.
