### ISSUE TITLE
Statement of Truth web component not updating error messages properly

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/vets-design-system-documentation#3065]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When attempting to implement the Statement of Truth web component, I noticed the error messages for the text input and the checkbox were not properly updating. This can be observed in storybook: https://design.va.gov/storybook/?path=%2Fdocs%2Fuswds-va-statement-of-truth--docs

For example, I type some error message into the `inputError` property and the error message appears as expected:
![image](https://github.com/user-attachments/assets/d7db25e5-6030-417f-bcc4-237d4386c52a)

However, if I delete the error message from the `inputError` property, it does not disappear:
![image](https://github.com/user-attachments/assets/834561dd-0ba6-4d6b-9d69-c7d7897b5dd6)

This behavior also happens with the `checkboxError` property. It's interesting because re-entering another error message after deleting does properly update the message again, so it seems to just be an issue with going from having an error message to having no error message.

## What I expected to happen

When the `inputError` or `checkboxError` properties are set to `undefined`, `null`, `''`, etc., the error message for the corresponding web component field should disappear.

## Reproducing

- Formation version:
- Device: Tested in Windows 11 and Ubuntu
- Browser: Tested in Brave (Chromium) and Firefox

Steps to reproduce:

As explained above, you can reproduce this using storybook here: https://design.va.gov/storybook/?path=%2Fdocs%2Fuswds-va-statement-of-truth--docs

1. Enter an error message into the `inputError` or `checkboxError` property
2. Delete the inputted error message string from that property

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3065?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
