### ISSUE TITLE
va-button analytics do not have the button's origin URL

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/vets-design-system-documentation#3091]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The Sitewide team is working on removing custom Google Analytics events where they are not needed. We have some `<va-button>`s around the site, but we can't remove the custom events from them because the `<va-button>` component does not send the `link-origin`:
<img width="745" alt="Screenshot 2024-07-25 at 3 19 10 PM" src="https://github.com/user-attachments/assets/444bf758-319c-47d6-bb6b-b238ef8d0702">

Here's a screenshot of the information we're getting for `<va-link>`.
<img width="755" alt="Screenshot 2024-07-25 at 3 08 59 PM" src="https://github.com/user-attachments/assets/d48def25-ef78-4ab7-a0c0-c5fe19299379">

## What I expected to happen
It would be helpful to have the `link-origin` for a `<va-button>` so we have some context as to where this button was clicked.

## Reproducing

Any browser/version. Checked the component's analytics here: https://github.com/department-of-veterans-affairs/component-library/blob/250230bb61afe1eda40679e35787cc867f8f2ebb/packages/web-components/src/components/va-button/va-button.tsx#L111

Steps to reproduce:

1. Go to this URL: https://www.va.gov/chicago-health-care/events/56659/
2. Open the "view other times for this event" accordion
3. Click the "show all times" button
4. Observe the details logged for the button click

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by randimays** [comment]
I don't know how much of a lift this would be, but perhaps we should add the `link-origin` to all of the web components? I'm noticing it's not on some of the others I've checked, and this would be useful information for our team. @jestutt to confirm: there's no other way GA gets the origin URL, correct?

**Comment by jestutt** [comment]
@randimays  No, please don't. All events already collect the page an event is happening on so the automatically generated `link-origin` is redundant. Add or filter by one of the page dimensions -- Page path and screen class, Page path + query string or Page location -- to your report to find what page and event happened on. 

cc @johnny-jesensky-adhoc

**Comment by randimays** [comment]
Thanks @jestutt; I'll close this ticket in that case.

> Add or filter by one of the page dimensions -- Page path and screen class, Page path + query string or Page location -- to your report to find what page and event happened on.

To confirm: this guidance is specifically for generating reports in the GA dashboard (not how to code the events)?

**Comment by jestutt** [comment]
@randimays Yes, that guidance is for the reporting end only.
