### ISSUE TITLE
Minimal header should not default to use headings

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#3097]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When using the [minimal header component](https://design.va.gov/storybook/?path=/docs/components-va-header-minimal--docs), teams have to set the `disable-headings` property to true every time they use the component.

## What I expected to happen

I expected the component to support the documentation that's in the [design system](https://design.va.gov/components/header/header-minimal) on default. 

The documentation states

> Set form title as header and sub-header. The minimal header has header and subheader props that allow for setting the title of the form and the form number, respectively. **Use of this component is intended for form flows and in particular when the h1 of the page is being to ask the user a question in keeping with the One Thing Per Page content principle.**

I interpret, and expect, this to mean that the minimal header will *never* load with an h1 or h2 inside of it. If that is true, I would like to suggest the `disable-headings` property be changed to `enable-headings` and only when that is set to true or is defined, that headings are allowed. This allows the component to be a little more flexible for non-form use. But if this is indeed intended for form use only, then this property could be removed completely.

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Viewing the [component in storybook](https://design.va.gov/storybook/?path=/docs/components-va-header-minimal--docs)
2. The component by default loads with headings.
3.
4.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

### Details
As this becomes available for teams to use, I want to help make sure they understand how to use it. And it's helpful to minimize or remove properties that don't apply to our use cases.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3097?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@caw310 I believe this should be a dev ticket instead of a design ticket, right?

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3097?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by powellkerry** [comment]
This should remain open until the vets-website and content-build PRs can be merged, after the next component-library release.

**Comment by micahchiang** [comment]
PRs have been merged, closing
