### ISSUE TITLE
Unable to modify icon in alerts

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/vets-design-system-documentation#3100]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

While Figma allows designers to modify or edit the icon in alerts, the coded implementation of alerts do not allow modification. My team needs to have warning alerts with the "lock" icon related to a complicated series of sign-in alerts that help Veterans on the journey to verify their identity and access My HealtheVet. After taking these designs through the Design System Council, we were advised to use _yellow_ alerts to better indicate that "success" was not imminent. This makes sense and we agree / are happy to take this advice! 

But we cannot use a lock icon with the yellow alert in code. The same flexibility in Figma is not possible in the coded instance of the alerts. 

## What I expected to happen

Figma and the coded version of the same component should have the same constraints. This is an easy swap in Figma, but devs need to create an entirely new detached instance of the component that they custom code in order to do this on our end. We expect that the iconography in alerts is flexible enough to allow interoperability of the lock icon with versions other than success only. 

## Reproducing

N/A
Steps to reproduce:

N/A

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround 
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
We built a custom component to accomplish this for now (warning alert with lock icon), but would like to lean on VADS instead and not customize things like this in the future. We'll update our version once this is possible out of the box. Thank you!

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3100?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
@sterkenburgsara Ran this past Matt and DST designers, I don't think we want to enable icons to be changed in all alerts. Perhaps best to add the variation you need. Would you update this ticket to a component update rather than as a bug?

**Comment by sterkenburgsara** [comment]
@caw310 sure!

**Comment by sterkenburgsara** [comment]
@caw310 I can't edit the labels -I'll close this one and I will resubmit a new ticket.
