### ISSUE TITLE
Documentation - Add logos assets to Logos page

### ISSUE THREAD

**Issue by danbrady** [department-of-veterans-affairs/vets-design-system-documentation#3101]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Other

### What is the name?

Logos

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [x] Usability guidance
- [ ] Accessibility considerations
- [x] Content considerations
- [x] Implementation
- [x] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

We should provide the VA logos on the [Logos page](https://design.va.gov/foundation/logos) on the site. Versions should include:
* SVG and high-res PNG versions
* Transparent and opaque versions
* All wide, stacked, and logotype versions

**Comment by LWWright7** [comment]
Worked on this ticket with @danbrady and @babsdenney in our design sync this morning.

**Comment by caw310** [comment]
Added to the sprint as unplanned.

**Comment by LWWright7** [comment]
@danbrady @babsdenney This one is ready for review!!

**Comment by danbrady** [comment]
The link on the site looks good. Here's what the extracted files look like to me:

<img width="269" alt="image" src="https://github.com/user-attachments/assets/e3768522-5d49-449e-a76e-18590ba1ba72">

A couple questions:
* Can/should we remove the additional "Wide Full Color on Light-1"?
* Should we remove spaces from file names?
* Should we add hi-res PNGs in case folks can't use SVGs?
* If so, do we need transparent & opaque background versions?

**Comment by LWWright7** [comment]
Yes, I think the "-1" file is just a duplicate and can be deleted. 
As for everything else...
@humancompanion-usds I sent you a slack message yesterday about this issue.  Please advise.

**Comment by LWWright7** [comment]
I created pull requests to delete the old "VALogos.zip" file and replace it with the new one that has files with spaces removed + .svg files.
