### ISSUE TITLE
Hex values don't align with documentation

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#311]
## What happened

@jenstrickland commented that the dotted blue border on my additional info component in my Sketch file looked lighter than the production implementation.  I looked into it, and on design.va.gov, the accordion border has a hex value of `#0071bb`.  

In the Sketch library, the border color is `#0072C1`, which is super close! I don't even see a difference but some with better eyes do.

I also noticed in the sketch library, when I pull up the color picker and I see all the colors from our design system palette, the primary blue shows up as `#0071BC` , which is _also_ super close, but still not the same as defined in our docs. I think we should shore all these things up so we're consistently using the same blue.
![image](https://user-images.githubusercontent.com/55992116/92954430-7020e400-f431-11ea-8e83-a028dfb8dea0.png)

## What I expected to happen

The primary blue values would align between the sketch library file elements, and the design system documentation.

## Reproducing
Latest design system sketch library file

Steps to reproduce:

1.  Inspect the hex value of the elements in our sketch library
2. In sketch, check out the color of the dotted blue border at the bottom of the additional info component
3. Check out the [design system documentation](https://design.va.gov/design/color-palette)

**Comment by CrystabelReiter** [comment]
Thanks @andaleliz I'll take a look at this today

**Comment by CrystabelReiter** [comment]
This has been corrected in the most recent sketch update
