### ISSUE TITLE
VaDateInput style issue when in error state

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/vets-design-system-documentation#3113]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
<img width="1080" alt="Screenshot 2024-07-31 at 11 33 02 AM" src="https://github.com/user-attachments/assets/c0ca5574-1d08-4b22-a429-b86f3d740dc0">

I entered `January`, `1`, and `8` for the year in the Storybook docs for `VaDateInput` and clicked off (unfocused) the inputs and produced error states on all 3 fields.

The year input's error message wraps, causing an alignment issue.

## What I expected to happen

Not sure exactly how errors should stack / display here. But the alignment should be the same.

## Reproducing

Any browser; this happens in Storybook.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by Mottie** [comment]
I'm seeing something similar for `va-memorable-date`:

If you focus, then blur the month input, you'll see the same error twice
<img width="437" alt="va-memorable-date showing Please enter a month between 1 and 12 as the error and above the month input" src="https://github.com/user-attachments/assets/67bf2d84-e186-49cb-815f-d6174bf939b6">

This also happens to the day and year input if you refresh the page and focus on that input, then blur

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3113?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by caw310** [comment]
Similar issue with memorable date https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3064

**Comment by randimays** [comment]
Alignment fix looks great, thanks! This is nitpicky, but thought I'd mention that the text within the dropdowns gets a bit cut off on the bottom when in an error state. 
<img width="246" alt="Screenshot 2024-09-03 at 12 42 12 PM" src="https://github.com/user-attachments/assets/570287ef-747f-473f-b90f-60bc31f681ee">
