### ISSUE TITLE
va-search-input firing the onSubmit function twice

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/vets-design-system-documentation#3117]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I noticed that `va-search-input` is firing the `onSubmit` function twice when the keyboard is used to submit the form (pressing "Enter"). In the video, you can see the `/forms` API call is made once when clicking to submit, and the second time it's submitted by hitting "Enter" and the API call is made twice. I think this is because the keyboard press event on the component is not using event.preventDefault(). I'm working on converting to this web component for the global search locally and noticing the same behavior.

https://github.com/user-attachments/assets/69d283fd-89c9-44de-86df-a2118274b0e8

## What I expected to happen

`onSubmit` function should only fire one time regardless of how the search is submitted.

## Reproducing

Prod example: https://www.va.gov/find-forms (and [here's the code](https://github.com/department-of-veterans-affairs/vets-website/blob/839ae19960c3e989f66084c618b50287990646c2/src/applications/find-forms/containers/SearchForm.jsx#L97) where that VaSearchInput is implemented)

Steps to reproduce:

1. Go to va.gov/find-forms and open the Network tab
2. Type in a search term such as "1010"
3. Press "Enter" to submit the term
4. Note that the `/forms` API is called twice when "Enter" is pressed

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
Since this is a production bug, would it be possible to prioritize this soon? It is also blocking a couple of tickets I have in our current sprint.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3117?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
