### ISSUE TITLE
Experimental Design Filter Icon

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/vets-design-system-documentation#3118]
## What

The VA design system needs an icon for filtering. There are two USWDS filter icons, **filter_alt** and **filter_list**. We prefer filter_alt, but would guidance on which to use.

<img width="357" alt="Screenshot 2024-07-29 at 9 21 03 AM" src="https://github.com/user-attachments/assets/c531180d-a3fb-43be-9e27-6286c4d3007b">

## Purpose

Adding an icon to the filter and sort link, would provide visual prominence and hierarchy to better grab Veterans attention and better indicate that the link is actionable. 

## Usage

When a Veteran is scheduling an appointment with a community care provider from a referral on va.gov, they are directed to a list of eligible community care providers. If the Veteran has specific criteria by which they wish to search, they can use the **filter and sort** link above the list. This link is in need of an icon to better indicate that it is an action that can be taken. 

## Behavior

This link (with icon) navigates to a filter page. 

## Examples

<img width="316" alt="Screenshot 2024-07-31 at 2 24 26 PM" src="https://github.com/user-attachments/assets/211f2f80-4cc2-49b1-83bb-0dd953a13750">

## Accessibility

USWDS has tested this icon and passed WCAG 2.1 AA

## Collaboration Cycle Ticket

[#80703](https://app.zenhub.com/workspaces/appointments-cc-direct-scheduling-660abc13699bfa00195d685a/issues/gh/department-of-veterans-affairs/va.gov-team/80703)

## Your team

Unified Appointments Experience

**Comment by danbrady** [comment]
Reference: [Internal slack support thread](https://dsva.slack.com/archives/C01DBGX4P45/p1722270264101049)

**Comment by danbrady** [comment]
These icons are now published in Figma DS. Attaching SVGs here to add to icon sprite.

![filter_list](https://github.com/user-attachments/assets/2584c6ac-5c48-4993-914c-e2863a650548)
![filter_alt](https://github.com/user-attachments/assets/2c09f79e-ea52-4832-9afb-887a8fe1cd27)


(Note: SVG attributes may need to be adjusted to match other icons in sprite.)

@caw310 This can be assigned to a dev. After it's added and released, we can update the doc site.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3118?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment]
Icons were already a part of the sprite sheet, closing ticket as no further work needed.
