### ISSUE TITLE
Add semantic typography tokens to css-library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3120]
## Description
We have [guidance](https://design.va.gov/foundation/typography#semantic-typography-tokens) around semantic typography tokens but have not yet added those as variables available for use in css-library. This ticket is for adding these tokens. 

## Considerations
- These should be added to [fonts.json](https://github.com/department-of-veterans-affairs/component-library/blob/1028ebfa3fa3713bbe54a4f9c044b14cb5aacb53/packages/css-library/tokens/fonts.json#L2) so they automatically get generated to `css-library/dist/tokens`. 
- Given what's already in `fonts.json`, structure for semantic tokens may look something like this: 
```json
{
  "vads-font": {
     "line-height": {
        "body-lead": { "value":  "1.75rem" }, 
        "default": { "value": "1.5rem" },
        ....
     },
    "size": {
      "body": {
         "large": { "value": "1.25rem" },
         "lead": { "value": "1.25rem" },
         "medium": { "value": "1.063rem" },
         ...
       },
     "heading": {
       "level-1" : { "value": "2.5rem" },
       "level-2" : { "value": "2rem" },
       ....
      }
    }
  }
}
```
Given the above, output to dist should generate css variables that look like `--vads-font-line-height-body-lead: 1.75rem`, `--vads-font-size-body-large: 1.25rem`, etc

## Tasks
- Use the above json structure to add [tokens listed here](https://design.va.gov/foundation/typography#semantic-typography-tokens) to [fonts.json](https://github.com/department-of-veterans-affairs/component-library/blob/1028ebfa3fa3713bbe54a4f9c044b14cb5aacb53/packages/css-library/tokens/fonts.json#L34)
- run `yarn build` from css-library to generate new dist stylesheets

## Acceptance Criteria
- [ ] above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3120?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
