### ISSUE TITLE
va-search-input does not have a disable-analytics option

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/vets-design-system-documentation#3122]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The `va-search-input` component seemingly does not make use of `disable-analytics` prop. When it is added, the basic analytics event for this component still fires:

<img width="525" alt="Screenshot 2024-08-01 at 4 19 05 PM" src="https://github.com/user-attachments/assets/e7638614-7ec1-4163-b257-7d81fb9434fc">

You can see this when using the search bar on https://www.va.gov/find-forms, typing a search term, and searching (I use the Chrome extension Adswerve to see the events).

## What I expected to happen

I expected the `va-search-input` component to allow disabling the analytics. I looked in the source code for this component: https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-search-input/va-search-input.tsx and the `disableAnalytics` prop is not present as it is for [va-link](https://github.com/department-of-veterans-affairs/component-library/blob/6747a2c36fc17b3a2488b5760a813c4d2f7ab219/packages/web-components/src/components/va-link/va-link.tsx#L39).

## Reproducing
You can add `disable-analytics` to the search input in the Find Forms app here: https://github.com/department-of-veterans-affairs/vets-website/blob/b364d52879588928a756ebfcd7ebe7eaf7788aef/src/applications/find-forms/containers/SearchForm.jsx#L97 and run the code locally using `yarn watch --env api=https://staging-api.va.gov`. Note that the `disable-analytics="true"` prop shows up in the DOM but the `int-search-input-click` still fires when the search happens.

<img width="417" alt="Screenshot 2024-08-01 at 4 22 26 PM" src="https://github.com/user-attachments/assets/95747ade-0034-4a14-82eb-0256ab71cc78">

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

The Sitewide team is working to remove any duplicate Google Analytics events from our products as we pay per event. We have a ticket [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18790) to resolve this duplicate event issue for Find Forms specifically but we can't complete it until this issue is fixed.

**Comment by micahchiang** [comment]
I've removed the `bug` label here because the component isn't broken. This is a feature request, and we'll get it sized and prioritized. 

If this is high priority for public websites, then DST welcomes pull requests from external teams.

**Comment by FranECross** [comment]
@randimays I agree! I'll stub a ticket and share here, and if you want to refine before sprint planning this week, we can then pull it in. Thanks @micahchiang and @randimays !

**Comment by FranECross** [comment]
@randimays Here's the ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18846. Thanks again for this suggestion!
