### ISSUE TITLE
Experimental Design [va-link-action]

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/vets-design-system-documentation#3136]
## What

It would be useful to have a `label` property for the va-link-action component similar to what the va-link has. There is an option of aria-describedby, but that is less useful than an aria-label.  

## Purpose

This would allow us to distinguish multiple similar links to screen-reader users.

## Usage / Examples

We currently use action links for checking into appointments, where there might be a list of appointments.
<img width="364" alt="Screenshot 2024-08-05 at 2 59 54 PM" src="https://github.com/user-attachments/assets/cb4a6833-3a16-4501-8798-cf7bd69f893a">
In the card example above we render the link like this: 
`<a data-testid="action-link" class="vads-c-action-link--green" href="/check-in" aria-label="Check in now for appointment on Monday, August 5 at 3:13 p.m.">Check in now</a>`

We would like to move to using the `va-link-action` component, but we would then loose the aria-label.

## Accessibility

Request relates to accessibility

## Your team

Check-in team

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
I don't think you need to come to DSC for this. This just sounds like a small feature request on va-link. We can accommodate that.

**Comment by loripusey** [comment]
@caw310 This is preventing us from capturing usage metrics on these action link clicks. Because we can't use the DS component, we are not able to capture usage metrics in GA4. We are having to prioritize accessibility over having complete metrics with which to inform our product decisions. We would appreciate some priority placed on this ask. cc: @benbrasso-agile6 @brianseek

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3136?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc
