### ISSUE TITLE
VAFileInputMultiple component adds null value to the files array when adding a file

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/vets-design-system-documentation#3139]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
I am working [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87835) ticket to try to implement the new `va-file-input-multiple` component. I noticed when adding a file and then looking at what was added to the `detail.files` array that we add the file  as well as a null file which seems unnecessary. 

![](https://files.slack.com/files-pri/T03FECE8V-F07FTT134DS/screenshot_2024-08-06_at_9.48.13___am.png)

## What I expected to happen

When I add a file I would expect just that file to be added to the `detail.files` array and not also a null record.
Additionally this requires users who use this to then write specific code to filter out the null record from files.

## Reproducing

Steps to reproduce:

1. Add `va-file-input-multiple` to code
2. Add a file
3. You'll notice that  the file is added as well as a null record

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
As our current work around we will continue to used the V1 version of the `va-file-input` component

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3139?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
