### ISSUE TITLE
Medallia "Feedback" Button Color and Placement Need to Work with "Back to Top"

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/vets-design-system-documentation#315]
# Feature Request

- [ x ] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Medallia interface

## Do you have a suggestion for a new component or utility?

We need to create a feedback button for Medallia in a color that doesn't compete with other buttons on the page. 

## Additional context

We also need to make sure that the button works with the planned implementation of the "Back to Top" button that Ryan Thurwell is working on, which may require experimenting with possible placement and functionality (follow down the page, etc. )

**Comment by KevinMHoffmanUSDS** [comment]
Discussed in the 9/18/2020 Design System Council Meeting.

**Comment by CrystabelReiter** [comment]
@KevinMHoffmanUSDS @sshein @rtwell 
What are your thoughts on making the button this accent cool color from USWDS: https://designsystem.digital.gov/components/button/
^ USA.gov uses this button color for their survey tool

My first thought on the button was to make it our primary green but we don't want the button to compete with other CTAs on the website

We also can't make it a neutral dark/black because from what I remember that's what the back to top component button color is going to be. 

Red is an option but with that color I think that there's sense of urgency about it like how it is for the "crisis button hotline"

**Comment by rtwell** [comment]
Do we know for certain these two components will coexist on the same page? should we put rules in place to govern this? I would like to avoid any page on va.gov turning into times square.

**Comment by CrystabelReiter** [comment]
@rianfowler Is there any flexibility of when/where the feedback button will appear?

**Comment by sshein** [comment]
My 2 cents - it's only the MVP of medallia that will have the floating feedback tab. Later iterations will integrate feedback more tightly into the flows themselves and do away with the floating side button. However, I'm not sure when those later iterations will happen. I also don't know when the 'back to top' button is going to be implemented.  Can anyone answer either of those questions? Joanne? @rtwell (I can't find Joanne's github name, Crystabel can you tag her?)

**Comment by CrystabelReiter** [comment]
I can't find her GH name but I did tag her in slack about this ticket.

**Comment by joanneesteban** [comment]
We have some flexibility on when & where the feedback button will appear. What are the thoughts on where it shouldn't appear? 

For moving away from the floating side button, I'd like to have a solution that works a bit more universally for the pages on the site and fits better for the design system, or test which options provide us more feedback.

Here are the out of box solutions for Medallia. Anything else we'll need to consult with the Front End team to include in the CSS:
![image](https://user-images.githubusercontent.com/48964695/93817704-5187cd80-fc27-11ea-8026-fcf393b0491e.png)

**Comment by rtwell** [comment]
Back to top will be live by december at the latest.

**Comment by CrystabelReiter** [comment]
Should we keep the floating side button, and work with the back to top button when it's getting implemented? Make sure there's no crossover. We'll have more control over the back to top button placement. 

@joanneesteban For now, we can try this button color. Let's see how this works with the other buttons. 

Background color: #02BFE7
Text color: #212121

**Comment by joanneesteban** [comment]
@CrystabelReiter Changed the button background and text colors to the above. You can test this out on staging.va.gov/find-locations. Let me know if we need to change anything else.

**Comment by rtwell** [comment]
@CrystabelReiter that's fine. I think we should create governance around what pages are allowed to have which interaction. imo, feedback and back to top should not coexist on the same page

**Comment by CrystabelReiter** [comment]
@rtwell I concur. We can work with what pages will and not have this feedback tab. Thanks @joanneesteban the change hasn't updated yet but I can take a look again later

**Comment by joanneesteban** [comment]
@CrystabelReiter any updates on the Feedback button QA?

**Comment by CrystabelReiter** [comment]
@joanneesteban looks fine to me 👍🏼

**Comment by KevinMHoffmanUSDS** [comment]
@ianMcCullough-ob Is currently researching this issue. @emilywaggoner suggested we follow up as this research is completed.

**Comment by ianMcCullough-ob** [comment]
> @ianMcCullough-ob Is currently researching this issue. @emilywaggoner suggested we follow up as this research is completed.

I'll share our my findings once I wrap everything up! Should be early the week of 11/30

**Comment by humancompanion-usds** [comment]
@ianMcCullough-ob has provided findings which will go live with this pull request:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/946

**Comment by humancompanion-usds** [comment]
Published! https://design.va.gov/patterns/feedback#research
