### ISSUE TITLE
va-date error issues

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#3152]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

It's possible some of this is related to [VaDateInput style issue when in error state](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3113) but there are also new issues in this ticket as well.

## What happened

![image](https://github.com/user-attachments/assets/01d9878b-0b07-43f7-beb5-15aeeae9d96d)

1. `va-date` has extra padding to the left when using `month-year-only="true"` and the screen size is bigger than `1008px`. Notice the `padding-left` is `20`, but other web components such as `va-memorable-date` are `16` when it errors.
2. `va-date` select icon styling is different than other web component selects (Looks like this might already be fixed on storybook, but maybe we're still seeing the old version on vets-website for now).
3. "Select" word sometimes gets cutoff both vertically and horizontally. You can see this on story book if you scroll down a bit.
4. Label is not bold like other web components when error is thrown
5. Error message says "Please enter a month between 1 and 12", but it is a select box, not a text box, and has names of months, not numbers. 

I believe some of these were already solved for `VaMemorableDate`, so maybe `VaDate` needs a parity pass.

## What I expected to happen

1. Should be consistent with other web components and `va-memorable-date`
2. Should be consistent with others select components
3. Should not be cut off vertically. Not sure about horizontally.
4. Label should be bold when there is an error
5. Error message should be more appropriate. See what va-memorable-date does.

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

Put a `va-date` with `month-year-only="true"` next to a `va-memorable-date` and compare differences.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3152?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by rhasselle-oddball** [comment]
Also seeing this issue:
![image](https://github.com/user-attachments/assets/b686c25f-cea2-434b-afd5-183136bc60b8)
