### ISSUE TITLE
Update pattern: Help users to...stay informed of their application status (notification touch points, My VA status)

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#3163]
## Problem Statement 

The Design System does not instruct VFS teams on their obligation to send notifications to users at certain touch points when a user submits a form/application to the VA via VA.gov.

## Hypothesis or Bet
* VFS teams should be able to follow Design System guidance in a pattern that describes the required and optional touchpoints for notifications, starting with forms/applications on VA.gov and limited to email notifications.
* Once we have this guidance we should be able to govern notifications and ensure that all form/application submissions are acknowledged and that users are notified at specific points as their submission progresses.

## We will know we're done when... ("Definition of Done")
* A published pattern on design.va.gov that details when notifications must (required) and can (optional) be sent for a form/application submission.
  * This pattern should point teams at the VA Notify intake form and/or documentation of how they can establish email notifications. 
* Governance team is made aware of this guidance update and are asking for proof that notifications are happening at the agreed upon touch points at Staging review.

## Known Blockers/Dependencies 

* VA Notify does have a record of each notification that is currently sent. Dave and the team need some time to wade through all of the notifications that are sent. Dave will communicate when the audit is complete and share the results.

## Projected Launch Date

This new pattern should be following on from the status work the Veteran-facing Forms team, 526 team, and MyVA (auth. exp.) teams are all working on now. Target start would be next quarter. This should be achievable inside of a quarter.

### Meeting notes from a meeting Dave, Danielle, Mikki, and I had on Thr Aug 8 to discuss documentation of notifications
 
* Forms should send a confirmation using VA Notify when a form is submitted.
* Danielle and Dave want to create a content style guide section for notifications. 
* Establish the core required touch points and then which are optional.
  * Appointments team did an audit.
  * Dave still working through all of the notifications we send. Email, SMS, sort of push notifications through the mobile app.
  * VA Notify does have a record. Dave needs some time to wade through all of the notifications that are sent.
  * Notifications center within My VA. Users will have a canonical place within the auth. exp. where this information is accessible. Users will be able to express preferences of how they get notifications.
* Dave working on a "complete this form" email. 5 forms using it. Don't know yet if this is successful. We may want to add this later.
* Rules around notifications, when they are sent and how, opt-in/opt-out defaults. For forms it is an opt out (versus opt-in) experience. 
  * SMS legally requires opt-out.
* VA Notify has an intake request for when you need a notification: [https://github.com/department-of-Veterans-affairs/va.gov-team/issues/new?assignees[…]Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D](https://github.com/department-of-Veterans-affairs/va.gov-team/issues/new?assignees=christy-tongty%2C+mjones-oddball%2C+GitSamJennings&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D)

* Dave: There may be information in here that we might want to move and/or deprecate as it goes into design.va.gov https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/notification-guide.md
* Dave: So I was thinking about the design system a bit more. One thing I think we need to also be careful of is there's a nuance between 'you've submitted your form" and 'we've received your form". We don't want to say that they've submitted the form and then we have a hiccup and a silent failure. We should be clear on the guidance pattern that "You don't send a 'success' notification unless you're 100% sure that step is a success"

**Comment by humancompanion-usds** [comment]
Tagging @jeana-adhoc on this initiative.

**Comment by humancompanion-usds** [comment]
I decided to stick with updating the Help users to...stay informed of their application status pattern given that it already covers much of this information and splitting out just notifications felt insufficient in terms of what needs to be communicated to teams. I have a [PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3315) up for the initial draft.

@jeana-adhoc @danbrady @babsdenney - Would appreciate feedback on this pattern update. Thanks!

**Comment by humancompanion-usds** [comment]
@jeana-adhoc @danbrady @babsdenney - Also, would appreciate your help in getting the [examples Jeana has put together](https://www.figma.com/design/dlhofkIJz3MC81PD0pJAb8/OCTO-%7C-Form-Status-Project-(VFF-%2B-My-VA)?node-id=0-1&t=PQ718Ka2Kc5XKder-1) into our Figma library for patterns, as you see fit.

**Comment by humancompanion-usds** [comment]
Items I have not covered and need to do more on in future:
* How does this work for Health applications, and specifically for Premal's upcoming CHAMPVA forms? There is a Health care section of MyVA but I'm not sure what shows up there and what does not.
* Where do forms that have 2 pathways to submission show up? For example, the 0966 Intent to file is submitted both stand alone and within the 526 and 0955 forms. The former show up in Benefit applications and forms in MyVA but the latter either don't show up or do in Claim Status Tool (unsure).
* What other touchpoints are other teams using within Benefits? I believe the 526 teams has a slightly different list. Do we want to remain flexible there or push all forms to use the 2-3 defined in this pattern?
* Submissions that become stale. This is a much bigger issue, but this pattern could eventually cover what to do about submissions that stay in pending beyond the expected processing timeframe.

**Comment by jeana-adhoc** [comment]
> Where do forms that have 2 pathways to submission show up? For example, the 0966 Intent to file is submitted both stand alone and within the 526 and 0955 forms. The former show up in Benefit applications and forms in MyVA but the latter either don't show up or do in Claim Status Tool (unsure).

The VFF team needs to figure this out for the 0966 and when we do that we'll be reaching out to the 526/0995 teams. As we move through that work I'll try to figure out what can be extrapolated for best practices. That could be added back here.

**Comment by babsdenney** [comment]
Will there be any documentation covering physical mail communication?

**Comment by humancompanion-usds** [comment]
@babsdenney - When we figure out if that is something VA Notify can help with. Right now they are focused on adding a call-back mechanism so a team can see if an email failed to be delivered.

**Comment by humancompanion-usds** [comment]
> Where do forms that have 2 pathways to submission show up? For example, the 0966 Intent to file is submitted both stand alone and within the 526 and 0955 forms. The former show up in Benefit applications and forms in MyVA but the latter either don't show up or do in Claim Status Tool (unsure).

This is tracked in https://github.com/department-of-veterans-affairs/digital-experience-products/issues/1221

**Comment by humancompanion-usds** [comment]
From @jstrothman:

> 1. The VADS pattern doesn't mention how to handle sub-forms, e.g. the 4142 on 526 and 0995
>   * Emily, Matt D, & I decided we should show those as separate cards and mention that it was submitted with [parent form]
> 2. The VADS pattern doesn't include info about uploaded documents
>   * My recommendation is that we include in the card info to the effect of: You uploaded 22 documents. We'll email you if we can't successfully deliver any of them.

I concur and will update this pattern asap.

**Comment by humancompanion-usds** [comment]
Pattern is updated!
