### ISSUE TITLE
Add desktop and mobile breadcrumb symbol to pattern library

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#317]
## Is this feature request relating to an existing component or utility? Please describe.
I'm not sure if there is already a breadcrumb symbol in our Sketch library. I saw [a component audit issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/206) that suggests there is, but I don't see it when I look for it in the library file or via the `Insert >` menu

## Do you have a suggestion for a new component or utility?
I think it'd be helpful to create a symbol for this so we can encourage consistent implementation/representation in designs.  Especially since the mobile breadcrumb is different (only shows immediate parent, and preceded by a `<` symbol.

## Additional context
I wasn't even aware of the difference in mobile breadcrumbs and it was pointed out in a design review for some of my mobile designs. To prevent that from happening in the future, I created my own symbol so I can consistently represent this in my design. Would save time of both reviewers and designers if we could easily drop in the right thing.

**Comment by CrystabelReiter** [comment]
Added to most recent sketch library update
