### ISSUE TITLE
Mega menu right-most column flaky on injected header

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/vets-design-system-documentation#3177]
## Status

- 2024-03-20: Revisit after the flattened header/footer is released. May be able to close.
- 2024-03-20: The majority of the flattened HTML work is completed, so unblocking this ticket.
- 2024-01-25: Blocked until after the header/footer, and injected header flattened HTML work is finished.

## Description

Here is is a legacy (TeamSite) page with the injected header: https://www.va.gov/health/

At widest screens, things look good:
![image](https://user-images.githubusercontent.com/6863534/193114286-9fd45585-fa95-4ab9-bf41-ede49c91bfaf.png)

At medium-ish widths, though, the right-most column goes blank:
![image](https://user-images.githubusercontent.com/6863534/193114533-37bf0997-169a-497c-bdb1-b8549777699f.png)

This is how things look at that width on the modernized pages. The right-most column is never "blank". It is initially populated:
![image](https://user-images.githubusercontent.com/6863534/193115005-041df849-2bae-4fc4-ba11-70b4a62c7530.png)
Then, eventually, the column goes away all together:
![image](https://user-images.githubusercontent.com/6863534/193115326-bbdab585-ce37-4920-8d8d-cfce4f642c7e.png)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3177?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by randimays** [comment]
@caw310 I was able to fit this fix into my injected header/footer split PR; now the mega menu there (https://www.va.gov/health) matches what is in the modernized site (https://www.va.gov). We should be able to close this.

See prod screenshots below for reference.

## 768px screen width
### Injected
<img width="600" alt="Screenshot 2024-08-13 at 2 34 17 PM" src="https://github.com/user-attachments/assets/30f6fd5b-85d3-42ca-9c6c-a4ce11c592fe">

### VA.gov home
<img width="600" alt="Screenshot 2024-08-13 at 2 34 13 PM" src="https://github.com/user-attachments/assets/f8fe92ab-b3ac-4249-b097-0872070d3211">

## 960px screen width
### Injected
<img width="800" alt="Screenshot 2024-08-13 at 2 33 58 PM" src="https://github.com/user-attachments/assets/55c6d03a-cd69-4e1b-bfb7-c5b63f345315">

### VA.gov home
<img width="800" alt="Screenshot 2024-08-13 at 2 33 53 PM" src="https://github.com/user-attachments/assets/108a0fbf-5227-47cb-a732-0f390040478a">

## 1200px screen width
### Injected
<img width="1201" alt="Screenshot 2024-08-13 at 2 33 38 PM" src="https://github.com/user-attachments/assets/73f380ff-4c8a-4b73-8086-9cd0aec99b6e">

### VA.gov home
<img width="1197" alt="Screenshot 2024-08-13 at 2 33 31 PM" src="https://github.com/user-attachments/assets/42627554-edcb-4308-b446-f16b420adbd3">

**Comment by caw310** [comment]
Closing per Randi's comment that she was able to fit in this work.
