### ISSUE TITLE
Experimental Design [Color tokens for forms in the mobile app]

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/vets-design-system-documentation#3187]
## What

> Give a brief description of the component or pattern you want to propose.

The mobile app design system team would like to add two new USWDS tokens for use in two new semantic tokens.
 
**Primitives**
- uswds-system-color-blue-warm-5
- uswds-system-color-blue-warm-80

**Semantic**
- vads-color-forms-surface-active-on-light (references blue-warm-5)
- vads-color-forms-surface-active-on-dark (references blue-warm-80)

![image](https://github.com/user-attachments/assets/972448dc-60e4-455e-9900-229b1e8d5c64)

## Purpose

> What problem does this component or pattern solve for the user?

Currently, the web's tile version of the Checkbox/Radio components adjusts the opacity for the background colors. In the mobile app, the Checkbox/Radio components can appear on different colored backgrounds, so we'd like to avoid adjusting the opacity. The new light mode color token is almost identical to the existing VADS color with opacity.

![image](https://github.com/user-attachments/assets/805c34ee-be7e-4b95-afef-ae13d87e880e)

## Usage

> **Context or task**: Explain the scenario or user tasks where this component is, or could be, used.

These two new color tokens will be used in forms. Currently, they are used in the Checkbox and Radio components.

## Behavior

> Describe the key interactions for this component, calling out any specific considerations for mobile.

N/A

## Examples

> Include any examples you have of this component or pattern. These can be screenshots, links to a Sketch file, or links to staging or production.

N/A

## Accessibility

> Include any accessibility considerations.

N/A

## Guidance

> What would you want to tell other teams about this component or pattern?

N/A

## Collaboration Cycle Ticket

> Provide a link to your collaboration cycle ticket. 

N/A

## Your team

> Tell us what team you are on. 

Mobile app design system team

## Research (optional)

> Include any research you have already conducted, or plan to conduct, on this component or pattern.

N/A

## Code (optional)

> Include any existing code.

N/A

## Next steps

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval.

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision.

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system/add-a-component-or-pattern-once-approved). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
@jessicawoodin It isn't necessary to bring this to DSC. 
@humancompanion-usds or @danbrady will add the color tokens.

**Comment by jessicawoodin** [comment]
@caw310 Thank you for letting me know. Is there a different process (or [issue template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new/choose)) that we should follow when we need things like this added to the VADS?

**Comment by caw310** [comment]
@jessicawoodin there isn't a process yet for color tokens since this is new. I would say use the bug documentation or support template? https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new/choose

Once we have a process for these types of requests we'll post something in the design channel.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3187?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
In VADS, we currently use `vads-input-tile-background-active-on-light` for this. As mentioned, that token's value currently uses opacity so the background color seeps through which can be problematic on colored backgrounds. Should we agree to update that value to a fully opaque color instead and add a `vads-input-tile-background-active-on-dark` and both teams use these same tokens/colors?

Thoughts @jessicawoodin @humancompanion-usds?

**Comment by humancompanion-usds** [comment]
I'd like to avoid using opacity so, yes, for the changes you described.
