### ISSUE TITLE
Add back variant to va-link in Figma - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3190]
## Description
Create design for va-link back variant and/or update Figma artifacts for link

## Details
Experimental design request this originates from. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2797#top

## Tasks
- [ ] Create designs for component
- [ ] Review designs with PO and DST designers 
- [ ] Review designs with developers and accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility and development considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3190?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
From a design perspective, for Figma, this is the exact same thing that already exists as a variant for the [Breadcrumb component](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=798-931&t=mkQXot8FDs860zr4-1). Do we really need to add a variant of this to link? Or does this suffice?

![Screen Shot 2024-08-23 at 11 13 32 AM](https://github.com/user-attachments/assets/220f00a8-7c82-4cf6-b292-db26dc8d59e8)

**Comment by LWWright7** [comment]
@danbrady @babsdenney This one is ready for review!

**Comment by danbrady** [comment]
@LWWright7 LGTM!
