### ISSUE TITLE
Remove disabled checkbox group examples from storybook

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/vets-design-system-documentation#3191]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

Checkbox

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [X] Accessibility considerations
- [ ] Content considerations
- [ ] Implementation
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Folks find the disabled examples in the checkbox group but we don't support that in VADS. Can it be removed? There are two instances. 

https://design.va.gov/components/form/checkbox#examples---group

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3191?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@caw310 Can you change this to a dev ticket? We do not have disabled checkboxes in the Figma design system.  It does need to be removed from documentation as well so could you make a ticket for that, please?  Thanks.

**Comment by micahchiang** [comment]
We do provide the option to disable an individual checkbox, so I'm not sure we want to remove these completely. Should examples instead be moved to individual checkbox?
