### ISSUE TITLE
VA.gov Pattern Library - Templates Layouts

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/vets-design-system-documentation#320]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- VA.gov Pattern Library - Templates

## Do you have a suggestion for a new component or utility?

The layout columns for the templates provided in the pattern library need updating to represent appropriate VA.gov layout areas. 

Currently, they look like this: 
<img width="999" alt="Current Pattern Library Templates Layout Columns" src="https://user-images.githubusercontent.com/41477797/95379673-b132d980-08b3-11eb-9e29-86bf2ef4d703.png">

In the old Vets.gov pattern library that is a precursor to our current pattern library, layout columns were appropriately designated:

<img width="863" alt="Vets gov Pattern Library Templates Layout Columns" src="https://user-images.githubusercontent.com/41477797/95379792-d889a680-08b3-11eb-9325-4030644706a7.png">
 

## Additional context
Here's an old copy of the Vets.gov pattern library from Aug. 2018 as a reference:
[vets-gov-pattern-library.sketch.zip](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/5343429/vets-gov-pattern-library.sketch.zip)

**Comment by CrystabelReiter** [comment]
Thanks @ccruzgra I'll fix these in the next update

**Comment by CrystabelReiter** [comment]
Fixed in most recent update on 10/15
