### ISSUE TITLE
Add List guidance to VADS

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#3206]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Utility

### What is the name?

Lists

### What is the nature of this update?

- [ ] How to build this component/pattern
- [X] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility considerations
- [X] Content considerations
- [X] Implementation
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

There is an anchor link to "List" documentation on this page https://design.va.gov/foundation/typography#lists  Maybe "List" in the "On this page" component should just be removed.

But the documentation for lists does not exist here at all. Maybe the guidance should point to here https://design.va.gov/components/list. But what I was looking for was the proper VADS way to turn off the left padding on unordered lists with no list style type.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3206?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7
