### ISSUE TITLE
Radio Button: Stray aria-describedby points to an ID that doesn't exist

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/vets-design-system-documentation#3225]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On our Higher Level Review form, maintained by the Decision Reviews team, we're seeing some stray `aria-describedby` attributes that point to an ID that doesn't exist. This shows up when you have an optional description for the radio button. It looks like this:

```html
<span class="usa-radio__label-description dd-privacy-hidden" data-dd-action-name="description" aria-describedby="option-label">VA may contact me by mail, telephone, email, or another way to schedule my conference.</span>
```

Note the extra `aria-describedby="option-label"` but that `option-label` doesn't exist.

This also happens in [one of the Storybook demos](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--error).

## What I expected to happen

We wouldn't expect the aria-describedby to show up if something it points to isn't present.

## Reproducing

- Formation version: N/A
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1. View the [Storybook demo](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--error).
2. Note the extra `aria-describedby="option-label"` but that `option-label` doesn't exist.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

Screenshot from the Higher Level Review form:

![Screen from Higher Level Review form with aria-describedby="option-label" but that `option-label` doesn't exist.](https://github.com/user-attachments/assets/6322d9c5-169e-4cde-b1fe-a606859f9313)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3225?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
