### ISSUE TITLE
Additional VA.gov Pattern Library Templates

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/vets-design-system-documentation#327]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- VA.gov Pattern Library - Templates page

## Do you have a suggestion for a new component or utility?

It would be helpful for designers, especially new designers coming into VA.gov, to have access to additional templates when they are creating prototypes, such as sample sign-in pages or additional sample form pages. The Vets.gov Pattern Library Sketch file that precedes our current VA.gov Pattern Library had a comprehensive collection of templates, and some of them could be leveraged and updated to reflect the latest VA.gov patterns for the benefit of designers. 

## Additional context

Vets.gov Pattern Library Sketch file: 
[vets-gov-pattern-library.sketch.zip](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/files/5394822/vets-gov-pattern-library.sketch.zip)

**Comment by CrystabelReiter** [comment]
Thanks Cindy! I'll try to prioritize this in my next sprint's work. :)

**Comment by caw310** [comment]
Closing as there have been templates added.
