### ISSUE TITLE
VADS website – sample links are scrolled out of view

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/vets-design-system-documentation#3275]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Rendering of [examples](https://design.va.gov/components/link/) of the vads `link` – for each example link I'm just seeing the tippy tops of text and have to scroll within the "window". it took me two visits and then two browsers to figure out I needed to scroll within the frame.

<img width="286" alt="image" src="https://github.com/user-attachments/assets/30c7b724-6d0d-4786-a00e-13f0379191be">

## What I expected to happen

See it without scrolling.

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook) Mac
- Browser: (e.g. Firefox, IE 11) Chrome, FF

Steps to reproduce:

1.
2.
3.
4.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by danbrady** [comment]
Looks like `p` were added to the storybook examples and that added margin around the component. Updated iframe sizes to compensate on the doc site.
