### ISSUE TITLE
va-accordion header level set based on nested va-alert content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#3281]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On the review & submit page in a `va-accordion-item` a [`level={3}` is hard-coded](https://github.com/department-of-veterans-affairs/vets-website/blob/ca060a5ed4edb45fdebb50e29403cb54b6c17bde/src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx#L479); but we're seeing an `h4` being rendered!

It appears that inside the [`va-accordion-item` code](https://github.com/department-of-veterans-affairs/component-library/blob/6747a2c36fc17b3a2488b5760a813c4d2f7ab219/packages/web-components/src/components/va-accordion/va-accordion-item.tsx#L110), it looks for _any_ `slot="headline"` in the content, but in our case, we have a `va-alert` with a header. And I _think_ that it's finding the `slot="headline"` for the `va-alert` and setting the `va-accordion-item` header level to match it.

<img width="1072" alt="review page with Supplemental claim issues for review showing the accordion header is an h4, but the level is set to 3. Inside the accordion is a va-alert with an h4 slot equals headline likely causing the accordion header level change" src="https://github.com/user-attachments/assets/e4e72280-2a78-4f63-89cd-41a479f9506d">

## What I expected to happen

I was expecting the hard-coded `level` property in `va-accordion-item` to over-ride the header level setting. Or, that the `va-accordion-item` would only look one-level deep for the slot.

## Reproducing

- Formation version: Current
- Device: (e.g. iPhone 8, Macbook): All
- Browser: (e.g. Firefox, IE 11): All

Steps to reproduce:

1. Go to https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995
2. Log in to any user (I use `vets.gov.user+0@gmail.com`)
3. Fill out the minimal amount of data (choose no for all types of evidence)
4. Get to the review & submit page
5. Open "Issues for review" accordion
6. Edit "You've selected these issues for review"
7. Un-check _all_ issues
8. Use `headingsMap` or inspect "Issues for review" accordion header. It should be `h3`
9. Select "Update page"
10. Note that the "Issues for review" accordion header is now an `h4` - this matches the alert header level

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [x] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment]
[slack convo](https://dsva.slack.com/archives/C01DBGX4P45/p1726519963578589)
