### ISSUE TITLE
va-select: support for `optgroup`

### ISSUE THREAD

**Issue by oleksii-morgun** [department-of-veterans-affairs/vets-design-system-documentation#3286]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

`va-select` does not currently have support for `<optgroup>` tag containing `<option>` elements. Instead, `populateOptions` function parses out only `<option>` tags without consideration for `<optgroups>`

## What I expected to happen

Since `<optgroup>` is suported by native HTML `<select>`, it would be useful to have `va-select` support it as well to accommodate for specific design needs. 

## Reproducing

- Formation version `"11.0.21"`
- Component Library version `"46.3.0"`
- Device: All
- Browser: All

Steps to reproduce:

1. Attempted the following implementation 👇🏻 
```
   
<va-select
      aria-live-region-text="You selected"
      label="Branch of Service with OPT GROUPS"
      message-aria-describedby="Optional description text for screen readers"
      name="options"
      value=""
    >
      <optgroup label="Group 1">
        <option value="navy">Navy</option>
        <option value="army">Army</option>
      </optgroup>

      <optgroup label="Group 2">
        <option value="marines">Marines</option>
        <option value="air-force">Air Force</option>
        <option value="coastguard">Coastguard</option>
      </optgroup>
 </va-select>
```

2. Component renders like so 👇🏻 
![Screenshot 2024-09-18 at 11 03 22 AM](https://github.com/user-attachments/assets/37643cdc-fc41-4945-abd6-71f9a9b8bcb6)

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
The need for optgroup support was initiated by the [discussion on Slack ](https://dsva.slack.com/archives/C8E985R32/p1719874010977669). MHV Secure Messaging have a design intent that needs to be supported by this feature. According to input from other specialists, adding `optgroup` support should be compliant from accessibility perspective as well.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3286?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc
