### ISSUE TITLE
Increase number of checkboxes available in Radio Buttons component

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#3292]
### Duplicate check

- [x] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

Radio Buttons

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility considerations
- [ ] Content considerations
- [x] Implementation
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Appointments has [a radio button list with 12 options](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=627-57984&t=hbOuagGUyD1JzvgI-4) that we're working on documenting. The [VADS Radio Buttons component]( https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=495-11388&t=OhoGYTMPjwNRnQGk-4) supports up to 10. This request would increase the number of possible radio buttons.

### Additional Context

If there is a limit to the number of allowable radio buttons in a list we're happy to discuss other options for future work - right now we're just trying to document the existing state. @sterkenburgsara recommended a few things to consider when we hit this in the future:

- Conditionally revealing sub-options under some radio buttons. perhaps you could have a smaller # of higher-level categories in order to reduce cognitive load here? There is some guidance about this in the VADS documentation
- Using a drop-list

**Comment by caw310** [comment]
@outerpress there isn't a limit technically. Are you referring to what is in Figma or guidance? I do not see a limit described.

**Comment by outerpress** [comment]
@caw310 yes this is for the Figma component. FYI @danbrady

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3292?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by danbrady** [comment]
Yep, I can take care of this. Peter requested this in Figma, but I asked him to add an issue so we can keep track of it. Thanks you both @outerpress and @caw310!

**Comment by danbrady** [comment]
Radio buttons component updated.

**Comment by outerpress** [comment]
Thanks @danbrady ! Works perfectly 👍
