### ISSUE TITLE
Add disabled variation to button - Design

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#3306]
## Description
Create design for disabled button variation and/or update Fiigma artifacts for va-button.

If this is a pattern or component that is already in existence, conduct a small-scale audit (3-5 examples) to make sure there aren't design issues that need to be addressed. Also, check the Design System Team backlog for outstanding design issues. If you find any, link to them in a comment on this ticket. If possible, address any outstanding issues with this design and link to this issue from the original issue. If not, indicate that in the original issue.

## Details
Original experimental design request: [Experimental Design - improvements to va-button disabled variation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2792#top)

## Tasks
- [ ] Conduct small audit if necessary (if component already exists and we are building a new version)
- [ ] Review DST backlog for outstanding design issues with this component, if necessary (if this component already exists and we are building a new version)
- [ ] Create designs for component
- [ ] Review designs with PO and DST designers 
- [ ] Review designs with developers and accessibility specialist
- [ ] Review designs with DST members (Carol can help schedule this)
- [ ] Address any comments from reviews, if necessary
- [ ] Comment on this ticket with any accessibility considerations engineers may need to know
- [ ] Comment on this ticket with content specifications (e.g. labels and error messages)
- [ ] Comment on this ticket with a link to the designs and post in DST Slack channel

## Acceptance Criteria
- [ ] Component design is complete and has been reviewed
- [ ] Accessibility and development considerations have been added to this ticket, if necessary
- [ ] Content specifications have been added to this ticket, if necessary
- [ ] Link to design has been added to this ticket and shared in Slack

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3306?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment]
@babsdenney & @danbrady this one is ready for review [here](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1198&t=kHJI4Z481cRErWwd-1).

**Comment by LWWright7** [comment]
@rsmithadhoc - also, the person who initiated this ticket had some concerns about contrast on this one....could you please double check.  They said "The current background color doesn't have sufficient contrast ratio against background colors on va.gov (modal variations + standard white page background)." Thanks!

**Comment by caw310** [comment]
Notes from Design weekly chat: 

- Only the Loading button for disabled variation. 
- Icon should be standardized so it will not be changeable. 
- Loading should be default text.

**Comment by rsmithadhoc** [comment]
> [@rsmithadhoc](https://github.com/rsmithadhoc) - also, the person who initiated this ticket had some concerns about contrast on this one....could you please double check. They said "The current background color doesn't have sufficient contrast ratio against background colors on va.gov (modal variations + standard white page background)." Thanks!

@LWWright7 Yeah, that is correct. 
- The button background would need to be `--uswds-system-color-gray-40` (`#919191`) to have enough contrast between it and the site background (`#FFFFFF`).
- Darkening up the button background means that the text needs to be darker as well. I think the minimum we can go for a warm gray is `#2A2A28` or darker. I didn't see a token for `gray-warm-darker`, so I will leave that up to you.
- It doesn't look like there are any differences in focus/hover for this button, which is fine and expected for the disabled button, so nothing should need to be done contrast-wise for those.

**Comment by caw310** [comment]
Added @danbrady as assignee to finish up the remaining work on this ticket before the end of the sprint as  @LWWright7 is out this week.

**Comment by danbrady** [comment]
@babsdenney [Ready for review](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199-1198&t=ljjZTHu0YNsbpnUL-1)!

**Comment by babsdenney** [comment]
@danbrady This looks great! Thank you for working on it.
