### ISSUE TITLE
Write instructions for implementing va-on-this-page to replace remaining "fake" instances on VW

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#3318]
## Description
It's worth noting that there are currently 5 pages that have "fake component" versions of the va-on-this-page component that all still use the dl/dd combo to display links and should probably be converted:

1. vets-website/src/applications/combined-debt-portal/debt-letters/components/DebtDetailsOnThisPageLinks.jsx
2. vets-website/src/applications/combined-debt-portal/debt-letters/components/OnThisPageLinks.jsx
3. vets-website/src/applications/combined-debt-portal/medical-copays/components/OnThisPageDetails.jsx
4. vets-website/src/applications/combined-debt-portal/medical-copays/components/OnThisPageOverview.jsx
5. vets-website/src/applications/combined-debt-portal/medical-copays/components/OnThisPageStatements.jsx

According to [#2493](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2493), these fake components were created as a workaround because the va-on-this-page component was not correctly finding all of the h2's on the page, so this work may be solved by resolving #2493.

## Details
As part of #1998 (and subsequent PR [#1346](https://github.com/department-of-veterans-affairs/component-library/pull/1346)), we converted the va-on-this-page component to make use of ul/li elements rather than dl/dd elements. The above five pages have "fake" on-this-page components which still utilize the old dl/dd combo and which could probably be updated to use the va-on-this-page component instead.

## Tasks
- [x] Provide instructions for how to convert these pages to use va-on-this-page

## Acceptance Criteria
- [ ] Instructions handed-off to Combined Debt Portal team

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3318?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc

**Comment by Andrew565** [comment]
It was discovered while looking into #2493 that these "fake" on-this-page components were created because the on-this-page component wasn't discovering all of the desired h2s. Those missing h2s were not discovered because they either were not wrapped in an `article` element, or had no ID attributes (meaning that they could not be used as anchor links).

When this ticket is worked on, the remedy will need to include modifying parts of the combined-debt-portal components and pages in order to ensure all of the h2s are getting picked up by the on-this-page component, in addition to replacing the 'fake' dt/dl-based components with va-on-this-page.

**Comment by caw310** [comment]
@Andrew565 will write instructions for teams to be able to replace their fake instances of va-on-this-page.

**Comment by Andrew565** [comment]
Instructions handed off to Joseph Lee on the VFS/Debt Resolution team.
