### ISSUE TITLE
Formation Deprecation - Remove Shared Variables Import generator-vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3322]
## Description
One of the last things we need to do in order to move off of Formation is remove the shared variables import from application stylesheets. This stylesheet is added as boilerplate in the generator-vets-website repository [here](https://github.com/department-of-veterans-affairs/generator-vets-website/blob/master/generators/form/templates/entry.scss.ejs) and [here](https://github.com/department-of-veterans-affairs/generator-vets-website/blob/master/generators/app/templates/entry.scss).

## Considerations
- We'll need to bump the version of generator-vets-website and publish to npm. This may need to be done from the command line. 

## Tasks
- Remove shared variable import statements from generator-vets-website, bump the version number for it, publish to npm and then update the dependency in vets-website.

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3322?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc
