### ISSUE TITLE
Support question: Adjusting width for va-radio-option in the development environment

### ISSUE THREAD

**Issue by cora-goldston-bah** [department-of-veterans-affairs/vets-design-system-documentation#3324]
# Support question

- [X] I’ve searched for any related issues/questions on github

## How can we help?

This is a follow-up to [issue #1937](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1937). As noted in that previous issue, Figma now allows designers to override the va-radio-option width. However, when our developers are working in the development environment, they're encountering a platform-wide style that constrains the va-radio-option width to 320px.

It appears the 320px platform-wide style is related to visibility on mobile devices. However, the development environment is constraining the width, even on our desktop pages.

Is there a way to override the width in the development environment? If not, we'd like to explore how we can make this possible in the future.

Thank you!
Transition Experience Team

**Comment by cora-goldston-bah** [comment]
Looping in the Transition Experience team
@nkontrabecki @vetskrieg @iseabock @RonnieYoung-UX

**Comment by micahchiang** [comment]
You should be able to target labels and adjust their width in your app stylesheet. MHV does something similar here - https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv-secure-messaging/sass/compose.scss#L16

**Comment by cora-goldston-bah** [comment]
Thank you, @micahchiang! We will look into this on our stylesheet.

**Comment by caw310** [comment]
@cora-goldston-bah is this still an issue or can we close this?

**Comment by cora-goldston-bah** [comment]
@caw310 We're all set, so I will close this ticket — thank you!
