### ISSUE TITLE
Discovery: Stencil and Lit interoperability

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#3344]
## Description
The USWDS team has asked us to collaborate in running some discovery to determine the extent to which Stencil and Lit are interoperable. Some [prior research](https://vfs.atlassian.net/wiki/spaces/DST/pages/3488645807/Stencil+vs+Lit) was done to assess the differences between the tools, and now we'd like to see what happens if we attempt to either consume, or inherit from, a USWDS Lit component. 

We should dedicate some time to researching the outcomes around this. 

## Considerations
- [Prior research](https://vfs.atlassian.net/wiki/spaces/DST/pages/3488645807/Stencil+vs+Lit)
- [Lit documentation](https://lit.dev/)
- [uswds web-components repo](https://github.com/uswds/web-components)
- The above uswds web-components package has no official releases, so we either need guidance from the uswds team on how to access their components, or consider publishing a test build to verdaccio to use ourselves

## Tasks
- [ ] Try to build a VADS component that consumes the uswds usa-link component and wraps it in stencil. Document any findings and challenges around what happens in a document published to confluence.  

## Acceptance Criteria
- [ ] Above tasks have been completed

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3344?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc

**Comment by Andrew565** [comment]
Research notes here: https://vfs.atlassian.net/wiki/spaces/DST/pages/3580919811/Discovery+Integrating+a+Lit-based+WC
