### ISSUE TITLE
Allow `VaFileInputMultiple`'s `onVaChange` to act only on the most recent item in the list

### ISSUE THREAD

**Issue by JoshingYou1** [department-of-veterans-affairs/vets-design-system-documentation#3348]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Reproducing

- Formation version: 1.0.1
- Device: Macbook
- Browser: Google Chrome

Steps to reproduce:

1. Create a `VaFileInputMultiple` component.
2. Add error handler based on the storybook example: https://design.va.gov/storybook/?path=/docs/uswds-va-file-input-multiple--docs. Place a console log inside of `event.detail.files.map(async (file, index) => {`
3. Upload multiple files and ensure the console log is being logged once per file.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

![Image](https://github.com/user-attachments/assets/8121a452-693f-4cb2-a43c-b5802fd2bbb6)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3348?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc

**Comment by ataker** [comment]
Based on [this support request](https://dsva.slack.com/archives/CBU0KDSB1/p1728318840098689)
