### ISSUE TITLE
Modal text overflow

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/vets-design-system-documentation#3355]
# Bug Report

- [x] I've searched for any related issues and avoided creating a duplicate issue

## What happened
When a 'va-modal' displays a long word (e.g. 30 characters or more) the text overflows and/or breaks the layout.

## Screenshots
![Image](https://github.com/user-attachments/assets/c2ddcc2d-35f8-43c6-aed3-1a4c9c712f71)
![Image](https://github.com/user-attachments/assets/c431f14b-224a-42e3-b803-8f942c1b7909)

## What I expected to happen
Modal text to not overflow

## Reproducing

- Version: current
- Device (e.g.iPhone, Macbook) All
- Browser (e.g. Chrome, Safari) All

Steps to reproduce:
1. Go to [va-modal](https://design.va.gov/components/modal/) in Storybook
2. Replace any word in the modal with an extra long word

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

## Details
This can be fixed with CSS.

**Comment by caw310** [comment]
@ToddWebDev Is this a new issue? @Mottie just implemented a fix. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2492

**Comment by ToddWebDev** [comment]
I think this is a separate issue. I can replicate the overflow issue with a long word on Storybook. It can be fixed with
`word-break: break-word;` or similar css.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3355?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rsmithadhoc

**Comment by ToddWebDev** [comment]
Just an implementation note that the word break should only apply to the modal header and modal body content. We do not want the words to break in the modal footer buttons. Since the buttons are flexbox children, it could lead to some awkward word breaking. Thank you.
