### ISSUE TITLE
Investigate and update use of chevrons in buttons 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#336]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name
There should be documentation on whether a primary buttons needs chevrons or not

## What is the nature of this update?
Primary CTA buttons across VA.gov are inconsistent whether they have a chevron or not including:

How to file a VA disability claim | https://staging.va.gov/disability/how-to-file-claim/
File for disability compensation | https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
Order hearing aid supplies | https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories/
Apply for health care benefits (blue) |  https://staging.va.gov/health-care/apply/application/introduction
View, schedule, or cancel a VA appointment online | https://staging.va.gov/health-care/schedule-view-va-appointments/
How to apply for the GI Bill and related benefits | https://staging.va.gov/education/how-to-apply/

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

![image](https://user-images.githubusercontent.com/18386248/98724133-46b50380-2361-11eb-9ea9-44128de2d2c9.png)

![image](https://user-images.githubusercontent.com/18386248/98724147-4c124e00-2361-11eb-911c-b93ed0551b8f.png)

**Comment by caw310** [comment]
Documentation needs to be updated
