### ISSUE TITLE
Update documentation to Wizards pattern

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#340]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

[192](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/192) exists, but I don't believe this is quite the same thing.

## This update is for:
- [x] Pattern

## What is the name

[Wizard pattern](https://design.va.gov/patterns/wizards)

## What is the nature of this update?

- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [ ] When to use something else
- [x] Usability guidance
- [ ] Accessibility
- [x] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

A cohort of VSP/Public Websites (John H, Mikki N, Peggy G, and myself) have been working on migrating form wizards from content pages to the `/introduction` pages of forms. We propose the design system documentation for this pattern reflects some of the recommendations Mikki has outlined in her [IA Recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md#userpage-flows-) document. 

In particular, from the Wizard Functionality section (not putting directly here in case updates are made to that doc and things get out of sync):
- Item 2, Shared Wizards
- Item 4, Abandon application 
- Item 5, Resume application

We're also recommending everything in the "Design features/options of the wizard" section be considered. Further elaboration on the last bullet from that section:

- Recommend that the wizard outcome should inform users where they're being routed by following the design pattern established in [this mock up](https://preview.uxpin.com/ca08f3dbf63475b2b62f3e8c00050ad1b19c4cb5#/pages/133049118/documentation/sitemap?mode=i), including a clear CTA to guide users. For a11y the CTA should be explict about where the user is going (Apply with Form 123, instead of Apply Now). This pattern tested well with users on a desktop prototype, [see research folder for details](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/how-to-apply-wizards/discovery/research). )
- When the wizard can't route a user, offer a "soft next step" following the design pattern established in [this mock-up](https://preview.uxpin.com/ca08f3dbf63475b2b62f3e8c00050ad1b19c4cb5#/pages/133084046/documentation/sitemap?mode=i)

Additionally, we recommend advising teams that on the `/introduction` pages, the browser back button should take users back to the wizard they saw immediately before going to the `/introduction` page.  Depending on how the user is routed by the wizard, sometimes the URL won't change, so this needs to be dealt w/ explicitly in our SPAs.

There are 2 features we tested (a "skip" and "go back" feature) that yielded inconclusive results, so we'll submit a request to have those considered at a later time, once they're tested in an unmoderated, mobile study.

**Comment by humancompanion-usds** [comment]
@andaleliz - Given that we've deprecated this pattern, is this issue still relevant? Are these more general form handling improvements you'd like to see that just need to be renamed? Seems like this issue is more generically about check suitability (i.e. is this the right form and if not, route me to the right form). What is the current best practice example I can look at?

**Comment by andaleliz** [comment]
Hi @humancompanion-usds - this issue is no longer relevant since that pattern has been deprecated (thank goodness!). I'll close it out.
