### ISSUE TITLE
Put restrictions around alert color usage

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#341]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [x] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

**Comment by allison0034** [comment]
We have designers using colors like warning and error for things other than warnings or errors. Since we have established those colors and created a pattern using them, it would be best to put some rules around using them. Eg. #fff1d2 should only be used for warning messages.

**Comment by humancompanion-usds** [comment]
We have standardized Alerts and design tokens now. Closing.
