### ISSUE TITLE
Update va-breadcrumb in development template

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/vets-design-system-documentation#3417]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

From a [support request](https://dsva.slack.com/archives/CBU0KDSB1/p1729525967436729):

> There was recently a change to breadcrumbs.html in content-build which author Andrew Steele brought to the attention of affected apps on vets-website. Our team made the recommended fix of changing a query selector from '.va-nav-breadcrumbs' to 'va-breadcrumbs'. However, when running vets-website locally, it uses dev-template.ejs to format breadcrumbs instead of content-build. It looks like this dev-template.ejs file will need to be updated to match the changes to breadcrumbs.html in content-build. Can we request this change be made? Thank you!

>[Link to change to content-build](https://github.com/department-of-veterans-affairs/content-build/pull/2254)
>[Link to dev-template file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/landing-pages/dev-template.ejs)

## What I expected to happen

va-breadcrumb updated in the dev template

## Reproducing

- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Run vets-website with pages using dev-template.ejs

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

Engineers: 
## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 3
@ataker - 
@harshil1793 -  
@it-harrison - 3
@jamigibbs -
@micahchiang - 3
@powellkerry -
@rmessina1010 -
@rsmithadhoc -

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3417?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc
