### ISSUE TITLE
Alert  component text alignment in wide settings

### ISSUE THREAD

**Issue by jrfbz** [department-of-veterans-affairs/vets-design-system-documentation#3419]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Beyond a width of 1056px, the alert text box starts drifting right. @babsdenney has mentioned that the USWDS components do not do this and it is a bug. Happens in all alert severities, slim and normal, as far as I can tell.

![Image](https://github.com/user-attachments/assets/3b766466-6f7d-47e0-9634-30264a11f846)

## What I expected to happen

For the text within the alert to stay left-aligned in the container.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [x] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

I did not check whether the alert in production does this, I am only commenting on the Figma component.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3419?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by harshil1793** [comment]
This issue has been fixed in [Alert Storybook](https://design.va.gov/storybook/?path=/story/uswds-va-alert--slim). @jamigibbs , would you mind taking a second look before I close it?

**Comment by jamigibbs** [comment]
@harshil1793 Sure. What testing have you done already to verify that it's resolved now?

**Comment by harshil1793** [comment]
I believe https://github.com/uswds/uswds/pull/5636 could have resolved the left alignment for the alerts.
