### ISSUE TITLE
Create Signature component

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/vets-design-system-documentation#344]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

No

## Do you have a suggestion for a new component or utility?
Component suggestion: official signature / attestation pattern for forms system. Currently being used on the 1010, and we are duplicating their design on the Financial Status Report form (5655).

Explicit attestations seem relatively common in VA forms, so establishing a standard for this would help with consistency going forward.

**Comment by rebeccawalsh** [comment]
Images not appearing in original request :(
10-10CG:
![image](https://user-images.githubusercontent.com/6361930/99850946-429c9900-2b4c-11eb-94d2-31f09fc1c1a2.png)


5655:
![image](https://user-images.githubusercontent.com/6361930/99850894-30baf600-2b4c-11eb-8769-b0c18cab4325.png)

**Comment by CrystabelReiter** [comment]
Final decision from Design System council meeting on 12/4/20:
We've decided that this would be a helpful component to add to the forms system. This will be added to the design system team backlog
@rebeccawalsh One piece of feedback from the council - We recommend to not hide the component under the accordion but to have it be separate like in the caregiver example. We'll note this in future documentation

**Comment by rebeccawalsh** [comment]
@CrystabelReiter Cool! Good golly, I didn't even realize it wasn't nested in the Caregiver example. Thanks! I thought I had copied it :P

**Comment by CrystabelReiter** [comment]
@caw310 Can we add this to the design system team backlog?

**Comment by caw310** [comment]
Will do.

**Comment by CrystabelReiter** [comment]
Update before my departure: 

Templates are in sketch for teams:
https://www.sketch.com/s/89d435c3-75e4-42c3-ad53-dc364c78b3fd

Documentation draft:
https://design.va.gov/patterns/form-templates-update

When development and staging review are done:

- [ ] Update any templates and documentation with accessibility, design, content feedback

- [ ] Add templates to the sketch library - update symbols to use the ones from the library

- [ ] Delete current form templates page. Update title on the update page from form-templates-update to form-templates. Publish draft

- [ ] Announce to teams

**Comment by ndsprinkle** [comment]
@humancompanion-usds We have

Attestation: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/Attestation.jsx

which consumes FormSignature: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/FormSignature.jsx

so it is in the forms libary and is re-usable, but it didn't line up with the mockups for our form (26-4555), so I had to do an in house solution. 

Also, from what I can tell, nothing uses either of these components. Because of that, we could safely update these components to be in-line with the design system without messing up any existing forms.

**Comment by humancompanion-usds** [comment]
As we discussed today I'd like our team to contribute the signature component that is documented in the Design System as a web-component which we'll then bring into the Forms library.

**Comment by humancompanion-usds** [comment]
This is superseded by issues #1886 and #2092
