### ISSUE TITLE
Document VA.gov design principles

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/vets-design-system-documentation#345]
# VA.gov design principles

VA.gov design principles are fundamental pieces of guidance that help designers make their applications consistent with DEPO’s standards of quality in the user experience. Designers should apply them when they conceive, design, critique, iterate upon, and launch the user interface and user flow of applications on VA.gov.

## Usable by everyone

- **Accessibility First, which is more than 508 compliance.** People with disabilities do not have fewer needs than anyone else. Everyone should be able to use any tool or application regardless of features or complexity. 
- **Mobile First because it surfaces the most important tasks and information in the most constrained context.** By considering a smaller form factor before a larger one, it helps you prioritize the information and choices most critical to the user.
- **Don’t give Veterans options that aren’t actionable.** Avoid dead ends by providing relevant next steps a Veteran can take by leveraging user data and available services.

## Simple

- **Focus users on the primary task, free of distractions.** Break complex tasks into small logically ordered steps. Provide context, explain impacts, and use VA sources to reduce data entry where possible.
- **Solve for clarity and consistency first, solve for polish second.** Understand the user problem with user flows, sketches, and wireframes before developing high fidelity solutions. Share that work for critique and improvements by looking across the larger ecosystem of VA.gov before getting to the details.

## Veteran first

- **Design with Veterans, not for Veterans.** Testing all digital tools and applications with Veterans and their caregivers reduces the risk of personal bias or assumptions resulting in a bad experience. Be sure to include Veterans who use assistive devices in your usability testing.
- **Respect Veterans’ time by using research to validate your best conceptual approach.** Rather than having Veterans spend time helping you resolve granular design decisions, focus your research on the primary user problem or need. 
- **A Veterans’ journey is fundamentally unique, and not limited to VA.gov.** The digital experience is a part of a larger, end-to-end service experience that should connect a Veteran to all the people, places, and services that helps them access benefits. Because of this unique nature, what works in other industries may not always apply at VA. Consider restorative design wherever possible. How might the digital tools we design make small steps toward restoring the Veteran's relationship to the VA?

## Integrated

- **The VA.gov customer experience should be consistent across tools, applications, and devices.** A Veteran should be able to access the same content and user experience regardless of how they engage with their data.
- **Use existing collaboration processes and channels to see your work in a larger context.** Some of what you’re designing may have been designed before, while some of what you are designing might be entirely new and necessary. Collaborate with the DEPO platform to ensure that you have visibility to spend your best effort on the things that VA.gov needs the most.

**Comment by mpeterz** [comment]
This is phenomenal, @rtwell ! Thanks so much. A few suggestions: 

* Under “Usable by everyone”:
In the 3rd bullet, what are “available services”? (Analytics and Insights team?) This seems like a great place to say you should leverage user research to ensure that options are actionable — and the options are the tasks Veterans want to do. 

* Under “Veteran first”:
Since some Veterans have a caregiver or delegate, it would be good to mention designing with people acting on behalf of Veterans in this section.

* Under “Integrated”:
It's important to make sure that when you design something you consider related things and work within the larger ecosystem. You describe this brilliantly under “Simple,” but I think there’s more to it. For example, as we work on secure messaging for the new native app, we are figuring out how secure messaging relates to  My HealtheVet and Cerner secure messaging. 

You're right that "Integrated" is tricky. Some words that come to mind: 
consolidate, merge, bring together
unify, harmonize, blend
incorporate, connect, join

**Comment by CrystabelReiter** [comment]
Final decision for design system council meeting on 12/4/20:
Finalize principles and soft launch with designers 

Some action items:
Have people add feedback and mark anything on the ticket 
Kevin, Martha, Kevin will decide on final language
Make sure to add in onboarding materials, collab cycle, newsletter, design.va.gov, design weekly

**Comment by rtwell** [comment]
@mpeterz ty for the thoughtful feedback. I added a blurb about caregivers to the Veteran first section. As far as the other two points:

> Under “Usable by everyone”:
> In the 3rd bullet, what are “available services”? (Analytics and Insights team?) This seems like a great place to say you should leverage user research to ensure that options are actionable — and the options are the tasks Veterans want to do.

What I'm driving at here is we should leverage tools and databases which might be relevant to users in the appropriate  context, e.g. using the facility locator API when we know your home address and we're displaying a list of locations. I'm open to suggestions as to how to make that clearer in the bullet. 

> Under “Integrated”:
> It's important to make sure that when you design something you consider related things and work within the larger ecosystem. You describe this brilliantly under “Simple,” but I think there’s more to it. For example, as we work on secure messaging for the new native app, we are figuring out how secure messaging relates to My HealtheVet and Cerner secure messaging.

IMO the spirit of this is captured with the two bullets under the **integrated** section, but I am open to a third bullet that really hammers this idea home—if you'd like to take a pass at it, I'm all ears.

**Comment by humancompanion-usds** [comment]
This was done years ago: https://design.va.gov/about/principles
