### ISSUE TITLE
Update best practices for bolding content for "key:value" 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#346]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [x] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

https://design.va.gov/content-style-guide/bold-text

## What is the nature of this update?
There are inconsistencies across the platform around what is bolded: the key or the value
Example:
Current rating: **10%** 
or
**Last opened:** January 16, 2020

Peggy informed us that we generally bold punctuation with shorter labels (ie. Date:, Note:), but don't bold with longer headers.

(invite a content specialist to this design system council discussion -- Randi will be responsible in updating the content style guide)

## Additional Context

![image](https://user-images.githubusercontent.com/18386248/100108112-702d5f00-2e38-11eb-9b9d-888bd8c17622.png)

![image](https://user-images.githubusercontent.com/18386248/100108137-77ed0380-2e38-11eb-8249-80303dc321b5.png)

![image](https://user-images.githubusercontent.com/18386248/100108159-7d4a4e00-2e38-11eb-86d4-7298445aaf8d.png)

![image](https://user-images.githubusercontent.com/18386248/100108188-82a79880-2e38-11eb-84a9-3412ff4df7eb.png)

**Comment by CrystabelReiter** [comment]
Final decision from Design System council meeting on 12/4/20: 
We recommend bolded key and not bolded value stacked vertically without a colon. 
@RLHecht Please update content documentation on design.va.gov. Thank you!

**Comment by RLHecht** [comment]
@CrystabelReiter I'm trying to add an example of the correct styling in the entry I'm writing for the style guide so I can link to it. So far, I can only find it the wrong way on the few unauthenticated pages I've looked at so far. For example: https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction Do you have a suggestion of where I can find a correct one where the user wouldn't need to log in to see it?

**Comment by humancompanion-usds** [comment]
@megzehn and @laurwill - I found this deep in our backlog but, it remains, to my knowledge, unsolved. Can you have a look and perhaps queue this up for an update to the Content Style Guide? Thanks!

**Comment by megzehn** [comment]
Thanks for sharing this, @humancompanion-usds!

It looks like we did add something to the [bold section of the style guide](https://design.va.gov/content-style-guide/bold-text) (in the last bullet list). I'll paste it here for reference.

> If you’re presenting a series of label and value pairs, such as the contact information (address, phone number, etc.) for a location. The label is always bold, not the value, and the label and value are separated by a line break as opposed to a colon. [Review examples on the H. John Heinz III Department of VA Medical Center page](https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/#caregiver-support)

I'm thinking we probably want to clarify the part about when to use a colon vs line break. I'll look for other examples and bring this up with Danielle and Beth. But in the meantime, I think it's OK to close this ticket from my perspective.
