### ISSUE TITLE
Revise gender identity question in ask users for gender pattern

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#3477]
# Bug Report

* [ ] Change the question from "How would you describe your gender?" to "How would you describe your gender identity?"
* [ ] The options should be checkboxes as this is a multi-select rather than a single answer.
* [ ] Change the name of the pattern from Ask users for gender to Ask users for gender identity

Please update Figma and then the screenshots in guidance. Apologies, this is my fault. I didn't catch the change to the question and neither Nancy nor I initially caught that this was supposed to be multi-select.

## What happened

Miscommunication between Matt and Nancy on the change to the question (mainly my failing to read carefully)

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

This is a minor word change but makes a big difference. I apologize for missing it earlier.

Once we update this please assign to me so I can make a guidance update. These are the points I need to mention:

> OMB does not specify that birth sex must be asked when gender identity is asked, so only asking for gender identity is an option. 
> OMB requires asking for gender identity when asking for birth sex. This does not mean we merge the birth sex/gender identity question/responses -- the two are not equivalent.
> VA has no approved standard for birth sex. If necessary, the question could be something like “What was your sex assigned at birth?” and responses limited to male or female. These choices align to the MPI architecture and MPI is the ADS for birth sex.

More generally:

> OMB PRA approval does not mean that the content conforms to VA standards. If a form was approved by OMB but it needs to be corrected, we should fix the form.
> It’s irrelevant if any form adds “for statistical purposes only” to a field because that intent does not travel with the collected data as it moves throughout our systems. Most demographics, and birth sex in particular, do not limit use to “statistical purposes,” so we’re misrepresenting information to the form submitter.

## Estimating
Designers: 
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@babsdenney
@danbrady
@LWWright7

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3477?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by babsdenney** [comment]
@danbrady @LWWright7 This is ready for review. 

- [Figma pattern - Gender Identity](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=4808-19469)
- [Doc site branch](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3526)
