### ISSUE TITLE
Update a11y considerations guidance for tables to discourage use of tables for non-data

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#3505]
### Duplicate check

- [x] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

va-table

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [x] Accessibility considerations
- [ ] Content considerations
- [ ] Implementation
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

We had a Design Intent with a team who switched from a Card to a Table display for non-data and @artsymartha68 and I had to push back on them to explore other designs. Currently in Table guidance we just point to the USWDS a11y guidance. It says nothing about us not wanting teams to use tables for non-data displays/layout. We need to add our own guidance pushing teams away from this option as it is not easy for screen reader users to navigate tables for display purposes. We could offer up alternatives in the guidance (using more data-sense Card displays, offering filtering and the ability to compare Cards, etc.)

### Additional Context

I want to do this now because in the adding of new Table variations to our v3 component, some teams are taking that as a signal that we want them to use tables when we really don't unless they are displaying data.

**Comment by rsmithadhoc** [comment]
PR opened here https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3619
