### ISSUE TITLE
Simplify content of in progress alert box

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#351]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: In progress alert box

## Do you have a suggestion for a new component or utility?
The current your application is in progress alert box is verbose, repetitive, and does not take advantage of gestalt principles to connect itself to the call to action of signing in.

To address this, I suggest the following:
- Wrapping important information within a heading appropriate to the level of the page (in this case it would be a h2 styled as a h3). This will make the alert more discoverable to screen reader users.
- Reduce repetition/rhythm of "your application..." that may cause users to ignore the alert completely.
- Make use of basic gestalt principles by including the call to actions within the alert box itself.

### Before
<img width="724" alt="Screen Shot 2020-12-03 at 12 19 58 PM" src="https://user-images.githubusercontent.com/14154792/101064332-dfeec880-3561-11eb-8f3d-deedfe95438e.png">

### After
![image](https://user-images.githubusercontent.com/14154792/101064375-eda44e00-3561-11eb-90f9-037e92b2763c.png)

**Comment by joshkimux** [comment]
@peggygannon I've transferred this to a ticket for the design system team! Feel free to edit/make suggestions 😄

**Comment by joshkimux** [comment]
Update: the suggested design will likely not perform well on mobile given the length of the heading. Would be great to see alternatives put together that strip out the repetitive content.

**Comment by caw310** [comment]
Feedback from DSC meeting on 7/23

- Add this to DST backlog
1. DST designer to document. 
2. DST engineer to make this part of the form system.  Or the next team who develops a form could build it and pull it in. 

@joshkimux - we agree but if you know front end team, please work with them to get it done. 
Robin - may have time to take a look at this.

**Comment by Mottie** [comment]
This work has been completed, merged in and available on staging.

**Comment by joshkimux** [comment]
Thank you @Mottie !!
