### ISSUE TITLE
File type bug in File Input Component

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/vets-design-system-documentation#3592]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I attempted to upload a `.pdf` file to the va-file-input component and it gave me a `This is not a valid file type.` error.
![Image](https://github.com/user-attachments/assets/02e641c3-7497-4336-95ab-d587e37f19f4)

From my digging into the code, I think there is an issue with the `accept` prop. I am passing in `'.pdf,.jpeg,.png'` but if I pass in `null` then the error does not appear. But I _do_ want to be able to specify allowable file types.

## What I expected to happen

There should be no error message.

## Reproducing

- Formation version:
- Device: Macbook
- Browser: Firefox

Steps to reproduce:

1. Run `yarn watch --env entry=auth,static-pages,login-page,verify,profile,form-upload-flow` locally.
2. Log in as a user.
3. Visit `http://localhost:3001/form-upload/21-0779`
4. Proceed through the form until you reach `http://localhost:3001/form-upload/21-0779/upload`
5. Attempt to upload a pdf file.
6. See error. Weep.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 5
@ataker - 3
@harshil1793 -  5
@it-harrison - 3
@jamigibbs - 5
@micahchiang - 5
@powellkerry - 3
@rmessina1010 - 5
@rsmithadhoc - 3

**Comment by Andrew565** [comment]
@Thrillberg I was not able to successfully reproduce this error locally. Can you please try again and see if it's working better for you now? Screenshot of successful upload of a pdf file:
![Image](https://github.com/user-attachments/assets/ac3b10e6-fd67-481a-baa8-e328f5c3fc5a)

**Comment by Thrillberg** [comment]
@Andrew565 Ah, my apologies! I think I resolved this in another way, so I will close this ticket now.
