### ISSUE TITLE
File retention over navigation in File Input Component

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/vets-design-system-documentation#3593]
# Bug Report

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

On my form (`http://localhost:3001/form-upload/21-0779/upload`), I'd like to be able to upload a file, navigate forward, then navigate backward, and have the component "retain" knowledge of the upload. I know that the FE component can't actually do this but is it possible to create an interface for the component whereby I can supply some parameters (size and file name) and make the FE component "pretend" to retain the file. When the user uploads, navigates away and then navigates back, it gives off the impression that the upload has been "lost" if we can't show the file in the component.

## Reproducing

Steps to reproduce:

1. Run `yarn watch --env entry=auth,static-pages,login-page,verify,profile,form-upload-flow` locally.
2. Log in as a user.
3. Visit `http://localhost:3001/form-upload/21-0779`
4. Proceed through the form until you reach `http://localhost:3001/form-upload/21-0779/upload`
5. Upload a pdf file.
6. Click Continue to navigate forward through the form
7. Click Back to navigate back through the form
8. The UI will give the impression that no file has been uploaded

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

## Estimating
Provide your estimate of 1, 2, 3, 5, 8 or 13 
@Andrew565 - 13
@ataker - 
@harshil1793 -  
@it-harrison -
@jamigibbs -
@micahchiang -
@powellkerry -
@rmessina1010 -
@rsmithadhoc -

**Comment by Thrillberg** [comment]
I think maybe this isn't a bug. Here's my PR that implements (hopefully) properly what I'm looking for: https://github.com/department-of-veterans-affairs/vets-website/pull/33434

**Comment by Andrew565** [comment]
The associated PR has already been merged, closing this ticket as completed.
