### ISSUE TITLE
Feature request: masking the social security number component

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#361]
# Feature Request

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Social Security Number form input
- Prior art: https://github.com/department-of-veterans-affairs/vets-website/pull/15265

## Do you have a suggestion for a new component or utility?
Several forms ask for social security numbers, and have a high likelihood of being filled out in public spaces. Recently I worked on a project that requested the social security number input be masked when users were not entering data and the input had a value that was not an empty string. This tested very well for accessibility in our preliminary screen reader tests, and could be tested further in live user research.

## Additional context
![Screen Shot 2020-12-15 at 2 35 30 PM](https://user-images.githubusercontent.com/934879/102277852-7a4df500-3eee-11eb-9d76-95b909c74ae2.png)

---
![Screen Shot 2020-12-15 at 2 35 34 PM](https://user-images.githubusercontent.com/934879/102277868-7f12a900-3eee-11eb-9cec-df3a1050498b.png)

**Comment by caw310** [comment]
Discussed during the DC 12/18 meeting. Follow up and action items: 

- Put in DS backlog to add this pattern
- Create the focus masked option (would be good for several fields) 
- Identify right places to incorporate this into the form system - set field as masked. 
- Identify technical LOE for this @cvalarida & @bkjohnson

**Comment by k80bowman** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16360) submitted
