### ISSUE TITLE
Change pagination "Previous" to "Prev" in Sketch file

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#362]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

In Sketch the pagination has the word "Previous" but in prod and design.va.gov it is "Prev" 
<img width="346" alt="Screen Shot 2020-12-18 at 4 00 43 PM" src="https://user-images.githubusercontent.com/72398073/102661165-4ff87380-414a-11eb-935c-4fa223974b81.png">

## What I expected to happen

I expected Sketch to match prod and design.va.gov

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Visit https://design.va.gov/components/pagination
2. Open Sketch file and look at Styles

**Comment by CrystabelReiter** [comment]
This will get updated in the next sketch update

**Comment by GnatalieH** [comment]
The Sketch library contains the correct version of "Prev", so I'm closing this ticket:

![Screen Shot 2022-06-23 at 10 36 13 AM](https://user-images.githubusercontent.com/88347129/175338532-496af8e6-2a8c-4d6f-8862-07c52fd75353.png)
