### ISSUE TITLE
Add borderless table to design.va.gov

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#363]
# Feature Request

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Borderless table. It currently exists in the Sketch file on Styles. It does not exist on design.va.gov. I would like to get it added with code if possible.
-

**Comment by caw310** [comment]
@allison0034 , the DSC reviewed this request on 2/12. Decision was to add this to DST backlog as low priority item. I'm moving this to reviewed on the DSC project and have put this in the Reviewed/Needs prioritizing column in the DST team zenboard.

**Comment by caw310** [comment]
@allison0034 , is this still needed?

**Comment by allison0034** [comment]
I am not sure, I do not see it in Sketch anymore. @GnatalieH is there a borderless table in Sketch that you know of?

**Comment by GnatalieH** [comment]
@allison0034 I thought it was, but it's not. So we need it.

**Comment by allison0034** [comment]
@GnatalieH there used to be a borderless table in the Sketch file, however I think it was removed.

@k80bowman I honestly do not remember exactly what it looked like. Since it is no longer there and there is an almost borderless version on the [Table component page](https://design.va.gov/components/table), I think we can close this ticket. If designers have another need we can address it.

**Comment by k80bowman** [comment]
Thank you @allison0034! I'll close this for now, but let us know if the need for a different type of table arises again.
