### ISSUE TITLE
Feature Request - Typeahead component

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#364]
# Feature Request

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.
No, this would be a new component for our design system

- Component/utility name: Typeahead auto-suggest

## Do you have a suggestion for a new component or utility?
The VSA Search and Discovery team built a custom component using the [Downshift library](https://github.com/downshift-js/downshift) for a global autocomplete. We would like to propose having a generic typeahead that could be used with dynamic data sources, and be the one true source of truth for cases where we want to suggest known options as users type.

## Additional context
* https://github.com/department-of-veterans-affairs/vets-website/pull/15415

**Comment by humancompanion-usds** [comment]
Type ahead functionality is documented now in https://design.va.gov/components/search-input
