### ISSUE TITLE
Add headers inside accordion component 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#368]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

There is a ticket to audit the accordion - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/210 - it does mention "accordion headers", but the content of the accordion isn't actually an `h1` through `h6` header.

This feature request is based on this accessibility audit - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17846

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name:
Accordion (https://design.va.gov/components/accordions)

## Do you have a suggestion for a new component or utility?

Currently the HTML in the design docs include a `button` directly inside the list item (`li`), but the React component wraps the button with a `div`

```html
<ul class="usa-unstyled-list">
  <li>
    <div class="accordion-header">
      <button class="usa-button-unstyled">
        Accordion Header Text
      </button>
    </div>
    <div>
      Accordion content
    </div>
  </li>
</ul>
```

Changing the wrapping `div` into an `h4` or adding an `h4` inside the button looks okay, but the former method adds a margin. Both cases change the font.

![Screen Shot 2021-01-06 at 4 09 07 PM](https://user-images.githubusercontent.com/136959/103824535-bf6ece00-5039-11eb-9e12-105b58f34f37.png)

## Additional context

Outside of the form system, we'll probably want to include different level headers (e.g. inside form 526's information page subway map), so we'd also need to maintain a consistent header size while allowing various header levels

**Comment by Rekiahhinton** [comment]
Hello! I am a brand new contributor who is currently learning HTML and CSS
I want to contribute to your project and help you solve your issue but I do not have any prior experience
Do you think working together would be possible?

**Comment by Mottie** [comment]
Hi @Rekiahhinton!

We've got a really tight schedule and not much free time for teaching the fundamentals. Might I suggest you try going through the content at [FreeCodeCamp](https://www.freecodecamp.org/)?

**Comment by Rekiahhinton** [comment]
Hi,
Thanks for responding. I'm currently working through the fundamentals at
Freecodecamp.org. Which coding language would one need to know to work on
this project?

-Rekiah Hinton
