### ISSUE TITLE
Add aria-describedby as a prop to the Table Component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#378]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Table Component

## Do you have a suggestion for a new component or utility?

Suggestion: add an optional prop to support `aria-describedby` on the table component. 

## Additional context

Existing a11y issue flagged by @joshkimux - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17149

### Summary
It's a somewhat common pattern for tables to contain paginated data, and display to users the range of data points they are currently viewing. (i.e. `Displaying 4 - 9 of 1,300,390`). As @joshkimux mentions in his original ticket above,  providing the option to add an `aria-describedby` to the table component allows that valuable information to be communicated to screen reader users through something like this:
```
<p id="unique-id" aria-live="polite" class="vads-u-font-size--lg vads-u-font-family--serif">
     Displaying 55 - 60 of 67 payments.
</p>

<table 
  aria-labelledby="paymentsRecievedHeader" 
  aria-describedby="unique-id paymentsRecievedContent" 
  ...
/>
```

**Comment by caw310** [comment]
@bkjohnson , can you check that this has been addressed? If so, then please close this ticket.

**Comment by bkjohnson** [comment]
The `aria-describedby` attribute can be set directly on `<va-table>` which has `role="table"`. This should allow the table component to be described by any element outside of itself without any dev work on our end.
