### ISSUE TITLE
Feature Request - Tabs component

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/vets-design-system-documentation#379]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: VAOS has tabs implemented and Health questionnaires plans to implement them as well, but they aren’t part of the design system yet.

## Do you have a suggestion for a new component or utility?
  Tabs are a navigation element that allows users to easily access different areas of a site or different part of an individual page. When considering tabs for the overall design system, the following accessibility issue should be addressed (information provided by Josh Kim). 

[Tabs vs. Links article by Adam Silver](https://adamsilver.io/articles/avoiding-tab-styles-for-navigation/) main points being:
- Styling links as tabs is deceptive – when a link is clicked, the content is shown after a page refresh with the focus moving back to the top of the viewport.
- Keyboard users may expect to be able to use the left and right arrow keys in order to switch tabs. This wouldn’t be expected with a list of links.
- And (sighted) screen reader users may expect certain functionality, like using a shortcut to move focus to the associated tab panel or announcing which tab is selected.

  Tabs are currently implemented on va.gov within the VAOS product to toggle between upcoming and past appointments. (https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/)  

Health questionnaires also plan to utilize these same tabs (visual styling, etc.) to allow users to toggle between To do and Completed questionnaires. (https://staging.va.gov/health-care/health-questionnaires/questionnaires/) 

## Additional context
Screenshot of tabs within VAOS
![Screen Shot 2021-01-13 at 6 00 43 PM](https://user-images.githubusercontent.com/66287082/105729592-689f3a80-5efb-11eb-9c69-0b7ddf17b84c.png)

Screenshot of tabs within Health questionnaires
![Screen Shot 2021-01-13 at 6 02 39 PM](https://user-images.githubusercontent.com/66287082/105729640-72c13900-5efb-11eb-82be-f3e539321279.png)

**Comment by caw310** [comment]
@GnatalieH , please breakdown the design tasks then share with @k80bowman who will breakdown development tasks for this new component.

**Comment by bkjohnson** [comment]
I think we do have tabs as part of the design system, they are just underused/underdocumented. This highlights the need for better documentation on what's available.

- [`formation` SASS file](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/4c3efba46d4a745462c6435dcf32fd03104a3114/packages/formation/sass/modules/_va-tabs.scss#L3)
- [SASS import in `claims-status`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/sass/claims-status.scss#L6)
- [Example of them in use](https://github.com/department-of-veterans-affairs/vets-website/blob/394ccc716ab2fc2e1e55a507c5a7d8c213bf30a2/src/applications/claims-status/components/TabNav.jsx#L8)

**Comment by GnatalieH** [comment]
@bkjohnson are they on Storybook and is what we have considered a web component? Thx.

**Comment by bkjohnson** [comment]
They aren't on storybook, and we don't have a web component for tabs.

**Comment by GnatalieH** [comment]
> @GnatalieH , please breakdown the design tasks then share with @k80bowman who will breakdown development tasks for this new component.

I've created #611 to address the documentation of Tabs when a web component has been built.
