### ISSUE TITLE
Documentation request: Width suggestions for cards

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/vets-design-system-documentation#380]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [X] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

This request is for additional documentation on suggested widths of cards.

## What is the nature of this update?

Please review the attached Slack thread to understand what was missing from documentation that resulted in clarification being needed related to widths of cards (consider responsive breakpoint documentation affecting the width too). https://dsva.slack.com/archives/C0NGDDXME/p1607450074385000

- [X] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

**Comment by caw310** [comment]
Being worked on as part of card pattern work.

**Comment by caw310** [comment]
Closing since it will be done with cards.
