### ISSUE TITLE
Feature Request - Privacy Act Statement variation and customization  # Feature Request

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/vets-design-system-documentation#381]
# Feature Request 

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Two changes are proposed for the Privacy Act Statement modal, in order to address current use cases.
![Screen Shot 2021-01-19 at 1 37 29 PM](https://user-images.githubusercontent.com/66287082/105730773-b6687280-5efc-11eb-8938-693ff119ee56.png)

## Do you have a suggestion for a new component or utility?
1. The first line of the respondent burden paragraph within the privacy act statement always states the feature is for “education benefits,” even when the feature is something else like the caregiver or health questionnaire forms. This can be seen on almost every form implemented on va.gov. This wording needs to be customizable so it can list the actual name of the feature.
![Education benefits](https://user-images.githubusercontent.com/66287082/105730808-c2543480-5efc-11eb-8201-4c1a9d5e73f9.png)

2. Health questionnaires will not have a respondent burden or OMB control number. Therefore, the entire respondent burden section of the privacy act statement does not apply. The health questionnaires team discussed keeping our own version of the privacy act statement minus the respondent burden in our code. However, we wouldn’t know when and if any updates occur to the privacy act notice section. Therefore, we wanted to know if the respondent burden paragraph could be made optional at the platform level? 
![Respondent Burden](https://user-images.githubusercontent.com/66287082/105730838-ca13d900-5efc-11eb-9515-d29f694bf617.png)

**Comment by caw310** [comment]
This will be addressed in this ticket. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/572

**Comment by kristenmcconnell** [comment]
Since I entered this ticket, the Forms Library Platform Spike Team has spun up. Would this be something that they should be aware of, since the request involves changes to code on a Forms Library component?

**Comment by caw310** [comment]
@kristenmcconnell , yes. I can share this with the forms library team.

**Comment by kristenmcconnell** [comment]
Thank you.

**Comment by k80bowman** [comment]
I broke the work for this request up into two tickets:
- https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/34524
- https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/34523
