### ISSUE TITLE
Create guidelines on using Gray boxes versus the hairline "column" sections

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#385]
## Issue Description
Create guidelines on using Gray boxes versus the hairline "column" sections

---
## Tasks
- [ ] Audit of current use
- [ ] Update Sketch file
- [ ] Document
- [ ] Add to design.va.gov

## Acceptance Criteria
- [ ] Updates Sketch file
- [ ] Accessible on design.va.gov
---

**Comment by caw310** [comment]
@allison0034 , if you have time to work on this when things are slow because folks are OoO, that would be great. Even just working on an audit would be helpful. Thanks!

**Comment by allison0034** [comment]
@caw310 are you referring to cards? The only gray boxes I know of are cards. And do you have an example of hairline columns?

**Comment by caw310** [comment]
@allison0034 , I dont have an example.

**Comment by GnatalieH** [comment]
@rtwell do you remember what this ticket is addressing? Specifically, what are hairline column sections (mentioned in title)? I think we could better deduce what the gray boxes are in this context if we understand hairline column sections. I've reviewed Chrystabel's handoff docs and can't find anything that talks about this stuff. Thanks.

**Comment by rtwell** [comment]
i'm guessing "columns" is confusing—this might be referring to designs like MyVA or the VAMC product that have horizontal rules. @GnatalieH this may have some overlap with the card work. 

some examples:

- search area in [resources and support](https://www.va.gov/resources/)
- [VAMC pages](https://www.va.gov/pittsburgh-health-care/)
- Facility locator [search results](https://www.va.gov/find-locations/?page=1&address=20002&facilityType=health&serviceType&latitude=38.89&longitude=-77.01&radius=10&bounds%5B%5D=-77.76&bounds%5B%5D=38.14&bounds%5B%5D=-76.26&bounds%5B%5D=39.64&context=Washington%2C%20District%20of%20Columbia%2020002%2C%20United%20States)
- [MyVA](https://staging.va.gov/) (you will need a test account to access) 
- the [tags on resources and support pages](https://www.va.gov/resources/signing-in-to-vagov/)
