### ISSUE TITLE
Add style guide / pattern for Blue status highlights  to DS

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#388]
## Issue Description
Add style guide / pattern fo Blue status highlights to DS

---
## Tasks
- [ ] Audit of current use
- [ ] Update Sketch file
- [ ] Document
- [ ] Add to design.va.gov

## Acceptance Criteria
- [ ] Updates Sketch file
- [ ] Accessible on design.va.gov
---

**Comment by caw310** [comment]
@GnatalieH , let's break this down further once you've identified what this entails.

**Comment by GnatalieH** [comment]
@caw310 this work is cards-related and will be handled in #[572](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/572). Can I close it?

**Comment by caw310** [comment]
@GnatalieH sure, can close this and just link this to 572.

**Comment by GnatalieH** [comment]
Closing as duplicate of #572.
