### ISSUE TITLE
Odd cursor behavior on radio inputs

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#391]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I noticed on VAOS that, when hovering on a radio input's label, the mouse cursor only changes to a pointer at areas near the label, but often not when hovering over the label.

**Example 1**

https://user-images.githubusercontent.com/2536801/106327059-59d5c200-6232-11eb-968a-b12892d3649d.mov

**Example 2**

https://user-images.githubusercontent.com/2536801/106327120-73770980-6232-11eb-8c8c-3176cc7c6a72.mov

[See this thread for the original context.](https://dsva.slack.com/archives/C7NJWUA8K/p1611941224006700)

**Notes from Trevor**
@1Copenut dug into this and found:

> It also appears the input is covering up the spans. Try hovering all the way to the right of the label and might be have as you expect.

> The input has a width 100% and it’s layered over the label, which is what’s preventing your cursor from showing the pointer over text.

## What I expected to happen

Since the label is clickable, I expected the cursor to change to a pointer on hover.

## Reproducing
- Formation version: ?
- Device: Macbook Pro
- Browser: Chrome 88.0.4324.96

Steps to reproduce:

1. On staging in VAOS, start scheduling an appointment you can see this on any list of radio buttons, including the Type of Care selection page (https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment) or Facility Selection (https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/choose-facility-type)
2. Hover over the input label
3. Notice when the cursor changes into a pointer

**Comment by caw310** [comment]
Reviewed during DSC meeting on 2/19.
We will put this on DST backlog. Look for Trevors help when we work on this .

We will work on this in next 2-3 sprints. Not high urgency bug.

**Comment by bkjohnson** [comment]
Closed by https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/600
