### ISSUE TITLE
Tweak wording on address fields

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/vets-design-system-documentation#393]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: Gathering address information

## Do you have a suggestion for a new component or utility?
Discussed already with Crystabel who spoke with Peggy. Currently our address input boxes read "Street address, Line 2, and Line 3."  It would be nice if instead of "Line 2" they read "Street address line 2" or something to re-iterate what those lines are for, especially for folks with cognitive disabilities.

**Comment by CrystabelReiter** [comment]
- [ ] Update sketch library address component and templates
- [ ] Update documentation screenshot in form template patterns 
- [ ] Change address in forms library
