### ISSUE TITLE
Month / Day / Year inputs should show entire label and remain same width when an error class is attached

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/vets-design-system-documentation#394]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
The Month / Day / Year pattern inputs (two selects, one text input) expand in width when the error class is added. This is an inconsistent behavior from our other inputs when they're in the error state. Screenshot attached below.

## What I expected to happen
- [ ] Inputs should be wide enough to show all of the month name after [PR #15935](https://github.com/department-of-veterans-affairs/vets-website/pull/15935) is merged.
- [ ] Inputs should retain their current width when the error state is activated

---
![Screen Shot 2021-02-01 at 9 43 20 PM](https://user-images.githubusercontent.com/934879/106554454-06d56680-64e1-11eb-8b45-92eb3d996fd0.png)

---
<img width="423" alt="Screen Shot 2021-02-04 at 7 38 29 PM" src="https://user-images.githubusercontent.com/934879/106978024-09260380-6721-11eb-89bf-e123fa7f4c84.png">

**Comment by Mottie** [comment]
Oops, closing the PR auto-closed this ticket... I'll reopen it so you can verify

**Comment by k80bowman** [comment]
Closing as this is resolved in both the web component and the React component.
Web component:
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/9c90a777-7076-4078-b6f6-5e8dd5f66e36)

React component
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/8def79c1-be68-4fcc-a4c1-a1b99b753b9f)
