### ISSUE TITLE
Redesign contact information prefilled state 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#395]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name:
Contact information pattern - prefilled state

## Do you have a suggestion for a new component or utility?
2 forms (526 and VET TEC) use a prefilled state version of the contact information pattern 
![image](https://user-images.githubusercontent.com/18386248/106771198-b65b2780-660c-11eb-95bf-50ff37181a5a.png)

This state is not a part of the common form definition, we need to figure out do we want to recommend this as a pattern? Ryan T. and I had a conversation and he thinks this isn't a great pattern and should be redesigned.

**Comment by sshein** [comment]
a relevant slack thread:
- https://dsva.slack.com/archives/C0136TS768M/p1597947144002000

**Comment by sshein** [comment]
here is a related ticket I submitted at one point awhile ago to the design system council / design system https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/305

**Comment by humancompanion-usds** [comment]
This issue is superseded by issues #305, #619, and the pattern is being written up in #1109.
