### ISSUE TITLE
Create standard help text format

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/vets-design-system-documentation#396]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name:

We need a defined pattern for helper text. This came up in a design channel conversation in slack around how we should format help text when it comes to form labels. 

## Additional context

![image](https://user-images.githubusercontent.com/18386248/106776266-e78a2680-6611-11eb-892e-7bf21b0cc41a.png)

Design channel [conversation](https://dsva.slack.com/archives/C0NGDDXME/p1612298930119600)

**Comment by caw310** [comment]
Request was discussed during 2/19 DSC meeting. Follow up action items are: 

- Provide Becca’s team Aria labels if they're not doing that already. @1Copenut 
- Once this is built, DST will create documentation and add as component.

**Comment by 1Copenut** [comment]
@rebeccawalsh I found a pattern on the GOV.UK site that I'd like us to adopt for handling these helper text labels:https://design-system.service.gov.uk/components/text-input/#hint-text

Specifically for our implementation, the HTML could look like the following snippet. The `aria-describedby` attribute on the input will look for the unique ID on the helper text div. Screen readers will read the label text, short pause, then read the helper text aloud.

```html
<label for="docket-number">Case or docket number</label>
<div id="docket-more-info-1">
  <strong>Note:</strong> You'll find this number on your case documents.
</div>
<input
  aria-describedby="docket-more-info-1"
  id="docket-number"
  type="text" 
/>
```

**Comment by humancompanion-usds** [comment]
Hint text has since been documented: https://design.va.gov/components/form/#hint-text
