### ISSUE TITLE
design.va.gov broken link via React Components

### ISSUE THREAD

**Issue by boris-ning-usds** [department-of-veterans-affairs/vets-design-system-documentation#397]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
- Broken link via https://design.va.gov/ on React Component.
![image](https://user-images.githubusercontent.com/41026275/106920631-4c5c8400-66d9-11eb-8234-66d28ca1a59e.png)
![image](https://user-images.githubusercontent.com/41026275/106921279-ddcbf600-66d9-11eb-8b9d-eb1a3eb8ebfb.png)

- I believe that this URL should point to /components instead of /visual-design/ - This is probably the proper link: https://design.va.gov/components/.

## What I expected to happen
- The link should work.

## Reproducing
- All platforms

Steps to reproduce:

1. Browse to https://design.va.gov.
2. Navigate to React Components.
3. Find the broken link.

**Comment by boris-ning-usds** [comment]
This line: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/68e2e561d23a70cc920245b7508ee3a7877570d7/src/index.html#L104 should probably be changed

{{ site.baseurl }}/components/

**Comment by caw310** [comment]
@cvalarida , if you have time can you fix this?
