### ISSUE TITLE
ClientError VSP Component not Autofocusing

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/vets-design-system-documentation#409]
# Feature Request or Maybe a Bug?

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

Currently in FormBuilder there is an error message that will overwrite any custom error behavior if the reverse proxy times out. It tells the user to check their internet connect and try again. When the error pops up its way above the content on the review page and users can potentially not see the error and be confused.

In my experience with the FormBuilder from starting new apps I have noticed this auto focus on mount is generated along with the boilerplate so it feels like a bug to be me since not focusing on a mounted error seems to deviate from the pattern.

My ask is to enhance this VSP error message so users auto-focus to the error on mount to limit confusion.

- Component/utility name:

Form Builder `clientError` component

Content to this component is in this [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1614627021416200)

## Do you have a suggestion for a new component or utility?
I would suggest that the Error auto focus using the VSP auto focus usually as used in this component [here](https://github.com/department-of-veterans-affairs/vets-website/blob/LinnJS-1010cg-progresive-loading/src/applications/caregivers/components/SubmitError/index.jsx#L12) 

## Additional context

Here is the other [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1615485699012700) that lead me to create this ticket.

### Image of Error its-self

![image](https://user-images.githubusercontent.com/23741323/110974049-163f9f00-832c-11eb-9e4e-78d0458f7258.png)

**Comment by LinnJS** [comment]
One thing else to note it seems super off to me that in the code base this is referred as a `clientError` and that we are telling the user to check the network connection when it has nothing to do with the user. But actually has to do with our network failing/timing out.

Reference to this error [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/src/js/review/SubmitButtons.jsx#L41-L49) as discussed in this slack [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1614701492468100?thread_ts=1614627021.416200&cid=CBU0KDSB1) which is also referenced above.

**Comment by ala-yna** [comment]
@caw310 - could we get an estimate as to when this will make it into a sprint? This is pretty high priority for us, and shouldn't take a long time. Thanks!

**Comment by caw310** [comment]
@ala-yna , we're going to talk about this today. Hoping to get it into the sprint starting tomorrow if possible. Will let you know.

**Comment by caw310** [comment]
@ala-yna , we've added this issue to our next sprint.

**Comment by ala-yna** [comment]
Great, thank you so much!

**Comment by ala-yna** [comment]
@caw310, do you have an estimate of when we'll be able to see this?

**Comment by caw310** [comment]
@ala-yna , this is slated for this sprint. It should be worked on this week.

**Comment by k80bowman** [comment]
@ala-yna I just want to double check, is this the behavior you want?

![error-scroll](https://user-images.githubusercontent.com/12739849/112890906-744ae100-90a5-11eb-917e-6d8debbe53fc.gif)

**Comment by ala-yna** [comment]
Looks good to me! Mind confirming, @LinnJS?

**Comment by k80bowman** [comment]
PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/16578
