### ISSUE TITLE
OMBInfo displays "Expiration Date:" when the property is not provided

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/vets-design-system-documentation#421]
# Feature Request
Other properties are hidden when not provided in OMBInfo component, `expDate` is the exception. Requesting it's label is also hidden if value is not provided.  
Optionally split out the "Privacy Act Statement" into its own component for use independent of OMBInfo.

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name:
https://github.com/department-of-veterans-affairs/component-library/blob/master/src/components/OMBInfo/OMBInfo.jsx

## Additional context

![image](https://user-images.githubusercontent.com/1094999/113736754-63185a80-96cb-11eb-822e-657afbb74e44.png)

**Comment by humancompanion-usds** [comment]
@jamigibbs - It looks to me like expDate is now required on the OMB Info component. Can you confirm and close if so. 

If someone comes forward with a valid use case where the expiration date is not available then we could change that. The only thing I can think of is the exception case where we get an emergency waiver pending approval of the form. But I gotta imagine that comes with an expiration date as well. Even if it does not, we may want to set a reasonable date as a reminder to update it in future once the pending form is approved by OMB.

**Comment by bkjohnson** [comment]
It is required on both the React component and the Web Component. The red asterisk indicates that it is required:

![Screenshot of the React OMBInfo component with the `expDate` prop marked as "required"](https://user-images.githubusercontent.com/2008881/198141770-2ffb70b5-db37-4e49-8c11-517321be393c.png)

![Screenshot of the OMBInfo Web Component with the `exp-date` prop marked as "required"](https://user-images.githubusercontent.com/2008881/198142004-e6605f79-069d-470b-9eaf-7f31930f9e4b.png)
