### ISSUE TITLE
Add more content suggestions and research insights for "additional info" component

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/vets-design-system-documentation#424]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Additional info

## What is the nature of this update?

It would be nice to have general guidance about the additional infor component - namely if it's better to be phrased as a question (e.g. "Why are you asking if I'm married?" or "What does CHAMPVA mean?") versus a statement (e.g. "Learn more about Primary Family Caregivers")

Additionally, it would be good to have advice about when to use this component based on research insights. The VSA team had a discussion where Jim mentioned that his users usually skipped the component. However Becca and I have often seen users interacting with the component. We discussed how first of all, if a user really needs to know the info, it shouldn't be in an additional info component. Secondly,  try not to have these components on pages with lots of information - they work best on forms when we follow the "one question per page" guidelines, and then have a single additional info component on that page.

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [x ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

**Comment by caw310** [comment]
Discussed during the 4/9 DSC meeting. Will add this to DST backlog.

**Comment by humancompanion-usds** [comment]
Shipped! https://design.va.gov/components/additional-info

**Comment by GnatalieH** [comment]
Awesome! @humancompanion-usds can I announce this update on #design? Or would you like to? It's a big deal to have this component's documentation shipped, thanks!
