### ISSUE TITLE
Rename action link class to match documented naming convention

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#426]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Description

The documentation on design.va.gov describes naming conventions for `formation` component classes:

![image](https://user-images.githubusercontent.com/2008881/114231854-d4584780-992f-11eb-87e6-08dacab3be0b.png)

However, our action link component doesn't follow this documentation:

![image](https://user-images.githubusercontent.com/2008881/114232023-1a151000-9930-11eb-84fb-37eb43822a2c.png)

## Context

- [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1617805314484100)

## Acceptance Criteria

- [ ] `formation` is updated to change the action link class name to `vads-c-action-link`
- [ ] `vets-website` is updated to find and replace all instances of the action link

**Comment by k80bowman** [comment]
PR to update Formation: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/609

**Comment by k80bowman** [comment]
PRs to update other repos that consume Formation:
1. https://github.com/department-of-veterans-affairs/component-library/pull/77
2. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/428
3. https://github.com/department-of-veterans-affairs/vets-website/pull/16791

**Comment by k80bowman** [comment]
All PRs have been merged and I [posted an update to the `vfs-frontend` channel](https://dsva.slack.com/archives/C5HP4GN3F/p1618491824088300) so that everyone is aware.
