### ISSUE TITLE
Inconsistency in Button Loading/Downloading Indicator

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/vets-design-system-documentation#432]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.
Though it relates to the following tickets:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/420#issuecomment-820525963
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/238

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

https://design.va.gov/components/loading-indicators

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

Really, this is about what exact pattern do we want to follow for these use cases.

## Additional Context
On the health questionnaire product, Veterans will have the ability to download a PDF of their completed questionnaires. This can be accessed through a "View and print answers" button on the confirmation page as well as the list of all questionnaires. Anyway, generating this PDF may take awhile. As I was exploring solutions on how to denote that "downloading" may take awhile, I found three patterns currently in use on va.gov. Therefore, I thought that some guidance on the preferred pattern might be needed. 

Here are the patterns that I found:
1. Once pressed, the button will changed to this: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/loading-button/LoadingButton.jsx. This is utilized in the Profile section, My VA Dashboard, part of the intro to the NCA for logged out users when they enter basic info and we check to see if they have already applied for health care, as well as VAOS. The health questionnaire FE engineer ran this through a screen reader and it did not test well when placed in our workflow. I spoke to Josh Kim briefly about this too. He wants to look at the code, but his initial feedback was "[there are ways to do this accessibly](https://adrianroselli.com/2021/01/multi-function-button.html), but [it would be better not to have to communicate the state within the button itself](https://adrianroselli.com/2020/12/be-careful-with-dynamic-accessible-names.html). Having a loading message right next to the button that’s announced with an aria-live region would be the ideal route if possible."

2.
![Screen Shot 2021-04-15 at 11 04 08 AM](https://user-images.githubusercontent.com/66287082/115086135-b2376a00-9ed9-11eb-9383-e96ff1665591.png) 
<br/>This is used when a Veteran is downloading VA Letters and Documents.

3. 
![Screen Shot 2021-04-15 at 2 12 30 PM](https://user-images.githubusercontent.com/66287082/115086221-d5fab000-9ed9-11eb-8b48-71f0fa30453c.png) 
<br/>This is used when the caregiver application takes a long time submitting. This is also the pattern that the health questionnaire team chose to go with at this time for our ["Downloading" use case](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13146).

**Comment by caw310** [comment]
Feedback from DSC meeting on 7/23

- We will create a new ticket for new designer to add this documentation in DS.  
- We will document the two use cases
    - Static files
    - Generative uploading and downloading will behave this way.

**Comment by KevinMHoffmanUSDS** [comment]
DSC made medium because of potential accessibility issues

**Comment by caw310** [comment]
Start with audit.

**Comment by GnatalieH** [comment]
Hi @kristenmcconnell. Thanks for sharing those examples. Do you know of any more instances of downloading that I should take a look at? Here's what I can suggest so far:

- We should not be using a button to communicate a process/activity. We should use text near the button to communicate what is happening, like Josh mentioned.
- We have a [disabled button style](https://design.va.gov/storybook/?path=/docs/components-va-button--disabled) in the Design System we could use when the process is initiated.
- If the process time is known, I suggest communicating uploading and downloading activity using the [DS Progress bar - Activity](https://design.va.gov/components/progress-bar/) component.
- Other processes, when the wait time is unknown, lend themselves to using the indeterminate [Loading indicator](https://design.va.gov/components/loading-indicator) component.

@SarahKay8 can you take a look at my proposed solution and note any a11y issues your might find? Thank you!

**Comment by kristenmcconnell** [comment]
I do not know of other examples. It has been awhile, since I looked into this.

**Comment by GnatalieH** [comment]
@kristenmcconnell it's OK, I got another example from posting in the #design channel. Thx.

**Comment by caw310** [comment]
@humancompanion-usds , please review.

**Comment by GnatalieH** [comment]
I added a bullet point under Accessibility in the Button documentation to say:

- Button labels should never change dynamically or be used to communicate a status.

[Here's that PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1111/files).

**Comment by GnatalieH** [comment]
Closing this ticket per Matt's suggestion. We'll handle uploading/downloading patterns in #[1121](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1121) and #[1122](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1122).
