### ISSUE TITLE
Breadcrumb line break on mobile

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#469]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

See [issue #21810](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21810#issuecomment-842608299) for original context.

* This was discovered on a small (320px) width screen 
* When the text in a breadcrumb exceeds ~33 characters the entire line except the left pointing carat 

Screenshot:
![image](https://user-images.githubusercontent.com/2536801/118735489-68ea7b00-b7f5-11eb-9619-8ec97b47aa11.png)

## What I expected to happen

- Icon and level text fill the first row, with overflow text wrapping below.

## Reproducing
- Formation version:
- Device: MacBook
- Browser: Chrome

Steps to reproduce:

1. Sign in to va.gov
2. Go to VAOS homepage: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
3. View page between 320-370 screen size

**Comment by caw310** [comment]
The DSC reviewed and discussed. This issue will be added to the DST backlog and be prioritized to fix.

**Comment by andresriveratoro** [comment]
Possible fix:
![Screen Shot 2022-06-16 at 12.07.41.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/6060c9db-6331-47e1-9c7a-18072a4c27f2)
![Screen Shot 2022-06-16 at 12.07.31.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/5f8f60da-4514-4ce2-a50a-5fab487d405f)
