### ISSUE TITLE
Mobile-friendly, expandable alert

### ISSUE THREAD

**Issue by lildziner** [department-of-veterans-affairs/vets-design-system-documentation#476]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## Why
Existing collapsible/expandable alert components are too tall to use within small content sections.  Existing alerts have consistently caused way-finding issues in multiple usability tests because they take up too much real estate and create confusion when consuming content on VA pages. 

> - What evidence do you have that it's needed by multiple services across VA?

Will be used by multiple Vet Center product pages that do not offer dedicated satellite location pages and on Facility locator [#24824](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24824).

I was also directed to [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14485) when the work began as the Facilities team was the team with the most urgent need to solve the existing problem.  

> - What evidence do you have that it meets the needs of the users of those services?

This experimental component will be used and tested in 10 pilot MVP product sites where we have close communication with content editors and the Veterans who will use the pages. 

> - Have you checked that it doesn't already exist in the VA.gov Design System? 

Yes, our starting point (seen in Round 1) was an alert box combines with an additional info component as seen on Suicide prevention pages.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

[UXPin prototype containing design iterations and rationale
](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145/simulate/sitemap?mode=i)

## Next steps
~~You will present your work to the Design System Council at an upcoming meeting.~~

**This effort has been approved by** @rtwell [see Slack conversation](https://dsva.slack.com/archives/C0FQSS30V/p1622221093275300?thread_ts=1622131991.220000&cid=C0FQSS30V)]

**This work has gone through the Design Intent process** [[#24195](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24195#issuecomment-844225140)]

**This ticket is being created for tracking purposes and is connected to the FE work in** [[#24151](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24151)] 

> Submit request to join an upcoming Design System Council meeting in #vsp-design-system 

>During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

>If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you have any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by caw310** [comment]
Hi. This was discussed in the DSC meeting on 6/11. Here are notes and follow ups. 

- Will go into experimental design tab and will be tested. 
- Remove  animation. Just expand
- Make sure icon reads to screen readers as an alert. 
- The gray is too light. Barely noticeable especially on yellow. That needs to be black, dark gray or blue to have more contrast. Increase contrast on hero.

**Comment by sshein** [comment]
Becca and Riley are testing this component btw. They can put their findings here maybe?

**Comment by humancompanion-usds** [comment]
Alert - expandable is in the DS: https://design.va.gov/components/alert-expandable Waiting on the 1010 team who has built a web component for this to test it. The DST has a task now with this to update the guidance to point to the new web component in Storybook: https://design.va.gov/storybook/?path=/docs/components-va-alert-expandable--default

**Comment by caw310** [comment]
Work for this has been completed.
