### ISSUE TITLE
Text date inputs

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#481]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
Update date inputs to use text fields instead of select boxes (dropdowns).

## Why
[USWDS guidance on date inputs](https://designsystem.digital.gov/components/date-input/)
[Gov.uk research on date inputs](https://designnotes.blog.gov.uk/2013/12/05/asking-for-a-date-of-birth/)
[Alice Bartlett: Burn your select tags](https://www.youtube.com/watch?v=CUkMCQR4TpY&t=1s)

## Next steps
You will present your work to the Design System Council at an upcoming meeting.

Submit request to join an upcoming Design System Council meeting in #vsp-design-system 

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by caw310** [comment]
This was discussed at the 4/22 DSC meeting. Action items:

- Put in DST  backlog as a” try it out” component. 
- Try to find someone to use and test.

**Comment by rileyorr** [comment]
Hi @caw310 and @joshkimux! I'm interested in using and testing this component as part of an iteration of [the Financial Status Report (VA Form 5655)](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction). 

Is this component available to use yet? I noticed [the design system date input documentation](https://design.va.gov/components/form/date-input) contains the existing component with dropdowns. 

cc @kevinstachura

**Comment by k80bowman** [comment]
@rileyorr what kind of timeline are you looking at?

**Comment by rileyorr** [comment]
Hi @k80bowman! My team's at least a month out from being able to conduct a usability study for this project in which we'd test the new component. Let me know if that helps!

**Comment by k80bowman** [comment]
@rileyorr That is helpful, thank you. We have not yet built this version of the date component, but we can fast-track its development by a little to hopefully get it done for you. We'd love to have you test it. We have a sprint starting this Thursday and, while we already have our work prioritized for it, we could add the development of this component as a stretch goal so that hopefully we can get started on it. Most likely it would be about three weeks before it's ready for you to use (potentially earlier, but I wouldn't want to promise that). Would that work for you?

**Comment by rileyorr** [comment]
@k80bowman that sounds perfect! I appreciate it.

**Comment by k80bowman** [comment]
@rileyorr great, I'll let you know when the component is ready to use.

**Comment by GnatalieH** [comment]
The Memorable date component satisfies this request, I believe. FYI @caw310 and @k80bowman

**Comment by k80bowman** [comment]
Yes, however we have some upgrades to that component that are not available in `vets-website` just yet. The component is there and you can go ahead and use it, but there are some issues with validation that we've resolved. We have to get an issue with the Cypress tests worked out and then it should be ready. I apologize for the delay.

**Comment by GnatalieH** [comment]
No worries, now I remember the validation issues, @k80bowman. Thanks for that update!

**Comment by k80bowman** [comment]
The memorable-date component is now available for use in vets-website.
