### ISSUE TITLE
On this page `h2` is missing unique id for on this page `nav` to point to

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#482]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

[Several on this page `h2`s have missing unique ids](https://github.com/department-of-veterans-affairs/content-build/search?p=1&q=on-this-page) as caught by @mpelzsherman 

## What I expected to happen

Instead of:

```html
<nav id="table-of-contents" aria-labelledby="on-this-page">
  <!-- h2 is missing the unique id "on-this-page" which the nav points to -->
  <h2 class="vads-u-margin-bottom--2 vads-u-font-size--lg">On this page</h2>
```

it should be:

```html
<nav id="table-of-contents" aria-labelledby="on-this-page">
  <h2 id="on-this-page" class="vads-u-margin-bottom--2 vads-u-font-size--lg">On this page</h2>
```

**Comment by bkjohnson** [comment]
Rather than the proposed solution, I think it would be better to adopt `<va-on-this-page>`: https://design.va.gov/storybook/?path=/docs/components-va-on-this-page--default

**Comment by joshkimux** [comment]
@bkjohnson yes that would be great!
@mpelzsherman does this answer your original question?

**Comment by mpelzsherman** [comment]
I didn't really have a question. I was responding to Tim Wright's [feedback](https://github.com/department-of-veterans-affairs/content-build/pull/304#discussion_r661723119) on my [PR](https://github.com/department-of-veterans-affairs/content-build/pull/304).

I tried using the va-on-this-page Web Component on Vet Center main page, but I don't see an `aria-labelledby` attribute on it:

![__Veterans_Affairs](https://user-images.githubusercontent.com/80267/124058006-8b77d280-d9f6-11eb-9d20-a14decba8c97.png)

You can see my changes in this [PR](https://github.com/department-of-veterans-affairs/content-build/pull/309). Let me know if this is an improvement in terms of 508-compliance, @joshkimux .

**Comment by bkjohnson** [comment]
We can add `aria-labelledby`, that shouldn't be an issue.

**Comment by mpelzsherman** [comment]
@joshkimux - is `aria-labelledby` required for 508 compliance?

**Comment by joshkimux** [comment]
@mpelzsherman , yes, this is in relation to WCAG 2.0 1.3.1 Info and Relationships. [ARIA13 recommends to use `aria-labelledby` to name regions and landmarks.](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA13.html)

**Comment by mpelzsherman** [comment]
@bkjohnson Is `aria-labelledby` already supported by `va-on-this-page`? If not, I'm happy to work on a PR to add support for it, and begin the process of converting of our `<nav id="table-of-contents"` instances.

**Comment by bkjohnson** [comment]
It isn't supported right now, and feel free to reach out with any questions you might have involving modifying the component.

**Comment by AngelaFowler82** [comment]
Hello all, following up on this. Is there a timeline? One of our VSA teams is in need of this component and we would like to ensure that it is accessible to screen reader users.

**Comment by k80bowman** [comment]
@AngelaFowler82 the Design System Team is in active discussions on how to best resolve this issue. We'll keep you updated.

**Comment by mpelzsherman** [comment]
I'm sorry that I never followed up on this. FWIW, the Facilities team can't use va-on-this-page unless this [issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/530) is resolved, due to the requirements laid out by our PO [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28249).

**Comment by bkjohnson** [comment]
This functionality is now included in the `<va-on-this-page>` Web Component. Right now this fix won't be in the static content since the Web Component is not being used.

**Comment by bkjohnson** [comment]
I think this issue may be able to be closed since https://github.com/department-of-veterans-affairs/content-build/pull/1173 made changes to use `<va-on-this-page>` instead of rely on the custom version.

**Comment by bkjohnson** [comment]
@joshkimux can you confirm if this can be closed or not?

**Comment by joshkimux** [comment]
Yes, we can close this, just [tested the on this page component on the Springfield, MA Vet Center page](https://www.va.gov/springfield-ma-vet-center/#in-the-spot-light) and it's labelled appropriately.
