### ISSUE TITLE
Appointment summary card

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#484]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
> Give a brief description of the component or pattern you want to propose.

A card that displays a summary of an appointment. When clicked, it opens a new page that provides detailed information about the appointment.

## Why
> Explain why you think this should be added to the VA.gov design system.
>
> - What evidence do you have that it's needed by multiple services across VA?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the VA.gov Design System? 

VAOS shows Veterans a calendar list of their upcoming appointments, as well as:
* Requested appointments
* Past appointments
* Canceled appointments

In 2020 the VAOS team redesigned our appointment list, after feedback that it was difficult find individual appointments.

The goals of the new design were to make the list:
* Make the list easy to scan by showing consistent appointment details
* Provide clear information about the state of the appointment (upcoming, canceled, etc.)
* Make scanning and opening an appointment easy to use on mobile devices.

Now that we have this pattern in VAOS, other services that display appointments could potentially use it when displaying appointment information to Veterans, either by displaying the appt summary and have it link directly to the VAOS appointment detail page, or by including both appt and detail in the same context.

This pattern could be useful in the upcoming MyVA dashboard, which displays appointment information.

## Anything else

* [Pre-redesign appointment card states](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md)
* [Research that identified the problem](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/july-2020-user-research/2020-july-VAOSR-EC-research-report.md)
* [Content model workshop](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1604003206398/599c3e97059a56a6ac9c0b2570fc3f9370944fda)
* [Concept and usability test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/jan-2021-appts-list-test/report-out.md)

Mockups:
* [Appointment summary card](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/KvEvMEg)
* [Appointment details page](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rblrZzD)

Also note: We aren't currently showing "Type of Care" on these cards because we don't have access to that data in this context. Type of Care came up in the research as a key piece of information that would help Veterans scan the list more easily and we hope to update the designs with this in the future. 

## Next steps
You will present your work to the Design System Council at an upcoming meeting.

Submit request to join an upcoming Design System Council meeting in #vsp-design-system 

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by caw310** [comment]
Notes from the DSC meeting with recommendations.

Recommendations:
- Add appointment to Details and left align below appointment information. 
- Appointment details and your contact details should be H2

Consider: 
- Have further conversation with Peter about hover state and entire card being clickable, and rounded corners. 
- Does this being a whole clickable card make copy & pasting that truncated info more difficult
- Would *notification emails* be another thing to consider? (W.r.t. the info displayed and potentially what’s linked)

**Comment by sshein** [comment]
Claims status tool is another pattern that is "card with action to go to details"... We should probably align everything at some point. Curious why we're not using an action link, or rather what is the rule when to use an action link versus this carat link. cc @allison0034 since I think you were talking to Crystabel at one point about that?

**Comment by allison0034** [comment]
@sshein action links should be for starting a journey. The [How to use action links](https://design.va.gov/experimental-design/action_links#how-to-use-action-links) does a good job of explaining it. Further down the page are the bold links with the carat ([active links](https://design.va.gov/experimental-design/action_links#active-links)).

**Comment by sshein** [comment]
ohh interesting thanks! I didn't realize we had a definition of "active links" up

**Comment by humancompanion-usds** [comment]
Card has shipped and includes the Appointment summary card, including a version showing a status: 
https://design.va.gov/components/card#appointment
https://design.va.gov/components/card#appointment-with-status

If the design of the Appointment card has changed from how we've depicted it in the Design System then feel free to reopen this. Otherwise, we're declaring this done.
