### ISSUE TITLE
Add guidance to DS on the minimum clickable target size for mobile

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#490]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [X] Other

## What is the name
Add guidance on the minimum clickable target size for mobile

## What is the nature of this update?
Documentation 

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [X] Usability guidance
- [ ] Accessibility
- [X ] Implementation
- [ ] Research insights
- [ ] Package information

**Comment by rtwell** [comment]
50px?

width vs height?

tap-able area for links!

**Comment by sshein** [comment]
did we make a decision on this in terms of what is recommended @caw310? I lost track :)

**Comment by caw310** [comment]
@sshein I believe the decision made is to create another ticket to look at all tap areas on mobile to make sure they are a minimum 44 pixels. 

Once the Design System Team gets a new designer, he or she will add guidance on clickable target size.

**Comment by sshein** [comment]
ok I think maybe there are two tickets - one to do the audit, but then a smaller one just to write up the guidance in the design system

**Comment by GnatalieH** [comment]
48 x 48 px is the minimum suggested touch target size per advice from @CourtneyChambers77. 44 x 44 px is often cited as a minimum size, but in order to sufficiently accommodate Android users, we need to use 48 x 48 px.

**Comment by caw310** [comment]
Identify where to post the minimum size for buttons on design.va.gov.
