### ISSUE TITLE
"Toolbox" content page tool callout

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/vets-design-system-documentation#495]
## What
This component is intended to exist on content pages to more obviously call out an interactive tool belonging to a page of content. (e.g. Check VA copay balances tool on 'Pay your VA copay bill' page.) What we propose is to call out an online tool, explain what it does, and provide a CTA to either sign in or view the tool.

## Why
> Explain why you think this should be added to the VA.gov design system.

We've noticed that veterans tend to ignore the current sign in component found on content pages (too big, looks like an ad? too much information? not clear what signing in would do for them?) We've also noticed that Veterans don't seem to understand that they are able to interact with their benefits based on the content page. 

Previously, we would place a green button to enter a tool, but folks would constantly scroll past it and have to be directed to enter a tool page. Recently, the Caregiver team found that this was not alleviated by the new action link design. Our idea was to package the action link and call out the presence of a tool and what it can do for the user more prominently in a "toolbox."

We tested these designs in the copay usability study and it tested well, with almost all Veterans clearly understanding there was another page for them to interact with once they sign in.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.
- [Link to the Copay prototype we tested](https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages//comment/comments?mode=i)
- [Results of testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/jun-2021/readout.md#is-the-online-tool-card-effective-at-communicating-the-tool-and-its-use-to-the-veteran)

### Screenshots
![image](https://user-images.githubusercontent.com/6361930/126538876-4a9768d8-9801-43f5-9c46-6f535ef5537c.png)

## Next steps
You will present your work to the Design System Council at an upcoming meeting.

Submit request to join an upcoming Design System Council meeting in #vsp-design-system 

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by KevinMHoffmanUSDS** [comment]
Recommendation from Design System Council: for now, this should be consistent with existing tools and patterns across VA.gov. Please reference VAOS (VA Online Scheduling) for pattern guidance.
