### ISSUE TITLE
"Other information you may need" component relies on color

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#497]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The "other information you may need" component relies on color to convey that the headings within it are links. This is particularly challenging on mobile as folks will not be able to hover over links. This issue has emerged several times across multiple teams.

![image](https://user-images.githubusercontent.com/14154792/126549786-0c0d3468-45f3-40a7-a50e-1b144ca22e43.png)

## What I expected to happen

We have remediated this on several tickets by adding in an underline.
https://github.com/department-of-veterans-affairs/vets-website/pull/15698

Steps to reproduce:

1. Go to https://staging.va.gov/health-care/pay-copay-bill/
2. Confirm "other information you may need" relies on color

**Comment by GnatalieH** [comment]
@joshkimux where is this component represented on design.va.gov? Maybe I'm overlooking it, but I can't find it. Thanks.

**Comment by caw310** [comment]
@GnatalieH , I believe Josh is referring to the gray card that has 'Other information...' as a header. That's a card I believe.

**Comment by GnatalieH** [comment]
@caw310 yes, but we don't have "Cards" documented as a component or pattern, yet. This ticket specifies a "component", so I wanted to sure we are on the same page. We *do* have a Featured content component in our design system (and Storybook). However, Featured content has a blue background.

I think the links should be underlined as @joshkimux pointed out. But I don't know if this is a design system task unless it applies to a specific component. Because what would a Developer be modifying? I can add a detail in the in-progress Cards Pattern documentation that links should be underlined and not use only color as an indicator that they are clickable.

**Comment by joshkimux** [comment]
@GnatalieH agreed that this should be fixed as a design system bug and that guidance for links would be super clutch (especially given how many alternate designs exist for links in general) 👍

**Comment by joshkimux** [comment]
Quick question to follow up on this-- should we tag a developer to this ticket or should we close this out and create a new ticket in a more appropriate place?

**Comment by GnatalieH** [comment]
> ~Quick question to follow up on this-- should we tag a developer to this ticket or should we close this out and create a new ticket in a more appropriate place?~
> 
> I browsed through va.gov again and noticed that this issue seems to have been fixed universally:
> 
> * [Pay copay bill (original ticket)](https://staging.va.gov/health-care/pay-copay-bill/)
> * [Apply for education benefits](https://staging.va.gov/education/how-to-apply/)
> * [Download your benefit letters](https://staging.va.gov/records/download-va-letters/)
> * [View your payment history](https://staging.va.gov/va-payment-history/)
> 
> Will close this out! It would still be great to have links as a part of the design system though 🙏

@joshkimux just made [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/579) today. Thanks!
