### ISSUE TITLE
Anchor Tags (Copy Link)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/vets-design-system-documentation#502]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

[x]

## What
> Give a brief description of the component or pattern you want to propose.
The Copy Link functionality provides an easy way for users to share deep-linked content.

## Why
> Explain why you think this should be added to the VA.gov design system.
>
> - What evidence do you have that it's needed by multiple services across VA?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the VA.gov Design System? 

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

## Next steps
You will present your work to the Design System Council at an upcoming meeting.

Submit request to join an upcoming Design System Council meeting in #vsp-design-system 

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by humancompanion-usds** [comment]
We have a Copy Deep Link component out there now, which will move to be a sub-page of the Link component shortly and may become just a variation of a Link but, it's there and documented: https://design.va.gov/components/copy-deep-link
