### ISSUE TITLE
Copy Deep Link ux affordance for H3s and accordion contents

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#506]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
> Give a brief description of the component or pattern you want to propose.

The `Copy Deep Link` affordance lets users copy a link to very deep content on very long pages, so that they can easily send people a link to granular deep info (example: like a service listing accordion on  a VAMC page). 

## Why
> Explain why you think this should be added to the VA.gov design system. 

We ran a pilot on one page to test engagement. While it didn't meet the 1.5% (this is relatively high) engagement rate, we know that linking people to deep content -- especially accordion content on VAMCs and specific questions on COVID pages -- is desired but not possible today. 

We want to include the affordance that we piloted in the Experimental section of the Design System, so that other teams can take the work from here and reuse, refine, and do further testing or research with it.

>
> - What evidence do you have that it's needed by multiple services across VA?

Feedback from public affairs officers and call center representatives. 

> - What evidence do you have that it meets the needs of the users of those services?

We piloted this with Veteran users, but did not test this specifically with public affairs and call center teams.

> - Have you checked that it doesn't already exist in the VA.gov Design System? 

Yes.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

Design specs: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19867#issuecomment-786718474

UX behavior, logic, and 508 notes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/20125 

Product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags-product-outline.md

## Next steps
You will present your work to the Design System Council at an upcoming meeting.

Submit request to join an upcoming Design System Council meeting in #vsp-design-system 

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by KevinMHoffmanUSDS** [comment]
@jenniferlee-dsva Are you available to present this on Friday for a few minutes? If not, I'm familiar enough with it that I think we can cover it.

**Comment by caw310** [comment]
Here are the follow up items from the DSC meeting on 8/6

- May want to come back to discuss component further. 
- As next step identify team to run experiment. 
- Document the experiment that was done on Experimental design section.
