### ISSUE TITLE
"Back to Top" Consistency Evaluation and Final Documentation/Web Component

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/vets-design-system-documentation#514]
# Feature Request

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [x] Component

Back to top

## What is the nature of this update?

Audit the usage of the "back to top: button across VA.gov, document any inconsistencies, and create documentation for the desired pattern (right aligned black button with small screen responsive behavior). Note anywhere where the desired pattern is deviated from and create tickets for all teams to update once a web component has been created. 

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Package information

**Comment by KevinMHoffmanUSDS** [comment]
@caw310 Here you go! Apologies this took longer than it should have.

**Comment by caw310** [comment]
@GnatalieH , Here is a ticket you could work on while you're getting acclimated.

**Comment by GnatalieH** [comment]
Perfect, thank you!
