### ISSUE TITLE
[WIP] User Survey (Medallia) Feedback Button Placement/Relocation

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/vets-design-system-documentation#515]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
> We use Medallia for user surveys on VA.gov. One of the survey requires a "Feedback" button/link to be visible and accessible on specific pages. We want to place this feedback button at the bottom of `main` (right page border) for these pages.  .

## Why
> Explain why you think this should be added to the VA.gov design system.
- Placing this (feedback) survey button at the bottom of `main` will solve several 508 accessibility issues occurring with its current location and will also improve the overall user experience, based on usability testing feedback. 
> - What evidence do you have that it's needed by multiple services across VA?
- We have multiple teams utilizing this survey on their VA.gov product pages.
> - What evidence do you have that it meets the needs of the users of those services?
- We have conducted usability and accessibility testing, which resulted in this recommendation based on test results.
> - Have you checked that it doesn't already exist in the VA.gov Design System? 
- Yes.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #vsp-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by jwoodman5** [comment]
@caw310 I am working with Ian McCullough to finalize this ticket. Thanks.

**Comment by ianMcCullough-ob** [comment]
Here is a working [sketch file](https://www.sketch.com/s/dbc369e6-21ae-4717-a169-a5e734934f93) that mocks up the proposed solution.

**Comment by jwoodman5** [comment]
@caw310 Please let us know what else we can provide or clarify. Also, is there a place we can read about what to expect for next steps/timing? Thank you!

**Comment by caw310** [comment]
@jwoodman5 , This issue will be discussed at the next Design System Council Meeting which will be Aug 20 at 1pm ET. I'll have you and Ian added to the meeting invite. 
Generally, one of you will provide a summary of the request and then folks from the DSC will ask questions or provide input. Usually, we try to provide an answer that day.

**Comment by caw310** [comment]
Feedback from the DSC meeting on 8/20. 
Concerns
- Proximity is a concern 
- Stylistically two buttons (back to top and feedback) deviate from each other
- Potential pagination issues with next link. 

Come back to us with iteration or let us know if you don’t want to make any changes. 
Revisit next week.

**Comment by ianMcCullough-ob** [comment]
[Confluence document](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1845231893/Medallia+-+Bottom+of+Main+Design+Proposal) addressing the above mentioned concerns

CC @jwoodman5

**Comment by caw310** [comment]
@ianMcCullough-ob , the meeting was cancelled since a lot of people were out. I'll make sure you're invited to the meeting this week.

**Comment by caw310** [comment]
DSC meeting notes
https://docs.google.com/document/d/1FREF28ooKpaSapGyzkmj9YSkyDy64FFiEV7IxbbMf_I/edit?usp=sharing


Final Decision
Concerns
Proximity is a concern
Stylistically two buttons deviate
Pagination issues with next link. 
Come back to us w/ iteration or let us know if you don’t want to make any changes. 
Revisit next week. 

Action Items
Natalie to share link to page where pagination is covered by back to top.

**Comment by humancompanion-usds** [comment]
This looks to have been resolved by the proposed design and just not closed when that happened:

![Image](https://user-images.githubusercontent.com/52176351/171942762-ba72f23c-49fe-4abb-b544-f6a79d48ef09.png)

There is a pull request filed to document this component which can speak to the placement decisions once I update it to match the current template:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/892

I will connect this issue to that pull request and close this once we've brought the component into the system.
