### ISSUE TITLE
Component for reviewing pre-filled information in forms

### ISSUE THREAD

**Issue by LeelahHolmes** [department-of-veterans-affairs/vets-design-system-documentation#518]
## What
A standardized component for reviewing pre-filled information in forms. The user can review the information and make targeted edits to a specific field if they notice something is incorrect.

## Why
The DGIB team is redesigning the application for VA education benefits to pull the bulk of the application from information already stored in VADIR and the VA profile. The team has recognized a need for a review/edit component for that pre-filled information. We suggest reusing the "edit" card currently used in the list-and-loop pattern of the design system. 

Other VA services leverage pre-filled data for contact information—as reviewing becomes more of a common action across VA forms, the review pattern should be documented and consistent.

## Anything else
Example of proposed component:
<img width="604" alt="Screen Shot 2021-08-16 at 1 57 21 PM" src="https://user-images.githubusercontent.com/84807182/129611172-e9079c7f-f64b-4b14-8cbb-a588a92b058b.png">
<img width="547" alt="Screen Shot 2021-08-16 at 1 57 42 PM" src="https://user-images.githubusercontent.com/84807182/129611185-5c141522-a45c-48c6-8095-bacd957cfeca.png">
<img width="705" alt="Screen Shot 2021-08-16 at 2 18 29 PM" src="https://user-images.githubusercontent.com/84807182/129611029-5424ce38-4ae7-4392-91d5-431e745d685b.png">
<img width="686" alt="Screen Shot 2021-08-16 at 2 18 55 PM" src="https://user-images.githubusercontent.com/84807182/129611030-18910867-dd0a-4d1d-83d9-d74e8341b2b4.png">

Usability testing for the redesigned 1990 form is underway—thus far, 100% of participants have been able to complete the review and edit tasks when shown the proposed component. Further results forthcoming!

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #vsp-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by caw310** [comment]
Feedback from DSC meeting on 8/20

- There were accessibility issue findings from list and loop testing we can point you towards. 
- Strongly recommend test with non sighted users. We can help. Martha would be best person to talk to.  
- Need a clear statement of the Veteran problem you’re trying to solve.  (ex. Want more veterans to fill out this form in less time. 
- Need data to show the a11y issues are addressed. 
- Suggest doing more tests with mobile users.

**Comment by KevinMHoffmanUSDS** [comment]
Is this related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/619?

**Comment by humancompanion-usds** [comment]
@LeelahHolmes - Can you answer @KevinMHoffmanUSDS's question above? Is this issue related to issue #619? What's the current status on this work? This is in the Design System Team's queue to work on so we're trying to understand where this stands. Thanks!

**Comment by LeelahHolmes** [comment]
On the advice of the platform, we adjusted our designs to prefill the user's information in the standard form input pattern. This is not a design we took to testing, so I can close this ticket. This overlaps with #619 insomuch as we were identifying a similar pattern gap in the design system.
