### ISSUE TITLE
"List Tool" Pattern

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/vets-design-system-documentation#523]
## What
At one point I created a pattern for my team to follow based on all the tools that were being created that were essentially "a list of things" with questions about that thing. I showed it the council awhile ago but it isn't documented anywhere

More details including design and research can be found here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/306

## Why
This pattern was needed by multiple VSA teams and probably would be useful for other VFS teams

## Anything else
This pattern has been tested multiple times and performed well

**Comment by humancompanion-usds** [comment]
@sshein - Should this issue be closed now that we have https://design.va.gov/patterns/authenticated-info-list? Or is there more to be done here?

**Comment by sshein** [comment]
yep! this was the request for me to add it to experimental, it can now be closed.
