### ISSUE TITLE
Checkbox label top margin is overwritten by error message CSS declaration, causing the checkboxes to jump around

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#532]
## What happened
When checkboxes have an error state, the top margin declaration is getting overwritten by the `.usa-input-error label` declaration which causes the boxes to jump around.  I saw this in Storybook. I haven't seen this on va.gov in production, but I spoke with Robin who coded out the checkbox groups for the NOD form and it sounds like this isn't even what teams are using anyway ([they use this instead](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines#checkbox-group))...so maybe not worth fixing.

## What I expected to happen

space between checkboxes should stay consistent even when an error message is displayed

## Reproducing
1. Visit the [checkbox page in storybook](https://design.va.gov/storybook/?path=/docs/components-checkboxgroup--default)
2. Use the errorMessage control to add an error message

- Device: Macbook
- Browser: Chrome

https://user-images.githubusercontent.com/55992116/131011651-06c85e2c-6346-40f1-99d7-a3303f5a3f33.mov

**Comment by pdavies88** [comment]
[File of issue](https://github.com/department-of-veterans-affairs/component-library/blob/master/packages/web-components/src/components/va-select/va-select.css)
Line 49 is being overwritten by Line 24

**Comment by caw310** [comment]
@GnatalieH , touch base with Preston to provide guidance on this fix. Please create a ticket for design work. 
@pdavies88 , please create ticket for dev work. 

Link this issue with the new ones.

**Comment by caw310** [comment]
Closing as work on this is tracked in another ticket. Dev work done and being reviewed. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/33114
