### ISSUE TITLE
Margin/padding discrepancy between checkboxes and radio buttons

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#534]
## What happened

There is a difference in spacing and indentation on the design system radio buttons + checkboxes. Checkboxes are left aligned with the label and have more space between them, as compared to the radio buttons.

I think this difference is caused by differences in the CSS declarations for the top margin value between the two components, which should be consistent.  The guidance for both states:
>If you customize, make sure selections are adequately spaced for touch screens.

Which suggests there's flexibility for spacing, but there should be a standard recommendation built into the guidance/CSS, for desktop and touch screens.

![Screen Shot 2021-08-25 at 2 30 02 PM](https://user-images.githubusercontent.com/55992116/131369909-93dc5cff-dd63-41f0-8a2f-ddc04228fd75.png)
![Screen Shot 2021-08-25 at 2 30 14 PM](https://user-images.githubusercontent.com/55992116/131369914-c0a72436-20ee-489d-8d41-e253b9684117.png)

## What I expected to happen

- Spacing and indentation on design system form controls should be consistent.
- design system provides a baseline with adequate spacing for desktop and touch screens.  I would recommend 24px between components, given the size of our inputs.

## Reproducing
- Device: Macbook
- Browser: Chrome

Steps to reproduce:

1. Look at the [design system documentation for radio buttons](https://design.va.gov/components/form-controls#radio-buttons)
2.Look at the [design system documentation for checkboxes](https://design.va.gov/components/form-controls#checkboxes)

**Comment by caw310** [comment]
@GnatalieH , tagging you in this to review.

**Comment by GnatalieH** [comment]
Hi. Something I noticed is that the spacing on a single checkbox looks more aligned with the radio button spacing:

![image](https://user-images.githubusercontent.com/88347129/131870080-97ae0cb4-b6cd-4a45-90fe-d9470546d2ac.png)

Here's the radio button example from Storybook:

![image](https://user-images.githubusercontent.com/88347129/131870349-6d8cbcb1-f87a-4677-9ff7-9388a10e6ccf.png)

@andaleliz are you suggesting 24 px spacing between the description and the first checkbox/radio button, or 24 px between the checkboxes/radio buttons themselves, or 24 px between all items? I agree that we should have a consistent pattern for our form controls and their descriptions. I also think we should make the left alignment consistent.

**Comment by andaleliz** [comment]
>are you suggesting 24 px spacing between the description and the first checkbox/radio button, or 24 px between the checkboxes/radio buttons themselves, or 24 px between all items? 

My suggestion is specific to the space between the interactive elements, so the checkboxes and radio buttons.  My thinking here is to ensure sufficient space between tap targets to help folks avoid tapping the wrong thing.  IMO it more clearly associated the legend with the elements when it is closer, like the radio inputs.

 >I also think we should make the left alignment consistent.
 💯 agree.
 
 Thanks for your attention to this!

**Comment by caw310** [comment]
Duplicate so closing.
