### ISSUE TITLE
Update Sidenav component documentation with IA standards

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#558]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Sidenav component

## What is the nature of this update?

Sidenav component documentation should be updated to include IA standards.

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [x] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [x] Research insights
- [ ] Package information

**Comment by caw310** [comment]
@GnatalieH , is this still needed? Or did the consistency audit and work address this?

**Comment by GnatalieH** [comment]
@caw310 we can close this because we're working on a new strategy to get IA standards into the design system (ticket #1001).
