### ISSUE TITLE
Follow up on Breadcrumbs Component documentation

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#573]
## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Breadcrumbs

## What is the nature of this update?

- [x] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [x] Usage guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Follow up on action items from Design Council Meeting 10/22/21. [Here are the notes](https://docs.google.com/document/d/1WGnEG07GF606uU_z03GNg3CfvWmyWXiZS6vHdajGeh0/edit?usp=sharing).

**Comment by caw310** [comment]
@GnatalieH , I've put this in the backlog/needs prioritizing. We can fit into one of the upcoming sprints.

**Comment by GnatalieH** [comment]
Closing this issue since @mnorthuis posted the new Breadcrumbs documentation recently and it is live.
