### ISSUE TITLE
Flesh out Address block Component documentation

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#574]
## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Address block Component

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usage guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Currently there is no content in the design.va.gov [Address block Component page](https://design.va.gov/components/address-block) other than an embedded Storybook example of the component. We should apply the new Component template to Address block and flesh out this documentation, including links to the Content style guide. 

We also need to add an example that shows a five-digit zip code, per the advice of Content. Designers have wondered if the full nine-digit zip code is a requirement (it's not) when they see the current Address block example in design.va.gov.

**Comment by caw310** [comment]
Notes from DSC meeting on 12/3

Final Decision
Add guidance to component of when to use and when to not use

Action Items
Write up guidance of when the blue bar is needed or not needed
Natalie to work with Beth, Brooks to make sure to include "here's how to use the appropriate code"
Use the Do's and Don't format
Only use:
For addresses when they need to stand out from a sea of content (with blue bar)
On form intro pages where the mailing address is needed
Don’t use it like this:
Phone numbers with blue bar hidden

Example of when not to use the callout line
https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#health-care-offered-here

**Comment by bethpottsVADEPO** [comment]
@GnatalieH Let me know if you want any input as you write up this documentation. This is the page we looked at in the design council meeting as an example of when to use the address block in less structured, more content-heavy pages where we need the address to stand out: https://www.va.gov/disability/how-to-file-claim/
