### ISSUE TITLE
Flesh out Additional info Component documentation

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#575]
## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Additional info

## What is the nature of this update?

- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usage guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

There is no content on the [Additional info documentation page](https://design.va.gov/components/additional-info) other than an embedded Storybook example of the component. We should apply the new Component template and flesh out Additional info documentation, including links to the Content style guide if applicable.

**Comment by caw310** [comment]
@GnatalieH , thanks for writing up an issue for this. Brooks will be building an Additional Info web component so let's coordinate this documentation with the development work on this.

**Comment by GnatalieH** [comment]
Thanks @caw310 I kind of went a little nuts writing tickets last night. But I think it will help A LOT of Designers to have this Component better documented. I'm not sure who the assignee(s) should be.

**Comment by andaleliz** [comment]
@GnatalieH you're totally right that more documentation would be helpful. I found [this related ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/209), not sure if you saw it. Perhaps it should be closed in favor of this new one? 

PS, I found this ticket as I searched for related issues in a bug I noticed for this component. Opened #577 as a result.

**Comment by andaleliz** [comment]
I also just noticed that the Sketch component has a black chevron but the storybook version has a gray chevron 🤷‍♀️

**Comment by andaleliz** [comment]
Today I noticed the blue border in the Sketch symbol is a different shade of blue than what I see in the component. Wanted to pass along as something to add to your list of things to look into when you do this work.

**Comment by GnatalieH** [comment]
> Today I noticed the blue border in the Sketch symbol is a different shade of blue than what I see in the component. Wanted to pass along as something to add to your list of things to look into when you do this work.

@andaleliz bonus question: which color is the correct one? Should I change the Sketch file or request a change for the component? Thanks!

**Comment by andaleliz** [comment]
@GnatalieH 😆 I love a bonus question. I'm not totally sure, but I think it would be the lighter one since it lines up with the call out boxes.  Which means the Sketch file should be updated, not the code. Someone with more history with the design system like @rtwell might know the correct answer.

**Comment by GnatalieH** [comment]
@andaleliz I updated the Sketch file to use the same blue color as the coded component, because the color in the Sketch file didn't match any of our styles. I next will modify the symbol so the left blue border is only displayed on the child element and not the parent.

**Comment by caw310** [comment]
From the DSC meeting on 12/3 when this item was discussed. 

Final Decision
Move forward with Brooks’s new version with the line indented

Action Items
Danielle will follow up with content specific guidance and usage to documentation
Add missing screen reader technology that announces it correctly. Functionally it's the same as an accordion, but none of the Aria tags are in the code. Talk to Noah for his staging review notes

**Comment by humancompanion-usds** [comment]
Done! https://design.va.gov/components/additional-info
