### ISSUE TITLE
Update DS Backlog on design.va.gov

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#576]
## This update is for:

- [ ] Content styleguide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [x] Other

## What is the name

[Design System Backlog](https://design.va.gov/documentation/backlog)

## What is the nature of this update?

- Update page to be better aligned with Google doc of DSC Backlog
- Make sure items on web page are current, source of truth

**Comment by caw310** [comment]
@GnatalieH , let's update in the next sprint. I'll assign to both of us and whomever has time can make the update.
