### ISSUE TITLE
Additional info component blue left border is not visible on small screens and overlaps content on larger screens

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#577]
## What happened

When the additional info component expands, it has a blue border present. This is not visible on smaller screens. I noticed this in the VA.gov profile, and since it also happens in the storybook example, I think this is a component-level bug (rather than something introduced by a single implementation)

On larger screens, the blue border overlaps content in a weird way:

![image](https://user-images.githubusercontent.com/55992116/140810610-2979c8f0-7ae3-434b-a6e7-d805b16ea906.png)

## What I expected to happen

The blue border on the left side should be visible on all screen sizes, and does not overlap other parts of the page in a weird way.

## Reproducing
- Device: (e.g. iPhone 8, Macbook) iPhone 10 in Chrome, or use chrome emulator
- Browser: (e.g. Firefox, IE 11) Chrome

Steps to reproduce:

1. Log into staging with user 15 on a device with a small screen, or resize your browser to less than 481 pixels wide
2. Navigate to the profile > military history section
3.  Click on the `what if i...` additional info component at the bottom of the page
4. Notice the blue bar is missing (video attached)
5. Navigate to the personal and contact information section, and open one of the additional info components.

OR

Check out [this page in Storybook](https://design.va.gov/storybook/?path=/story/components-additionalinfo--default) and make sure canvas is set to small or xS screen. 

https://user-images.githubusercontent.com/55992116/140661096-dd84ada3-7bc0-4f59-acfd-87000cc3fc8f.mp4

**Comment by bkjohnson** [comment]
This may be addressed with the web component implementation:

![Peek 2021-11-11 17-05](https://user-images.githubusercontent.com/2008881/141391234-fc5ef1a4-e351-4882-9cd5-b435a023b789.gif)

**Comment by andaleliz** [comment]
Looks like it would be! Is this in storybook yet?

**Comment by bkjohnson** [comment]
Nope, not yet. What isn't obvious from that gif is that this solves the border issue by causing another one - the component is offset to the right, and would look weird with in context with other text. Here is what I'm talking about:

![Peek 2021-11-16 14-39](https://user-images.githubusercontent.com/2008881/142077776-208a4e19-464b-408e-9931-68c943e05730.gif)

I'm going to spend a bit more time on this and see if I can come up with something that resolves the border issue while not causing another problem, but if I can't then I may end up going with the implementation that has this border issue. I've talked with @GnatalieH about this and she thinks that the offset may deter designers from using the comopnent. Maybe this means that the entire component is due for a redesign, I'm not sure.

**Comment by andaleliz** [comment]
@bkjohnson I see what you're talking about - the other solutions I've mulled over also introduce new problems.  

@GnatalieH I wonder if we remove the blue border from the parent and only add it on the child if that could work? Maybe needs to be closer to the parent than shown in this video but it'll give you an idea.

https://user-images.githubusercontent.com/55992116/142217119-44f52db3-57a7-42f3-bcf0-3c775dccf003.mov

**Comment by caw310** [comment]
Kevin approved the solution proposed by Liz.  Brooks will make this change and Courtney will test to make sure there isn't an a11y issue for screen readers with this solution.

**Comment by bkjohnson** [comment]
The change has been implemented, and a development build [can be viewed here](https://60f9b557105290003b387cd5-rtshxufvmf.chromatic.com/?path=/story/components-va-additional-info--default). Axe checks are still passing.

**Comment by GnatalieH** [comment]
@bkjohnson in the Storybook example, the Additional info text is flush left without any spacing between the edge of the viewport and the text. This is how the surrounding content looks, too. Is this how the component will render, or will there actually be some padding/margin space to the left of the text? 

![image](https://user-images.githubusercontent.com/88347129/143888885-3e195539-a794-4a12-90bb-cd56fcc3451c.png)

**Comment by bkjohnson** [comment]
The component being flush without any spacing is just because the `<body>` has been forced to have 0 padding. If this isn't done, then the content will look like this:

![image](https://user-images.githubusercontent.com/2008881/143905185-9ec5a783-82b9-4492-831c-eb8e68492264.png)

**Comment by bkjohnson** [comment]
I'm going to close this since it has been fixed in our [web component](https://design.va.gov/storybook/?path=/docs/components-va-additional-info--default) which is now available in `vets-website`. The changes to the migration script to make it easier on teams to migrate should be merged in soonish.
