### ISSUE TITLE
Add Background alert with icon to Sketch pattern library

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#578]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Background alert

## What is the nature of this update?

New design for the Background alert with icon should be added to design.va.gov documentation and to the Sketch pattern library. 

- [x] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Responsive/resizable Sketch symbols need to be made so that Designers don't have to detach the symbol when they type new content into the alert.

**Comment by caw310** [comment]
@GnatalieH Lets break this into two tickets.
