### ISSUE TITLE
Add Links as a Component on design.va.gov

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#579]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [x] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Links

## What is the nature of this update?

- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [x] Implementation
- [x] Research insights
- [ ] Package information

## Additional Context

Because divergent patterns for links have emerged recently on the Platform, Designers would benefit from having Links usage guidelines on design.va.gov. Most design systems organize Links as a component, and we should too. The documentation should highlight accessibility considerations and crosslink to the content style guide's Links entry.

**Comment by joshkimux** [comment]
You may want to sync with @RLHecht as she is doing something similar!

**Comment by GnatalieH** [comment]
> You may want to sync with @RLHecht as she is doing something similar!

Will do, thanks!
