### ISSUE TITLE
Update alert web component to support icon in backgroundOnly mode

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#586]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

`<va-alert>`

## What is the nature of this update?

Design work has been completed to allow an icon for the "background only" variant for the alert component. We need to modify the Web Component to support this feature.

## Additional Context

- [Design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31192)

**Comment by GnatalieH** [comment]
I removed myself as assignee because this is a technical ticket to update the web component.
