### ISSUE TITLE
Responsive list table alignment is incorrect in Storybook

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#595]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The first column ("Name") is bottom-aligned in the Responsive list story.

![image](https://user-images.githubusercontent.com/88347129/145419411-77539816-f8a2-4926-9cae-55f378963967.png)

## What I expected to happen

The first column should be top-aligned  just like the second column ("Description") is.

## Reproducing
- Formation version: unsure
- Device: small viewport size in Storybook story
- Browser: Chrome Version 96.0.4664.55

Steps to reproduce:

1. Go to [Table story](https://design.va.gov/storybook/?path=/story/components-table--default)
2. In the Canvas tab, select the Small Screen size to view the Responsive list table.

**Comment by bkjohnson** [comment]
We can close this once https://github.com/department-of-veterans-affairs/va.gov-team/issues/35148 is done. The [web component version](https://github.com/department-of-veterans-affairs/component-library/pull/291) doesn't have this issue.
