### ISSUE TITLE
Radio option AXE console error - id attribute value must be unique

### ISSUE THREAD

**Issue by imelda-guzman** [department-of-veterans-affairs/vets-design-system-documentation#601]
Hello from the VAS-UI team,

We are hoping to get another update to the va-radio component.  Our app currently has multiple radio groups with the same option label and we need to be able to define the radio option id ourselves or be able to remove the default id attribute for options.

We currently have these versions installed

- @department-of-veterans-affairs/component-library: 3.7.2
- @department-of-veterans-affairs/web-components: 0.16.2

Attached is a screenshot of the radio groups in our app for reference.

![radio-groups](https://user-images.githubusercontent.com/748095/146274451-34d177b1-655e-45cb-8301-ee948b4dd8ac.jpeg)

### The Issue
The va-radio component options are returning AXE console errors for duplicate id's.  By default the va-radio component currently adds id attributes to all options based on the label name.

![axe-console-errors](https://user-images.githubusercontent.com/748095/146273281-cac2903f-4558-47a3-bf8d-68237ea22a07.png)

### What is expected
As a user of this component we would like to have the ability to either set the id for a radio option or have a boolean flag that allows us to remove the default id that gets added by the va-radio component.

**Comment by allison0034** [comment]
@imelda-guzman can you attach the whole screen shot? If this is a form, and users have multiple radio buttons, I would suggest going to one question per page. I think you need to involve accessibility. @noahgelman @joshkimux

**Comment by GnatalieH** [comment]
@CourtneyChambers77 is our Accessibility Specialist on the Design System Team, and I believe she asked to see this pattern in staging so she could run some tests. This is tangential to your issue, @imelda-guzman, but we encourage accordion usage to organize sibling content and not form elements like radio buttons, buttons, etc. The Additional info component has a similar behavior and may be a better choice for your needs.

**Comment by CourtneyChambers77** [comment]
Hello,  I'm free when you are I would like to see the component to add my
suggestions

**Comment by joshkimux** [comment]
@imelda-guzman , the issue is stemming from there being duplicate questions. I agree with @allison0034 and @GnatalieH that this would likely be better handled from a design perspective by using one question per page as opposed to remediating the existing design from an engineering perspective.

**Comment by imelda-guzman** [comment]
Thank you all for the feedback. To answer @allison0034 question, yes this is a form with different sections that reuse the same labels.  I attached a screenshot of the full page for reference

<img width="600" alt="fullpage" src="https://user-images.githubusercontent.com/748095/147680823-4d91e4ea-6018-4d2b-bb8e-f7f2f901afd8.png">

You all make valid points for accessibility and after reading all your comments and #607 I will need to take this back to our team and lead Designer to discuss how to best re-work the sections.  I don't think we'll be able to go to individual pages for each section so I would love to get in contact with @CourtneyChambers77 for ideas and how best to move forward.

In regards to the va-radio component, I think it would still be nice to have access to create our own unique ID's or have access to a boolean flag to be able to turn it off.  Per the example in [Storybook ](https://design.va.gov/storybook/?path=/docs/components-va-radio--default) a user doesn't have that option to set.

@CourtneyChambers77 please let me know the best way to reach you.

**Comment by GnatalieH** [comment]
@imelda-guzman I believe the Design System Team is going to consider your suggested update to the radio button component, it's work that @k80bowman and @caw310 will prioritize in 2022. Our developer who recently worked on this component recognized your request as valid. Thanks!

**Comment by k80bowman** [comment]
This is now an engineering task. Whichever engineer picks this up, we need you to update the va-radio component to accept an id prop, though the id should default to using the label (as it does currently) if no id prop is provided. You should also work with @GnatalieH to update the guidance for this component to include any necessary guidance around using this prop. We should probably also include any essential guidance in the prop description in Storybook.

**Acceptance Criteria**
- [ ] `va-radio` component is updated to accept an optional id prop (with the label prop used as a default)
- [ ] tests are updated accordingly
- [ ] documentation is updated with proper usage for this prop (design.va.gov and Storybook)

**Comment by pdavies88** [comment]
@CourtneyChambers77 I don't happen to have Axe DevTools Pro so I'm not able to isolate elements for testing but if you have a Pro Suite or another similar tool, would you be able to confirm that the Axe tests pass in regards to id's not being duplicated. You can test via this url: https://60f9b557105290003b387cd5-wecismebro.chromatic.com/iframe.html?id=components-va-radio--custom-id&viewMode=story


I'm confident it will be fine but I want to double check and make sure the issue reported originally via this screenshot in the ticket is resolved:
![146273281-cac2903f-4558-47a3-bf8d-68237ea22a07](https://user-images.githubusercontent.com/11822533/151596686-b2313bc4-09ed-48b7-b327-0d3cb10f7e7b.png)

**Comment by pdavies88** [comment]
@CourtneyChambers77 I have updated the PR and the check for the Radio elements have no accessibility name can be retested here:

https://60f9b557105290003b387cd5-dtnuqwjdxy.chromatic.com/iframe.html?id=components-va-radio--id-usage&viewMode=story

I added an `aria-label` to the labels and I think that should give us the fix we are looking for but please let me know if you are still experiencing the issue reported via:
![image (1).png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/5708e16a-bf06-46e7-9b3e-9d80bb340936)

**Comment by CourtneyChambers77** [comment]
Able to review the component with a SR and passes
