### ISSUE TITLE
Prevent horizontal scrolling in accordion items

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#602]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

While trying to migrate to the accordion web component, an alert within the web component resulted in a horizontal scrollbar being added.

![image](https://user-images.githubusercontent.com/2008881/146574219-15364ee6-7434-44fb-a8c4-5bdcaada3360.png)

## What I expected to happen

I expected that the accordion item would wrap any content inside, preventing horizontal scrolling.

## Reproducing

This seems to happen when a slotted container has 100% width and inner content which will cause that width to expand. When the slotted container doesn't have 100% width, the horizontal scrolling doesn't happen.

![image](https://user-images.githubusercontent.com/2008881/146574822-b4aeadac-4cf1-4490-b928-9833faffdfe1.png)

Steps to reproduce:

1. Put a child container into the `<va-accordion-item>`
2. Set the width of that container to be 100%
3. Put a long line of text into the container

**Comment by GnatalieH** [comment]
FWIW, these examples I see with alerts and form controls like buttons, etc. within accordions aren't really kosher. How can we better inform teams of proper vs. improper accordion usage?

**Comment by bkjohnson** [comment]
@GnatalieH I'm not sure about that. We can certainly put something like "don't do this" in the usage documentation on design.va.gov, but that still might go unseen. If we wanted, we could find or come up with a linting rule that would allow us to prevent certain children inside certain components, but for now we don't have that.
