### ISSUE TITLE
Update Accordions component guidelines with more guardrails to prevent improper usage

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#607]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Accordions component guidelines

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [ ] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Recently a couple of examples of improper accordion usage have surfaced. Please see #601 and #602 for reference. The Accordions component documentation should be updated to specifically communicate that accordions are meant to organize sibling content and _not_ things like form controls and alerts. In addition, the accessibility considerations should be updated to explain _why_ we shouldn't use these elements in accordions. We should also consider adding placement guidelines, such as not using accordions in the left nav or right rail, if that is what we wish to avoid.

**Comment by caw310** [comment]
@allison0034 , if you have time next week, would you be able to work on this?

**Comment by GnatalieH** [comment]
@CourtneyChambers77 are there accessibility considerations I should note for Accordions? Also, what kind of testing can be run to check for accessibility issues? Thanks!

**Comment by CourtneyChambers77** [comment]
Accessible Accordion
Accordion widgets must require accessibility considerations to make them useful for everyone. This will explain what is needed to do to create accessible, inclusive accordion components.

Accordions are related to the UX techniques of progressive disclosure(opens in a new tab), which aims to maintain the focus of a user's attention by reducing clutter, confusion and cognitive workload. It works by only present details of a section upon a tap or click, when necessary.

An accordion is a list of items, each composed with two parts: a header and a panel.

Header
Summary of the section of content should hide/show. It also serves as the visibility control of the content (hint: <button>), meaning it is interactive with a mouse and keyboard.

It usually contains a title describing the section, and a visual indicator of the visibility state of the accordion item.

Panel
The section of content should show/hide.
When the accordion is closed, the content inside the panel shouldn't be visible or interactable (: focusable elements shouldn't be focusable when they are not visible on screen).

When not to use an accordion
Given its benefits, it can be tempting to use accordions whenever possible, but this can often do more harm than good.
Nielsen Norman Group gives some criteria on when to use accordions and when to avoid using it. In short, when all the page content is relevant to users, it is more advantageous to show all the content at once, even if doing so results in longer pages. On the desktop it is easier to simply scroll the page than to decide on which topics to click on.

Accordion and Accessibility
As HTML doesn't natively provide an accordion element, we need to implement this widget by making sure it is accessible to keyboard and screen reader users. That's what we will cover next. The implementation we will take as example comes from the "Design Patterns and Widgets"(opens in a new tab) in the WAI-ARIA Authoring Practices 1.2(opens in a new tab).

Testing Accordion 
•	I can use Tab and Enter (Space) to navigate through accordion.
•	Focus don’t shift inside accordion before I open the accordion item.
•	I can also use arrow keys up and down to navigate through accordion. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/info/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/info/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/info/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<h2 style='margin-top:0in'><b><span style='font-size:16.5pt;line-height:107%;
font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:
"Times New Roman";mso-hansi-theme-font:minor-latin;mso-bidi-font-family:"Times New Roman";
color:#212529'><a
href="https://www.aditus.io/patterns/accordion/#keyboard-support"><span
style='color:#212529;text-decoration:none;text-underline:none'><span
style='box-sizing: inherit'>Keyboard Support</span></a><o:p></o:p></span></b></h2>



Element | Key | Required | Action
-- | -- | -- | --
header | Enter or Space | ✅ | Changes   the collapsed/expanded state of the associated panel.
header | Arrow Down | ✖️ | Moves   focus to the next accordion header.
header | Arrow Up | ✖️ | Moves   focus to the previous accordion header.
header | Home | ✖️ | Moves   focus to the first accordion header.
header | End | ✖️ | Moves   focus to the last accordion header.




</body>

</html>

**Comment by GnatalieH** [comment]
Thanks you @CourtneyChambers77! This is great. We'll need to see if our Accordion component matches your suggested behaviors in terms of Keyboard Support. I'll finesse these recommendations into our documentation on design.va.gov.
