### ISSUE TITLE
va-select component not firing event using onChange handler

### ISSUE THREAD

**Issue by imelda-guzman** [department-of-veterans-affairs/vets-design-system-documentation#608]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We are currently swapping out custom elements with the VA web components and ran into the issue where the  va-select component doesn't fire any event when using the onChange handler.

## What I expected to happen

I expected the onChange to fire when I change the value in the select element.

## Reproducing
- Formation version: 6.17.3
- Device: Windows laptop
- Browser: Edge Version 94.0.992.58
- Component library: 3.11.0
- Web components: 0.20.0 

Steps to reproduce:

1. Add a va-select component to your project
2. Add an onChange handler function
3. Make selection

**Comment by andresriveratoro** [comment]
Imelda,

Thank you for reporting this. Could you share a code snippet of how you're using this component?

Without knowing more, try this:
```
import { VaSelect } from '@department-of-veterans-affairs/web-components/react-bindings';

<VaSelect onVaSelect={() => console.log('hi')}>
```

**Comment by imelda-guzman** [comment]
Hi Andres,

Thank you for pointing me in the right direction. I tested your example and that works.  My apologies, it was a user error. I had the component setup like this

-  No import 
- component written like this ( va-select ) 
- using wrong function handler

`<va-select onChange={myfunction}>`

The documentation for how to use these web components properly is a bit confusing and missing key details for how to setup correctly.

I followed the setup for the web components on the [VA Design System website](https://design.va.gov/documentation/developers#load-the-web-component-library) and there is no mention of needing to import these components.

_6. Any Web Components from the Design System (identified by tags prefixed with <va-*>) should now work as expected on your page._

The [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-select--default) for the va-select also makes no mention of which function handler to use and the example code has the tag prefixed with `<va-*>` instead of `<VaSelect>`

Please let me know if you would like me to open an issue for documentation update against these web components.

**Comment by andresriveratoro** [comment]
I'm glad it's working. [https://github.com/ionic-team/stencil-ds-output-targets#react](https://github.com/ionic-team/stencil-ds-output-targets#react) explains when and why this is needed, but this information is missing in our documentation. I can open the issue. Thank you for bringing this to our attention.

**Comment by k80bowman** [comment]
Also created this [ticket](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/34746) to update documentation on Storybook

**Comment by caw310** [comment]
Wasn't really an issue. Closing.

**Comment by caw310** [comment]
Wasn't really an issue. Closing.
