### ISSUE TITLE
Add test coverage in the design-system-dashboard-cli repo

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#620]
## Description

The [`design-system-dashboard-cli` repo](https://github.com/department-of-veterans-affairs/design-system-dashboard-cli) is what we use to gather usage data on how our components are being used, and this data gets fed into a Domo dashboard. Despite the importance of that data, the repo still feels like an MVP product and doesn't have any unit tests. As we continue to use that data and make changes to how we gather it, we may want to add some automated testing and integrate it with CI.

Since some of the functions are reading from files, we may want to [use a dependency to help us mock the files](https://github.com/tschaub/mock-fs). Having a few small sample files to use which represent what we would get in `vets-website` and `content-build` could help with testing.

## Acceptance Criteria
- [ ] Add unit tests for existing code
- [ ] Add the running of those tests to the CI for PRs and merges (pre-deploy)

**Comment by caw310** [comment]
As discussed in stand up, test coverage should be at least 30%.
