### ISSUE TITLE
Found an issue with background color only alarts

### ISSUE THREAD

**Issue by ytsaoca** [department-of-veterans-affairs/vets-design-system-documentation#621]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We noticed that there is an inconsistency between the sketch design system and the component library. The sketch files show a grey icon on the error alert, but the icon for the error alert in the component library is red. 

![Screen Shot 2022-01-11 at 1 18 00 PM](https://user-images.githubusercontent.com/90633685/149201937-ec906b1d-c47a-4880-bf4a-ccadf1663a0f.png)

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1.
2.
3.
4.

**Comment by caw310** [comment]
@k80bowman @GnatalieH , We will need to look into this one to identify which needs updating. Putting in our backlog 'reviewed/needs prioritizing' for now to determine when we will look into this.

**Comment by k80bowman** [comment]
Confirming that the va-alert component used with the status=error, background-only=true, and show-icon=true options shows the alert with a red icon
<img width="464" alt="image" src="https://user-images.githubusercontent.com/12739849/149211418-c757bab2-0896-4443-a170-ff14c5d95f36.png">

**Comment by GnatalieH** [comment]
> Confirming that the va-alert component used with the status=error, background-only=true, and show-icon=true options shows the alert with a red icon in Storybook <img alt="image" width="464" src="https://user-images.githubusercontent.com/12739849/149211418-c757bab2-0896-4443-a170-ff14c5d95f36.png">

I wonder if this was intentional design decision to make only the Warning alert use a red icon rather than dark gray icon like the rest of the alerts. @rtwell do you know the history of this alert style? I realize this perhaps isn't something that needs to be fixed in Storybook, but I do need to change Sketch library symbol to match it if the red icon is indeed intentionally used. I see that the full size Warning alert box also uses the red icon. Thanks!

**Comment by bkjohnson** [comment]
Showing an icon in a background-only alert is pretty new, and the existing styles for regular alerts were used likely out of convenience/simplicity. I don't think engineers had access to the sketch files during development.

**Comment by GnatalieH** [comment]
Thanks Brooks. [Here is a link to the Sketch file](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/621#issuecomment-1012292474) I'd shared when this work was being done. If you click on a page and then click the Inspector tab on the right side of the screen, you can hover over different elements on the screen to see the CSS. I think the Sketch icon style is bigger, too, but @andresriveratoro and I had talked about that and he had tweaked the icon size a bit.

**Comment by ytsaoca** [comment]
'cc @niradatta1  @dcgoodwin2112 @kristenmcconnell

**Comment by GnatalieH** [comment]
Closing this ticket because I fixed the Sketch library Error background alert icon color to be red.
