### ISSUE TITLE
Document link styles for states: default, hover, active, visited, and focus

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#624]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Links styles need to be documented for default, hover, active, visited, and focus states.

## What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [x] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

After link styles are documented, a Developer will update the live code example to match. See [Typography-->Links](https://design.va.gov/design/typography#links) for example.

**Comment by GnatalieH** [comment]
**WIP**

Default link:

a {
    color: #004795;
    text-decoration: underline;
    transition-duration: 0.3s;
    transition-timing-function: ease-in-out;
    transition-property: color, background-color, border-color;
}

Hover state:

a:hover {
    text-decoration: underline;
}

Active/focus state:
TBA

Visited state:

a {
    color: #4c2c92;
    text-decoration: underline;
}

**Comment by GnatalieH** [comment]
@k80bowman can I get some assistance from a Developer on how to capture the hover and active/focus state values? I'm not sure if I need to spec out the background and focus halo colors that appear on hover and active/focus states. Thanks.

**Comment by k80bowman** [comment]
@GnatalieH absolutely. You should be able to do this in your browser tools. Might be easier for me to show you, though. I'll reach out in Slack.

**Comment by GnatalieH** [comment]
Next steps

- Use the link states I listed in this ticket to fix the live code preview that we use in [Typography/Links](https://design.va.gov/design/typography#links).
- I will use this same code preview when I create the Links Component documentation page.
