### ISSUE TITLE
[Modal] Add usage guidelines to Modal documentation

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#626]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content styleguide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Modal

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [x] Research insights
- [ ] Package information

## Additional Context

In order to help prevent modal misuse, @artsymartha68 suggested we update our documentation with more guidance. @allison0034 also suggested adding specifications for maximum content length in modals.

**Comment by GnatalieH** [comment]
@caw310 and @k80bowman this may be a good ticket to prioritize soon. @allison0034 and @artsymartha68 have both requested additional guidance in our modal documentation.

**Comment by caw310** [comment]
@humancompanion-usds @GnatalieH  - Looks like there are guidelines for Modal. Can we close this ticket?

**Comment by GnatalieH** [comment]
Yes, I'm closing now @caw310. Thanks.
