### ISSUE TITLE
Tabs: create Sketch symbols for VA Pattern Library

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#627]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name?

Tabs

## What is the nature of this update?

- [x] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Create symbols for Sketch pattern library of Tabs component.

**Comment by caw310** [comment]
Closing as VADS no longer uses Sketch and this should be addressed in Figma.
