### ISSUE TITLE
Organize UX Audits within Design System Team Confluence space

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#629]
### Issue
Currently UX audits of components and patterns live in different Mural boards. This is problematic because editing permissions in Mural can be tricky to implement, and Mural doesn't allow for easy browsing or searching within the boards. 

### Proposed solution
@allison0034 suggested moving the audits to a dedicated area within the DST Confluence space. Having a dedicated Confluence space will allow other teams to easily access the audits. A placeholder parent [page has been created here](https://vfs.atlassian.net/wiki/spaces/DST/pages/2061336609/Audits). 

### Steps to achieve solution

1. Create pages in Confluence for each of the components and patterns that have an audit in Mural. Start with Tabs (current audit in progress).
2. Add a placeholder table for organizing Mural link(s) within each page.
4. Add corresponding URLs for screenshots.
5. Have Allison and Sean review Tabs (to validate the page template) after it has been completed.
6. Add more components and patterns using validated template.

**Comment by caw310** [comment]
We have audits in confluence. closing
