### ISSUE TITLE
Full page reload on va-breadcrumbs component

### ISSUE THREAD

**Issue by imelda-guzman** [department-of-veterans-affairs/vets-design-system-documentation#635]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Using the **VaBreadcrumbs** web component is returning a full page reload for the breadcrumb links.  The page reload does not happen when using the React component **Breadcrumbs** 

```
import React from "react";
import { Link } from "react-router-dom";
import { VaBreadcrumbs } from '@department-of-veterans-affairs/web-components/react-bindings';
import Breadcrumbs from '@department-of-veterans-affairs/component-library/Breadcrumbs';

const routes = [
  {
    id: 1,
    breadcrumb: 'Clinic Configurations',
    path: '/clinic-configurations'
  },
  {
    id: 2,
    breadcrumb: 'Create New Clinic',
    path: '/clinic-configurations/clinic-creation'
  },
];

const ClinicBreadcrumbs = () => {

  return (
    <>
      {/* VA Web component */}
      <VaBreadcrumbs>
        {routes.map((item) => (
          <Link key={item.id} to={item.path}>{item.breadcrumb}</Link>
        ))}
      </VaBreadcrumbs>

      {/* VA React component */}
      <Breadcrumbs>
        {routes.map((item) => (
          <Link key={item.id} to={item.path}>{item.breadcrumb}</Link>
        ))}
      </Breadcrumbs>
    </>
  );
  
};

export default ClinicBreadcrumbs;
```

## What I expected to happen

I expected the Web component to have the same behavior like the React component and not reload the page when navigating the breadcrumb links.

## Reproducing
- Component Library version: 5.0.1
- Web Component version: 1.0.0
- Formation version: 6.17.5
- React Router Dom version: 5.2.0
- Device: Windows laptop
- Browser: Microsoft Edge Version 96.0.1054.72

Steps to reproduce:

1. Setup two pages and add VaBreadcrumbs to subpage
2. Import VaBreadcrumbs and map over routes
3. Click on va-breadcrumb links - you'll see full page reload
4. Test against React component breadcrumbs - no page reload

I provided some code above for reference.

**Comment by bkjohnson** [comment]
This may be happening because we are hiding the actual children that get passed in and are recreating them in the shadow DOM so that we can have more control over styling:

https://github.com/department-of-veterans-affairs/component-library/blob/69655465824e556cc6ea5291be94557e61448986/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx#L70-L91

We may be able to solve this by leaving the slotted children visible and applying our styling in our global CSS file like we're doing here:

https://github.com/department-of-veterans-affairs/component-library/blob/64da9e17d85b198b474d77fa300979a111bd7b94/packages/web-components/src/global/main.css

**Comment by andresriveratoro** [comment]
We can definitely solve this by displaying the slotted children, but I haven't been able to figure out how to wrap each child inside a `li` to retain our accessibility for this component.

Alternatively, I wanted to see if I could do something like this to not recreate the node entirely like we are currently, but each child displays as `undefined`.
```jsx
  componentWillLoad() {
    //  This renders slot content outside of a slot.
    //  This is a workaround for the limitations of styling slotted nested elements.
    //  See https://stackoverflow.com/questions/61626493/slotted-css-selector-for-nested-children-in-shadowdom-slot/61631668
    const anchorNodes = Array.from(this.el.querySelectorAll('a'));
    this.breadcrumbs = anchorNodes.map(
      (node: HTMLAnchorElement, index: number) => {
        const liWrapper = document.createElement('li');
        if (index === anchorNodes.length - 1) {
          node.setAttribute('aria-current', 'page');
        }
        liWrapper.appendChild(node);
        return liWrapper;
      },
    );
  }
```

**Comment by andresriveratoro** [comment]
Alternatively, this can be solved by including the `li` wrapper when mapping over the children in apps, but that offloads the responsibility to the dev using the web component. I don't like it because I think it makes it less user friendly.

**Comment by bkjohnson** [comment]
Here's an example of how we might wrap the children (I'm doing this using stencil 2.12.1 so I can put a `ref` on the `<slot>`), I think it's similar to what you have:

```diff

diff --git a/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.css b/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.css
index b1b2fd7..441f3aa 100644
--- a/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.css
+++ b/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.css
@@ -2,9 +2,9 @@
   display: block;
 }
 
-::slotted(*) {
-  display: none;
-}
+/* ::slotted(*) { */
+/*   display: none; */
+/* } */
 
 nav {
   background: var(--color-white);
diff --git a/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx b/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
index fbb8c4a..598a1a3 100644
--- a/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
+++ b/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
@@ -15,6 +15,7 @@ import {
   shadow: true,
 })
 export class VaBreadcrumbs {
+  crumbs!: HTMLSlotElement;
   @Element() el: HTMLElement;
 
   /**
@@ -90,6 +91,18 @@ export class VaBreadcrumbs {
     );
   }
 
+  componentDidLoad() {
+    const crumbs = this.crumbs.assignedNodes();
+
+    crumbs.forEach(crumb => {
+      const li = document.createElement('li');
+      crumb.parentNode.replaceChild(li, crumb);
+      li.appendChild(crumb);
+    });
+  }
+
   render() {
     const { label } = this;
 
@@ -100,7 +113,7 @@ export class VaBreadcrumbs {
             {this.breadcrumbs}
           </ul>
         </nav>
-        <slot></slot>
+        <slot ref={(el: HTMLSlotElement) => (this.crumbs = el)}></slot>
       </Host>
     );
   }
```

Sample output:

![links wrap anchors in DOM](https://user-images.githubusercontent.com/2008881/154162577-65fc2267-c519-4992-addc-83e42dc62046.png)

I'm not sure if that kind of DOM manipulation would break whatever React is doing in its virtual DOM though.
