### ISSUE TITLE
Document type-ahead as a component on design.va.gov

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#636]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [X] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name?

Type-ahead

## What is the nature of this update?

- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [x] Research insights
- [ ] Package information

## Additional Context

After audit and design (if applicable) phases have been completed, Type-ahead should be documented as a Component on design.va.gov.

**Comment by GnatalieH** [comment]
@CourtneyChambers77 I wanted to make you aware of this ticket, even though it's not on the board for the current sprint. I found this [accessibility audit presentation](https://docs.google.com/presentation/d/1JSN9Bd7-4yOl8hVZS3zEhHuDxI3DMAYzZLCXYz9fMfs/edit?usp=sharing) for type-ahead that Josh Kim did.

**Comment by k80bowman** [comment]
@CourtneyChambers77 Don't worry about working on this yet. We'll prioritize it in a future sprint. Thanks!

**Comment by CourtneyChambers77** [comment]
No problem and Thanks

**Comment by GnatalieH** [comment]
@caw310 and @humancompanion-usds this documentation needs Accessibility considerations and may need the below technical details from @andresriveratoro added, unless Matt thinks the technical details are better suited to live in Storybook:

If a VFS engineer wants to use type-ahead, they would have to create their own logic for retrieving results from an API (using the events available on the component to aid) and then pass those results to va-search 

Can we assign @CourtneyChambers77 the Accessibility considerations? Thanks.

**Comment by caw310** [comment]
@GnatalieH Let's wait to draft accessibility considerations until after Staging review.

**Comment by humancompanion-usds** [comment]
I can handle the technical details from Andres when I update this to use the new Component layout. This can move forward.

**Comment by GnatalieH** [comment]
@caw310 I finished adding the examples. Should be OK to close now.

**Comment by GnatalieH** [comment]
[Here is a draft](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/GnatalieH-type-ahead/src/_components/search-input.md) of the Search input documentation.

**Comment by caw310** [comment]
All done so closing.
