### ISSUE TITLE
Update Links code preview on design.va.gov

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#639]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [x] Other

## What is the name?

Typography --> Links code preview

## What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern 
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [x] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

Specs for all link states are listed on #624. This request is to update the code preview with the new specs on [Typography --> Links](See [Typography-->Links](https://design.va.gov/design/typography#links) for example.). 

TL,DR: the active state text link example in Typography should be in regular and not bold typeface to match what we use for most text links on va.gov.

**Comment by GnatalieH** [comment]
@k80bowman and @caw310 can we move this work out of icebox and get it prioritized? It's becoming increasingly important to get the Links documentation published (Allison recently made a request for a new pattern for PDF downloads, and Links covers this), and it's honestly such a small fix I can't imagine it would take a developer that long to do it. I did spend time documenting the link states per Katy's request. Thanks!

**Comment by k80bowman** [comment]
@GnatalieH Sure, I can add it to my list of tickets to consider for our next sprint. Thanks for reminding us!
