### ISSUE TITLE
[Alert] Change alert box close icon from blue to dark gray/black

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/vets-design-system-documentation#661]
# Component Improvement Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name?
`va-alert`

## What is the nature of this update?

I propose changing the color of the close icon in the dismissible alert option from blue to dark gray. The component is shown in Storybook only in the blue alert example but when it's used for the yellow and red alerts, it looks like it should not be blue. Since a close icon is a universal symbol, I propose that it doesn't need to be blue in order for a user to be able to tell if they click it, it will close the dialog. 

## Additional Context

Screenshot from Storybook:
![Screen Shot 2022-03-08 at 12 52 45 PM](https://user-images.githubusercontent.com/97965610/157297270-6020c253-5ea8-477e-b9a1-9e9d886b2993.png)

Proposed color for the close icon so that it looks correct for the other color alerts:
![Screen Shot 2022-03-08 at 12 57 20 PM](https://user-images.githubusercontent.com/97965610/157297493-4073a197-8dfd-4fbb-a5f8-9ec1f68c480b.png)

Instead of:
<img width="920" alt="Screen Shot 2022-03-08 at 1 18 19 PM" src="https://user-images.githubusercontent.com/97965610/157300758-e693ac4d-d286-4807-afc5-55de209b717d.png">

**Comment by GnatalieH** [comment]
I want to add a comment that mentions some issues this ticket this will solve. Currently, the blue circle x icon (seen in the full width alert example in this ticket) can be added with a prop to background only alerts (web components). But the blue icon clashes with the green, red, and yellow background alerts, and teams haven't opted to use it. If we want to help teams implement dismissible background only alerts, while using one icon color between all the alerts, we should move forward with changing this icon to dark gray from the current blue color.

**Comment by k80bowman** [comment]
Work has been completed. https://design.va.gov/components/alert
