### ISSUE TITLE
Drop support for IE 11 or specify what conditions this will be done

### ISSUE THREAD

**Issue by mgifford** [department-of-veterans-affairs/vets-design-system-documentation#668]
The USWDS has defined their [expectations for supported browsers here](https://designsystem.digital.gov/documentation/developers/#browser-support). 

IE usage no longer shows up in the [analytics and is well under 2% usage](https://analytics.usa.gov/).

When can we finally remove this insecure browser from the list of supported browsers? 
https://design.va.gov/documentation/

Which also officially supports the 2% rule: 

> Formation supports older and newer browsers through progressive enhancement. We follow the 2% rule: we support any browser above 2% usage as observed by [analytics.usa.gov](https://analytics.usa.gov/).

Who knew that the **Samsung Internet** was such a popular browser!

**Comment by humancompanion-usds** [comment]
[Work is underway](https://github.com/department-of-veterans-affairs/digital-experience-products/issues/528) to communicate that IE11 is deprecated. We'll use this ticket for the Design System Team to be sure to update the documentation site once that work is complete.

**Comment by bkjohnson** [comment]
Closing since we no longer support IE11. [This issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8852) is the best public documentation I could find. Here is a [slack thread](https://dsva.slack.com/archives/C5HP4GN3F/p1659125110185859) announcing the deprecation.
