### ISSUE TITLE
Audit Sketch VA Pattern library

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#674]
### Steps to complete

1. Compare assets between Sketch library symbols and developed components. 
2. Note in spreadsheet or Mural board where discrepancies occur.

Relates to [#470](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/470).

**Comment by andaleliz** [comment]
FYI I think this is a duplicate of #470

**Comment by caw310** [comment]
Here is a link to the Google sheet with all audit info.  https://docs.google.com/spreadsheets/d/17Fw7flaFcd4CG24E_bBTb4Hq0AEfrT2ivjHqrjuACos/edit?usp=sharing

**Comment by GnatalieH** [comment]
I'd like to close this issue since the audit of Sketch library components compared with developed components work is completed.
