### ISSUE TITLE
View more items in a list

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/vets-design-system-documentation#677]
- [x] Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
An option to view more items in a long list.

This currently exists on the [VAOS facility selection page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request-flow/facility.png). Also see it in action [here (on staging)](https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/va-facility-2).

It's best used in lists where the first items in a long list should be the most relevant results. The less relevant results are hidden until the user clicks "view more" which shows 5 more items.

In VAOS, we show the first 5 results in the list, and hide the rest, by default.

When all items are loaded, the option to view more disappears. There is no option to view fewer.

## Why
 - What evidence do you have that it's needed by multiple services across VA?

This is generally useful for long lists sorted by relevancy because it focuses attention on the most helpful results (hopefully). I'll add specific examples from other teams when I find them.

 - What evidence do you have that it meets the needs of the users of those services?

It's been active on VAOS for more than 2 years.

 - Have you checked that it doesn't already exist in the VA.gov Design System? 

Yes

## Anything else

We can likely pull analytics for the interaction on VAOS, if that will be helpful.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #vsp-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can add your component/pattern to the [Experimental Design section](https://design.va.gov/experimental-design/) of design.va.gov. If you have any questions on how to add your component/pattern to the Experimental section, please reach out to the Design System Team at #vsp-design-system.

**Comment by andaleliz** [comment]
@outerpress, I may have some additional use cases for you:
1. @kevinstachura is working on a similar use case in the claim status tool (visual attached)
2. @rileyorr is using the same component as Kevin's team in the Debt Portal's letter download page redesign ([prototype](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1cjwadz*_gcl_aw*R0NMLjE2NDMwMzc3MjYuQ2owS0NRaUF1Ym1QQmhDeUFSSXNBSldOcGlNMVo1NGR3LW9ZQnBONHktQTBuVHlyVW1MS3RscWZxRldaMmd1ZG0wcmFqSWp0OVl1NjZIQWFBc0NvRUFMd193Y0I.#/pages/149089100/simulate/sitemap?mode=i))
![show-updates](https://user-images.githubusercontent.com/55992116/161272629-d7d7dff2-7301-49ec-986a-d6f574216170.gif)

**Comment by humancompanion-usds** [comment]
This came to DSC on 4/8/22:

### Final Decision
Put VAOS list provider example in Experimental (Peter). Make sure to put guidance around what we discussed. 

We still need to follow up on other pattern.

### Action Items
Peter will begin the Experimental process and ping Natalie if he needs assistance.

I ended up making some design options for this team and they adopted one of them. This isn't yet documented in the Design System and should be. Also, the option that was used may, or may not, be the best option so we need to check back in to see how that team got on with what they decided (how it tested and if it is deployed what the analytics show).

**Comment by outerpress** [comment]
Created pull request #927 for this pattern.

**Comment by humancompanion-usds** [comment]
Pattern is deployed: https://design.va.gov/patterns/show-more-options

Please let us know if/when you have research on the successful use of this pattern. If that research can go into the research repo and get labeled appropriately then we can point to it. Let me know if you need help with that.
