### ISSUE TITLE
Experimental Design (va-text-input)

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/vets-design-system-documentation#680]
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
> Give a brief description of the component or pattern you want to propose.

Add a new optional prop for the (*Required) label text. 

## Why
> Explain why you think this should be added to the VA.gov design system.

Our use case for needing this change is so that we can fully implement Spanish translation in the Check In Experience app. This would be a nice to have pattern for all form field components.

> - What evidence do you have that it's needed by multiple services across VA?

Translation will become an issue for most applications at some point probably.
> - What evidence do you have that it meets the needs of the users of those services?

There are non-natively english speaking users of all services.
> - Have you checked that it doesn't already exist in the VA.gov Design System? 

Yes

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

Here is a PR that I have made with the needed changes and tests.
https://github.com/department-of-veterans-affairs/component-library/pull/337

This is a PR to add a new optional prop for the (*Required) label text. Our use case for needing this change is so that we can fully implement Spanish translation in the Check In Experience app. This would be a nice to have pattern for all form field components, but this PR only covers text input. The current (*Required) text is set to the default when no value is present.

I made the entire previously hardcoded string overridable from the opening parenthesis to the closing parenthesis as well as the *, I figured that this would be better than just the text portion incase a future need to override the whole string comes along. I could see this happening with a custom icon or something similar that another application may need.

The PR also includes new tests for default label and the passed in prop label.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #vsp-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can add your component/pattern to the [Experimental Design section](https://design.va.gov/experimental-design/) of design.va.gov. If you have any questions on how to add your component/pattern to the Experimental section, please reach out to the Design System Team at #vsp-design-system.

**Comment by caw310** [comment]
Here is the follow up form the DSC meeting  on 4/1 where this was discussed. 

Experimental Design Request: Add a new optional prop for the (*Required) label text. 
Final Decision
We will add this to the experimental design section, make a version of the component so text input and date can support content element language attribute to key off that to use appropriate language to pull the string for that language. 

Action Items
Adrian will pass along strings for translations to DST. Tag Carol and Katy. 
DST will make a version of the component so text input and date can support content element language attribute to key off that to use appropriate language to pull the string for that language.

**Comment by bkjohnson** [comment]
`<va-text-input>` now supports dynamic translation as of [`v10.1.0`](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v10.1.0)
