### ISSUE TITLE
[Search] Add Type-ahead component to Sketch pattern library

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#686]
**Description**
The new Type-ahead component and its various states will need to be added to the Sketch library as symbols. 

**Steps to resolve**
1. Convert Type-ahead mockups into symbols that convey default, focus, hover, and active states for the input field, search button, and dropdown menu.
2. Name Type-ahead symbols appropriately so they appear in the correct nested menu within the pattern library file's "Insert" menu.
3. Communicate the update on #design and #design-system Slack channels.

**Comment by GnatalieH** [comment]
@caw310 and @humancompanion-usds I created this ticket to add the Type-ahead component to the Sketch pattern library file, since I noticed there wasn't one already. Just FYI.

**Comment by GnatalieH** [comment]
- [Link to mobile artboard](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/JnGwp3G)
- [Link to desktop artboard](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/09EP0kV)

Ready for your review @humancompanion-usds

**Comment by humancompanion-usds** [comment]
Looks great! 

For the future, I think it would be good to show in the header desktop a variation that has the search box open just to show how it works.
