### ISSUE TITLE
[Link] Poor focus indicator colour contrast on "Send us your feedback" link

### ISSUE THREAD

**Issue by danieldafoe** [department-of-veterans-affairs/vets-design-system-documentation#687]
# Bug Report

* [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I tried tabbing through the web page in order to see if I could tell where focus was at all times. When arriving at the button to send feedback about the web page, I was not able to see the focus indicator very easily.

<img width="260" alt="Yellow focus indicator around a link that is on a yellow background" src="https://user-images.githubusercontent.com/6425338/161356569-049bd475-bcdd-457a-81ad-61d447a30108.png">

## What I expected to happen

I expected to be able to tab through https://design.va.gov and have a clear focus indicator visible at all times.

## Reproducing
* Formation version: I don’t know what a “formation version” is. It would be useful to explain this somewhere in the path of opening an issue. If it helps, I accessed the site on 04/01/2022.
* Device: (e.g. iPhone 8, Macbook) MacBook Pro 13", M1, 2020
* Browser: (e.g. Firefox, IE 11) Google Chrome (Version 99.0.4844.84 (Official Build) (x86_64))

Steps to reproduce:

1. Open https://design.va.gov/
2. Start using only the tab key to move through the actionable elements
3. Observe the contrast of the focus indicator when you arrive at the “Send us your feedback” link

**Comment by humancompanion-usds** [comment]
We dropped the beta banner yesterday because we are no longer in Beta (and have not been for some time). Thus this is no longer an issue.
