### ISSUE TITLE
[Link] Add fa-download icon to design.va.gov > Design > Icons page

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#696]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [ ] Component
- [ ] Pattern
- [ ] Utility
- [x] Other

## What is the nature of this update?

Add Font Awesome download icon to examples on [Icons page](https://design.va.gov/design/icons).

## What problem does this solve?

Since we are suggesting a PDF download link pattern that includes the fa-download icon, we should add it to our Icons examples. 

## Additional Context

@artsymartha68 requested this icon addition in the comments of an older ticket, and @humancompanion-usds approved [moving forward](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-1093058149) with it.

fa-download is already included in the Sketch library.

## Example

![fa-download](https://user-images.githubusercontent.com/88347129/163026687-d28418dc-db92-4a3b-858c-ded54a819f5c.png)

**Comment by caw310** [comment]
Closing as ticket 1800 encompassed work in this issue. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1800

**Comment by humancompanion-usds** [comment]
We added a download icon back when I synced all of the icons in Sketch to guidance.

<img width="978" alt="Screenshot 2023-06-15 at 9 14 58 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/1423dd13-91a1-45ed-b1fe-2cfd9954d819">
