### ISSUE TITLE
[Modal] va-modal Continue variation should use a green button

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#697]
# Bug Report

**NOTE: please hold on fixing this bug until we have coordinated with the Collab. Cycle (Allison and Sean) on their green button usage guidance.**

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

The [Continue modal](https://design.va.gov/storybook/?path=/docs/components-va-modal--continue) (web component) includes Primary and Secondary buttons, but should use a green button instead.

<img width="1048" alt="Screen Shot 2022-04-11 at 4 19 45 PM" src="https://user-images.githubusercontent.com/88347129/163031741-667f5135-898c-4134-8538-2f775ab8873e.png">

## What I expected to happen

I expected the green button to be used instead of the Primary and Secondary buttons. This is specific to the Continue modal.

Steps to reproduce:

1. Navigate [to Storybook](https://design.va.gov/storybook/?path=/docs/components-va-modal--continue).
2. Click the button to open the modal under the Continue story.

**Comment by k80bowman** [comment]
@GnatalieH Should this change be made if we're considering deprecating the green button? See #653

**Comment by k80bowman** [comment]
@GnatalieH Should this change be made if we're considering deprecating the green button? See #653

**Comment by GnatalieH** [comment]
We're deprecating the Wizard instance of the green button, @k80bowman. I suggested to @allison0034 that we consider using the green button on the Continue modal, like we do on the Continue alert. I think the green button can reinforce the mental model of completing a sign in or other action in order to continue with a process.

**Comment by humancompanion-usds** [comment]
We decided yesterday in our stand-up discussion of Green button that we will not in fact use the Green button anywhere but in the [Sign-in or tool prompt Alert](https://design.va.gov/components/alert#sign-in-or-tool-prompt)
