### ISSUE TITLE
Add pattern for Help users to check their eligibility

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/vets-design-system-documentation#702]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [ ] Component
- [x] Pattern
- [ ] Utility
- [ ] Other

## What is the name?

 Confirming important information typically with a checkbox within a form

## What is the nature of this update?

- [x] How to build this component/pattern
- [x] When to use this component/pattern 
- [x] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

## What problem does this solve?

We have seen a few instances come through the collaboration cycle where a user needs to confirm important information while in a form. We also need to consider how this will affect the review page.

## Additional Context

Examples: [First example](https://preview.uxpin.com/2a1ce93f62d447e101cfce3c803d20941fba7203#/pages/141808821/simulate/sitemap?mode=i)
![vh2](https://user-images.githubusercontent.com/72398073/163598298-a10bbb06-fc5e-4f81-9e2c-509238ddbc43.png)
![vh-1](https://user-images.githubusercontent.com/72398073/163598317-b773a7fc-ca07-4734-9333-771798a7d74d.png)
[Another example](https://d.pr/i/tQBvUz)

**Comment by mnorthuis** [comment]
Here is an example used in the Education Rogers STEM application - they are asked a series of questions (in a wizard format which is another convo :-) ) and then they are given the "just to make sure, here's what you said" message. This is an application where they have a high rate of declined applications.  

As a side note, FWIW, the education wizard on the "how to apply" page, was really established as another tool to avoid the high rejection rate by making sure they get to the right form. 

![image](https://user-images.githubusercontent.com/20994159/164766114-2cbdc844-ae44-4bfe-a1af-4ce4ef774340.png)

**Comment by kristenmcconnell** [comment]
[Pre-check-in wireframe example](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/688F5149-95AF-4AD0-8078-1994D093DF72)

**Comment by caw310** [comment]
This item was discussed in the 4/22 DSC meeting. Follow up actions: 

- Capture pattern in forms. If info doesn’t impact flow, but we have wrong info, we have pattern for handling that case
- Add guidance for usage

**Comment by GnatalieH** [comment]
Here is a [flow diagram](https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d/p/A7F989DF-5E3D-4012-AEBB-0922E823E5C8/canvas) I began to capture the info verification process at a high level. I think the next steps will be including examples of confirmation screens, such as the "check answers" pattern we use in the new forms Review page and also an example that is more like the education benefits examples.

**Comment by GnatalieH** [comment]
Closing this ticket because the Pattern documentation work can be handled in [#1109](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1109). Both @humancompanion-usds and @allison0034 have reviewed and signed off on the work done so far.

**Comment by humancompanion-usds** [comment]
We did spawn #1109 to create a new pattern however, I think there is a great example of different pattern in here which [Miki pointed out ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/702#issuecomment-1106726386) for the pattern to Help users to check their eligibility. That pattern only received 3 votes from DSC and VFS Teams but, given that I have a clear example to point to I'm going to repurpose this issue to create that pattern.
