### ISSUE TITLE
VaSelect - Add disabled property

### ISSUE THREAD

**Issue by BrockBeaudry** [department-of-veterans-affairs/vets-design-system-documentation#707]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Component

### What is the name?

va-select

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [ ] Usability guidance
- [ ] Accessibility
- [x] Implementation
- [ ] Research insights
- [ ] Package information

### What problem does this solve?
I would like to make certain form inputs read-only (i.e. disabled) based on user permissions or dates. Currently this does not seem possible with the VaSelect component, as setting the disabled property on the VaSelect itself does not disable the underlying select in the shadow root. 

Allowing the VaSelect to support this standard HTML select feature would make the component more feature complete and developer friendly.

### Additional Context

![va-select-request](https://user-images.githubusercontent.com/7774165/164048266-c231f1c5-443e-42a0-9a18-0616d8f6058a.jpg)

**Comment by k80bowman** [comment]
The [va-select](https://design.va.gov/storybook/?path=/docs/components-va-select--default) component currently has no disabled property or option, which would explain why it doesn't work.

We can definitely take a look and see if this is a feature we'd like to add.

**Comment by BrockBeaudry** [comment]
@k80bowman Thanks for taking a look! This would be a huge help for us.

**Comment by andresriveratoro** [comment]
Adding [related issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/751) here to make it easier to track and update when we have made the decision.

**Comment by humancompanion-usds** [comment]
@BrockBeaudry - Can you explain in greater detail your use case for needing to disable these fields? While we do plan to make it possible, it's strongly discouraged. I'd like to understand the use case so we can write guidance that speaks to why folks are needing to do this today. Thanks!
