### ISSUE TITLE
[Accordion] Accordion using Heading Tags for all List Titles

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/vets-design-system-documentation#727]
Issue:
* Heading `<h1>` through `<h6>` tags are used to wrap the title for accordion buttons
* Conversation should be had about whether heading tags should be used in accordions as they are mainly used to collapse a long list of information and not semantically provide context in regards to area of topic as headings usually do
* Accordions generally have a Heading tag before the grouping occurs
* Having excessive Heading tags on a page can be hurtful to SEO especially the use of multiple h1 tags

**Comment by caw310** [comment]
Closing as this is old and the VADS components have been updated so this should no longer be an issue. IF you are still seeing the issue with the new components, file a new bug.
