### ISSUE TITLE
[Accordion] Fix va-accordion-item test

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#728]
## Description
The "fires a custom event when the location hash matches the accordion id" test for the va-accordion-item component has started to fail intermittently. You can see details about what is going on and what fixes have been tried in this [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1638387283182000).

## Notes
It seems to fail on CI but not locally (or at least it has not failed locally yet). You can see it failed on [this run](https://github.com/department-of-veterans-affairs/component-library/runs/4387812332?check_suite_focus=true#step:8:119).

## Acceptance Criteria
- [ ] Test is fixed and no longer fails intermittently

**Comment by caw310** [comment]
@Andrew565 is this still an issue? Can we close this?

**Comment by Andrew565** [comment]
This is still needed.

**Comment by micahchiang** [comment]
Closing the PR since it's almost 2 years old at this point, but dropping a link to reference it for future work - https://github.com/department-of-veterans-affairs/component-library/pull/246

**Comment by caw310** [comment]
Closing as this is old and the VADS components have been updated so this should no longer be an issue. IF you are still seeing the issue with the new components, file a new bug.
