### ISSUE TITLE
[Icon] Style va-text-input so it doesn't rely on formation.css

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/vets-design-system-documentation#730]
## Issue Description
Currently, the styles implicitly rely on formation.css to show up properly, but that shouldn't be a peer dependency.

**Comment by caw310** [comment]
@Andrew565 @jamigibbs - can we closet this since we will have a new icon web component?

**Comment by Andrew565** [comment]
I think it's safe to close this as we're assuming anyone using the V1 version of va-text-input will automatically have Formation available to them, and anyone using the V3 version will have all V3 styles already encapsulated in the component.
