### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#741]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

I made a bunch of changes to the IA and content of the site and have missed some broken links.

## What I expected to happen

I expected to be able to find them all before committing or that we'd have a link-checker in place, but I didn't and we don't.

## Broken links found thus far
* [x] What's new button in the header
* [x] Code and design files button in the header
* [x] What's new in the footer
* [x] Maturity Scale in What's new
* [x] Drafts file (lists all drafts on the site but isn't linked from anywhere)
* [x] Index page documentation links

More to follow.

**Comment by k80bowman** [comment]
- [Fixed links going to utilities](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/743)
- [Fixed links going to layout](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/739)
- [Fixed homepage links](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pulls?q=is%3Apr+is%3Aclosed#:~:text=1-,fix%20links%20on%20homepage,-%23737%20by%20k80bowman)

**Comment by humancompanion-usds** [comment]
We found more!

![screencapture-drlinkcheck-account-subscriptions-1-projects-1-reports-broken-2022-04-28-15_49_11](https://user-images.githubusercontent.com/52176351/165834106-ced7c31e-94ba-41e3-945d-6455a1251ccb.png)

![screencapture-drlinkcheck-account-subscriptions-1-projects-1-reports-broken-2022-04-28-15_50_16](https://user-images.githubusercontent.com/52176351/165834285-242ebe3b-5473-4183-b8b7-484c2ac77142.png)

![screencapture-drlinkcheck-account-subscriptions-1-projects-1-reports-broken-2022-04-28-15_51_15](https://user-images.githubusercontent.com/52176351/165834390-fd2522aa-75f9-4b4a-bcf1-8a520f971aa2.png)
