### ISSUE TITLE
Indicate TTY numbers in va-telephone

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#775]
# Description

Some phone numbers are only meant to be used with a TTY. The `<va-telephone>` component should have a way of indicating this.

## Context

There was a [slack thread](https://dsva.slack.com/archives/C8E985R32/p1651155317299029) about how to format an `<a>` tag for TTY use. If `<va-telephone>` had this functionality we could recommend that the component be used.

## Questions

- Should the "TTY" text be included in the text inside of the `<a>` tag as well

## Acceptance Criteria

- [ ] `<va-telephone>` compnent indicates that the number is a TTY number in the `aria-label`

**Comment by k80bowman** [comment]
Let's make sure that the issues reported in department-of-veterans-affairs/va.gov-team#40492 and department-of-veterans-affairs/va.gov-team#43969 are addressed as part of the work for this ticket.

**Comment by k80bowman** [comment]
[Guidance on telephone numbers from design.va.gov](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
