### ISSUE TITLE
Improve accessibility of component maturity sidenav indicator on design.va.gov

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#777]
## Description
The component maturity indicator in the sidenav is creating issues for voiceover users. According to Angela Fowler (in a user research session) it would be better if the indicator was semantically after the component name in the sidenav. However, for design purposes, we want it to visually appear before the component name.

## Details
Brooks suggested using flex-order to visually put it in front of the link text but semantically after the link text.

## Acceptance Criteria
- [ ] The component maturity indicator is semantically after the component name but appears visually ahead of it
- [ ] The maturity indicator is a different shape for use, use with caution, and don't use

**Comment by bkjohnson** [comment]
The CSS `order` prop can [change the visual order of an element but leave its order untouched in the DOM](https://developer.mozilla.org/en-US/docs/Web/CSS/order#accessibility_concerns) which normally might be a bad thing. In this case that may be exactly what we want.

With local testing here's what I got:

```diff
diff --git a/src/_includes/_side-nav.html b/src/_includes/_side-nav.html
index fca7c42..bb9e041 100644
--- a/src/_includes/_side-nav.html
+++ b/src/_includes/_side-nav.html
@@ -16,10 +16,11 @@
         {% unless p.index or p.has-parent %}
           {% unless p.draft and (p.url != page.url) %}
             <li class="site-sidenav-list__item {% if is-current == true %} current {%- endif -%}">
-              <a class="site-sidenav-list__link " href="{{site.baseurl}}{{ p.url }}">
+              <a class="site-sidenav-list__link vads-u-display--flex vads-u-align-items--center" href="{{site.baseurl}}{{ p.url }}">
+                {{p.title}}
                 {%- if p.status and (p.layout == "component" or p.layout == "pattern") -%}
                   {%- include _site-side-nav-status.html component-status=p.status -%}
-                {%- endif -%}{{p.title}}
+                {%- endif -%}
                 {%- if p.sub-pages -%}
                   {%- if is-current == true -%}
                 <i aria-hidden="true" class="fas fa-minus site-sidenav-list__handle" role="img"></i>
diff --git a/src/_includes/_site-side-nav-status.html b/src/_includes/_site-side-nav-status.html
index ea2199d..de58396 100644
--- a/src/_includes/_site-side-nav-status.html
+++ b/src/_includes/_site-side-nav-status.html
@@ -1,5 +1,5 @@
 {% for scale in site.data.maturity-scale.scale %}
   {%- if scale.name == include.component-status -%}
-  <i class="fas fa-circle site-sidenav-status site-sidenav-status--{{include.component-status}}"></i>
+  <i class="fas fa-circle site-sidenav-status site-sidenav-status--{{include.component-status}} vads-u-order--first"></i>
   {%- endif -%}
-{% endfor %}
\ No newline at end of file
+{% endfor %}
```

![Showing order is flipped in the inspector compared to rendered page](https://user-images.githubusercontent.com/2008881/165987705-bac71a7e-5111-413a-8c8d-9a95db3300a8.png)

**Comment by humancompanion-usds** [comment]
The shape of the indicator was raised as well in #design during a VA.gov Platform and Apps Weekly Design + Content + Research sync meeting. Different shapes for use, use with caution, don't use would allow those who cannot differentiate the colors to visually identify them.
