### ISSUE TITLE
Login Self-Help 'One Thing per Page' Self-Help Resource

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/vets-design-system-documentation#794]
Check the [design system backlog](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aopen+is%3Aissue+label%3Apattern-new%2Ccomponent-new%2Cpattern-update%2Ccomponent-update) and existing [components](https://design.va.gov/components/) and [patterns](https://design.va.gov/patterns/) to see if your proposal has already been suggested. 

## What
A 'one thing per page' login self-help resource that provides users with the ability to self-triage common login issues.

## Why
A significant portion of VA 411 Call Center issues and Ask VA inquiries are related to login issues. These issues are typically responded to with a templated response, providing users with the appropriate links and steps based on the login used (Id.me, My HeatheVet, etc). The turnaround time for this templated response delivery can span 4 days to a few weeks. By providing a self-help resource to help address common login issues, a reduction in call volume and AVA ticket inquiries can be expected, as well as addressing the user's issues in a more timely manner.

### SalesForce tickets pertaining to Login issues Since March 1, 2021:
 - 25% (18,589) of all VA 411 Call Center tickets
 - 28% (7,117) of all VSP Tier 2 Contact Center

### AVA Tickets from the previous 6 months
 - 2075 tickets under Case Type ‘[VA.gov](http://va.gov/) Account Technical Issue’
 - 841 tickets under Case Sub-Type ‘[VA.gov](http://va.gov/) Account Technical Issue: Cannot Login’

### What evidence do you have that it meets the needs of the users of those services?
We are basing this proposal based on ticket volume and poor performance on the existing [sign-in resources page](https://www.va.gov/resources/signing-in-to-vagov/)

### Have you checked that it doesn't already exist in the VA.gov Design System? 
Yes

## Anything else
- [Confluence document](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2177007712/Login+Self-Service+Data) outlining ticket and inquiry volume as well as feedback data on the existing [sign-in resources page](https://www.va.gov/resources/signing-in-to-vagov/)
- [Github ticket pertaining to the retiring of the wizard](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/399)
- [UK.gov 'one thing per page' recomendation](https://www.gov.uk/service-manual/design/form-structure#start-with-one-thing-per-page)

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system#4-add-your-component-or-pattern-to-the-system). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by caw310** [comment]
Adding a the follow up suggestions from the DSC meeting on 5/6.

- Suggest that you sync with content team and identity team about resources pages to see if there are any immediate steps to deal with issues. 
- Second step, propose or think through working with those teams to identify possible solutions. 
- Encourage you to experiment.
