### ISSUE TITLE
Replace mailto w/snippet that enables subject

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#80]
## This update is for:

- [x] Content style guide (but on Documentation section of design system)

## What is the nature of this update?
![Capture](https://user-images.githubusercontent.com/43381063/57803101-8f1c4280-7725-11e9-96bc-e66da1f18c8b.PNG)

On this page: https://design.va.gov/documentation/content-writers

And this page: https://design.va.gov/documentation/feedback 

Please replace the content style guide mailto link with this snippet that enables subject line: 

Email us at [vawebdesign@va.gov](mailto:vawebdesign@va.gov?subject=Content%20style%20guide).

**Comment by jaredcunha-usds** [comment]
I'm thinking about keeping that in there. Here's why: a mailto link will always try to open an email client. It can't open webmail, such as mail.google.com, and therefore cannot post the subject line automatically. 

Unless you feel that fixing the subject line isn't really necessary…
