### ISSUE TITLE
Updates to Alert Box

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#810]
These are updates needed for the Alert Box component

### Engineering work
- [x] Update the right padding to 2rem (20px)
- [x] Update the left, top and bottom padding to 1.6rem (16px)
- [x] Update left-border to 8px
- [x] Update top border to 8px (full-width variant)
- [x] Update Storybook to include better examples (more text)
- [x] Update icon size to 2.4rem x 2.4rem (24px x 24px)
### Design work
- [ ] Update icon size to 24px x 24px in Sketch
- [ ] Update Sketch to include the padding and border changes listed above

### Engineering work
- [x] Right padding has been changed to 2rem (20px)
- [x] Left, top and bottom padding has been changed to 1.6rem (16px)
- [x] Left-border is 8px
- [x] Top border is 8px for full-width variant
- [x] Icon size is 2.4rem x 2.4rem (24px x 24px)

### Design work
- [ ] Sketch design has updated padding, border width and icon size

**Comment by caw310** [comment]
@andresriveratoro as discussed in standup, Mat says we should follow USWDS. Thanks!

**Comment by andresriveratoro** [comment]
@GnatalieH I've updated the new padding, border and icon size in the Tasks and Acceptance Criteria.

**Comment by GnatalieH** [comment]
Thanks @andresriveratoro. The example you showed looked great in standup.

**Comment by caw310** [comment]
Closing
