### ISSUE TITLE
Audit disabled form states

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#830]
## Description
Audit of the use of disabled form states on VA.gov. Identify as many instances of this component or pattern in use on VA.gov and share with the Design System Team.

## Tasks
- [ ] Work with engineers and the Governance team to find examples of this type of component
- [ ] Add screenshots of component usage examples to a Mural board, including links to sources
- [ ] Gather feedback on findings from the DST (Carol can help schedule a session for this). Questions to ask include:
    - Are any changes to current implementations needed?
    - Are there any variations that can be consolidated?
    - Are there any accessibility considerations that should be taken into account as part of the design?
- [ ] Respond to feedback from DST
- [ ] Add link to Mural board as a comment in this ticket and to the component design ticket if applicable

## Acceptance Criteria
- [ ] Component usage examples have been collected on a Mural board and a link to the board has been added to this ticket
- [ ] Audit findings have been shared with the DST and all feedback has been addressed.

**Comment by k80bowman** [comment]
Hey @allison0034, yes, I found some in the code, but I don't have URLs for where they exist on VA.gov, only where they exist in the code. Is that what you are looking for?

**Comment by allison0034** [comment]
@k80bowman yes, any help in telling me what pages they might be on would be appreciated. I started to poke around and did not see any, I assume they are buried in forms.

**Comment by k80bowman** [comment]
Yes, it seems that they are, which is why I did not try to hunt them down either. Here are the first few I found:

Check-in app
- https://github.com/department-of-veterans-affairs/vets-website/blob/63521dc769c9dd1389fbaec075673b9aa5226f37/src/applications/check-in/components/AppointmentDisplay/CheckInButton.jsx#L21
- https://github.com/department-of-veterans-affairs/vets-website/blob/63521dc769c9dd1389fbaec075673b9aa5226f37/src/applications/check-in/components/pages/Edit/shared/UpdateButton.jsx#L22
- https://github.com/department-of-veterans-affairs/vets-website/blob/5e77237d816e4dda6225ec84f51bfa10e17d3118/src/applications/check-in/components/pages/validate/ValidateDisplay.jsx#L116

Claims Status app
- https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/applications/claims-status/containers/AskVAPage.jsx#L91

Disability Benefits app
- https://github.com/department-of-veterans-affairs/vets-website/blob/39972a9efa1c729ebbfc5d7059cd367e1d4e9f8b/src/applications/disability-benefits/all-claims/components/ArrayField.jsx#L427
- https://github.com/department-of-veterans-affairs/vets-website/blob/39972a9efa1c729ebbfc5d7059cd367e1d4e9f8b/src/applications/disability-benefits/all-claims/components/ArrayField.jsx#L496
- https://github.com/department-of-veterans-affairs/vets-website/blob/2bccfe06302ab0870d04f607b0f7c37751b0e8c7/src/applications/disability-benefits/all-claims/components/SelectArrayItemsWidget.jsx#L177
- https://github.com/department-of-veterans-affairs/vets-website/blob/e625c47428a56dd929c9cec6925b4357dcd19178/src/applications/disability-benefits/disability-rating-calculator/components/RatingRow.jsx#L88

**Comment by humancompanion-usds** [comment]
The audit revealed disabled buttons and we've documented, with DK's help, why that should not be done:
https://design.va.gov/components/button/#do-not-disable-buttons
https://design.va.gov/components/form/#accessibility-considerations-for-all-form-elements

**Comment by GnatalieH** [comment]
@humancompanion-usds should I re-remove the disabled button example from the Sketch library?

**Comment by humancompanion-usds** [comment]
@GnatalieH - No, do not remove the disabled state. While the guidance recommends against it there is still room for a scenario in future where it may be valid. We have decided however to not add the disabled states to other form fields.
