### ISSUE TITLE
Add analytics tracking to va-alert-expandable in vets-website

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/vets-design-system-documentation#833]
## Description
We would like to add analytics for `va-alert-expandable`. This issue will be updated with the correct key-value pairs needed to track analytics after consulting with Brian Martin.

## Details
Modify `analyticsEvents` object in [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/component-library-analytics-setup.js) to include:

```
'va-alert-expandable': [
  {
    action: 'expand',
    event:'int-alert-expandable-expand', 
  },
  {
    action: 'collapse',
    event:'int-alert-expandable-collapse',
  }
```

---
## Tasks
- [ ] Update `analyticsEvents` in [component-library-analytics-setup.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/component-library-analytics-setup.js)

## Acceptance Criteria
- [ ] `va-alert-expandable` analytics tracking is set up in `vets-website`
---

**Comment by andresriveratoro** [comment]
@longmd I've updated this issue with relevant details. Thanks!

**Comment by longmd** [comment]
@andresriveratoro , the PR for this has been approved. Am I good to merge it?

**Comment by caw310** [comment]
Closing this as work has been done.
