### ISSUE TITLE
Bundle react-components using Webpack

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/vets-design-system-documentation#837]
## Description
We would like to bundle our `react-components` package using Webpack. Please make sure that our component-library works in `vets-website` after implementing these changes.

## Details
[Discovery issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33187)
[Discovery pull request](https://github.com/department-of-veterans-affairs/component-library/pull/413)

I ran into issues building `web-components` when using the latest versions of `webpack` and `webpack-cli` in `react-components`. These issues went away when using the same versions used in `core`.

## Acceptance Criteria
- [ ] `react-components` package is bundled using Webpack
    - [ ] Bundle should be in `/dist`
- [ ] `component-library` is updated to use the the `react-components` bundle file
- [ ] `component-library` is tested and working in `vets-website`

**Comment by andresriveratoro** [comment]
I have been unable to get this to work. 

`react-components` was tested locally on a new React project and was working as expected except for the `Banner` component that utilizes the `VaAlert` react binding.

`component-library` was tested locally on a new React project. React components are working with the exception of `Banner`, but web components and React bindings do not work. The issue that I'm encountering happens when calling the `defineCustomElements` function.

![Screen Shot 2022-05-31 at 11 39 20](https://user-images.githubusercontent.com/36863582/171419830-7ee99a81-0048-4388-beda-198c9bffcab5.png)

Possibly related issues: https://github.com/ionic-team/stencil/issues/1882

**Comment by andresriveratoro** [comment]
I've made progress on this issue, but I'm getting syntax errors on IE11. It's working for Chrome, Edge, Firefox and Safari.

**Comment by k80bowman** [comment]
Closing this since we are focusing on deprecating and deleting the React components instead.
