### ISSUE TITLE
Update 2 links: VA.gov Playbook

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vets-design-system-documentation#85]
- [ X] Other

See attached screenshot.

## What is the nature of this update?

- [X] General documentation

## Additional Context

on this page https://www.va.gov/playbook/ - the tiles for the design guide and the editorial guide should point to the new pages on Design.va.gov. 

1/
Currently: https://www.va.gov/playbook/design/
Should go to: https://design.va.gov/design/

2/
Currently: https://www.va.gov/playbook/editorial/
Should go to: https://design.va.gov/content-style-guide/

![image](https://user-images.githubusercontent.com/43381063/58029954-ad9a8900-7aeb-11e9-908b-187ec0c19386.png)

**Comment by jaredcunha-usds** [comment]
Because design.va.gov is a different site, I feel like maybe we just link to it under the resources section or update the content on each of those pages to link out to design.va.gov. In my opinion, I prefer the latter because we can still call out using design.va.gov as _plays_. We just need to update the content within those pages to instruct folks to use design.va.gov.

**Comment by jenniferlee-dsva** [comment]
I prefer linking directly from the tiles because the pages they currently link to are actually outdated vets.gov information which are no longer valid. And anything that's still applicable is covered by the Design System. 

If you take the latter approach described in your comment,  I think those pages would need more than just a link to the Design System and content style guide; the whole page content would need to be updated. 

For example, on the editorial guide page - the content is actually no longer true. For instance, on vets.gov, they used Chicago Manual of Style as their reference guide. On VA.gov, we use AP Style as our reference.  Ppl who land on the playbook page would actually get invalid info for a deprecated guide and site.

**Comment by jenniferlee-dsva** [comment]
I guess another approach would be to remove those tiles altogether and link to the Design System> Design and > content style guide pages in resources. But that seems like it's hiding relevant info.

**Comment by jaredcunha-usds** [comment]
From an interaction standpoint, I'm hesitant to have identical UI behaving inconsistently where some cards link in-site and some link off-site. That's not what I would expect as a user. So I'd rather remove the content from those two pages completely and replace it with a blurb and a button that forwards users to design.va.gov.

**Comment by jaredcunha-usds** [comment]
Closing this is it was decided to move this content design.va.gov.
