### ISSUE TITLE
Generate react-components docs

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/vets-design-system-documentation#856]
## Description
We would like to have automated documentation generation for our react-components package. This will be used on design.va.gov for React component docs similar to what we're doing for our web components.

## Details
- [Repository](https://github.com/reactjs/react-docgen) for react-docgen
- Here's an [article](https://medium.com/@whoisryosuke/automating-react-documentation-using-react-docgen-%EF%B8%8F-3e1b2e2b0c0b) that offers a solution. I tried it and modified it to only read .jsx files, but I kept running into `No suitable component definition found` errors.

![Screen Shot 2022-05-12 at 10.54.50.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/ef11271a-b68c-41d5-935c-b68935be040c)

## Tasks
- [ ] Write a script using [react-docgen](https://github.com/reactjs/react-docgen) that will output a json with a similar structure to our web-component's `component-docs.json`

## Acceptance Criteria
- [ ] `react-components` package generates React component documentation on build

**Comment by jamigibbs** [comment]
I think because we are using web components now on the documentation site, generating react-components docs will no longer be necessary. Closing it for now but please re-open if we feel like it still needs to be investigated.
