### ISSUE TITLE
Add ESLint rule to warn on tel links and suggest telephone component instead

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#864]
## Description

`vets-website` has many files which are using `<a href="tel:...">` links instead of `<va-telephone>`. In order to encourage design system usage, we should add a linting rule that can match on that pattern.

## Details
There are currently 54 files in `vets-website` with the `tel` links, and many of those files have the links more than once.

```
rg "<a href=\"tel" -l | count
```

![Example of files with multiple telephone links](https://user-images.githubusercontent.com/2008881/168158659-1edbbea1-c843-41fe-be4b-92cbb4cfdfef.png)

~One possible exception to this rule is TTY numbers. We have a ticket to allow this indicator to be included in the web component (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/775), but we probably don't want to throw the ESLint warning on [patterns like this](https://github.com/department-of-veterans-affairs/vets-website/blob/165ec43cf231e443ac61712ab1e98c8f71bf1d46/src/applications/enrollment-verification/containers/EnrollmentVerificationIntroPage.jsx#L178-L180) since the web component doesn't support that _right now_.~

## Acceptance Criteria
- [ ] Linting rule in `vets-website` can warn on the `<a href="tel:..."` pattern and guide users to the `<va-telephone>` web component

**Comment by bkjohnson** [comment]
Closed in https://github.com/department-of-veterans-affairs/vets-website/pull/22040. Will be following up to turn the new warnings into errors for changed files on Wednesday 9/7.

**Comment by k80bowman** [comment]
Are you going to post the announcement today?

**Comment by bkjohnson** [comment]
I [did it yesterday](https://dsva.slack.com/archives/C03R5SBELQM/p1661807632071969).

**Comment by k80bowman** [comment]
Perfect, I just missed it. Thank you!
