### ISSUE TITLE
Add prettier/ESLint config for web-components package

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#878]
## Description

_This is based on my local experience with ESLint & prettier plugins installed in my editor_

We have a [root level prettier config](https://github.com/department-of-veterans-affairs/component-library/blob/1593c4f78b8357c0fdeec478d51b8b3486b21c41/.prettierrc.json) in `component-library`, but this doesn't seem to be applying to files in the `web-components` package. However, the `react-components` package does seem capable of making prettier-related changes when a file is saved. It has an [ESLint config](https://github.com/department-of-veterans-affairs/component-library/blob/1593c4f78b8357c0fdeec478d51b8b3486b21c41/packages/react-components/.eslintrc.js), but no prettier config.

I think it would be ideal if we could have top-level ESLint & prettier configs that apply to all subdirectories. If that doesn't work, having the files live at the top level but symlinking them in each of the subpackages might work.

## Acceptance Criteria
- [ ] All `component-library` packages share same ESLint & prettier configs
- [ ] `web-components` package is capable of applying `prettier` config for all team members

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
