### ISSUE TITLE
Use our Process List component on the Contribute to the Design System page

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#888]
In our research we found that the Contribute to the Design System page (https://design.va.gov/about/contributing-to-the-design-system) contains a process with 6 steps. Each step is a bit lengthy and all together they are overwhelming. This issue tracks:

* [x] Use the Process List component on the contribution page to provide a summary of the 6 steps in contributing.
* [x] Create a child page for the 6 steps, as necessary (some steps are short enough to perhaps be within the process list) that the Process List links to in order to provide more information

**Comment by humancompanion-usds** [comment]
Deployed! https://design.va.gov/about/contributing-to-the-design-system/

**Comment by GnatalieH** [comment]
@humancompanion-usds I don't see the Process list component on the Contributing to... page. Am I missing something, or will this change be deployed at a later date? Just wanted to let you know. Thanks.
