### ISSUE TITLE
[Background only alert] - Update Storybook with real-world examples; replace Buttons with Action links for CTAs

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#908]
## Description
[Several Background only alert examples in Storybook](https://design.va.gov/storybook/?path=/docs/components-va-alert--background-only) are using a sign-in button for the CTA, and do not reflect real-world use cases. 

## Examples

![Screen Shot 2022-05-26 at 8.54.28 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/638b44c6-c3fe-473a-988c-7b17c3eaaa91)

## Tasks
- [ ] Update content in Background alerts to match real world use cases
- [ ] Replace button CTA with an Action link wherever necessary

**Comment by caw310** [comment]
DS workshop: Group 1 - Low priority

**Comment by humancompanion-usds** [comment]
While this is a low priority for VFS Teams, it is a high priority for DSC to clean-up alert confusion and this is a part of that. Danielle and I decided yesterday to give some specific uses for background-only alerts with icons. Specifically, we agreed the info style at least should be reserved for highlighting content and be distinct from Featured Content. So before devs start making examples let's all sync up on what those examples should be.

**Comment by humancompanion-usds** [comment]
@caw310 - Given that #1759 is slated for the 6/8 sprint can we do this one at the same time? We'd only be working on the background-only with icon variation.

**Comment by caw310** [comment]
Yes. I'll put this in sprint 29

**Comment by humancompanion-usds** [comment]
@allison0034 - I could use your help here finding good examples of background-only with icon alerts so we can update our examples. Just a list of where to look would be sufficient.

**Comment by humancompanion-usds** [comment]
@allison0034 - Are you saying there are no known instance of background-only Alerts or none that use the icon variation? Because we are actively deprecating the non-icon version. So if all teams are using that instead of the icon then we had better give them a head's up that we're doing this.

**Comment by allison0034** [comment]
@humancompanion-usds I do not have any screen shots of one with the icon, other than the save in forms. I swore there was one for facility locator but I cannot find it. I can log in to staging and see if there are any. Since this is immediate feedback, I may just have to trigger it in a form.

**Comment by allison0034** [comment]
You could potentially use the one on check in...
<img width="376" alt="Screen Shot 2023-06-09 at 10 58 05 AM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/72398073/9fb0a3a0-1f9f-4aed-ac31-8d38c2401977">

Also, do you want me to make the announcement in Mondays meeting that the no icon is being deprecated?

**Comment by humancompanion-usds** [comment]
Okay, I'll start with this one but more examples would be helpful. Let's not announce until we've made the changes in the Design System.

**Comment by caw310** [comment]
Will carry over into the next sprint.

**Comment by humancompanion-usds** [comment]
@caw310 - This issue needs to be assigned to an engineer as it requires a bit more change than I have time to do. Here is what needs to happen:

1. Change the background-only prop to always include the icon and update the docs on that prop appropriately. 
2. Remove the show-icon prompt.
3. Update the info variation example to use the text that Allison provided above in the screenshot.
4. Update the warning and success variations to use the examples I have provided from the Appointments team in the screenshot below.
5. Remove all other stories.

Thanks.

![Screenshot 2023-06-06 at 12.32.13 PM.png](https://images.zenhubusercontent.com/623c98bb27734da1243c0bb5/9b7592ef-dd1f-4827-98eb-2006f35e2846)

**Comment by jamigibbs** [comment]
@humancompanion-usds I need some clarification:

> 2. Rename background-only to Slim to align with USWDS.

Do you mean to just rename the title of our Storybook example for background only to "Slim", or, actually rename the prop itself? There is a left border with [USWDS slim](https://designsystem.digital.gov/components/alert/) that background-only does not have so they seem to be two distinct things. Renaming the prop might also be a breaking change.

**USWDS**
<img width="951" alt="Screenshot 2023-06-29 at 2 28 07 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/8373b1b1-b5b1-42da-a535-582ef92c7294">


**VA**
<img width="1015" alt="Screenshot 2023-06-29 at 2 38 27 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/dec0760c-f72b-4f06-94e5-263a3edc81c7">

**Comment by humancompanion-usds** [comment]
@jamigibbs - We should follow this up with an issue to align our Slim variations in the MVP (sorry, they were aligned in Sketch so I thought that had been communicated). So yes to naming it Slim now and yes in future to adding the missing border in the mvp version of the component.
