### ISSUE TITLE
Language switch design and simplified header and footer for wizard forms

### ISSUE THREAD

**Issue by ytsaoca** [department-of-veterans-affairs/vets-design-system-documentation#919]
Check the [design system backlog](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aopen+is%3Aissue+label%3Apattern-new%2Ccomponent-new%2Cpattern-update%2Ccomponent-update) and existing [components](https://design.va.gov/components/) and [patterns](https://design.va.gov/patterns/) to see if your proposal has already been suggested. 

## What
The Check-in team has been working on a pattern for reviewing, then editing contact information within a workflow/form. We have been syncing with the VA.gov Profile and the accessibility teams throughout our process.

The sitewide content team proved the need of presenting Spanish content.
The check-in team wants to include the function to present the check-in and pre-check-in content in Spanish for the veterans whose native language is Spanish or Tagalog.

## Why

The team implemented [the current toggle design on the COVID page](https://www.va.gov/health-care/covid-19-vaccine/), we assume that the user experiences won't be good because of the information architecture and the identical UI design between the toggle and the back link of the check-in flow.

After speaking with Dene and accessibility, we created 2 design options: (1) [add a subheader with the language toggle](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/m123alz), and (2) notification on the top and a language toggle at the bottom - [Version 1](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/dlpj8JE) and [Version2](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/zxaK1Le).
We also want to simplify the header and footer for the wizard flow to reduce cognitive overload and to release spaces for the kay content.

## Next steps
After attending the Platform Design Office Hour with @humancompanion-usds and @naomimarcussen,  we decided to conduct a user research study in July to validate the assumptions of the current toggle and test the new designs.

You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system#4-add-your-component-or-pattern-to-the-system). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment]
@caw310 - Has this one come to DSC yet? If so, can you add notes. If not, can you follow up with this team? Thanks.

**Comment by caw310** [comment]
@humancompanion-usds I actually don't believe this went to DSC. I think we did not discuss because Danielle had submitted this ticket 2 months before and we had not come to made a determination yet.  https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/667

**Comment by humancompanion-usds** [comment]
Okay. I'm working on Danielle's request to get it into the system soon. Let's get this one scheduled to come to DSC soon also.

**Comment by caw310** [comment]
@ytsaoca , was research done on this? If so would like to hear about the results from research. Would you like to still bring this to DSC?

**Comment by caw310** [comment]
@outerpress , do you have any information on research for this? If we don't hear back we will close this.

**Comment by outerpress** [comment]
@caw310 I think this is the Check-in team, CC @benbrasso-agile6 (FYI @kristenmcconnell)

**Comment by benbrasso-agile6** [comment]
@caw310 here's the [research report](https://github.com/department-of-veterans-affairs/va.gov-team/bl%E2%89%88ob/master/products/health-care/checkin/research/veteran-facing/Spanish/research-findings.md). 

However, check in still uses the [pattern on the COVID page](https://www.va.gov/health-care/covid-19-vaccine/). Check in gets very, very, very little non english speakers and/or users actually using the toggle. At least, the last time I checked. 

If you want us to come to DSC, that's fine. @ytsaoca

**Comment by humancompanion-usds** [comment]
We have added Language toggle to guidance and we plan to build this component: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2583
