### ISSUE TITLE
Banner component SHOULD be recallable when dismissed

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/vets-design-system-documentation#920]
## Description

Currently our `<va-banner>` disappears forever when dismissed:

<details>

<summary>GIF of dismissing a banner</summary>

![Banner on staging.va.gov is dismissed and remains totally removed upon refresh, with no UI to bring it back](https://user-images.githubusercontent.com/2008881/171455268-cfff991f-f3e4-4be5-a8ad-bf7f953f44b5.gif)

</details>

Good interaction design would allow the dismissed banner to be recalled.

## Details
- [Slack thread with Josh Kim](https://dsva.slack.com/archives/C8E985R32/p1654100141446649) discussing recalling dismissed banners

## Acceptance Criteria
- [ ] Banner can be recalled again once dismissed

**Comment by caw310** [comment]
DS workshop: Group 1 - Medium priority

**Comment by FranECross** [comment]
@micahchiang @caw310 This ticket is attached to a Public Websites epic, and is the only ticket still open. Do you know if this is still work planned to be done, but just not a priority yet? Thanks. cc @laflannery @jilladams

**Comment by jilladams** [comment]
I'd vote we close this AND the epic, given that we've all figured out guidance around permanently dismissed banners, Editors expect that, KBs document it, etc. I'm gonna go ahead and close the epic, but: we can always make new tickets if that changes.
