### ISSUE TITLE
Va-Select component does not visually update on programmatic data change

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/vets-design-system-documentation#932]
# Bug Report
We are creating a custom component for address input in a form that consists of Va-Checkbox, Va-Text-Input & Va-Select components. The checkbox allows the user to autofill the address data with data entered in a previous part of the form. When the checkbox is selected, the data does populate and the Va-Text-Inputs update their value. The Va-Select does take and process the data correctly (which you can see in both the form props and when inspecting the element with chrome dev tools), but the input visually never updates with what should be the newly populated value. The same is true of clearing the data. If we deselect the checkbox and the field clear, the select does not visually clear, even though the field value is nulled out. 

## What happened
**User interaction:** 
https://user-images.githubusercontent.com/6738544/172627925-0db66551-df87-4749-a0cf-63cac70dbbcf.mov

**Field props showing values before and after checkbox selection:** 
![Screen Shot 2022-06-08 at 9 27 47 AM](https://user-images.githubusercontent.com/6738544/172628541-18b3b76f-f368-44d7-978b-211813a9a753.png)

**Element inspection with checkbox selected:** 
![Screen Shot 2022-06-08 at 9 29 49 AM](https://user-images.githubusercontent.com/6738544/172629054-646bb49f-79c7-4fc2-a2bc-fcd457d44823.png)

## What I expected to happen
when the component receives a data update, regardless of whether it is programmatic or user selected that the update will visually occur. 

## Reproducing
- Formation version: Unknown
- Device: MacBook Pro
- Browser: Chrome 102

**Steps to reproduce:**

1. Pull down [Current Branch](https://github.com/department-of-veterans-affairs/vets-website/tree/longmd-41869-add-caregiver-address-autofill).
2. Run locally and navigate to [Caregivers Application](http://localhost:3002/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg).
3. When form asks if you want to apply for benefits as a Primary Family Caregiver, select yes.
4. Fill out data related to the Primary Family Caregiver. This address form is on page 2 of that chapter.

**Comment by andresriveratoro** [comment]
Possible fix:
```diff
diff --git a/packages/web-components/src/components/va-select/va-select.tsx b/packages/web-components/src/components/va-select/va-select.tsx
index f7a113ab..1ebbf26b 100644
--- a/packages/web-components/src/components/va-select/va-select.tsx
+++ b/packages/web-components/src/components/va-select/va-select.tsx
@@ -8,6 +8,7 @@ import {
   Prop,
   State,
   h,
+  Watch,
 } from '@stencil/core';
 import i18next from 'i18next';
 import { getSlottedNodes } from '../../utils/utils';
@@ -128,6 +129,11 @@ export class VaSelect {
     );
   }
 
+  @Watch('value')
+  handleValueChange() {
+    this.populateOptions();
+  }
+
   render() {
     const { error, label, required, name } = this;
 
```
