### ISSUE TITLE
Update/addition to link collection pattern

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#943]
## What
In My VA, we use a collection of links and icons to highlight links that can take users to content that is related to an overall topic. The links themselves are not necessarily related to each other.  For example, under health care, a user has a health-care related set of links to this content:
- secure messaging
- manage Rx
- view test results
- etc

## Why
The My VA collection of links provides a way to have a collection without a heading, container, and with more lightweight borders than some of the examples on [the collection page](https://design.va.gov/components/link/collection). This pattern is useful for link-heavy pages such as My VA, that also have many headings to delineate sections. The icons and borders help differentiate the links in the collection from the links in the cards and alerts on the page.

This also offers different placement opportunities than the current guidance that suggestions the link collection be placed at the bottom of the page. Our link collection is used to provide the links in the context of a section of the page without distracting from the main task or call to action.

**What evidence do you have that it's needed by multiple services across VA?**
I don't have any strong evidence that it's NEEDED, but I know there are many use cases on content pages where we need to surface a variety of links to Veterans in a way that is meaningful, and easy to find, but not distracting from the main body.

**What evidence do you have that it meets the needs of the users of those services?**
I've heard many Veterans complain about a wall of links and struggling to parse through content heavy pages on VA.gov.

**Have you checked that it doesn't already exist in the VA.gov Design System?** 
This particular pattern doesn't exist but there are variations on [the collection page](https://design.va.gov/components/link/collection)

## Anything else
**Mock-ups**
[My VA Desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/AxrLJlM)
[My VA Mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/agw4D9Z)

**Comment by andaleliz** [comment]
I got it, thanks @caw310 ! Sounds like the council determined this can't be something reviewed async. See you tomorrow :)

**Comment by humancompanion-usds** [comment]
In DSC we decided to bring this component into the Link - Collection and to document the uses of icons. We also set out on an Icon inventory audit to improve our Iconography guidelines.

**Comment by caw310** [comment]
DS workshop - Group 1 identified this as low priority.

**Comment by humancompanion-usds** [comment]
Allison completed the icon audit: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1657909827854/aa73720ad01c07977213daa48d510906f1e912ed?sender=u9ae4d29a0ed5c3d2753a7824 (I can't get to the Share link for this one but Natalie is the owner and should be able to open up access). She included some recommendations. I will file a new issue to get those into the system. 

The next steps here are for @seanasewell to talk to the Aut. Exp. team about where they landed on icon usage in Profile and make sure there is not overlap with existing icon usage elsewhere as seen in the audit. If there is, and the icons are not used in the same or a similar way, then we may need to do some conflict resolution. But let's figure out where they are first.

**Comment by GnatalieH** [comment]
@humancompanion-usds I just invited you to the Mural board as an editor. Please let me know if you have any access issues. Thx!

**Comment by andaleliz** [comment]
Hi all, just checking in on this. I see @seanasewell has the next steps of connecting with my team to discuss icon usage in Profile. I don't believe we have have any icons in Profile outside of alerts that are already part of the design system component. @cgednalske can you think of any?

We'd be happy to connect with Sean if needed but it sounds like perhaps the work on this can move forward?

**Comment by cgednalske** [comment]
@andaleliz -- Account settings has some icons conveying the different authentication steps have been completed ([Sketch file](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/Gm030dY)). Are those already following a design system pattern? Other than that I can't think of any others.

**Comment by humancompanion-usds** [comment]
@andaleliz - Yes, I'm aware that you are using icons that are not yet defined in the Design System for their specific use. Unfortunately, so are facility pages. For example:

![190501796-1301ed0f-ac06-458b-8a45-be0bb5c91670](https://user-images.githubusercontent.com/52176351/191040849-d9f63759-5fce-4ad0-b767-e32eca317e45.png)

What I was hoping to gather from your team is a list of each icon you intend to use, it's FontAwesome name, and how/when you will use it. I'll start the list and then just please correct any misinterpretation and add any icons I've missed:

### Profile icon usage
* Suitcase - <img width="18" alt="image" src="https://user-images.githubusercontent.com/52176351/191046246-e8954b5a-b3de-417a-9e82-e993887d26c0.png"> - Travel reimbursement 
* File medical - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191047086-11b54281-ec35-457e-ae99-f2ae041a7889.png"> - VA medical records and lab & test results
* Clipboard check - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191049270-337e8ad7-de3d-4187-bc12-91edaf13c220.png"> - Claims and appeals
* Messages - <img width="22" alt="image" src="https://user-images.githubusercontent.com/52176351/191049594-efd90725-2197-4b69-a6b7-59f1d9664d3a.png"> - Messages
  * Profile uses the solid, facilities the outline style.
* Prescription bottle - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191049825-b8f4647a-6cda-4537-8386-f69dc1e325bf.png"> - Prescriptions
* File invoice dollar - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191053289-f6e16c7e-baf9-4c4a-9135-4e3cd9c7d218.png"> - Debt
* Dollar - <img width="11" alt="image" src="https://user-images.githubusercontent.com/52176351/191055153-9d67b1b3-1b63-4878-965d-3d656a34768b.png"> - Direct deposit
* User check - <img width="23" alt="image" src="https://user-images.githubusercontent.com/52176351/191055294-f059ad0e-1ccf-45ee-b1ac-fd32ee25c342.png"> - Payment history
* Calendar - <img width="16" alt="image" src="https://user-images.githubusercontent.com/52176351/191055441-928ffbe2-1bf4-444c-95c3-bd94ff434c43.png"> - Appointments

### Overlaps
We do have a potential overlap in usage, which can be [seen in the audit](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1657909827854/aa73720ad01c07977213daa48d510906f1e912ed?sender=u9ae4d29a0ed5c3d2753a7824).

* Briefcases for Health, Careers, and Travel reimbursement. This seems fine to me. Health is using the medical bag icon, careers the briefcase, and travel the suitcase. Thus they are each distinct types of cases. If you wanted to move to a plane, bus, train, or car, some other symbol of travel, that might help avoid any confusion here.

If that list above is correct then we can get these icons into the System and be on our way to adding this component.

**Comment by allison0034** [comment]
Hi @andaleliz @cgednalske @aagosto90 (not sure we have the new notification icons either), Matt asked me to follow up on this. We need to document the following for each of your icons:

1. List of each icon you intend to use
2. It's FontAwesome name
3. How/when you will use it

Matt started the list below and noted an overlap.

 ### Profile icon usage
* Suitcase - <img width="18" alt="image" src="https://user-images.githubusercontent.com/52176351/191046246-e8954b5a-b3de-417a-9e82-e993887d26c0.png"> - Travel reimbursement 
* File medical - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191047086-11b54281-ec35-457e-ae99-f2ae041a7889.png"> - VA medical records and lab & test results
* Clipboard check - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191049270-337e8ad7-de3d-4187-bc12-91edaf13c220.png"> - Claims and appeals
* Messages - <img width="22" alt="image" src="https://user-images.githubusercontent.com/52176351/191049594-efd90725-2197-4b69-a6b7-59f1d9664d3a.png"> - Messages
  * Profile uses the solid, facilities the outline style.
* Prescription bottle - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191049825-b8f4647a-6cda-4537-8386-f69dc1e325bf.png"> - Prescriptions
* File invoice dollar - <img width="14" alt="image" src="https://user-images.githubusercontent.com/52176351/191053289-f6e16c7e-baf9-4c4a-9135-4e3cd9c7d218.png"> - Debt
* Dollar - <img width="11" alt="image" src="https://user-images.githubusercontent.com/52176351/191055153-9d67b1b3-1b63-4878-965d-3d656a34768b.png"> - Direct deposit
* User check - <img width="23" alt="image" src="https://user-images.githubusercontent.com/52176351/191055294-f059ad0e-1ccf-45ee-b1ac-fd32ee25c342.png"> - Payment history
* Calendar - <img width="16" alt="image" src="https://user-images.githubusercontent.com/52176351/191055441-928ffbe2-1bf4-444c-95c3-bd94ff434c43.png"> - Appointments
  * Facilities uses an outline style.

### Overlaps
We do have a potential overlap in usage, which can be [seen in the audit](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1657909827854/aa73720ad01c07977213daa48d510906f1e912ed?sender=u9ae4d29a0ed5c3d2753a7824).

* Briefcases for Health, Careers, and Travel reimbursement. This seems fine to me. Health is using the medical bag icon, careers the briefcase, and travel the suitcase. Thus they are each distinct types of cases. If you wanted to move to a plane, bus, train, or car, some other symbol of travel, that might help avoid any confusion here.

**Comment by andaleliz** [comment]
Hi @allison0034 and @humancompanion-usds sorry for the delay on this. I think it slipped off the radar since it's not assigned to us and therefore doesn't show up in our sprints. I'll work on this and get the info back to you.

**Comment by aagosto90** [comment]
@allison0034 @andaleliz @humancompanion-usds 
**Icons for My VA notifications:**
- Exclamation - ![Screen Shot 2022-10-07 at 11 42 49 AM](https://user-images.githubusercontent.com/97965610/194594791-2a171c26-ecbc-43e5-98b3-16b605b9c1b5.png) - Important/urgent notifications requiring user action
- Info - ![Screen Shot 2022-10-07 at 11 42 58 AM](https://user-images.githubusercontent.com/97965610/194594881-d846495a-c5ec-4be2-bd11-e67c5e272028.png) - Informational notifications not requiring user action

All of the icons on My VA in our links that this ticket refers to have already been outlined by Matt. The only exception is we are currently working on adding and "Education and training" section to My VA and we'll need icons for that. Here's what we currently have in Sketch but we can change them according to guidance from platform especially since a couple are being used for other things on the page. We're still in the early stages of the collab cycle for this work so definitely nothing set in stone yet.
- Graduation cap - ![Screen Shot 2022-10-07 at 12 11 49 PM](https://user-images.githubusercontent.com/97965610/194600005-94659521-db94-439d-8d2a-69ab5a5ef7cd.png) - Learn how to apply for VA education and benefits
- Clipboard list - ![Screen Shot 2022-10-07 at 12 11 59 PM](https://user-images.githubusercontent.com/97965610/194600274-4698ef69-4066-4648-a7b8-f44c1fdd9d6b.png) - Compare GI benefits by school
- Dollar sign - ![Screen Shot 2022-10-07 at 12 17 14 PM](https://user-images.githubusercontent.com/97965610/194600510-2df4212a-4c0a-4b26-8086-ba2c3acfa495.png) - Check your GI bill statement of benefits

![Screen Shot 2022-10-07 at 11 55 32 AM](https://user-images.githubusercontent.com/97965610/194596821-be5c4431-7c96-480c-8f1f-330a41949ca3.png)

We also currently have some icons at the bottom of My VA for VA benefits but we anticipate **eliminating this section** as part of the [My VA audit work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601) we've started the collab cycle for. Since they are still currently on the site I'll include them. Those are:
- Briefcase medical - ![Screen Shot 2022-10-07 at 12 18 57 PM](https://user-images.githubusercontent.com/97965610/194600933-a215cea2-7d4f-4848-9039-3853fc0c92e1.png) - Health care
- File alt - ![Screen Shot 2022-10-07 at 12 19 10 PM](https://user-images.githubusercontent.com/97965610/194601077-c104e10e-e724-41d4-8168-ea7fd64a6d37.png) - Disability compensation
- Graduation cap - ![Screen Shot 2022-10-07 at 12 19 16 PM](https://user-images.githubusercontent.com/97965610/194601145-bdffa862-6389-4fc5-823e-65b81a0820ce.png) - Education and training

Let me know if there's anything else I can do to help!

**Comment by andaleliz** [comment]
Thanks for covering the My VA icons @aagosto90!

Outside of the icons in the design system alert components, profile only uses `fa-check` on the account security page to indicate when a step has been completed.

Both My VA and Profile use `chevron-right` at the end of the disability rating link in the "name tag" component, which sits between the site header and main content area for both products. I don't think this is part of a specific DS pattern.

You can see examples of both in this screenshot:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/55992116/195199461-20804381-9977-442f-b11c-d6a4914d2202.png">

**Comment by GnatalieH** [comment]
@andaleliz what happens when you click "40% service connected"? We going to document some guidelines around the `chevron-right` icon usage because it relates to #1421 (which @joshkimux recently created). Thanks.

**Comment by andaleliz** [comment]
@GnatalieH It links to the disability rating tool. We [published some docs about the nametag](https://github.com/department-of-veterans-affairs/va.gov-team/blob/48d00f333b430ff2dff34f140fdfe8469188026c/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md) recently, hopefully they're helpful. Lmk if you need more info!

**Comment by humancompanion-usds** [comment]
Icons are updated here: https://design.va.gov/foundation/icons
Link - Collection is updated here: https://design.va.gov/components/link/collection
