### ISSUE TITLE
Update Experimental Design description and process 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#950]
### Duplicate check

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### This update is for:

Other

### What is the name?

Experimental design process

### What is the nature of this update?

- [ ] How to build this component/pattern
- [ ] When to use this component/pattern
- [ ] When to use something else
- [X] Usability guidance
- [ ] Accessibility
- [ ] Implementation
- [ ] Research insights
- [ ] Package information

### What problem does this solve?

The experimental design process and description needs to be updated with the feedback we have received to make the process better for contributors and more streamlined.

**Comment by humancompanion-usds** [comment]
@caw310 - I feel like I just did this by revamping the Guidance section:
https://design.va.gov/about/contributing-to-the-design-system/

Can you review those changes and, if there are particular pieces of feedback that we have not addressed, update this issue to call those out?
