### ISSUE TITLE
Required text inputs should not have red border by default

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/vets-design-system-documentation#956]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
Our text input web components now have a red border by default when the required prop is added.

## What I expected to happen
The red border should not appear by default

## Reproducing
Steps to reproduce:
- You can see this in storybook

It looks like it may have been added with this [PR](https://github.com/department-of-veterans-affairs/component-library/pull/426).

**Comment by k80bowman** [comment]
Additionally, as part of this ticket, please update the red border to be 4px to match [USWDS](https://designsystem.digital.gov/components/text-input/).

**Comment by andresriveratoro** [comment]
This looks like it's a combination of `required` and the [:invalid ](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid)pseudo-class causing the red border to appear when an input is empty. This behavior can be seen here in the [examples](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid#examples). Notice the difference between the URL input and email input.

**Comment by andresriveratoro** [comment]
![Screen Shot 2022-06-16 at 16 52 47](https://user-images.githubusercontent.com/36863582/174162588-f76d0997-b6eb-4b68-8be0-2d627da99992.png)
