### ISSUE TITLE
File Input - Audit

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#963]
## Description
Audit of File Input. Identify as many instances of this component or pattern in use on VA.gov and share with the Design System Team.

## Tasks
- [ ] Work with engineers and the Governance team to find examples of this type of component
- [ ] Add screenshots of component usage examples to a Mural board, including links to sources
- [ ] Gather feedback on findings from the DST (Carol can help schedule a session for this). Questions to ask include:
    - Are any changes to current implementations needed?
    - Are there any variations that can be consolidated?
    - Are there any accessibility considerations that should be taken into account as part of the design?
- [ ] Respond to feedback from DST
- [ ] Add link to Mural board as a comment in this ticket and to the component design ticket if applicable

## Acceptance Criteria
- [ ] Component usage examples have been collected on a Mural board and a link to the board has been added to this ticket
- [ ] Audit findings have been shared with the DST and all feedback has been addressed.

**Comment by GnatalieH** [comment]
Here is the [Mural board audit](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1657212587413/e9c04daa4f509253154b2a1aa5dc6bbead180413?sender=u851998f98038e0f1e2da4592) for FileInput. WIP.

**Comment by GnatalieH** [comment]
Suggestions made in meeting with @humancompanion-usds this morning:

**FileInput - Component**
Focus on:
- Content considerations for upload button text specificity (Upload death certificate vs. Upload, for example)
- Header vs. label for upload button (*required instance, too)
- Margin spacing between headers/labels and the upload button
- Guidelines for button style (Primary or Secondary, width)
- Error state design (look at USWDS examples)

FileInput - Pattern
Focus on:
- Plain language around file type and size requirements
- Placement of "hint" text in relation to upload button
- Interaction design of uploading multiple files vs. one file
- Hierarchy of upload button or buttons in relation to page content
- More?
