### ISSUE TITLE
File Input web component - Documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#968]
## Description
Add or update documentation and guidance for File Input on design.va.gov. When adding a new component, use the [component documentation template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_components/template.md).

## Details
Existing documentation on File Upload - https://design.va.gov/patterns/forms/file-upload
[add links to any design documents]
[add link to Sketch component page]

Be sure to use the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option. If this is a new component that has not yet gone through Staging Review, use the "Use with Caution: Candidate" label.

## Tasks
- [ ] Write or update component documentation for design.va.gov
- [ ] Coordinate with accessibility specialist to create or update accessibility guidance
- [ ] Request documentation draft review
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Component documentation is published on design.va.gov

**Comment by jamigibbs** [comment]
@humancompanion-usds @GnatalieH I've created a draft PR for the `va-file-input` component documentation here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1117

I've added the storybook examples, code usage, and a few other updates based on [this template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_components/template.md) but I think there might still be a few gaps related to design and UX feedback. I'm not sure if there is anything additional we want to add related to that.
